### ISSUE TITLE
Duckdns | Unable to determine zone identifier for {0} using zone names: {1} 

### ISSUE THREAD

**Issue by thibleroy** [certbot/certbot#10049]
Hello, I have an issue regarding certbot x duckdns x letsencrypt x ovh (dns challenge)

## I ran this command and it produced this output:
`sudo docker run -it --rm --name certbot -v "/Users/thibleroy/dev/certbot/etc-letsencrypt:/etc/letsencrypt" -v "/Users/thibleroy/dev/certbot/ovh:/secrets" -v "/Users/thibleroy/dev/certbot/var-letsencrypt:/var/lib/letsencrypt" -v "/Users/thibleroy/dev/certbot/logs:/var/log/letsencrypt" certbot/dns-ovh:v2.6.0 certonly --dns-ovh --dns-ovh-credentials /secrets/ovh.ini --dns-ovh-propagation-seconds 60 -d "thibleroy.duckdns.org" -v
Password:
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-ovh, Installer None
Requesting a certificate for thibleroy.duckdns.org
Performing the following challenges:
dns-01 challenge for thibleroy.duckdns.org
Cleaning up challenges
Unable to determine zone identifier for thibleroy.duckdns.org using zone names: ['thibleroy.duckdns.org', 'duckdns.org', 'org']
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.`

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
Log

2024-11-08 17:13:01,789:DEBUG:certbot._internal.main:certbot version: 2.11.0
2024-11-08 17:13:01,789:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-11-08 17:13:01,789:DEBUG:certbot._internal.main:Arguments: ['--dns-ovh', '--dns-ovh-credentials', '/secrets/ovh.ini', '--dns-ovh-propagation-seconds', '60', '-d', 'thibleroy.duckdns.org', '-v']
2024-11-08 17:13:01,789:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-ovh,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-11-08 17:13:01,907:DEBUG:certbot._internal.log:Root logging level set at 20
2024-11-08 17:13:01,910:DEBUG:certbot._internal.plugins.selection:Requested authenticator dns-ovh and installer None
2024-11-08 17:13:01,910:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * dns-ovh
Description: Obtain certificates using a DNS TXT record (if you are using OVH for DNS).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='dns-ovh', value='certbot_dns_ovh._internal.dns_ovh:Authenticator', group='certbot.plugins')
Initialized: <certbot_dns_ovh._internal.dns_ovh.Authenticator object at 0x7fc88ae32150>
Prep: True
2024-11-08 17:13:01,911:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_ovh._internal.dns_ovh.Authenticator object at 0x7fc88ae32150> and installer None
2024-11-08 17:13:01,911:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator dns-ovh, Installer None
2024-11-08 17:13:01,960:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2038242537', new_authzr_uri=None, terms_of_service=None), 0869e71bdf97f69352f4c04137339478, Meta(creation_dt=datetime.datetime(2024, 11, 4, 17, 32, 52, tzinfo=<UTC>), creation_host='4056a32ff673', register_to_eff=None))>
2024-11-08 17:13:01,961:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-11-08 17:13:01,963:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-11-08 17:13:02,403:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 746
2024-11-08 17:13:02,405:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 08 Nov 2024 17:13:02 GMT
Content-Type: application/json
Content-Length: 746
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "iYJYrExXjjE": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-11-08 17:13:02,409:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for thibleroy.duckdns.org
2024-11-08 17:13:02,415:DEBUG:acme.client:Requesting fresh nonce
2024-11-08 17:13:02,416:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-11-08 17:13:02,565:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-11-08 17:13:02,567:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 08 Nov 2024 17:13:02 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: SEOe4WhpzuIIuqWI7kBEIOwGDzUyLW6AXITUMPs5J4x8Y7xB9EE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

2024-11-08 17:13:02,570:DEBUG:acme.client:Storing nonce: SEOe4WhpzuIIuqWI7kBEIOwGDzUyLW6AXITUMPs5J4x8Y7xB9EE
2024-11-08 17:13:02,571:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "thibleroy.duckdns.org"\n    }\n  ]\n}'
2024-11-08 17:13:02,576:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjAzODI0MjUzNyIsICJub25jZSI6ICJTRU9lNFdocHp1SUl1cVdJN2tCRUlPd0dEelV5TFc2QVhJVFVNUHM1SjR4OFk3eEI5RUUiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "TM6U22L6X6jKdsdt60UAll6ktK5UZ6CKIDYXNk2kIQ9DOCDX8HfaNrjM1pipZYHqaZw--NALBwzAFuShr58Onk_y398SCd80qObdidxpUDdTgEBL-rXwxR0-FMU-vvGIpZ9RAMlX_CwWrl6aW3QvzW6xdcieZe1DZb9_yUMeTDeahwZyC0kyq8uyMgwwik30gMkuuYEMP-ExzYoAdePa11WFecyhdqBKqqguBJ79-enSwGaIzEaZjwO7490ZID1oV2Y_1vlTHpVWSSZw5TFGKR5WGKr0XfeCoCo2y0gl6DtrJV47Z1Wa3Tb_PR2k6Q2XHU3FtGJt_Osa9j0Of0SbfQ",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInRoaWJsZXJveS5kdWNrZG5zLm9yZyIKICAgIH0KICBdCn0"
}
2024-11-08 17:13:02,983:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 347
2024-11-08 17:13:02,985:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Fri, 08 Nov 2024 17:13:02 GMT
Content-Type: application/json
Content-Length: 347
Connection: keep-alive
Boulder-Requester: 2038242537
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/2038242537/321218960837
Replay-Nonce: SEOe4Whpcik3l-sjlbd3y_M6myLovv2d5BH7tQUoUhvgfKBHCq0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2024-11-11T17:32:55Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "thibleroy.duckdns.org"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/425568884857"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/2038242537/321218960837"
}
2024-11-08 17:13:02,986:DEBUG:acme.client:Storing nonce: SEOe4Whpcik3l-sjlbd3y_M6myLovv2d5BH7tQUoUhvgfKBHCq0
2024-11-08 17:13:02,987:DEBUG:acme.client:JWS payload:
b''
2024-11-08 17:13:02,989:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/425568884857:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjAzODI0MjUzNyIsICJub25jZSI6ICJTRU9lNFdocGNpazNsLXNqbGJkM3lfTTZteUxvdnYyZDVCSDd0UVVvVWh2Z2ZLQkhDcTAiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzQyNTU2ODg4NDg1NyJ9",
  "signature": "JdatFe7YtWYJ9cuvwUEjcGwph3exzRJ7aAr3REiuGXU0Vl2ZIedBC6vw6aGCtOMy1ZamKgmL3kDUUxDG4zD5nFGy8ePmIve8gDlTa9dMEvUEhkBXuHoT0LqJc2Wg3v3BENlygyim2YWmlX_HMiMqVUGlgleuW56Z5zUNfYCQ12ovDMqOAC6eF65yriiLKhGf_5DK7hIYbHkaE-yS9-2VA9arEJpIG3JQpH3PQaxZvb4BshO9L8kvTpTImMrg5A2WnxAS6o5Pcg5ClYZ6-gm8ZD2Z6k1ZLpgzK-n8wBKFi4z54gPrrXpfhy_tCeIe-cGhWaFMkAYr-Q0ww6QB2UUcQg",
  "payload": ""
}
2024-11-08 17:13:03,188:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/425568884857 HTTP/1.1" 200 805
2024-11-08 17:13:03,190:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Fri, 08 Nov 2024 17:13:03 GMT
Content-Type: application/json
Content-Length: 805
Connection: keep-alive
Boulder-Requester: 2038242537
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: qZ7aiiUHzoWhxti7oIqmYr6fFPx-AS_VXK9tdAw9ryGIbTXwIs8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "thibleroy.duckdns.org"
  },
  "status": "pending",
  "expires": "2024-11-11T17:32:55Z",
  "challenges": [
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/425568884857/3UEhZA",
      "status": "pending",
      "token": "XJ7tdQ9UshclNwOI7L1ohNKE81WyU6Ng-DjS7ZrM5vs"
    },
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/425568884857/6zvJxQ",
      "status": "pending",
      "token": "XJ7tdQ9UshclNwOI7L1ohNKE81WyU6Ng-DjS7ZrM5vs"
    },
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/425568884857/fl0ZEQ",
      "status": "pending",
      "token": "XJ7tdQ9UshclNwOI7L1ohNKE81WyU6Ng-DjS7ZrM5vs"
    }
  ]
}
2024-11-08 17:13:03,192:DEBUG:acme.client:Storing nonce: qZ7aiiUHzoWhxti7oIqmYr6fFPx-AS_VXK9tdAw9ryGIbTXwIs8
2024-11-08 17:13:03,194:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-11-08 17:13:03,196:INFO:certbot._internal.auth_handler:dns-01 challenge for thibleroy.duckdns.org
2024-11-08 17:13:03,258:DEBUG:root:Parameter resolve_zone_name is not set, use tldextract to guess the zone name from known TLDs
2024-11-08 17:13:03,258:DEBUG:filelock:Attempting to acquire lock 140499298842144 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:03,259:DEBUG:filelock:Lock 140499298842144 acquired on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:03,259:DEBUG:filelock:Attempting to acquire lock 140499298840992 on /root/.lexicon_tld_set/urls/62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2024-11-08 17:13:03,260:DEBUG:filelock:Lock 140499298840992 acquired on /root/.lexicon_tld_set/urls/62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2024-11-08 17:13:03,261:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): publicsuffix.org:443
2024-11-08 17:13:03,463:DEBUG:urllib3.connectionpool:https://publicsuffix.org:443 "GET /list/public_suffix_list.dat HTTP/1.1" 200 86557
2024-11-08 17:13:03,504:DEBUG:filelock:Attempting to release lock 140499298840992 on /root/.lexicon_tld_set/urls/62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2024-11-08 17:13:03,505:DEBUG:filelock:Lock 140499298840992 released on /root/.lexicon_tld_set/urls/62bf135d1c2f3d4db4228b9ecaf507a2.tldextract.json.lock
2024-11-08 17:13:03,520:DEBUG:filelock:Attempting to release lock 140499298842144 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:03,521:DEBUG:filelock:Lock 140499298842144 released on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:03,563:DEBUG:root:Actual zone name resolved for domain thibleroy.duckdns.org: thibleroy.duckdns.org
2024-11-08 17:13:03,563:DEBUG:root:Override resolved zone name because --delegated option is set: thibleroy.duckdns.org
2024-11-08 17:13:03,568:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eu.api.ovh.com:443
2024-11-08 17:13:03,801:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
2024-11-08 17:13:03,845:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 2
2024-11-08 17:13:03,900:DEBUG:root:Parameter resolve_zone_name is not set, use tldextract to guess the zone name from known TLDs
2024-11-08 17:13:03,901:DEBUG:filelock:Attempting to acquire lock 140499298154400 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:03,901:DEBUG:filelock:Lock 140499298154400 acquired on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:03,904:DEBUG:filelock:Attempting to release lock 140499298154400 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:03,905:DEBUG:filelock:Lock 140499298154400 released on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:03,931:DEBUG:root:Actual zone name resolved for domain duckdns.org: .duckdns.org
2024-11-08 17:13:03,932:DEBUG:root:Override resolved zone name because --delegated option is set: duckdns.org..duckdns.org
2024-11-08 17:13:03,937:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eu.api.ovh.com:443
2024-11-08 17:13:04,123:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
2024-11-08 17:13:04,164:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 2
2024-11-08 17:13:04,219:DEBUG:root:Parameter resolve_zone_name is not set, use tldextract to guess the zone name from known TLDs
2024-11-08 17:13:04,220:DEBUG:filelock:Attempting to acquire lock 140499300145088 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,220:DEBUG:filelock:Lock 140499300145088 acquired on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,223:DEBUG:filelock:Attempting to release lock 140499300145088 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,223:DEBUG:filelock:Lock 140499300145088 released on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,248:DEBUG:root:Actual zone name resolved for domain org: .org
2024-11-08 17:13:04,249:DEBUG:root:Override resolved zone name because --delegated option is set: org..org
2024-11-08 17:13:04,253:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eu.api.ovh.com:443
2024-11-08 17:13:04,441:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
2024-11-08 17:13:04,485:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 2
2024-11-08 17:13:04,489:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common_lexicon.py", line 220, in _perform
    resolved_domain = self._resolve_domain(domain)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common_lexicon.py", line 263, in _resolve_domain
    raise errors.PluginError('Unable to determine zone identifier for {0} using zone names: {1}'
certbot.errors.PluginError: Unable to determine zone identifier for thibleroy.duckdns.org using zone names: ['thibleroy.duckdns.org', 'duckdns.org', 'org']

2024-11-08 17:13:04,490:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-11-08 17:13:04,491:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-11-08 17:13:04,545:DEBUG:root:Parameter resolve_zone_name is not set, use tldextract to guess the zone name from known TLDs
2024-11-08 17:13:04,546:DEBUG:filelock:Attempting to acquire lock 140499298629968 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,546:DEBUG:filelock:Lock 140499298629968 acquired on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,549:DEBUG:filelock:Attempting to release lock 140499298629968 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,549:DEBUG:filelock:Lock 140499298629968 released on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,589:DEBUG:root:Actual zone name resolved for domain thibleroy.duckdns.org: thibleroy.duckdns.org
2024-11-08 17:13:04,590:DEBUG:root:Override resolved zone name because --delegated option is set: thibleroy.duckdns.org
2024-11-08 17:13:04,594:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eu.api.ovh.com:443
2024-11-08 17:13:04,808:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
2024-11-08 17:13:04,840:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 2
2024-11-08 17:13:04,893:DEBUG:root:Parameter resolve_zone_name is not set, use tldextract to guess the zone name from known TLDs
2024-11-08 17:13:04,894:DEBUG:filelock:Attempting to acquire lock 140499303831008 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,894:DEBUG:filelock:Lock 140499303831008 acquired on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,896:DEBUG:filelock:Attempting to release lock 140499303831008 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,897:DEBUG:filelock:Lock 140499303831008 released on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:04,922:DEBUG:root:Actual zone name resolved for domain duckdns.org: .duckdns.org
2024-11-08 17:13:04,923:DEBUG:root:Override resolved zone name because --delegated option is set: duckdns.org..duckdns.org
2024-11-08 17:13:04,927:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eu.api.ovh.com:443
2024-11-08 17:13:05,146:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
2024-11-08 17:13:05,180:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 2
2024-11-08 17:13:05,235:DEBUG:root:Parameter resolve_zone_name is not set, use tldextract to guess the zone name from known TLDs
2024-11-08 17:13:05,236:DEBUG:filelock:Attempting to acquire lock 140499341634224 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:05,237:DEBUG:filelock:Lock 140499341634224 acquired on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:05,239:DEBUG:filelock:Attempting to release lock 140499341634224 on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:05,239:DEBUG:filelock:Lock 140499341634224 released on /root/.lexicon_tld_set/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json.lock
2024-11-08 17:13:05,264:DEBUG:root:Actual zone name resolved for domain org: .org
2024-11-08 17:13:05,264:DEBUG:root:Override resolved zone name because --delegated option is set: org..org
2024-11-08 17:13:05,269:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eu.api.ovh.com:443
2024-11-08 17:13:05,475:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
2024-11-08 17:13:05,509:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 2
2024-11-08 17:13:05,511:DEBUG:certbot.plugins.dns_common_lexicon:Encountered error finding domain_id during deletion: Unable to determine zone identifier for thibleroy.duckdns.org using zone names: ['thibleroy.duckdns.org', 'duckdns.org', 'org']
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common_lexicon.py", line 220, in _perform
    resolved_domain = self._resolve_domain(domain)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common_lexicon.py", line 263, in _resolve_domain
    raise errors.PluginError('Unable to determine zone identifier for {0} using zone names: {1}'
certbot.errors.PluginError: Unable to determine zone identifier for thibleroy.duckdns.org using zone names: ['thibleroy.duckdns.org', 'duckdns.org', 'org']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common_lexicon.py", line 231, in _cleanup
    resolved_domain = self._resolve_domain(domain)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common_lexicon.py", line 263, in _resolve_domain
    raise errors.PluginError('Unable to determine zone identifier for {0} using zone names: {1}'
certbot.errors.PluginError: Unable to determine zone identifier for thibleroy.duckdns.org using zone names: ['thibleroy.duckdns.org', 'duckdns.org', 'org']
2024-11-08 17:13:05,514:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1894, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common_lexicon.py", line 220, in _perform
    resolved_domain = self._resolve_domain(domain)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common_lexicon.py", line 263, in _resolve_domain
    raise errors.PluginError('Unable to determine zone identifier for {0} using zone names: {1}'
certbot.errors.PluginError: Unable to determine zone identifier for thibleroy.duckdns.org using zone names: ['thibleroy.duckdns.org', 'duckdns.org', 'org']
2024-11-08 17:13:05,517:ERROR:certbot._internal.log:Unable to determine zone identifier for thibleroy.duckdns.org using zone names: ['thibleroy.duckdns.org', 'duckdns.org', 'org']

**Comment by DorianCoding** [comment]
Hello,

It seems your zone is not found on the DNS, there is many options:

- Your API key has not access to your domain.
- Your domain is not managed by dns-ovh, and maybe by something else like dns-duck.
- Your zonename or your domain is invalid.

**Comment by osirisinferi** [comment]
> * Your domain is not managed by dns-ovh, and maybe by something else like dns-duck.

It's obviously this problem, as the domain in question is `thibleroy.duckdns.org`.. Which is managed/hosted by.. Well.. DuckDNS.

@thibleroy Please use the appropriate DNS plugin like [`certbot-dns-duckdns`](https://github.com/infinityofspace/certbot_dns_duckdns).
