### ISSUE TITLE
Today, certbot started crashing during python initialization

### ISSUE THREAD

**Issue by AlexisWilke** [certbot/certbot#10095]
## My operating system is (include version):

    $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 22.04.5 LTS
    Release:	22.04
    Codename:	jammy

    $ uname -a
    Linux monster 5.15.0-128-generic #138-Ubuntu SMP Sat Nov 30 22:28:23 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

OS Package

    $ dpkg -l certbot
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name           Version        Architecture Description
    +++-==============-==============-============-=================================================
    ii  certbot        1.21.0-1build1 all          automatically configure HTTPS using Let's Encrypt

## I ran this command and it produced this output:

The certbot timer started failing. The exact same error happens when I run `certbot help` as follow:

    $ certbot help
    Traceback (most recent call last):
      File "/usr/bin/certbot", line 33, in <module>
        sys.exit(load_entry_point('certbot==1.21.0', 'console_scripts', 'certbot')())
      File "/usr/bin/certbot", line 25, in importlib_load_entry_point
        return next(matches).load()
      File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
        module = import_module(match.group('module'))
      File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/usr/lib/python3/dist-packages/certbot/main.py", line 2, in <module>
        from certbot._internal import main as internal_main
      File "/usr/lib/python3/dist-packages/certbot/_internal/main.py", line 23, in <module>
        from certbot import configuration
      File "/usr/lib/python3/dist-packages/certbot/configuration.py", line 8, in <module>
        from certbot import util
      File "/usr/lib/python3/dist-packages/certbot/util.py", line 25, in <module>
        from certbot._internal import constants
      File "/usr/lib/python3/dist-packages/certbot/_internal/constants.py", line 4, in <module>
        import pkg_resources
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3267, in <module>
        def _initialize_master_working_set():
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3241, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3279, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 564, in _build_master
        ws = cls()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 557, in __init__
        self.add_entry(entry)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 613, in add_entry
        for dist in find_distributions(entry, True):
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2077, in find_on_path
        for dist in factory(fullpath):
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2135, in distributions_from_metadata
        if len(os.listdir(path)) == 0:
    OSError: [Errno 5] Input/output error: '/usr/lib/python3/dist-packages/python_dateutil-2.8.1.egg-info'

## Certbot's behavior differed from what I expected because:

Python initialization fails.

Other tools, such as apt-get, do not seem to have that issue.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

I do see errors in link with various domain names and such, but nothing about the crash above.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

I do not think that this is relevant since even the `help` command fails.

Note: it just started for me. I upgraded and rebooted my server last night and noticed the error this morning (Dec 18, 2024).

**Comment by AlexisWilke** [comment]
Hmm... It works now. So I guess python was just being silly or something. Closing.
