### ISSUE TITLE
Improve NoInstallationError message

### ISSUE THREAD

**Issue by kuba** [certbot/certbot#1092]
https://github.com/letsencrypt/letsencrypt/blob/v0.0.0.dev20151021/letsencrypt-apache/letsencrypt_apache/configurator.py#L145
1. We should never do `raise Exception`, always `raise Exception()`
2. I just had a report from RHEL user that he couldn't get Apache plugin to work. Turns out that default server root is `/etc/httpd`. Can we please do `raise errors.NoInstallationError("Configs not found at {0}".format(self.conf("server-root")))` so that the explicit error message is found in the logs? Now it's only:
   
   ```
   2015-10-23 14:40:49,632:DEBUG:letsencrypt.plugins.disco:No installation (PluginEntryPoint#apache):
   Traceback (most recent call last):
   File "/usr/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py", line 103, in prepare
     self._initialized.prepare()
   File "/usr/local/lib/python2.7/site-packages/letsencrypt_apache/configurator.py", line 145, in prepare
     raise errors.NoInstallationError
   NoInstallationError
   ```

Could you look into that @swartzcr, please? :)

**Comment by pde** [comment]
Should be fixed these days.
