### ISSUE TITLE
Messing with /etc/letsencrypt leads to An unexpected error occurred. TypeError: coercing to Unicode: need string or buffer, NoneType found.

### ISSUE THREAD

**Issue by erebus2** [certbot/certbot#1195]
Hello everyone,

I got yet another problem with letsencrypt. :-(

First of all, I was able to obtain and install several letsencrypt certificates although I had to use the standalone authenticator. (the apache plugin is broken for me, but that's a different issue.)

However, after I had obtained several certificates, letsencrypt suddenly stopped working.

Now, when I try to request a cert, I just get the following error:

   An unexpected error occurred.
   TypeError: coercing to Unicode: need string or buffer, NoneType found
   Please see the logfiles in /var/log/letsencrypt for more details.

The error happens just after I have typed the domain name which I need the certificate for. It happens with both authenticators (manual and standalone) and it happens with every domain name I tried.

These are the last lines of the logfile:

```
[...]
2015-10-29 14:15:32,882:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2015-10-29 14:15:32,909:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-10-29 14:15:33,851:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2015-10-29 14:15:33,856:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Thu, 29 Oct 2015 14:19:37 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 29 Oct 2015 14:19:37 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': '***'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-10-29 14:15:33,859:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Thu, 29 Oct 2015 14:19:37 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 29 Oct 2015 14:19:37 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': '***'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2015-10-29 14:15:33,859:DEBUG:letsencrypt.display.ops:No installer, picking names manually
2015-10-29 14:15:38,067:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1097, in main
return args.func(args, config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 473, in auth
_auth_from_domains(le_client, config, domains, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 295, in _auth_from_domains
lineage = _treat_as_renewal(config, domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 215, in _treat_as_renewal
config, domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 189, in _find_duplicative_certs
candidate_names = set(candidate_lineage.names())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/storage.py", line 435, in names
with open(target) as f:
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

What the heck is happening here??????????????

**Comment by bowensong** [comment]
`names()` function:
```python
    def names(self, version=None):
        # ...
        if version is None:
            target = self.current_target("cert")
        else:
            target = self.version("cert", version)
        with open(target) as f:   # <----- crashed here, because target is None
            return crypto_util.get_sans_from_cert(f.read())
```

And the `current_target()` function:
```python
    def current_target(self, kind):
        # ...
        link = getattr(self, kind)
        if not os.path.exists(link):
            return None
        # ...
```

OK, now I guess the reason was because `self.cert` file does not exist.

**Comment by devnsec-com** [comment]
`names()` function:
```python
    def names(self, version=None):
        # ...
        if version is None:
            target = self.current_target("cert")
        else:
            target = self.version("cert", version)
        with open(target) as f:   # <----- crashed here, because target is None
            return crypto_util.get_sans_from_cert(f.read())
```

And the `current_target()` function:
```python
    def current_target(self, kind):
        # ...
        link = getattr(self, kind)
        if not os.path.exists(link):
            return None
        # ...
```

OK, now I guess the reason was because `self.cert` file does not exist.

**Comment by erebus2** [comment]
Ok, after looking at several source files and attempted some patches, it seems that this is an IOF issue¹.

In particular, I renamed several files in /etc/letsencrypt because I didn't like the -0001 suffix which LE had added to one of my domain names. Although I took care of any symlinks that needed to be updated, I missed the _content_ of the renewal config file which included several pointers to a renamed directory which were now broken. LE is working again since I fixed that file.

Fixing this problem at the root is a cantfix as there is no way of patching HID operating units (at least none that I know of).

However, I think that this kind of error could be handled more gracefully (e. g. by adding an exception handler in the right place).

-----
¹ IOF issue: A problem which is caused by something related to I/O devices and seating furniture

**Comment by kuba** [comment]
You must not rename any files in `/etc/letsencrypt`. You should not mess with `-0001` files. You should not mess with renewal configs in this way. As per documentation (http://letsencrypt.readthedocs.org/en/latest/using.html#where-are-my-certificates), you should only look into `/etc/letsencrypt/live` and symlink to files in it or use those paths in the server config files.

**Comment by kuba** [comment]
I think the correct action to take here is to document prohibited alterations.

**Comment by pde** [comment]
We still need a README.txt file in the live directories to explain this stuff to the user at the right moment.  Also perhaps this error should be more informative :)

**Comment by cweiske** [comment]
I have the same error.
I stumbled over the `-d domain -d domain` problem #1376 and did not want a certificate with all domains.

So I removed the `/etc/letsencrypt/live/$firstdomain` directory and now I get this error.

**Comment by lucas42** [comment]
I agree with @cweiske - a nice error message would be helpful (BTW thanks for the tip on deleting things from `renewal` and `archive`)
Anyone writing any sort of automation will want to check that they can generate new certs from scratch - and the way most people will test this is to remove files from `live/`(I certainly did).  At the very least, doing this should return a clear error message explaining about `renewal/` and `archive/`.  But ideally, it'd just continue to work.  (Either by recreating the symlinks to archive and showing a warning, or by re-generating the certs from scratch)

**Comment by pwaring** [comment]
I've received the same error today, however I haven't changed anything in `/etc/letsencrypt` (the last modification dates are when I last ran `letsencrypt-auto` three days ago).

**Comment by jrslv** [comment]
I experienced this error when I moved a directory from `/etc/letsencrypt/live/` and run `./letsencrypt-auto certonly --standalone ...` for another domain.

**Comment by schoen** [comment]
Despite the apparent Unicode connection, I've concluded that this is a "deleting or renaming files in `/etc/letsencrypt`" issue. 

Hopefully this is better addressed by the existing README which will soon be in more places

https://github.com/certbot/certbot/pull/6377

and better error messages over time about various kinds of corrupted `/etc/letsencrypt` (although we still presumably need to do a systematic review of every way that it could become corrupt).
