### ISSUE TITLE
Error about missing module ipaddress, even though it's installed

### ISSUE THREAD

**Issue by thomassnielsen** [certbot/certbot#1209]
Here's the output:

``` sh
~/WebDevelopment/letsencrypt ❯ ./letsencrypt-auto
-n Updating letsencrypt and virtual environment dependencies...
-n .
-n .
-n .

Running with virtualenv: sudo /Users/thomas/.local/share/letsencrypt/bin/letsencrypt
Traceback (most recent call last):
  File "/Users/thomas/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from letsencrypt.cli import main
  File "/Users/thomas/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 29, in <module>
    from letsencrypt import client
  File "/Users/thomas/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 17, in <module>
    from letsencrypt import continuity_auth
  File "/Users/thomas/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/continuity_auth.py", line 9, in <module>
    from letsencrypt import proof_of_possession
  File "/Users/thomas/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/proof_of_possession.py", line 5, in <module>
    from cryptography import x509
  File "/Users/thomas/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/Users/thomas/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/x509/base.py", line 15, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/Users/thomas/.local/share/letsencrypt/lib/python2.7/site-packages/cryptography/x509/extensions.py", line 9, in <module>
    import ipaddress
ImportError: No module named ipaddress
letsencrypt/. git/master

~/WebDevelopment/letsencrypt ❯ pip list | grep ipaddress
ipaddress (1.0.14)
```

I have a feeling it might be related to python2 vs python3, but I'm not sure what to do about it. My default is python2.

**Comment by pde** [comment]
Hi!  What version of what OS are you running this on?

**Comment by kuba** [comment]
Please run `~/.local/share/letsencrypt/bin/pip list` and paste the **entire** output here. `pip list` is no good, because we use a separate virtualenv.

https://github.com/pyca/cryptography/blob/1.1/setup.py#L48 suggests it should be installed. @alex, is that a known issue?

**Comment by alex** [comment]
@kuba nope, I haven't seen this before

**Comment by thomassnielsen** [comment]
I'm running OS X 10.11.1. `ipaddress` is precent when listing from the virtualenv.

```
~ ❯ ~/.local/share/letsencrypt/bin/pip list
acme (0.0.0.dev20151030)
autopep8 (1.1.1)
awscli (1.8.6)
awsebcli (3.4.6)
botocore (1.2.4)
cement (2.4.0)
cffi (1.3.0)
CherryPy (3.8.0)
colorama (0.3.3)
ConfigArgParse (0.9.3)
configobj (5.0.6)
cryptography (1.1)
docker-py (0.5.3)
dockerpty (0.3.4)
docopt (0.6.2)
docutils (0.12)
enum34 (1.0.4)
fig (1.0.1)
funcsigs (0.4)
hiredis (0.2.0)
idna (2.0)
inflection (0.2.0)
ipaddress (1.0.14)
jmespath (0.7.1)
Klarna-API (3.1.0)
letsencrypt (0.0.0.dev20151030)
letsencrypt-apache (0.0.0.dev20151030)
marshmallow (1.2.6)
mock (1.3.0)
ndg-httpsclient (0.4.0)
parsedatetime (1.5)
pathspec (0.3.3)
pbr (1.8.1)
pep8 (1.6.2)
pgsanity (0.2.8)
pip (7.1.2)
psutil (3.2.2)
pyasn1 (0.1.8)
pycparser (2.14)
pyOpenSSL (0.15.1)
pyRFC3339 (0.2)
python-augeas (0.5.0)
python2-pythondialog (3.3.0)
pytz (2015.7)
PyYAML (3.11)
requests (2.6.2)
rsa (3.1.4)
schematics (0.9.post4)
setuptools (18.4)
six (1.10.0)
sqlparse (0.1.15)
texttable (0.8.3)
virtualenv (13.1.2)
websocket-client (0.11.0)
Werkzeug (0.10.4)
wheel (0.24.0)
wxPython-common (3.0.2.0)
zope.component (4.2.2)
zope.event (4.1.0)
zope.interface (4.1.3)
```

**Comment by pde** [comment]
This is an ancient issue with an antique install script. These days you should probably use `brew` to install Certbot on OS X, but if recent `certbot-auto` scripts are misbehaving please reopen/refile.
