### ISSUE TITLE
Error creating new authz without CNAME record

### ISSUE THREAD

**Issue by mitnk** [certbot/certbot#1369]
From [Known issue page](https://github.com/letsencrypt/letsencrypt/wiki/Known-issues), it says the issue was caused by "request a domain that has a DNS CNAME to a subdomain of the requested domain". But mine seems not the case. Please see the log for details.

```
[2015-11-05 08:55:24,217][DEBUG] Root logging level set at 30
[2015-11-05 08:55:24,218][INFO] Saving debug log to /var/log/letsencrypt/letsencrypt.log
[2015-11-05 08:55:24,218][DEBUG] letsencrypt version: 0.0.0.dev20151104
[2015-11-05 08:55:24,219][DEBUG] Arguments: ['--agree-dev-preview', '-d', 'hugo.wang', '-d', 'www.hugo.wang', '--server', 'https://acme-v01.api.letsencrypt.org/directory', '-a', 'manual']
[2015-11-05 08:55:24,220][DEBUG] Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
[2015-11-05 08:55:24,232][DEBUG] Requested authenticator manual and installer None
[2015-11-05 08:55:24,258][DEBUG] Single candidate plugin: * manual
Description: Manually configure an HTTP server
Interfaces: IAuthenticator, IPlugin
Entry point: manual = letsencrypt.plugins.manual:Authenticator
Initialized: <letsencrypt.plugins.manual.Authenticator object at 0x41646070>
Prep: True
[2015-11-05 08:55:24,259][DEBUG] Selected authenticator <letsencrypt.plugins.manual.Authenticator object at 0x41646070> and installer None
[2015-11-05 08:55:24,345][DEBUG] Picked account: <Account(d9acbb840813ef5d7105b29b23015262)>
[2015-11-05 08:55:24,346][DEBUG] Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
[2015-11-05 08:55:24,369][INFO] Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
[2015-11-05 08:55:24,653][DEBUG] "GET /directory HTTP/1.1" 200 263
[2015-11-05 08:55:24,664][DEBUG] Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Thu, 05 Nov 2015 08:55:24 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 05 Nov 2015 08:55:24 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'a9cJpqa_T4PwBgaLYSZ-gcuaQA-iAR9VYyhehCKbCUo'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
[2015-11-05 08:55:24,666][DEBUG] Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Thu, 05 Nov 2015 08:55:24 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 05 Nov 2015 08:55:24 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*', 'Replay-Nonce': 'a9cJpqa_T4PwBgaLYSZ-gcuaQA-iAR9VYyhehCKbCUo'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
[2015-11-05 08:55:28,064][INFO] Generating key (2048 bits): /etc/letsencrypt/keys/0010_key-letsencrypt.pem
[2015-11-05 08:55:28,107][INFO] Creating CSR: /etc/letsencrypt/csr/0010_csr-letsencrypt.pem
[2015-11-05 08:55:28,108][DEBUG] CSR: CSR(file='/etc/letsencrypt/csr/0010_csr-letsencrypt.pem', data='0\x82\x02\x8f0\x82\x01w\x02\x01\x000\x141\x120\x10\x06\x03U\x04\x03\x0c\thugo.wang0\x82\x01"0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x01\x05\x00\x03\x82\x01\x0f\x000\x82\x01\n\x02\x82\x01\x01\x00\xcd\x95\x96\x05\t\x9c\xbc\xac\xef\xf1\xc0\xfd\x82\x88\xb1\xcfn\x8d\xf0w\xb5\x0b\xe3\xf7n\xbe\xb5<\x07q\x16\xa4\xaf\xb5\xe8\x92h\x15\xdeQ\x03U\x04\x0c\x11\x19\x97\x03\n\\\xef\x15v\xac.\xb6\x1cFu\xa0\xa4\xc99\xe0\xceK\xfd\xe7\xf7\xe3\xdc\xd6[\xbe\xaeg\xe3\xf4,\xe3\xed$U\xfb\xcb\xb3,\xda\x1f\xcb|\\\xff\x83\xb4!8\x1a\xce6/?\x8c\x08\x9c^\xb6\xa0\xa3\xac\xfe\x07\x10\x82:\x80\xf9\x06\xcf\xd3\x80q\xbe\xad\xe5\xf5\xf6\xdf\\\x0e\xa1F\x14\x17\x1fy=o!\xc2\x8e\xdd\x13\xef\xc2\x19j\xc2l\x05\xef\x14\x85\xa8\x12\xadL\t\xea\x8f\x9e\x89\xf41%\x02\x08[\x0f[\x1e\x9a\xc6\x9d\x0f\xa5{\xbd-\x07\xc7i\x03MD\xca\x1e\xd3e\xda\xa0\xce\xf3`\xe0\xa5\x9c\xfe\x94\xfe\x83\xbc\x13\x02{>.`\xe4\xb4\x7f\x7f\xc0\xd7\xf7\xc1\xc6Ih\xa4\xf5d5\xce\xdeFj\xf2\xf4\xc7+\xc4]\x8d\xcb\x80\x8f\x9da\x0e\xfe\xd8\xf7\xcf\x82\xb0\xed$,\xd7\x8cx\xf2N\x8a\r\x02\x03\x01\x00\x01\xa0604\x06\t*\x86H\x86\xf7\r\x01\t\x0e1\'0%0#\x06\x03U\x1d\x11\x04\x1c0\x1a\x82\thugo.wang\x82\rwww.hugo.wang0\r\x06\t*\x86H\x86\xf7\r\x01\x01\x0b\x05\x00\x03\x82\x01\x01\x00\xa7:v\x93\x14\xe4:\xa2&y\xbb\xa0\xbe=\xb3\xde\xd9\xb6F!\xfa\x9dD\xf2\xe9\x86e\xff\xfe\xc6\x82\xe3\xd1\xbd\x02\xdc\xb4\xe1\xb5y\xa0\x84<J\xfbD\xd8\x89IMv=wJ\x91\x16\ry\x93\xb7\xf9\xa3\xe1p\xec\xa4\xf6k5\x9a0\xf8\xae\x95Y\xa3\x9cD\xbbH\x99@(Z\x85\x0b\xfe\x9b\xa9C\x0e\r/\x1f\x08\xf318\xf5\x02\x84\xe5Nqp\'v)\xd1\xac\xadB$\x8b\xb6v%$\xc6\xfd.c\xe1\xef\r\xa6\xb1\xb1\x8b\xc3\x06_\x84"EW~",\xc8\xf8s7\x11\x1e\x951\xec\xf5\xb3r\xa2\xc7\xa8\x05\xc9\xe6\x07\xad\x14j\x98P\xc9Pl\xd0_l,Q\xb6\xae\xec\xaf\xb9p\x95\x9eW\xa8\xfc\xa4\x17\xdd\xce\xccE\x11&\x0ej\x16#\x91FR\x00\xb8\xf7\xdeT\xc3C\xf0(\xcb(\xb8<\xd0\x03\xcf\xcf\'\x02b\x1b\xf5_\xc6\x12O\xa0\x17\xfaN/<*\xc1R\x12\xa5\x18\xbaH\xf2\xff\x972>;\xbe\xbf5*vnk\x82\tIN\xaf\xa6', form='der'), domains: ['hugo.wang', 'www.hugo.wang']
[2015-11-05 08:55:28,110][DEBUG] Requesting fresh nonce
[2015-11-05 08:55:28,110][DEBUG] Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
[2015-11-05 08:55:28,115][INFO] Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
[2015-11-05 08:55:28,348][DEBUG] "HEAD /acme/new-authz HTTP/1.1" 405 0
[2015-11-05 08:55:28,360][DEBUG] Received <Response [405]>. Headers: {'Content-Length': '0', 'Pragma': 'no-cache', 'Expires': 'Thu, 05 Nov 2015 08:55:28 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 05 Nov 2015 08:55:28 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'YNOyC7SIrVR6mX0OXdWb4w218z7GaanwX8dlbrKgn4Y'}. Content: ''
[2015-11-05 08:55:28,361][DEBUG] Storing nonce: '`\xd3\xb2\x0b\xb4\x88\xadTz\x99}\x0e]\xd5\x9b\xe3\r\xb5\xf3>\xc6i\xa9\xf0_\xc7en\xb2\xa0\x9f\x86'
[2015-11-05 08:55:28,362][DEBUG] Omitted empty fields: combinations=None, challenges=None, status=None, expires=None
[2015-11-05 08:55:28,363][DEBUG] Serialized JSON: {"identifier": {"type": "dns", "value": "hugo.wang"}, "resource": "new-authz"}
[2015-11-05 08:55:28,370][DEBUG] Omitted empty fields: x5c=(), x5tS256=None, alg=None, cty=None, jku=None, x5u=None, x5t=None, crit=(), kid=None, jwk=None, typ=None
[2015-11-05 08:55:28,408][DEBUG] Omitted empty fields: x5c=(), x5tS256=None, cty=None, jku=None, x5u=None, nonce=None, crit=(), x5t=None, kid=None, typ=None
[2015-11-05 08:55:28,409][DEBUG] Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "tyMI0EXnjTYZqgCm8NAkJsPTbnQRhFblWaof7jxmnpReZwxPwVhCFNjNNY19cI2fWfaQz-9hC3yyrrbbDUoML9UVOfuobGZy0vvg_ykGo2GVGbyEc-dHu579x8lSppDzVNsZj0T1Ip8tnnI0vQygMrdYCop52Z7j1znnCnHIB9IFT7O0cTRhrb2fOuFFNKiXUNMvt1REk3KeE8ChGMYjuHjDk7LTDTdeyYgnnOzz55nGd77lS23aZ9VqEwQ39ztzunH0IlNglxheVQmyIsZASZHpsSzc3_2VZMfAa6LYjNXJrfAZ-jwUSb1t8IkmS2skKAQ1GBBP6apXJX5FED12xw"}}, "protected": "eyJub25jZSI6ICJZTk95QzdTSXJWUjZtWDBPWGRXYjR3MjE4ejdHYWFud1g4ZGxicktnbjRZIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJodWdvLndhbmcifSwgInJlc291cmNlIjogIm5ldy1hdXRoeiJ9", "signature": "V1nIh67S3TMdHCznLm_TUntyVJvcPtHTYuYCrmzONXa2zvs7CCZi7tUioJoFa7C_ZSLlYOP1O_ijRd5bn46gbGjGPJ-ufg9Tu9Jb-Gx0axfy4MStigRKn2HUvXQHwQvEZwJj8P5soVx3H3bkvW0RtphAw93F7oFxpX-Std_i6XHO_n7Yt7gTgYFgjSz9DFXjuvmud1P_xuXCHW2qDYiLxucmdcclow4Jyc1YBkK_XxU2ehrkg0x1dyMMoqPZaJTbD3m6anf2wey5NXeif1DRHj6d9_p9YlaDTVBtyFwAC7fCA2e9G8scD4WmYr9K4SAAi-O1b0jsESIQPndesdrt1Q"}'}
[2015-11-05 08:55:28,414][INFO] Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
[2015-11-05 08:55:30,678][DEBUG] "POST /acme/new-authz HTTP/1.1" 500 76
[2015-11-05 08:55:30,689][DEBUG] Received <Response [500]>. Headers: {'Content-Length': '76', 'Expires': 'Thu, 05 Nov 2015 08:55:30 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 05 Nov 2015 08:55:30 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'ItfBDwhp8OkyZLdJrEAppKaXmKzy28eEaHDPYqiU8Mk'}. Content: '{"type":"urn:acme:error:serverInternal","detail":"Error creating new authz"}'
[2015-11-05 08:55:30,690][DEBUG] Storing nonce: '"\xd7\xc1\x0f\x08i\xf0\xe92d\xb7I\xac@)\xa4\xa6\x97\x98\xac\xf2\xdb\xc7\x84hp\xcfb\xa8\x94\xf0\xc9'
[2015-11-05 08:55:30,691][DEBUG] Received response <Response [500]> (headers: {'Content-Length': '76', 'Expires': 'Thu, 05 Nov 2015 08:55:30 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 05 Nov 2015 08:55:30 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'ItfBDwhp8OkyZLdJrEAppKaXmKzy28eEaHDPYqiU8Mk'}): '{"type":"urn:acme:error:serverInternal","detail":"Error creating new authz"}'
[2015-11-05 08:55:30,696][DEBUG] Exiting abnormally:
Traceback (most recent call last):
  File ".local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/mitnk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1143, in main
    return args.func(args, config, plugins)
  File "/home/mitnk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 490, in obtaincert
    _auth_from_domains(le_client, config, domains, plugins)
  File "/home/mitnk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 328, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains, plugins)
  File "/home/mitnk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 229, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/mitnk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 212, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/home/mitnk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 170, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/home/mitnk/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/home/mitnk/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/home/mitnk/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/home/mitnk/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 624, in post
    return self._check_response(response, content_type=content_type)
  File "/home/mitnk/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 542, in _check_response
    raise messages.Error.from_json(jobj)
Error: serverInternal :: The server experienced an internal error :: Error creating new authz
```

**Comment by hugo-aa** [comment]
Hi @kuba @rolandshoemaker FYI, after I changed my domain's Name Servers from `xx.hichina.com` (where I registered my domain) to NameCheap's FreeDNS Name Servers: `xx.registrar-servers.com`, the domain (which was in the log messages above) fetched the cert files successfully.

**Comment by mitnk** [comment]
Hi @kuba @rolandshoemaker FYI, after I changed my domain's Name Servers from xx.hichina.com (where I registered my domain) to NameCheap's FreeDNS Name Servers: xx.registrar-servers.com, the domain (which was in the log messages above) fetched the cert files successfully.

**Comment by mydansun** [comment]
I use dnspod but it does not make any sense

**Comment by nirocfz** [comment]
@mydansun 什么意思？遇到同样的错误了吗？

**Comment by mydansun** [comment]
It works wher I use namecheap! (freedns1.registrar-servers.com....)

**Comment by cpu** [comment]
@bmw @pde Candidate for closing? I see `Error: serverInternal :: The server experienced an internal error :: Error creating new authz` in the output above which shouldn't correlate to a missing CNAME record, but a more significant error boulder-side. Nov 5th 2015 is too far in the past for us to do much meaningful troubleshooting.
