### ISSUE TITLE
letsencrypt fails on OS X 10.10.5

### ISSUE THREAD

**Issue by TheNavigat** [certbot/certbot#1535]
The client fails with

```
An unexpected error occurred.
Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Syntax error
```

Upon checking /var/log/letsencrypt/letsencrypt.log, the following traceback was there.

```
2015-11-17 09:08:13,815:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/Users/nav/Documents/letsencrypt/venv/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.1.0.dev0', 'console_scripts', 'letsencrypt')()
  File "/Users/nav/Documents/letsencrypt/letsencrypt/cli.py", line 1188, in main
    return args.func(args, config, plugins)
  File "/Users/nav/Documents/letsencrypt/letsencrypt/cli.py", line 497, in obtain_cert
    _auth_from_domains(le_client, config, domains)
  File "/Users/nav/Documents/letsencrypt/letsencrypt/cli.py", line 326, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/Users/nav/Documents/letsencrypt/letsencrypt/client.py", line 254, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/Users/nav/Documents/letsencrypt/letsencrypt/client.py", line 237, in obtain_certificate
    return self._obtain_certificate(domains, csr) + (key, csr)
  File "/Users/nav/Documents/letsencrypt/letsencrypt/client.py", line 195, in _obtain_certificate
    authzr = self.auth_handler.get_authorizations(domains)
  File "/Users/nav/Documents/letsencrypt/letsencrypt/auth_handler.py", line 74, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/Users/nav/Documents/letsencrypt/acme/acme/client.py", line 215, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authz_uri)
  File "/Users/nav/Documents/letsencrypt/acme/acme/client.py", line 195, in request_challenges
    response = self.net.post(new_authzr_uri, new_authz)
  File "/Users/nav/Documents/letsencrypt/acme/acme/client.py", line 628, in post
    return self._check_response(response, content_type=content_type)
  File "/Users/nav/Documents/letsencrypt/acme/acme/client.py", line 544, in _check_response
    raise messages.Error.from_json(jobj)
Error: unauthorized :: The client lacks sufficient authorization :: Error creating new authz :: Syntax error
```

I'm reporting the issue as a failure because I don't think "Syntax error" is related to "lacks sufficient authorization", I believe something is wrong here.

**Comment by rafasegat** [comment]
Solution?!

**Comment by TheNavigat** [comment]
This was caused because the domain wasn't even pointed to the machine.

However, Certbot didn't work on OS X, and that was fixed by https://github.com/certbot/certbot/commit/4cb35eaeb346e11963c59fd4aa5170a7e01f7190.
