### ISSUE TITLE
osx manual certonly

### ISSUE THREAD

**Issue by sheldon** [certbot/certbot#1812]
Hey

First of all, thanks for the awesome work on this, it's great!

Here's an error I got trying out 'manual certonly' on OSX today:

```
Traceback (most recent call last):
  File "/Users/sels/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 1283, in main
    return args.func(args, config, plugins)
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 501, in obtain_cert
    le_client = _init_le_client(args, config, authenticator, installer)
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 174, in _init_le_client
    acc, acme = _determine_account(args, config)
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/cli.py", line 161, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 116, in register
    acme = acme_from_config_key(config, key)
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 41, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 60, in __init__
    self.net.get(directory).json())
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 609, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 591, in _send_request
    response = requests.request(method, url, *args, **kwargs)
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/sels/.local/share/letsencrypt/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
SSLError: ("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",)
```

**Comment by sydneyli** [comment]
I'm closing this issue since we have no context on what is going on here, and this issue hasn't really seen any traffic/further reports since 2015. Please nudge me here if you're still experiencing this issue-- I'm happy to re-open!
