### ISSUE TITLE
 Webroot installation failed 

### ISSUE THREAD

**Issue by awekas** [certbot/certbot#1837]
I have registered 3 domains (including subdomains) on my server. Because its a Apache 2.2 (known problems) i certifacate it with the -webroot method. 
One of the subdomains will not work. i allways get the error: 
Failed authorization procedure. subdomain.mydomain.at (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Error parsing key authorization file: Invalid key authorization: 264 parts

The Apache and DNS configuration is the same as the working subdomain. I have no idea where is the problem. 
here is the Logfile:
(subdomain and domain was changed by security reason)

The key folder (.well-known) was generated at the root directory
2015-12-08 14:49:56,558:DEBUG:root:Sending POST request to .....
2015-12-08 14:49:56,558:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-08 14:49:56,825:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/challenge/9PBNYxWsLwbqIMZjJFJghsLD5qGpbvpOVeWxF_pDLXc/1307454 H$
2015-12-08 14:49:56,827:DEBUG:root:Received . Headers: {'Content-Length': '312', 'Expires': 'Tue, 08 Dec 2015 14:49:56 GMT', 'Serv$
2015-12-08 14:49:56,828:DEBUG:acme.client:Storing nonce: "<\xc7\x7f\x9df\xd2\xe5,\x1fV\x89'p\x86\xce\xee\xc7\x1b\xa7N\xd2\xabx\xa6\xe0\xb7\x88\xfe$
2015-12-08 14:49:56,828:DEBUG:acme.client:Received response (headers: {'Content-Length': '312', 'Expires': 'Tue, 08 Dec 2015 14:4$
2015-12-08 14:49:59,831:DEBUG:root:Sending GET request to .........
2015-12-08 14:49:59,832:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2015-12-08 14:50:00,149:DEBUG:requests.packages.urllib3.connectionpool:"GET /acme/authz/9PBNYxWsLwbqIMZjJFJghsLD5qGpbvpOVeWxF_pDLXc HTTP/1.1" 200 $
2015-12-08 14:50:00,151:DEBUG:root:Received . Headers: {'Content-Length': '1221', 'Expires': 'Tue, 08 Dec 2015 14:50:00 GMT', 'Str$
2015-12-08 14:50:00,152:DEBUG:acme.client:Received response (headers: {'Content-Length': '1221', 'Expires': 'Tue, 08 Dec 2015 14:$
2015-12-08 14:50:00,153:INFO:letsencrypt.reporter:Reporting to user: The following 'urn:acme:error:unauthorized' errors were reported by the serve$

Domains: subdomain.mydomain.at
Error: The client lacks sufficient authorization
2015-12-08 14:50:00,153:INFO:letsencrypt.auth_handler:Cleaning up challenges
2015-12-08 14:50:00,153:DEBUG:letsencrypt.plugins.webroot:Removing /var/www/wetter/xxx/xxx/.well-known/acme-challenge/jGmDinFf2mA1mj12b$
2015-12-08 14:50:00,154:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in
sys.exit(main())
File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1283, in main
return args.func(args, config, plugins)
File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 512, in obtain_cert
authfrom_domains(le_client, config, domains)
File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 336, in authfrom_domains
lineage = le_client.obtain_and_enroll_certificate(domains)
File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 283, in obtain_and_enroll_certificate
certr, chain, key, _ = self.obtain_certificate(domains)
File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 266, in obtain_certificate
return self.obtaincertificate(domains, csr) + (key, csr)
File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 224, in obtaincertificate
authzr = self.auth_handler.get_authorizations(domains)
File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 84, in get_authorizations 

Output in CLI:
./letsencrypt-auto certonly --webroot -w /var/www/wetter/path/path/ -d subdomain.mydomain.at
.......
Failed authorization procedure. subdomain.mydomain.at (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Error parsing key authorization file: Invalid key authorization: 264 parts

IMPORTANT NOTES:
- The following 'urn:acme:error:unauthorized' errors were reported by
  the server:

Domains: subdomain.mydomain.at
Error: The client lacks sufficient authorization

Thanks for your help! 
Othmar

**Comment by gabri-ns** [comment]
got the same issue. this is my log:
> FailedChallenges: Failed authorization procedure.
> xxx.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: 
> Invalid response from http://xxx.com/.well-known/acme-challenge/aceHydXs4vdN7iQs4XeUI68nD4Obo_rDRwtWvXJt3JA [x.x.x.x]: 403,
> www.xxx.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: 
> Invalid response from http://www.xxx.com/.well-known/acme-challenge/-qLfqlsXDsTTsIDxgz8MYR0402XXOqtm0O_TaiGFc2k [x.x.x.x]: 403

i think the reason is because letsencrypt client setting wrong permission for the challange file, so the web server -that running as apache- can not read the file, hence 403 status.
![image](https://cloud.githubusercontent.com/assets/8247479/11830335/79267976-a3d6-11e5-8a91-0fa063c75e2a.png)

**Comment by maste9** [comment]
Here it is on certificate renewal for subdomain owncloud.lob-online.de
````
Failed authorization procedure. owncloud.lob-online.de (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://owncloud.lob-online.de/.well-known/acme-challenge/N2JxzBlFWdiOc6eb3TdR93wTPASmb_38DUDQUgbQS44 [178.0.27.157]: 404

IMPORTANT NOTES:
 - The following 'urn:acme:error:unauthorized' errors were reported by
   the server:

   Domains: owncloud.lob-online.de
   Error: The client lacks sufficient authorization
````
on a Debian ARM7 Apache 2.2 with
````
./letsencrypt-auto certonly --webroot -w /var/www/ -d lob-online.de  -w /var/www/friendica/ -d friendica.lob-online.de -w /var/www/owncloud/ -d owncloud.lob-online.de
````
But I'm not sure at the moment if this could be due to a server misconfiguration as friendica.lob-online.de and ownloud.lob-online.de both point to lob-online.de root folder obviously. Which they didn't before the change from other certs to letsencrypt. 

BUT: This could have happened after the **bootstrap process did break** and fucked my apache2 config up completely which I restored painfully the last week. Might be that I did not restore it completely and there are still misconfigurations I have to locate. This could explain, why script can't find the _.well-known_ folder under the subdomains

**Comment by maste9** [comment]
To update my constraints:

I solved the configuration issues so that my subdomains are pointing correctly. But **letsencrypt still throws the same error message** in response.

**Comment by stweil** [comment]
Using webroot installation will fail on all typical TYPO3 websites. TYPO3 uses a `.htaccess` in the webroot which forbids any access to files or directories starting with a "." in their name. This also applies to the `.well-known` folder used by letsencrypt. It is necessary to fix the Apache2 configuration and explicitly allow accessing of `.wellknown`, then webroot installation will work.

**Comment by sydneyli** [comment]
This doesn't seem like a certbot-specific issue, and has to do with your fileserver/CMS's setup. If people are still having trouble with the webroot authentication method, feel free to drop a note at [our community forums](https://community.letsencrypt.org/c/help) where there's a large audience of folks that are quite familiar with the project!
