### ISSUE TITLE
Bitnami Amazon AMIs are not supported and the preinstalled apache is not detected

### ISSUE THREAD

**Issue by aoighost** [certbot/certbot#1859]
Because of the way Bitnami handles their AMIs on Amazon, the Apache plugin does not detect the installed apache. This is because of how bitnami organizes their directory structure. Link to documentation follows: https://wiki.bitnami.com/Components/Apache#How_to_enable_HTTPS_support_with_SSL_certificates

**Comment by pde** [comment]
Duplicate of #788, I think.  Please reopen if this isn't fixed when 0.2.0 is released in January.

**Comment by pde** [comment]
Or try out the code in #1811; if it doesn't work for you, you can reopen this sooner :)

**Comment by benhorowitz** [comment]
I think this is still an issue, I ran into it today:

```2016-06-28 22:35:56,103:DEBUG:certbot.main:Root logging level set at 20
2016-06-28 22:35:56,103:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-06-28 22:35:56,108:DEBUG:certbot.main:certbot version: 0.8.1
2016-06-28 22:35:56,108:DEBUG:certbot.main:Arguments: ['--apache', '-v']
2016-06-28 22:35:56,108:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-06-28 22:35:56,110:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2016-06-28 22:35:56,117:DEBUG:certbot.plugins.disco:No installation (PluginEntryPoint#apache):
Traceback (most recent call last):
  File "/home/bitnami/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 105, in prepare
    self._initialized.prepare()
  File "/home/bitnami/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 161, in prepare
    raise errors.NoInstallationError
NoInstallationError
2016-06-28 22:35:56,118:DEBUG:certbot.plugins.selection:No candidate plugin
2016-06-28 22:35:56,118:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None```
