### ISSUE TITLE
Auto script python error

### ISSUE THREAD

**Issue by tiarebalbi** [certbot/certbot#1902]
After the update below when i try to run the script i see this error:

---

:~/letsencrypt$ python --version
## Python 2.7.6

From https://github.com/letsencrypt/letsencrypt
- branch            master     -> FETCH_HEAD
  8bfda79..af68109  master     -> origin/master
  Updating 8bfda79..af68109
  ------------------------------------------------------------

Updating letsencrypt and virtual environment dependencies......Exception:
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/commands/install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/req/req_set.py", line 409, in _prepare_file
    req_to_install, finder)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/req/req_set.py", line 365, in _check_skip_installed
    finder.find_requirement(req_to_install, self.upgrade)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/index.py", line 486, in find_requirement
    all_versions = self._find_all_versions(req.name)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/index.py", line 404, in _find_all_versions
    index_locations = self._get_index_urls_locations(project_name)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/index.py", line 378, in _get_index_urls_locations
    page = self._get_page(main_index_url)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/index.py", line 818, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/index.py", line 928, in get_page
    "Cache-Control": "max-age=600",
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 477, in get
    return self.request('GET', url, *_kwargs)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/download.py", line 373, in request
    return super(PipSession, self).request(method, url, *args, *_kwargs)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 573, in send
    r = adapter.send(request, *_kwargs)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, *_kw)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    return self.recv(_args, *_kwargs)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in recv
    data = self.connection.recv(_args, **kwargs)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1320, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/home/ubuntu/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1178, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
SysCallError: (104, 'ECONNRESET')
ubuntu@ip-172-31-34-83:~/letsencrypt$

**Comment by schoen** [comment]
This seems to be a firewall or CDN problem. The Let's Encrypt Community Forum at https://community.letsencrypt.org/ is a more effective place to try to diagnose problems of this sort because there are many more people monitoring it and prepared to help with debugging suggestions.

I hope you were eventually able to figure out the problem somehow!
