### ISSUE TITLE
letsencrypt-auto stops with No matching distribution found for letsencrypt

### ISSUE THREAD

**Issue by jtolksdo** [certbot/certbot#1963]
Hi,
I'm trying to install letsencrypt on OpenSuSE 13.1. I've updated python already from a recent repository, so that I have a current version. However, letsencrypt installation fails. I've been told it's a pip issue, but I'm not sure how to resolve.

Any ideas?

s18366321:~/letsencrypt # ./letsencrypt-auto --apache
Updating letsencrypt and virtual environment dependencies......  Could not find a version that satisfies the requirement letsencrypt (from versions: )
No matching distribution found for letsencrypt

s18366321:~/letsencrypt # ./letsencrypt-auto -vv
-vv
Updating letsencrypt and virtual environment dependencies...
Requirement already up-to-date: setuptools in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Requirement already up-to-date: pip in /root/.local/share/letsencrypt/lib/python2.7/site-packages
Collecting letsencrypt
  Could not find a version that satisfies the requirement letsencrypt (from versions: )

**Comment by osirisinferi** [comment]
Could you read the [pip user documentation](https://pip.pypa.io/en/stable/user_guide/) and please check your pip configuration files for perhaps "strange" configurations? As I said on the LE community site, I have no experience with OpenSuse, nor Pip, but perhaps you'll find something "odd" in there.

**Comment by bmw** [comment]
I'd start by trying the following:

Delete `/root/.local/share/letsencrypt` and do a `git pull` to make sure your version of `letsencrypt-auto` is up to date. After that, try running `letsencrypt-auto` again.

If that fails, run please run `/root/.local/share/letsencrypt/bin/pip freeze` and report the output back here.

**Comment by TheBigfoot** [comment]
Hello,
I'm having the same issue, just on CentOS 7.
I did already remove /root/.local/share/letsencrypt, updated to the latest version, but it is still failing.
```
[root@munin letsencrypt]# ./letsencrypt-auto -vv
-vv
Bootstrapping dependencies for RedHat-based OSes...
yum is /usr/bin/yum
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.softaculous.com
 * epel: mirrors.n-ix.net
 * extras: mirror.de.leaseweb.net
 * updates: mirror.de.leaseweb.net
Package python-2.7.5-34.el7.x86_64 already installed and latest version
Package python-devel-2.7.5-34.el7.x86_64 already installed and latest version
Package python-virtualenv-1.10.1-2.el7.noarch already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.softaculous.com
 * epel: mirrors.n-ix.net
 * extras: mirror.de.leaseweb.net
 * updates: mirror.de.leaseweb.net
Package gcc-4.8.5-4.el7.x86_64 already installed and latest version
Package dialog-1.2-4.20130523.el7.x86_64 already installed and latest version
Package augeas-libs-1.4.0-2.el7.x86_64 already installed and latest version
Package 1:openssl-devel-1.0.1e-51.el7_2.1.x86_64 already installed and latest version
Package libffi-devel-3.0.13-16.el7.x86_64 already installed and latest version
Package redhat-rpm-config-9.1.0-68.el7.centos.noarch already installed and latest version
Package ca-certificates-2015.2.4-71.el7.noarch already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.softaculous.com
 * epel: mirrors.n-ix.net
 * extras: mirror.de.leaseweb.net
 * updates: mirror.de.leaseweb.net
Package 1:mod_ssl-2.4.6-40.el7.centos.x86_64 already installed and latest version
Nothing to do
Creating virtual environment...
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /root/.local/share/letsencrypt/bin/python2.7
Also creating executable in /root/.local/share/letsencrypt/bin/python
Installing Setuptools..............................................................................................................................................................................................................................done.
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
Updating letsencrypt and virtual environment dependencies...
Downloading/unpacking setuptools from https://pypi.python.org/packages/source/s/setuptools/setuptools-19.2.tar.gz#md5=78353b1f80375ca5e088f4b4627ffe03
  Downloading setuptools-19.2.tar.gz (641kB): 641kB downloaded
  Running setup.py egg_info for package setuptools
    
Installing collected packages: setuptools
  Found existing installation: setuptools 0.9.8
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for setuptools
    
    Installing easy_install script to /root/.local/share/letsencrypt/bin
    Installing easy_install-2.7 script to /root/.local/share/letsencrypt/bin
Successfully installed setuptools
Cleaning up...
Downloading/unpacking pip from https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz#md5=3823d2343d9f3aaab21cf9c917710196
  Downloading pip-7.1.2.tar.gz (1.0MB): 1.0MB downloaded
  Running setup.py egg_info for package pip
    
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
Installing collected packages: pip
  Found existing installation: pip 1.4.1
    Uninstalling pip:
      Successfully uninstalled pip
  Running setup.py install for pip
    
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
    Installing pip script to /root/.local/share/letsencrypt/bin
    Installing pip2.7 script to /root/.local/share/letsencrypt/bin
    Installing pip2 script to /root/.local/share/letsencrypt/bin
Successfully installed pip
Cleaning up...
Collecting letsencrypt
  Could not find a version that satisfies the requirement letsencrypt (from versions: )
No matching distribution found for letsencrypt
```

pip freeze output:
```
[root@munin letsencrypt]# /root/.local/share/letsencrypt/bin/pip freeze
[root@munin letsencrypt]# echo $?
0
```

**Comment by TheBigfoot** [comment]
I was playing around a little bit with that pip, still not working, but seeing a big issue with pip:
```
[root@munin letsencrypt]# /root/.local/share/letsencrypt/bin/pip search letsencrypt
Exception:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/commands/search.py", line 43, in run
    pypi_hits = self.search(query, options)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/commands/search.py", line 60, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/download.py", line 785, in request
    headers=headers, stream=True)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 508, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/download.py", line 373, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno 21] Is a directory
```

**Comment by sudhirkhanger** [comment]
```
[root@centos-512mb-fra1-01 letsencrypt]# /root/.local/share/letsencrypt/bin/pip search letsencrypt
Exception:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/commands/search.py", line 43, in run
    pypi_hits = self.search(query, options)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/commands/search.py", line 60, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/download.py", line 763, in request
    headers=headers, stream=True)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/download.py", line 377, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)

**Comment by sudhirkhanger** [comment]
```
Creating virtual environment...
Running virtualenv with interpreter /bin/python2.7
New python executable in /root/.local/share/letsencrypt/bin/python2.7
Also creating executable in /root/.local/share/letsencrypt/bin/python
Installing Setuptools..............................................................................................................................................................................................................................done.
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
Updating letsencrypt and virtual environment dependencies...
Downloading/unpacking setuptools from https://pypi.python.org/packages/source/s/setuptools/setuptools-19.4.tar.gz#md5=c5a7d90c1e0acf8c4ec5c2bf31bc25b5
  Downloading setuptools-19.4.tar.gz (641kB): 641kB downloaded
  Running setup.py egg_info for package setuptools
    
    warning: no files found matching '*' under directory 'setuptools/_vendor'
Installing collected packages: setuptools
  Found existing installation: setuptools 0.9.8
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for setuptools
    
    warning: no files found matching '*' under directory 'setuptools/_vendor'
    Installing easy_install script to /root/.local/share/letsencrypt/bin
    Installing easy_install-2.7 script to /root/.local/share/letsencrypt/bin
Successfully installed setuptools
Cleaning up...
Downloading/unpacking pip from https://pypi.python.org/packages/source/p/pip/pip-8.0.1.tar.gz#md5=21db6796276402d0f48f0ccfee2abdac
  Downloading pip-8.0.1.tar.gz (1.1MB): 1.1MB downloaded
  Running setup.py egg_info for package pip
    
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '.landscape.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    warning: no previously-included files found matching 'appveyor.yml'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
Installing collected packages: pip
  Found existing installation: pip 1.4.1
    Uninstalling pip:
      Successfully uninstalled pip
  Running setup.py install for pip
    
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.mailmap'
    warning: no previously-included files found matching '.travis.yml'
    warning: no previously-included files found matching '.landscape.yml'
    warning: no previously-included files found matching 'pip/_vendor/Makefile'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'dev-requirements.txt'
    warning: no previously-included files found matching 'appveyor.yml'
    no previously-included directories found matching '.travis'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'contrib'
    no previously-included directories found matching 'tasks'
    no previously-included directories found matching 'tests'
    Installing pip script to /root/.local/share/letsencrypt/bin
    Installing pip2.7 script to /root/.local/share/letsencrypt/bin
    Installing pip2 script to /root/.local/share/letsencrypt/bin
Successfully installed pip
Cleaning up...
Collecting letsencrypt
  Could not fetch URL https://pypi.python.org/simple/letsencrypt/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765) - skipping
  Could not find a version that satisfies the requirement letsencrypt (from versions: )
No matching distribution found for letsencrypt

**Comment by KostyaTretyak** [comment]
On CentOS 7.1
```
./letsencrypt-auto --help
Updating letsencrypt and virtual environment dependencies.....  Could not find a version that satisfies the requirement letsencrypt (from versions: )
No matching distribution found for letsencrypt
```

**Comment by voteforpresident** [comment]
I get the same error like KostyaTretyak on CentOS 7.1

Updating letsencrypt and virtual environment dependencies.....  Could not find a version that satisfies the requirement letsencrypt (from versions: )
No matching distribution found for letsencrypt
Let's encrypt returned an error status.  Aborting.

**Comment by ohemorange** [comment]
Has this happened since January 2016? @KostyaTretyak did you ever find a solution?

**Comment by ohemorange** [comment]
Great, thanks!
