### ISSUE TITLE
Issue with using letsencrypt-auto on Debian Jessie

### ISSUE THREAD

**Issue by grantwwu** [certbot/certbot#2239]
If I run ./letsencrypt-auto like so, it seems like the script chokes at very end, like so:

admin@<hostname>:~/letsencrypt ⇒ ./letsencrypt-auto 
Updating letsencrypt and virtual environment dependencies......
Requesting root privileges to run with virtualenv: sudo /home/admin/.local/share/letsencrypt/bin/letsencrypt
Traceback (most recent call last):
  File "/home/admin/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from letsencrypt.cli import main
  File "/home/admin/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 32, in <module>
    from letsencrypt import client
  File "/home/admin/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 27, in <module>
    from letsencrypt import storage
  File "/home/admin/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/storage.py", line 7, in <module>
    import configobj
ImportError: No module named configobj

This error doesn't appear if I run sudo ./letsencrypt-auto.

@leee

**Comment by grantwwu** [comment]
...I'm just going to close this; I no longer use Debian, and I haven't had any issues since, with Certbot on Ubuntu.
