### ISSUE TITLE
letsencrypt-apache build failure for v0.3.0

### ISSUE THREAD

**Issue by hlieberman** [certbot/certbot#2308]
The tests for letsencrypt-apache are now failing with an error:  
```AttributeError: 'module' object has no attribute 'augeas_configurator_test'```

Stacktrace:
```
Traceback (most recent call last):
  File "setup.py", line 66, in <module>
    test_suite='letsencrypt_apache',
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 157, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 138, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 178, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/test.py", line 36, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'augeas_configurator_test'
```

Full build log attached.

[python-letsencrypt-apache_0.3.0-1_amd64.txt](https://github.com/letsencrypt/letsencrypt/files/109086/python-letsencrypt-apache_0.3.0-1_amd64.txt)

CC: @erikrose

**Comment by erikrose** [comment]
Okay, I've repro'd it.

**Comment by erikrose** [comment]
Funny—I installed pdbpp to help with debugging, and now the tests run fine.

Then I started a fresh 2.6 venv (I had originally repro'd it under 2.6) and installed the 3 LE packages, and now it's reproducible again.

**Comment by hlieberman** [comment]
@erikrose, sorry about earlier.  I've set it up to be reproducible on this vm for you.  You should be able to ssh to it as root, and you can install or do whatever you want on it; it's a clean VM for you to mess with.

host: 192.34.60.108

**Comment by hlieberman** [comment]
Alright; I managed to track down the problem here.

As of 0.3.0, letsencrypt_apache now uses some of the test libraries from letsencrypt.  However, we strip the tests and the testdata from the python-letsencrypt library during its build step to save space in the package and to prevent the distribution of unneeded files.

This is a downstream bug.  I've sent an email out to the other letsencrypt maintainers to figure out the right thing for us to do.

**Comment by erikrose** [comment]
That'd do it. :-) We've been including the test dependencies (mostly just mock) in the letsencrypt-auto requirements file for the same reason. Would it simplify things greatly for you if we stopped shipping the tests with the packages? We've had discussions about that.
