### ISSUE TITLE
"The requested webroot plugin does not appear to be installed"

### ISSUE THREAD

**Issue by atleta** [certbot/certbot#2391]
Hi,

I'm getting this error on debian 7.7 after fixing a possible bug in cli.py by replacing line 892 with the following:

```
if self.visible_topics.get(topic, None):
```

The above was a quick fix, not entirely sure what the intent of the code was (just wanted to use the app), but it was breaking with the following exception trace before:

```
Traceback (most recent call last):
  File "/usr/local/lib/letsencrypt/env/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/letsencrypt/env/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1406, in main
    args = prepare_and_parse_args(plugins, cli_args)
  File "/usr/local/lib/letsencrypt/env/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1122, in prepare_and_parse_args
    _plugins_parsing(helpful, plugins)
  File "/usr/local/lib/letsencrypt/env/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 1249, in _plugins_parsing
    help="public_html / webroot path. This can be specified multiple times to "
  File "/usr/local/lib/letsencrypt/env/local/lib/python2.7/site-packages/letsencrypt/cli.py", line 892, in add
    if self.visible_topics[topic]:
KeyError: 'webroot'
```

I have manually installed letsencrypt, added the backported augeas lib. It works fine on a debian 8.0 system, but breaks on the 7.7, which I can't upgrade right now. Pretty frustrating.

**Comment by pde** [comment]
`webroot.py` is part of the core codebase, so the fact that it's not behaving correctly is the source both of the first error you encountered and then also the second one.  If you run with `--debug -tvv`, do you see any errors that might hint why webroot isn't showing up correctly?

Also, what installation method are you using?

**Comment by pde** [comment]
(because webroot is a core component, it should always have an entry (either `True` or `False`) in `visible_topics`.)

**Comment by atleta** [comment]
This is the output when running with the above switches. (I haven't changed back the code to the original, so it's not producing the exception.)

```
(env)root@live:/usr/local/lib/letsencrypt# letsencrypt certonly --debug -tvv --webroot -w /tmp -d mydomain.com -d www.mydomain.com
2016-02-08 00:08:47,406:DEBUG:letsencrypt.cli:Root logging level set at 10
2016-02-08 00:08:47,407:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-02-08 00:08:47,407:DEBUG:letsencrypt.cli:letsencrypt version: 0.3.0
2016-02-08 00:08:47,408:DEBUG:letsencrypt.cli:Arguments: ['--debug', '-tvv', '--webroot', '-w', '/tmp', '-d', 'mydomain.com', '-d', 'www.mydomain.com']
2016-02-08 00:08:47,408:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry()
2016-02-08 00:08:47,408:DEBUG:letsencrypt.cli:Requested authenticator webroot and installer None
2016-02-08 00:08:47,409:DEBUG:letsencrypt.display.ops:No candidate plugin
2016-02-08 00:08:47,409:DEBUG:letsencrypt.cli:Selected authenticator None and installer None
The requested webroot plugin does not appear to be installed
```

I have installed it into a virtualenv using pip, and installed the dependencies manually using apt-get (based on what I have seen in the ```bootstrap/_deb_common.sh``` script). Here's the version info for each of them:
```
(env)root@live:/usr/local/lib/letsencrypt# dpkg -l python python-dev gcc dialog libaugeas0 augeas-lenses "*virtualenv" libssl-dev libffi-dev ca-certificates                                                        
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                            Version                      Architecture 
+++-===============================================-============================-=============
ii  augeas-lenses                                   1.2.0-0.2+deb8u1~bpo70+1     all          
ii  ca-certificates                                 20130119+deb7u1              all          
ii  dialog                                          1.1-20120215-2               amd64        
ii  gcc                                             4:4.7.2-1                    amd64        
ii  libaugeas0                                      1.2.0-0.2+deb8u1~bpo70+1     amd64        
ii  libffi-dev:amd64                                3.0.10-3                     amd64        
ii  libssl-dev                                      1.0.1e-2+deb7u19             amd64        
ii  python                                          2.7.3-4+deb7u1               all          
ii  python-dev                                      2.7.3-4+deb7u1               all          
ii  python-virtualenv                               1.7.1.2-2                    all          
```

**Comment by atleta** [comment]
```
(env)root@live:/usr/local/lib/letsencrypt# pip freeze
acme==0.3.0
cached-property==1.3.0
cffi==1.5.0
coloredlogs==5.0
ConfigArgParse==0.10.0
configobj==5.0.6
cryptography==1.2.2
enum34==1.1.2
funcsigs==0.4
humanfriendly==1.43.1
idna==2.0
ipaddress==1.0.16
letsencrypt==0.3.0
letsencrypt-nginx==0.3.0
mock==1.3.0
ndg-httpsclient==0.4.0
parsedatetime==1.5
pbr==1.8.1
pip-accel==0.42.3
psutil==3.4.2
pyasn1==0.1.9
pycparser==2.14
pyOpenSSL==0.15.1
pyparsing==2.0.7
pyRFC3339==1.0
python2-pythondialog==3.3.0
pytz==2015.7
requests==2.9.1
six==1.10.0
Werkzeug==0.11.3
zope.component==4.2.2
zope.event==4.1.0
zope.interface==4.1.3
```

**Comment by smajda** [comment]
I just had this same problem and it turned out an old version of virtualenv was installing distribute in my virtualenv and `import pkg_resources` in `plugins.disco` was finding this in distribute instead of setuptools. Check your `site-packages` directory for a distribute egg and delete it.

**Comment by bmw** [comment]
Since this issue hasn't seen any activity in a long time and to my knowledge none of our supported installation mechanisms have ever installed things to `/usr/local/lib`, I'm closing this issue. If someone continues to have problems here, please comment or open a new issue.
