### ISSUE TITLE
letsencrypt.cli:Exiting abnormally

### ISSUE THREAD

**Issue by preexo** [certbot/certbot#2520]
I tried installing a letsencrypt cert through the latest version of the freedombox, it fails with this log. I can't find the reason for failure in the message, thanks for any help!

```
2016-02-22 07:17:13,788:DEBUG:letsencrypt.cli:Root logging level set at 30
2016-02-22 07:17:13,803:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-02-22 07:17:13,813:DEBUG:letsencrypt.cli:letsencrypt version: 0.4.0
2016-02-22 07:17:13,814:DEBUG:letsencrypt.cli:Arguments: ['--agree-tos', '--register-unsafely-without-email', '--domain', 'home.preexo.net', '--authenticator', 'webroot', '--webroot-path', '/var/www/html/', '--renew-by-default']
2016-02-22 07:17:13,824:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-02-22 07:17:13,859:DEBUG:letsencrypt.cli:Requested authenticator webroot and installer None
2016-02-22 07:17:13,866:DEBUG:letsencrypt.plugins.webroot:Creating root challenges validation dir at /var/www/html/.well-known/acme-challenge
2016-02-22 07:17:13,869:DEBUG:letsencrypt.display.ops:Single candidate plugin: * webroot
Description: Webroot Authenticator
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = letsencrypt.plugins.webroot:Authenticator
Initialized: <letsencrypt.plugins.webroot.Authenticator object at 0x75dc4d10>
Prep: True
2016-02-22 07:17:13,881:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.webroot.Authenticator object at 0x75dc4d10> and installer None
2016-02-22 07:17:14,015:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.0', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1987, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 690, in obtain_cert
    le_client = _init_le_client(config, authenticator, installer)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 206, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 191, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 108, in register
    logger.warn("Registering without email!")
  File "/usr/lib/python2.7/logging/__init__.py", line 1171, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1288, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1328, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 751, in handle
    self.emit(record)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/log.py", line 64, in emit
    self.width + self.PADDING_WIDTH)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 2675, in infobox
    kwargs)
  File "/usr/lib/python2.7/dist-packages/dialog.py", line 1765, in _widget_with_no_output
    widget_name, output))
PythonDialogBug
```

**Comment by bmw** [comment]
Does [this](https://github.com/letsencrypt/letsencrypt/issues/1154#issuecomment-151672549) help?

**Comment by bmw** [comment]
Haven't heard back on this, so I'm closing this issue.

**Comment by preexo** [comment]
Sorry for not replying, this was due to wrong usage of let's encrypt in the freedombox package. I think it had to do something with how the message box was used, but should have not been used, not fully sure... But it has been fixed within the freedombox package shortly after I reported and was no bug in let's encrypt at all. 
Thanks!
