### ISSUE TITLE
ImportError: No module named _struct

### ISSUE THREAD

**Issue by abdelouahabb** [certbot/certbot#2653]
I got this error while trying to install it on `Ubuntu 14.04.4 LTS`

`0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Checking for new version...
Traceback (most recent call last):
  File "/tmp/tmp.o2fLAv99sp/fetch.py", line 14, in <module>
    from json import loads
  File "/usr/local/lib/python2.7/json/__init__.py", line 108, in <module>
    from .decoder import JSONDecoder
  File "/usr/local/lib/python2.7/json/decoder.py", line 5, in <module>
    import struct
  File "/usr/local/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: No module named _struct
abdelouahab@abdelouahab:~/letsencrypt$ info
`

**Comment by bmw** [comment]
`_struct` is part of the Python standard library. I suspect there is a problem with your system's Python installation.

**Comment by abdelouahabb** [comment]
same thing even after using `sudo apt-get --reinstall install python python-support`

**Comment by pde** [comment]
It looks as though you're installed some things with `pip` (the files are in `/usr/local`).  That sometimes messes up Debian's native python state.

**Comment by abersh** [comment]
how to fix this error "importerror no module named simplejson" i'm using django 1.6.11 pleas any one

**Comment by abersh** [comment]
how to fix this error "importerror no module named register" i'm using django 1.6.11

**Comment by hockeymikey** [comment]
Having this same issue

**Comment by Doemela** [comment]
Got the same:
Cmd ./certbot-auto

Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
dialog is already the newest version.
gcc is already the newest version.
python is already the newest version.
python-dev is already the newest version.
augeas-lenses is already the newest version.
ca-certificates is already the newest version.
libaugeas0 is already the newest version.
libffi-dev is already the newest version.
libssl-dev is already the newest version.
python-virtualenv is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Checking for new version...
Traceback (most recent call last):
  File "/tmp/tmp.5rBDEgQCIo/fetch.py", line 14, in <module>
    from json import loads
  File "/usr/local/lib/python2.7/json/__init__.py", line 108, in <module>
    from .decoder import JSONDecoder
  File "/usr/local/lib/python2.7/json/decoder.py", line 5, in <module>
    import struct
  File "/usr/local/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: No module named _struct
WARNING: unable to check for updates.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 8, in <module>
    import base64
  File "/usr/local/lib/python2.7/base64.py", line 9, in <module>
    import struct
  File "/usr/local/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: No module named _struct

python --version = Python 2.7.6
pip --version = pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
find / -type f -path '*/bin/python2.7'
/usr/bin/python2.7
/usr/local/bin/python2.7
Operating system 	Ubuntu Linux 14.04

**Comment by hockeymikey** [comment]
No luck

**Comment by stdin** [comment]
Just got this on Ubuntu 14.04 as well.

**Comment by mmamani** [comment]
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Traceback (most recent call last):
  File "/tmp/tmp.hHVWNyycuV/fetch.py", line 17, in <module>
    from json import loads
  File "/usr/local/lib/python2.7/json/__init__.py", line 108, in <module>
    from .decoder import JSONDecoder
  File "/usr/local/lib/python2.7/json/decoder.py", line 5, in <module>
    import struct
  File "/usr/local/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: No module named _struct
WARNING: unable to check for updates.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 8, in <module>
    import base64
  File "/usr/local/lib/python2.7/base64.py", line 9, in <module>
    import struct
  File "/usr/local/lib/python2.7/struct.py", line 1, in <module>
    from _struct import *
ImportError: No module named _struct

**Comment by schoen** [comment]
I'm sorry that we didn't manage to find a solution to this issue that worked for most of you when it was reported in 2016 and 2017. Can any of the people who've commented on this issue indicate whether you've either found solutions or been able to reproduce it more recently (if you're still using Ubuntu 14.04)?

**Comment by schoen** [comment]
I'll take that as a no and hope that all of the problems have subsequently cleared up. (Please open a new issue if you encounter this with a current Certbot on a vendor-supported OS version.)
