### ISSUE TITLE
letsencrypt-auto fails on debian jessie

### ISSUE THREAD

**Issue by ferdinandsalis** [certbot/certbot#2721]
When on a fresh debian jessie install (via digital ocean) running the following command —
```
ferdinand: ~/letsencrypt$ ./letsencrypt-auto certonly --webroot --webroot-path /usr/share/nginx/html --renew-by-default --email mail@ferdinandsalis.com --text --agree-tos -d www.ferdinandsalis.com -d ferdinandsalis.com
```
I get the following error —
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2364, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 989, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/ferdinand/.loc...ncrypt/bin/python2.7 - setuptools pkg_resources _markerlib pip wheel failed with error code 1
```
Also here is the comlete log of the command —
```
Bootstrapping dependencies for Debian-based OSes...
[sudo] password for ferdinand:
Hit:1 http://security.debian.org jessie/updates InRelease
Hit:2 http://ftp.debian.org/debian sid InRelease
Ign:3 http://nginx.org/packages/mainline/debian jessie InRelease
Hit:4 http://nginx.org/packages/mainline/debian jessie Release
Ign:6 http://debian.lagis.at/debian jessie InRelease
Get:7 http://mirror.unitedcolo.de/debian jessie-updates InRelease [142 kB]
Get:8 http://debian.lagis.at/debian jessie Release [148 kB]
Hit:10 https://deb.nodesource.com/node_5.x jessie InRelease
Fetched 291 kB in 1s (288 kB/s)
Reading package lists... Done
W: http://nginx.org/packages/mainline/debian/dists/jessie/Release.gpg: Signature by key 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 uses weak digest algorithm (SHA1)
Reading package lists... Done
Building dependency tree
Reading state information... Done
augeas-lenses is already the newest version (1.2.0-0.3).
libaugeas0 is already the newest version (1.2.0-0.3).
ca-certificates is already the newest version (20160104).
dialog is already the newest version (1.3-20160209-1).
gcc is already the newest version (4:5.3.1-1).
libffi-dev is already the newest version (3.2.1-4).
libssl-dev is already the newest version (1.0.2g-1).
python is already the newest version (2.7.11-1).
python-dev is already the newest version (2.7.11-1).
python-virtualenv is already the newest version (15.0.1+ds-1).
virtualenv is already the newest version (15.0.1+ds-1).
0 upgraded, 0 newly installed, 0 to remove and 347 not upgraded.
Checking for new version...
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2364, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 989, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/ferdinand/.loc...ncrypt/bin/python2.7 - setuptools pkg_resources _markerlib pip wheel failed with error code 1
```
Any pointers very much appreciated. Thanks.

**Comment by nitmir** [comment]
As an alternative, you can install the `letsencrypt` package from the `jessie-backports` repository

**Comment by ferdinandsalis** [comment]
@nitmir thanks that worked but I guess the issue is not yet resolved …

**Comment by Georgevik** [comment]
@ferdinandsalis How did you do to run it?. 
In my case, I'm using debian wheezy and I have the same error

**Comment by ferdinandsalis** [comment]
I did as @nitmir suggested. See http://backports.debian.org/Instructions/.

**Comment by kfchoong** [comment]
I resolved the issue by setting the locale variables:
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

**Comment by hlieberman** [comment]
@pde, this one looks like it's fixed.
