### ISSUE TITLE
Apache test_enhance_unknown_vhost unit test failing on some systems

### ISSUE THREAD

**Issue by pde** [certbot/certbot#2773]
```
venv/bin/python letsencrypt-apache/letsencrypt_apache/tests/configurator_test.py
.....No handlers could be found for logger "letsencrypt_apache.configurator"
........................F...........................................
======================================================================
FAIL: test_enhance_unknown_vhost (__main__.TwoVhost80Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pde/eff/chocolate/chocolate/letsencrypt/venv/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/pde/eff/chocolate/chocolate/letsencrypt/letsencrypt-apache/letsencrypt_apache/tests/configurator_test.py", line 755, in test_enhance_unknown_vhost
    self.config.enhance, "satoshi.com", "redirect")
AssertionError: PluginError not raised

----------------------------------------------------------------------
Ran 73 tests in 21.146s

FAILED (failures=1)
```

**Comment by pde** [comment]
`git bisect` tells me it was caused by this: 109d6caf6525e1673e4d126bd1a73530645be9bf

**Comment by pde** [comment]
Which does look like a rather relevant change.

**Comment by pde** [comment]
Noah, do you want to take a look at this?

**Comment by pde** [comment]
I can repro consistently on my laptop, but not on obs7.  Which is pretty fishy...

**Comment by pde** [comment]
I lied. I can repro on obs7.

**Comment by SwartzCr** [comment]
I can't seem to get this to repro locally - though it does look like I minorly edited that test: https://github.com/letsencrypt/letsencrypt/pull/2489/files

**Comment by joohoi** [comment]
This seems to be reproducable on the default vagrant machine.

**Comment by SwartzCr** [comment]
@joohoi do you know if this is still a problem?

**Comment by SwartzCr** [comment]
pinging @joohoi again, as I've now totally lost track of the status of this potential issue

**Comment by joohoi** [comment]
This seems to be fine now. Closing the issue.
