### ISSUE TITLE
"Cert not yet due for renewal" but using --keep-until-expiring

### ISSUE THREAD

**Issue by Aranad** [certbot/certbot#2882]
I'm getting an "Exiting abnormally" condition with "Cert not yet due for renewal" every day, but I'm using the --keep-until-expiring option so this shouldn't be happening - and actually it only started happening within the last couple of months.

**Comment by bmw** [comment]
Can you provide the output or logfile? "Cert not yet due for renewal" wouldn't cause the "Exiting abnormally" message so there is something else going on.

Seeing "Cert not due for renewal" when using `--keep-until-expiring` is expected though. It's keeping your existing certificate because it isn't close to expiration.

**Comment by Aranad** [comment]
2016-05-02 07:00:02,158:DEBUG:letsencrypt.main:Root logging level set at 30
2016-05-02 07:00:02,159:INFO:letsencrypt.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-05-02 07:00:02,159:DEBUG:letsencrypt.main:letsencrypt version: 0.5.0
2016-05-02 07:00:02,159:DEBUG:letsencrypt.main:Arguments: ['--keep-until-expiring', '--expand', '--webroot', '-w', '/var/www/domains/letsencrypt', '-d', 'organicdesign.co.nz', '-d', 'www.organicdesign.co.nz' ... ]
2016-05-02 07:00:02,159:DEBUG:letsencrypt.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-05-02 07:00:02,161:DEBUG:letsencrypt.plugins.selection:Requested authenticator webroot and installer None
2016-05-02 07:00:02,163:DEBUG:letsencrypt.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = letsencrypt.plugins.webroot:Authenticator
Initialized: <letsencrypt.plugins.webroot.Authenticator object at 0x7f9f00d019d0>
Prep: True
2016-05-02 07:00:02,163:DEBUG:letsencrypt.plugins.selection:Selected authenticator <letsencrypt.plugins.webroot.Authenticator object at 0x7f9f00d019d0> and installer None
2016-05-02 07:00:02,254:DEBUG:letsencrypt.main:Picked account: <Account(92016cc0eddf575860420deafd267fee)>
2016-05-02 07:00:02,255:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-05-02 07:00:02,257:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-02 07:00:02,720:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2016-05-02 07:00:02,722:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Mon, 02 May 2016 07:00:33 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 02 May 2016 07:00:33 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'O3UDGGMo-3AbFLfsTxcMCzpoNXbwHLSd4H1ukKuiPDM'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-05-02 07:00:02,722:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Mon, 02 May 2016 07:00:33 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 02 May 2016 07:00:33 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'O3UDGGMo-3AbFLfsTxcMCzpoNXbwHLSd4H1ukKuiPDM'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-05-02 07:00:02,734:INFO:letsencrypt.renewal:Cert not yet due for renewal
2016-05-02 07:00:02,737:DEBUG:letsencrypt.main:Exiting abnormally:
Traceback (most recent call last):
  File "/home/nad/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/nad/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 692, in main
    return config.func(config, plugins)
  File "/home/nad/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 531, in obtain_cert
    notify("Certificate not yet due for renewal; no action taken.")
  File "/home/nad/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/display/util.py", line 73, in notification
    self.dialog.msgbox(message, height, width=self.width)
  File "/home/nad/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 3016, in msgbox
    kwargs)
  File "/home/nad/.local/share/letsencrypt/local/lib/python2.7/site-packages/dialog.py", line 1765, in _widget_with_no_output
    widget_name, output))
PythonDialogBug

**Comment by bmw** [comment]
The lack of a (more) useful error message is due to #2813. As a workaround to see what's going on you can:

1) Create a file named `test.py` with the following contents:
```
import dialog

try:
    dialog.Dialog().msgbox(
        "Certificate not yet due for renewal; no action taken.", 10, width=72)
except Exception as e:
    print e.message
```

2) Run `/home/nad/.local/share/letsencrypt/bin/python test.py`.

**Comment by evodicka** [comment]
I am experiencing the same behaviour. When I run your test script, I get only:
`expected an empty output from u'msgbox', but got: u'Error opening terminal: unknown.\n'`

**Comment by bmw** [comment]
@evodicka, how did you install `certbot`?

Regardless, one workaround is to just avoid the use of `dialog` entirely by providing `-t` or `--text` on the command line.

**Comment by evodicka** [comment]
certbot was installed either by cloning this repo or by downloading the `certbot-auto` script as described in the readme. Both installations run into the dialog problem.
However, the workaround using `-t` works for me

**Comment by Aranad** [comment]
The -t switch works for me too, thanks a lot. I'll leave it open though since it's a bug that it gives the error at all since --keep-until-expiring means that it shouldn't raise a "Cert not yet due for renewal" problem, and then shouldn't exit uncleanly.

**Comment by bmw** [comment]
> I'll leave it open though since it's a bug that it gives the error at all since --keep-until-expiring means that it shouldn't raise a "Cert not yet due for renewal" problem, and then shouldn't exit uncleanly.

Printing "Cert not due for renewal" is not a bug, its the intended behavior. Just to make sure we're on the same page, the help for `--keep-until-expiring` is shown below:
```
  --keep-until-expiring, --keep, --reinstall
                        If the requested cert matches an existing cert, always
                        keep the existing one until it is due for renewal (for
                        the 'run' subcommand this means reinstall the existing
                        cert) (default: False)
```
The addition of this flag causes the client to check whether or not the certificate is due for renewal. If it is, the client obtains a new cert, otherwise, you'll see the message "Cert not yet due for renewal" and the client will exit (potentially after reinstalling the certificate if using the `run` subcommand).

Printing this message does not cause the client to exit with a non-zero status. In your log above, the reason the client exited with a non-zero status is because it tried to open a ncurses dialog. 

Are you trying to run the client automatically using something like `cron`? Doing so would explain the Python dialog error. If so, I encourage you to look at our [renewal documentation](https://certbot.eff.org/docs/using.html#renewal) specifically the part about using the `-q/--quiet` flag to only provide error output.

Hope this helps!

**Comment by Aranad** [comment]
Yep that clears things up, thanks a lot.
