### ISSUE TITLE
./tools/venv.sh and ./tools/venv3.sh fail on Ubuntu 16.04, Python 2.7.11

### ISSUE THREAD

**Issue by TheNavigat** [certbot/certbot#2896]
Python version is 2.7.11

Here's everything printed.

```
+ command -v python2
/usr/bin/python2
+ export VENV_ARGS=--python python2
+ ./tools/_venv_common.sh -e acme[dev] -e .[dev,docs] -e certbot-apache -e certbot-nginx -e letshelp-certbot -e certbot-compatibility-test
+ VENV_NAME=venv
+ rm -rf *.egg-info
+ date +%s
+ mv venv venv.1461692822.bak
+ virtualenv --no-site-packages venv --python python2
Running virtualenv with interpreter /usr/bin/python2
New python executable in /root/letsencrypt/venv/bin/python2
Also creating executable in /root/letsencrypt/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
+ . ./venv/bin/activate
+ deactivate nondestructive
+ unset -f pydoc
+ [ -z  ]
+ [ -z  ]
+ [ -n  ]
+ [ -n  ]
+ [ -z  ]
+ unset VIRTUAL_ENV
+ [ ! nondestructive = nondestructive ]
+ VIRTUAL_ENV=/root/letsencrypt/venv
+ export VIRTUAL_ENV
+ _OLD_VIRTUAL_PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+ PATH=/root/letsencrypt/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+ export PATH
+ [ -z  ]
+ [ -z  ]
+ _OLD_VIRTUAL_PS1=# 
+ [ x != x ]
+ basename /root/letsencrypt/venv
+ PS1=(venv) # 
+ export PS1
+ alias pydoc
+ [ -n  ]
+ [ -n  ]
+ pip install -U setuptools
Requirement already up-to-date: setuptools in ./venv/lib/python2.7/site-packages
+ pip install -U pip
Requirement already up-to-date: pip in ./venv/lib/python2.7/site-packages
+ pip install -e acme[dev] -e .[dev,docs] -e certbot-apache -e certbot-nginx -e letshelp-certbot -e certbot-compatibility-test
Exception:
Traceback (most recent call last):
  File "/root/letsencrypt/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/root/letsencrypt/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wheel_cache
  File "/root/letsencrypt/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 280, in populate_requirement_set
    wheel_cache=wheel_cache
  File "/root/letsencrypt/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 136, in from_editable
    editable_req, default_vcs)
  File "/root/letsencrypt/venv/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1146, in parse_editable
    '__placeholder__' + extras
  File "/root/letsencrypt/venv/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2833, in parse
    req, = parse_requirements(s)
  File "/root/letsencrypt/venv/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2781, in parse_requirements
    yield Requirement(line)
  File "/root/letsencrypt/venv/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl/pkg_resources/__init__.py", line 2790, in __init__
    raise RequirementParseError(str(e))
RequirementParseError: Invalid requirement, parse error at "'__placeh'"
```

**Comment by r-marques** [comment]
Was having the same problem in an unrelated project running virtualenv version 15.0.1
Solved it by install virtualenv 15.0.0 with `pip install 'virtualenv==15.0.0'`

**Comment by TheNavigat** [comment]
Although I can't be 100% sure, but this bug looks close. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821223

Apparently, it's a reported bug, and it should be fixed soon.

**Comment by bmw** [comment]
Well, that Debian bug has been resolved and the issue persists. Not sure if it's a virtualenv bug, pip bug, or pkg_resources bug.

**Comment by bmw** [comment]
Using `pip install 'virtualenv==15.0.0` doesn't work for me, but a temporary workaround is to change [this line](https://github.com/letsencrypt/letsencrypt/blob/master/tools/_venv_common.sh#L21) to `pip install -U pip==8.1.0`.
