### ISSUE TITLE
Webroot Plugin: Cleanup Error

### ISSUE THREAD

**Issue by LukasGentele** [certbot/certbot#2905]
Hi! I'm using the letsencrypt client from a docker container with the following command:
`letsencrypt-auto certonly --agree-tos -m email@domain.com -d "domain.com" --webroot --webroot-path=/srv/www/letsencrypt`

The command fails with this error: 
`An unexpected error occurred:
OSError: [Errno 16] Device or resource busy: '/srv/www/letsencrypt/.well-known/acme-challenge'
Please see the logfiles in /var/log/letsencrypt for more details.`

The log file shows the exception that has been thrown here:
`2016-05-01 06:02:09,853:DEBUG:letsencrypt.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 692, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 509, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/main.py", line 93, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 274, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/client.py", line 246, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 74, in get_authorizations
    self._respond(resp, best_effort)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 134, in _respond
    self._cleanup_challenges(active_achalls)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/auth_handler.py", line 266, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/letsencrypt/plugins/webroot.py", line 234, in cleanup
    os.rmdir(root_path)
OSError: [Errno 16] Device or resource busy: '/srv/www/letsencrypt/.well-known/acme-challenge'`

Apparently it's related to the cleanup process. The interesting thing is that the text-file used for authorization actually is being deleted although the error implies otherwise. I commented out the following line:
https://github.com/letsencrypt/letsencrypt/blob/master/certbot/plugins/webroot.py#L234
Afterwards, everything worked as expected and even the text-file for authorization had been deleted (although that sounds strange to me). It looks like the removal of this file is being triggered multiple times.

I hope that helps you to narrow the problem down and fix it for further releases.

**Comment by Ti-webdev** [comment]
@LukasGentele
Is it /srv/www/letsencrypt/.well-known/acme-challenge mountpoint?
