### ISSUE TITLE
subprocess.CalledProcessError: on ubuntu 12.04 with python 2.7.3

### ISSUE THREAD

**Issue by Leo-G** [certbot/certbot#2948]
The current python version is 2.7.3 but I get the below error
 Installing Python packages...
    Traceback (most recent call last):
      File "/tmp/tmp.IFDfKVVN9X/pipstrap.py", line 146, in <module>
        exit(main())
      File "/tmp/tmp.IFDfKVVN9X/pipstrap.py", line 133, in main
        shell=True)
      File "/usr/lib/python2.7/subprocess.py", line 544, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U /tmp/pipstrap-P537CR/pip-8.0.3.tar.gz /tmp/pipstrap-P537CR/setuptools-20.2.2.tar.gz /tmp/pipstrap-P537CR/wheel-0.29.0.tar.gz' returned non-zero exit status 2
    user@vps:~/letsencrypt# python --version
    Python 2.7.3

Please let me know how I can fix this

**Comment by bmw** [comment]
@erikrose, any thoughts?

**Comment by SpotlightKid** [comment]
Probably your installed version of pip doesn't support one of the used options in the command, e.g. `--no-index` or  `--no-deps`. As a workaround, try updating pip manually, e.g. `sudo pip install -U pip`. Warning: this circumvents Ubuntu's package system and overwrites the files from the python-pip package.

**Comment by pde** [comment]
@Leo-G what version of `pip` do you have installed?

**Comment by n8henrie** [comment]
I'm also getting a similar error running Raspbian Jessie, Python 2.7.11, pip 8.1.2. The only difference is I'm getting `returned non-zero exit status 1` instead of `2`.

**Comment by n8henrie** [comment]
I copied the `/tmp/pipstrap-` directory before it was auto-deleted and tried manually running the `pip install` command on its contents, using the certbot-installed `pip` installation, which I think provides a clue as to what's going on in my case:

```
Unpacking ./pipstrap-dKT0oe/wheel-0.29.0.tar.gz
   Running setup.py (path:/tmp/pip-7EWCSs-build/setup.py) egg_info for package from file:///opt/tmp/pipstrap-dKT0oe/wheel-0.29.0.tar.gz
```
...A bunch of lines of copying stuff, then...
```
running install_lib
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-s6TDD_-build/setup.py", line 91, in <module>
    cmdclass={'test': PyTest},
  File "/opt/pyenv/versions/2.7.11/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/pyenv/versions/2.7.11/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/pyenv/versions/2.7.11/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/n8henrie/.local/share/letsencrypt/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/opt/pyenv/versions/2.7.11/lib/python2.7/distutils/command/install.py", line 575, in run
    self.run_command(cmd_name)
  File "/opt/pyenv/versions/2.7.11/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/opt/pyenv/versions/2.7.11/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/opt/pyenv/versions/2.7.11/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/home/n8henrie/.local/share/letsencrypt/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 16, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/opt/pyenv/versions/2.7.11/lib/python2.7/distutils/cmd.py", line 302, in set_undefined_options
    getattr(src_cmd_obj, src_option))
  File "/opt/pyenv/versions/2.7.11/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
    raise AttributeError, attr
AttributeError: install_layout
----------------------------------------
  Rolling back uninstall of pip
```

**Comment by n8henrie** [comment]
I got mine to work yesterday evening by specifying `/usr/bin/python` instead of my pyenv installed python2.

- Was **not** working: python 2.7.11, pip 8.1.2
- **Did** work: python 2.7.9, pip 8.1.2

The eventually installed venv versions:

```bash
$ ~/.local/share/letsencrypt/bin/python --version
Python 2.7.9  
$ ~/.local/share/letsencrypt/bin/python -m pip --version
pip 8.0.3
```

**Comment by AndrinS** [comment]
I'm currently facing the same issue. (error code 1)

Here are my current "versions":
```
$ ~/.local/share/letsencrypt/bin/python --version
Python 2.7.6
$ ~ # ~/.local/share/letsencrypt/bin/python -m pip --version
/root/.local/share/letsencrypt/bin/python: No module named pip
```

How do I install an older version of python?

**Comment by n8henrie** [comment]
@AndrinS Do may have an older python version already installed.

- Are you using pyenv?
- What do you get from `python --version`?
- What do you get from `/usr/bin/python --version`?

**Comment by AndrinS** [comment]
- Not that I know.
- Python 2.7.6
- Python 2.7.6

**Comment by n8henrie** [comment]
I don't think you're having the same problem that I did. Can you post your actual error output?

Are you sure you have pip installed? What do you get with `python -m pip --version`?

**Comment by AndrinS** [comment]
pip 1.5.6 from /usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg (python 2.7)


Actually let's continue over on #3080 because somehow the error code changed to exit status 2 again.

**Comment by bmw** [comment]
Since this hasn't seen any traffic in over two years, I'm closing the issue, however, if you're still hitting the problem, please let me know!
