### ISSUE TITLE
500 and deserialization error when trying to domain registration

### ISSUE THREAD

**Issue by proninyaroslav** [certbot/certbot#2955]
Error during the registration of the domain:
```
$ ./letsencrypt-auto --apache -d proninyaroslav.ru -d www.proninyaroslav.ru

An unexpected error occurred:
ClientError: (<Response [500]>, DeserializationError('The following field are required: detail',))
```
Fedora 23, Apache server.

Full log:
```
2016-05-10 16:53:14,651:DEBUG:letsencrypt.main:Root logging level set at 30
2016-05-10 16:53:14,652:INFO:letsencrypt.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-05-10 16:53:14,652:DEBUG:letsencrypt.main:letsencrypt version: 0.5.0
2016-05-10 16:53:14,652:DEBUG:letsencrypt.main:Arguments: ['--apache', '-d', 'proninyaroslav.ru', '-d', 'www.proninyaroslav.ru']
2016-05-10 16:53:14,653:DEBUG:letsencrypt.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-05-10 16:53:14,655:DEBUG:letsencrypt.plugins.selection:Requested authenticator apache and installer apache
2016-05-10 16:53:14,854:DEBUG:letsencrypt.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = letsencrypt_apache.configurator:ApacheConfigurator
Initialized: <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7f075cb22c50>
Prep: True
2016-05-10 16:53:14,855:DEBUG:letsencrypt.plugins.selection:Selected authenticator <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7f075cb22c50> and installer <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7f075cb22c50>
2016-05-10 16:53:25,274:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-05-10 16:53:25,276:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-10 16:53:25,897:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 263
2016-05-10 16:53:25,900:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '263', 'Expires': 'Tue, 10 May 2016 16:53:25 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 10 May 2016 16:53:25 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'UdVnh8JIwLV7xMfw_vLpxbRZS-nvTfLHvKYDmB_Wfkc'}. Content: '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-05-10 16:53:25,901:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '263', 'Expires': 'Tue, 10 May 2016 16:53:25 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 10 May 2016 16:53:25 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'UdVnh8JIwLV7xMfw_vLpxbRZS-nvTfLHvKYDmB_Wfkc'}): '{"new-authz":"https://acme-v01.api.letsencrypt.org/acme/new-authz","new-cert":"https://acme-v01.api.letsencrypt.org/acme/new-cert","new-reg":"https://acme-v01.api.letsencrypt.org/acme/new-reg","revoke-cert":"https://acme-v01.api.letsencrypt.org/acme/revoke-cert"}'
2016-05-10 16:53:25,902:DEBUG:root:Requesting fresh nonce
2016-05-10 16:53:25,902:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-reg. args: (), kwargs: {}
2016-05-10 16:53:25,903:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-10 16:53:26,315:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-reg HTTP/1.1" 405 0
2016-05-10 16:53:26,317:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '78', 'Pragma': 'no-cache', 'Expires': 'Tue, 10 May 2016 16:53:26 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 10 May 2016 16:53:26 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '-OjRvBp7mc1Rg4t-xHO5BRMOq-zwUadRqzzuz8jOB-4'}. Content: ''
2016-05-10 16:53:26,318:DEBUG:acme.client:Storing nonce: '\xf8\xe8\xd1\xbc\x1a{\x99\xcdQ\x83\x8b~\xc4s\xb9\x05\x13\x0e\xab\xec\xf0Q\xa7Q\xab<\xee\xcf\xc8\xce\x07\xee'
2016-05-10 16:53:26,318:DEBUG:acme.jose.json_util:Omitted empty fields: key=None, agreement=None, authorizations=None, certificates=None
2016-05-10 16:53:26,318:DEBUG:acme.client:Serialized JSON: {"contact": ["mailto:proninyaroslav@mail.ru"], "resource": "new-reg"}
2016-05-10 16:53:26,319:DEBUG:acme.jose.json_util:Omitted empty fields: kid=None, x5c=(), crit=(), jwk=None, typ=None, alg=None, jku=None, cty=None, x5tS256=None, x5u=None, x5t=None
2016-05-10 16:53:26,321:DEBUG:acme.jose.json_util:Omitted empty fields: kid=None, x5c=(), crit=(), typ=None, jku=None, cty=None, x5tS256=None, x5u=None, x5t=None, nonce=None
2016-05-10 16:53:26,321:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-reg. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "yI1a2NKSiDYrIokPhzbn1fiQ6gQ9-m2_0_BqIey_GkjCemGIbMTQOIll3yuUriU_QGZixt3meE-zleIp0VsAClEWa8X_17LI5bs5jMQWE1HkCJjrhltGY4Qghlm3UzNynJmGxicZBRD9brmesr_lKUrPFrOgnA1-d3dYyIUNA0wTZko1n7yG4R5MrD5-SaEvqm1lfKLj1Ce0xGtB9n9ZDRQbUqAnMfYTJ56-slbPtfvg8psOkOrsivA5zM0a9O-XOMFM-FIbNpHHmx-D4stUqdMCIb-62B8MquUjgUlpgZB9efeK796LN4svFW5WxKHPInL5tihSjKVMcrqy2CW19Q"}}, "protected": "eyJub25jZSI6ICItT2pSdkJwN21jMVJnNHQteEhPNUJSTU9xLXp3VWFkUnF6enV6OGpPQi00In0", "payload": "eyJjb250YWN0IjogWyJtYWlsdG86cHJvbmlueWFyb3NsYXZAbWFpbC5ydSJdLCAicmVzb3VyY2UiOiAibmV3LXJlZyJ9", "signature": "IlwrUhhmpjj4F_2GE98bKNkjxK7-FwILxzokjZ4JWw4tnpO1tENdy4nU4j0XYjvCfn-WPgJsiYAVxBGzh1mKSNCHoN99i6fzQ8foSjO-Hyijq44o114UnISDOoRCP0FY2HyEulR5AmToVbLMg1H8eA9Eah5azAinD_mk9L3s8VhyY_pBA1PSe3nOqfxlZMn-YG8gpg4-DalorQhnslZMVLbMRZdAGw5aio4djeFmEhiWq0aHBjVKxyB7wgYESancvDlZ-ZA5DRBioZLGoOsuCosbp1-hEf4BVKHAtdiBzQFs3oyLNlhBswv3T0sCYao1P30y7bPvXw1AJk1LhvPZQQ"}'}
2016-05-10 16:53:26,322:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-05-10 16:53:26,882:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-reg HTTP/1.1" 500 53
2016-05-10 16:53:26,886:DEBUG:root:Received <Response [500]>. Headers: {'Content-Length': '53', 'Expires': 'Tue, 10 May 2016 16:53:26 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 10 May 2016 16:53:26 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'zuZno4_zVB6mPy6rz1f4PbVeHfitNgAzVVlFzBKvv8E'}. Content: '{"type":"urn:acme:error:serverInternal","status":500}'
2016-05-10 16:53:26,888:DEBUG:acme.client:Storing nonce: '\xce\xe6g\xa3\x8f\xf3T\x1e\xa6?.\xab\xcfW\xf8=\xb5^\x1d\xf8\xad6\x003UYE\xcc\x12\xaf\xbf\xc1'
2016-05-10 16:53:26,888:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '53', 'Expires': 'Tue, 10 May 2016 16:53:26 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 10 May 2016 16:53:26 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'zuZno4_zVB6mPy6rz1f4PbVeHfitNgAzVVlFzBKvv8E'}): '{"type":"urn:acme:error:serverInternal","status":500}'
2016-05-10 16:53:26,890:DEBUG:letsencrypt.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/main.py", line 692, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/main.py", line 455, in run
    le_client = _init_le_client(config, authenticator, installer)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/main.py", line 356, in _init_le_client
    acc, acme = _determine_account(config)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/main.py", line 341, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 119, in register
    regr = perform_registration(acme, config)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/letsencrypt/client.py", line 149, in perform_registration
    return acme.register(messages.NewRegistration.from_data(email=config.email))
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 98, in register
    response = self.net.post(self.directory[new_reg], new_reg)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 652, in post
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 571, in _check_response
    raise errors.ClientError((response, error))
ClientError: (<Response [500]>, DeserializationError('The following field are required: detail',))
```

**Comment by gparent** [comment]
I'm wondering if this is a server failure, because I'm getting the same issue.

Gotta love short expiry times in situations like this...

See thread here giving same symptoms:

https://community.letsencrypt.org/t/deserialization-and-500-error-when-trying-to-renew-with-dry-run/14316

**Comment by proninyaroslav** [comment]
@gparent 
Suggest an attempt to repeat registration or it doesn't help?

**Comment by benjamingrobertson** [comment]
I am having this issue as well.

**Comment by benjamingrobertson** [comment]
Well, I was having this issue. I was able to get a cert when I tried again just now. Didn't change any config on my part.

**Comment by proninyaroslav** [comment]
@benjamingrobertson 
Yes, I did it at the third attempt.

**Comment by jsha** [comment]
Fixed by #2797

**Comment by pde** [comment]
Fix landed for 0.6.0

**Comment by vbotka** [comment]
For the record.

Yesterday I found the error:
2016-07-10 21:17:09,152:WARNING:letsencrypt.renewal: ... produced an unexpected error: (<Response [500]>, DeserializationError('The following field are required: detail',)). Skipping.

There was no error today.

**Comment by jsha** [comment]
@vbotka: What version of the client are you running?

**Comment by adamseoul** [comment]
Just wanted to leave a note that yes as others have said if this happens pls try again in a few min

**Comment by jsha** [comment]
Also, if this happens check https://letsencrypt.status.io/ to see if there is any current outage.
