### ISSUE TITLE
something is wrong

### ISSUE THREAD

**Issue by koppi** [certbot/certbot#2969]
```bash
koppi@x220:~/letsencrypt$ ./letsencrypt-auto --help
Checking for new version...
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2364, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 989, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/koppi/.local/s...ncrypt/bin/python2.7 - setuptools pkg_resources _markerlib pip wheel failed with error code 1
koppi@x220:~/letsencrypt$ uname -a
Linux x220 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
koppi@x220:~/letsencrypt$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04 (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
koppi@x220:~/letsencrypt$ 
```

**Comment by pde** [comment]
Yes, it shouldn't be using python3 libraries.  @erikrose, have any theories about this?

**Comment by pde** [comment]
Meanwhile, you can do: `sudo apt-get install letsencrypt` on xenial.  Also install `python-letsencrypt-apache` if you'd like to use the Apache plugin.

**Comment by koppi** [comment]
@pde Thank's for the tip with apt-get install. That works for me. Should I close this issue, then?

**Comment by bmw** [comment]
Glad you were able to get it working. I think we should leave this issue open because while the OS packages on Xenial should be preferred, `letsencrypt-auto` should still work.

**Comment by koppi** [comment]
I think, this issue can be closed, it probably was some sort of python path miss-configuration on my side. An install from a fresh Ubuntu 16.04 worked as expected.
