### ISSUE TITLE
--dry-run on renew didn't work

### ISSUE THREAD

**Issue by AleksCee** [certbot/certbot#2977]
Hello,

I just try to test the renew like this:
./letsencrypt-auto renew -v --dry-run
and the log says:

```
2016-05-12 21:03:20,463:DEBUG:certbot.main:Root logging level set at 20
2016-05-12 21:03:20,464:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-05-12 21:03:20,464:DEBUG:certbot.main:certbot version: 0.6.0
2016-05-12 21:03:20,464:DEBUG:certbot.main:Arguments: ['-v', '--dry-run']
2016-05-12 21:03:20,464:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-05-12 21:03:20,465:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 693, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 538, in renew
    renewal.renew_all_lineages(config)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 305, in renew_all_lineages
    raise errors.Error("Currently, the renew verb is only capable of "
Error: Currently, the renew verb is only capable of renewing all installed certificates that are due to be renewed; individual domains cannot be specified with this action. If you would like to renew specific certificates, use the certonly command. The renew verb may provide other options for selecting certificates to renew in the future.
```

I use a cli.ini with 
authenticator = webroot
webroot-map = {....some domains which are correctly installed with certonly command }

Any idea?

Thanks, Alex

**Comment by pde** [comment]
Thanks for this bug report! Related: #2305

The available workarounds should be:

1.test and renew with `certonly` rather than `renew` (see [the docs](https://certbot.eff.org/docs/using.html#renewal) for a full writeup): 
2. remove the `webroot-map` from cli.ini

**Comment by rkmax** [comment]
@pde  I'm getting the following error

    .conf produced an unexpected error: Failed authorization procedure. www.mydomain.com (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain

I tested from the browser I have access. I'm wondering if it's because I have a redirect from http to https

example certbot try to fetch a file from

    http://www.mydomain.com/.well-known/acme-challenge/0mxXzrutzBAg2zyRjwH3pnsypbUDUCb2SIS55COiRd4

is it possible that certbot doesn't follow the redirect link?

**Comment by bmw** [comment]
@rkmax, that error comes from the Let's Encrypt CA and it does follow redirects from HTTP to HTTPS. Are you still having the problem?

**Comment by rkmax** [comment]
@bmw Yes, the issue still is happening

**Comment by bmw** [comment]
OK. The more information you provide, the better I can help you. For instance, which plugin are you using? Can you provide log files (found in `/var/log/letsencrypt` by default)? Are the files in `.well-known/acme-challenge` still there? If so, do you mind giving me the domain you're experiencing the error for so I can look at it myself? You can provide this information here or e-mail me at bmw@eff.org.

Also, if you want more real time help, I recommend you visit https://community.letsencrypt.org or the #letsencrypt IRC channel on Freenode.

If you prefer to continue to get help through GitHub, it's probably best that you open a new issue. The problem you're experiencing is different from the one reported here.
