### ISSUE TITLE
Stacktrace when running renew --force-renew from crontab.

### ISSUE THREAD

**Issue by EntityReborn** [certbot/certbot#2982]
Running `* * * * * cd /root/certbot/ && ./certbot-auto renew --dry-run` from crontab causes the following stacktrace:

```
2016-05-13 06:12:02,698:DEBUG:certbot.main:Root logging level set at 30
2016-05-13 06:12:02,699:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-05-13 06:12:02,700:DEBUG:certbot.main:certbot version: 0.6.0
2016-05-13 06:12:02,700:DEBUG:certbot.main:Arguments: ['--dry-run']
2016-05-13 06:12:02,700:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,Plugi$
2016-05-13 06:12:02,720:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7fbccfaf1ad0> and installer <certbot.cli._Default object at 0x7fb$
2016-05-13 06:12:02,720:DEBUG:certbot.cli:Default Detector is Namespace(account=<certbot.cli._Default object at 0x7fbccfb448d0>, agree_dev_preview=None, allow_subset_of_names=<cer$
2016-05-13 06:12:02,727:INFO:certbot.renewal:Cert not due for renewal, but simulating renewal for dry run
2016-05-13 06:12:02,739:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2016-05-13 06:12:02,743:DEBUG:certbot.plugins.disco:No installation (PluginEntryPoint#apache):
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 105, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 152, in prepare
    raise errors.NoInstallationError
NoInstallationError
2016-05-13 06:12:02,744:DEBUG:certbot.plugins.selection:No candidate plugin
2016-05-13 06:12:02,744:DEBUG:certbot.plugins.selection:No candidate plugin
2016-05-13 06:12:02,744:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
2016-05-13 06:12:02,744:INFO:certbot.main:Could not choose appropriate plugin: The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError()
2016-05-13 06:12:02,745:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/l<redacted>.conf produced an unexpected error: The apache plugin i$
The error was: NoInstallationError(). Skipping.
2016-05-13 06:12:02,745:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 342, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 500, in obtain_cert
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 196, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 273, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
PluginSelectionError: The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError()

2016-05-13 06:12:02,746:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 693, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 538, in renew
    renewal.renew_all_lineages(config)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 359, in renew_all_lineages
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)
```

Running the above command properly in a shell, this error isn't generated, and the dry-test runs successfully.

apachectl -V:
```
[Fri May 13 01:24:49.831599 2016] [proxy_html:notice] [pid 4955:tid 139940341507968] AH01425: I18n support in mod_proxy_html requires mod_xml2enc. Without it, non-ASCII characters in proxied pages are likely to display incorrectly.
Server version: Apache/2.4.12 (Ubuntu)
Server built:   Jul 24 2015 15:59:00
Server's Module Magic Number: 20120211:41
Server loaded:  APR 1.5.2, APR-UTIL 1.5.4
Compiled using: APR 1.5.1, APR-UTIL 1.5.4
Architecture:   64-bit
Server MPM:     event
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"
```

Git pull was from today.

**Comment by joohoi** [comment]
Did you get this solved after the IRC discussion?

**Comment by EntityReborn** [comment]
Thank you, yes I did. The resolve was to copy my commands to a script, and start the script with the same PATH= line as what running `env` in an interactive shell quotes. Once I did this, logs indicated no errors while dry-run-renewing the cert.
