### ISSUE TITLE
Resizing PuTTY window causes crash for certbot-auto in FreeBSD jail

### ISSUE THREAD

**Issue by voltagex** [certbot/certbot#3030]
```
2016-05-19 10:57:30,211:INFO:certbot.auth_handler:http-01 challenge for test.voltagex.org
2016-05-19 10:57:38,998:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 108, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 72, in perform
    self._set_webroots(achalls)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 90, in _set_webroots
    known_webroots)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 107, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 141, in _prompt_for_new_webroot
    "Input the webroot for {0}:".format(domain))
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/display/util.py", line 198, in directory_select
    height=self.height, help_button=True, title=message)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 2407, in dselect
    kwargs, raw_help=True)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1746, in _widget_with_string_output
    code, output = self._perform(args, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1541, in _perform
    args_file)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1502, in _handle_program_exit
    child_output_rfd)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1454, in _wait_for_program_termination
    child_output.strip()))
DialogError

2016-05-19 10:57:38,999:DEBUG:certbot.error_handler:Calling registered functions
2016-05-19 10:57:38,999:INFO:certbot.auth_handler:Cleaning up challenges
2016-05-19 10:57:39,005:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 693, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 509, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 93, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 275, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 246, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 70, in get_authorizations
    resp = self._solve_challenges()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 108, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 72, in perform
    self._set_webroots(achalls)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 90, in _set_webroots
    known_webroots)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 107, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 141, in _prompt_for_new_webroot
    "Input the webroot for {0}:".format(domain))
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/display/util.py", line 198, in directory_select
    height=self.height, help_button=True, title=message)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 2407, in dselect
    kwargs, raw_help=True)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1746, in _widget_with_string_output
    code, output = self._perform(args, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1541, in _perform
    args_file)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1502, in _handle_program_exit
    child_output_rfd)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1454, in _wait_for_program_termination
    child_output.strip()))
DialogError
```

**Comment by pde** [comment]
Can you get the same crash by running `dialog` from the command line, without `certbot` at all? Eg just run `dialog --inputbox Thing 20 80` and then resize the window?

**Comment by voltagex** [comment]
Sorry for the late response to this. Can't repro with `dialog`, nor with `certbot 0.8.1`. My report here doesn't have enough info to work out how I triggered the bug in the first place ;/
