### ISSUE TITLE
Permissions error during pip installation - OS X 

### ISSUE THREAD

**Issue by DjKiDD** [certbot/certbot#3051]
```
tangerine:Scripts admin$ curl -O https://dl.eff.org/certbot-auto
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 43233  100 43233    0     0  54902      0 --:--:-- --:--:-- --:--:-- 54864
tangerine:Scripts admin$ chmod a+x certbot-auto
tangerine:Scripts admin$ ./certbot-auto
WARNING: Mac OS X support is very experimental at present...
if you would like to work on improving it, please ensure you have backups
and then run this script again with the --debug flag!
tangerine:Scripts admin$ ./certbot-auto --debug
Bootstrapping dependencies via Mac OS X...
No Homebrew/MacPorts; installing Homebrew...
==> This script will install:
/usr/local/bin/brew
/usr/local/Library/...
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
==> The following directories will be made group writable:
/usr/local/.
==> The following directories will have their owner set to admin:
/usr/local/.
==> The following directories will have their group set to admin:
/usr/local/.

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/.

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
==> /usr/bin/sudo /usr/sbin/chown admin /usr/local/.
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/.
==> /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown admin /Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Counting objects: 487, done.
remote: Compressing objects: 100% (441/441), done.
remote: Total 487 (delta 27), reused 331 (delta 17), pack-reused 0
Receiving objects: 100% (487/487), 771.99 KiB | 0 bytes/s, done.
Resolving deltas: 100% (27/27), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
HEAD is now at 375efe0 Remove LLVM-GCC support. (#252)
==> Tapping homebrew/core
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 3706, done.
remote: Compressing objects: 100% (3587/3587), done.
remote: Total 3706 (delta 13), reused 2502 (delta 9), pack-reused 0
Receiving objects: 100% (3706/3706), 2.87 MiB | 3.66 MiB/s, done.
Resolving deltas: 100% (13/13), done.
Checking connectivity... done.
Tapped 3583 formulae (3,732 files, 8.9M)
==> Installation successful!
==> Next steps
Run `brew help` to get started
Further documentation: https://git.io/brew-docs
==> Homebrew has enabled anonymous aggregate user behavior analytics
Read the analytics documentation (and how to opt-out) here:
  https://git.io/brew-analytics
==> Installing dependencies for augeas: libxml2, deadline
==> Installing augeas dependency: libxml2
==> Downloading https://homebrew.bintray.com/bottles/libxml2-2.9.3.el_capitan.b
######################################################################## 100.0%
==> Pouring libxml2-2.9.3.el_capitan.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libxml2/lib
    CPPFLAGS: -I/usr/local/opt/libxml2/include

==> Summary
🍺  /usr/local/Cellar/libxml2/2.9.3: 276 files, 9.8M
==> Installing augeas dependency: deadline
==> Downloading https://homebrew.bintray.com/bottles/readline-6.3.8.el_capitan.
######################################################################## 100.0%
==> Pouring readline-6.3.8.el_capitan.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.


Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/6.3.8: 46 files, 2.0M
==> Installing augeas
==> Downloading https://homebrew.bintray.com/bottles/augeas-1.4.0.el_capitan.bo
######################################################################## 100.0%
==> Pouring augeas-1.4.0.el_capitan.bottle.1.tar.gz
==> Caveats
Lenses have been installed to:
  /usr/local/share/augeas/lenses/dist
==> Summary
🍺  /usr/local/Cellar/augeas/1.4.0: 422 files, 3.0M
==> Downloading https://homebrew.bintray.com/bottles/dialog-1.3-20160209.el_cap
######################################################################## 100.0%
==> Pouring dialog-1.3-20160209.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/dialog/1.3-20160209: 13 files, 815.7K
pip not installed
Installing pip...
Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 551kB/s 
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 5.3MB/s 
Installing collected packages: pip, wheel
Exception:
Traceback (most recent call last):
  File "/var/folders/lj/x_6n9rg90_s9j5hvg1t1z9sr0000gn/T/tmp05p1Hh/pip.zip/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/var/folders/lj/x_6n9rg90_s9j5hvg1t1z9sr0000gn/T/tmp05p1Hh/pip.zip/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/var/folders/lj/x_6n9rg90_s9j5hvg1t1z9sr0000gn/T/tmp05p1Hh/pip.zip/pip/req/req_set.py", line 742, in install
    **kwargs
  File "/var/folders/lj/x_6n9rg90_s9j5hvg1t1z9sr0000gn/T/tmp05p1Hh/pip.zip/pip/req/req_install.py", line 831, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/var/folders/lj/x_6n9rg90_s9j5hvg1t1z9sr0000gn/T/tmp05p1Hh/pip.zip/pip/req/req_install.py", line 1032, in move_wheel_files
    isolated=self.isolated,
  File "/var/folders/lj/x_6n9rg90_s9j5hvg1t1z9sr0000gn/T/tmp05p1Hh/pip.zip/pip/wheel.py", line 346, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/var/folders/lj/x_6n9rg90_s9j5hvg1t1z9sr0000gn/T/tmp05p1Hh/pip.zip/pip/wheel.py", line 317, in clobber
    ensure_dir(destdir)
  File "/var/folders/lj/x_6n9rg90_s9j5hvg1t1z9sr0000gn/T/tmp05p1Hh/pip.zip/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makers
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pip'

```

**Comment by DomT4** [comment]
You can't write to `/Library` on OS X without `sudo`.

The script attempts to prevent this by installing a Homebrew/MacPorts/etc Python but doesn't get that far becase the system Python check for OS X El Cap is broken. This was very likely fixed by https://github.com/certbot/certbot/commit/4cb35eaeb346e11963c59fd4aa5170a7e01f7190 but that doesn't seem to have made it into the `certbot-auto` master script yet.

**Comment by bmw** [comment]
We're deprecating and removing macOS support from `certbot-auto`/`letsencrypt-auto` (see #4520). Instead, users should use Homebrew or MacPorts to install Certbot. Instructions for doing this with Homebrew can be found [here](https://certbot.eff.org/#osx-other).
