### ISSUE TITLE
An unexpected error occurred

### ISSUE THREAD

**Issue by Norcoen** [certbot/certbot#3059]
Machine: Ubuntu 14.04 64bit LXC Container on proxmox
Used this tutorial: https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-14-04
and this:
https://webnugget.de/setting-up-gitlab-with-free-ssl-certs-from-lets-encrypt-on-ubuntu-14-04/

After usage of letsencrypt-auto I get the following error in certbot.log:

```
root@gitlab:/etc/letsencrypt# /opt/letsencrypt/letsencrypt-auto certonly -c /root/letsencrypt-config/gitlab.ini
Checking for new version...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Requesting root privileges to run certbot...
   /root/.local/share/letsencrypt/bin/letsencrypt certonly -c /root/letsencrypt-config/gitlab.ini
An unexpected error occurred:
TypeError: __new__() takes exactly 8 arguments (1 given)
Please see the logfile 'certbot.log' for more details.
```

```
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 646, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 174, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 33, in __init__
    self.plugin_cls = entry_point.load()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/standalone.py", line 19, in <module>
    from certbot.plugins import util
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/util.py", line 5, in <module>
    import psutil
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/psutil/__init__.py", line 1416, in <module>
    _last_cpu_times = cpu_times()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/psutil/__init__.py", line 1411, in cpu_times
    return _psplatform.cpu_times()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/psutil/_pslinux.py", line 254, in cpu_times
    return scputimes(*fields)
TypeError: __new__() takes exactly 8 arguments (1 given)
certbot.log (END)
```

**Comment by Norcoen** [comment]
Weird, I just ran the command again, now getting a different error,
ran it again, different error again.

It seems to depend on which directory I'm currently in when virtualenv is called

**Comment by blackfyre** [comment]
Got the same error 😢 

```bash
homeassistant@gatekeeper:~/certbot$ ./certbot-auto certonly --standalone --preferred-challenges http-01 --email me@domain.com -d my.ddns.com
Requesting root privileges to run certbot...
  /home/homeassistant/.local/share/letsencrypt/bin/letsencrypt certonly --standalone --preferred-challenges http-01 --email me@domain.com -d my.ddns.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Please read the Terms of Service at
https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf. You must agree
in order to register with the ACME server at
https://acme-v01.api.letsencrypt.org/directory
-------------------------------------------------------------------------------
(A)gree/(C)ancel: a
An unexpected error occurred:
The server experienced an internal error :: Unable to update registration
Please see the logfiles in /var/log/letsencrypt for more details.
```

And in the log file:
```
2017-08-09 06:10:27,799:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/home/homeassistant/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/homeassistant/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 753, in main
    return config.func(config, plugins)
  File "/home/homeassistant/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 676, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/home/homeassistant/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 390, in _init_le_client
    acc, acme = _determine_account(config)
  File "/home/homeassistant/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 375, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/home/homeassistant/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 172, in register
    regr = acme.agree_to_tos(regr)
  File "/home/homeassistant/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 168, in agree_to_tos
    regr.update(body=regr.body.update(agreement=regr.terms_of_service)))
  File "/home/homeassistant/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 131, in update_registration
    updated_regr = self._send_recv_regr(regr, body=body)
  File "/home/homeassistant/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 106, in _send_recv_regr
    response = self.net.post(regr.uri, body)
  File "/home/homeassistant/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 682, in post
    return self._post_once(*args, **kwargs)
  File "/home/homeassistant/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 695, in _post_once
    return self._check_response(response, content_type=content_type)
  File "/home/homeassistant/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 582, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Unable to update registration
```

**Comment by cpu** [comment]
@blackfyre I suspect this problem was the result [of an outage event last night](https://letsencrypt.status.io/pages/incident/55957a99e800baa4470002da/598a267824308e1a05000183). Are you still seeing this error?

**Comment by blackfyre** [comment]
To honest, I've moved away from the certbot-auto solution and installed it from Jessie backport... that was working fine.

**Comment by schoen** [comment]
I suspect that this error probably can't happen any more, although it might be a form of problem with not giving useful error messages in case of certificate authority outages (tracked at https://github.com/certbot/certbot/issues/1249).

If anyone experiences this error again in the future, please mention it in issue #1249 if it's associated with a Let's Encrypt service outage (you can check at https://letsencrypt.status.io/), or open a new issue if it's not. Thanks!
