### ISSUE TITLE
OS detection may be causing a crash on OS X

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3139]
The PR #3124 contains the following crash report:

```
2016-06-04 16:54:31,737:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/Users/dosaygo/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 735, in main
    return config.func(config, plugins)
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 549, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 366, in _init_le_client
    return client.Client(config, acc, authenticator, installer, acme=acme)
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 184, in __init__
    acme = acme_from_config_key(config, self.account.key)
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 42, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 631, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 613, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/Users/dosaygo/.local/share/letsencrypt/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1096, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1035, in putheader
    raise ValueError('Invalid header value %r' % (one_value,))
ValueError: Invalid header value 'CertbotACMEClient/0.8.0 (darwin 10.11.5\n) Authenticator/manual Installer/None'
```

**Comment by bmw** [comment]
This is a dupe of #3120 which I believe was resolved in #3118. Is this correct @schoen?

**Comment by eviert** [comment]
I am not entirely sure if related: But I face the same issue in #3118 debug output below:

An unexpected error occurred:
ValueError: Invalid header value 'CertbotACMEClient/0.8.0 (darwin 10.10.5\n) Authenticator/standalone Installer/None'
Please see the logfiles in /var/log/letsencrypt for more details.
www1dev:certbot evier$ ./certbot-auto certonly --standalone --debug
Requesting root privileges to run certbot...
  /Users/evier/.local/share/letsencrypt/bin/letsencrypt certonly --standalone --debug
Traceback (most recent call last):
  File "/Users/evier/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 735, in main
    return config.func(config, plugins)
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 549, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 366, in _init_le_client
    return client.Client(config, acc, authenticator, installer, acme=acme)
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 184, in __init__
    acme = acme_from_config_key(config, self.account.key)
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 42, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 631, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 613, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/Users/evier/.local/share/letsencrypt/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1096, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1035, in putheader
    raise ValueError('Invalid header value %r' % (one_value,))
ValueError: Invalid header value 'CertbotACMEClient/0.8.0 (darwin 10.10.5\n) Authenticator/standalone Installer/None'

**Comment by bmw** [comment]
Yes this looks like the same error. The fix has been merged in `master` but has not been released yet. The patch will be included in the next release.

**Comment by eviert** [comment]
Thanks for the update! What is the current recommendation for those needing to use the client to obtain a cert prior to the release?
