### ISSUE TITLE
certbot 0.8.1- Apache2.4 - No vhost found (one host per file)

### ISSUE THREAD

**Issue by kokmok** [certbot/certbot#3175]
Hello,
certbot can not find my vhost on an apache 2.4 running on Ubuntu14.4.

Here is an exemple vhost.conf file content
`
< virtualHost *:80 >
        ServerAdmin xxx@xxx.com
    ServerName sub.domain.ltd
    ServerAlias sub.domain.ltd
        DocumentRoot /home/user/www
    SuexecUserGroup username usergroup
    <Directory />
        Options FollowSymLinks
        AllowOverride All
    </Directory>

```
<Directory /home/user/www>
    Options FollowSymLinks MultiViews
    AllowOverride All
    Require all granted
</Directory>

    ErrorLog /home/user/errors/error.log
LogLevel warn
    CustomLog ${APACHE_LOG_DIR}/access.log combined

   RewriteEngine on
   RewriteCond %{SERVER_NAME} =sub.domain.ltd
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,QSA,R=permanent]
```

</ virtualHost>
`

I just need to renew my certfificates but it's not working.

**Comment by bmw** [comment]
What command did you run? What was the error message? Are you able to provide a log where the problem occurred (they're found in `/var/log/letsencrypt` by default)?

**Comment by kokmok** [comment]
the renewing is finaly ok (my bad). But `./letsencrypt-auto` can't find vhost (that are well placed under /etc/apache2/sites-available).
`./letsencrypt-auto` log : 
`2016-06-16 07:53:03,415:DEBUG:certbot.main:Root logging level set at 30
2016-06-16 07:53:03,416:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-06-16 07:53:03,416:DEBUG:certbot.main:certbot version: 0.8.1
2016-06-16 07:53:03,416:DEBUG:certbot.main:Arguments: []
2016-06-16 07:53:03,416:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-06-16 07:53:03,419:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2016-06-16 07:53:04,786:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7f490174e810>
Prep: True
2016-06-16 07:53:04,786:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7f490174e810> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7f490174e810>
2016-06-16 07:53:06,436:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 498, in run
    domains = _find_domains(config, installer)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 265, in _find_domains
    raise errors.Error("Please specify --domains, or --installer that "
Error: Please specify --domains, or --installer that will help in domain names autodiscovery`

`./letsencrypt-auto -d sub.domain.ltd`
`2016-06-16 07:49:25,881:DEBUG:certbot.main:Root logging level set at 30
2016-06-16 07:49:25,881:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-06-16 07:49:25,881:DEBUG:certbot.main:certbot version: 0.8.1
2016-06-16 07:49:25,881:DEBUG:certbot.main:Arguments: ['-d', 'sub.domain.ltd']
2016-06-16 07:49:25,881:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-06-16 07:49:25,884:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2016-06-16 07:49:27,264:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7f7134655d90>
Prep: True
2016-06-16 07:49:27,265:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7f7134655d90> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7f7134655d90>
2016-06-16 07:49:27,366:DEBUG:certbot.main:Picked account: <Account(345c5ea4e845041c67efd068ef2937ec)>
2016-06-16 07:49:27,367:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-06-16 07:49:27,369:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-06-16 07:49:27,567:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 280
2016-06-16 07:49:27,568:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '280', 'Expires': 'Thu, 16 Jun 2016 07:49:27 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 16 Jun 2016 07:49:27 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'd9zMRk7gIINHxguwexI07T6NKYSCAvf6uMQMkGtYxHU'}. Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-06-16 07:49:27,568:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '280', 'Expires': 'Thu, 16 Jun 2016 07:49:27 GMT', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 16 Jun 2016 07:49:27 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'd9zMRk7gIINHxguwexI07T6NKYSCAvf6uMQMkGtYxHU'}): '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-06-16 07:49:27,577:INFO:certbot.renewal:Cert not yet due for renewal
2016-06-16 07:49:40,079:ERROR:certbot_apache.configurator:No vhost exists with servername or alias of: sub.domain.ltd. No vhost was selected. Please specify servernames in the Apache config
2016-06-16 07:49:40,087:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 369, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 223, in deploy_cert
    vhost = self.choose_vhost(domain)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 323, in choose_vhost
    return self._choose_vhost_from_list(target_name, temp)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 333, in _choose_vhost_from_list
    raise errors.PluginError("No vhost selected")
PluginError: No vhost selected

2016-06-16 07:49:40,087:DEBUG:certbot.error_handler:Calling registered functions
2016-06-16 07:49:40,090:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 507, in run
    lineage.chain, lineage.fullchain)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 369, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 223, in deploy_cert
    vhost = self.choose_vhost(domain)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 323, in choose_vhost
    return self._choose_vhost_from_list(target_name, temp)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 333, in _choose_vhost_from_list
    raise errors.PluginError("No vhost selected")
PluginError: No vhost selected
`

**Comment by joohoi** [comment]
This issue is filed against very old version of certbot-apache, and a lot has changed since. I'm closing this issue as most likely fixed, feel free to comment if the problem still persists in some form and we'll reopen the issue.
