### ISSUE TITLE
CentOS 6: ImportError: cannot import name HTTPSHandler

### ISSUE THREAD

**Issue by Kohera** [certbot/certbot#3245]
When using Certbot:

Nothing to do
Traceback (most recent call last):
  File "/tmp/tmp.GkQSuyHRCi/fetch.py", line 20, in <module>
    from urllib2 import build_opener, HTTPHandler, HTTPSHandler, HTTPError
ImportError: cannot import name HTTPSHandler
WARNING: unable to check for updates.
Creating virtual environment...
Installing Python packages...
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/apps/python2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "/tmp/tmp.YTKCWjjrSr/pipstrap.py", line 24, in <module>
    from hashlib import sha256
ImportError: cannot import name sha256

2016-07-06 13:08:31,247:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 108, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 72, in perform
    self._set_webroots(achalls)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 90, in _set_webroots
    known_webroots)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 107, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 141, in _prompt_for_new_webroot
    "Input the webroot for {0}:".format(domain))
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/display/util.py", line 203, in directory_select
    height=self.height, help_button=True, title=message)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 2407, in dselect
    kwargs, raw_help=True)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1746, in _widget_with_string_output
    code, output = self._perform(args, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1541, in _perform
    args_file)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1502, in _handle_program_exit
    child_output_rfd)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1454, in _wait_for_program_termination
    child_output.strip()))
DialogError

2016-07-06 13:08:31,247:DEBUG:certbot.error_handler:Calling registered functions
2016-07-06 13:08:31,247:INFO:certbot.auth_handler:Cleaning up challenges
2016-07-06 13:08:31,248:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 555, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 94, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 276, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 247, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 70, in get_authorizations
    resp = self._solve_challenges()
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 108, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 72, in perform
    self._set_webroots(achalls)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 90, in _set_webroots
    known_webroots)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 107, in _prompt_for_webroot
    webroot = self._prompt_for_new_webroot(domain)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 141, in _prompt_for_new_webroot
    "Input the webroot for {0}:".format(domain))
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/display/util.py", line 203, in directory_select
    height=self.height, help_button=True, title=message)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 2407, in dselect
    kwargs, raw_help=True)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1746, in _widget_with_string_output
    code, output = self._perform(args, **kwargs)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1541, in _perform
    args_file)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1502, in _handle_program_exit
    child_output_rfd)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/dialog.py", line 1454, in _wait_for_program_termination
    child_output.strip()))
DialogError

**Comment by pde** [comment]
It looks like you have several crazy errors during that run! But probably the one that's killing you is that the copy of urllib2 in your Python PATH is weird or old and doesn't include modern HTTPS support.

You can possibly confirm that by typing:
```
python
import urllib2
print urllib2.__file__
```

**Comment by pde** [comment]
@erikrose do you think there's any extra handling we should add for cases like this in the future?

**Comment by erikrose** [comment]
[urllib2 will have no HTTPSHandler iff Python was built without SSL support.](https://docs.python.org/2/library/urllib2.html#urllib2.build_opener) That's rare but possible, it appears. So it would be neighborly of us to import HTTPSHandler separately, catch any ImportError, and complain "Your version of Python was built without SSL support. Please [point me to a better version]."

**Comment by Logic-gate** [comment]
Okay, so I had a similar issue...I had to build python with SSl support. 

Instructions for a quick work around:

`yum install openssl`
`yum install openssl-devel`

Get python from `https://www.python.org/ftp/python`, pick a version `>2.7` but not `3::not tested` and make sure you don't have the same version installed. The thing is, I have `2.6` with SSL support, but the I think certbot wants `2.7+`.

`wget https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz` for example
`tar xvzf Python-2.7.9.tgz`
`nano Python-2.7.9/Modules/Setup.dist` --because vim was never meant for humans.
find the following lines and uncomment it so that they looks like this:

```
# Socket module helper for socket(2)
_socket socketmodule.c timemodule.c

# Socket module helper for SSL support; you must comment out the other
# socket line above, and possibly edit the SSL variable:
SSL=/usr/local/openssl
_ssl _ssl.c \
        -DUSE_SSL -I$(SSL)/include -I$(SSL)/include/openssl \
        -L$(SSL)/lib -lssl -lcrypto
```
That's it,
`./configure`
`make`
`make install`

If you get a path issue in `make`, when you edit `Setup.dist`, make sure to `cp` it to `Setup`. `make clean` will also advise you to do the same.

I didn't edit anything in certbot, it automatically recognized that latest version...kodos for that.

Hope this helps.

**Comment by Logic-gate** [comment]
@erikrose something like this would do the trick at the beginning of certbot; `python  -c "import ssl; print(ssl.OPENSSL_VERSION)"` Granted, not the cleanest of solutions.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
