### ISSUE TITLE
Cannot make it work on CentOS 7.2.1511. Please help!

### ISSUE THREAD

**Issue by dangtranhoang** [certbot/certbot#3270]
2016-07-11 07:55:59,299:WARNING:certbot.cli:You are running with an old copy of certbot that does not receive updates, and is less reliable than more recent versions. We recommend upgrading to the latest$
2016-07-11 07:55:59,308:DEBUG:certbot.main:certbot version: 0.8.1
2016-07-11 07:55:59,309:DEBUG:certbot.main:Arguments: ['--webroot', '-w', '/etc/letsencrypt/well-known-auto', '-d', 'cartas.com', '-d', 'www.cartas.com', '--agree-tos']
2016-07-11 07:55:59,309:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-07-11 07:55:59,314:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2016-07-11 07:55:59,319:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x2b9a610>
Prep: True
2016-07-11 07:55:59,319:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x2b9a610> and installer None
2016-07-11 07:55:59,346:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 550, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 360, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 345, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 117, in register
    backend=default_backend())))
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 40, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 27, in _available_backends
    "cryptography.backends"
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 37, in <module>
    from cryptography.hazmat.backends.openssl.x509 import _Certificate
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/x509.py", line 24, in <module>
    class _Certificate(object):
  File "/usr/lib64/python2.7/site-packages/cryptography/utils.py", line 23, in register_decorator
    verify_interface(iface, klass)
  File "/usr/lib64/python2.7/site-packages/cryptography/utils.py", line 43, in verify_interface
    actual = inspect.getargspec(getattr(klass, method))
  File "/usr/lib64/python2.7/inspect.py", line 815, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <method-wrapper '__ne__' of type object at 0x370f430> is not a Python function

**Comment by Pascal666** [comment]
Perhaps a Python dependency problem?  "pip list" will show you what versions are installed.  The below list is from one of my CentOS 7.2.1511 boxes that certbot just worked on.  You could try "pip install <module> --upgrade" if any of yours are older.  Note that this could easily break other python utilities on the same box.  Please let us know which one was causing the problem.

acme (0.8.1)
astroid (1.2.1)
attrs (15.2.0)
backports.ssl-match-hostname (3.4.0.2)
bitcointools (1.1.44)
bleach (1.4.2)
certbot (0.8.1)
cffi (0.8.6)
chardet (2.2.1)
ConfigArgParse (0.10.0)
configobj (4.7.2)
cryptography (0.8.2)
ecdsa (0.13)
enum34 (1.1.6)
fpconst (0.7.3)
gnupg (2.0.2)
html5lib (0.9999999)
idna (2.1)
iniparse (0.4)
ipaddress (1.0.16)
kitchen (1.1.1)
logilab-common (0.62.1)
M2Crypto (0.21.1)
miniupnpc (1.9)
mock (1.0.1)
ndg-httpsclient (0.3.2)
nose (1.3.0)
parsedatetime (1.5)
pip (7.1.0)
ply (3.4)
protobuf (3.0.0b2)
psutil (4.3.0)
pyasn1 (0.1.9)
pyasn1-modules (0.0.8)
pycparser (2.14)
pycurl (7.19.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pylint (1.3.1)
PyNaCl (1.0.1)
pyOpenSSL (0.15.1)
pyparsing (1.5.6)
pyRFC3339 (1.0)
pyserial (2.6)
pystun (0.1.0)
python-bitcoinlib (0.5.0)
python-libbitcoinclient (0.4.2)
python2-pythondialog (3.3.0)
pytz (2012d)
pyxattr (0.5.1)
pyzmq (15.2.0)
requests (2.6.0)
service-identity (16.0.0)
setuptools (24.0.2)
six (1.10.0)
SOAPpy (0.11.6)
Twisted (14.0.2)
Twisted-Core (12.2.0)
Twisted-Web (12.1.0)
txrestapi (0.2)
txrudp (0.5.1)
txWS (0.9.1)
urlgrabber (3.10)
urllib3 (1.10.2)
yum-metadata-parser (1.1.4)
zope.component (4.1.0)
zope.event (4.0.3)
zope.interface (4.0.5)

**Comment by dangtranhoang** [comment]
Hi @Pascal666, thanks for your info.

I re-run the script and it works. So definitely it's because of Python dependency. I did make an update before receiving your message so I don't know which dependency cause the problem. Here are all dependencies I update this morning:

cffi 
cryptography 
ndg-httpsclient 
parsedatetime 
perf 
ply 
psutil 
pyasn1 
pyOpenSSL 
python2-pythondialog 
pytz 
setuptools 
six 
urllib3 
zope.component 
zope.event 
zope.interface
