### ISSUE TITLE
AttributeError: 'module' object has no attribute 'DeprecatedIn12'

### ISSUE THREAD

**Issue by Pascal666** [certbot/certbot#3278]
New install on fully patched CentOS 7:

2016-07-12 06:48:14,575:DEBUG:certbot.main:Root logging level set at 30
2016-07-12 06:48:14,576:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-07-12 06:48:14,576:WARNING:certbot.cli:You are running with an old copy of certbot that does not receive updates, and is less reliable than more recent versions. We recommend upgrading to the latest certbot-auto script, or using native OS packages.
2016-07-12 06:48:14,596:DEBUG:certbot.main:certbot version: 0.8.1
2016-07-12 06:48:14,596:DEBUG:certbot.main:Arguments: ['-a', 'webroot', '--webroot-path=/usr/share/nginx/html', '-d', 'www.google.com']
2016-07-12 06:48:14,597:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-07-12 06:48:14,605:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2016-07-12 06:48:14,617:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x1640b50>
Prep: True
2016-07-12 06:48:14,617:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x1640b50> and installer None
2016-07-12 06:48:21,704:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 550, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 360, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 345, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 117, in register
    backend=default_backend())))
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 40, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 27, in _available_backends
    "cryptography.backends"
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 37, in <module>
    from cryptography.hazmat.backends.openssl.x509 import _Certificate
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/x509.py", line 18, in <module>
    from cryptography import utils, x509
  File "/usr/lib64/python2.7/site-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
File "/usr/lib64/python2.7/site-packages/cryptography/x509/base.py", line 15, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib64/python2.7/site-packages/cryptography/x509/extensions.py", line 20, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/usr/lib64/python2.7/site-packages/cryptography/x509/general_name.py", line 18, in <module>
    from cryptography.x509.name import Name
  File "/usr/lib64/python2.7/site-packages/cryptography/x509/name.py", line 10, in <module>
    from cryptography.x509.oid import NameOID, ObjectIdentifier
  File "/usr/lib64/python2.7/site-packages/cryptography/x509/oid.py", line 101, in <module>
    utils.DeprecatedIn12
AttributeError: 'module' object has no attribute 'DeprecatedIn12'

**Comment by Pascal666** [comment]
I was able to get past this error by upgrading cryptography from 1.3.1 to 1.4.:

# pip install cryptography --upgrade
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting cryptography
  Downloading cryptography-1.4.tar.gz (399kB)
    100% |################################| 401kB 515kB/s
Requirement already up-to-date: idna>=2.0 in /usr/lib/python2.7/site-packages (from cryptography)
Requirement already up-to-date: pyasn1>=0.1.8 in /usr/lib/python2.7/site-packages (from cryptography)
Requirement already up-to-date: six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography)
Collecting setuptools>=11.3 (from cryptography)
  Downloading setuptools-24.0.2-py2.py3-none-any.whl (441kB)
    100% |################################| 442kB 830kB/s
Collecting enum34 (from cryptography)
  Downloading enum34-1.1.6-py2-none-any.whl
Requirement already up-to-date: ipaddress in /usr/lib/python2.7/site-packages (from cryptography)
Collecting cffi>=1.4.1 (from cryptography)
  Downloading cffi-1.7.0.tar.gz (400kB)
    100% |################################| 401kB 751kB/s
Requirement already up-to-date: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography)
Installing collected packages: setuptools, enum34, cffi, cryptography
  Found existing installation: setuptools 20.6.7
    Uninstalling setuptools-20.6.7:
      Successfully uninstalled setuptools-20.6.7
  Found existing installation: enum34 1.1.2
    Uninstalling enum34-1.1.2:
      Successfully uninstalled enum34-1.1.2
  Found existing installation: cffi 1.5.2
    Uninstalling cffi-1.5.2:
      Successfully uninstalled cffi-1.5.2
  Running setup.py install for cffi
  Found existing installation: cryptography 1.3.1
    Uninstalling cryptography-1.3.1:
      Successfully uninstalled cryptography-1.3.1
  Running setup.py install for cryptography
Successfully installed cffi-0.8.6 cryptography-0.8.2 enum34-1.1.6 setuptools-24.0.2

**Comment by bmw** [comment]
@Pascal666, there are [OS packages](https://certbot.eff.org/#centosrhel7-other) available in EPEL7 which should be preferred over `certbot-auto`. The script should still work though.

@alex, do you have any thoughts on what would be causing this?

**Comment by Pascal666** [comment]
Yes, the above was using the OS package:
Installed Packages
certbot.noarch                         0.8.1-1.el7                         @epel

**Comment by alex** [comment]
I just downloaded cryptography 1.3.1 from PyPI, and `utils` definitely exposes the name `DeprecatedIn12`. Where did you install your cryptography from?

**Comment by Pascal666** [comment]
Yum:
python-cryptography.x86_64            0.8.2-1.el7                      @base

Is there some way to tell if another python package modified what yum installed?

**Comment by bmw** [comment]
Ah. Sorry. Didn't realize you were using the OS packages. The `pip install` through me off.

I think you're right and this is probably due to a mix of OS and PyPI packages. Do you have any ideas @hogarthj?

**Comment by Pascal666** [comment]
Reviewing my logs, cryptography-1.3.1.tar.gz was installed by pip on 4/6/16 and python-cryptography-0.8.2-1.el7.x86_64 was installed by Yum on 7/12/16 as a prerequisite for certbot-0.8.1-1.el7.noarch

**Comment by alex** [comment]
It seems likely to me that installing the yum version over the pypi version
broke something and left with you an install that was half one version,
half teh other.

On Wed, Jul 13, 2016 at 9:39 PM, Pascal666 <notifications@github.com> wrote:

> Reviewing my logs, cryptography-1.3.1.tar.gz was installed by pip on
> 4/6/16 and python-cryptography-0.8.2-1.el7.x86_64 was installed by Yum on
> 7/12/16 as a prerequisite for certbot-0.8.1-1.el7.noarch
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/certbot/certbot/issues/3278#issuecomment-232534060>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAADBMfZoG6Rh8yngIa2fDOG9EJHG3Pxks5qVZNMgaJpZM4JKGk4>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by Pascal666** [comment]
Yeah, the Yum python packages probably don't look for prior installs by pip of the same package.

**Comment by Pascal666** [comment]
New install via Yum on new CentOS 7 box works fine, other than the below error.  Thank you for your time.

You are running with an old copy of certbot that does not receive    │
   │ updates, and is less reliable than more recent versions. We          │
   │ recommend upgrading to the latest certbot-auto script, or using      │
   │ native OS packages.
