### ISSUE TITLE
Various errors with GRSecurity in Debian 8

### ISSUE THREAD

**Issue by AlexanderCurl** [certbot/certbot#3295]
Hi.

I wanted to install the certbot, but it didn't work on my hardened Debian.
My system is a Debian 8 with custom grsec patched kernel, seems to be a various programs runs anonymous mmap, and after just segfault.

Kernel is:
Linux _somehostname_ 4.2.3-alexc-grsec #2 SMP Thu Oct 15 13:29:59 CEST 2015 x86_64 GNU/Linux

[20492906.581729] grsec: From 86.152.6.44: denied RWX mmap of <anonymous mapping> by /root/.local/share/letsencrypt/bin/letsencrypt[letsencrypt:14368] uid/euid:0/0 gid/egid:0/0, parent /opt/letsencrypt/letsencrypt-auto[letsencrypt-aut:14092] uid/euid:0/0 gid/egid:0/0
[20492906.586538] letsencrypt[14368]: segfault at 0 ip 0000036a42e3a99b sp 000003dfe5e7af78 error 6 in libffi.so.6.0.2[36a42e35000+7000]
[20492906.586554] grsec: From 86.152.6.44: Segmentation fault occurred at            (nil) in /root/.local/share/letsencrypt/bin/letsencrypt[letsencrypt:14368] uid/euid:0/0 gid/egid:0/0, parent /opt/letsencrypt/letsencrypt-auto[letsencrypt-aut:14092] uid/euid:0/0 gid/egid:0/0
[20492906.591183] grsec: From 86.152.6.44: denied resource overstep by requesting 4096 for RLIMIT_CORE against limit 0 for /root/.local/share/letsencrypt/bin/letsencrypt[letsencrypt:14368] uid/euid:0/0 gid/egid:0/0, parent /opt/letsencrypt/letsencrypt-auto[letsencrypt-aut:14092] uid/euid:0/0 gid/egid:0/0

**Comment by mithrandi** [comment]
This looks like https://bitbucket.org/cffi/cffi/issues/177/foo-segfaults-with-grsec-denied-rwx-mmap but I think that should be fixed upstream.

**Comment by bmw** [comment]
Have you tried using the Certbot packages in `jessie-backports`, building them from source if necessary?

**Comment by AlexanderCurl** [comment]
well, if the bin fails with the grsec, doesn't matter if I compiled from source, or using jessie-backports...

**Comment by Eriner** [comment]
This is an issue with Arch running GRSec kernel as well.

`grsec: From 127.0.0.1 denied RWX mmap of <anonymous mapping> by /usr/bin/certbot[certbot:2483]`

uname: `Linux 4.5.7.201606142010-1-grsec x86_64 GNU/Linux`

**Comment by AlexanderCurl** [comment]
This issue could be solved, if you are using a paxctld. The kernel has been compiled with grsec.inotify feature, after just edit the /etc/paxctld.conf add the runnable bin to the config with the pax flags could use, and restart the paxctld. The changes must been applied individually, without modify the ELF bin. Don't need to convert the binary anymore with paxctl.

**Comment by SwartzCr** [comment]
glad to hear - I'm going to close this, but let me know if you still have any issues!

**Comment by smarek** [comment]
Hey @SwartzCr let me continue on this.
With recent update of Certbot (debian certbot package), it starts to fail with this kind of error:

```
./letsencrypt-auto renew
Upgrading certbot-auto 0.16.0 to 0.17.0...
Replacing certbot-auto...
Error: couldn't get currently installed version for /root/.local/share/letsencrypt/bin/letsencrypt: 
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 9, in <module>
    from acme import jose
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: cannot change memory protections: Permission denied
```

I had to purge .local/share/letsencrypt and run ./letsencrypt-auto renew again to get this up and running. Same error was triggered by `certbot-auto renew` command.

I haven't found a correct way to fix this with paxctl applied on python2.7 / python3.5 binaries and/or binary/library files within .local/share/letsencrypt

**Comment by SwartzCr** [comment]
@smarek could you please open this as a new issue? This seems like a very different error, and for it to be responded to appropriately it deserves it's own thread

**Comment by smarek** [comment]
Did that in #4996
