### ISSUE TITLE
Installing Python packages problem

### ISSUE THREAD

**Issue by rokistar** [certbot/certbot#3313]
ubuntu 14.04,python 2.7.6,pip 1.5.4 

./certbot-auto renew 
.............
.............
WARNING: unable to check for updates.
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.I7ZngYZIe5/pipstrap.py", line 146, in <module>
    exit(main())
  File "/tmp/tmp.I7ZngYZIe5/pipstrap.py", line 130, in main
    for url, digest in PACKAGES]
  File "/tmp/tmp.I7ZngYZIe5/pipstrap.py", line 112, in hashed_download
    response = opener().open(url)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: \<urlopen error [Errno 110] Connection timed out\>

**Comment by bmw** [comment]
The connection to  [PyPI](https://pypi.python.org) timed out when trying to download packages needed for installation. Are you still having this problem? It may have just be a glitch in the network.

If so, what's the output of `curl https://pypi.python.org/pypi/certbot/json`?

**Comment by rokistar** [comment]
curl: (7) Failed to connect to pypi.python.org port 443: Connection timed out

**Comment by bmw** [comment]
That website is up, however, your server is unable to access it. There's a problem with your network. Make sure everything's configured properly, you don't have firewall rules blocking the traffic, etc.

**Comment by rokistar** [comment]
Thank you
