### ISSUE TITLE
Challenge files not written

### ISSUE THREAD

**Issue by staff0rd** [certbot/certbot#3316]
v1.1-20080819, Amazon AMI, I ran the following, and received a failure due to a 404.  Checking the `wwwroot` I see that  `/.well-known` was created, but `/acme-challenge/` and it's child/ren were not.  I additionally created a dummy file in `wwwroot/.well-known` and successfully confirmed that it was being served.

~~~
sudo /opt/letsencrypt/letsencrypt-auto certonly --webroot -w /my/wwwroot -d mydomain.info -d www.mydomain.info --config /etc/letsencrypt/config.ini --agree-tos --debug
~~~

~~~
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 555, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 94, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 276, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 247, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 74, in get_authorizations
    self._respond(resp, best_effort)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 131, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 195, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
FailedChallenges: Failed authorization procedure. 
+ details of 404
~~~

**Comment by staff0rd** [comment]
I ended up solving this using --standalone
