### ISSUE TITLE
parsedatetime version conflict on FreeBSD

### ISSUE THREAD

**Issue by andreastt** [certbot/certbot#3376]
When installing the _py27-certbot_ package on FreeBSD 10.2 where _py27-letsencrypt_ is already, there is a version conflict of the system _parsedatetime_ library and certbot’s requirement:

```
# certbot
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 700, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 174, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 33, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2379, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2396, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 833, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (parsedatetime 2.1 (/usr/local/lib/python2.7/site-packages), Requirement.parse('parsedatetime<2.0'))
```

```
# uname -a
FreeBSD x 10.2-RELEASE-p17 FreeBSD 10.2-RELEASE-p17 #0: Tue May 17 06:44:54 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

If I uninstall py27-letsencrypt, this uninstalls py27-certbot and parsedatetime as well. Reinstalling py27-certbot after this fixes the problem.

**Comment by czettnersandor** [comment]
It looks like py27-letsencrypt is not available any more and the use of py27-certbot is recommended, which will install the correct parsedatetime

**Comment by bmw** [comment]
Since this is about a very old version of the letsencrypt package and hasn't seen any updates since 2016, I'm closing this issue. If anyone continues to have problems, please comment or open a new issue.
