### ISSUE TITLE
Stack trace when port is in use

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3404]
Running latest certbot master, with port 5001 occupied, I get the below stack trace. Instead it should present the message about port in use and wait for user input.

```
-------------------------------------------------------------------------------
Could not bind TCP port 5001 because it is already in use by another process on
this system (such as a web server). Please stop the program in question and then
try again.
-------------------------------------------------------------------------------
Exiting abnormally:
Traceback (most recent call last):
  File "/home/jsha/certbot/venv/bin/certbot", line 9, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/home/jsha/certbot/certbot/main.py", line 770, in main
    return config.func(config, plugins)
  File "/home/jsha/certbot/certbot/main.py", line 565, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/home/jsha/certbot/certbot/main.py", line 104, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/home/jsha/certbot/certbot/client.py", line 275, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/jsha/certbot/certbot/client.py", line 247, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/home/jsha/certbot/certbot/auth_handler.py", line 70, in get_authorizations
    resp = self._solve_challenges()
  File "/home/jsha/certbot/certbot/auth_handler.py", line 114, in _solve_challenges
    assert len(resp) == len(self.achalls)
TypeError: object of type 'NoneType' has no len()

Traceback (most recent call last):
  File "/home/jsha/certbot/venv/bin/certbot", line 9, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/home/jsha/certbot/certbot/main.py", line 770, in main
    return config.func(config, plugins)
  File "/home/jsha/certbot/certbot/main.py", line 565, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/home/jsha/certbot/certbot/main.py", line 104, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/home/jsha/certbot/certbot/client.py", line 275, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/jsha/certbot/certbot/client.py", line 247, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/home/jsha/certbot/certbot/auth_handler.py", line 70, in get_authorizations
    resp = self._solve_challenges()
  File "/home/jsha/certbot/certbot/auth_handler.py", line 114, in _solve_challenges
    assert len(resp) == len(self.achalls)
TypeError: object of type 'NoneType' has no len()
```

**Comment by bmw** [comment]
Do you either have the log or the command line you used to create this issue? I'm having trouble repoing. I get this:
```
$ sudo certbot -d example.com --standalone certonly --tls-sni-01-port 5001 --http-01-port 5002 -t
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for example.com

-------------------------------------------------------------------------------
Could not bind TCP port 5001 because it is already in use by another process on
this system (such as a web server). Please stop the program in question and then
try again.
-------------------------------------------------------------------------------
Press Enter to Continue
An unexpected error occurred:
TypeError: object of type 'NoneType' has no len()
Please see the logfiles in /var/log/letsencrypt for more details.
```
where I had to hit enter to continue past that prompt. The only way I can recreate your behavior is by setting `-n/--noninteractive/--non-interactive` on the command line which should not wait for user input as suggested by the flag.

That traceback is horrible though. I created #3406 to track the problem.

**Comment by jsha** [comment]
Ah, yeah, this is with `. tests/integration/_common.sh`, so it's using `--non-interactive`, and you're right that it should not pause and prompt. The main thing I worried about was the stack trace, and you've captured the problem better in #3406, so closing this in preference for that one.
