### ISSUE TITLE
certbot-auto macports install missing CA Bundle

### ISSUE THREAD

**Issue by knightcode** [certbot/certbot#3446]
I got this error during the first execution of `certbot-auto` on mac OS with Macports:

```
$ ./certbot-auto --debug --verbose
Bootstrapping dependencies via Mac OS X...
Using MacPorts to install dependencies...
--->  Computing dependencies for augeas
--->  Cleaning augeas
--->  Scanning binaries for linking errors
--->  No broken files found.
--->  Computing dependencies for dialog
--->  Cleaning dialog
--->  Scanning binaries for linking errors
--->  No broken files found.
WARNING: unable to check for updates.
Creating virtual environment...
Running virtualenv with interpreter /opt/local/bin/python2.7
New python executable in /Users/savory/.local/share/letsencrypt/bin/python
Installing setuptools, pip, wheel...done.
Installing Python packages...
Traceback (most recent call last):
  File "/var/folders/xv/1jqbxqpj4dz9bp5zyl8q80tr0000gn/T/tmp.9PWfygNI/pipstrap.py", line 146, in <module>
    exit(main())
  File "/var/folders/xv/1jqbxqpj4dz9bp5zyl8q80tr0000gn/T/tmp.9PWfygNI/pipstrap.py", line 130, in main
    for url, digest in PACKAGES]
  File "/var/folders/xv/1jqbxqpj4dz9bp5zyl8q80tr0000gn/T/tmp.9PWfygNI/pipstrap.py", line 112, in hashed_download
    response = opener().open(url)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

This fixed it:

```
sudo port install curl-ca-bundle
```

**Comment by knightcode** [comment]
also, before that. Instead of `pip`:
```
sudo port install py-virtualenv
sudo port select --set virtualenv virtualenv27
```

**Comment by bmw** [comment]
This issue hasn't seen any traffic since 2016. If anyone is still experiencing this problem, please comment or open a new issue.
