### ISSUE TITLE
Cannot create virtualenv with letsencrypt-auto

### ISSUE THREAD

**Issue by Xarkam** [certbot/certbot#3474]
Hi, 
I need info to fix this error for creating certificate

```
root@intranet:/opt/letsencrypt# ./letsencrypt-auto --apache -d issues.mywebsite.com
Bootstrapping dependencies for Debian-based OSes...
Hit:1 http://archive.canonical.com/ubuntu xenial InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Fetched 94.5 kB in 6s (14.5 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
augeas-lenses is already the newest version (1.4.0-0ubuntu1).
ca-certificates is already the newest version (20160104ubuntu1).
gcc is already the newest version (4:5.3.1-1ubuntu1).
libaugeas0 is already the newest version (1.4.0-0ubuntu1).
libffi-dev is already the newest version (3.2.1-4).
python is already the newest version (2.7.11-1).
python-dev is already the newest version (2.7.11-1).
dialog is already the newest version (1.3-20160209-1).
python-virtualenv is already the newest version (15.0.1+ds-3).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.2).
The following packages were automatically installed and are no longer required:
  python-pbr python-stevedore virtualenv-clone
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  virtualenv
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/4,342 B of archives.
After this operation, 30.7 kB of additional disk space will be used.
Selecting previously unselected package virtualenv.
(Reading database ... 144350 files and directories currently installed.)
Preparing to unpack .../virtualenv_15.0.1+ds-3_all.deb ...
Unpacking virtualenv (15.0.1+ds-3) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up virtualenv (15.0.1+ds-3) ...
Traceback (most recent call last):
  File "/tmp/tmp.SSdvkleKHJ/fetch.py", line 20, in <module>
    from urllib2 import build_opener, HTTPHandler, HTTPSHandler, HTTPError
ImportError: cannot import name HTTPSHandler
WARNING: unable to check for updates.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/.local/share/letsencrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
```

Alternative python give me 

```
root@intranet:/opt/letsencrypt# /etc/alternatives/python
Python 2.7.12 (default, Jul  1 2016, 15:12:24)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

I dont understand the call of python3 to creating virtualenv.
I suppose this is the problem.

Thanks.

**Comment by erikrose** [comment]
The reason Python 3 is being used to run virtualenv is that an Ubuntu-packaged version of virtualenv is being used and [it specifies Python 3 explicitly](http://packages.ubuntu.com/xenial/virtualenv). Don't worry, though—the version of python used to run virtualenv has no bearing on which version actually lands in the created virtual environment.

Your more pressing problem appears to be an installation of Python that does not support SSL, evidenced by the failure to import HTTPSHandler. I'm surprised to see that.

**Comment by Xarkam** [comment]
Hi.

I've posed a question on http://askubuntu.com/questions/820249/python-3-5-not-builded-with-ssl-support or support of ssl on python3 to ubuntu 16.04.

I wait :)

**Comment by Xarkam** [comment]
After a response on ask ubuntu, I suspect the script don't use the python 3 but 2.
Always after updating alternative
```
root@intranet:/opt/letsencrypt# update-alternatives --config python
There are 2 choices for the alternative python (providing /usr/bin/python).

  Selection    Path                Priority   Status
------------------------------------------------------------
  0            /usr/bin/python3.5   10        auto mode
  1            /usr/bin/python2.7   10        manual mode
* 2            /usr/bin/python3.5   10        manual mode
```

I can't understand because the error is same and python3 is compiled with ssl support.

**Comment by erikrose** [comment]
certbot uses Python 2. It tries to find binaries with these names, in this order: python2.7, python27, python2, python. We don't even support Python 3 (yet).

**Comment by SwartzCr** [comment]
@Xarkam is there anything else we can do to help you with this?

**Comment by Xarkam** [comment]
No. I now use the version available in the repositories.
I was able to generate certificates without using letsencrypt-auto.

**Comment by SwartzCr** [comment]
okay I'm going to close this issue then - feel free to re-open it if you think there's still something we need to do
