### ISSUE TITLE
SSLError: bad handshake: SysCallError(104, 'ECONNRESET')

### ISSUE THREAD

**Issue by zhonger** [certbot/certbot#3492]
# when I use `certbot-auto` command to apply a cert, it return that:
   `SSLError: bad handshake: SysCallError(104, 'ECONNRESET')`
# the log is here:
`2016-09-13 02:59:35,970:DEBUG:certbot.main:Root logging level set at 30
2016-09-13 02:59:35,970:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-09-13 02:59:35,970:DEBUG:certbot.main:certbot version: 0.8.1
2016-09-13 02:59:35,970:DEBUG:certbot.main:Arguments: ['--standalone', '--email', 'wuwozhonger@gmail.com', '-d', 'git.shuosc.org']
2016-09-13 02:59:35,970:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-09-13 02:59:35,973:DEBUG:certbot.plugins.selection:Requested authenticator standalone and installer None
2016-09-13 02:59:36,055:DEBUG:certbot.plugins.selection:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x7f2fcd8c2910>
Prep: True
2016-09-13 02:59:36,055:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x7f2fcd8c2910> and installer None
2016-09-13 02:59:36,433:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-09-13 02:59:36,437:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-09-13 02:59:36,733:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/home/asc/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 550, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 360, in _init_le_client
    acc, acme = _determine_account(config)
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 345, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 118, in register
    acme = acme_from_config_key(config, key)
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 42, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 631, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 613, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/asc/.local/share/letsencrypt/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)`
`SSLError: bad handshake: SysCallError(104, 'ECONNRESET')`

**Comment by pde** [comment]
How long did this persist for? It could either be a server outage, or interference from network devices between the machine you're running Certbot on, and the Let's Encrypt servers.

**Comment by zhonger** [comment]
It has been 5 days since I  meet the problem. The machine's ip which i'm running Certbot on is 202.121.199.229 from asia/shanghai. If i do `ping` command, it's reachable.
`ping letsencrypt.org
PING letsencrypt.org (184.26.119.165) 56(84) bytes of data.
64 bytes from a184-26-119-165.deploy.static.akamaitechnologies.com (184.26.119.165): icmp_seq=1 ttl=45 time=174 ms
64 bytes from a184-26-119-165.deploy.static.akamaitechnologies.com (184.26.119.165): icmp_seq=2 ttl=45 time=168 ms`
So could you give me more advices?
Thankyou # @pde

**Comment by pde** [comment]
Hi! Could you collect a packet trace showing what happens when you connect to the server? It should be possible by installing your favourite packet capture software (I like `tshark`) and running something like this:

```
sudo tshark -w /tmp/packets.pcap host acme-v01.api.letsencrypt.org
```

Then running Certbot to reproduce the error, and upload us a copy of the resulting `/tmp/packets.pcap`?

**Comment by zhonger** [comment]
Here is the packets.pcap. If you want more information,please just tell me.
[packets.pcap.zip](https://github.com/certbot/certbot/files/471336/packets.pcap.zip)

**Comment by zhonger** [comment]
Hi! Now `certbot-auto` command has worked. Thank you all the same. @pde

**Comment by David-5-1** [comment]
As I found this thread looking up for the error, if other people face it, ensure you are not trying to renew certificates at the start of an hour (I had it run at midnight CEST because I used `@daily` in a cron file but did not know how it was handled by cron). Changing renewal time fixed the issue. :slightly_smiling_face:

**Comment by alex-ber** [comment]
@David-5-1, thanks.

**Comment by inieves** [comment]
@David-5-1 Can you kindly explain what is the issue/problem with trying to renew certificates at the start of an hour?

**Comment by David-5-1** [comment]
@inieves I do not work at Let'sEncrypt so I do not know, I just suspect their servers are being overloaded from crons that runs at the beginning of hours. However, I wrote that one year ago and I do not know if the issue still exists, I just changed my setup for good then :-).
