### ISSUE TITLE
Getting SSLError when running Certbot

### ISSUE THREAD

**Issue by benileo** [certbot/certbot#3527]
I'm on debian:jessie, and I installed the package from the jessie-backports.
I'm getting the following error when running certbot:
```
2016-09-22 23:36:34,725:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-09-22 23:36:34,727:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-09-22 23:36:34,869:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 550, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 360, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 345, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 118, in register
    acme = acme_from_config_key(config, key)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 42, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 631, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 613, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
SSLError: [Errno 2] No such file or directory
```

**Comment by benileo** [comment]
I may have found a fix, I'll re-open if I have any more problems.

**Comment by benileo** [comment]
I believe the problem was related to a missing account key. When I copied over the account keys from another server, this error went away. Very misleading.

**Comment by bmw** [comment]
That's a bit surprising to me, but I'm glad you worked it out. If you like and can recreate the problem, feel free to create a new issue for improving the error messages with instructions on how to cause the error.

**Comment by benileo** [comment]
Thanks Brad, I'll see if I can formalize the steps to re-create the problem and I'll create an issue if so. Cheers!

**Comment by kakysha** [comment]
Same error here:
`  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 613, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
SSLError: [Errno 2] No such file or directory`

But its a first time I'm using letsencrypt, so, no option to copy any prev keys from other machine. Any solutions?

**Comment by MaikoHermans** [comment]
@kakysha I'm getting the exact same error.
What did you do to fix it?

**Comment by kakysha** [comment]
@MaikoHermans I accidentally removed /etc/ssl folder, which had root certificates for openssl and for the whole system, so any of my python/curl/etc https requests fail. I reinstalled openssl configs
`sudo apt-get -o Dpkg::Options::="--force-confmiss" install --reinstall openssl`
and it helped.

**Comment by benileo** [comment]
This happened to me in a docker container. 
```
FROM nginx:1.11.3
RUN echo "deb http://ftp.debian.org/debian jessie-backports main" \ 
	> /etc/apt/sources.list.d/certbot.list \
	&& apt-get update \
	&& apt-get install -y -t jessie-backports \
		certbot \
		cron \
		rsyslog \
		--no-install-recommends \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm /etc/apt/sources.list.d/certbot.list

COPY post-hook.sh /usr/local/bin/post-hook.sh
COPY rsyslog.conf /etc/rsyslog.conf
COPY entrypoint.py .

ENTRYPOINT [ "./entrypoint.py" ]
```
In entrypoint.py I end up calling `certbot certonly` if the certificates don't exist already, then start nginx in the foreground. 

I highly doubt that the `debian:jessie` image has a misconfigured version of openssl. I'm not able to duplicate the issue at this time although I will continue to try. Could it possibly be an error when setting up some of the python dependencies?
