### ISSUE TITLE
Certbot requires OpenSSL with SSLv3

### ISSUE THREAD

**Issue by cimnine** [certbot/certbot#3573]
On FreeBSD, I configured my OpenSSL to not contain SSLv3 anymore, as it's (IMO) deprecated.

But certbot somehow requires SSLv3 baked into OpenSSL to work, else:

    Traceback (most recent call last):
      File "/usr/local/bin/certbot", line 9, in <module>
        load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
        return ep.load()
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
        return self.resolve()
      File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 14, in <module>
        from acme import jose
      File "/usr/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
        from acme.jose.interfaces import JSONDeSerializable
      File "/usr/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
        from acme.jose import util
      File "/usr/local/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
        import OpenSSL
      File "/usr/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
        from OpenSSL import rand, crypto, SSL
      File "/usr/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
        from OpenSSL._util import (
      File "/usr/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
        from cryptography.hazmat.bindings.openssl.binding import Binding
      File "/usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
        from cryptography.hazmat.bindings._openssl import ffi, lib
    ImportError: /usr/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: Undefined symbol "SSLv3_server_method"

As the letsencrypt servers do not even offer SSLv3 anymore [1], I suggest to remove any references to SSLv3 from certbot altogether and make sure it works with versions of openssl, that don't have SSLv3 support compiled in anymore.

[1]: https://www.ssllabs.com/ssltest/analyze.html?d=acme-v01.api.letsencrypt.org

**Comment by pde** [comment]
Hi @cimnine, can you check whether `import OpenSSL` works for you in a Python prompt. If it doesn't, can you please re-file this bug against https://github.com/pyca/pyopenssl ?

**Comment by cimnine** [comment]
You're right, it's pyopenssl who causes the error. ~Chris

**Comment by cimnine** [comment]
The problem wasn't pyopenssl, but the python `cryptography` module which wasn't at par with openssl. Recompiling cryptography solved the problem.
