### ISSUE TITLE
PluginError with apache possibly due to custom log format in web configuration.

### ISSUE THREAD

**Issue by apcorg** [certbot/certbot#3584]
2016-10-05 19:17:46,549:DEBUG:certbot.main:Root logging level set at 20
2016-10-05 19:17:46,550:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-05 19:17:46,557:DEBUG:certbot.main:certbot version: 0.9.0
2016-10-05 19:17:46,557:DEBUG:certbot.main:Arguments: ['--apache', '-d', 'freeandsecure.online']
2016-10-05 19:17:46,557:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-05 19:17:46,561:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2016-10-05 19:17:47,967:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): ('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/cd.takebackthetech.net.conf', u'Syntax error')
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 106, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 190, in prepare
    self.check_parsing_errors("httpd.aug")
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 74, in check_parsing_errors
    raise errors.PluginError(msg)
PluginError: ('There has been an error in parsing the file (%s): %s', u'/etc/apache2/sites-enabled/cd.takebackthetech.net.conf', u'Syntax error')
2016-10-05 19:17:47,968:DEBUG:certbot.plugins.selection:No candidate plugin
2016-10-05 19:17:47,968:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None

**Comment by bmw** [comment]
@apcorg, that's quite possible.

Can you post the contents of `/etc/apache2/sites-enabled/cd.takebackthetech.net.conf`, redacting any information as you deem necessary? This should allow us to see what the problem was.

**Comment by apcorg** [comment]
NameVirtualHost *:80

LogFormat "%v:%p %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" proxy_combined

<VirtualHost *:80>
  ServerAdmin ###@###.###
  ServerName cd.takebackthetech.net
  ServerAlias cd.###.###.###
  DocumentRoot /var/www/###/###
  ErrorLog /var/log/apache2/error.log
  CustomLog ${APACHE_LOG_DIR}/proxy_vhosts_access.log proxy_combined

</VirtualHost>
<Directory "/var/www/###/###">
      AllowOverride All
      RewriteEngine on
      php_admin_value date.timezone UTC
      php_admin_value allow_url_fopen 1
      php_admin_value open_basedir none
      php_value magic_quotes_gpc Off
</Directory>

<IfModule mod_ssl.c>

<VirtualHost ###:443>
  SSLEngine on
  SSLCACertificateFile /etc/ssl/certs/###
  SSLCertificateFile /etc/ssl/certs/###
  SSLCertificateKeyFile /etc/ssl/private/###
  ServerName cd.takebackthetech.net

  DocumentRoot /var/www/###/###
  ErrorLog /var/log/apache2/error.log
  CustomLog ${APACHE_LOG_DIR}/proxy_vhosts_access.log proxy_combined
</VirtualHost>

<IfModule mod_ssl.c>

**Comment by bmw** [comment]
The error is due to the closing `IfModule` directive. The syntax [according to Apache](https://httpd.apache.org/docs/2.4/mod/core.html#ifmodule) is simply `</IfModule>`. If you change the last line in this file to that, it solves the problem.

**Comment by apcorg** [comment]
Thanks! You were right. We also found some other issues with our config files. Clearing those up helped.
