### ISSUE TITLE
crypto.so ImportError: undefined symbol: PyUnicodeUCS2_Decode

### ISSUE THREAD

**Issue by Geremia** [certbot/certbot#3617]
This occurs with master and v0.9.1 versions:

```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.10.0.dev0', 'console_scripts', 'certbot')()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/certbot/main.py", line 14, in <module>
    from acme import jose
  File "/usr/lib64/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/usr/lib64/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/usr/lib64/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/usr/lib64/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
ImportError: /usr/lib64/python2.7/site-packages/OpenSSL/crypto.so: undefined symbol: PyUnicodeUCS2_Decode
```
I am on Slackware Linux 14.2

**Comment by pde** [comment]
If you just run `import OpenSSL` in a `python` shell, do you get a similar error? If so, `pyOpenSSL` is broken on Slackware 14.2...

**Comment by Geremia** [comment]
@pde Yes, I get the error when doing that.

The issue appears to be that my `python` is UCS4:
```
>>> import sys
>>> print sys.maxunicode
1114111
```
whereas `lib OpenSSL` appears to be expecting UCS2.

Is there a way to force the OpenSSL lib to use UCS4?

**Comment by Geremia** [comment]
I had a packaging issue.
```
ls -l /usr/lib64/python2.7/site-packages/OpenSSL/crypto.so
```
says Oct 14  2013!

You may close this issue. thank you
