### ISSUE TITLE
Possible to select conflicting authenticator and installer plugins

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#3668]
Steps to reproduce:
1. Use latest certbot master. Probably same on 0.9.0+ though.
2. Have a box with both Nginx and Apache installed, but Nginx is the running web server.
3. `certbot  --text -v -d xn--gckc5l.crud.net -d crud.net -a nginx --staging --break-my-certs`

Expected result:

Certificate issued and installed.

Actual result:

Certificate issued, but installation fails because:

```
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 2001:4800:780e:510:3a19:958a:ff04:5613. Set the 'ServerName' directive globally to suppress this message
(98)Address already in use: AH00072: make_sock: could not bind to address [::]:443
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:443
no listening sockets available, shutting down
AH00015: Unable to open logs

Exiting abnormally:
Traceback (most recent call last):
  File "/home/jsha/certbot/venv/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/home/jsha/certbot/certbot/main.py", line 778, in main
    return config.func(config, plugins)
  File "/home/jsha/certbot/certbot/main.py", line 516, in run
    lineage.chain, lineage.fullchain)
  File "/home/jsha/certbot/certbot/client.py", line 384, in deploy_certificate
    self.installer.restart()
  File "/home/jsha/certbot/certbot-apache/certbot_apache/configurator.py", line 1665, in restart
    self._reload()
  File "/home/jsha/certbot/certbot-apache/certbot_apache/configurator.py", line 1676, in _reload
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl graceful.
```

Note that this is technically as user error since I needed to specify `-i nginx` in addition to `-a nginx`. However, we should detect and prevent this user error.

**Comment by bmw** [comment]
In case you're not aware, you can also just do `--nginx`.

This will be a little tricky to solve unless we just hard code pairs of plugins that are known not work together (which in my opinion is a poor solution long term as it doesn't help new/third party plugins).
