### ISSUE TITLE
Certbot crashes

### ISSUE THREAD

**Issue by alpody** [certbot/certbot#3678]
Certbot crashes on slackware 14.2
I  had compiled certbot as slackware package by https://slackbuilds.org/repository/14.2/system/letsencrypt/

 /var/log/letsencrypt/letsencrypt.log: 

2016-10-23 19:48:24,867:DEBUG:certbot.main:Root logging level set at 20
2016-10-23 19:48:24,869:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-23 19:48:24,937:DEBUG:certbot.main:certbot version: 0.9.1
2016-10-23 19:48:24,942:DEBUG:certbot.main:Arguments: []
2016-10-23 19:48:24,942:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEn
tryPoint#standalone)
2016-10-23 19:48:24,999:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2016-10-23 19:48:25,624:DEBUG:certbot.plugins.selection:Multiple candidate plugins: \* webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x9537dec>
Prep: True
- standalone
  Description: Spin up a temporary webserver
  Interfaces: IAuthenticator, IPlugin
  Entry point: standalone = certbot.plugins.standalone:Authenticator
  Initialized: <certbot.plugins.standalone.Authenticator object at 0x953c04c>
  Prep: True
  2016-10-23 19:48:37,856:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x9537dec> and installer None
  2016-10-23 19:48:49,958:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
  2016-10-23 19:48:49,975:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
  2016-10-23 19:48:50,650:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 280
  2016-10-23 19:48:50,656:DEBUG:root:Received <Response [200]>. Headers: CaseInsensitiveDict({'content-length': '280', 'strict-transport-security': 'max-age=604800', 'boulder-request-id': 'Z-X7Xx2VzQ3HVBWDzY8AUMOBCdOx-zvFxGLwd6BFgZU', 'expires': 'Sun, 23 Oct 2016 20:52:42 GMT', 'server': 'nginx', 'connection': 'keep-alive', 'pragma': 'no-cache', 'cache-control': 'max-age=0, no-cache, no-store', 'date': 'Sun, 23 Oct 2016 20:52:42 GMT', 'x-frame-options': 'DENY', 'content-type': 'application/json', 'replay-nonce': 'GmHzSa8BwH-ihTeKi30OQzAfvPY_TP78QP0t_y35OZE'}). Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
  2016-10-23 19:48:50,656:DEBUG:acme.client:Received response <Response [200]> (headers: CaseInsensitiveDict({'content-length': '280', 'strict-transport-security': 'max-age=604800', 'boulder-request-id': 'Z-X7Xx2VzQ3HVBWDzY8AUMOBCdOx-zvFxGLwd6BFgZU', 'expires': 'Sun, 23 Oct 2016 20:52:42 GMT', 'server': 'nginx', 'connection': 'keep-alive', 'pragma': 'no-cache', 'cache-control': 'max-age=0, no-cache, no-store', 'date': 'Sun, 23 Oct 2016 20:52:42 GMT', 'x-frame-options': 'DENY', 'content-type': 'application/json', 'replay-nonce': 'GmHzSa8BwH-ihTeKi30OQzAfvPY_TP78QP0t_y35OZE'})): '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
  2016-10-23 19:48:50,658:DEBUG:root:Requesting fresh nonce
  2016-10-23 19:48:50,660:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-reg. args: (), kwargs: {}
  2016-10-23 19:48:50,668:DEBUG:certbot.main:Exiting abnormally:
  Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 11, in <module>
    load_entry_point('certbot==0.9.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 558, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 368, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 353, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 120, in register
    regr = perform_registration(acme, config)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 150, in perform_registration
    return acme.register(messages.NewRegistration.from_data(email=config.email))
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 96, in register
    response = self.net.post(self.directory[new_reg], new_reg)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 646, in post
    data = self._wrap_in_jws(obj, self._get_nonce(url))
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 641, in _get_nonce
    self._add_nonce(self.head(url))
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 619, in head
    return self._send_request('HEAD', _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 606, in _send_request
    response = self.session.request(method, url, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, *_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 292, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 423, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 234, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util.py", line 262, in is_connection_dropped
    p.register(sock, POLLIN)
  TypeError: argument must be an int, or have a fileno() method.

**Comment by bmw** [comment]
This is interesting. Certbot crashed deep down inside one of our dependencies. Do you repeatedly get this error or was it a one time thing? If you get it on every run, do you also see the error if you run the following on the command line:
```
python -c "import requests; requests.Session().request('HEAD', 'https://acme-v01.api.letsencrypt.org/acme/new-reg')"
```
That should be equivalent to what Certbot was trying to do when it crashed, except the user agent string would be different.

**Comment by alpody** [comment]
When I run code on the comman line:
`python -c "import requests; requests.Session().request('HEAD', 'https://acme-v01.api.letsencrypt.org/acme/new-reg')"`
I get no error.
Certbot crashes every time when i run it.

**Comment by lewiseason** [comment]
I'm having the same issue on CentOS 7.3 with `python` 2.7.5 and `certbot` 0.9.3 (installed through a system package).

My stack trace seems to be slightly different, but the underlying urllib issue is the same:

```Traceback (most recent call last):
  File "/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 563, in obtain_cert
    action, _ = _auth_from_domains(le_client, config, domains, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 100, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 281, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 253, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 68, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 210, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 190, in request_challenges
    new_authz)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 646, in post
    data = self._wrap_in_jws(obj, self._get_nonce(url))
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 641, in _get_nonce
    self._add_nonce(self.head(url))
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 619, in head
    return self._send_request('HEAD', *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 606, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 292, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 423, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 234, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/usr/lib/python2.7/site-packages/requests/packages/urllib3/util.py", line 262, in is_connection_dropped
    p.register(sock, POLLIN)
TypeError: argument must be an int, or have a fileno() method.
```

**Comment by bmw** [comment]
I haven't seen any reports of this problem since early 2017 so I'm closing the issue. If people are still hitting this though, please comment or open a new issue.
