### ISSUE TITLE
certbot does not handle utf-8 characters in apache config path

### ISSUE THREAD

**Issue by jberkel** [certbot/certbot#3681]
Thanks for adding IDN support. It works well, but got some errors during installation.

The file's path is `/etc/apache2/sites-available/motî.net-le-ssl.conf`
Using current certbot master (d54cb76432a2eff43cc9cc3c1cc4d9136eac2221), error occur in 3 different places in `reverter.py`:

```
2016-10-24 11:55:56,510:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/home/jan/certbot/certbot/client.py", line 374, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/home/jan/certbot/certbot-apache/certbot_apache/configurator.py", line 230, in deploy_cert
    vhost = self.choose_vhost(domain)
  File "/home/jan/certbot/certbot-apache/certbot_apache/configurator.py", line 324, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/jan/certbot/certbot-apache/certbot_apache/configurator.py", line 788, in make_vhost_ssl
    self._copy_create_ssl_vhost_skeleton(avail_fp, ssl_fp)
  File "/home/jan/certbot/certbot-apache/certbot_apache/configurator.py", line 882, in _copy_create_ssl_vhost_skeleton
    self.reverter.register_file_creation(False, ssl_fp)
  File "/home/jan/certbot/certbot/reverter.py", line 383, in register_file_creation
    new_fd.write("{0}{1}".format(path, os.linesep))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xee' in position 32: ordinal not in range(128)
```

```
Traceback (most recent call last):
  File "/home/jan/certbot/venv/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/home/jan/certbot/certbot/main.py", line 766, in main
    return config.func(config, plugins)
  File "/home/jan/certbot/certbot/main.py", line 514, in run
    lineage.chain, lineage.fullchain)
  File "/home/jan/certbot/certbot/client.py", line 375, in deploy_certificate
    self.installer.save()  # needed by the Apache plugin
  File "/home/jan/certbot/certbot-apache/certbot_apache/augeas_configurator.py", line 130, in save
    self.save_notes)
  File "/home/jan/certbot/certbot/reverter.py", line 206, in add_to_checkpoint
    self.config.in_progress_dir, save_files, save_notes)
  File "/home/jan/certbot/certbot/reverter.py", line 252, in _add_to_checkpoint_dir
    notes_fd.write(save_notes)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xee' in position 49: ordinal not in range(128)
```

```
Traceback (most recent call last):
  File "/home/jan/certbot/certbot/client.py", line 374, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/home/jan/certbot/certbot-apache/certbot_apache/configurator.py", line 230, in deploy_cert
    vhost = self.choose_vhost(domain)
  File "/home/jan/certbot/certbot-apache/certbot_apache/configurator.py", line 324, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/jan/certbot/certbot-apache/certbot_apache/configurator.py", line 808, in make_vhost_ssl
    self.save()
  File "/home/jan/certbot/certbot-apache/certbot_apache/augeas_configurator.py", line 130, in save
    self.save_notes)
  File "/home/jan/certbot/certbot/reverter.py", line 206, in add_to_checkpoint
    self.config.in_progress_dir, save_files, save_notes)
  File "/home/jan/certbot/certbot/reverter.py", line 238, in _add_to_checkpoint_dir
    op_fd.write(filename + os.linesep)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xee' in position 32: ordinal not in range(128)
```

**Comment by jberkel** [comment]
At some point this was working but now it's broken again. Here's a more recent log file:

```
2018-06-26 23:54:02,329:DEBUG:certbot.main:certbot version: 0.25.1
2018-06-26 23:54:02,330:DEBUG:certbot.main:Arguments: []
2018-06-26 23:54:02,330:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-06-26 23:54:02,353:DEBUG:certbot.log:Root logging level set at 20
2018-06-26 23:54:02,353:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-06-26 23:54:02,389:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0xf621990c> and installer <certbot.cli._Default object at 0xf621990c>
2018-06-26 23:54:02,422:INFO:certbot.renewal:Cert not yet due for renewal
2018-06-26 23:54:02,424:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2018-06-26 23:54:02,730:DEBUG:certbot_apache.configurator:Apache version is 2.4.10
2018-06-26 23:54:03,923:WARNING:certbot.renewal:Attempting to renew cert (zegoggl.es) from /etc/letsencrypt/renewal/zegoggl.es.conf produced an unexpected error: 'ascii' codec can't encode character u'\xee' in position 30: ordinal not in range(128). Skipping.
2018-06-26 23:54:03,926:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/renewal.py", line 438, in handle_renewal_request
    plugins)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/updater.py", line 31, in run_generic_updaters
    installer, _ = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 198, in choose_configurator_plugins
    installer = pick_installer(config, req_inst, plugins, installer_question)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 32, in pick_installer
    config, default, plugins, question, (interfaces.IInstaller,))
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 77, in pick_plugin
    verified.prepare()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 246, in prepare
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 127, in prepare
    self._initialized.prepare()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 237, in prepare
    self.vhosts = self.get_virtual_hosts()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 817, in get_virtual_hosts
    new_vhost = self._create_vhost(path)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 781, in _create_vhost
    self.aug.get("/augeas/files%s/path" % apache_util.get_file_path(path)))
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/apache_util.py", line 39, in get_file_path
    return _split_aug_path(vhost_path)[0]
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/apache_util.py", line 71, in _split_aug_path
    while not os.path.exists(file_path):
  File "/opt/eff.org/certbot/venv/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xee' in position 30: ordinal not in range(128)
```

After renaming the Apache config file (`/etc/apache2/sites-available/motî.net-le-ssl.conf`) the cert renewal works.

Note that this fails regardless of the cert being renewed, a single config file with UTF-8 characters seems to to triggers this. I also tried Python3 + master, same result.
