### ISSUE TITLE
certbot-auto is looking for apache despite following instructions for nginx

### ISSUE THREAD

**Issue by redgluten** [certbot/certbot#3691]
I started following [the instructions](https://certbot.eff.org/#ubuntutrusty-nginx) for Ubuntu trusty + nginx and the auto install process failed.

Content of `letsencrypt.log`:

```log
2016-10-25 20:06:06,111:DEBUG:certbot.main:Root logging level set at 20
2016-10-25 20:06:06,111:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-25 20:06:06,145:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-25 20:06:06,145:DEBUG:certbot.main:Arguments: []
2016-10-25 20:06:06,145:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-25 20:06:06,154:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2016-10-25 20:06:06,192:WARNING:certbot.plugins.util:Failed to find apache2ctl in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2016-10-25 20:06:06,199:DEBUG:certbot.plugins.disco:No installation (PluginEntryPoint#apache): Cannot find Apache control command apache2ctl
Traceback (most recent call last):
  File "/home/gluten/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 106, in prepare
    self._initialized.prepare()
  File "/home/gluten/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 168, in prepare
    'Cannot find Apache control command {0}'.format(restart_cmd))
NoInstallationError: Cannot find Apache control command apache2ctl
2016-10-25 20:06:06,200:DEBUG:certbot.plugins.selection:No candidate plugin
2016-10-25 20:06:06,201:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
```

**Comment by bmw** [comment]
The problem here is simply bad documentation on our part. Running `certbot-auto` both installs Certbot and runs it. In your case, Certbot was successfully installed, but encountered problems when it was running. This is because for your use case, Certbot needs additional commands on the command line.

Try continuing with the "Getting Started" instructions from your link above.

I created certbot/website#165 to fix the problem in our documentation.

**Comment by bmw** [comment]
Closing in favor of certbot/website#165.

**Comment by quangtt** [comment]
I got the same problem here.
Do you guys have any temporary solutions?

**Comment by brunogarett** [comment]
everything works fine and now nothing works 🙈
