### ISSUE TITLE
Problem renewing certificate

### ISSUE THREAD

**Issue by BradlySharpe** [certbot/certbot#3710]
Running on Centos 6, Python 2.7.9.

```
[bradly@latte letsencrypt]$ ./certbot-auto renew -v
Requesting root privileges to run certbot...
  /home/bradly/.local/share/letsencrypt/bin/letsencrypt renew -v
Root logging level set at 10
Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot version: 0.9.3
Arguments: ['-v']
Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/healthydesires.com.au.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/webmail.bradlysharpe.com.au.conf
-------------------------------------------------------------------------------
Should renew, less than 30 days before certificate expiry 2016-10-30 05:12:00 UTC.
Cert is due for renewal, auto-renewing...
Requested authenticator webroot and installer None
Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0xb6c213ac>
Prep: True
Selected authenticator <certbot.plugins.webroot.Authenticator object at 0xb6c213ac> and installer None
Picked account: <Account(e5f134b9926699673511d9e7de013720)>
Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
"GET /directory HTTP/1.1" 200 280
Received <Response [200]>. Headers: {'Content-Length': '280', 'Expires': 'Mon, 31 Oct 2016 05:25:15 GMT', 'Boulder-Request-Id': 'corZwUvBFaIWx-orFn2I2OheOtKZa7OpV2mt9LoDxu4', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 31 Oct 2016 05:25:15 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'REm4xjZlyxSoAnET18INs_uExdLTdj_e_H7NkXMYCT4'}. Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
Received response <Response [200]> (headers: {'Content-Length': '280', 'Expires': 'Mon, 31 Oct 2016 05:25:15 GMT', 'Boulder-Request-Id': 'corZwUvBFaIWx-orFn2I2OheOtKZa7OpV2mt9LoDxu4', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 31 Oct 2016 05:25:15 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'REm4xjZlyxSoAnET18INs_uExdLTdj_e_H7NkXMYCT4'}): '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
Renewing an existing certificate
Requesting fresh nonce
Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
"HEAD /acme/new-authz HTTP/1.1" 405 0
Received <Response [405]>. Headers: {'Content-Length': '91', 'Pragma': 'no-cache', 'Boulder-Request-Id': 'k592rNnC8b8kOVm-eaLddL14_Rahi9KR0u6mP1i4KYA', 'Expires': 'Mon, 31 Oct 2016 05:25:15 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 31 Oct 2016 05:25:15 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'ACMu9rBAOuQfoLLocaAJeyEUaLty9wzGr6b7w1j94B4'}. Content: ''
Storing nonce: '\x00#.\xf6\xb0@:\xe4\x1f\xa0\xb2\xe8q\xa0\t{!\x14h\xbbr\xf7\x0c\xc6\xaf\xa6\xfb\xc3X\xfd\xe0\x1e'
Omitted empty fields: status=None, expires=None, combinations=None, challenges=None
Serialized JSON: {"identifier": {"type": "dns", "value": "mail.bradlysharpe.com.au"}, "resource": "new-authz"}
Omitted empty fields: x5c=(), crit=(), typ=None, kid=None, x5t=None, jku=None, alg=None, x5u=None, x5tS256=None, jwk=None, cty=None
Omitted empty fields: x5c=(), crit=(), typ=None, kid=None, nonce=None, x5t=None, jku=None, x5u=None, x5tS256=None, cty=None
Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "q92D1a0oh4MalmC-dS2NwBcjR0Fkcc9eQhzcDpkOWWk-QSE79xmIVNZzLhspH9Ok5-h-YWP1Fnd4GJh2lLlmW65SVNsYAD97zs_y-dSJUnxPrFsxyjL73qXeomC5W15SM8emHVwQ6jyFv15esiElQ-ruzXdpTP_34uNLI6NJiZZ37GJ65t8XPuim5aUL_ZGyo8ZmWEjNIHhC7jpX_xvi3b7rfd6TV-kxeCbL_m5dUVx5ub1pGUH01wy5-Nn0DoId8DEBWK75vfK2tfX5MTKlBSocpf183fzXW4ybZoifDyNt4YrznNmI1RRM6vyueJaPexxRFhPjxnkO66lv620zIw"}}, "protected": "eyJub25jZSI6ICJBQ011OXJCQU91UWZvTExvY2FBSmV5RVVhTHR5OXd6R3I2Yjd3MWo5NEI0In0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJtYWlsLmJyYWRseXNoYXJwZS5jb20uYXUifSwgInJlc291cmNlIjogIm5ldy1hdXRoeiJ9", "signature": "gG-JvBUUa4f20LsurQRrWb65tiiw7D0Dx07Znvb8Z-M7ijfh6dLuU9dCOwk7Qcmx_nwp4oW4OwhTb4hRFCxIcu74uoZ30JCw9XTWyNiYUsysawlj35MeK9MAQu41ho30xCK-PePu6MRStsRhy-6EsD-o_DIxG2kJs9qsBdQo41ybeBMWl5zwrbykSpkhvkidbyL6qzOkr2rDKK-6T52XA69JgS5mh_hJfdxUbqWv8zOKINsMwWK3djszgCdAkaDrXZzfFQE1KnkpbbLXrt_pCXrw052RVUb97xYk4FvAVH9PVrANI3GMyGAZi3MzKt0U1VBIUC5vmFOHGYO0fV7Fsg"}'}
"POST /acme/new-authz HTTP/1.1" 500 62
Received <Response [500]>. Headers: {'Content-Length': '62', 'Boulder-Request-Id': 'KUGAxn_52j2_tjcxFVhI0SOfcQXMQII_sWBRILmwvmU', 'Expires': 'Mon, 31 Oct 2016 05:25:15 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 31 Oct 2016 05:25:15 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '0XzH6b5TrmBc9svPByaqrm6T3Cij-6ujNZ56UcskSM8'}. Content: '{\n  "type": "urn:acme:error:serverInternal",\n  "status": 500\n}'
Storing nonce: '\xd1|\xc7\xe9\xbeS\xae`\\\xf6\xcb\xcf\x07&\xaa\xaen\x93\xdc(\xa3\xfb\xab\xa35\x9ezQ\xcb$H\xcf'
Received response <Response [500]> (headers: {'Content-Length': '62', 'Boulder-Request-Id': 'KUGAxn_52j2_tjcxFVhI0SOfcQXMQII_sWBRILmwvmU', 'Expires': 'Mon, 31 Oct 2016 05:25:15 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Mon, 31 Oct 2016 05:25:15 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '0XzH6b5TrmBc9svPByaqrm6T3Cij-6ujNZ56UcskSM8'}): '{\n  "type": "urn:acme:error:serverInternal",\n  "status": 500\n}'
Attempting to renew cert from /etc/letsencrypt/renewal/webmail.bradlysharpe.com.au.conf produced an unexpected error: urn:acme:error:serverInternal :: The server experienced an internal error. Skipping.
Traceback was:
Traceback (most recent call last):
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/renewal.py", line 348, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 563, in obtain_cert
    action, _ = _auth_from_domains(le_client, config, domains, lineage)
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 96, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/renewal.py", line 238, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 253, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 68, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 210, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 190, in request_challenges
    new_authz)
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 649, in post
    return self._check_response(response, content_type=content_type)
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 565, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:serverInternal :: The server experienced an internal error


-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/mail.bradlysharpe.com.au.conf
-------------------------------------------------------------------------------
Cert not yet due for renewal

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/healthydesires.com.au/fullchain.pem (skipped)
  /etc/letsencrypt/live/mail.bradlysharpe.com.au/fullchain.pem (skipped)
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/webmail.bradlysharpe.com.au/fullchain.pem (failure)
Exiting abnormally:
Traceback (most recent call last):
  File "/home/bradly/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 592, in renew
    renewal.renew_all_lineages(config)
  File "/home/bradly/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/renewal.py", line 365, in renew_all_lineages
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)

1 renew failure(s), 0 parse failure(s)
```

**Comment by maltris** [comment]
I am experiencing the same error. It seems to occur not just on renewal or first issues but also on new registrations. 

Weird coincidence, that the clocks got changed today ...

**Comment by joerx** [comment]
+1 - getting the same when trying new cert in standalone mode with http-01.

**Comment by kfmes** [comment]
me too, same problem. 
seems to api server returning internal server error

**Comment by bezumkin** [comment]
Same for me

**Comment by simbwa** [comment]
Am having the same problem. Certificate renewal fails and even generating new certificates for new subdomains fails.

Could there be a problem with the Certbot service?

**Comment by dimd13** [comment]
+1

**Comment by AlexMl** [comment]
Experience the same error.
Probably some issue with Letsencrypt itself?

**Comment by joerx** [comment]
Looks like a service outage to me. Bug open for more than 3 hrs, no feedback from maintainers. 👎

**Comment by AlexMl** [comment]
https://letsencrypt.status.io/

**Comment by fgpietersz** [comment]
It is a known server issue, not a client bug: https://letsencrypt.status.io/

**Comment by BradlySharpe** [comment]
Explains why I can issue a certificate for my mail subdomain but not webmail I guess

**Comment by chriscroome** [comment]
I also appear to have this issue, a 500 error when trying to get a new cert, on Debian Jessie with `certbot` from backports, this is what I have in `/var/log/letsencrypt`:

```
2016-10-31 11:32:26,121:DEBUG:urllib3.connectionpool:"POST /acme/new-reg HTTP/1.1" 500 109
2016-10-31 11:32:26,124:DEBUG:root:Received <Response [500]>. Headers: {'content-length': '109', 'boulder-request-id': 'LcFE8lMQUx64f-09p9bAHF5IdRJYM6XwXrlj6AvX7HY', 'expires': 'Mon, 31 Oct 2016 11:32:26 GMT', 'server': 'nginx', 'connection': 'close', 'pragma': 'no-cache', 'cache-control': 'max-age=0, no-cache, no-store', 'date': 'Mon, 31 Oct 2016 11:32:26 GMT', 'content-type': 'application/problem+json', 'replay-nonce': 'gAC7vKrTMR7RtELUMv1CKufNjXDUIV7HnuwwP5qCSHE'}. Content: '{\n  "type": "urn:acme:error:serverInternal",\n  "detail": "Error creating new registration",\n  "status": 500\n}'
2016-10-31 11:32:26,125:DEBUG:acme.client:Storing nonce: '\x80\x00\xbb\xbc\xaa\xd31\x1e\xd1\xb4B\xd42\xfdB*\xe7\xcd\x8dp\xd4!^\xc7\x9e\xec0?\x9a\x82Hq'
2016-10-31 11:32:26,125:DEBUG:acme.client:Received response <Response [500]> (headers: {'content-length': '109', 'boulder-request-id': 'LcFE8lMQUx64f-09p9bAHF5IdRJYM6XwXrlj6AvX7HY', 'expires': 'Mon, 31 Oct 2016 11:32:26 GMT', 'server': 'nginx', 'connection': 'close', 'pragma': 'no-cache', 'cache-control': 'max-age=0, no-cache, no-store', 'date': 'Mon, 31 Oct 2016 11:32:26 GMT', 'content-type': 'application/problem+json', 'replay-nonce': 'gAC7vKrTMR7RtELUMv1CKufNjXDUIV7HnuwwP5qCSHE'}): '{\n  "type": "urn:acme:error:serverInternal",\n  "detail": "Error creating new registration",\n  "status": 500\n}'
2016-10-31 11:32:26,127:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 550, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 360, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 345, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 120, in register
    regr = perform_registration(acme, config)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 150, in perform_registration
    return acme.register(messages.NewRegistration.from_data(email=config.email))
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 98, in register
    response = self.net.post(self.directory[new_reg], new_reg)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 656, in post
    return self._check_response(response, content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 572, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Error creating new registration
```

**Comment by bmw** [comment]
Yes this is due to the active Let's Encrypt incident. Unfortunately, there's nothing we can do on the client side, but Let's Encrypt is usually pretty quick about fixing errors like this. Try obtaining/renewing your cert again later and the issue should be resolved. Sorry for the trouble.
