### ISSUE TITLE
An unexpected error occurred: The server experienced an internal error :: Error creating new cert

### ISSUE THREAD

**Issue by renier** [certbot/certbot#3739]
Is anyone else experiencing this?

```
2016-11-04 04:42:51,011:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-cert HTTP/1.1" 500 101
2016-11-04 04:42:51,014:DEBUG:root:Received <Response [500]>. Headers: {'Content-Length': '101', 'Boulder-Request-Id': '3AnEa3bEBsjxcmxUxV1jwK4iEapWgGEwgRQkhciaykA', 'Expires': 'Fri, 04 Nov 2016 04:42:51 GMT', 'Server': 'nginx', 'Connection': 'close', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Boulder-Requester': '5841681', 'Date': 'Fri, 04 Nov 2016 04:42:51 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'ouZYgXZeuYm4g5vtA9DnFb67EjG3YlnOw44sywUVmrg'}. Content: '{\n  "type": "urn:acme:error:serverInternal",\n  "detail": "Error creating new cert",\n  "status": 500\n}'
2016-11-04 04:42:51,015:DEBUG:acme.client:Storing nonce: '\xa2\xe6X\x81v^\xb9\x89\xb8\x83\x9b\xed\x03\xd0\xe7\x15\xbe\xbb\x121\xb7bY\xce\xc3\x8e,\xcb\x05\x15\x9a\xb8'
2016-11-04 04:42:51,015:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '101', 'Boulder-Request-Id': '3AnEa3bEBsjxcmxUxV1jwK4iEapWgGEwgRQkhciaykA', 'Expires': 'Fri, 04 Nov 2016 04:42:51 GMT', 'Server': 'nginx', 'Connection': 'close', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Boulder-Requester': '5841681', 'Date': 'Fri, 04 Nov 2016 04:42:51 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'ouZYgXZeuYm4g5vtA9DnFb67EjG3YlnOw44sywUVmrg'}): '{\n  "type": "urn:acme:error:serverInternal",\n  "detail": "Error creating new cert",\n  "status": 500\n}'
2016-11-04 04:42:51,016:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 706, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 474, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 269, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 252, in obtain_certificate
    return self.obtain_certificate_from_csr(domains, csr) + (key, csr)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 229, in obtain_certificate_from_csr
    authzr)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 319, in request_issuance
    headers={'Accept': content_type})
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 652, in post
    return self._check_response(response, content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 568, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Error creating new cert
```

**Comment by cpu** [comment]
Hi @renier,

The time you received this error matches up with [yesterday's maintenance window](https://letsencrypt.status.io/pages/history/55957a99e800baa4470002da).

Have you been able to issue since then? I strongly suspect this was transient and caused server-side by our maintenance.

**Comment by jvivona** [comment]
we are attempting to test a dry run and are getting the error as of 4PM US Eastern Time.
![image](https://cloud.githubusercontent.com/assets/1454249/20020425/92d72fca-a2a7-11e6-9178-424b7793c954.png)

**Comment by renier** [comment]
Working for me now.
