### ISSUE TITLE
certbot doesn't use free ipv6 ports 80 and 443

### ISSUE THREAD

**Issue by toralf** [certbot/certbot#3755]
The ipv4 ports are used here but ipv6 are free (pls see attached log file.

**Comment by toralf** [comment]
`2016-11-06 02:10:02,899:DEBUG:certbot.main:Root logging level set at 20
2016-11-06 02:10:02,901:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-11-06 02:10:02,902:DEBUG:certbot.main:certbot version: 0.9.3
2016-11-06 02:10:02,902:DEBUG:certbot.main:Arguments: ['--standalone', '--non-interactive', '--text', '--renew-hook', 'hook', '--disable-hook-validation']
2016-11-06 02:10:02,904:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-11-06 02:10:02,924:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2016-12-02 09:26:00 UTC.
2016-11-06 02:10:02,924:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2016-11-06 02:10:02,956:DEBUG:certbot.plugins.selection:Requested authenticator standalone and installer None
2016-11-06 02:10:03,184:DEBUG:certbot.plugins.selection:Single candidate plugin: * standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x38aa0aa6510>
Prep: True
2016-11-06 02:10:03,186:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x38aa0aa6510> and installer None
2016-11-06 02:10:03,379:DEBUG:certbot.main:Picked account: <Account(1af7e869e0a6f467e5ccf8ad7c3de9f5)>
2016-11-06 02:10:03,381:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-11-06 02:10:03,386:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-11-06 02:10:03,601:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 280
2016-11-06 02:10:03,602:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '280', 'Expires': 'Sun, 06 Nov 2016 02:10:03 GMT', 'Boulder-Request-Id': 'Jrk7cSWCoXeCrFdOEofA1MrTtrAPBa36HHJPIB0tfko', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sun, 06 Nov 2016 02:10:03 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '71GVA2TyFSK_Sq7CuzboAlp3AokQ0-UfI8IMboT-DLM'}. Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-11-06 02:10:03,602:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '280', 'Expires': 'Sun, 06 Nov 2016 02:10:03 GMT', 'Boulder-Request-Id': 'Jrk7cSWCoXeCrFdOEofA1MrTtrAPBa36HHJPIB0tfko', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sun, 06 Nov 2016 02:10:03 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': '71GVA2TyFSK_Sq7CuzboAlp3AokQ0-UfI8IMboT-DLM'}): '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-11-06 02:10:03,603:INFO:certbot.main:Renewing an existing certificate
2016-11-06 02:10:03,603:DEBUG:root:Requesting fresh nonce
2016-11-06 02:10:03,604:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2016-11-06 02:10:03,774:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2016-11-06 02:10:03,774:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '91', 'Pragma': 'no-cache', 'Boulder-Request-Id': 'Pp2VD78sfOjXsbbIIbSTL2f1uUPRut_k-xlsGpNiiHY', 'Expires': 'Sun, 06 Nov 2016 02:10:03 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Sun, 06 Nov 2016 02:10:03 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '60WPxCiWlK847SmiQBevwjrISeJ8cABSTzav0XpzR74'}. Content: ''
2016-11-06 02:10:03,775:DEBUG:acme.client:Storing nonce: '\xebE\x8f\xc4(\x96\x94\xaf8\xed)\xa2@\x17\xaf\xc2:\xc8I\xe2|p\x00RO6\xaf\xd1zsG\xbe'
2016-11-06 02:10:03,776:DEBUG:acme.jose.json_util:Omitted empty fields: status=None, combinations=None, expires=None, challenges=None
2016-11-06 02:10:03,776:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "jabber.zwiebeltoralf.de"}, "resource": "new-authz"}
2016-11-06 02:10:03,778:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, alg=None, jku=None, cty=None, x5t=None, kid=None, x5tS256=None, x5u=None, jwk=None
2016-11-06 02:10:03,780:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, nonce=None, cty=None, x5t=None, kid=None, x5tS256=None, x5u=None
2016-11-06 02:10:03,781:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "14qOyIsujLUxHtLMRQDbhRktvMk8n-MC6eHv1xNV1S1oQTprKBDcZAJavBLFGuxvm6ryFS4Oq1vg91KH7v87EiqqLW91aRsWL3_Wlc3RH1q43KEpPkMq8B0cSwZnxXMVaD3uB1WG1XTDQn9TD7_pfZ0NKF0L1o2twxIom_Avhg0GfNr9HlggM5BIRmhnbVwHulPkTt72Dla29W0XF_Uq2IcbzCnG0iMgKS2waj-jqdSLzEj_utS35N90cHxOulR4qgrqmW3Lk7eq_9F7t2-35RFpdYnAZ5-QSYqMEGx7W9i9qTmQ2qYoGozayYlFY7LZzosrJwLp7UJllSPSJyjX6w"}}, "protected": "eyJub25jZSI6ICI2MFdQeENpV2xLODQ3U21pUUJldndqcklTZUo4Y0FCU1R6YXYwWHB6Ujc0In0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJqYWJiZXIuendpZWJlbHRvcmFsZi5kZSJ9LCAicmVzb3VyY2UiOiAibmV3LWF1dGh6In0", "signature": "ep4rO9LhOVOk8ZiIvhmBSbJ2SlfF4qfaOR6YvLAB18JwKfEri5H_wAA8Eh2nrHVVHplIGJBHdospDfU1w5kgmW1YXX-4mZr-6AsjrNx34hxcgjTnGLf5AIr2rVaKQjqw3rCh5MCZ0CwZwBFgTkQ-9-aAL2Kk042D13GgG3Q1QT3tJkkenr7ivOxUYOLucCiMYchqptfH6a-uSpAvvVTI_LABHNmRJK4KsvBnEK7KrUGVlY5kacb_n-mEwWl7NuLWZ2POhL4DILsI9d7eBurJgL929jDm4x5Bv_vDqFvHdlclvSMS8NsguuutUlAczaUTBYHpGf89ToWL2o0d22ioog"}'}
2016-11-06 02:10:03,984:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 201 1387
2016-11-06 02:10:03,985:DEBUG:root:Received <Response [201]>. Headers: {'Content-Length': '1387', 'Expires': 'Sun, 06 Nov 2016 02:10:03 GMT', 'Boulder-Request-Id': 'JN3dS476rkSNHVx2U_x9own0KoJ62YfGw25XvkXgqtU', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/ClboIMFaUc_0G_Ix0oZMiZbh8aFb--ARjMIwry1z35w', 'Pragma': 'no-cache', 'Boulder-Requester': '3903350', 'Date': 'Sun, 06 Nov 2016 02:10:03 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'lUqohIaXDB804sI9dpJaXcA7dwdFfEaDRdvPiBacXp0'}. Content: '{\n  "identifier": {\n    "type": "dns",\n    "value": "jabber.zwiebeltoralf.de"\n  },\n  "status": "valid",\n  "expires": "2016-12-02T10:25:44Z",\n  "challenges": [\n    {\n      "type": "http-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/ClboIMFaUc_0G_Ix0oZMiZbh8aFb--ARjMIwry1z35w/253592724",\n      "token": "93R6Mxe_tH3nQy-5I87Ju3QCchOPDcPo71ORvLDMQLs"\n    },\n    {\n      "type": "dns-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/ClboIMFaUc_0G_Ix0oZMiZbh8aFb--ARjMIwry1z35w/253592725",\n      "token": "N-5DDhe7dmH2Yzv5b7ZNUoKQ22rENJBYLjXKsI9_fJ4"\n    },\n    {\n      "type": "tls-sni-01",\n      "status": "valid",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/ClboIMFaUc_0G_Ix0oZMiZbh8aFb--ARjMIwry1z35w/253592726",\n      "token": "CfH_orwlHtk0un-ih1nhHtGXFPrCo-4PVCPz0qfptnA",\n      "keyAuthorization": "CfH_orwlHtk0un-ih1nhHtGXFPrCo-4PVCPz0qfptnA.V5iZYwOrIh6WbBwN4U4-Q-g1gDe4ZJUARP6nbRqwkIY",\n      "validationRecord": [\n        {\n          "hostname": "jabber.zwiebeltoralf.de",\n          "port": "443",\n          "addressesResolved": [\n            "5.9.158.75",\n            "2a01:4f8:190:514a::2"\n          ],\n          "addressUsed": "5.9.158.75"\n        }\n      ]\n    }\n  ],\n  "combinations": [\n    [\n      2\n    ],\n    [\n      0\n    ],\n    [\n      1\n    ]\n  ]\n}'
2016-11-06 02:10:03,985:DEBUG:acme.client:Storing nonce: '\x95J\xa8\x84\x86\x97\x0c\x1f4\xe2\xc2=v\x92Z]\xc0;w\x07E|F\x83E\xdb\xcf\x88\x16\x9c^\x9d'
2016-11-06 02:10:03,985:DEBUG:acme.client:Received response <Response [201]> (headers: {'Content-Length': '1387', 'Expires': 'Sun, 06 Nov 2016 02:10:03 GMT', 'Boulder-Request-Id': 'JN3dS476rkSNHVx2U_x9own0KoJ62YfGw25XvkXgqtU', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/ClboIMFaUc_0G_Ix0oZMiZbh8aFb--ARjMIwry1z35w', 'Pragma': 'no-cache', 'Boulder-Requester': '3903350', 'Date': 'Sun, 06 Nov 2016 02:10:03 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'lUqohIaXDB804sI9dpJaXcA7dwdFfEaDRdvPiBacXp0'}): '{\n  "identifier": {\n    "type": "dns",\n    "value": "jabber.zwiebeltoralf.de"\n  },\n  "status": "valid",\n  "expires": "2016-12-02T10:25:44Z",\n  "challenges": [\n    {\n      "type": "http-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/ClboIMFaUc_0G_Ix0oZMiZbh8aFb--ARjMIwry1z35w/253592724",\n      "token": "93R6Mxe_tH3nQy-5I87Ju3QCchOPDcPo71ORvLDMQLs"\n    },\n    {\n      "type": "dns-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/ClboIMFaUc_0G_Ix0oZMiZbh8aFb--ARjMIwry1z35w/253592725",\n      "token": "N-5DDhe7dmH2Yzv5b7ZNUoKQ22rENJBYLjXKsI9_fJ4"\n    },\n    {\n      "type": "tls-sni-01",\n      "status": "valid",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/ClboIMFaUc_0G_Ix0oZMiZbh8aFb--ARjMIwry1z35w/253592726",\n      "token": "CfH_orwlHtk0un-ih1nhHtGXFPrCo-4PVCPz0qfptnA",\n      "keyAuthorization": "CfH_orwlHtk0un-ih1nhHtGXFPrCo-4PVCPz0qfptnA.V5iZYwOrIh6WbBwN4U4-Q-g1gDe4ZJUARP6nbRqwkIY",\n      "validationRecord": [\n        {\n          "hostname": "jabber.zwiebeltoralf.de",\n          "port": "443",\n          "addressesResolved": [\n            "5.9.158.75",\n            "2a01:4f8:190:514a::2"\n          ],\n          "addressUsed": "5.9.158.75"\n        }\n      ]\n    }\n  ],\n  "combinations": [\n    [\n      2\n    ],\n    [\n      0\n    ],\n    [\n      1\n    ]\n  ]\n}'
2016-11-06 02:10:03,987:INFO:certbot.auth_handler:Performing the following challenges:
2016-11-06 02:10:03,987:INFO:certbot.auth_handler:tls-sni-01 challenge for jabber.zwiebeltoralf.de
2016-11-06 02:10:03,987:DEBUG:certbot.plugins.util:Psutil not found, using simple socket check.
2016-11-06 02:10:03,989:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/certbot/auth_handler.py", line 112, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/usr/lib64/python2.7/site-packages/certbot/plugins/standalone.py", line 234, in perform
    self._verify_ports_are_available(achalls)
  File "/usr/lib64/python2.7/site-packages/certbot/plugins/standalone.py", line 231, in _verify_ports_are_available
    "At least one of the required ports is already taken.")
MisconfigurationError: At least one of the required ports is already taken.

2016-11-06 02:10:03,989:DEBUG:certbot.error_handler:Calling registered functions
2016-11-06 02:10:03,989:INFO:certbot.auth_handler:Cleaning up challenges
2016-11-06 02:10:03,989:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/jabber.zwiebeltoralf.de.conf produced an unexpected error: At least one of the required ports is already taken.. Skipping.
2016-11-06 02:10:03,990:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/certbot/renewal.py", line 348, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib64/python2.7/site-packages/certbot/main.py", line 563, in obtain_cert
    action, _ = _auth_from_domains(le_client, config, domains, lineage)
  File "/usr/lib64/python2.7/site-packages/certbot/main.py", line 96, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib64/python2.7/site-packages/certbot/renewal.py", line 238, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/usr/lib64/python2.7/site-packages/certbot/client.py", line 253, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib64/python2.7/site-packages/certbot/auth_handler.py", line 74, in get_authorizations
    resp = self._solve_challenges()
  File "/usr/lib64/python2.7/site-packages/certbot/auth_handler.py", line 112, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/usr/lib64/python2.7/site-packages/certbot/plugins/standalone.py", line 234, in perform
    self._verify_ports_are_available(achalls)
  File "/usr/lib64/python2.7/site-packages/certbot/plugins/standalone.py", line 231, in _verify_ports_are_available
    "At least one of the required ports is already taken.")
MisconfigurationError: At least one of the required ports is already taken.

2016-11-06 02:10:03,992:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib64/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/usr/lib64/python2.7/site-packages/certbot/main.py", line 592, in renew
    renewal.renew_all_lineages(config)
  File "/usr/lib64/python2.7/site-packages/certbot/renewal.py", line 365, in renew_all_lineages
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)

`

**Comment by johanfleury** [comment]
Isn't this issue a duplicate of #1466?

**Comment by toralf** [comment]
oops - never argued that it can't speak ipv6 at all - so you're right
