### ISSUE TITLE
Error install Python packages (UnicodeDecodeError)

### ISSUE THREAD

**Issue by proninyaroslav** [certbot/certbot#3756]
Python version 2.7.12
I wanted to update keys and got it

```
Creating virtual environment...
/usr/lib/python2.7/site-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
/usr/lib/python2.7/site-packages/ndg/httpsclient/ssl_peer_verification.py:25: UserWarning: SubjectAltName support is disabled - check pyasn1 package installation to enable
  warnings.warn(SUBJ_ALT_NAME_SUPPORT_MSG)
/usr/lib/python2.7/site-packages/ndg/httpsclient/subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
Installing Python packages...
Exception:
Traceback (most recent call last):
  File "/home/yaroslav/.local/share/letsencrypt/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/yaroslav/.local/share/letsencrypt/lib/python2.7/site-packages/pip/commands/install.py", line 272, in run
    with self._build_session(options) as session:
  File "/home/yaroslav/.local/share/letsencrypt/lib/python2.7/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/home/yaroslav/.local/share/letsencrypt/lib/python2.7/site-packages/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/yaroslav/.local/share/letsencrypt/lib/python2.7/site-packages/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/home/yaroslav/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/distro.py", line 1051, in <module>
    _distro = LinuxDistribution()
  File "/home/yaroslav/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/distro.py", line 594, in __init__
    if include_lsb else {}
  File "/home/yaroslav/.local/share/letsencrypt/lib/python2.7/site-packages/pip/_vendor/distro.py", line 922, in _lsb_release_info
    stdout, stderr = stdout.decode('ascii'), stderr.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 22: ordinal not in range(128)
Traceback (most recent call last):
  File "/tmp/tmp.5MHWZnj36Z/pipstrap.py", line 146, in <module>
    exit(main())
  File "/tmp/tmp.5MHWZnj36Z/pipstrap.py", line 133, in main
    shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U /tmp/pipstrap-ncRZkT/pip-8.0.3.tar.gz /tmp/pipstrap-ncRZkT/setuptools-20.2.2.tar.gz /tmp/pipstrap-ncRZkT/wheel-0.29.0.tar.gz' returned non-zero exit status 2

```

**Comment by ghollingworth** [comment]
Need to:

sudo apt-get install python-pip

I would think this should should be a dependancy...

Gordon

**Comment by SwartzCr** [comment]
@proninyaroslav can you let us know if this is still an issue for you? Also what OS are you running certbot on?

**Comment by SwartzCr** [comment]
I'm going to close this @proninyaroslav feel free to comment to re-open it if it's still an issue for you
