### ISSUE TITLE
psutil versioning weirdness on Ubuntu 16.04

### ISSUE THREAD

**Issue by wolkenschieber** [certbot/certbot#3760]
Hi,

I'm trying to create a letsencrypt certificate in Ubuntu 16.04. For the process I'm using `python-letsencrypt             0.4.1-1` from the official repositories.

When running `letsencrypt certonly` following error messages are written:

```
2016-11-07 07:19:22,493:INFO:letsencrypt.auth_handler:Performing the following challenges:
2016-11-07 07:19:22,493:INFO:letsencrypt.auth_handler:tls-sni-01 challenge for DOMAIN
2016-11-07 07:19:22,494:DEBUG:letsencrypt.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/standalone.py", line 207, in perform
    if any(util.already_listening(port, renewer) for port in self._necessary_ports):
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/standalone.py", line 207, in <genexpr>
    if any(util.already_listening(port, renewer) for port in self._necessary_ports):
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/util.py", line 28, in already_listening
    net_connections = psutil.net_connections()
AttributeError: 'module' object has no attribute 'net_connections'

2016-11-07 07:19:22,494:DEBUG:letsencrypt.error_handler:Calling registered functions
2016-11-07 07:19:22,494:INFO:letsencrypt.auth_handler:Cleaning up challenges
2016-11-07 07:19:22,495:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 706, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 474, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 269, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 252, in obtain_certificate
    return self.obtain_certificate_from_csr(domains, csr) + (key, csr)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 225, in obtain_certificate_from_csr
    authzr = self.auth_handler.get_authorizations(domains)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/auth_handler.py", line 80, in get_authorizations
    cont_resp, dv_resp = self._solve_challenges()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/auth_handler.py", line 115, in _solve_challenges
    dv_resp = self.dv_auth.perform(self.dv_c)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/standalone.py", line 207, in perform
    if any(util.already_listening(port, renewer) for port in self._necessary_ports):
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/standalone.py", line 207, in <genexpr>
    if any(util.already_listening(port, renewer) for port in self._necessary_ports):
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/util.py", line 28, in already_listening
    net_connections = psutil.net_connections()
AttributeError: 'module' object has no attribute 'net_connections'
```

Are there missing dependencies in the offical package?

Best regards

**Comment by DavidBruchmann** [comment]
I run the command like this with the same system like you:

`letsencrypt certonly -a webroot --webroot-path=/var/www/html/domain.com -d domain.com`

and it's working without problems.
I propose you try it like my example first, just replace domain.com by your own domain.

**Comment by wolkenschieber** [comment]
I don't/can't want to use Apache to obtain the certificates. Instead I use

```
letsencrypt certonly --standalone -d domain.com
```

This gives me above error.

**Comment by DavidBruchmann** [comment]
Ok, I never use apache too but nginx instead.
Sorry with the standalone-option I can't help.

**Comment by wolkenschieber** [comment]
Nevermind, thanks for your answers though.

Am 07.11.2016 um 10:08 schrieb David Bruchmann:

**Comment by pde** [comment]
@wolkenschieber we're going to ask Ubuntu to ship Certbot 0.9.3 in Xenial, rather than the ancient `letsencrypt` 0.4.1 you've got...

**Comment by bmw** [comment]
We no longer use `psutil` so I think this issue can be closed.
