### ISSUE TITLE
Pluginerror - dotdeb.gpg

### ISSUE THREAD

**Issue by michalbobo** [certbot/certbot#3793]
Hi,
I am trying to install SSL certificate on Debian8+apache2. I went by the certbot manual but when i try to call certbot --apache a i get this error. Anyone any thoughts on what is wrong please?

`016-11-14 15:44:04,481:DEBUG:certbot.main:Root logging level set at 20
2016-11-14 15:44:04,483:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-11-14 15:44:04,494:DEBUG:certbot.main:certbot version: 0.9.3
2016-11-14 15:44:04,495:DEBUG:certbot.main:Arguments: ['--apache']
2016-11-14 15:44:04,496:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoin$
2016-11-14 15:44:04,501:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2016-11-14 15:44:04,944:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): ('There has been an error in parsing the file (%s): %s', '/etc/apache2/sit$
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 106, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 190, in prepare
    self.check_parsing_errors("httpd.aug")
  File "/usr/lib/python2.7/dist-packages/certbot_apache/augeas_configurator.py", line 74, in check_parsing_errors
    raise errors.PluginError(msg)
PluginError: ('There has been an error in parsing the file (%s): %s', '/etc/apache2/sites-available/dotdeb.gpg', 'Syntax error')
2016-11-14 15:44:04,946:DEBUG:certbot.plugins.selection:No candidate plugin
2016-11-14 15:44:04,947:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
`

**Comment by pde** [comment]
It looks like you have accidentally left a GPG file, `/etc/apache2/sites-available/dotdeb.gpg`, in your Apache configuration directory. It shouln't be there -- move it somewhere else!
