### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED on debian 7

### ISSUE THREAD

**Issue by Lohoris** [certbot/certbot#3814]
```
looris@termite:~/bin$ ./certbot-auto 
Bootstrapping dependencies for Debian-based OSes...
Ign:1 http://overviewer.org/debian ./ InRelease
Hit:2 http://overviewer.org/debian ./ Release                                                                                                             
Hit:3 http://www.deb-multimedia.org jessie InRelease                                                                                                      
Hit:8 http://security.debian.org stable/updates InRelease                                                                                                  
Hit:9 http://security.debian.org testing/updates InRelease                                                                       
Ign:11 http://pkg.jenkins.io/debian-stable binary/ InRelease                                                                     
Hit:12 http://pkg.jenkins.io/debian-stable binary/ Release                           
Ign:4 http://mirror.sinavps.ch/debian stable InRelease                               
Hit:5 http://mirror.sinavps.ch/debian testing InRelease
Hit:7 http://mirror.sinavps.ch/debian stable-updates InRelease          
Hit:10 http://mirror.sinavps.ch/debian jessie-backports InRelease       
Hit:14 http://mirror.sinavps.ch/debian stable Release                   
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
augeas-lenses is already the newest version (1.2.0-0.2+deb8u1).
libaugeas0 is already the newest version (1.2.0-0.2+deb8u1).
ca-certificates is already the newest version (20141019+deb8u1).
dialog is already the newest version (1.2-20140911-1).
gcc is already the newest version (4:4.9.2-2).
libffi-dev is already the newest version (3.1-2+b2).
python is already the newest version (2.7.9-1).
python-dev is already the newest version (2.7.9-1).
python-virtualenv is already the newest version (1.11.6+ds-1).
virtualenv is already the newest version (1.11.6+ds-1).
libssl-dev is already the newest version (1.0.2j-1).
0 upgraded, 0 newly installed, 0 to remove and 109 not upgraded.
WARNING: unable to check for updates.
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.fpcU2HSisa/pipstrap.py", line 146, in <module>
    exit(main())
  File "/tmp/tmp.fpcU2HSisa/pipstrap.py", line 130, in main
    for url, digest in PACKAGES]
  File "/tmp/tmp.fpcU2HSisa/pipstrap.py", line 112, in hashed_download
    response = opener().open(url)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
looris@termite:~/bin$ cat /etc/debian_version 
7.8
```

**Comment by pde** [comment]
Does this happen regardless of which network you're on?

**Comment by erikrose** [comment]
Hmm, running pipstrap (alone, the same version as in certbot-auto) works for me on a Debian 7.11 box. The error you're seeing indicates that https://pypi.python.org is not offering a cert that your system-wide certificate store recognizes. I can't think of a reason that should be the case. Does this error continue to happen if you try again?

If so, I'd be curious whether an isolated invocation of pipstrap fails in the same way for you. On your Debian box...

1. `virtualenv smoo`
2. `source smoo/bin/activate`
3. Paste https://raw.githubusercontent.com/certbot/certbot/master/letsencrypt-auto-source/pieces/pipstrap.py into a new file.
4. `chmod a+x pipstrap.py`
5. `./pipstrap.py` and see if you get an error.
6. `rm -rf smoo`

**Comment by Lohoris** [comment]
Yep, it still happens!

```
(smoo)looris@termite:/tmp/smoo$ ./pipstrap.py 
Traceback (most recent call last):
  File "./pipstrap.py", line 146, in <module>
    exit(main())
  File "./pipstrap.py", line 130, in main
    for url, digest in PACKAGES]
  File "./pipstrap.py", line 112, in hashed_download
    response = opener().open(url)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
```

Feel free to ask me what you need to know in order to find the problem…

**Comment by erikrose** [comment]
Okay, let's see if it still happens with curl. If it does, there's something amiss with your cert store, or you're getting MITMd.

1. curl 'https://pypi.python.org/packages/source/p/pip/pip-8.0.3.tar.gz' > /dev/null
2. curl 'https://pypi.python.org/packages/source/s/setuptools/' > /dev/null
3. curl 'https://pypi.python.org/packages/source/w/wheel/wheel-0.29.0.tar.gz' > /dev/null

If it breaks, you'll see some error output.

**Comment by Lohoris** [comment]
Yep!

```
looris@termite:/tmp$ curl 'https://pypi.python.org/packages/source/p/pip/pip-8.0.3.tar.gz' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html
```

Given the error it makes me think it just can't find the certificates, rather than them being wrong… is that so?

**Comment by erikrose** [comment]
Most likely. Do you have the https://packages.debian.org/wheezy/ca-certificates package installed?

**Comment by Lohoris** [comment]
It's installed but… I guess that's a _very_ old version, maybe?

```
looris@termite:/tmp$ dpkg -s ca-certificates
Package: ca-certificates
Status: install ok installed
Priority: optional
Section: misc
Installed-Size: 373
Maintainer: Michael Shuler <michael@pbandjelly.org>
Architecture: all
Multi-Arch: foreign
Version: 20141019+deb8u1
Depends: openssl (>= 1.0.0), debconf (>= 0.5) | debconf-2.0
Breaks: ca-certificates-java (<< 20121112+nmu1)
Enhances: openssl
Description: Common CA certificates
 This package includes PEM files of CA certificates to allow SSL-based
```

**Comment by erikrose** [comment]
Hmm, perhaps. Try upgrading it and see if anything changes.

**Comment by Lohoris** [comment]
Ok, now it works, thanks for your patience!

**Comment by erikrose** [comment]
Hooray!
