### ISSUE TITLE
Unsupported filesystem layout. sites-available/enabled expected.

### ISSUE THREAD

**Issue by MidnightSeer** [certbot/certbot#3825]
I don't understand why i get this error.  

sudo ~/lets-encrypt/certbot-auto --apache

Here is output from the script:
Saving debug log to /var/log/letsencrypt/letsencrypt.log             
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org      
Cert not yet due for renewal                                         
Keeping the existing certificate                                     
Created an SSL vhost at                                              
/etc/apache2/sites-available/skulptrenegade.org-le-ssl.conf          
Deploying Certificate to VirtualHost                                 
/etc/apache2/sites-available/skulptrenegade.org-le-ssl.conf          
Enabling available site:                                             
/etc/apache2/sites-available/skulptrenegade.org-le-ssl.conf          
Deploying Certificate to VirtualHost                                 
/etc/apache2/mods-enabled/proxy.conf

Debug File:
2016-11-28 07:08:12,289:DEBUG:certbot.error_handler:Calling registered functions
2016-11-28 07:08:12,299:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/home/hades/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/hades/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/home/hades/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 515, in run
    lineage.chain, lineage.fullchain)
  File "/home/hades/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 374, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/home/hades/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 293, in deploy_cert
    self.enable_site(vhost)
  File "/home/hades/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1587, in enable_site
    "Unsupported filesystem layout. "
NotSupportedError: Unsupported filesystem layout. sites-available/enabled expected.

I have both:
/etc/apache2/sites-enabled
/etc/apache2/sites-available

ls /etc/apache2/sites-enabled/
000-default.conf  skulptrenegade.org.conf
ls /etc/apache2/sites-available/
000-default.conf  default-ssl.conf  skulptrenegade.org.conf

I also could not find the files the scripts says it created.

**Comment by pde** [comment]
Hi @MidnightSeer!

What OS/version are you running this on? If you're comfortable reading Python code, you can probably tell what went wrong by reading [this file](https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/constants.py)

**Comment by joohoi** [comment]
Lines 

```Deploying Certificate to VirtualHost
/etc/apache2/mods-enabled/proxy.conf```

look interesting. Could you pastebin your /etc/apache2/mods-enabled/proxy.conf

**Comment by joohoi** [comment]
@MidnightSeer did you get this solved? Anything weird in proxy.conf?

**Comment by joohoi** [comment]
Closing this as resolved, if the problem persists, feel free to add more information about the problem.
