### ISSUE TITLE
ImportError: libffi.so.5 - on Jessie

### ISSUE THREAD

**Issue by Barabrossa** [certbot/certbot#3831]
Hi,
I get following error when I am try run certbot command.Maybe is problem in PYTHONPATH? Thanks

\# certbot
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 14, in <module>
    from acme import jose
  File "/usr/lib/python2.7/dist-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/usr/lib/python2.7/dist-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/usr/lib/python2.7/dist-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 11, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libffi.so.5: cannot open shared object file: No such file or directory

\# dpkg -S libffi.so
libffi6:amd64: /usr/lib/x86_64-linux-gnu/libffi.so.6.0.2
libffi6:amd64: /usr/lib/x86_64-linux-gnu/libffi.so.6
libffi-dev:amd64: /usr/lib/x86_64-linux-gnu/libffi.so

**Comment by pde** [comment]
Hi! It looks like you've installed copies of `python-cryptography` and `PyOpenSSL` in `/usr/local/bin` (probably with `pip`?), and those versions are now broken, perhaps due to incompatibility with your currently installed version of OpenSSL.

You can confirm this by running `python` and then trying `import OpenSSL`.

There are many ways to fix this, but I'd probably recommend doing `sudo pip uninstall cryptogrpahy PyOpenSSL`, and sticking to verisons from your OS.  If you want to use `pip`, it's much safer to do it inside a `virtualenv`.

**Comment by pde** [comment]
Closing, but please reopen if this isn't the issue.
