### ISSUE TITLE
DependencyWarning Error

### ISSUE THREAD

**Issue by ozanguven** [certbot/certbot#3865]
After the recent update, I keep getting "DependencyWarning" when I run "certbot" command on Archlinux (3.8.4-1).

At below you can see the errors:

```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 18, in <module>
    from certbot import account
  File "/usr/lib/python2.7/site-packages/certbot/account.py", line 16, in <module>
    from acme import messages
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/site-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
```

Below packages are already installed:
python2 2.7.12-2
python2-requests 2.12.3-1
python2-urllib3 1.19.1-1

certbot 0.9.3-1
certbot-nginx 0.9.3-1

Any advice?

**Comment by pde** [comment]
What happens if you run `python` and then type `import requests`?

**Comment by ozanguven** [comment]
python2
Python 2.7.12 (default, Nov  7 2016, 11:55:55)
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 60, in <module>    from .packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
>>>

**Comment by ozanguven** [comment]
Okay, first I removed `requests`, then removed `requests-2.9.1.dist-info` directory and reinstalled `requests` again, now `certbot renew` works.

```
pip uninstall requests
rm -R /usr/lib/python2.7/site-packages/requests-2.9.1.dist-info/
pip2.7 install requests
```
