### ISSUE TITLE
Problems running on CentOS 7 

### ISSUE THREAD

**Issue by mhayes14** [certbot/certbot#3894]
Hi

Having issues running on CentOS 7. Installed via EPEL, had no problems with this in the past.

Python 2.7.5
certbot 0.9.3

```
2016-12-11 21:59:56,459:DEBUG:certbot.main:Root logging level set at 20
2016-12-11 21:59:56,459:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-12-11 21:59:56,467:DEBUG:certbot.main:certbot version: 0.9.3
2016-12-11 21:59:56,467:DEBUG:certbot.main:Arguments: ['--webroot', '-w', '<removed>, '-d', '<removed>', '-d', '<removed>']
2016-12-11 21:59:56,467:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-12-11 21:59:56,475:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2016-12-11 21:59:56,482:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x2fd1050>
Prep: True
2016-12-11 21:59:56,482:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x2fd1050> and installer None
2016-12-11 22:00:00,771:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 558, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 368, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 353, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 117, in register
    backend=default_backend())))
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 40, in default_backend
    _default_backend = MultiBackend(_available_backends())
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 27, in _available_backends
    "cryptography.backends"
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 37, in <module>
    from cryptography.hazmat.backends.openssl.x509 import _Certificate
  File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/backends/openssl/x509.py", line 24, in <module>
    class _Certificate(object):
  File "/usr/lib64/python2.7/site-packages/cryptography/utils.py", line 23, in register_decorator
    verify_interface(iface, klass)
  File "/usr/lib64/python2.7/site-packages/cryptography/utils.py", line 43, in verify_interface
    actual = inspect.getargspec(getattr(klass, method))
  File "/usr/lib64/python2.7/inspect.py", line 815, in getargspec
    raise TypeError('{!r} is not a Python function'.format(func))
TypeError: <method-wrapper '__ne__' of type object at 0x30aad10> is not a Python function
```

Thanks

**Comment by pde** [comment]
Your system's copy of `python-cryptography` is out of sync with your copy of `openssl` / `libssl-dev`. Probably upgrading `python-cryptography` and `pyOpenSSL` will fix this.

**Comment by pde** [comment]
Actually, this is a little different form the usual `ImportError` that people get from `cryptograhy` so I'll leave it open until @mhayes14 confirms that this is a version mismatch problem.

**Comment by mhayes14** [comment]
Thanks for your advice. These dependencies all seem to be up to date (e.g. `Requirement already up-to-date: cryptography in /usr/lib64/python2.7/site-packages`, `Requirement already up-to-date: pyOpenSSL in /usr/lib/python2.7/site-packages`). Any further suggestions?

**Comment by pde** [comment]
@mhayes14 are you running `pip install -U` there?  How are you installing Certbot?

**Comment by mhayes14** [comment]
@pde Yep. Certbot is installed via yum with EPEL. Thanks.

**Comment by pde** [comment]
@alex @reaperhulk any thoughts on that particular error?  I've never seen it before.

@mhayes14 I would recommend `pip uninstall cryptography pyopenssl`, and installing those dependencies with `yum` instead.

**Comment by alex** [comment]
I've also never seen this before. I believe this is what I would expect to see if I somehow had a copy of cryptography that was part fairly-old version and new-ish version. But I have no idea what one would do to cause that.

**Comment by mhayes14** [comment]
Installing `python-cryptography` via yum resolved the problem. I'm not sure how this happened, I've not had a problem previously despite similar setups. Thanks for your help.

**Comment by grt1st** [comment]
@mhayes14 It quite works,thank you dude.
