### ISSUE TITLE
Catch and diagnose python crytography ImportError?

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3895]
We get a lot of these. They happen for different causes, but probably we could provide information that's better than a traceback.

**Comment by pde** [comment]
For instance: #3894 #3831 #3573 #2122

**Comment by pde** [comment]
@bmw and I talked about asking to have this mitigation implemented in upstream `python-cryptography` (cc: @alex @reaperhulk), but I actually think we might be able to do a slightly better job in Certbot, because we can probably distinguish some cases:

* User seems to have `pip install`ed stuff that is broken and messing with OS Certbot packages
* User is running `certbot-auto`, which means that a broken `python-cryptography` is probably due to having upgraded `openssl` since they made their venv

Are there other cases for us to think about?

**Comment by pde** [comment]
* 'pip install cryptography' fails from within `certbot-auto`, which probably means your `libssl-dev` build environment is either broken or incompatible with the version of `python-cryptography` that we pinned?

**Comment by pde** [comment]
Also #1646

**Comment by pde** [comment]
And #2544

**Comment by derFunk** [comment]
I still wasn't able to resolve this on a Debian Jessie instance, upgraded from Wheezy (dependency to libffi 5 not satisfied):

```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 14, in <module>
    from acme import jose
  File "/usr/lib/python2.7/dist-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/usr/lib/python2.7/dist-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/usr/lib/python2.7/dist-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libffi.so.5: cannot open shared object file: No such file or directory
```

See also https://github.com/certbot/certbot/issues/3831.

**Comment by bmw** [comment]
@pde are you still working on this? You showed me some code for it at one point. What's it's current status?

**Comment by pde** [comment]
I made a small start on it, in the [diagnose-pip-errors](https://github.com/certbot/certbot/tree/diagnose-pip-errors) branch. Not sure if I'm going to have enough cycles to pop this off the stack soon, so I'd be happy to give it away if anyone is interested.
