### ISSUE TITLE
Problem while installing certbot

### ISSUE THREAD

**Issue by vallettea** [certbot/certbot#3897]
I'm running nginx on ubuntu 15.1 with python 2.7.9 from anaconda installed but I get the following error : 

```
root@ubuntu:~# ./certbot-auto
Bootstrapping dependencies for Debian-based OSes...
Hit http://mirrors.linode.com wily InRelease
Hit http://mirrors.linode.com wily-updates InRelease
Hit http://mirrors.linode.com wily-backports InRelease
Hit http://security.ubuntu.com wily-security InRelease
Hit http://ppa.launchpad.net wily InRelease
Hit http://mirrors.linode.com wily/main Sources
Hit http://mirrors.linode.com wily/restricted Sources
Hit http://mirrors.linode.com wily/universe Sources
Hit http://mirrors.linode.com wily/multiverse Sources
Hit http://mirrors.linode.com wily/main amd64 Packages
Hit http://mirrors.linode.com wily/restricted amd64 Packages
Hit http://mirrors.linode.com wily/universe amd64 Packages
Hit http://mirrors.linode.com wily/multiverse amd64 Packages
Hit http://mirrors.linode.com wily/main i386 Packages
Hit http://mirrors.linode.com wily/restricted i386 Packages
Hit http://mirrors.linode.com wily/universe i386 Packages
Hit http://mirrors.linode.com wily/multiverse i386 Packages
Hit http://mirrors.linode.com wily/main Translation-en
Hit http://mirrors.linode.com wily/multiverse Translation-en
Hit http://mirrors.linode.com wily/restricted Translation-en
Hit http://security.ubuntu.com wily-security/main Sources
Hit http://security.ubuntu.com wily-security/restricted Sources
Hit http://mirrors.linode.com wily/universe Translation-en
Hit http://ppa.launchpad.net wily/main amd64 Packages
Hit http://mirrors.linode.com wily-updates/main Sources
Hit http://mirrors.linode.com wily-updates/restricted Sources
Hit http://mirrors.linode.com wily-updates/universe Sources
Hit http://mirrors.linode.com wily-updates/multiverse Sources
Hit http://security.ubuntu.com wily-security/universe Sources
Hit http://mirrors.linode.com wily-updates/main amd64 Packages
Hit http://ppa.launchpad.net wily/main i386 Packages
Hit http://mirrors.linode.com wily-updates/restricted amd64 Packages
Hit http://security.ubuntu.com wily-security/multiverse Sources
Hit http://mirrors.linode.com wily-updates/universe amd64 Packages
Hit http://mirrors.linode.com wily-updates/multiverse amd64 Packages
Hit http://mirrors.linode.com wily-updates/main i386 Packages
Hit http://ppa.launchpad.net wily/main Translation-en
Hit http://mirrors.linode.com wily-updates/restricted i386 Packages
Hit http://mirrors.linode.com wily-updates/universe i386 Packages
Hit http://mirrors.linode.com wily-updates/multiverse i386 Packages
Hit http://security.ubuntu.com wily-security/main amd64 Packages
Hit http://mirrors.linode.com wily-updates/main Translation-en
Hit http://mirrors.linode.com wily-updates/multiverse Translation-en
Hit http://mirrors.linode.com wily-updates/restricted Translation-en
Hit http://mirrors.linode.com wily-updates/universe Translation-en
Hit http://mirrors.linode.com wily-backports/main Sources
Hit http://security.ubuntu.com wily-security/restricted amd64 Packages
Hit http://security.ubuntu.com wily-security/universe amd64 Packages
Hit http://security.ubuntu.com wily-security/multiverse amd64 Packages
Hit http://security.ubuntu.com wily-security/main i386 Packages
Hit http://mirrors.linode.com wily-backports/restricted Sources
Hit http://mirrors.linode.com wily-backports/universe Sources
Hit http://mirrors.linode.com wily-backports/multiverse Sources
Hit http://mirrors.linode.com wily-backports/main amd64 Packages
Hit http://mirrors.linode.com wily-backports/restricted amd64 Packages
Hit http://mirrors.linode.com wily-backports/universe amd64 Packages
Hit http://mirrors.linode.com wily-backports/multiverse amd64 Packages
Hit http://mirrors.linode.com wily-backports/main i386 Packages
Hit http://mirrors.linode.com wily-backports/restricted i386 Packages
Hit http://security.ubuntu.com wily-security/restricted i386 Packages
Hit http://mirrors.linode.com wily-backports/universe i386 Packages
Hit http://mirrors.linode.com wily-backports/multiverse i386 Packages
Hit http://mirrors.linode.com wily-backports/main Translation-en
Hit http://mirrors.linode.com wily-backports/multiverse Translation-en
Hit http://mirrors.linode.com wily-backports/restricted Translation-en
Hit http://security.ubuntu.com wily-security/universe i386 Packages
Hit http://mirrors.linode.com wily-backports/universe Translation-en
Hit http://security.ubuntu.com wily-security/multiverse i386 Packages
Hit http://security.ubuntu.com wily-security/main Translation-en
Hit http://security.ubuntu.com wily-security/multiverse Translation-en
Hit http://security.ubuntu.com wily-security/restricted Translation-en
Hit http://security.ubuntu.com wily-security/universe Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
augeas-lenses is already the newest version.
dialog is already the newest version.
gcc is already the newest version.
libaugeas0 is already the newest version.
libffi-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
virtualenv is already the newest version.
ca-certificates is already the newest version.
libssl-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 102 not upgraded.
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.0agy4jHp02/pipstrap.py", line 146, in <module>
    exit(main())
  File "/tmp/tmp.0agy4jHp02/pipstrap.py", line 133, in main
    shell=True)
  File "/opt/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U /tmp/pipstrap-QKo3Qx/pip-8.0.3.tar.gz /tmp/pipstrap-QKo3Qx/setuptools-20.2.2.tar.gz /tmp/pipstrap-QKo3Qx/wheel-0.29.0.tar.gz' returned non-zero exit status 1
root@ubuntu:~#
```

any help appreciated.
Thanks

**Comment by pde** [comment]
@erikrose thoughts?

**Comment by erikrose** [comment]
Unfortunately, we're going to need to gather to some info to figure out what's going on. Can you...

1. Download (but don't unpack) https://pypi.python.org/packages/source/p/pip/pip-8.0.3.tar.gz, https://pypi.python.org/packages/source/s/setuptools/setuptools-20.2.2.tar.gz, and https://pypi.python.org/packages/source/w/wheel/wheel-0.29.0.tar.gz.
2. Run `pip install --no-index --no-deps -U pip-8.0.3.tar.gz setuptools-20.2.2.tar.gz wheel-0.29.0.tar.gz`.
3. Paste the hopefully informative error message here.

**Comment by erikrose** [comment]
Note to self: if that doesn't break, try activating the letsencrypt virtualenv first (assuming the script didn't delete it on failure).

**Comment by acejacek** [comment]
I have the same problem while running certbot-auto on Raspbery B. I did the test. Result: Illegal instruction. It can be connected to type of processor: `model name	: ARMv6-compatible processor rev 7 (v6l)`

**Comment by SwartzCr** [comment]
@acejacek certbot should be packaged for raspberry pi, have you tried downloading the packaged version?

**Comment by acejacek** [comment]
@SwartzCr No, I did not tried packaged version, I couldn't find any. But my problem is solved, I've found [acme-nginx](https://github.com/kshcherban/acme-nginx), which works OK for my simple needs.

**Comment by SwartzCr** [comment]
Okay - I'll close this ticket then, but feel free to come chat on the if you need help in the future. More general let's encrypt help can be found on iRC at #letsencrypt on irc.freenode.net or at community.letsencrypt.org
