### ISSUE TITLE
certbot certonly --manual -> "An unexpected error occurred"

### ISSUE THREAD

**Issue by losvedir** [certbot/certbot#3911]
I'm running certbot 0.9.3 installed via homebrew on macOS Sierra 10.12.1.

I'm trying to run `sudo certbot certonly --manual` in order to generate my certificate to install on my heroku app.

The first time I ran it, the blue-background app crashed after I put in my email address (a mailing list at my work). I re-ran it using my real email address (thinking maybe that mattered somehow), and it advanced to the next step. But then when Agree to the Terms of Service it crashes. I've tried a few times now, and it's the same:

```
An unexpected error occurred:
The server experienced an internal error :: Unable to update registration
Please see the logfiles in /var/log/letsencrypt for more details.
```

I don't know what, if anything, in my logs is sensitive so I won't include the whole thing unless someone asks for it.

But at the end, it looks like here is where it's failing:

```
2016-12-14 14:35:43,317:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/reg/7252540 ....
```

```
2016-12-14 14:35:47,386:DEBUG:root:Received <Response [500]>. Headers: {'Content-Length': '107', 'Boulder-Request-Id': '...', 'Expires': 'Wed, 14 Dec 2016 14:35:47 GMT', 'Server': 'nginx', 'Connection': 'close', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Boulder-Requester': '7252540', 'Date': 'Wed, 14 Dec 2016 14:35:47 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '...'}. Content: '{\n  "type": "urn:acme:error:serverInternal",\n  "detail": "Unable to update registration",\n  "status": 500\n}'
```

**Comment by footcow** [comment]
Same error here with Debian Jessie

`2016-12-14 14:39:46,837:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-reg. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "uk7JAhLZrYfbnn4jeIy6tDK1DLyIKi2YQK-POvIeLOSUJOjg5Lmhxl66eK_NQGN456KBO7pOf5YaM3KUJt_7TMl7LAU-8MMTXNjn4lUy4xrb1zgaONO0JKwC-W7xE5-mWOqfcWSmj4du_AMcfUhLSumKYm3hiYuMR1qa-79Plqu_w7C40z9VgfPVbtLftGv0-8SSxH2ZCUEGIS21yGiN8gdxIcJICjXo3Giu2MRQYr0Ek9vkqI2bWo1kMaKktvMEmO1h2XNI1qhVL5ySeeMOA0UoqUl8sU2fYcN_lK0-PtNdrttrThpmk6rAolKpl10V9ApXFQBSPRdev92Qn-mUKQ"}}, "protected": "eyJub25jZSI6ICI2TXRkLWNkVllIVzBoLW5PbDgyNFZfcUx6UHNBM211YWt0RC1VM1FRb3prIn0", "payload": "eyJjb250YWN0IjogWyJtYWlsdG86aGVydmVAdGFwcHVibGlzaGVyLmNvbSJdLCAicmVzb3VyY2UiOiAibmV3LXJlZyJ9", "signature": "Yr9yOPJP1wHX1j1oCke_HeITZgJYm9U4pQoL7fZTd-txVSYJXeoC6QI4Cxv4V7FXW6_eU1CtUF0Un_2B0UlHO65rGlNEmJDp2SQr1j3D6aRyUv9qMV9fFd0DaVvAwIHqOlRNGUpWaycyvaDHZCNjFkg1q4zkD6Y9IEngW2CYyQgOpJx295TXa9IyTlE3tUPD6MTigdYpOXBHiWibtZpiLjP9AxFcq_bgpB81pPKvqg29NEDPLQhpmFSsydvsKk9CSh_1zw72X2k8mcQKK4FX-a4eEZpM19GNqx86XEWlGgJ9qMusUuZ3C57rACYNsYI_ds4qEIA5_01qfSNPd938Nw"}'}
2016-12-14 14:39:50,037:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-reg HTTP/1.1" 500 62
2016-12-14 14:39:50,039:DEBUG:root:Received <Response [500]>. Headers: {'Content-Length': '62', 'Boulder-Request-Id': 'oSJlHDsssbTleXo0WTlgG-4crQAHDPQRzwsP78LhCg0', 'Expires': 'Wed, 14 Dec 2016 14:39:50 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 14 Dec 2016 14:39:50 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'wb1o7QrbuSFDHOAmtiyjyCP_Lz3N3EuBQewq45qwmA4'}. Content: '{\n  "type": "urn:acme:error:serverInternal",\n  "status": 500\n}'
2016-12-14 14:39:50,040:DEBUG:acme.client:Storing nonce: '\xc1\xbdh\xed\n\xdb\xb9!C\x1c\xe0&\xb6,\xa3\xc8#\xff/=\xcd\xdcK\x81A\xec*\xe3\x9a\xb0\x98\x0e'
2016-12-14 14:39:50,040:DEBUG:acme.client:Received response <Response [500]> (headers: {'Content-Length': '62', 'Boulder-Request-Id': 'oSJlHDsssbTleXo0WTlgG-4crQAHDPQRzwsP78LhCg0', 'Expires': 'Wed, 14 Dec 2016 14:39:50 GMT', 'Server': 'nginx', 'Connection': 'close', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Wed, 14 Dec 2016 14:39:50 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': 'wb1o7QrbuSFDHOAmtiyjyCP_Lz3N3EuBQewq45qwmA4'}): '{\n  "type": "urn:acme:error:serverInternal",\n  "status": 500\n}'
2016-12-14 14:39:50,041:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 558, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 368, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 353, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 120, in register
    regr = perform_registration(acme, config)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 150, in perform_registration
    return acme.register(messages.NewRegistration.from_data(email=config.email))
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 96, in register
    response = self.net.post(self.directory[new_reg], new_reg)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 649, in post
    return self._check_response(response, content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 565, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:serverInternal :: The server experienced an internal error`

**Comment by cpu** [comment]
Please check status.letsencrypt.org - this is the result of an ongoing incident server side.
