### ISSUE TITLE
Microsecond DeserializationError in acme/jose/json_util.py

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3927]
Observed here: https://travis-ci.org/certbot/certbot/jobs/184330468#L4348

```
+certbot --server http://localhost:4000/directory --no-verify-ssl --tls-sni-01-port 5001 --http-01-port 5002 --manual-test-mode --config-dir /tmp/leitXaa6/conf --work-dir /tmp/leitXaa6/work --logs-dir /tmp/leitXaa6/logs --non-interactive --no-redirect --agree-tos --register-unsafely-without-email --debug -vv --authenticator standalone --installer null --renew-by-default auth --csr /tmp/leitXaa6/csr-p384.der --cert-path /tmp/leitXaa6/csr/cert-p384.pem --chain-path /tmp/leitXaa6/csr/chain-p384.pem
Root logging level set at 0
Saving debug log to /tmp/leitXaa6/logs/letsencrypt.log
certbot version: 0.10.0.dev0
Arguments: ['--server', 'http://localhost:4000/directory', '--no-verify-ssl', '--tls-sni-01-port', '5001', '--http-01-port', '5002', '--manual-test-mode', '--config-dir', '/tmp/leitXaa6/conf', '--work-dir', '/tmp/leitXaa6/work', '--logs-dir', '/tmp/leitXaa6/logs', '--non-interactive', '--no-redirect', '--agree-tos', '--register-unsafely-without-email', '--debug', '-vv', '--authenticator', 'standalone', '--installer', 'null', '--renew-by-default', '--csr', '/tmp/leitXaa6/csr-p384.der', '--cert-path', '/tmp/leitXaa6/csr/cert-p384.pem', '--chain-path', '/tmp/leitXaa6/csr/chain-p384.pem']
Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#script,PluginEntryPoint#apache,PluginEntryPoint#null)
Requested authenticator standalone and installer null
Single candidate plugin: * null
Description: Null Installer
Interfaces: IInstaller, IPlugin
Entry point: null = certbot.plugins.null:Installer
Initialized: <certbot.plugins.null.Installer object at 0x7f6981493ad0>
Prep: True
Single candidate plugin: * standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x7f6981493ed0>
Prep: True
Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x7f6981493ed0> and installer <certbot.plugins.null.Installer object at 0x7f6981493ad0>
Picked account: <Account(029eda689fa59664e67c23c63a78f5bd)>
Sending GET request to http://localhost:4000/directory.
Starting new HTTP connection (1): localhost
http://localhost:4000 "GET /directory HTTP/1.1" 200 220
Received response:
HTTP 200
Content-Type: application/json
Replay-Nonce: EWq8NS1TuiwLMwJ4-CJhYO0dhZ5TdT5hbwerleURYYc
Date: Thu, 15 Dec 2016 19:07:22 GMT
Content-Length: 220

{
  "new-authz": "http://127.0.0.1:4000/acme/new-authz",
  "new-cert": "http://127.0.0.1:4000/acme/new-cert",
  "new-reg": "http://127.0.0.1:4000/acme/new-reg",
  "revoke-cert": "http://127.0.0.1:4000/acme/revoke-cert"
}
CSR: CSR(file='/tmp/leitXaa6/csr-p384.der', data='0\x82\x01"0\x81\xa9\x02\x01\x000\x000v0\x10\x06\x07*\x86H\xce=\x02\x01\x06\x05+\x81\x04\x00"\x03b\x00\x04\xef+\xb8\xb1\xb9\xd8C,\x1d\xc7v@J\x96\xf0\x93\xf8\x96\x14\xa3\xb0\x8fe\x9c\x9e\xe8#K\xd8\x8e]#\x87\'\xe1\xe2}\x02M\x98\xc3\xcb\xa2?\xd1\x1e\xaa\x80\xe6\xe3\xfd\x9d\xe2\xa1\x85\xdb]N\xf8\xc4\xa6 \xa4\x8b[\xf4\x0cSt\xc1\xc0Q(\x8c\xcc%%\xa2\xd6K)k\xda\xb5g6(\xd8\x8b\xc1H\xbfo2i\x1e\xa0*0(\x06\t*\x86H\x86\xf7\r\x01\t\x0e1\x1b0\x190\x17\x06\x03U\x1d\x11\x04\x100\x0e\x82\x0cecdsa.le.wtf0\n\x06\x08*\x86H\xce=\x04\x03\x02\x03h\x000e\x021\x00\xf5\x9e\xf4\xfb\x81||\x83m@\xcds\xd3\x91\x1d\xf5@\xd4\x01#\x92L\xfb\x8c\x11\x90\x92\xc3;;Kz\x9e\x88p\x16\xfd\x8f\xeegd\xcf\xa8Zy\xeb\xf9\xf5\x020P\xbb2z\x9b\xd3\xac;\x9b@\x99P\x7f\xf0\xdd\xe5\x8ey\xb2\xca?\xecIbf\xe1,\xe8\xb2\x08\x1b4TQ\x12\xcc\xc1\xfd<\xfa\x82\'\xfeP6\x96\xf1\xbc', form='der'), domains: [u'ecdsa.le.wtf']
Requesting fresh nonce
Sending HEAD request to http://127.0.0.1:4000/acme/new-authz.
Starting new HTTP connection (1): 127.0.0.1
http://127.0.0.1:4000 "HEAD /acme/new-authz HTTP/1.1" 405 0
Received response:
HTTP 405
Allow: POST
Content-Type: application/problem+json
Replay-Nonce: UFEDjQkRucLMjhfoLhy8sL6EAVouuOXn28k_QB_DSQ8
Date: Thu, 15 Dec 2016 19:07:22 GMT
Content-Length: 91


Storing nonce: UFEDjQkRucLMjhfoLhy8sL6EAVouuOXn28k_QB_DSQ8
JWS payload:
{
  "identifier": {
    "type": "dns", 
    "value": "ecdsa.le.wtf"
  }, 
  "resource": "new-authz"
}
Sending POST request to http://127.0.0.1:4000/acme/new-authz:
{
  "header": {
    "alg": "RS256", 
    "jwk": {
      "e": "AQAB", 
      "kty": "RSA", 
      "n": "6JxxspSOFQEavQsA4lsYmRaY2cRSlKOp_EEg0hfuUzFraXk9XO0fWmH44wRonlR3n1mQTCBOa2kdZwweCwCK11AtS3KmgtnGxA8kQEJxZANBhHy7W8M4C4xcy6160gPiJYspFTB6vGllxh-cDmXKsOttNAF6biVICjBjneNEsQvyqPzDVR2NW_MJQgLXUghy5UbsNG_chgFAlgamoex2XZGNaFGbfylRiL-A2YhUYV-WAEaAiWNhjmBximLxo-1u73_-RvMH3GaftB0tH2pZuKK5oUf0oyYWMsQVnRMnn1C1U5Oc5a3HhevrYGWWJaFH5TX0FA3BevHVF45IGNu2nQ"
    }
  }, 
  "protected": "eyJub25jZSI6ICJVRkVEalFrUnVjTE1qaGZvTGh5OHNMNkVBVm91dU9YbjI4a19RQl9EU1E4In0", 
  "payload": "ewogICJpZGVudGlmaWVyIjogewogICAgInR5cGUiOiAiZG5zIiwgCiAgICAidmFsdWUiOiAiZWNkc2EubGUud3RmIgogIH0sIAogICJyZXNvdXJjZSI6ICJuZXctYXV0aHoiCn0", 
  "signature": "RP-h9kZB0HVhBqqoo9mZi4W6C1k8iBjqa8zs6QRDJQ5vhgTKq7x5kBzGWZDGgw-yA7vBLiChXdCIw1Xb0d6QQfFM1keMLzcSKyZhyZTGj5fFxFwj_8F6gUCU1yS2f_uaht9QQk9GcwmoNPz2m2lp-vjlQRrzB6KNjfPBD6ZX3Cxt3617XhVZfW7vKUf-0eCcGak92ikm_GhUw_UERdr5GCy5r6gJUaemCp0f680ol0PHHf_gF-bwBtBPORCv2ccRYXWIQJzjC7gLi_iJidg3kbJoslRrAuKjwZKdw1CXvoYeihUKUzQXrfGM-6y4tHDJXVwumBB5PYDW04Dzq-_tWQ"
}
http://127.0.0.1:4000 "POST /acme/new-authz HTTP/1.1" 201 931
Received response:
HTTP 201
Content-Type: application/json
Link: <http://127.0.0.1:4000/acme/new-cert>;rel="next"
Location: http://127.0.0.1:4000/acme/authz/3p4dRTFbUDHls059TxWNSAwI4bGYRKNe0Gm3I6_QZ-g
Replay-Nonce: 5PbQttV_-1jGDQw90YjIwaQu0z-DxV6BXxN57oar2V4
Date: Thu, 15 Dec 2016 19:07:23 GMT
Content-Length: 931

{
  "identifier": {
    "type": "dns",
    "value": "ecdsa.le.wtf"
  },
  "status": "pending",
  "expires": "2016-12-22T19:07:22.999999964Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "http://127.0.0.1:4000/acme/challenge/3p4dRTFbUDHls059TxWNSAwI4bGYRKNe0Gm3I6_QZ-g/25",
      "token": "TAH1_dXZJA4RNacmorjSV6zL6yo1ylHS_VDyy0ZSL4k"
    },
    {
      "type": "http-01",
      "status": "pending",
      "uri": "http://127.0.0.1:4000/acme/challenge/3p4dRTFbUDHls059TxWNSAwI4bGYRKNe0Gm3I6_QZ-g/26",
      "token": "UOnlGdn1TeqXw3eM0bOdOorHcoxsSAIJYD56yZ0T6Ao"
    },
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "http://127.0.0.1:4000/acme/challenge/3p4dRTFbUDHls059TxWNSAwI4bGYRKNe0Gm3I6_QZ-g/27",
      "token": "alLVlrRjSdYOPS_57W3QqDEuVhXvzOjhtrBWR7N7l_A"
    }
  ],
  "combinations": [
    [
      0
    ],
    [
      2
    ],
    [
      1
    ]
  ]
}
Storing nonce: 5PbQttV_-1jGDQw90YjIwaQu0z-DxV6BXxN57oar2V4
Exiting abnormally:
Traceback (most recent call last):
  File "/home/travis/build/certbot/certbot/.tox/cover/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/home/travis/build/certbot/certbot/certbot/main.py", line 819, in main
    return config.func(config, plugins)
  File "/home/travis/build/certbot/certbot/certbot/main.py", line 609, in obtain_cert
    _csr_obtain_cert(config, le_client)
  File "/home/travis/build/certbot/certbot/certbot/main.py", line 579, in _csr_obtain_cert
    certr, chain = le_client.obtain_certificate_from_csr(config.domains, csr, typ)
  File "/home/travis/build/certbot/certbot/certbot/client.py", line 239, in obtain_certificate_from_csr
    authzr = self.auth_handler.get_authorizations(domains)
  File "/home/travis/build/certbot/certbot/certbot/auth_handler.py", line 68, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/home/travis/build/certbot/certbot/acme/acme/client.py", line 212, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/home/travis/build/certbot/certbot/acme/acme/client.py", line 195, in request_challenges
    return self._authzr_from_response(response, identifier)
  File "/home/travis/build/certbot/certbot/acme/acme/client.py", line 171, in _authzr_from_response
    body=messages.Authorization.from_json(response.json()),
  File "/home/travis/build/certbot/certbot/acme/acme/jose/json_util.py", line 293, in from_json
    return cls(**cls.fields_from_json(jobj))
  File "/home/travis/build/certbot/certbot/acme/acme/jose/json_util.py", line 288, in fields_from_json
    slot, value, error))
DeserializationError: Deserialization error: Could not decode 'expires' (u'2016-12-22T19:07:22.999999964Z'): Deserialization error: microsecond must be in 0..999999

Traceback (most recent call last):
  File "/home/travis/build/certbot/certbot/.tox/cover/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/home/travis/build/certbot/certbot/certbot/main.py", line 819, in main
    return config.func(config, plugins)
  File "/home/travis/build/certbot/certbot/certbot/main.py", line 609, in obtain_cert
    _csr_obtain_cert(config, le_client)
  File "/home/travis/build/certbot/certbot/certbot/main.py", line 579, in _csr_obtain_cert
    certr, chain = le_client.obtain_certificate_from_csr(config.domains, csr, typ)
  File "/home/travis/build/certbot/certbot/certbot/client.py", line 239, in obtain_certificate_from_csr
    authzr = self.auth_handler.get_authorizations(domains)
  File "/home/travis/build/certbot/certbot/certbot/auth_handler.py", line 68, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/home/travis/build/certbot/certbot/acme/acme/client.py", line 212, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/home/travis/build/certbot/certbot/acme/acme/client.py", line 195, in request_challenges
    return self._authzr_from_response(response, identifier)
  File "/home/travis/build/certbot/certbot/acme/acme/client.py", line 171, in _authzr_from_response
    body=messages.Authorization.from_json(response.json()),
  File "/home/travis/build/certbot/certbot/acme/acme/jose/json_util.py", line 293, in from_json
    return cls(**cls.fields_from_json(jobj))
  File "/home/travis/build/certbot/certbot/acme/acme/jose/json_util.py", line 288, in fields_from_json
    slot, value, error))
DeserializationError: Deserialization error: Could not decode 'expires' (u'2016-12-22T19:07:22.999999964Z'): Deserialization error: microsecond must be in 0..999999


travis_time:end:0919fec0:start=1481828516919747112,finish=1481828843048039056,duration=326128291944
[0K
[31;1mThe command "travis_retry tox && ([ "xxx$BOULDER_INTEGRATION" = "xxx" ] || ./tests/travis-integration.sh)" exited with 1.[0m
travis_fold:start:cache.2
[0Kstore build cache
travis_time:start:0bab88f6
[0K
travis_time:end:0bab88f6:start=1481828843053595771,finish=1481828843057775559,duration=4179788
[0Ktravis_time:start:23bcdc62
[0K[32;1mchange detected (content changed, file is created, or file is deleted):
/home/travis/.cache/pip/http/0/a/8/f/a/0a8faabd212d81beff3ad0e11f3e4746188c0ad05c9190218de2e48a
/home/travis/.cache/pip/http/0/e/7/b/9/0e7b99547a0247a24df2175f35e166cf96f0194417e99b4851dbf306
/home/travis/.cache/pip/http/1/1/4/a/4/114a41049557a84c55958c18d02d44eb147fadc5d401e269e3d7ea8e
/home/travis/.cache/pip/http/1/2/f/0/c/12f0cd18a3076db0eb5826e17852f4cdee9eb61327cae1626f135a27
/home/travis/.cache/pip/http/1/3/d/0/7/13d079be9bc04f1c81305bd90c36ae55a8da785cc06c54fda914c531
/home/travis/.cache/pip/http/1/c/f/2/e/1cf2ec08b116d0e8a4bd0c1c6441595628f3d6f6275c7d9cb54fb0c2
/home/travis/.cache/pip/http/2/2/8/1/d/2281ddaafdd93fe42769bedb55d3a2b9e1e6dc7ec1c52bbbd71e9bf7
/home/travis/.cache/pip/http/2/3/9/9/c/2399ce14e5d071a00b24636db2a7d8f9ef4a63fbd2d60206408e2290
/home/travis/.cache/pip/http/2/8/6/c/5/286c54cdc5b4148a51195597f569a332ef7fea34f79b203fcfd498bf
/home/travis/.cache/pip/http/3/a/f/3/a/3af3addf06e983a6c02f46e7bea70c221d3ff95bf1418fa6da354e14
/home/travis/.cache/pip/http/3/d/0/7/9/3d
[0m
[32;1m...
[0m
[32;1mchanges detected, packing new archive[0m
.
[32;1muploading archive[0m

travis_time:end:23bcdc62:start=1481828843062320854,finish=1481828851329256332,duration=8266935478
```

**Comment by bmw** [comment]
I haven't seen any reports of this problem in 2 years so I'm closing this issue. If anyone hits it, please comment or make a new issue.
