### ISSUE TITLE
Tracking bug for possible unit test parallelization heisenbugs

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3928]
There will probably be a few of these left over since #3836 landed. We can track them here.

**Comment by pde** [comment]
https://isnot.org/bugs/py33-io.txt

**Comment by pde** [comment]
I sometimes see this from `t27`:
```
======================================================================
FAIL: Test that relevant_values() can reject a default value.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pde/certbot/certbot/tests/storage_test.py", line 565, in test_relevant_values_default
    self.assertEqual(self._test_relevant_values_common(values), {})
AssertionError: {'rsa_key_size': 2048} != {}
- {'rsa_key_size': 2048}
+ {}

----------------------------------------------------------------------
Ran 575 tests in 8.439s

FAILED (failures=1)
Please deploy a DNS TXT record under the name
_acme-challenge.foo.com with the following value:

Slui_IKoxhFjRRete7mBO4dnCu24lJt4G4q1k-CO1ho

Once this is deployed,
ERROR: InvocationError: '/home/pde/certbot/.tox/py27/bin/nosetests -v certbot --processes=-1 --process-timeout=100'
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
```

**Comment by dashaxiong** [comment]
Here's one that has been cropping up occassionally. It occurs on a `tox` run of all supported pythons, `py35` has the error. Yet running `tox -e py35` by itself doesn't.

```
ERROR: test_non_systemd_os_info (certbot.tests.util_test.OsInfoTest)
Traceback (most recent call last):
  File "/home/craig/Engineering/certbot/.tox/py35/lib/python3.5/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/craig/Engineering/certbot/certbot/tests/util_test.py", line 418, in test_non_systemd_os_info
    self.assertEqual(get_os_info()[0], 'nonsystemd')
  File "/home/craig/Engineering/certbot/certbot/util.py", line 236, in get_os_info
    return get_python_os_info()
  File "/home/craig/Engineering/certbot/certbot/util.py", line 327, in get_python_os_info
    platform.system(),
  File "/usr/local/lib/python3.5/platform.py", line 1095, in system
    return uname().system
  File "/usr/local/lib/python3.5/platform.py", line 1061, in uname
    processor = _syscmd_uname('-p', '')
  File "/usr/local/lib/python3.5/platform.py", line 818, in _syscmd_uname
    output = f.read().strip()
ValueError: I/O operation on closed file.

Ran 574 tests in 8.150s

FAILED (errors=1)
ERROR: InvocationError: '/home/craig/Engineering/certbot/.tox/py35/bin/nosetests -v certbot --processes=-1 --process-timeout=100'
```
