### ISSUE TITLE
Interactivity glitch in git master

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3934]
```
root@isnot:/etc/apache2/sites-enabled# lel --config-dir /tmp/zzz --test-cert --agree-t --regi
Saving debug log to /var/log/letsencrypt/letsencrypt.log

Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
1: goxogle.com
2: isnot.org
3: is.isnot.org
4: tweedle.isnot.org
5: www.isnot.org
6: demo.reworld.org
-------------------------------------------------------------------------------
An unexpected error occurred:
AssertionError: Invalid IDisplay call for this prompt:
Select the appropriate numbers separated by commas and/or spaces, or leave input blank to select all options shown
Please see the logfiles in /var/log/letsencrypt for more details.
```

**Comment by pde** [comment]
Full log is:
```
2016-12-20 19:29:07,802:DEBUG:certbot.main:Root logging level set at 20
2016-12-20 19:29:07,803:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-12-20 19:29:07,803:DEBUG:certbot.main:certbot version: 0.10.0.dev0
2016-12-20 19:29:07,803:DEBUG:certbot.main:Arguments: ['--config-dir', '/tmp/zzz', '--test-cert', '--agree-t', '--regi']
2016-12-20 19:29:07,803:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#script,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#nginx,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-12-20 19:29:07,803:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2016-12-20 19:29:08,407:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7fdf74e84310>
Prep: True
2016-12-20 19:29:08,408:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7fdf74e84310> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7fdf74e84310>
2016-12-20 19:29:08,410:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "venv/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/home/ubuntu/letsencrypt/certbot/main.py", line 831, in main
    return config.func(config, plugins)
  File "/home/ubuntu/letsencrypt/certbot/main.py", line 561, in run
    domains, certname = _find_domains_or_certname(config, installer)
  File "/home/ubuntu/letsencrypt/certbot/main.py", line 290, in _find_domains_or_certname
    domains = display_ops.choose_names(installer)
  File "/home/ubuntu/letsencrypt/certbot/display/ops.py", line 111, in choose_names
    code, names = _filter_names(names)
  File "/home/ubuntu/letsencrypt/certbot/display/ops.py", line 161, in _filter_names
    tags=sorted_names, cli_flag="--domains", force_interactive=True)
  File "/home/ubuntu/letsencrypt/certbot/display/util.py", line 224, in checklist
    code, ans = self.input("Select the appropriate numbers separated "
  File "/home/ubuntu/letsencrypt/certbot/display/util.py", line 141, in input
    if self._return_default(message, default, cli_flag, force_interactive):
  File "/home/ubuntu/letsencrypt/certbot/display/util.py", line 259, in _return_default
    assert default is not None or force_interactive, msg
AssertionError: Invalid IDisplay call for this prompt:
Select the appropriate numbers separated by commas and/or spaces, or leave input blank to select all options shown
```
