### ISSUE TITLE
Renewal conf files should use relative paths for specifying live/archive dirs

### ISSUE THREAD

**Issue by pde** [certbot/certbot#3953]
Encountered while trying to move a config directory into our tree to make test farm tests with it:
```
certbot certificates --config-dir $PWD/tests/letstest/testdata/sample-config/

3 00:04:06,256:DEBUG:certbot.main:Root logging level set at 20
2016-12-23 00:04:06,257:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-12-23 00:04:06,257:DEBUG:certbot.main:certbot version: 0.10.0.dev0
2016-12-23 00:04:06,257:DEBUG:certbot.main:Arguments: ['--config-dir', '/home/pde/certbot/certbot/tests/letstest/testdata/sample-config/']
2016-12-23 00:04:06,258:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#script,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#nginx,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-12-23 00:04:06,259:WARNING:certbot.cert_manager:Renewal configuration file /home/pde/certbot/certbot/tests/letstest/testdata/sample-config/renewal/isnot.org.conf produced an unexpected error: expected /tmp/sample-config/live/isnot.org/cert.pem to be a symlink. Skipping.
2016-12-23 00:04:06,259:DEBUG:certbot.cert_manager:Traceback was:
Traceback (most recent call last):
  File "/home/pde/certbot/certbot/certbot/cert_manager.py", line 75, in certificates
    renewal_candidate = storage.RenewableCert(renewal_file, config)
  File "/home/pde/certbot/certbot/certbot/storage.py", line 392, in __init__
    self._check_symlinks()
  File "/home/pde/certbot/certbot/certbot/storage.py", line 431, in _check_symlinks
    "expected {0} to be a symlink".format(link))
CertStorageError: expected /tmp/sample-config/live/isnot.org/cert.pem to be a symlink

2016-12-23 00:04:06,260:WARNING:certbot.cert_manager:Renewal configuration file /home/pde/certbot/certbot/tests/letstest/testdata/sample-config/renewal/is.isnot.org.conf produced an unexpected error: expected /tmp/sample-config/live/is.isnot.org/cert.pem to be a symlink. Skipping.
2016-12-23 00:04:06,260:DEBUG:certbot.cert_manager:Traceback was:
Traceback (most recent call last):
  File "/home/pde/certbot/certbot/certbot/cert_manager.py", line 75, in certificates
    renewal_candidate = storage.RenewableCert(renewal_file, config)
  File "/home/pde/certbot/certbot/certbot/storage.py", line 392, in __init__
    self._check_symlinks()
  File "/home/pde/certbot/certbot/certbot/storage.py", line 431, in _check_symlinks
    "expected {0} to be a symlink".format(link))
CertStorageError: expected /tmp/sample-config/live/is.isnot.org/cert.pem to be a symlink
```
The problem is this:
```
cat tests/letstest/testdata/sample-config/renewal/isnot.org.conf
# renew_before_expiry = 30 days
version = 0.10.0.dev0
archive_dir = /tmp/sample-config/archive/isnot.org
cert = /tmp/sample-config/live/isnot.org/cert.pem
privkey = /tmp/sample-config/live/isnot.org/privkey.pem
chain = /tmp/sample-config/live/isnot.org/chain.pem
fullchain = /tmp/sample-config/live/isnot.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = apache
installer = apache
account = 7938300b2c3f1793e9f494c2be6918a5
config_dir = /tmp/sample-config
```
This config dir was created below `/tmp/` on one machine, and is unhappy being moved elsewhere.

**Comment by pde** [comment]
Probably these paths should be `archive/isnot.org`, `live/isnot.org/cert.pem` and with the starting path set to `config_dir`?

**Comment by ohemorange** [comment]
The cert/privkey/chain/fullchain paths have been full paths since as early as 0.8.1.

**Comment by pde** [comment]
That's good news, it means we've already broken anyone who would have been broken by this? ;)

**Comment by ohemorange** [comment]
Alternatively, we've been sufficiently opinionated about workflow to set up stable (if inflexible) configuration patterns.

**Comment by pde** [comment]
Yup. But at least from a developer's POV being able to move those config dirs around is nice. I hadn't noticed this issue before because, although I was moving them between systems, they always lived in `/tmp/`.

**Comment by ohemorange** [comment]
Unless you're moving the renewal config file, but not the cert files. Then it's harder.

**Comment by pde** [comment]
I don't think it's possible to move a renewal conf file to anywhere that isn't `$config_dir/renewal`, and have it work?

**Comment by ohemorange** [comment]
Sure! Move everything over to a new config dir (and update the config dir), except the cert files which are left under the old directory structure.

**Comment by berglh** [comment]
I've just experienced this problem from a docker perspective. I use nginx and certbot containers, yet I may want to perform a scripted openssl check against the cert in cron to determine if I need to update the certs (no point increasing load on lets encrypt) on the host system. 

Upon this check completing, I would then run the certbot container and orchestrate the reloading of nginx configuration in the nginx container. I'm unaware of anything that can do this autonomously with certbot currently, although in hindsight it would kind of make sense that the certbot client should be able to perform a localised expiration check before checking for a renewal. 

I digress; this results in the problem my script trying to resolve the symlink to the archive folder which references the full paths as used in the docker container (currently the default path of configuration) which, due to some physical hardware restriction and volume encryption choices, mean that the symlinks don't resolve to the correct location on the host file system i.e. `/etc/letsencrypt` instead of `/encryptedvolume/etc/letsencrypt`.

I can *gaffa tape* this by using a single soft directory symlink on the host system to point `/etc/letsencrypt` at the right place, but I just thought I'd mention it as scenario is affected by this design choice for those in container land doing silly things.

**Comment by kousu** [comment]
I just experienced this too. I have multiple vhosts on a single server and I didn't want to have them share an _account key_, so I made different accounts by running with `--workdir` and `--config-dir`.

Now I'm making some changes. Our domain name for one vhost changed. I want to keep the account key -- I don't have to, but if I keep it the certificate transparency logs will look more legitimate -- so I want to keep using the same files, but rename the folder to match.

```
# mv /etc/letsencrypt-bainmagique.space/ /etc/letsencrypt-sunflowercollective
# certbot --work-dir /etc/letsencrypt-sunflowercollective/ --config-dir /etc/letsencrypt-sunflowercollective/ certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewal configuration file /etc/letsencrypt-sunflowercollective/renewal/sunflowercollective.org.conf produced an unexpected error: expected /etc/letsencrypt-bainmagique.space/live/sunflowercollective.org/cert.pem to be a symlink. Skipping.
Renewal configuration file /etc/letsencrypt-sunflowercollective/renewal/bainmagique.space.conf produced an unexpected error: expected /etc/letsencrypt-bainmagique.space/live/bainmagique.space/cert.pem to be a symlink. Skipping.

-------------------------------------------------------------------------------

The following renewal configuration files were invalid:
  /etc/letsencrypt-sunflowercollective/renewal/sunflowercollective.org.conf
  /etc/letsencrypt-sunflowercollective/renewal/bainmagique.space.conf
-------------------------------------------------------------------------------

```

Why are there absolute paths anywhere in this folder? I see these lines:

```
# grep -r bainmagique.space
renewal/sunflowercollective.org.conf:archive_dir = /etc/letsencrypt-bainmagique.space/archive/sunflowercollective.org
renewal/sunflowercollective.org.conf:cert = /etc/letsencrypt-bainmagique.space/live/sunflowercollective.org/cert.pem
renewal/sunflowercollective.org.conf:privkey = /etc/letsencrypt-bainmagique.space/live/sunflowercollective.org/privkey.pem
renewal/sunflowercollective.org.conf:chain = /etc/letsencrypt-bainmagique.space/live/sunflowercollective.org/chain.pem
renewal/sunflowercollective.org.conf:fullchain = /etc/letsencrypt-bainmagique.space/live/sunflowercollective.org/fullchain.pem
renewal/sunflowercollective.org.conf:config_dir = /etc/letsencrypt-bainmagique.space
renewal/sunflowercollective.org.conf:work_dir = /etc/letsencrypt-bainmagique.space
renewal/bainmagique.space.conf:archive_dir = /etc/letsencrypt-bainmagique.space/archive/bainmagique.space
renewal/bainmagique.space.conf:cert = /etc/letsencrypt-bainmagique.space/live/bainmagique.space/cert.pem
renewal/bainmagique.space.conf:privkey = /etc/letsencrypt-bainmagique.space/live/bainmagique.space/privkey.pem
renewal/bainmagique.space.conf:chain = /etc/letsencrypt-bainmagique.space/live/bainmagique.space/chain.pem
renewal/bainmagique.space.conf:fullchain = /etc/letsencrypt-bainmagique.space/live/bainmagique.space/fullchain.pem
renewal/bainmagique.space.conf:config_dir = /etc/letsencrypt-bainmagique.space
renewal/bainmagique.space.conf:work_dir = /etc/letsencrypt-bainmagique.space
```

This fixed it

```
# sed s/bainmagique.space/sunflowercollective/ renewal/sunflowercollective.org.conf  > renewal/sunflowercollective.org.conf_
# sed s/bainmagique.space/sunflowercollective/ renewal/bainmagique.space.conf > renewal/bainmagique.space.conf_
# mv renewal/sunflowercollective.org.conf_ renewal/sunflowercollective.org.conf
# mv renewal/bainmagique.space.conf_ renewal/bainmagique.space.conf
```

```
# certbot --work-dir /etc/letsencrypt-sunflowercollective/ --config-dir /etc/letsencrypt-sunflowercollective/ certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Found the following certs:
  Certificate Name: sunflowercollective.org
    Domains: sunflowercollective.org calc.collectiftournesol.org calc.sunflowercollective.org collectiftournesol.org
    Expiry Date: 2018-04-02 06:58:27+00:00 (VALID: 83 days)
    Certificate Path: /etc/letsencrypt-sunflowercollective/live/sunflowercollective.org/fullchain.pem
    Private Key Path: /etc/letsencrypt-sunflowercollective/live/sunflowercollective.org/privkey.pem
  Certificate Name: bainmagique.space
    Domains: bainmagique.space collectiftournesol.org sunflowercollective.org
    Expiry Date: 2018-03-02 02:00:27+00:00 (VALID: 52 days)
    Certificate Path: /etc/letsencrypt-sunflowercollective/live/bainmagique.space/fullchain.pem
    Private Key Path: /etc/letsencrypt-sunflowercollective/live/bainmagique.space/privkey.pem
-------------------------------------------------------------------------------
```

These paths don't need to be absolute.

**Comment by kenaniah** [comment]
This is still an issue. My infrastructure has a use case in which the certbot configs for multiple environments are stored in a git repository under different parent directories, and certbot continuously overwriting the renewal configs with absolute paths is a real headache.

**Comment by kenaniah** [comment]
One potential workaround would be to update the renewal config files after they have been regenerated. After running certbot, one could do something like the following to convert all absolute paths to relative ones:
```bash
find /etc/letsencrypt/ -path '*.conf' -print0 | xargs -0 sed -i '' -E 's/\= .+\/letsencrypt/\= relative_path/g'
```

**Comment by kousu** [comment]
I've migrated to https://github.com/acmesh-official/acme.sh on Linux and https://man.openbsd.org/acme-client on BSD. They have much more manageable configurations.
