### ISSUE TITLE
webroot auth has problem with _

### ISSUE THREAD

**Issue by profiwh** [certbot/certbot#3973]
/usr/bin/certbot certonly -c /etc/letsencrypt/cli.ini -n --webroot -w /mnt/servers/serverdomain/domain.cz/web/sms_cron  -d sms_cron.domain.cz
 --agree-tos

ends with error because of _ at DNS
version : 0.9.3-1~bpo8+1 from debian

2017-01-05 10:28:32,508:DEBUG:acme.client:Received response <Response [400]> (headers: {'Content-Length': '102', 'Boulder-Request-Id': 'MtzTbYF
nPVRhS_w9vjJzew010YnN5YnE9fbmXZZVjrM', 'Expires': 'Thu, 05 Jan 2017 10:28:35 GMT', 'Server': 'nginx', 'Connection': 'close', 'Cache-Control': '
max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Boulder-Requester': '7892334', 'Date': 'Thu, 05 Jan 2017 10:28:35 GMT', 'Content-Type':
'application/problem+json', 'Replay-Nonce': '_JMJyj6sMVl1ZtbaF25RwFQF1kSWnKwICYiZ_VDUBw0'}): '{\n  "type": "urn:acme:error:malformed",\n  "deta
il": "Invalid character in DNS name",\n  "status": 400\n}'
2017-01-05 10:28:32,510:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 563, in obtain_cert
    action, _ = _auth_from_domains(le_client, config, domains, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 100, in _auth_from_domains
    lineage = le_client.obtain_and_enroll_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 281, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 253, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 68, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 210, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 190, in request_challenges
    new_authz)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 649, in post
    return self._check_response(response, content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 565, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:malformed :: The request message was malformed :: Invalid character in DNS name

**Comment by bmw** [comment]
This actually isn't a problem with webroot. Let's Encrypt will not issue a certificate for a DNS name containing a "_" character because it's not a valid hostname. See letsencrypt/boulder#1225 for more info.
