### ISSUE TITLE
enforce_le_validity should enforce DNS name does not have enough labels

### ISSUE THREAD

**Issue by jsoref** [certbot/certbot#4015]
```sh
$ certbot -t -v --config-dir ~/letsencrypt/etc --work-dir ~/letsencrypt/lib --logs-dir ~/letsencrypt/log
...
certbot version: 0.10.0.dev0
...
Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
1: test
2: {censored}
3: {censored}.{fqdn}
4: test.{fqdn}
...
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel):
...
Obtaining a new certificate
JWS payload:
{
  "identifier": {
    "type": "dns",
    "value": "test"
  },
  "resource": "new-authz"
}
Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz:
{
  "header": {
    "alg": "RS256",
    "jwk": {
      "e": "AQAB",
      "kty": "RSA",
      "n": "{censored}"
    }
  },
  "protected": "{censored}",
  "payload": "{censored}",
  "signature": "{censored}"
}
https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-authz HTTP/1.1" 400 109
Received response:
HTTP 400
Server: nginx
Content-Type: application/problem+json
Content-Length: 109
Boulder-Request-Id: IHU_9Xb-u9Uak8nfZC6BFqxLWaLW2AyU3AlwndymcZs
Boulder-Requester: 8231837
Replay-Nonce: 1_r6VJcRNbo71Yix-2jexKajYr9I9V9n-ZL9bqU1jSs
Expires: Wed, 11 Jan 2017 01:46:00 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 11 Jan 2017 01:46:00 GMT
Connection: close

{
  "type": "urn:acme:error:malformed",
  "detail": "DNS name does not have enough labels",
  "status": 400
}
Storing nonce: 1_r6VJcRNbo71Yix-2jexKajYr9I9V9n-ZL9bqU1jSs
Exiting abnormally:
Traceback (most recent call last):
  File "~/certbot/venv/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "~/certbot/certbot/main.py", line 849, in main
    return config.func(config, plugins)
  File "~/certbot/certbot/main.py", line 575, in run
    action, lineage = _auth_from_available(le_client, config, domains, certname)
  File "~/certbot/certbot/main.py", line 107, in _auth_from_available
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "~/certbot/certbot/client.py", line 291, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "~/certbot/certbot/client.py", line 262, in obtain_certificate
    self.config.allow_subset_of_names)
  File "~/certbot/certbot/auth_handler.py", line 68, in get_authorizations
    domain, self.account.regr.new_authzr_uri)
  File "~/certbot/acme/acme/client.py", line 216, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "~/certbot/acme/acme/client.py", line 196, in request_challenges
    new_authz)
  File "~/certbot/acme/acme/client.py", line 667, in post
    return self._check_response(response, content_type=content_type)
  File "~/certbot/acme/acme/client.py", line 570, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:malformed :: The request message was malformed :: DNS name does not have enough labels
```

https://github.com/certbot/certbot/blob/a146102c733eb50649a4f72d1221547d72ed4d4d/certbot/util.py#L430
`def enforce_domain_sanity(domain)` should be rejecting tlds.

At least, afaik, especially given that letsencrypt does, yielding:
`DNS name does not have enough labels`

The tests in 2625daad75a9233ee0f2d57576adff23e6db1779 made things worse.

This is basically #1682 which was optimistically closed as a duplicate of #1814, but that PR didn't address #1682.

**Comment by nickfong** [comment]
I can add logic to detect if there is only one label in the domain (and update the associated test cases) unless someone else wants/has this issue already

**Comment by bmw** [comment]
Not catching this error on Certbot's side is intentional. We removed checks for this (and for underscore characters in labels which Let's Encrypt also doesn't support) in #3061.

The reason for this is that while Let's Encrypt won't issue for these domains, another ACME CAs might pop up or Let's Encrypt could change their policy in the future. We would like Certbot to continue to work in either of these scenarios and because Certbot can get packaged in an OS distro and not receive anything but security updates for years, we don't want a client side check preventing a user from requesting a cert that a CA will issue for.

**Comment by bmw** [comment]
Thinking about this a bit more, if you'd like to make these changes to `enforce_le_validity`, I'd be fine with that. The difference is error checking in `enforce_domain_sanity` is applied to all domains, even those given on the command line. In general, we're trying to be more conservative with the names we suggest, not adding a name to the list if we have reason to believe the CA won't issue for it.

**Comment by jsoref** [comment]
I don't think things have changed. Maybe I'll look at it in the fall…
