### ISSUE TITLE
Test failures on CentOS 6

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4044]
Using the test script I posted in #4043, tests on CentOS 6 fail with:
```
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_dry_run_flag (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 224, in test_dry_run_flag
[centos@127.0.0.1] out:     self.assertRaises(errors.Error, self.parse, short_args)
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_encode_revocation_reason (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 264, in test_encode_revocation_reason
[centos@127.0.0.1] out:     namespace = self.parse(['--reason', reason])
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_force_interactive (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 272, in test_force_interactive
[centos@127.0.0.1] out:     errors.Error, self.parse, "renew --force-interactive".split())
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_help (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 76, in test_help
[centos@127.0.0.1] out:     self._help_output(['--help'])  # assert SystemExit is raised here
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 56, in _help_output
[centos@127.0.0.1] out:     self.assertRaises(SystemExit, self.parse, args, output)
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_install_abspath (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 66, in test_install_abspath
[centos@127.0.0.1] out:     namespace = self.parse(['install', '--cert-path', cert,
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_must_staple_flag (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 175, in test_must_staple_flag
[centos@127.0.0.1] out:     namespace = self.parse(short_args)
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_no_gui (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 183, in test_no_gui
[centos@127.0.0.1] out:     namespace = self.parse(args)
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_option_was_set (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 253, in test_option_was_set
[centos@127.0.0.1] out:     self.parse('--rsa-key-size {0}'.format(key_size_value).split())
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_parse_domains (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 134, in test_parse_domains
[centos@127.0.0.1] out:     namespace = self.parse(short_args)
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_preferred_challenges (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 162, in test_preferred_challenges
[centos@127.0.0.1] out:     namespace = self.parse(short_args)
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_server_flag (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 170, in test_server_flag
[centos@127.0.0.1] out:     namespace = self.parse('--server example.com'.split())
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ======================================================================
[centos@127.0.0.1] out: ERROR: test_staging_flag (certbot.tests.cli_test.ParseTest)
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Traceback (most recent call last):
[centos@127.0.0.1] out:   File "/tmp/tmp.0yoK1JwZYF/certbot-0.11.0.dev0/certbot/tests/cli_test.py", line 201, in test_staging_flag
[centos@127.0.0.1] out:     namespace = self.parse(short_args)
[centos@127.0.0.1] out: AttributeError: 'ParseTest' object has no attribute 'parse'
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: ----------------------------------------------------------------------
[centos@127.0.0.1] out: Ran 580 tests in 20.726s
[centos@127.0.0.1] out: 
[centos@127.0.0.1] out: FAILED (errors=12)
```
Not yet sure of the cause of these problems or if they should be fixed for 0.10.x. We are not packaged on CentOS 6 and tests work fine using [test_tests.sh](https://github.com/certbot/certbot/blob/master/tests/letstest/scripts/test_tests.sh).

**Comment by bmw** [comment]
We define the `parse` method in `setUpClass` and its [documentation](https://docs.python.org/2/library/unittest.html#unittest.TestCase.setUpClass) says `setUpClass` is only available in Python 2.7+. Our tests pass while using `nose`, but using a CentOS 6 docker image our tests fail with the same issue when running `python setup.py test` from the root of our repo after activating the venv.

What are you doing `nose`?
