### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by drsaluml** [certbot/certbot#4076]
Please help me install Nginx on CentOS 6

```
2017-01-18 08:42:34,181:INFO:certbot.crypto_util:Generating key (1024 bits): /var/lib/letsencrypt/snakeoil/0002_key.pem
2017-01-18 08:42:34,299:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/auth_handler.py", line 112, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_nginx/configurator.py", line 815, in perform
    sni_response = chall_doer.perform()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_nginx/tls_sni_01.py", line 71, in perform
    self._mod_config(addresses)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_nginx/tls_sni_01.py", line 101, in _mod_config
    for k, _ in body:
ValueError: need more than 1 value to unpack

2017-01-18 08:42:34,299:DEBUG:certbot.error_handler:Calling registered functions
2017-01-18 08:42:34,299:INFO:certbot.auth_handler:Cleaning up challenges
2017-01-18 08:42:35,662:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/main.py", line 849, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/main.py", line 575, in run
    action, lineage = _auth_from_available(le_client, config, domains, certname)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/main.py", line 107, in _auth_from_available
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/client.py", line 291, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/client.py", line 262, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/auth_handler.py", line 74, in get_authorizations
    resp = self._solve_challenges()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/auth_handler.py", line 112, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_nginx/configurator.py", line 815, in perform
    sni_response = chall_doer.perform()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_nginx/tls_sni_01.py", line 71, in perform
    self._mod_config(addresses)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_nginx/tls_sni_01.py", line 101, in _mod_config
    for k, _ in body:
ValueError: need more than 1 value to unpack
```

**Comment by bmw** [comment]
Certbot was successfully installed on your system, however, I believe this traceback is our parser struggling to parse your main Nginx configuration file. Certbot expects this file to be at `/etc/nginx/nginx.conf`. Can you provide a copy of this file? Feel free to redact values as you feel necessary.

**Comment by ohemorange** [comment]
Related: #3857

**Comment by ohemorange** [comment]
*this is different from #3857.

**Comment by ohemorange** [comment]
Ping on more info!

**Comment by bmw** [comment]
We never got a follow up on this and a lot of parsing is/has changed and improved. If you can still repo, please follow up providing more info.
