### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by theDevilsVoice** [certbot/certbot#4098]
Hello I get segfault every time I try to execute certbot. Probably something simple I am overlooking, thanks!

```
root@thedevilsvoice:/var/log/letsencrypt# certbot certonly --manual
Segmentation fault
root@thedevilsvoice:/var/log/letsencrypt# cd
root@thedevilsvoice:~# uname -a
Linux thedevilsvoice 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64 GNU/Linux
root@thedevilsvoice:~# cat /etc/debian_version 
8.7
root@thedevilsvoice:~# certbot -h
Segmentation fault
root@thedevilsvoice:~# 




root@thedevilsvoice:~# cd  -
/var/log/letsencrypt
root@thedevilsvoice:/var/log/letsencrypt#  ls -lart
total 64
-rw-r--r--  1 root root    0 Oct 17 17:49 letsencrypt.log.12
-rw-r--r--  1 root root 1579 Oct 17 17:49 letsencrypt.log.11
-rw-r--r--  1 root root 4124 Oct 17 17:51 letsencrypt.log.10
-rw-r--r--  1 root root 4113 Oct 17 17:52 letsencrypt.log.9
-rw-r--r--  1 root root  744 Oct 17 17:52 letsencrypt.log.8
-rw-r--r--  1 root root 1645 Oct 17 17:54 letsencrypt.log.7
-rw-r--r--  1 root root 1645 Oct 17 17:56 letsencrypt.log.6
-rw-r--r--  1 root root 1596 Oct 17 17:58 letsencrypt.log.5
-rw-r--r--  1 root root 1578 Oct 17 17:59 letsencrypt.log.4
-rw-r--r--  1 root root 1572 Oct 17 18:01 letsencrypt.log.3
-rw-r--r--  1 root root 1482 Oct 17 18:02 letsencrypt.log.2
-rw-r--r--  1 root root 1482 Oct 17 18:02 letsencrypt.log.1
drwx------  2 root root 4096 Oct 17 18:05 .
-rw-r--r--  1 root root 1482 Oct 17 18:05 letsencrypt.log
drwxr-xr-x 13 root root 4096 Jan 21 07:35 ..
root@thedevilsvoice:/var/log/letsencrypt# cat *
2016-10-17 18:05:18,261:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 18:05:18,262:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 18:05:18,269:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 18:05:18,269:DEBUG:certbot.main:Arguments: ['--manual']
2016-10-17 18:05:18,270:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 18:05:18,275:DEBUG:certbot.plugins.selection:Requested authenticator manual and installer None
2016-10-17 18:05:18,280:DEBUG:certbot.plugins.selection:Single candidate plugin: * manual
Description: Manually configure an HTTP server
Interfaces: IAuthenticator, IPlugin
Entry point: manual = certbot.plugins.manual:Authenticator
Initialized: <certbot.plugins.manual.Authenticator object at 0x7fe7d7295290>
Prep: True
2016-10-17 18:05:18,281:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.manual.Authenticator object at 0x7fe7d7295290> and installer None
2016-10-17 18:05:18,464:DEBUG:certbot.main:Picked account: <Account(4170cac55318016306f54509e2268f35)>
2016-10-17 18:05:18,466:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-10-17 18:05:18,469:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-10-17 18:02:32,504:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 18:02:32,506:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 18:02:32,513:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 18:02:32,513:DEBUG:certbot.main:Arguments: ['--manual']
2016-10-17 18:02:32,514:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 18:02:32,518:DEBUG:certbot.plugins.selection:Requested authenticator manual and installer None
2016-10-17 18:02:32,524:DEBUG:certbot.plugins.selection:Single candidate plugin: * manual
Description: Manually configure an HTTP server
Interfaces: IAuthenticator, IPlugin
Entry point: manual = certbot.plugins.manual:Authenticator
Initialized: <certbot.plugins.manual.Authenticator object at 0x7f69c6a54290>
Prep: True
2016-10-17 18:02:32,525:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.manual.Authenticator object at 0x7f69c6a54290> and installer None
2016-10-17 18:02:32,714:DEBUG:certbot.main:Picked account: <Account(4170cac55318016306f54509e2268f35)>
2016-10-17 18:02:32,716:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-10-17 18:02:32,720:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-10-17 17:51:25,980:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 17:51:25,981:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 17:51:25,982:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 17:51:25,982:DEBUG:certbot.main:Arguments: ['--dry-run']
2016-10-17 17:51:25,983:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 17:51:25,998:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2016-09-23 12:08:00 UTC.
2016-10-17 17:51:25,999:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2016-10-17 17:51:26,023:DEBUG:certbot.plugins.selection:Requested authenticator manual and installer none
2016-10-17 17:51:26,023:DEBUG:certbot.plugins.selection:No candidate plugin
2016-10-17 17:51:26,027:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#manual): Running manual mode non-interactively is not supported
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 106, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/manual.py", line 106, in prepare
    raise errors.PluginError("Running manual mode non-interactively is not supported")
PluginError: Running manual mode non-interactively is not supported
2016-10-17 17:51:26,028:DEBUG:certbot.plugins.selection:No candidate plugin
2016-10-17 17:51:26,028:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
2016-10-17 17:51:26,028:INFO:certbot.main:Could not choose appropriate plugin: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Running manual mode non-interactively is not supported',)
2016-10-17 17:51:26,029:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/bitsmasher.net.conf produced an unexpected error: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Running manual mode non-interactively is not supported',). Skipping.
2016-10-17 17:51:26,030:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 348, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 554, in obtain_cert
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 197, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 272, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
PluginSelectionError: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Running manual mode non-interactively is not supported',)

2016-10-17 17:51:26,030:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 592, in renew
    renewal.renew_all_lineages(config)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 365, in renew_all_lineages
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)

2016-10-17 17:49:43,428:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 17:49:43,429:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 17:49:43,441:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 17:49:43,441:DEBUG:certbot.main:Arguments: []
2016-10-17 17:49:43,443:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 17:49:43,447:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2016-10-17 17:49:44,018:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7f11ff3b53d0>
Prep: True
2016-10-17 17:49:44,021:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7f11ff3b53d0> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7f11ff3b53d0>
2016-10-17 17:49:48,039:DEBUG:certbot.main:Picked account: <Account(4170cac55318016306f54509e2268f35)>
2016-10-17 17:49:48,042:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-10-17 17:49:48,050:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-10-17 18:02:04,723:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 18:02:04,725:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 18:02:04,732:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 18:02:04,732:DEBUG:certbot.main:Arguments: ['--manual']
2016-10-17 18:02:04,733:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 18:02:04,737:DEBUG:certbot.plugins.selection:Requested authenticator manual and installer None
2016-10-17 18:02:04,743:DEBUG:certbot.plugins.selection:Single candidate plugin: * manual
Description: Manually configure an HTTP server
Interfaces: IAuthenticator, IPlugin
Entry point: manual = certbot.plugins.manual:Authenticator
Initialized: <certbot.plugins.manual.Authenticator object at 0x7f535d90b290>
Prep: True
2016-10-17 18:02:04,744:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.manual.Authenticator object at 0x7f535d90b290> and installer None
2016-10-17 18:02:04,929:DEBUG:certbot.main:Picked account: <Account(4170cac55318016306f54509e2268f35)>
2016-10-17 18:02:04,931:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-10-17 18:02:04,935:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-10-17 18:01:17,225:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 18:01:17,226:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 18:01:17,233:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 18:01:17,234:DEBUG:certbot.main:Arguments: ['--manual', '--email', 'franklin@bitsmasher.net', '-d', 'bitsmasher.net', '-d', 'www.bitsmasher.net']
2016-10-17 18:01:17,235:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 18:01:17,239:DEBUG:certbot.plugins.selection:Requested authenticator manual and installer None
2016-10-17 18:01:17,244:DEBUG:certbot.plugins.selection:Single candidate plugin: * manual
Description: Manually configure an HTTP server
Interfaces: IAuthenticator, IPlugin
Entry point: manual = certbot.plugins.manual:Authenticator
Initialized: <certbot.plugins.manual.Authenticator object at 0x7f6b77dea690>
Prep: True
2016-10-17 18:01:17,246:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.manual.Authenticator object at 0x7f6b77dea690> and installer None
2016-10-17 18:01:17,432:DEBUG:certbot.main:Picked account: <Account(4170cac55318016306f54509e2268f35)>
2016-10-17 18:01:17,434:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-10-17 18:01:17,438:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-10-17 17:59:08,357:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 17:59:08,359:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 17:59:08,366:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 17:59:08,367:DEBUG:certbot.main:Arguments: ['--webroot', '--email', 'franklin@bitsmasher.net', '-d', 'bitsmasher.net', '-d', 'www.bitsmasher.net']
2016-10-17 17:59:08,368:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 17:59:08,373:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2016-10-17 17:59:08,380:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f5d60924690>
Prep: True
2016-10-17 17:59:08,381:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7f5d60924690> and installer None
2016-10-17 17:59:08,587:DEBUG:certbot.main:Picked account: <Account(4170cac55318016306f54509e2268f35)>
2016-10-17 17:59:08,589:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-10-17 17:59:08,594:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-10-17 17:58:35,550:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 17:58:35,552:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 17:58:35,558:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 17:58:35,559:DEBUG:certbot.main:Arguments: ['--standalone', '--email', 'franklin@bitsmasher.net', '-d', 'bitsmasher.net', '-d', 'www.bitsmasher.net']
2016-10-17 17:58:35,560:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 17:58:35,564:DEBUG:certbot.plugins.selection:Requested authenticator standalone and installer None
2016-10-17 17:58:35,761:DEBUG:certbot.plugins.selection:Single candidate plugin: * standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x7f36a4054690>
Prep: True
2016-10-17 17:58:35,763:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x7f36a4054690> and installer None
2016-10-17 17:58:35,948:DEBUG:certbot.main:Picked account: <Account(4170cac55318016306f54509e2268f35)>
2016-10-17 17:58:35,950:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-10-17 17:58:35,954:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-10-17 17:56:02,227:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 17:56:02,229:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 17:56:02,236:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 17:56:02,236:DEBUG:certbot.main:Arguments: ['--apache', '-d', 'bitsmasher.net', '-d', 'www.bitsmasher.net']
2016-10-17 17:56:02,238:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 17:56:02,243:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2016-10-17 17:56:02,722:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7fe1bd972250>
Prep: True
2016-10-17 17:56:02,724:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7fe1bd972250> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7fe1bd972250>
2016-10-17 17:56:02,896:DEBUG:certbot.main:Picked account: <Account(4170cac55318016306f54509e2268f35)>
2016-10-17 17:56:02,898:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-10-17 17:56:02,901:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-10-17 17:54:18,713:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 17:54:18,715:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 17:54:18,722:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 17:54:18,722:DEBUG:certbot.main:Arguments: ['--apache', '-d', 'bitsmasher.net', '-d', 'www.bitsmasher.net']
2016-10-17 17:54:18,723:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 17:54:18,727:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2016-10-17 17:54:19,201:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7f8835a47210>
Prep: True
2016-10-17 17:54:19,203:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7f8835a47210> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7f8835a47210>
2016-10-17 17:54:19,374:DEBUG:certbot.main:Picked account: <Account(4170cac55318016306f54509e2268f35)>
2016-10-17 17:54:19,376:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-10-17 17:54:19,379:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-10-17 17:52:49,760:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 17:52:49,761:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 17:52:49,768:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 17:52:49,768:DEBUG:certbot.main:Arguments: []
2016-10-17 17:52:49,769:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 17:52:49,774:DEBUG:certbot.main:Expected interfaces: None
2016-10-17 17:52:49,775:DEBUG:certbot.main:Filtered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#standalone)
2016-10-17 17:52:22,193:DEBUG:certbot.main:Root logging level set at 20
2016-10-17 17:52:22,194:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-10-17 17:52:22,194:DEBUG:certbot.main:certbot version: 0.9.3
2016-10-17 17:52:22,194:DEBUG:certbot.main:Arguments: []
2016-10-17 17:52:22,195:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2016-10-17 17:52:22,206:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2016-09-23 12:08:00 UTC.
2016-10-17 17:52:22,206:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2016-10-17 17:52:22,227:DEBUG:certbot.plugins.selection:Requested authenticator manual and installer none
2016-10-17 17:52:22,227:DEBUG:certbot.plugins.selection:No candidate plugin
2016-10-17 17:52:22,231:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#manual): Running manual mode non-interactively is not supported
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 106, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/manual.py", line 106, in prepare
    raise errors.PluginError("Running manual mode non-interactively is not supported")
PluginError: Running manual mode non-interactively is not supported
2016-10-17 17:52:22,232:DEBUG:certbot.plugins.selection:No candidate plugin
2016-10-17 17:52:22,232:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
2016-10-17 17:52:22,232:INFO:certbot.main:Could not choose appropriate plugin: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Running manual mode non-interactively is not supported',)
2016-10-17 17:52:22,233:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/bitsmasher.net.conf produced an unexpected error: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Running manual mode non-interactively is not supported',). Skipping.
2016-10-17 17:52:22,233:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 348, in renew_all_lineages
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 554, in obtain_cert
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 197, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 272, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
PluginSelectionError: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Running manual mode non-interactively is not supported',)

2016-10-17 17:52:22,234:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 592, in renew
    renewal.renew_all_lineages(config)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 365, in renew_all_lineages
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)

```

**Comment by jsha** [comment]
A note for other readers: There are some stack traces about "Running manual mode non-interactively is not supported," but I think those are red herrings since they wouldn't cause a segfault.

@theDevilsVoice, are you running the version from jessie-backports? Can you update it to the latest? We released a new version very recently, and I think it was the version that removed ncurses support, which I have seen cause some segfaults.

**Comment by theDevilsVoice** [comment]
Hmm, ok well I cloned the latest and it seems to work correctly as seen below. It's command line, not ncurses now it looks like. 

I can't truly test it right now without breaking my site (I was able to use a different host to do a manual renew yesterday). 


**This is on a digital ocean droplet.** 

thedevilsvoice@thedevilsvoice:/etc/apt$ more sources.list
deb http://http.debian.net/debian jessie main
deb-src http://http.debian.net/debian jessie main

deb http://security.debian.org/ jessie/updates main
deb-src http://security.debian.org/ jessie/updates main

# jessie-updates, previously known as 'volatile'
deb http://http.debian.net/debian jessie-updates main
deb-src http://http.debian.net/debian jessie-updates main
# added by frank
deb http://ftp.debian.org/debian jessie-backports main
deb http://download.virtualbox.org/virtualbox/debian jessie contrib
thedevilsvoice@thedevilsvoice:/etc/apt$ 


thedevilsvoice@thedevilsvoice:~/workspace$ apt-cache search letsencrypt
acme-tiny - letsencrypt tiny Python client
letsencrypt.sh - ACME client implemented in Bash
letsencrypt.sh-apache2 - letsencrypt.sh challenge response support for Apache2
certbot - automatically configure HTTPS using Let's Encrypt
letsencrypt - transitional dummy package
thedevilsvoice@thedevilsvoice:~/workspace$ sudo apt-get install letsencrypt

[sudo] password for thedevilsvoice: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  letsencrypt
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 4,576 B of archives.
After this operation, 30.7 kB of additional disk space will be used.
Get:1 http://ftp.debian.org/debian/ jessie-backports/main letsencrypt all 0.9.3-1~bpo8+2 [4,576 B]
Fetched 4,576 B in 0s (112 kB/s) 
Selecting previously unselected package letsencrypt.
(Reading database ... 98757 files and directories currently installed.)
Preparing to unpack .../letsencrypt_0.9.3-1~bpo8+2_all.deb ...
Unpacking letsencrypt (0.9.3-1~bpo8+2) ...
Setting up letsencrypt (0.9.3-1~bpo8+2) ...
thedevilsvoice@thedevilsvoice:~/workspace$ 
thedevilsvoice@thedevilsvoice:~/workspace$ sudo certbot -h
thedevilsvoice@thedevilsvoice:~/workspace$ sudo certbot --help
thedevilsvoice@thedevilsvoice:~/workspace$ which certbot
/usr/bin/certbot
thedevilsvoice@thedevilsvoice:~/workspace$ /usr/bin/certbot 
Segmentation fault
thedevilsvoice@thedevilsvoice:~/workspace$ 



thedevilsvoice@thedevilsvoice:~/workspace$ git clone https://github.com/certbot/certbot.git
Cloning into 'certbot'...
<<SNIP>>
thedevilsvoice@thedevilsvoice:~/workspace/certbot$ ./certbot-auto
Bootstrapping dependencies for Debian-based OSes...
<<SNIP>>
Installation succeeded.
Requesting root privileges to run certbot...
  /home/thedevilsvoice/.local/share/letsencrypt/bin/letsencrypt
sudo: unable to resolve host thedevilsvoice
Saving debug log to /var/log/letsencrypt/letsencrypt.log

Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
1: www.bitsmasher.net
-------------------------------------------------------------------------------
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel):
thedevilsvoice@thedevilsvoice:~/workspace/certbot$

**Comment by hlieberman** [comment]
FrankTheTank <notifications@github.com> writes:
> thedevilsvoice@thedevilsvoice:~/workspace$ sudo certbot -h
> thedevilsvoice@thedevilsvoice:~/workspace$ sudo certbot --help
> thedevilsvoice@thedevilsvoice:~/workspace$ which certbot
> /usr/bin/certbot
> thedevilsvoice@thedevilsvoice:~/workspace$ /usr/bin/certbot 
> Segmentation fault

Well, that certainly shouldn't happen.  I've just tested in a fresh DO
droplet myself, and I can't replicate that behavior.

I am a little bit suspicious about the way you were able to do apt-get
install letsencrypt; you shouldn't have been able to pull in backports
packages that way by default.

What architecture are you on?  Can you attach the output of `dpkg -l`
for me?  (It's going to be rather long, so please don't put it directly
into the bug.)

Sincerely,
-- 
Harlan Lieberman-Berg
~hlieberman
