### ISSUE TITLE
ImportError: cannot import name integer_types

### ISSUE THREAD

**Issue by Kajisav** [certbot/certbot#4130]
When trying to run **certbot certonly --standalone** or **certbot certonly --webroot** I get the above error _ImportError: cannot import name integer_types_. I searched around online but couldn't find anything that seemed relevant.

OS is Fedora 25 x86_64, Linux 4.8.6 kernel, python 2.7.13 and 3.5.2 installed, nginx web server.

Here is the traceback from python:

```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2575, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 18, in <module>
    from certbot import account
  File "/usr/lib/python2.7/site-packages/certbot/account.py", line 16, in <module>
    from acme import messages
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/site-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from .compat import (
ImportError: cannot import name integer_types
```

**Comment by Kajisav** [comment]
The issue was unrelated to certbot. My system had a version of python2-requests installed via pip during the build process of a uwsgi webapp running on my system. Its version was conflicting with the system's version trying to install.
