### ISSUE TITLE
Renew failure

### ISSUE THREAD

**Issue by samerafach** [certbot/certbot#4141]
Out of the sudden, I got an error after trying to renew my certificates. One certificate is failing to renew. Here's the log in `/var/log/letsencrypt/`:

```
2017-01-31 20:59:54,078:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/www.mydomain.com.conf produced an unexpected error: object of type 'NoneType' has no len(). Skipping.
2017-01-31 20:59:54,079:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 413, in handle_renewal_request
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 626, in obtain_cert
    action, _ = _auth_from_available(le_client, config, domains, certname, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 103, in _auth_from_available
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 296, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 262, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 73, in get_authorizations
    resp = self._solve_challenges()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 117, in _solve_challenges
    assert len(resp) == len(self.achalls)
TypeError: object of type 'NoneType' has no len()

```

Let me know if you require more info.

**Comment by samerafach** [comment]
Updating to 0.11.0 solved the problem.
