### ISSUE TITLE
One singe invalid config that could not be parsed should not break all the system.

### ISSUE THREAD

**Issue by danielschlegel** [certbot/certbot#4145]
https://community.letsencrypt.org/t/error-creating-certs/26800/2

**Comment by bmw** [comment]
Thanks for reporting the bug. Do you happen to have a full log of the issue? Logfiles are by default stored in `/var/log/letsencrypt`.

**Comment by danielschlegel** [comment]
Since this is running inside a docker container i lost the logs of the exact problem i posted. This is the only thing i can reproduce. But this can be related to deleting directory.

2017-02-03 09:44:24,565:DEBUG:certbot.main:Root logging level set at -40
2017-02-03 09:44:24,565:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-02-03 09:44:24,566:DEBUG:certbot.main:certbot version: 0.11.1
2017-02-03 09:44:24,566:DEBUG:certbot.main:Arguments: ['--webroot', '-w', '/tmp/letsencrypt', '-d', 'example.com', '--email', 'firmasaga@gmx.net', '--text', '--agree-tos', '-vvvvvv']
2017-02-03 09:44:24,566:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2017-02-03 09:44:24,566:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2017-02-03 09:44:24,568:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f6a5c9c6c10>
Prep: True
2017-02-03 09:44:24,568:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7f6a5c9c6c10> and installer None
2017-02-03 09:44:24,571:DEBUG:certbot.main:Picked account: <Account(fe264de9ac54aaa32de6c2f86a80e725)>
2017-02-03 09:44:24,572:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-02-03 09:44:24,575:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-02-03 09:44:24,785:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 352
2017-02-03 09:44:24,785:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 352
Boulder-Request-Id: LESpOdhYZnYDrMXcWudUSHM8RdYKbyo9TG1gPnzoYsw
Replay-Nonce: WgxlZf4PDBZA-Smg7k-eAv51TaxY_4vLTPUD7xUaMGM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 03 Feb 2017 09:44:24 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 03 Feb 2017 09:44:24 GMT
Connection: keep-alive

{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
2017-02-03 09:44:24,803:DEBUG:certbot.cert_manager:Renewal conf file /etc/letsencrypt/renewal/example.com-0001.conf is broken. Skipping.
2017-02-03 09:44:24,803:DEBUG:certbot.cert_manager:Traceback was:
Traceback (most recent call last):
  File "/router/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/cert_manager.py", line 243, in _search_lineages
    candidate_lineage = storage.RenewableCert(renewal_file, cli_config)
  File "/router/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/storage.py", line 392, in __init__
    self._check_symlinks()
  File "/router/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/storage.py", line 431, in _check_symlinks
    "expected {0} to be a symlink".format(link))
CertStorageError: expected /etc/letsencrypt/live/example.com-0001/cert.pem to be a symlink

2017-02-03 09:44:24,810:DEBUG:certbot.cert_manager:Renewal conf file /etc/letsencrypt/renewal/example.com.conf is broken. Skipping.
2017-02-03 09:44:24,810:DEBUG:certbot.cert_manager:Traceback was:
Traceback (most recent call last):
  File "/router/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/cert_manager.py", line 243, in _search_lineages
    candidate_lineage = storage.RenewableCert(renewal_file, cli_config)
  File "/router/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/storage.py", line 373, in __init__
    "file reference".format(self.configfile))
CertStorageError: renewal config file {} is missing a required file reference

**Comment by bmw** [comment]
Got it. Neither of the errors in your log above should be fatal and Certbot should continue to run, however, I was able to reproduce the fatal errors from your community forum post. I did it by changing the symlink  `/etc/letsencrypt/live/<domain>/cert.pem` to point to a random text file rather than the expected certificate.

We'll get this fixed.
