### ISSUE TITLE
Fedora 25: ImportError: cannot import name integer_types

### ISSUE THREAD

**Issue by JesusAMR** [certbot/certbot#4218]
When running for the first time the command certbot --apache i get the following Traceback error:

$ certbot --apache
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2575, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 18, in <module>
    from certbot import account
  File "/usr/lib/python2.7/site-packages/certbot/account.py", line 16, in <module>
    from acme import messages
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/site-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 26, in <module>
    from .compat import (
ImportError: cannot import name integer_types

**Comment by SwartzCr** [comment]
it'd be useful to know how you installed certbot - is it a system package, are you running it from a cloned git repo, are you using certbot-auto?

**Comment by JesusAMR** [comment]
I installed certbot through the system package with the following command.

$ sudo dnf install python-certbot-apache

**Comment by mrj** [comment]
For me, the solution was https://bugzilla.redhat.com/show_bug.cgi?id=1177479#c4

**Comment by JesusAMR** [comment]
Will try later today, thanks.

**Comment by JesusAMR** [comment]
Seems to have fixed it thanks

**Comment by SwartzCr** [comment]
looks like you closed it and then accidentally re-opened it. I'm going to close this again, but feel free to re-open and add more information!

**Comment by thilinapiy** [comment]
Above did not worked for me but 
> pip install -U requests 

did work.

**Comment by tiagoor** [comment]
"pip install -U requests" worked for me, on CentOS 7.3..
