### ISSUE TITLE
requests.packages.urllib3.contrib.pyopenssl.inject_into_urllib3(): 'module' object has no attribute 'pyopenssl'

### ISSUE THREAD

**Issue by x-yuri** [certbot/certbot#4227]
When I run `certbot` like so:

```
certbot certonly --webroot -w /path/to/docroot -d domain.com -d www.domain.com
```

I get:

```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 19, in <module>
    from certbot import client
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 10, in <module>
    from acme import client as acme_client
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 29, in <module>
    requests.packages.urllib3.contrib.pyopenssl.inject_into_urllib3()
AttributeError: 'module' object has no attribute 'pyopenssl'
```

```
$ dpkg -l | grep python- | egrep '(ssl|urllib|requests)'
ii  python-openssl                      16.0.0-1~bpo8+1               all          Python 2 wrapper around the OpenSSL library
ii  python-requests                     2.11.1-1~bpo8+1               all          elegant and simple HTTP library for Python2, built for human beings
ii  python-urllib3                      1.16-1~bpo8+1                 all          HTTP library with thread-safe connection pooling for Python
```

**Comment by x-yuri** [comment]
Upon further investigation, it turned out that the issue reveals itself with `python-2.7.8`. With `python-2.7.9` no such error appears, since [this line][1]:

```python
requests.packages.urllib3.contrib.pyopenssl.inject_into_urllib3()
```

doesn't get executed. Additionally, the issue seems to be fixed with #3990.

[1]: https://github.com/certbot/certbot/blob/30acc5cf474adcfdcc8936d2201441d5354d0e12/acme/acme/client.py#L30
