### ISSUE TITLE
UnicodeEncodeError while expanding certificate (ascii)

### ISSUE THREAD

**Issue by zabanshenas** [certbot/certbot#4273]
Whats the problem with the following code?

My domain is: zabanshenas.com, talk.zabanshenas.com

I ran this command: 
```
/usr/local/certbot/certbot-auto -t --renew-by-default --agree-tos --webroot -w /etc/letsencrypt/webroot --server https://acme-v01.api.letsencrypt.org/directory -m eng.hnaseri@gmail.com --expand -d zabanshenas.com,www.zabanshenas.com,talk.zabanshenas.com,www.talk.zabanshenas.com certonly
```

It produced this output: 
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for zabanshenas.com
http-01 challenge for www.zabanshenas.com
http-01 challenge for talk.zabanshenas.com
http-01 challenge for www.talk.zabanshenas.com
Using the webroot path /etc/letsencrypt/webroot for all unmatched domains.
Waiting for verification...
Cleaning up challenges
An unexpected error occurred:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 276-280: ordinal not in range(128)
Please see the logfiles in /var/log/letsencrypt for more details.
```
logfile:
```
2017-02-28 16:06:00,465:INFO:certbot.auth_handler:Cleaning up challenges
2017-02-28 16:06:00,465:DEBUG:certbot.plugins.webroot:Removing /etc/letsencrypt/webroot/.well-known/acme-challenge/Olybbkj6iWuPN5MrNF7tAAIGrGyh8Ddy22F0TAoQaRE
2017-02-28 16:06:00,466:DEBUG:certbot.plugins.webroot:Removing /etc/letsencrypt/webroot/.well-known/acme-challenge/5o1e3MiNU8gmtuV_Etz44dwhwQXdFbgR86cZhIHU04c
2017-02-28 16:06:00,467:DEBUG:certbot.plugins.webroot:Removing /etc/letsencrypt/webroot/.well-known/acme-challenge/8kKTJhJa6T5wYMWrEwfr7x1wO2FtcNPMaTTMA27z1uA
2017-02-28 16:06:00,467:DEBUG:certbot.plugins.webroot:All challenges cleaned up, removing /etc/letsencrypt/webroot/.well-known/acme-challenge
2017-02-28 16:06:00,469:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 882, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 659, in obtain_cert
    action, _ = _auth_from_available(le_client, config, domains, certname, lineage)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 104, in _auth_from_available
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/renewal.py", line 296, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 265, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 77, in get_authorizations
    self._respond(resp, best_effort)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 134, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 197, in _poll_challenges
    _report_failed_challs(all_failed_achalls)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 488, in _report_failed_challs
    _generate_failed_chall_msg(achalls), reporter.MEDIUM_PRIORITY)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 504, in _generate_failed_chall_msg
    if messages.is_acme_error(error):
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/acme/messages.py", line 39, in is_acme_error
    return (ERROR_PREFIX in str(err)) or (OLD_ERROR_PREFIX in str(err))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 276-280: ordinal not in range(128)
```

**Comment by SwartzCr** [comment]
huh - looks like the same problem as #4241 
any ideas @bmw?

**Comment by bmw** [comment]
@zabanshenas, can you include the full log? The error Certbot is struggling to parse should be present in the log before what you've included here.

**Comment by zabanshenas** [comment]
the full log is here : http://pastebin.com/mYK2uCdV
However I managed to solve the problem.
That was because my subdomain was for a discourse forum and since discourse is installed with docker, I needed to follow [special steps](https://meta.discourse.org/t/how-should-i-enable-letsencrypt-while-discourse-is-beside-other-websites/58107) to make my certificate be issued.
However I think the error I got from certbot wasn't informative enough and in fact it was misleading imo.

**Comment by bmw** [comment]
Thanks for the log and I'm glad you figured it out. The error you saw was due to our code failing to properly handle the non-ascii characters returned from your server.

**Comment by SwartzCr** [comment]
So, while this is a misconfiguration with docker, #4241 is a misconfiguration with a service provider. It seems that we're parsing responses without checking them. It might be nice to change the code to validate the response and if it's invalid rather than erroring out due to an ascii parse error, catching it and then giving a more useful error message to the user.
I'm going to flag this as a good volunteer task, but @bmw let me know if you disagree or think that we should make a separate issue for it.

**Comment by bmw** [comment]
The problem here isn't that the response is invalid, but that it isn't ASCII. We need to make sure we handle non-ascii characters in error messages properly to prevent masking the real error.

**Comment by SwartzCr** [comment]
Right - I think this is a pretty common problem and we should fix this if we can. Can you add it to a milestone?

**Comment by bmw** [comment]
Sure. It's in 1.0 now, but I'll add it to 0.14.0 so we can triage it for the next release.

**Comment by SwartzCr** [comment]
tagging #4516

**Comment by ericfish** [comment]
I got the same error, since my sites are in Chinese and I had to change the index page to update the cert and change it back for every site which is painful. Suggest this bug can be fixed with high priority. Thanks!

**Comment by mystdeim** [comment]
Any news?! It's a very annoying bug

**Comment by ynasser** [comment]
@mystdeim Yes, there's a PR for this in #4867.
