### ISSUE TITLE
Failed to connect to xx.xx.xx.xxx:443 for TLS-SNI-01    challenge

### ISSUE THREAD

**Issue by EmersonBR** [certbot/certbot#4285]
## My operating system is (include version):

Windows 10 using Putti to access Pi

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:

Failed to connect to xx.xx.xx.xxx:443 for TLS-SNI-01
   challenge

## Certbot's behavior differed from what I expected because:
it did not connect to my PI from DNS

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for xxxxxxxxxxxxxxxxxxxx.duckdns.org
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. emersonhass.duckdns.org (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to xx.xx.xx.xxx.xx:443 for TLS-SNI-01 challenge

IMPORTANT NOTES:
 - If you lose your account credentials, you can recover through
   e-mails sent to xxxxxxxxxxx@gmail.com.
 - The following errors were reported by the server:

   Domain: xxxxxxxxxxxx.duckdns.org
   Type:   connection
   Detail: Failed to connect to xx.xx.xx.xxx:443 for TLS-SNI-01
   challenge

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.

**Comment by bmw** [comment]
To be clear, you're running Certbot on a Raspberry Pi? Which OS? Raspbian?

Can you include a full version of the log? What you posted just looks like Certbot's stdout output.

**Comment by EmersonBR** [comment]
Pi rasbian. Thank you BMW!

**Comment by bmw** [comment]
A full version of your log which I asked for in my last message would still be useful. Make sure you've followed the following advice from the output above:

> To fix these errors, please make sure that your domain name was
entered correctly and the DNS A record(s) for that domain
contain(s) the right IP address. Additionally, please check that
your computer has a publicly routable IP address and that no
firewalls are preventing the server from communicating with the
client. If you're using the webroot plugin, you should also verify
that you are serving files from the webroot path you provided.

If you still need help, you can try this. I'm assuming you chose the standalone plugin. Run `sudo python -m SimpleHTTPServer 80` on your Raspberry Pi. Leave that command running and try to connect to your domain using your web browser. Does it work?

**Comment by EmersonBR** [comment]
I get this when I open the dns link:

Directory listing for /

.bash_history
.bash_logout
.bashrc
.duck.sh.swp
.local/
.profile
.selected_editor
duckdns/
hassbian-scripts/
letsencrypt/
python-openzwave/

and they are links that download files, I can click on them and they download some sort of log. 

Also on the Pi, it shows the following:


pi@hassbian:~ $ sudo python -m SimpleHTTPServer 80
Serving HTTP on 0.0.0.0 port 80 ...
192.168.1.1 - - [07/Mar/2017 08:06:51] "GET / HTTP/1.1" 200 -
192.168.1.1 - - [07/Mar/2017 08:06:51] code 404, message File not found
192.168.1.1 - - [07/Mar/2017 08:06:51] "GET /favicon.ico HTTP/1.1" 404 -
192.168.1.1 - - [07/Mar/2017 08:07:09] "GET /.bash_history HTTP/1.1" 200 -

^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 230, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 226, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 599, in test
    httpd.serve_forever()
  File "/usr/lib/python2.7/SocketServer.py", line 236, in serve_forever
    poll_interval)
  File "/usr/lib/python2.7/SocketServer.py", line 155, in _eintr_retry
    return func(*args)
KeyboardInterrupt
pi@hassbian:~ $ ^C

**Comment by EmersonBR** [comment]
Sorry, here is the original text:

Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for emersonhass.duckdns.org
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. emersonhass.duckdns.org (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to 73.56.155.227:443 for TLS-SNI-01 challenge

IMPORTANT NOTES:
 - If you lose your account credentials, you can recover through
   e-mails sent to etkasper@gmail.com.
 - The following errors were reported by the server:

   Domain: emersonhass.duckdns.org
   Type:   connection
   Detail: Failed to connect to 73.56.155.227:443 for TLS-SNI-01
   challenge

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.

**Comment by bmw** [comment]
You're running Certbot on your Pi correct? If you're running it locally it won't work (without significant extra work).

One thing you can try is adding `--preferred-challenges http` to the command line. If that doesn't work, I should have been more clear about the log. I meant a copy of the log stored in `/var/log/letsencrypt`. As included in the text of our issue template: "Feel free to redact domains, e-mail and IP addresses as you see fit.".

**Comment by EmersonBR** [comment]
**Where do I put the --preferred-challenges http command line? 

Also, I cannot find my yaml file any longer, where would that be located?

Do you think I should re-install everything, including home assistant and letsencrypt?** 




****Here is the log named letsencrypt.log, (btw, I also have 3 other logs named letsencrypt.log.1,letsencrypt.log.2 and letsencrypt.log.3) :**** 



2017-03-03 22:35:01,781:DEBUG:certbot.main:Root logging level set at 20
2017-03-03 22:35:01,790:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-03-03 22:35:01,796:DEBUG:certbot.main:certbot version: 0.12.0
2017-03-03 22:35:01,797:DEBUG:certbot.main:Arguments: ['--email', 'xxxxxxx@gmail.com', '-d', 'xxxxxxxxxxxxx.duckdns.org']
2017-03-03 22:35:01,802:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2017-03-03 22:35:01,808:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2017-03-03 22:35:20,565:WARNING:certbot.plugins.util:Failed to find apache2ctl in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2017-03-03 22:35:20,566:DEBUG:certbot.plugins.disco:No installation (PluginEntryPoint#apache): Cannot find Apache control command apache2ctl
Traceback (most recent call last):
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 114, in prepare
    self._initialized.prepare()
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 169, in prepare
    'Cannot find Apache control command {0}'.format(restart_cmd))
NoInstallationError: Cannot find Apache control command apache2ctl
2017-03-03 22:35:20,569:DEBUG:certbot.plugins.selection:Multiple candidate plugins: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7574d3d0>
Prep: True

* standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x7574da30>
Prep: True
2017-03-03 22:57:07,881:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x7574da30> and installer None
2017-03-03 22:57:09,270:DEBUG:certbot.main:Picked account: <Account(44982801c6ba22ccba74d86d8212348e)>
2017-03-03 22:57:09,279:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-03-03 22:57:09,318:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-03-03 22:57:09,843:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 352
2017-03-03 22:57:09,846:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 352
Boulder-Request-Id: 4-hqG8uwMFNp5cl4DVoNNF9axl5yr_rDk-7qY23Y-zU
Replay-Nonce: CGAkdbvW5laq0ioSsS-Fi3oHG_yubiBp0Bf1drMjjxw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 03 Mar 2017 22:57:09 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 03 Mar 2017 22:57:09 GMT
Connection: keep-alive

{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
2017-03-03 22:57:09,848:INFO:certbot.main:Obtaining a new certificate
2017-03-03 22:57:09,849:DEBUG:acme.client:Requesting fresh nonce
2017-03-03 22:57:09,849:DEBUG:acme.client:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz.
2017-03-03 22:57:09,949:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "HEAD /acme/new-authz HTTP/1.1" 405 0
2017-03-03 22:57:09,951:DEBUG:acme.client:Received response:
HTTP 405
Server: nginx
Content-Type: application/problem+json
Content-Length: 91
Allow: POST
Boulder-Request-Id: S7oV1FsGTUnJxKFOksqgrApf3iQ05wjVTvd65WUjlg4
Replay-Nonce: XRpKPQsz-7ylUTtyOq3cpFIamI3uUxTaoBBY8ONFxPs
Expires: Fri, 03 Mar 2017 22:57:09 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 03 Mar 2017 22:57:09 GMT
Connection: keep-alive


2017-03-03 22:57:09,952:DEBUG:acme.client:Storing nonce: XRpKPQsz-7ylUTtyOq3cpFIamI3uUxTaoBBY8ONFxPs
2017-03-03 22:57:09,953:DEBUG:acme.client:JWS payload:
{
  "identifier": {
    "type": "dns", 
    "value": "xxxxxxxxxxxxxxxx.duckdns.org"
  }, 
  "resource": "new-authz"
}
2017-03-03 22:57:09,989:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz:
{
  "header": {
    "alg": "RS256", 
    "jwk": {
      "e": "AQAB", 
      "kty": "RSA", 
      "n": "xME4xR8MRxdg43hrBHsHQuURaaVZFlRv3FHG8v_d_oPz1wVpBtQ6rADmpfjJo_R48EmAlo74jmCXX6z9DC6azyoi9QUYZgRN2fosN2p-owaSeXXEw4JYbP8duL-HK95x2y9YbDaaWKEVSCXkAZeiJ1ZOE5Hv0Ekyv7x5hcb0q4nrf_8jspYh3KcBTqtflxKwso_7QVKCaNdgrSpZlZlhJQXt8I9dRVPJXnq_iMw3xud0lvAYoZFoMCXg3JNbvdPxAA9xy9GluquS90h8nuC7Ry54TAo57nGhRH0WsKxUAQx8OgL9JZ5BO8VyYZZajrHRIHhKfdre82I-M4OSxYe6Pw"
    }
  }, 
  "protected": "eyJub25jZSI6ICJYUnBLUFFzei03eWxVVHR5T3EzY3BGSWFtSTN1VXhUYW9CQlk4T05GeFBzIn0", 
  "payload": "ewogICJpZGVudGlmaWVyIjogewogICAgInR5cGUiOiAiZG5zIiwgCiAgICAidmFsdWUiOiAiZW1lcnNvbmhhc3MuZHVja2Rucy5vcmciCiAgfSwgCiAgInJlc291cmNlIjogIm5ldy1hdXRoeiIKfQ", 
  "signature": "Z8yO8Ua70fgIZm5DYsIEW9Deh-T_BC8p2g599WH4zN226AtXk4H1hiqdGsdYuNbevjZQ0-H7GXIk-vrQ0b-KIqdU3QjXzuaYvh9aJexlK8-F01N8ARsVVF0j7pG3M6bj6ZkJUFquWA2-vGqAV8hmbKzv1o6toy0mPNncoshzSp9dIYaE1ego1GJMNgjWurp-UhG-Bul_s4vhNasoFIGPZLXQRlBZqLuOuBdMZCyQmIMslnIG_TR8BtBjjUuCjWWv54MGzHwt7gt4tvz5UtmMglqL7_u3ZdwPwjpI0dtLrAHD_s1pgdV24NwAOyxe_svY4HfoxQ9Z0aQyzyrPYxkwqg"
}
2017-03-03 22:57:10,209:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-authz HTTP/1.1" 201 1008
2017-03-03 22:57:10,212:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Content-Type: application/json
Content-Length: 1008
Boulder-Request-Id: aIfYRUzEHBcUKG93sgDSPBqJ3uft3YB2y0Lg-FDd6v8
Boulder-Requester: 10256576
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Location: https://acme-v01.api.letsencrypt.org/acme/authz/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE
Replay-Nonce: AvGhOrUPTqkqV2c9WggkHZCcumTTOoMbA5YKd9g6RlY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 03 Mar 2017 22:57:10 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 03 Mar 2017 22:57:10 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "xxxxxxxxxxxxxxxx.duckdns.org"
  },
  "status": "pending",
  "expires": "2017-03-10T22:57:10.070456302Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082294",
      "token": "JF1iqa78Z7FKUCV1KHS3T_2yp-FdriqGcmP_yQ97mP8"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082295",
      "token": "h6W220A_FJipByi3AhoedZBUWoID9r99KFYTksBaLMs"
    },
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082296",
      "token": "IK0PWhNVfmQyRWwSJaml1mZu_CRkjzFNNlPe_5TTLo4"
    }
  ],
  "combinations": [
    [
      0
    ],
    [
      1
    ],
    [
      2
    ]
  ]
}
2017-03-03 22:57:10,213:DEBUG:acme.client:Storing nonce: AvGhOrUPTqkqV2c9WggkHZCcumTTOoMbA5YKd9g6RlY
2017-03-03 22:57:10,221:INFO:certbot.auth_handler:Performing the following challenges:
2017-03-03 22:57:10,222:INFO:certbot.auth_handler:tls-sni-01 challenge for xxxxxxxxxxxxx.duckdns.org
2017-03-03 22:57:10,275:INFO:certbot.auth_handler:Waiting for verification...
2017-03-03 22:57:10,276:DEBUG:acme.client:JWS payload:
{
  "keyAuthorization": "IK0PWhNVfmQyRWwSJaml1mZu_CRkjzFNNlPe_5TTLo4.KUmRA_iUACIgjbVyta1UEoX_fspi0zvmZMMUUiSni_M", 
  "type": "tls-sni-01", 
  "resource": "challenge"
}
2017-03-03 22:57:10,309:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082296:
{
  "header": {
    "alg": "RS256", 
    "jwk": {
      "e": "AQAB", 
      "kty": "RSA", 
      "n": "xME4xR8MRxdg43hrBHsHQuURaaVZFlRv3FHG8v_d_oPz1wVpBtQ6rADmpfjJo_R48EmAlo74jmCXX6z9DC6azyoi9QUYZgRN2fosN2p-owaSeXXEw4JYbP8duL-HK95x2y9YbDaaWKEVSCXkAZeiJ1ZOE5Hv0Ekyv7x5hcb0q4nrf_8jspYh3KcBTqtflxKwso_7QVKCaNdgrSpZlZlhJQXt8I9dRVPJXnq_iMw3xud0lvAYoZFoMCXg3JNbvdPxAA9xy9GluquS90h8nuC7Ry54TAo57nGhRH0WsKxUAQx8OgL9JZ5BO8VyYZZajrHRIHhKfdre82I-M4OSxYe6Pw"
    }
  }, 
  "protected": "eyJub25jZSI6ICJBdkdoT3JVUFRxa3FWMmM5V2dna0haQ2N1bVRUT29NYkE1WUtkOWc2UmxZIn0", 
  "payload": "ewogICJrZXlBdXRob3JpemF0aW9uIjogIklLMFBXaE5WZm1ReVJXd1NKYW1sMW1adV9DUmtqekZOTmxQZV81VFRMbzQuS1VtUkFfaVVBQ0lnamJWeXRhMVVFb1hfZnNwaTB6dm1aTU1VVWlTbmlfTSIsIAogICJ0eXBlIjogInRscy1zbmktMDEiLCAKICAicmVzb3VyY2UiOiAiY2hhbGxlbmdlIgp9", 
  "signature": "PkXfR9L4-jnHH_3ZQhY7hGFf2TuucU_zk5b5hdqU1UYLtOJKukqT9Q3QSNH50gJ0TEv4B9vv-SG0I0xrQmBNCaw0XHaZmWI9CdNmGwNnYPMgYmotcfy07Zd1X7HohSP1LiHWUyM3Eqe7hljvzj_AIBmzdvQQS9YCDN8qFLGzM2fwj3xTU7vrjTNXurVx6x52EZjW7WE8yecvWCC8ElqdzkGOmqjhT1VME0eA_ghzD92SuwBZ92gGWqjAjyM-yuYmCxCAy59OyF4J6OFnTHLNlGNZ0yr9gZlrkNz0CiuyR7mCcptMfE8-oBdO0CVwiFAXJVuvTHLVt6cRIx7ZkVyqKA"
}
2017-03-03 22:57:10,468:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082296 HTTP/1.1" 202 338
2017-03-03 22:57:10,470:DEBUG:acme.client:Received response:
HTTP 202
Server: nginx
Content-Type: application/json
Content-Length: 338
Boulder-Request-Id: 6-WXQMibceYhuL0XJR1cnBUlsrXRZr-W1g5ofAv4RHY
Boulder-Requester: 10256576
Link: <https://acme-v01.api.letsencrypt.org/acme/authz/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE>;rel="up"
Location: https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082296
Replay-Nonce: XF_Aw680q0Ll01H55UtP6hG_zobKJM2IWZRZryiga-8
Expires: Fri, 03 Mar 2017 22:57:10 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 03 Mar 2017 22:57:10 GMT
Connection: keep-alive

{
  "type": "tls-sni-01",
  "status": "pending",
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082296",
  "token": "IK0PWhNVfmQyRWwSJaml1mZu_CRkjzFNNlPe_5TTLo4",
  "keyAuthorization": "IK0PWhNVfmQyRWwSJaml1mZu_CRkjzFNNlPe_5TTLo4.KUmRA_iUACIgjbVyta1UEoX_fspi0zvmZMMUUiSni_M"
}
2017-03-03 22:57:10,471:DEBUG:acme.client:Storing nonce: XF_Aw680q0Ll01H55UtP6hG_zobKJM2IWZRZryiga-8
2017-03-03 22:57:13,475:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/acme/authz/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE.
2017-03-03 22:57:13,611:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /acme/authz/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE HTTP/1.1" 200 1115
2017-03-03 22:57:13,613:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 1115
Boulder-Request-Id: JdLkyHecS_gFIY75mLGpLtmjnJJjF5MAAwF3Qty2AXI
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Replay-Nonce: uuPuDcZsuCGA7oENicMTrRVfpu3oID8pWbgyfkWDAC4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 03 Mar 2017 22:57:13 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 03 Mar 2017 22:57:13 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "xxxxxxxxxxxxxxxx.duckdns.org"
  },
  "status": "pending",
  "expires": "2017-03-10T22:57:10Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082294",
      "token": "JF1iqa78Z7FKUCV1KHS3T_2yp-FdriqGcmP_yQ97mP8"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082295",
      "token": "h6W220A_FJipByi3AhoedZBUWoID9r99KFYTksBaLMs"
    },
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082296",
      "token": "IK0PWhNVfmQyRWwSJaml1mZu_CRkjzFNNlPe_5TTLo4",
      "keyAuthorization": "IK0PWhNVfmQyRWwSJaml1mZu_CRkjzFNNlPe_5TTLo4.KUmRA_iUACIgjbVyta1UEoX_fspi0zvmZMMUUiSni_M"
    }
  ],
  "combinations": [
    [
      0
    ],
    [
      1
    ],
    [
      2
    ]
  ]
}
2017-03-03 22:57:16,619:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/acme/authz/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE.
2017-03-03 22:57:16,767:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /acme/authz/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE HTTP/1.1" 200 1539
2017-03-03 22:57:16,773:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 1539
Boulder-Request-Id: YQcAceYPGuJ02rLPQNCfXepxWMY2L23ou_Bb1QxF5Pg
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Replay-Nonce: 9GOLRlzt13wLFjwmSLwEZGUInFoZeDyTXE5QNlxGOdA
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 03 Mar 2017 22:57:16 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 03 Mar 2017 22:57:16 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "xxxxxxxxxxxxxxxx.duckdns.org"
  },
  "status": "invalid",
  "expires": "2017-03-10T22:57:10Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082294",
      "token": "JF1iqa78Z7FKUCV1KHS3T_2yp-FdriqGcmP_yQ97mP8"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082295",
      "token": "h6W220A_FJipByi3AhoedZBUWoID9r99KFYTksBaLMs"
    },
    {
      "type": "tls-sni-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:connection",
        "detail": "Failed to connect to xx.xx.xxx.xxx:443 for TLS-SNI-01 challenge",
        "status": 400
      },
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/R_ZzSnvDk9zwedraG1ZKB4S6a9fIHznsjnQDA-uVyIE/738082296",
      "token": "IK0PWhNVfmQyRWwSJaml1mZu_CRkjzFNNlPe_5TTLo4",
      "keyAuthorization": "IK0PWhNVfmQyRWwSJaml1mZu_CRkjzFNNlPe_5TTLo4.KUmRA_iUACIgjbVyta1UEoX_fspi0zvmZMMUUiSni_M",
      "validationRecord": [
        {
          "hostname": "xxxxxxxxxxxxxxxxx.duckdns.org",
          "port": "443",
          "addressesResolved": [
            "xx.xx.xxx.xxx"
          ],
          "addressUsed": "xx.xx.xxx.xxx"
        }
      ]
    }
  ],
  "combinations": [
    [
      0
    ],
    [
      1
    ],
    [
      2
    ]
  ]
}
2017-03-03 22:57:16,779:DEBUG:certbot.reporter:Reporting to user: The following errors were reported by the server:

Domain: xxxxxxxxxxxxxxxx.duckdns.org
Type:   connection
Detail: Failed to connect to xx.xx.xxx.xxx:443 for TLS-SNI-01 challenge

To fix these errors, please make sure that your domain name was entered correctly and the DNS A record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2017-03-03 22:57:16,782:INFO:certbot.auth_handler:Cleaning up challenges
2017-03-03 22:57:16,784:DEBUG:certbot.plugins.standalone:Stopping server at 0.0.0.0:443...
2017-03-03 22:57:17,238:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/home/pi/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 896, in main
    return config.func(config, plugins)
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 692, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 92, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 294, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 265, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 77, in get_authorizations
    self._respond(resp, best_effort)
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 134, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 198, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
FailedChallenges: Failed authorization procedure. xxxxxxxxxxxxxxxx.duckdns.org (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to xx.xx.xxx.xxx:443 for TLS-SNI-01 challenge

**Comment by bmw** [comment]
> Where do I put the --preferred-challenges http command line?

You can place it anywhere after `certbot-auto`.

**Comment by bmw** [comment]
If you're still having issues here, I strongly recommend you create a post on https://community.letsencrypt.org. There is a large community of people there familiar with the project that should be able to help you get Certbot working on your setup.
