### ISSUE TITLE
IOError during config_changes

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4289]
This bug isn't `certbot-auto` specific. Reversion still works properly before/after this, but this looks like a bug with the reverter and should be investigated.

## My operating system is (include version):

CentOS 6

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

#### Setup
```
$ sudo docker run --rm -p 80:80 -p 443:443 -it centos:centos6 bash
# yum install httpd -y
# curl https://dl.eff.org/certbot-auto > certbot-auto
# chmod +x certbot-auto
# ./certbot-auto -n --staging --agree-tos --register-unsafely-without-email -d example.org --redirect --apache
```
#### Problem
```
# ./certbot-auto config_changes                                                                             
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
IOError: [Errno 2] No such file or directory: '/var/lib/letsencrypt/backups/1488504145.43/FILEPATHS'
Please see the logfiles in /var/log/letsencrypt for more details.
```

## Certbot's behavior differed from what I expected because:

Certbot blew up.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2017-03-03 01:22:37,183:DEBUG:certbot.main:Root logging level set at 20
2017-03-03 01:22:37,183:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-03-03 01:22:37,184:DEBUG:certbot.main:certbot version: 0.12.0
2017-03-03 01:22:37,184:DEBUG:certbot.main:Arguments: []
2017-03-03 01:22:37,184:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2017-03-03 01:22:37,186:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/main.py", line 896, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/main.py", line 534, in config_changes
    client.view_config_changes(config, num=config.num)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/client.py", line 587, in view_config_changes
    rev.view_config_changes(num)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/reverter.py", line 167, in view_config_changes
    with open(os.path.join(cur_dir, "FILEPATHS")) as paths_fd:
IOError: [Errno 2] No such file or directory: '/var/lib/letsencrypt/backups/1488504145.43/FILEPATHS'
```

**Comment by bmw** [comment]
This seems to have been fixed.
