### ISSUE TITLE
Can not start certbot 0.12 - former versions worked 

### ISSUE THREAD

**Issue by weberhofer** [certbot/certbot#4299]
The system does not provide "requests[security]>=2.10". Interesting is, that the tests run nicely on the same systems.

## My operating system is (include version):
openSUSE Leap 42.1

## I installed Certbot with OS package manager:
python-acme-0.12.0-6.1.noarch
python-certbot-0.12.0-7.1.noarch
python-certbot-apache-0.12.0-7.1.noarch
certbot-0.12.0-7.1.noarch

## I ran this command and it produced this output:
> certbot
Traceback (most recent call last):
  File "/usr/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests[security]>=2.10' distribution was not found and is required by acme

## Certbot's behavior differed from what I expected because:
certbot should work

**Comment by bmw** [comment]
This looks like a problem with the OS packages. As you're probably aware, Python is erroring out saying Certbot's dependencies are not correctly installed. I'm not very familiar with openSUSE. Is there a bug tracker for the packages where you can report this?

**Comment by weberhofer** [comment]
I'm one of the packagers for openSUSE. Meanwhile I have investigated the issue a bit more: The problem is/was, that certbot raised it's dependency on python-requests >= 2.10 which is not provided by the OS.
Now we changed dependencies in the spec file and we provided a update to the library. I also found #4248 which says we can use older versions resulting in less accurate error-messages in some cases. We'll decide how to handle this issue in the future.

**Comment by neofutur** [comment]
FYI : same problem on gentoo : 
 certbot --apache
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3080, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3066, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3093, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests[security]>=2.10' distribution was not found and is required by acme

i m not the gentoo packager, could you please provide a workaround ?

**Comment by bmw** [comment]
> i m NOT the gentoo packager, and not very python-savvy could you please provide a workaround ? shouldn t this package trigger the istall of the needed python depedency upo install ?

It looks like you're using the `git` version of our packages which I don't recommend. With that said, you can work around the problem by updating `dev-python/requests` to a version >= 2.10.

**Comment by neofutur** [comment]
thaks, that worked, working again after installing dev-python/requests-2.11.1::gentoo

still seeing a few worrying errors like : 
/usr/lib/python2.7/site-packages/OpenSSL/rand.py:43: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  result_code = _lib.RAND_bytes(result_buffer, num_bytes)

just tell if this is worth opening one more bug report .

**Comment by bmw** [comment]
This warning should go away by upgrading `dev-python/pyopenssl` to a newer version (see pyca/pyopenssl#568).
