### ISSUE TITLE
Upgrading certbot-auto 0.11.1 to 0.12.0.

### ISSUE THREAD

**Issue by skynet** [certbot/certbot#4311]
```
Upgrading certbot-auto 0.11.1 to 0.12.0...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/certbot/main.py", line 11, in <module>
    import zope.component
  File "/root/.local/share/letsencrypt/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 16, in <module>
    from zope.interface import Interface
ImportError: No module named interface
```

**Comment by SwartzCr** [comment]
Hey @skynet what OS are you running Certbot on?
Have you managed to fix this issue or is it still a problem?

**Comment by skynet** [comment]
Fixed it:
```
/usr/bin/easy_install virtualenv
```
