### ISSUE TITLE
ssl.CertificateError: hostname 'new.domain.com' doesn't match either of ...

### ISSUE THREAD

**Issue by LorenzoPetite** [certbot/certbot#4321]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Virtualmin

## I ran this command and it produced this output:
In virtualmin, I have requested a certificate for the following domains: 'child.steezonairehoodies.com', 'steezonairehoodies.com', 'test.steezonairehoodies.com', 'www.steezonairehoodies.com'

This works fine but when I added the 'hotelplan-tignes.steezonairehoodies.com' to the list and then clicked request certificate I received this output:
'
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying www.steezonairehoodies.com...
www.steezonairehoodies.com verified!
Verifying test.steezonairehoodies.com...
test.steezonairehoodies.com verified!
Verifying child.steezonairehoodies.com...
child.steezonairehoodies.com verified!
Verifying hotelplan-tignes.steezonairehoodies.com...
Traceback (most recent call last):
  File "/usr/share/webmin/webmin/acme_tiny.py", line 202, in <module>
    main(sys.argv[1:])
  File "/usr/share/webmin/webmin/acme_tiny.py", line 198, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/usr/share/webmin/webmin/acme_tiny.py", line 122, in get_crt
    resp = urlopen(wellknown_url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 838, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 272, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'hotelplan-tignes.steezonairehoodies.com' doesn't match either of 'child.steezonairehoodies.com', 'steezonairehoodies.com', 'test.steezonairehoodies.com', 'www.steezonairehoodies.com'
'

## Certbot's behavior differed from what I expected because:
It should just add 'hotelplan-tignes.steezonairehoodies.com' to a new certificate.

**Comment by bmw** [comment]
The output and error you show here isn't from Certbot. In fact, it looks like it's from [acme-tiny](https://github.com/diafygi/acme-tiny) which is another client for obtaining Certificates from Let's Encrypt. I recommend you open an issue on their repo as this is for EFF's Certbot client.
