### ISSUE TITLE
Rollback may not work if an IInstaller's server's config is broken

### ISSUE THREAD

**Issue by pde** [certbot/certbot#4403]
Here's a funny bug. The circumstances that caused it were weird (I installed a cert using `--config-dir /tmp/zzy`, and then that directory was deleted by the OS), but it seems that rollbacks should in principle be possible even if a config is broken?

```
certbot rollback --checkpoints 1 -v
Root logging level set at 10
Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot version: 0.13.0.dev0
Arguments: ['--checkpoints', '1', '-v']
Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
Attempting to acquire lock file /tmp/.certbot.lock
Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/001-demo.reworld.org-le-ssl.conf:
SSLCertificateFile: file '/tmp/zzy/live/demo.reworld.org/fullchain.pem' does not exist or is empty

Misconfigured PluginEntryPoint#apache: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/001-demo.reworld.org-le-ssl.conf:
SSLCertificateFile: file '/tmp/zzy/live/demo.reworld.org/fullchain.pem' does not exist or is empty
Traceback (most recent call last):
  File "/home/ubuntu/letsencrypt/certbot/plugins/disco.py", line 114, in prepare
    self._initialized.prepare()
  File "/home/ubuntu/letsencrypt/certbot-apache/certbot_apache/configurator.py", line 172, in prepare
    self.config_test()
  File "/home/ubuntu/letsencrypt/certbot-apache/certbot_apache/configurator.py", line 1699, in config_test
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/001-demo.reworld.org-le-ssl.conf:
SSLCertificateFile: file '/tmp/zzy/live/demo.reworld.org/fullchain.pem' does not exist or is empty

Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7ff559c37b10>
Prep: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 31 of /etc/apache2/sites-enabled/001-demo.reworld.org-le-ssl.conf:
SSLCertificateFile: file '/tmp/zzy/live/demo.reworld.org/fullchain.pem' does not exist or is empty
```

**Comment by pde** [comment]
I bet this also applies to nginx...
