### ISSUE TITLE
Cannot run certbot with Python 2.7.13

### ISSUE THREAD

**Issue by TangelSaki** [certbot/certbot#4413]
**Debian 8.7 x64
Python 2.7.13
pip 9.0.1 from /usr/python2.7/lib/python2.7/site-packages (python 2.7)
Latest certbot**

I tried to run command as root ` certbot-auto renew ` : 
```
augeas-lenses is already the newest version.
libaugeas0 is already the newest version.
ca-certificates is already the newest version.
gcc is already the newest version.
libffi-dev is already the newest version.
python is already the newest version.
python-dev is already the newest version.
python-virtualenv is already the newest version.
virtualenv is already the newest version.
libssl-dev is already the newest version.
openssl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Creating virtual environment...
Installing Python packages...
Traceback (most recent call last):
  File "/tmp/tmp.ZHMId8dK0n/pipstrap.py", line 146, in <module>
    exit(main())
  File "/tmp/tmp.ZHMId8dK0n/pipstrap.py", line 133, in main
    shell=True)
  File "/usr/python2.7/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'pip install --no-index --no-deps -U /tmp/pipstrap-ejsy6j/pip-8.0.3.tar.gz /tmp/pipstrap-ejsy6j/setuptools-20.2.2.tar.gz /tmp/pipstrap-ejsy6j/wheel-0.29.0.tar.gz' returned non-zero exit status 1
```
Thanks.

**Comment by SwartzCr** [comment]
Weird - it might be nice to know what error it threw, is there anything in the logs it generated?
Also have you tried getting the version of certbot that's packaged for debian 8? You can find instructions on how to download it here: https://certbot.eff.org/#debianjessie-other

**Comment by TangelSaki** [comment]
no log in `/var/log/letsencrypt`.

In addition,I follow the instructions to install certbot: 
`$ sudo apt-get install certbot -t jessie-backports`
then,I tired to run `certbot certonly`: 
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/python2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'certbot==0.9.3' distribution was not found and is required by the application
```

I install Python2.7 have an issue before I use certbot: 
```
Setting up python-pkg-resources (0.6.24-1) ...
/var/lib/dpkg/info/python-pkg-resources.postinst: 6: /var/lib/dpkg/info/python-pkg-resources.postinst: pycompile: not found
dpkg: error processing python-pkg-resources (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 python-pkg-resources
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

so I deleted `pycompile` file: 
`rm /usr/bin/pycompile`

then run the following commands: 
 `apt-get -f remove python-pkg-resources`
 `apt-get -f install python-pkg-resources`
it's install `python-pkg-resources` successfully.

Will it be the problem?

Thanks.

**Comment by SwartzCr** [comment]
I think you should be fine, it's likely that certbot-auto installed some system level packages, and now the packaged version of certbot is confused by the dependencies that certbot auto compiled?
Either way, there should be a new version packaged for Debian. I'm going to close this issue, assuming that you've gotten it to work, but feel free to re-open it if you're still running into issues.
