### ISSUE TITLE
certbot --apache not working on 16.04.02

### ISSUE THREAD

**Issue by Lizzardd** [certbot/certbot#4450]
## My operating system is (include version):
Ubuntu 16.04.2 LTS \n \l

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get install python-certbot-apache

## I ran this command and it produced this output:
 certbot --apache

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2017-03-31 09:03:04,285:DEBUG:certbot.main:Root logging level set at 20
2017-03-31 09:03:04,286:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-03-31 09:03:04,286:DEBUG:certbot.main:certbot version: 0.11.1
2017-03-31 09:03:04,286:DEBUG:certbot.main:Arguments: ['--apache']
2017-03-31 09:03:04,287:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2017-03-31 09:03:04,287:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-03-31 09:03:04,584:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7fa8ba5b49d0>
Prep: True
2017-03-31 09:03:04,585:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7fa8ba5b49d0> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7fa8ba5b49d0>
2017-03-31 09:03:10,486:DEBUG:certbot.main:Picked account: <Account(3a7d865c0747c97c61443eefb872f75d)>
2017-03-31 09:03:10,487:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-03-31 09:03:10,489:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-03-31 09:03:10,890:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 352
2017-03-31 09:03:10,891:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 352
Boulder-Request-Id: HJo0rLJySSr6hRggeBD1FdAOkrQt1M6M01whvr11-tY
Replay-Nonce: 5ByKyFMcg89Lag5EpL2lvaAla6g4bBa9NbBS7CuWaLk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 31 Mar 2017 09:03:10 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 31 Mar 2017 09:03:10 GMT
Connection: keep-alive

{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
2017-03-31 09:03:10,891:INFO:certbot.main:Obtaining a new certificate
2017-03-31 09:03:10,892:DEBUG:root:Requesting fresh nonce
2017-03-31 09:03:10,892:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz.
2017-03-31 09:03:11,099:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2017-03-31 09:03:11,100:DEBUG:acme.client:Received response:
HTTP 405
Server: nginx
Content-Type: application/problem+json
Content-Length: 91
Allow: POST
Boulder-Request-Id: P2lQ59ybhDFV93B2-y4HWv0BHjd1A8qBefMiF2VQb2k
Replay-Nonce: z7NVkgt2PkkQbNPYO9f7EdEOtCu6Ygf3C5kTSuvsje8
Expires: Fri, 31 Mar 2017 09:03:11 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 31 Mar 2017 09:03:11 GMT
Connection: keep-alive

2017-03-31 09:03:11,100:DEBUG:acme.client:Storing nonce: z7NVkgt2PkkQbNPYO9f7EdEOtCu6Ygf3C5kTSuvsje8
2017-03-31 09:03:11,100:DEBUG:acme.client:JWS payload:
{
  "identifier": {
    "type": "dns", 
    "value": "DOMAIN"
  }, 
  "resource": "new-authz"
}
2017-03-31 09:03:11,102:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz:
{
  "header": {
    "alg": "RS256", 
    "jwk": {
      "e": "AQAB", 
      "kty": "RSA", 
      "n": "w1KBjbs0wvXiLBvzqi1x53RWcWpJf9wSE5q8a_ak4n1PmnNzA3Cwy4HvQoozf34Po_ZECSJqF8VhoeCJT4BRee6KrJQfcDv7NbbgDgTzmV8TgX3gymDN-T0M16CP5603pVsuZZrHlWRM18iBfRAJgnfbwAVWhSJPd_cCCdQ3FqfNBaf32W5t1u84qCm3fCDG-J0TCM16j7yZNclvGCV11fZ_5oeJV-bAuYRbROwBN-jQb7Kmm0jndj4wOjhgtrg1l2eZ1E2O6eVsBHFanE3JU5jwYC1wEd7l_zZ112Vm6K9QjiEy3VG-xtO2cb4DX9NwLcaSznaNg5Qtnb3bRnn07w"
    }
  }, 
  "protected": "eyJub25jZSI6ICJ6N05Wa2d0MlBra1FiTlBZTzlmN0VkRU90Q3U2WWdmM0M1a1RTdXZzamU4In0", 
  "payload": "ewogICJpZGVudGlmaWVyIjogewogICAgInR5cGUiOiAiZG5zIiwgCiAgICAidmFsdWUiOiAicGxleC1kZXYuYW1pdGkuY2xvdWQiCiAgfSwgCiAgInJlc291cmNlIjogIm5ldy1hdXRoeiIKfQ", 
  "signature": "F3VXMHDV8s9LoZBIL9OYWG-SUqhwpL_rKiVajAEGGtOiWRK3ipbTbPvPhWXFA66wlOc5FXLN4uEpxngtDBh7hylzgGyYCYrRNbs0fTtf01oT7wSN6ps_tGCCZs1Pz2f9DYiGp5fD0Q8uNK49AyGVgJ4VhrF-DOFnp7dEzWWOK_lF61u50BqOPk0cE7h-rIGH1uGBItA4U-CktVTV7OsnXr2vmcG1k2RnuZE7Sr_H7B1VY_Sgt2lx7iN_FD3x0-yAh_VW7xdQBmmnKtwO26iPyChfnNhsVR6ZPa-4YfC2cCI17XBrGIl77GQgF8UUQ0OqOWLYDEPN-gfq1qiKA5VTzA"
}
2017-03-31 09:03:11,320:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 201 1005
2017-03-31 09:03:11,321:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Content-Type: application/json
Content-Length: 1005
Boulder-Request-Id: Ly0HFndMUfesiUXFzuN3IKfYTh7gqRgfkhNfwYYTTxo
Boulder-Requester: 11652250
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Location: https://acme-v01.api.letsencrypt.org/acme/authz/bVf-7GzFMBGBlttAR8wWB7_pCr2Srtx-fQcA7Yn4CGE
Replay-Nonce: 3mWCCmsj8iYsmbsi31MOe6bhDZj2k3pm-8BwJq_mYv8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 31 Mar 2017 09:03:11 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 31 Mar 2017 09:03:11 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "DOMAIN"
  },
  "status": "pending",
  "expires": "2017-04-07T09:03:11.193005722Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/bVf-7GzFMBGBlttAR8wWB7_pCr2Srtx-fQcA7Yn4CGE/921869484",
      "token": "2Gr9uA__O2M3Sbl9TGRM0gvHpNWwBTjIqIZAR4gSndg"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/bVf-7GzFMBGBlttAR8wWB7_pCr2Srtx-fQcA7Yn4CGE/921869485",
      "token": "hM1omve1nF1AwnJkld82uXklKyDuIYzxQ_B4_74458s"
    },
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/bVf-7GzFMBGBlttAR8wWB7_pCr2Srtx-fQcA7Yn4CGE/921869486",
      "token": "6Y3b6m0IsQsLySpQvtusI0o_JjX8DOhFyL6Ita_KmpM"
    }
  ],
  "combinations": [
    [
      2
    ],
    [
      1
    ],
    [
      0
    ]
  ]
}
2017-03-31 09:03:11,321:DEBUG:acme.client:Storing nonce: 3mWCCmsj8iYsmbsi31MOe6bhDZj2k3pm-8BwJq_mYv8
2017-03-31 09:03:11,322:INFO:certbot.auth_handler:Performing the following challenges:
2017-03-31 09:03:11,322:INFO:certbot.auth_handler:tls-sni-01 challenge for DOMAIN
2017-03-31 09:03:11,571:DEBUG:certbot_apache.tls_sni_01:Adding Include /etc/apache2/le_tls_sni_01_cert_challenge.conf to /files/etc/apache2/apache2.conf
2017-03-31 09:03:11,572:DEBUG:certbot_apache.tls_sni_01:writing a config file with text:
 <IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName 0cb9fad4a62b336216e3802cde9228e6.1551d2d3019ce605dc616b137e7b119a.acme.invalid
    UseCanonicalName on
    SSLStrictSNIVHostCheck on

    LimitRequestBody 1048576

    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /var/lib/letsencrypt/6Y3b6m0IsQsLySpQvtusI0o_JjX8DOhFyL6Ita_KmpM.crt
    SSLCertificateKeyFile /var/lib/letsencrypt/6Y3b6m0IsQsLySpQvtusI0o_JjX8DOhFyL6Ita_KmpM.pem

    DocumentRoot /var/lib/letsencrypt/tls_sni_01_page/
</VirtualHost>

</IfModule>

2017-03-31 09:03:11,587:DEBUG:certbot.reverter:Creating backup of /etc/apache2/apache2.conf
2017-03-31 09:03:11,704:ERROR:certbot.util:Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist

2017-03-31 09:03:11,705:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 111, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1748, in perform
    self.restart()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1658, in restart
    self._reload()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1669, in _reload
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

AH00112: Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist

2017-03-31 09:03:11,705:DEBUG:certbot.error_handler:Calling registered functions
2017-03-31 09:03:11,705:INFO:certbot.auth_handler:Cleaning up challenges
2017-03-31 09:03:11,813:ERROR:certbot.util:Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

2017-03-31 09:03:11,813:ERROR:certbot.error_handler:Encountered exception during recovery
2017-03-31 09:03:11,814:ERROR:certbot.error_handler:Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/error_handler.py", line 99, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 280, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1769, in cleanup
    self.restart()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1658, in restart
    self._reload()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1669, in _reload
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

2017-03-31 09:03:11,815:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.11.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 882, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 608, in run
    action, lineage = _auth_from_available(le_client, config, domains, certname)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 108, in _auth_from_available
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 294, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 265, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 73, in get_authorizations
    resp = self._solve_challenges()
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 111, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1748, in perform
    self.restart()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1658, in restart
    self._reload()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 1669, in _reload
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

**Comment by joohoi** [comment]
Looks like Apache is failing to restart for some reason, could you paste the relevant lines from
```/var/log/apache2/error.log``` to aid with debugging?

**Comment by ronaldborla** [comment]
Is there any update to this? I'm having the same issue

**Comment by joohoi** [comment]
@ronaldborla would you be able to provide more information (my previous question about error.log contents)?

**Comment by ronaldborla** [comment]
@joohoi I remember I've already resolved my problem. It may have not been completely related to this issue. It turns out, the domain was not correctly configured

**Comment by joohoi** [comment]
Ok, I'm going to close this issue for now. If you or someone else experiences the same problem in the future, feel free to comment here, and we'll reopen it.
