### ISSUE TITLE
./certbot-auto certonly --standalone fails

### ISSUE THREAD

**Issue by alexzaitsev** [certbot/certbot#4460]
## My operating system is (include version):

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

## I ran this command and it produced this output:

```
second@softcraft:/opt/certbot$ ./certbot-auto certonly --standalone
Bootstrapping dependencies for Debian-based OSes...
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://nyc2.mirrors.digitalocean.com/ubuntu xenial InRelease                
Hit:3 http://nyc2.mirrors.digitalocean.com/ubuntu xenial-updates InRelease
Hit:4 http://nyc2.mirrors.digitalocean.com/ubuntu xenial-backports InRelease
Hit:5 https://deb.nodesource.com/node_6.x xenial InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
augeas-lenses is already the newest version (1.4.0-0ubuntu1).
ca-certificates is already the newest version (20160104ubuntu1).
gcc is already the newest version (4:5.3.1-1ubuntu1).
libaugeas0 is already the newest version (1.4.0-0ubuntu1).
libffi-dev is already the newest version (3.2.1-4).
python is already the newest version (2.7.11-1).
python-dev is already the newest version (2.7.11-1).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.6).
openssl is already the newest version (1.0.2g-1ubuntu4.6).
python-virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/second/.local/...ncrypt/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
q
```

## Certbot's behavior differed from what I expected because:

it's failed

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
second@softcraft:/opt/certbot$ cd /var/log/letsencrypt
-bash: cd: /var/log/letsencrypt: No such file or directory
second@softcraft:/opt/certbot$ cd /var/log/certbot
-bash: cd: /var/log/certbot: No such file or directory
```

**Comment by alexzaitsev** [comment]
solved https://github.com/certbot/certbot/issues/2883
