### ISSUE TITLE
Unable to process multiple domains

### ISSUE THREAD

**Issue by jhabdas** [certbot/certbot#4471]
## My operating system is:
macOS Sierra Version 10.12.3 (16D32)

## I installed Certbot with:
`certbot-auto`

## I ran this command and it produced this output:
`./certbot-auto --no-self-upgrade --debug certonly --manual`

## Certbot's behavior differed from what I expected because:

It blew up twice in a row upon second domain verification while attempting to request certs for multiple domains separated by comma.

## Here is a Certbot log showing the issue:

```
2017-04-06 09:03:41,789:DEBUG:certbot.main:Root logging level set at 20
2017-04-06 09:03:41,791:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-04-06 09:03:41,804:DEBUG:certbot.main:certbot version: 0.9.3
2017-04-06 09:03:41,804:DEBUG:certbot.main:Arguments: ['--no-self-upgrade', '--debug', '--manual']
2017-04-06 09:03:41,805:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#nginx,PluginEntryPoint#standalone,PluginEntryPoint#manual,PluginEntryPoint#webroot,PluginEntryPoint#apache,PluginEntryPoint#null)
2017-04-06 09:03:41,813:DEBUG:certbot.plugins.selection:Requested authenticator manual and installer None
2017-04-06 09:03:41,817:DEBUG:certbot.plugins.selection:Single candidate plugin: * manual
Description: Manually configure an HTTP server
Interfaces: IAuthenticator, IPlugin
Entry point: manual = certbot.plugins.manual:Authenticator
Initialized: <certbot.plugins.manual.Authenticator object at 0x10a2b2b10>
Prep: True
2017-04-06 09:03:41,818:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.manual.Authenticator object at 0x10a2b2b10> and installer None
2017-04-06 09:03:41,946:DEBUG:certbot.main:Picked account: <Account(7f1fd8db3ebd76a7b13eb53616b9c977)>
2017-04-06 09:03:41,970:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2017-04-06 09:03:42,091:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-04-06 09:03:43,573:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 352
2017-04-06 09:03:43,574:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '352', 'Expires': 'Thu, 06 Apr 2017 09:03:43 GMT', 'Boulder-Request-Id': 'Lh3qaLFXaZ7KUhHBmajzxHbkaOYix5Y0T-rZah-RzqY', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 06 Apr 2017 09:03:43 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'EFI4sLpA5SYxcQ43eBziEbbU4f-P2XFIaTkRYxZIer4'}. Content: '{\n  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2017-04-06 09:03:43,575:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '352', 'Expires': 'Thu, 06 Apr 2017 09:03:43 GMT', 'Boulder-Request-Id': 'Lh3qaLFXaZ7KUhHBmajzxHbkaOYix5Y0T-rZah-RzqY', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 06 Apr 2017 09:03:43 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'EFI4sLpA5SYxcQ43eBziEbbU4f-P2XFIaTkRYxZIer4'}): '{\n  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2017-04-06 09:03:43,575:DEBUG:certbot.display.ops:No installer, picking names manually
2017-04-06 09:03:55,554:INFO:certbot.main:Renewing an existing certificate
2017-04-06 09:03:55,565:DEBUG:root:Requesting fresh nonce
2017-04-06 09:03:55,566:DEBUG:root:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {}
2017-04-06 09:03:56,170:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2017-04-06 09:03:56,171:DEBUG:root:Received <Response [405]>. Headers: {'Content-Length': '91', 'Pragma': 'no-cache', 'Boulder-Request-Id': 'Ej_Ck5IuBA7yxiuaSRT_RsGXRQiIKZKiM14z3XuAdTY', 'Expires': 'Thu, 06 Apr 2017 09:03:55 GMT', 'Server': 'nginx', 'Connection': 'keep-alive', 'Allow': 'POST', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 06 Apr 2017 09:03:55 GMT', 'Content-Type': 'application/problem+json', 'Replay-Nonce': '8w2VYqTmDTvof8qDQkRUtUnPOUX_Cabwi_or7FfqwAI'}. Content: ''
2017-04-06 09:03:56,171:DEBUG:acme.client:Storing nonce: '\xf3\r\x95b\xa4\xe6\r;\xe8\x7f\xca\x83BDT\xb5I\xcf9E\xff\t\xa6\xf0\x8b\xfa+\xecW\xea\xc0\x02'
2017-04-06 09:03:56,172:DEBUG:acme.jose.json_util:Omitted empty fields: combinations=None, expires=None, status=None, challenges=None
2017-04-06 09:03:56,172:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "website1.com"}, "resource": "new-authz"}
2017-04-06 09:03:56,173:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, alg=None, x5t=None, x5u=None, jwk=None, cty=None, kid=None, x5tS256=None
2017-04-06 09:03:56,174:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, x5t=None, x5u=None, x5tS256=None, cty=None, kid=None, nonce=None
2017-04-06 09:03:56,174:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "zjyq6w9UUP7bznIl5GxI8xJIUiCp8adSej7bV76ek1m83BOIXtSLhBRVeOx3FycqAPn--I0-3FGS6Rsrfcq84g4l03qX-JNKvh9_rHkLSojOSQsF5yUgESTS2GQEbtvFen4m0Y5U5FthsHiXRljVzeyMPjRNh3p9qUy0iIXxH20REivMBlGoXPD1tM5CHpc-EkEo5oaL8eyF0gzVjV2UTPfdORc1i5-Eyknv0yz7-LOAnvydsdTyO3CdouL4HpoMNUTHvbQeLdNQdIU5cMwbxKzeleW6rA025jqUwsFBRut2hcRffKSzdJZynMzapiWjHZlzFCDwQRdv0iY3EsYlMw"}}, "protected": "eyJub25jZSI6ICI4dzJWWXFUbURUdm9mOHFEUWtSVXRVblBPVVhfQ2Fid2lfb3I3RmZxd0FJIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJjb21mdXNpb25sbGMuY29tIn0sICJyZXNvdXJjZSI6ICJuZXctYXV0aHoifQ", "signature": "PnFKHMdr8mB4YyflhH6gmfDQQcX_EY2wboaR19SvvR3qvl4WYm_gaOZs8GwNH9uGMDmR5JAPiHOLfj9Rp39lchKnApkmOvV5HAaW25jM71Y517DxfdTVPY99z412F4CdOMdhZpgKEexeLTsjN3ARGOaKnWLLLJomqfqpcJFsexLdjU4AFBSZbvouwY6JBe8qnGJC5OpvJeuXpiOWWxvMOH2VfVtskcN6pRVvV-lDU-sNPkog61DzX_utSWZ0UAuBmA6XjhKABPaWlN8Fkazf5UWamqwmOr8lI9YhOH4ll5oiXdr9rP5JdKZZqMy2sN6GqniqDD88BBN79ZjnwUejsw"}'}
2017-04-06 09:03:57,965:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 201 1001
2017-04-06 09:03:57,966:DEBUG:root:Received <Response [201]>. Headers: {'Content-Length': '1001', 'Expires': 'Thu, 06 Apr 2017 09:03:57 GMT', 'Boulder-Request-Id': '8YJAQxwOauQTOpFRMao9NBYy_v_OkOeC-u_Yp9Q7YsQ', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/_KvPlR7E9iA2bj3vh1LHZck7WKeYeMYopI7J1oLH0D8', 'Pragma': 'no-cache', 'Boulder-Requester': '8056955', 'Date': 'Thu, 06 Apr 2017 09:03:57 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'yY35Z-lHLFJ5oTMs40wkeyG4oynAJ2VlSqHF9_pXNGE'}. Content: '{\n  "identifier": {\n    "type": "dns",\n    "value": "website1.com"\n  },\n  "status": "pending",\n  "expires": "2017-04-13T09:03:57.313937797Z",\n  "challenges": [\n    {\n      "type": "http-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/_KvPlR7E9iA2bj3vh1LHZck7WKeYeMYopI7J1oLH0D8/973849842",\n      "token": "f5LF-2oiyzK-hf7AWWgg5C-5zeZPWMAgKXlTkYHJ-ME"\n    },\n    {\n      "type": "tls-sni-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/_KvPlR7E9iA2bj3vh1LHZck7WKeYeMYopI7J1oLH0D8/973849843",\n      "token": "YlxI0DMTqgaCV_fI2Queie9Ib9qqIY8l3lGlDxidCFU"\n    },\n    {\n      "type": "dns-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/_KvPlR7E9iA2bj3vh1LHZck7WKeYeMYopI7J1oLH0D8/973849844",\n      "token": "QDDJXuESWjTZ7oO7PXnMntMyWD5WSNvUeyaHg_t5vr0"\n    }\n  ],\n  "combinations": [\n    [\n      2\n    ],\n    [\n      0\n    ],\n    [\n      1\n    ]\n  ]\n}'
2017-04-06 09:03:57,966:DEBUG:acme.client:Storing nonce: "\xc9\x8d\xf9g\xe9G,Ry\xa13,\xe3L${!\xb8\xa3)\xc0'eeJ\xa1\xc5\xf7\xfaW4a"
2017-04-06 09:03:57,966:DEBUG:acme.client:Received response <Response [201]> (headers: {'Content-Length': '1001', 'Expires': 'Thu, 06 Apr 2017 09:03:57 GMT', 'Boulder-Request-Id': '8YJAQxwOauQTOpFRMao9NBYy_v_OkOeC-u_Yp9Q7YsQ', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/_KvPlR7E9iA2bj3vh1LHZck7WKeYeMYopI7J1oLH0D8', 'Pragma': 'no-cache', 'Boulder-Requester': '8056955', 'Date': 'Thu, 06 Apr 2017 09:03:57 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'yY35Z-lHLFJ5oTMs40wkeyG4oynAJ2VlSqHF9_pXNGE'}): '{\n  "identifier": {\n    "type": "dns",\n    "value": "website1.com"\n  },\n  "status": "pending",\n  "expires": "2017-04-13T09:03:57.313937797Z",\n  "challenges": [\n    {\n      "type": "http-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/_KvPlR7E9iA2bj3vh1LHZck7WKeYeMYopI7J1oLH0D8/973849842",\n      "token": "f5LF-2oiyzK-hf7AWWgg5C-5zeZPWMAgKXlTkYHJ-ME"\n    },\n    {\n      "type": "tls-sni-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/_KvPlR7E9iA2bj3vh1LHZck7WKeYeMYopI7J1oLH0D8/973849843",\n      "token": "YlxI0DMTqgaCV_fI2Queie9Ib9qqIY8l3lGlDxidCFU"\n    },\n    {\n      "type": "dns-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/_KvPlR7E9iA2bj3vh1LHZck7WKeYeMYopI7J1oLH0D8/973849844",\n      "token": "QDDJXuESWjTZ7oO7PXnMntMyWD5WSNvUeyaHg_t5vr0"\n    }\n  ],\n  "combinations": [\n    [\n      2\n    ],\n    [\n      0\n    ],\n    [\n      1\n    ]\n  ]\n}'
2017-04-06 09:03:57,968:DEBUG:acme.jose.json_util:Omitted empty fields: combinations=None, expires=None, status=None, challenges=None
2017-04-06 09:03:57,968:DEBUG:acme.client:Serialized JSON: {"identifier": {"type": "dns", "value": "website2.com"}, "resource": "new-authz"}
2017-04-06 09:03:57,969:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, alg=None, x5t=None, x5u=None, jwk=None, cty=None, kid=None, x5tS256=None
2017-04-06 09:03:57,971:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, x5t=None, x5u=None, x5tS256=None, cty=None, kid=None, nonce=None
2017-04-06 09:03:57,971:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "zjyq6w9UUP7bznIl5GxI8xJIUiCp8adSej7bV76ek1m83BOIXtSLhBRVeOx3FycqAPn--I0-3FGS6Rsrfcq84g4l03qX-JNKvh9_rHkLSojOSQsF5yUgESTS2GQEbtvFen4m0Y5U5FthsHiXRljVzeyMPjRNh3p9qUy0iIXxH20REivMBlGoXPD1tM5CHpc-EkEo5oaL8eyF0gzVjV2UTPfdORc1i5-Eyknv0yz7-LOAnvydsdTyO3CdouL4HpoMNUTHvbQeLdNQdIU5cMwbxKzeleW6rA025jqUwsFBRut2hcRffKSzdJZynMzapiWjHZlzFCDwQRdv0iY3EsYlMw"}}, "protected": "eyJub25jZSI6ICJ5WTM1Wi1sSExGSjVvVE1zNDB3a2V5RzRveW5BSjJWbFNxSEY5X3BYTkdFIn0", "payload": "eyJpZGVudGlmaWVyIjogeyJ0eXBlIjogImRucyIsICJ2YWx1ZSI6ICJjaGljYWdvZ2FuZ2hpc3RvcnkuY29tIn0sICJyZXNvdXJjZSI6ICJuZXctYXV0aHoifQ", "signature": "V25Y1H5Av9jkBnvfcbVv-ZyMghzCGa2SqI38CpwRvoet_v4oyOQeUoZn2Ywp11F_ZcpLF8KzFmc-0r_2c4hdZ0uG-X6nPQooVv7XkXKxLa1JjpxQm9TQ7pB1oGc6RE4wMV5GchIumjBvH5qaluK-Rv-Z-qI4U0VVHqRY4_XuoX5JrsMaUOa-ysIw-CjsYddz64hPwjfSngJRUxAotwcmuHdGZu5boqjdM9XR39AypOJGOpUGIC3TolUGXmJCg3lO_Uh0DDovYylvEIxymE2tYpwD5GKoQ_8420jSi1qfEH8NdZzwWteX09ZlaEZcPZJKET3nXCxSBl2JVl6dXiPT-w"}'}
2017-04-06 09:03:58,678:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 201 1007
2017-04-06 09:03:58,678:DEBUG:root:Received <Response [201]>. Headers: {'Content-Length': '1007', 'Expires': 'Thu, 06 Apr 2017 09:03:58 GMT', 'Boulder-Request-Id': '3nIFJ2B59Az90x4wlMxpHZwhUGyfITs1xsyVVe0Z_vI', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/zyPpYCs2Yj0OD9WdFZWHV5EGtWqftsvV-gVIIu3fqJc', 'Pragma': 'no-cache', 'Boulder-Requester': '8056955', 'Date': 'Thu, 06 Apr 2017 09:03:58 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'pTrtAWXXionTjosWQBDRkwLhfvN3qXYcqDD_TZbIyBc'}. Content: '{\n  "identifier": {\n    "type": "dns",\n    "value": "website2.com"\n  },\n  "status": "pending",\n  "expires": "2017-04-13T09:03:58.147162147Z",\n  "challenges": [\n    {\n      "type": "http-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyPpYCs2Yj0OD9WdFZWHV5EGtWqftsvV-gVIIu3fqJc/973849878",\n      "token": "qXWXT3LE-CauUstDUOgaTYTgkvYf9m7cxGnpx2O_bsw"\n    },\n    {\n      "type": "tls-sni-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyPpYCs2Yj0OD9WdFZWHV5EGtWqftsvV-gVIIu3fqJc/973849879",\n      "token": "uHlHdPfP20BQBxU8MDqLxmrW6osXHek5tERYrZAtcRg"\n    },\n    {\n      "type": "dns-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyPpYCs2Yj0OD9WdFZWHV5EGtWqftsvV-gVIIu3fqJc/973849880",\n      "token": "5K4hD1dAKvbDQFFS2pl11FEAvjvFd6Pq79fLPg-FtgM"\n    }\n  ],\n  "combinations": [\n    [\n      2\n    ],\n    [\n      0\n    ],\n    [\n      1\n    ]\n  ]\n}'
2017-04-06 09:03:58,679:DEBUG:acme.client:Storing nonce: '\xa5:\xed\x01e\xd7\x8a\x89\xd3\x8e\x8b\x16@\x10\xd1\x93\x02\xe1~\xf3w\xa9v\x1c\xa80\xffM\x96\xc8\xc8\x17'
2017-04-06 09:03:58,679:DEBUG:acme.client:Received response <Response [201]> (headers: {'Content-Length': '1007', 'Expires': 'Thu, 06 Apr 2017 09:03:58 GMT', 'Boulder-Request-Id': '3nIFJ2B59Az90x4wlMxpHZwhUGyfITs1xsyVVe0Z_vI', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Connection': 'keep-alive', 'Link': '<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"', 'Location': 'https://acme-v01.api.letsencrypt.org/acme/authz/zyPpYCs2Yj0OD9WdFZWHV5EGtWqftsvV-gVIIu3fqJc', 'Pragma': 'no-cache', 'Boulder-Requester': '8056955', 'Date': 'Thu, 06 Apr 2017 09:03:58 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'pTrtAWXXionTjosWQBDRkwLhfvN3qXYcqDD_TZbIyBc'}): '{\n  "identifier": {\n    "type": "dns",\n    "value": "website2.com"\n  },\n  "status": "pending",\n  "expires": "2017-04-13T09:03:58.147162147Z",\n  "challenges": [\n    {\n      "type": "http-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyPpYCs2Yj0OD9WdFZWHV5EGtWqftsvV-gVIIu3fqJc/973849878",\n      "token": "qXWXT3LE-CauUstDUOgaTYTgkvYf9m7cxGnpx2O_bsw"\n    },\n    {\n      "type": "tls-sni-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyPpYCs2Yj0OD9WdFZWHV5EGtWqftsvV-gVIIu3fqJc/973849879",\n      "token": "uHlHdPfP20BQBxU8MDqLxmrW6osXHek5tERYrZAtcRg"\n    },\n    {\n      "type": "dns-01",\n      "status": "pending",\n      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/zyPpYCs2Yj0OD9WdFZWHV5EGtWqftsvV-gVIIu3fqJc/973849880",\n      "token": "5K4hD1dAKvbDQFFS2pl11FEAvjvFd6Pq79fLPg-FtgM"\n    }\n  ],\n  "combinations": [\n    [\n      2\n    ],\n    [\n      0\n    ],\n    [\n      1\n    ]\n  ]\n}'
2017-04-06 09:03:58,679:INFO:certbot.auth_handler:Performing the following challenges:
2017-04-06 09:03:58,691:INFO:certbot.auth_handler:http-01 challenge for website1.com
2017-04-06 09:03:58,702:INFO:certbot.auth_handler:http-01 challenge for website2.com
2017-04-06 09:05:28,775:DEBUG:acme.challenges:Verifying http-01 at http://website1.com/.well-known/acme-challenge/f5LF-2oiyzK-hf7AWWgg5C-5zeZPWMAgKXlTkYHJ-ME...
2017-04-06 09:05:28,885:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): website1.com
2017-04-06 09:05:30,173:DEBUG:requests.packages.urllib3.connectionpool:"GET /.well-known/acme-challenge/f5LF-2oiyzK-hf7AWWgg5C-5zeZPWMAgKXlTkYHJ-ME HTTP/1.1" 200 None
2017-04-06 09:05:30,259:DEBUG:acme.challenges:Received <Response [200]>: f5LF-2oiyzK-hf7AWWgg5C-5zeZPWMAgKXlTkYHJ-ME.AUvSjL3krZYCsm2PMgypJZ6tLoA5V_5C3-PXzhTNTQA
. Headers: {'Content-Encoding': 'gzip', 'transfer-encoding': 'chunked', 'Age': '0', 'Vary': 'Accept-Encoding', 'Last-Modified': 'Thu, 06 Apr 2017 09:05:11 GMT', 'Connection': 'keep-alive', 'ETag': '"8a80a0c49ccab2879a13478bd0b5b5b2"', 'Date': 'Thu, 06 Apr 2017 09:05:29 GMT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'X-CSRF-Token', 'Content-Type': 'text/html; charset=utf-8'}
2017-04-06 09:09:02,472:DEBUG:acme.challenges:Verifying http-01 at http://website2.com/.well-known/acme-challenge/qXWXT3LE-CauUstDUOgaTYTgkvYf9m7cxGnpx2O_bsw...
2017-04-06 09:09:02,481:INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): website2.com
2017-04-06 09:09:03,377:DEBUG:requests.packages.urllib3.connectionpool:"GET /.well-known/acme-challenge/qXWXT3LE-CauUstDUOgaTYTgkvYf9m7cxGnpx2O_bsw HTTP/1.1" 200 108
2017-04-06 09:09:03,379:DEBUG:acme.challenges:Received <Response [200]>: qXWXT3LE-CauUstDUOgaTYTgkvYf9m7cxGnpx2O_bsw.AUvSjL3krZYCsm2PMgypJZ6tLoA5V_5C3-PXzhTNTQA
. Headers: {'Content-Length': '108', 'Content-Encoding': 'gzip', 'Age': '0', 'Vary': 'Accept-Encoding', 'Last-Modified': 'Thu, 06 Apr 2017 09:08:41 GMT', 'Connection': 'keep-alive', 'Date': 'Thu, 06 Apr 2017 09:09:03 GMT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'X-CSRF-Token', 'Content-Type': 'text/html; charset=utf-8'}
2017-04-06 09:09:03,379:INFO:certbot.auth_handler:Waiting for verification...
2017-04-06 09:09:03,390:DEBUG:acme.client:Serialized JSON: {"keyAuthorization": "f5LF-2oiyzK-hf7AWWgg5C-5zeZPWMAgKXlTkYHJ-ME.AUvSjL3krZYCsm2PMgypJZ6tLoA5V_5C3-PXzhTNTQA", "type": "http-01", "resource": "challenge"}
2017-04-06 09:09:03,391:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, alg=None, x5t=None, x5u=None, jwk=None, cty=None, kid=None, x5tS256=None
2017-04-06 09:09:03,393:DEBUG:acme.jose.json_util:Omitted empty fields: x5c=(), crit=(), typ=None, jku=None, x5t=None, x5u=None, x5tS256=None, cty=None, kid=None, nonce=None
2017-04-06 09:09:03,393:DEBUG:root:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/challenge/_KvPlR7E9iA2bj3vh1LHZck7WKeYeMYopI7J1oLH0D8/973849842. args: (), kwargs: {'data': '{"header": {"alg": "RS256", "jwk": {"e": "AQAB", "kty": "RSA", "n": "zjyq6w9UUP7bznIl5GxI8xJIUiCp8adSej7bV76ek1m83BOIXtSLhBRVeOx3FycqAPn--I0-3FGS6Rsrfcq84g4l03qX-JNKvh9_rHkLSojOSQsF5yUgESTS2GQEbtvFen4m0Y5U5FthsHiXRljVzeyMPjRNh3p9qUy0iIXxH20REivMBlGoXPD1tM5CHpc-EkEo5oaL8eyF0gzVjV2UTPfdORc1i5-Eyknv0yz7-LOAnvydsdTyO3CdouL4HpoMNUTHvbQeLdNQdIU5cMwbxKzeleW6rA025jqUwsFBRut2hcRffKSzdJZynMzapiWjHZlzFCDwQRdv0iY3EsYlMw"}}, "protected": "eyJub25jZSI6ICJwVHJ0QVdYWGlvblRqb3NXUUJEUmt3TGhmdk4zcVhZY3FERF9UWmJJeUJjIn0", "payload": "eyJrZXlBdXRob3JpemF0aW9uIjogImY1TEYtMm9peXpLLWhmN0FXV2dnNUMtNXplWlBXTUFnS1hsVGtZSEotTUUuQVV2U2pMM2tyWllDc20yUE1neXBKWjZ0TG9BNVZfNUMzLVBYemhUTlRRQSIsICJ0eXBlIjogImh0dHAtMDEiLCAicmVzb3VyY2UiOiAiY2hhbGxlbmdlIn0", "signature": "NxCYO6HIQ3ppaGufYCWHX02_WK1-VjE9mn1BGvp50CrI-XvSKx8F0Yz61clSzjeR9DdsQl9W7Vaqs5fPQ_hQAD0PmWyl-tc_UCHiBhDEomN2C1NK9iEjYYI_tOLC2m2euwWsIZrdMbwco8fGGRup7fwmVF_nmw_ZQii2oIlMJyFmcQdht_XllzXnlxnb-rCJ4Gqf_cVKbm_d9hygu6mGg7GMzIKlXw2dStGEHAPNJEZmTHi1lY2H-UnhJnYM-_eZLTPvCu1VpBWJ3RNcHxaoPXZiWNntOpi6CaF7Rtm7shM45fZ5LGJBI9WFp8VoZkCQkrbLyUFo9QkQPz2iJ4KVkg"}'}
2017-04-06 09:09:03,516:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/Users/derpdiggler/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 563, in obtain_cert
    action, _ = _auth_from_domains(le_client, config, domains, lineage)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/main.py", line 96, in _auth_from_domains
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/renewal.py", line 238, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/client.py", line 253, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 78, in get_authorizations
    self._respond(resp, best_effort)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 131, in _respond
    resp, chall_update)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/certbot/auth_handler.py", line 155, in _send_responses
    self.acme.answer_challenge(achall.challb, resp)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 227, in answer_challenge
    response = self.net.post(challb.uri, response)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 647, in post
    response = self._send_request('POST', url, data=data, **kwargs)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/acme/client.py", line 606, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/derpdiggler/.local/share/letsencrypt/lib/python2.7/site-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(SysCallError(54, 'ECONNRESET'),))
```

**Comment by SwartzCr** [comment]
Weird! Did you specify the domains interactively? Have you tried inputting them on the command line with the -d flag? (though that doesn't seem like the problem here)
It seems like something on your system is blocking certbot from making second post request. What are you using for your webserver? Do you have any programs that might be blocking certbot? (like little snitch?)

**Comment by jhabdas** [comment]
The first request goes through fine. I'll try the second one interactively again (alone this time) and see how it goes. As for the CLI, I haven't spent time groking it yet as I typically to custom TLS certs for my domains. I use Dan Pollock's hosts file. Cheers.

**Comment by SwartzCr** [comment]
Hmm - more information on your setup would be nice.
You're running certbot on your local computer and manually uploading the challenges to a webserver? Is that right?
If so, it'd be useful to know:
Where and how is the webserver hosted
Is there a reason you can't run certbot directly on the webserver
What does your local network look like - would there be anything preventing the computer you're running certbot on from from contacting the let's encrypt acme server
And maybe a link to that hosts file

**Comment by jhabdas** [comment]
Network should be ruled out as individual requests work fine. Hosting out of scope as I ran this locally. Going to close this for now to help you reduce noise in your repo. Please feel free to reopen if it makes sense.
