### ISSUE TITLE
Renew not working Ubuntu 16.04.2

### ISSUE THREAD

**Issue by joshespi** [certbot/certbot#4499]
## My operating system is (include version):
Ubuntu 16.04.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
I initially installed with the instructions found here a few months ago.
https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-ubuntu-16-04

This morning (4/13/17) I installed with the instructions found here.
https://certbot.eff.org/#ubuntuxenial-apache

I received the same type of issue before and after installing the new certbot

## I ran this command and it produced this output:
command:
`sudo certbot renew`

Output:
```
Cert is due for renewal, auto-renewing...
Could not choose appropriate plugin: The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',)
Attempting to renew cert from /etc/letsencrypt/renewal/globalassets.provo.edu.conf produced an unexpected error: The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',). Skipping.
```

I receive the same command for all 3 of the certs on this server.

## Certbot's behavior differed from what I expected because:
I'm still new to certbot/letsencrypt.  I'm not sure what the syntax error on line 2 of the letsencrypt log is referring to.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2017-04-13 15:40:43,144:DEBUG:certbot.main:Root logging level set at 20
2017-04-13 15:40:43,145:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-04-13 15:40:43,145:DEBUG:certbot.main:certbot version: 0.11.1
2017-04-13 15:40:43,145:DEBUG:certbot.main:Arguments: []
2017-04-13 15:40:43,145:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint$
2017-04-13 15:40:43,154:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2017-05-02 20:09:00 UTC.
2017-04-13 15:40:43,154:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2017-04-13 15:40:43,155:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-04-13 15:40:43,341:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): There has been an error in parsing the file /etc/apac$
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 114, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 191, in prepare
    self.check_parsing_errors("httpd.aug")
  File "/usr/lib/python2.7/dist-packages/certbot_apache/augeas_configurator.py", line 77, in check_parsing_errors
    raise errors.PluginError(msg)
PluginError: There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error
2017-04-13 15:40:43,342:DEBUG:certbot.plugins.selection:No candidate plugin
2017-04-13 15:40:43,342:DEBUG:certbot.plugins.selection:No candidate plugin
2017-04-13 15:40:43,342:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
2017-04-13 15:40:43,342:INFO:certbot.main:Could not choose appropriate plugin: The apache plugin is not working; there may be problems with your$
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',)
2017-04-13 15:40:43,343:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/globalassets.provo.edu.conf produced an u$
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',).$
2017-04-13 15:40:43,343:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 413, in handle_renewal_request
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 650, in obtain_cert
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly") 
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/selection.py", line 197, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/selection.py", line 272, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
PluginSelectionError: The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',)

2017-04-13 15:40:43,346:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2017-05-02 19:40:00 UTC.
2017-04-13 15:40:43,346:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2017-04-13 15:40:43,346:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-04-13 15:40:43,532:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): There has been an error in parsing the file /etc/apac$
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 114, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 191, in prepare
    self.check_parsing_errors("httpd.aug")
  File "/usr/lib/python2.7/dist-packages/certbot_apache/augeas_configurator.py", line 77, in check_parsing_errors
    raise errors.PluginError(msg)
PluginError: There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error
2017-04-13 15:40:43,532:DEBUG:certbot.plugins.selection:No candidate plugin
2017-04-13 15:40:43,532:DEBUG:certbot.plugins.selection:No candidate plugin
2017-04-13 15:40:43,532:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
2017-04-13 15:40:43,533:INFO:certbot.main:Could not choose appropriate plugin: The apache plugin is not working; there may be problems with your$
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',)
2017-04-13 15:40:43,533:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/beta.provo.edu.conf produced an unexpecte$
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',).$

2017-04-13 15:40:43,533:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 413, in handle_renewal_request
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 650, in obtain_cert
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/selection.py", line 197, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/selection.py", line 272, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
PluginSelectionError: The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',)  

2017-04-13 15:40:43,535:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2017-05-09 13:33:00 UTC.
2017-04-13 15:40:43,535:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2017-04-13 15:40:43,536:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-04-13 15:40:43,722:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): There has been an error in parsing the file /etc/apac$
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 114, in prepare
   self._initialized.prepare()
  File "/usr/lib/python2.7/dist-packages/certbot_apache/configurator.py", line 191, in prepare
    self.check_parsing_errors("httpd.aug")
  File "/usr/lib/python2.7/dist-packages/certbot_apache/augeas_configurator.py", line 77, in check_parsing_errors
    raise errors.PluginError(msg)
PluginError: There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error
2017-04-13 15:40:43,722:DEBUG:certbot.plugins.selection:No candidate plugin
2017-04-13 15:40:43,722:DEBUG:certbot.plugins.selection:No candidate plugin
2017-04-13 15:40:43,722:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
2017-04-13 15:40:43,722:INFO:certbot.main:Could not choose appropriate plugin: The apache plugin is not working; there may be problems with your$
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',)
2017-04-13 15:40:43,723:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/beta.employee.provo.edu.conf produced an $
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',).$
2017-04-13 15:40:43,723:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 413, in handle_renewal_request
    main.obtain_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 650, in obtain_cert
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/selection.py", line 197, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/plugins/selection.py", line 272, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
PluginSelectionError: The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',)

2017-04-13 15:40:43,723:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.11.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 882, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 688, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 430, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 3 renew failure(s), 0 parse failure(s)
```

Here is the file that the error is referring to. 

```
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1946, in main
    args = prepare_and_parse_args(plugins, cli_args)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1638, in prepare_and_parse_args
    return helpful.parse_args()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1206, in parse_args
    parsed_args = self.parser.parse_args(self.args)
  File "/usr/lib/python2.7/dist-packages/configargparse.py", line 216, in parse_args
    env_vars = env_vars)
  File "/usr/lib/python2.7/dist-packages/configargparse.py", line 349, in parse_known_args
    self, args=args, namespace=namespace)
  File "/usr/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python2.7/argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1837, in __call__
    _process_domain(args, domain_arg)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1818, in _process_domain
    domain = le_util.enforce_domain_sanity(domain)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/le_util.py", line 328, in enforce_domain_sanity
    "bare IP address.".format(domain))
ConfigurationError: Requested name 158.91.1.105 is an IP address. The Let's Encrypt certificate authority will not issue certificates for a bare$
```

**Comment by SwartzCr** [comment]
Hmm it seems like your apache conf file is throwing an error.
Have you changed it since you got your certs? If you changed the domain name to the ip address of your server that could be the problem ( as the error shown is ConfigurationError: Requested name 158.91.1.105 is an IP address. The Let's Encrypt certificate authority will not issue certificates for a bare [ip])
If you don't think that's the issue, sharing the output of `apache2ctl` would be helpful, alternately just posting your apache configs would also help

**Comment by joshespi** [comment]
I have not changed the anything with Apache config since I got the certs.  This is however the first Linux web server I've setup so its quite possible that I've set something up incorrectly. I've mostly used DigitalOcean guides to get me to the point I'm at.

For the record. I have the Server on a single IP as mentioned above. with 3 domains pointed at that IP.

## Apache Config (which should be mostly default)

```
# This is the main Apache server configuration file.  It contains the
# configuration directives that give the server its instructions.
# See http://httpd.apache.org/docs/2.4/ for detailed information about
# the directives and /usr/share/doc/apache2/README.Debian about Debian specific
# hints.
#
#
# Summary of how the Apache 2 configuration works in Debian:
# The Apache 2 web server configuration in Debian is quite different to
# upstream's suggested way to configure the web server. This is because Debian's
# default Apache2 installation attempts to make adding and removing modules,
# virtual hosts, and extra configuration directives as flexible as possible, in
# order to make automating the changes and administering the server as easy as
# possible.

# It is split into several files forming the configuration hierarchy outlined
# below, all located in the /etc/apache2/ directory:
#
#       /etc/apache2/
#       |-- apache2.conf
#       |       `--  ports.conf
#       |-- mods-enabled
#       |       |-- *.load
#       |       `-- *.conf
#       |-- conf-enabled
#       |       `-- *.conf
#       `-- sites-enabled
#               `-- *.conf
#
#
# * apache2.conf is the main configuration file (this file). It puts the pieces
#   together by including all remaining configuration files when starting up the
#   web server.
#
# * ports.conf is always included from the main configuration file. It is
#   supposed to determine listening ports for incoming connections which can be
#   customized anytime.
#
# * Configuration files in the mods-enabled/, conf-enabled/ and sites-enabled/
#   directories contain particular configuration snippets which manage modules,
#   global configuration fragments, or virtual host configurations,
#   respectively.
#
#   They are activated by symlinking available configuration files from their
#   respective *-available/ counterparts. These should be managed by using our
#   helpers a2enmod/a2dismod, a2ensite/a2dissite and a2enconf/a2disconf. See
#   their respective man pages for detailed information.
#
# * The binary is called apache2. Due to the use of environment variables, in
#   the default configuration, apache2 needs to be started/stopped with
#   /etc/init.d/apache2 or apache2ctl. Calling /usr/bin/apache2 directly will not
#   work with the default configuration.


# Global configuration
# 

# 
# ServerRoot: The top of the directory tree under which the server's
# configuration, error, and log files are kept.
# 
# NOTE!  If you intend to place this on an NFS (or otherwise network)  
# mounted filesystem then please read the Mutex documentation (available
# at <URL:http://httpd.apache.org/docs/2.4/mod/core.html#mutex>);
# you will save yourself a lot of trouble.
# 
# Do NOT add a slash at the end of the directory path.
#
#ServerRoot "/etc/apache2"

#
# The accept serialization lock file MUST BE STORED ON A LOCAL DISK.
#       
Mutex file:${APACHE_LOCK_DIR} default

#       
# PidFile: The file in which the server should record its process
# identification number when it starts.
# This needs to be set in /etc/apache2/envvars
#
PidFile ${APACHE_PID_FILE}
 
#
# Timeout: The number of seconds before receives and sends time out.
#   
Timeout 300
 
# 
# KeepAlive: Whether or not to allow persistent connections (more than
# one request per connection). Set to "Off" to deactivate.
#
KeepAlive On

#   
# MaxKeepAliveRequests: The maximum number of requests to allow
# during a persistent connection. Set to 0 to allow an unlimited amount.
# We recommend you leave this number high, for maximum performance.
#   
MaxKeepAliveRequests 100

#
# KeepAliveTimeout: Number of seconds to wait for the next request from the  
# same client on the same connection.
#   
KeepAliveTimeout 5


# These need to be set in /etc/apache2/envvars

# These need to be set in /etc/apache2/envvars
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}
  
# 
# HostnameLookups: Log the names of clients or just their IP addresses
# e.g., www.apache.org (on) or 204.62.129.132 (off).
# The default is off because it'd be overall better for the net if people
# had to knowingly turn this feature on, since enabling it means that   
# each client request will result in AT LEAST one lookup request to the
# nameserver.
# 
HostnameLookups Off
 
# ErrorLog: The location of the error log file.
# If you do not specify an ErrorLog directive within a <VirtualHost>
# container, error messages relating to that virtual host will be
# logged here.  If you *do* define an error logfile for a <VirtualHost>
# container, that host's errors will be logged there and not here.
#
ErrorLog ${APACHE_LOG_DIR}/error.log
        
# 
# LogLevel: Control the severity of messages logged to the error_log.
# Available values: trace8, ..., trace1, debug, info, notice, warn,
# error, crit, alert, emerg.
# It is also possible to configure the log level for particular modules, e.g.
# "LogLevel info ssl:warn"
#
LogLevel warn
    
# Include module configuration:
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

# Include list of ports to listen on
Include ports.conf


# Sets the default security model of the Apache2 HTTPD server. It does
# not allow access to the root filesystem outside of /usr/share and /var/www.
# The former is used by web applications packaged in Debian,
# the latter may be used for local directories served by the web server. If
# your system is serving content from a sub-directory in /srv you must allow
# access here, or in any related virtual host.
<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all denied
</Directory>

<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/>
        Options FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>

#<Directory /srv/>
#       Options Indexes FollowSymLinks
#       AllowOverride None
#       Require all granted
#</Directory>




# AccessFileName: The name of the file to look for in each directory
# for additional configuration directives.  See also the AllowOverride
# directive.
#       
AccessFileName .htaccess

# 
# The following lines prevent .htaccess and .htpasswd files from being
# viewed by Web clients.
# 
<FilesMatch "^\.ht">
        Require all denied
</FilesMatch>


#
# The following directives define some format nicknames for use with
# a CustomLog directive.
#
# These deviate from the Common Log Format definitions in that they use %O
# (the actual bytes sent including headers) instead of %b (the size of the
# requested file), because the latter makes it impossible to detect partial
# requests.
# 
# Note that the use of %{X-Forwarded-For}i instead of %h is not recommended.
# Use mod_remoteip instead.
# 
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

# Include of directories ignores editors' and dpkg's backup files,
# see README.Debian for details.
        
# Include generic snippets of statements
IncludeOptional conf-enabled/*.conf

# Include the virtual host configurations:
IncludeOptional sites-enabled/*.conf
        
# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

```

**Comment by joshespi** [comment]
Is that all you wanted? are there other configs I could provide?

**Comment by joshespi** [comment]
as an update. I'm now getting the following response when I try to run `apache2ctl configtest`

```
AH00526: Syntax error on line 12 of /etc/apache2/sites-enabled/globalassets.provo.edu-le-ssl.conf:
SSLCertificateFile: file '/etc/letsencrypt/live/globalassets.provo.edu/fullchain.pem' does not exist or is empty
```

I've verified that that file does exist, I've also verified that it is not empty.

**Comment by joshespi** [comment]
I get this error if/when trying to call down a new cert

```
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('There has been an error in parsing the file /etc/apache2/sites-available/letsencrypt.log on line 2: Syntax error',)
```

**Comment by joshespi** [comment]
I'm not sure if this is the best way to handle it, but it ended up working for me.  Mind you this temporarily took every site that had been using letsencrypt certs down.

I disabled all my sites in apache.
`sudo a2dissite (yoursiteconfig)`
Repeat that code for every site and SSL site config.

I then removed everything that was related to lets encrypt. I did all these commands in sudo
```
rm -rf /etc/letsencrypt/
rm /etc/apache2/sites-available/letsencrypt.log
rm /var/lib/letsencrypt
rm /var/log/letsencrypt
```
I then did a `sudo apt-get remove python-certbot-apache`

This had everything removed to my knowledge.

I then just started over from scratch install using the certbot.eff.org instruction. In my case for Ubuntu 16.04

`sudo apt-get update`
I ran updates
and then did a `sudo apt autoremove` since I had a few packages that are no longer being used

I then installed Certbot again with `sudo apt-get install python-certbot-apache`

I pulled down new certs for my 3 sites and everything is now working fine.

I did test `certbot --apache --dry-run renew` to confirm that my certs would renew successfully in the future. 

keep in mind you'll need to edit your http host file to accept traffic over port 80 again if you had them redirecting like I did.

I hope this continues to work anyway. Fingers crossed!

**Comment by SwartzCr** [comment]
Wow - that was quite the nuclear option. Thanks for the heroic debugging, I'm glad that worked out for you.
In the future feel free to ping me in #letsencrypt on irc.freenode.net if you need more hands on help. Sorry this was such a mess for you!
