### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by DevDaveo** [certbot/certbot#4502]
## My operating system is (include version):
Ubuntu 14.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
$ certbot-auto certonly --webroot --rsa-key-size 4096 --webroot-path /usr/local/psa/admin/htdocs -d 123-123-123-123.xyz.host.com

Obtaining a new certificate
Performing the following challenges:
http-01 challenge for 123-123-123-123.xyz.host.com
Using the webroot path /usr/local/psa/admin/htdocs for all unmatched domains.
Waiting for verification...
Cleaning up challenges
An unexpected error occurred:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbb' in position 306: ordinal not in range(128)

## Here is a Certbot log showing the issue:
2017-04-14 10:38:58,841:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 755, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 682, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 82, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 316, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 285, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 81, in get_authorizations
    self._respond(resp, best_effort)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 138, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 201, in _poll_challenges
    _report_failed_challs(all_failed_achalls)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 492, in _report_failed_challs
    _generate_failed_chall_msg(achalls), reporter.MEDIUM_PRIORITY)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 508, in _generate_failed_chall_msg
    if messages.is_acme_error(error):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/messages.py", line 39, in is_acme_error
    return (ERROR_PREFIX in str(err)) or (OLD_ERROR_PREFIX in str(err))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbb' in position 306: ordinal not in range(128)

I've noticed this error serveral times and it seems the solution is also relatively easy:
https://www.google.com/search?q=UnicodeEncodeError%3A+%27ascii%27+codec+can%27t+encode+character&ie=UTF-8

**Comment by SwartzCr** [comment]
Hi @DevDaveo this seems to be the same problem as #4273 (and #4241 and #4367)
We're hoping to get a fix to the misleading error message in this upcoming milestone (as is being tracked in #4273) but it's likely that the site that the Let's Encrypt Certificate Authority is trying to reach to verify your domain is not reachable, and the CA is sending back the error page. You can look at the other linked issues for more information, but I'd suggest trying to go to that subdomain in a web browser and seeing what happens or running webroot with manual and trying to navigate to the specific hash while Certbot is hosting it to manually check as well.
I'm going to close this, since we're tracking the general error elsewhere, but feel free to open other issues if you have more specific problems, or come chat in #letsencrypt on irc.freenode.net if you want more hands on help!
