### ISSUE TITLE
Error creating certificate with certbot, acme-v01.api.letsencrypt.org

### ISSUE THREAD

**Issue by ahmadkhudeish** [certbot/certbot#4531]
## My operating system is (include version):
Debian 8 (Jessie)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Ansible

## I ran this command and it produced this output:
certbot certonly -a webroot --webroot-path=/var/www/{{ letsencrypt_domain_name }} -d {{ letsencrypt_domain_name }}  -n --agree-tos --email {{ letsencrypt_email }}

## Certbot's behavior differed from what I expected because:
`stderr: Saving debug log to /var/log/letsencrypt/letsencrypt.log
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
An unexpected error occurred:
ConnectionError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f020eee70d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Please see the logfiles in /var/log/letsencrypt for more details.
`

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

`2017-04-20 01:55:59,029:DEBUG:certbot.main:Root logging level set at 20
2017-04-20 01:55:59,029:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-04-20 01:55:59,030:DEBUG:certbot.main:certbot version: 0.9.3
2017-04-20 01:55:59,030:DEBUG:certbot.main:Arguments: ['-a', 'webroot', '--webroot-path=/var/www/production/portal.feenix.co.nz/current', '-d', 'portal.feenix.co.nz', '-n', '--agree-tos', '--email', 'net$
2017-04-20 01:55:59,030:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2017-04-20 01:55:59,030:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2017-04-20 01:55:59,032:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f0a07dc9b50>
Prep: True
2017-04-20 01:55:59,033:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7f0a07dc9b50> and installer None
2017-04-20 01:55:59,210:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2017-04-20 01:55:59,217:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-04-20 01:55:59,234:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.9.3', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 776, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 558, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 368, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 353, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 118, in register
    acme = acme_from_config_key(config, key)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 42, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 624, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 606, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<requests.packages.urllib3.connection.Verifie$
`

**Comment by SwartzCr** [comment]
it seems that Certbot is being blocked from connecting to the let's encrypt server to receive your cert. 
Similar to a few problems that have be reported on the community forums: https://community.letsencrypt.org/t/max-retries-exceeded-with-acme-v01-api-letsencrypt-org-443/10711/15
and 
https://community.letsencrypt.org/t/problems-while-creating-a-certificate/32442
and
https://community.letsencrypt.org/t/possible-proxy-problem/15340/4

It's possible that you have some incorrect proxy settings or a firewall that are preventing you from connecting over port 443 to the acme server. There are some debugging recommendations in those links, but you might also benefit from this digital ocean guide: https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-debian-8
which mentions ways to configure IPTables and UFW

**Comment by SwartzCr** [comment]
also maybe @schoen has worked entirely through this problem with people on the commuity forum and has a recommendation

**Comment by schoen** [comment]
I have generally invited @jsha to debug it with people when there appeared to be any kind of connectivity problem reaching Akamai.

**Comment by jsha** [comment]
@ahmadkhudeish, could you re-post on the forum at https://community.letsencrypt.org/new-topic and we'll help you debug it over there? This is a configuration issue with your server, not a bug in Certbot, and we have a wider array of people on the forum who can bring their expertise to bear. Thanks!

**Comment by SwartzCr** [comment]
thanks @jsha - though I will mention that in a lot of the linked threads that I found people didn't seem to have been able to resolve their problems

**Comment by jsha** [comment]
Fair; though they are likely different issues. Two of the linked threads are "network is unreachable;" this one is "Failed to establish a new connection: [Errno -2] Name or service not known." The fact that exceptions get wrapped in a "Max retries exceeded" error makes root causes harder to see (https://github.com/certbot/certbot/issues/4535).

**Comment by mprokopov** [comment]
I was lucky to resolve this issue with

     docker network disconnect bridge certbot
     docker network connect bridge certbot

Somehow network connection for certbot has been stuck and disconnect/connect helped.

**Comment by alfiedotwtf** [comment]
I had this same error, and seemed like it was name resolution to blame. Adding the right entry to /etc/hosts fixed it.

**Comment by jsha** [comment]
Note that editing /etc/hosts is not a great long term solution, since the IP addresses this host resolves to are very likely to change.

**Comment by mprokopov** [comment]
I managed to fix this issue just with restart/recreate nginx docker container or both nginx and certbot.
