### ISSUE TITLE
Apache parsing problems

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4613]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Dev instructions

## I ran this command and it produced this output:

The virtual environment I was using is the one produced by `tools/venv3.sh`. The fact that Python 3 is being used is important. Starting with the default Apache configuration on this system, I ran:
```
certbot -d example.org --apache --no-redirect
certbot rollback --checkpoints 42
```
And got this traceback:
```
Exiting abnormally:
Traceback (most recent call last):
  File "venv3/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/home/bmw/src/certbot/certbot/main.py", line 742, in main
    return config.func(config, plugins)
  File "/home/bmw/src/certbot/certbot/main.py", line 515, in rollback
    client.rollback(config.installer, config.checkpoints, config, plugins)
  File "/home/bmw/src/certbot/certbot/client.py", line 615, in rollback
    config, default_installer, plugins, question="Which installer "
  File "/home/bmw/src/certbot/certbot/plugins/selection.py", line 32, in pick_installer
    config, default, plugins, question, (interfaces.IInstaller,))
  File "/home/bmw/src/certbot/certbot/plugins/selection.py", line 77, in pick_plugin
    verified.prepare()
  File "/home/bmw/src/certbot/certbot/plugins/disco.py", line 238, in prepare
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/home/bmw/src/certbot/certbot/plugins/disco.py", line 238, in <listcomp>
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/home/bmw/src/certbot/certbot/plugins/disco.py", line 120, in prepare
    self._initialized.prepare()
  File "/home/bmw/src/certbot/certbot-apache/certbot_apache/configurator.py", line 196, in prepare
    self.vhosts = self.get_virtual_hosts()
  File "/home/bmw/src/certbot/certbot-apache/certbot_apache/configurator.py", line 606, in get_virtual_hosts
    for vhost_path in self.parser.parser_paths.keys():
RuntimeError: dictionary changed size during iteration
```

## Certbot's behavior differed from what I expected because:

Rollback should work. Here's a traceback of where the problem occurs from `ipdb`:
```
  /home/bmw/src/certbot/venv3/bin/certbot(11)<module>()
     10     sys.exit(
---> 11         load_entry_point('certbot', 'console_scripts', 'certbot')()
     12     )

  /home/bmw/src/certbot/certbot/main.py(742)main()
    741 
--> 742     return config.func(config, plugins)
    743 

  /home/bmw/src/certbot/certbot/main.py(515)rollback()
    514     """Rollback server configuration changes made during install."""
--> 515     client.rollback(config.installer, config.checkpoints, config, plugins)
    516 

  /home/bmw/src/certbot/certbot/client.py(615)rollback()
    614     installer = plugin_selection.pick_installer(
--> 615         config, default_installer, plugins, question="Which installer "
    616         "should be used for rollback?")

  /home/bmw/src/certbot/certbot/plugins/selection.py(32)pick_installer()
     31     return pick_plugin(
---> 32         config, default, plugins, question, (interfaces.IInstaller,))
     33 

  /home/bmw/src/certbot/certbot/plugins/selection.py(77)pick_plugin()
     76     verified = filtered.verify(ifaces)
---> 77     verified.prepare()
     78     prepared = verified.available()

  /home/bmw/src/certbot/certbot/plugins/disco.py(238)prepare()
    237         """Prepare all plugins in the registry."""
--> 238         return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
    239 

  /home/bmw/src/certbot/certbot/plugins/disco.py(238)<listcomp>()
    237         """Prepare all plugins in the registry."""
--> 238         return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
    239 

  /home/bmw/src/certbot/certbot/plugins/disco.py(120)prepare()
    119             try:
--> 120                 self._initialized.prepare()
    121             except errors.MisconfigurationError as error:

  /home/bmw/src/certbot/certbot-apache/certbot_apache/configurator.py(196)prepare()
    195         # Get all of the available vhosts
--> 196         self.vhosts = self.get_virtual_hosts()
    197 

  /home/bmw/src/certbot/certbot-apache/certbot_apache/configurator.py(613)get_virtual_hosts()
    612             for path in paths:
--> 613                 new_vhost = self._create_vhost(path)
    614                 if not new_vhost:

  /home/bmw/src/certbot/certbot-apache/certbot_apache/configurator.py(567)_create_vhost()
    566 
--> 567         if self.parser.find_dir("SSLEngine", "on", start=path, exclude=False):
    568             is_ssl = True

  /home/bmw/src/certbot/certbot-apache/certbot_apache/parser.py(321)find_dir()
    320                     directive, arg,
--> 321                     self._get_include_path(self.get_arg(match + "/arg")),
    322                     exclude))

  /home/bmw/src/certbot/certbot-apache/certbot_apache/parser.py(433)_get_include_path()
    432         else:
--> 433             self._parse_file(arg)
    434 

  /home/bmw/src/certbot/certbot-apache/certbot_apache/parser.py(494)_parse_file()
    493                     self._remove_httpd_transform(filepath)
--> 494                 self._add_httpd_transform(filepath)
    495                 self.aug.load()

> /home/bmw/src/certbot/certbot-apache/certbot_apache/parser.py(567)_add_httpd_transform()
    566             self.parser_paths[os.path.dirname(incl)] = [
--> 567                 os.path.basename(incl)]
    568 
```
I believe what's happening is either we believe modules are loaded that weren't before or this is the first time we set `exclude=False` in a call to `find_dir`. Why would we ever set `exclude=False`?

@joohoi, I think this is probably a high priority ticket to work on (or at least investigate). We're continuing to find new files included by Apache meaning we didn't parse things right the first time (or there's a good reason for using `exclude=False` that I'm not aware of). I definitely could use your insight here.

**Comment by joohoi** [comment]
Your fix for the issue should be sufficient for now. The exclude=False seems to have been in place since 2015. This must be because we didn't have (and still don't besides Debian / Ubuntu) a reliable way to find out which directives to jump into and which not.

So there's two things that need improvement here:

 - Parser definitely could use some refactoring regarding these parts. This is what I think should be done first. For example separating the directive parsing discovery from other functionality (the find_directive here as an example), and reliably setting and using the variables controlling this exclude behavior amongst others.

- Making more distributions "smart" in this regard. ie. working out the distribution specific constraints and define & module loading methods, ultimately resulting us being able to have smart parsing there too, skipping the currently inactive parts and jumping into active ones.

**Comment by bmw** [comment]
Yeah I looked into it a bit and James added the `exclude` parameter when he made the parser able to parse conditionals on Debian based systems. Once the two tasks you identified above are resolved, I think we should remove it entirely as I don't see why we'd ever want to use it if we're properly able to parse conditionals.

**Comment by bmw** [comment]
Since this is a longer term goal and nothing is on fire, I'm moving this out of 0.15.0.
