### ISSUE TITLE
Multiple Apache Vhosts tests failed with augeas 1.7+

### ISSUE THREAD

**Issue by yan12125** [certbot/certbot#4624]
## My operating system is (include version):
Arch Linux latest

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
git clone

## I ran this command and it produced this output:
```
TOXENV=py36 tox
======================================================================
ERROR: test_choose_vhost_wildcard_found (certbot_apache.tests.configurator_test.AugeasVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1296, in test_choose_vhost_wildcard_found
    self.config.choose_vhost(name)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original

======================================================================
ERROR: test_choose_vhost_wildcard_not_found (certbot_apache.tests.configurator_test.AugeasVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1285, in test_choose_vhost_wildcard_not_found
    self.config.choose_vhost(name)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 339, in choose_vhost
    return self._choose_vhost_from_list(target_name, temp)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 360, in _choose_vhost_from_list
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original

======================================================================
ERROR: test_choose_vhost_with_matching_wildcard (certbot_apache.tests.configurator_test.AugeasVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1268, in test_choose_vhost_with_matching_wildcard
    self.assertFalse(name in self.config.choose_vhost(name).aliases)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original

======================================================================
ERROR: test_choose_vhost_without_matching_wildcard (certbot_apache.tests.configurator_test.AugeasVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1274, in test_choose_vhost_without_matching_wildcard
    self.assertTrue(name in self.config.choose_vhost(name).aliases)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 339, in choose_vhost
    return self._choose_vhost_from_list(target_name, temp)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 360, in _choose_vhost_from_list
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original

======================================================================
ERROR: test_make_vhost_ssl (certbot_apache.tests.configurator_test.MultiVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1328, in test_make_vhost_ssl
    ssl_vhost = self.config.make_vhost_ssl(self.vh_truth[1])
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original

======================================================================
ERROR: test_make_vhost_ssl_with_existing_rewrite_conds (certbot_apache.tests.configurator_test.MultiVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1395, in test_make_vhost_ssl_with_existing_rewrite_conds
    ssl_vhost = self.config.make_vhost_ssl(self.vh_truth[3])
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original

======================================================================
ERROR: test_make_vhost_ssl_with_existing_rewrite_rule (certbot_apache.tests.configurator_test.MultiVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1376, in test_make_vhost_ssl_with_existing_rewrite_rule
    ssl_vhost = self.config.make_vhost_ssl(self.vh_truth[4])
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original

======================================================================
ERROR: test_choose_vhost_select_vhost_non_ssl (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 230, in test_choose_vhost_select_vhost_non_ssl
    chosen_vhost = self.config.choose_vhost("none.com")
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 339, in choose_vhost
    return self._choose_vhost_from_list(target_name, temp)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 360, in _choose_vhost_from_list
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original

======================================================================
ERROR: test_http_header_hsts_twice (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 963, in test_http_header_hsts_twice
    "Strict-Transport-Security")
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 1218, in enhance
    func(self.choose_vhost(domain), options)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original
-------------------- >> begin captured logging << --------------------
certbot_apache.configurator: WARNING: Failed ensure-http-header for encryption-example.demo
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_http_header_hsts (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 941, in test_http_header_hsts
    "Strict-Transport-Security")
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 1218, in enhance
    func(self.choose_vhost(domain), options)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original
-------------------- >> begin captured logging << --------------------
certbot_apache.configurator: WARNING: Failed ensure-http-header for certbot.demo
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_http_header_uir (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 979, in test_http_header_uir
    "Upgrade-Insecure-Requests")
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 1218, in enhance
    func(self.choose_vhost(domain), options)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original
-------------------- >> begin captured logging << --------------------
certbot_apache.configurator: WARNING: Failed ensure-http-header for certbot.demo
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_http_header_uir_twice (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1001, in test_http_header_uir_twice
    "Upgrade-Insecure-Requests")
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 1218, in enhance
    func(self.choose_vhost(domain), options)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original
-------------------- >> begin captured logging << --------------------
certbot_apache.configurator: WARNING: Failed ensure-http-header for encryption-example.demo
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_make_vhost_ssl (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 602, in test_make_vhost_ssl
    ssl_vhost = self.config.make_vhost_ssl(self.vh_truth[0])
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original

======================================================================
ERROR: test_ocsp_stapling (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 862, in test_ocsp_stapling
    self.config.enhance("certbot.demo", "staple-ocsp")
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 1218, in enhance
    func(self.choose_vhost(domain), options)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original
-------------------- >> begin captured logging << --------------------
certbot_apache.configurator: WARNING: Failed staple-ocsp for certbot.demo
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_redirect_from_previous_run (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1144, in test_redirect_from_previous_run
    self.config.enhance("red.blue.purple.com", "redirect")
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 1218, in enhance
    func(self.choose_vhost(domain), options)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original
-------------------- >> begin captured logging << --------------------
certbot_apache.configurator: WARNING: Failed redirect for red.blue.purple.com
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_redirect_two_domains_one_vhost (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1132, in test_redirect_two_domains_one_vhost
    self.config.enhance("red.blue.purple.com", "redirect")
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 1218, in enhance
    func(self.choose_vhost(domain), options)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original
-------------------- >> begin captured logging << --------------------
certbot_apache.configurator: WARNING: Failed redirect for red.blue.purple.com
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_redirect_well_formed_http (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1016, in test_redirect_well_formed_http
    self.config.enhance("certbot.demo", "redirect")
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 1218, in enhance
    func(self.choose_vhost(domain), options)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original
-------------------- >> begin captured logging << --------------------
certbot_apache.configurator: WARNING: Failed redirect for certbot.demo
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_redirect_with_existing_rewrite (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1067, in test_redirect_with_existing_rewrite
    self.config.enhance("certbot.demo", "redirect")
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 1218, in enhance
    func(self.choose_vhost(domain), options)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 844, in make_vhost_ssl
    self._copy_create_ssl_vhost_skeleton(nonssl_vhost, ssl_fp)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 963, in _copy_create_ssl_vhost_skeleton
    ssl_vh_contents, sift = self._sift_rewrite_rules(orig_contents)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 1007, in _sift_rewrite_rules
    if B and not self._sift_rewrite_rule(line):
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 932, in _sift_rewrite_rule
    target = line.split()[2].strip()
IndexError: list index out of range
-------------------- >> begin captured logging << --------------------
certbot.reverter: DEBUG: Creating backup of /tmp/tmpwjw3vo_atemp/debian_apache_2_4/multiple_vhosts/apache2/sites-available/certbot.conf
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_redirect_with_old_https_redirection (certbot_apache.tests.configurator_test.MultipleVhostsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yen/Projects/certbot/.tox/py36/lib/python3.6/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/tests/configurator_test.py", line 1092, in test_redirect_with_old_https_redirection
    ssl_vhost = self.config.choose_vhost("certbot.demo")
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 333, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/home/yen/Projects/certbot/certbot-apache/certbot_apache/configurator.py", line 857, in make_vhost_ssl
    "Could not reverse map the HTTPS VirtualHost to the original")
certbot.errors.PluginError: Could not reverse map the HTTPS VirtualHost to the original

----------------------------------------------------------------------
Ran 167 tests in 6.005s

FAILED (errors=19)
```

## Certbot's behavior differed from what I expected because:
All tests should pass.

```TOXENV=py27 tox``` results in the same errors, so it's not a Python 2/3 trap.
I tried augeas 1.4.0, 1.5.0, 1.6.0, 1.7.0 and 1.8.0. Versions newer or equal to 1.7.0 break tests.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
N/A

**Comment by bmw** [comment]
Thanks for reporting this @yan12125.

cc @joohoi

**Comment by bmw** [comment]
At least part of the problem is due to the bug I filed with Augeas at hercules-team/augeas#466. I'll continue investigating this issue once we have a workaround for that problem.
