### ISSUE TITLE
Support non-ASCII in filenames

### ISSUE THREAD

**Issue by jsha** [certbot/certbot#4630]
Re-posting from https://github.com/certbot/certbot/issues/3614#issuecomment-299855587 by @brunis:

> I'm still having issues, tried registering a cert for bakkeløbet.dk. I puny encoded the domain name with punycoder.com. Using certbot 0.10.2.

> cmdline: sudo letsencrypt certonly -a webroot --webroot-path=/var/www/bakkeløbet/wordpress/ -d xn--bakkelbet-q8a.dk -d www.xn--bakkelbet-q8a.dk

> The output from letsencrypt is:
```
Encountered exception during recovery
'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/certbot/error_handler.py", line 99, in _call_registered
self.funcs-1
File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 280, in _cleanup_challenges
self.auth.cleanup(achalls)
File "/usr/lib/python2.7/dist-packages/certbot/plugins/webroot.py", line 224, in cleanup
validation_path = self._get_validation_path(root_path, achall)
File "/usr/lib/python2.7/dist-packages/certbot/plugins/webroot.py", line 198, in _get_validation_path
return os.path.join(root_path, achall.chall.encode("token"))
File "/usr/lib/python2.7/posixpath.py", line 80, in join
path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
An unexpected error occurred:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
Please see the logfiles in /var/log/letsencrypt for more details.
```
> Please add support for danish letters: æ, ø and å

Note: The original thread is about IDN support, but reading this stack trace, I notice that the problem is actually in constructing a filename. Specifically, Python is failing to encode `/var/www/bakkeløbet/wordpress/ ` as ASCII. We should support non-ASCII filenames.

**Comment by SwartzCr** [comment]
associating this with #4516

**Comment by jsha** [comment]
This error still happens with certbot-auto 0.35.1:

```
# certbot-auto certonly -a webroot --webroot-path=/var/www/hótml -d example2.com --staging --register-unsafely-without-email
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Registering without email!

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please read the Terms of Service at
https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf. You must
agree in order to register with the ACME server at
https://acme-staging-v02.api.letsencrypt.org/directory
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(A)gree/(C)ancel: a
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for example2.com
Using the webroot path /var/www/hótml for all unmatched domains.
Cleaning up challenges
Encountered exception during recovery: 
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/error_handler.py", line 124, in _call_registered
    self.funcs[-1]()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 220, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 221, in cleanup
    validation_path = self._get_validation_path(root_path, achall)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/plugins/webroot.py", line 196, in _get_validation_path
    return os.path.join(root_path, achall.chall.encode("token"))
  File "/opt/eff.org/certbot/venv/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
An unexpected error occurred:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 10: ordinal not in range(128)
Please see the logfiles in /var/log/letsencrypt for more details.

IMPORTANT NOTES:
 - Your account credentials have been saved in your Certbot
   configuration directory at /etc/letsencrypt. You should make a
   secure backup of this folder now. This configuration directory will
   also contain certificates and private keys obtained by Certbot so
   making regular backups of this folder is ideal.
```

**Comment by llimllib** [comment]
I think I hit the same error today when trying to upgrade certbot. Since you keep sending me nastygrams that you're going to stop allowing me to renew certificates in June, I would rate this as extremely frustrating.

```
$ sudo /usr/local/bin/certbot-auto certonly --nginx
/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a release (2.7.7+) that supports hmac.compare_digest as soon as possible.
  utils.PersistentlyDeprecated2018,
Saving debug log to /var/log/letsencrypt/letsencrypt.log
NGINX configured with OpenSSL alternatives is not officially supported by Certbot.
Plugins selected: Authenticator nginx, Installer nginx

Which names would you like to activate HTTPS for?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: billmill.org
2: gogs.billmill.org
3: www.billmill.org
4: hubvan.com
5: www.hubvan.com
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 1 3
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/billmill.org.conf)

What would you like to do?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Keep the existing certificate for now
2: Renew & replace the cert (limit ~5 per 7 days)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 2
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for billmill.org
http-01 challenge for www.billmill.org
Cleaning up challenges
An unexpected error occurred:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 113: ordinal not in range(128)
Please see the logfiles in /var/log/letsencrypt for more details.
```
Is some particular version of python required? If so, https://certbot.eff.org/lets-encrypt/ubuntuother-nginx should say so

```
$ python --version
Python 2.7.6
$ uname -a
Linux hubvan 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

**Comment by llimllib** [comment]
I managed to fix it (maybe!) by following this advice: https://github.com/certbot/certbot/issues/5592#issuecomment-456113602

(The file location has changed to `/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_nginx/_internal/parser.py`)

It's pretty crazy that that's what I had to do

**Comment by ivan-u7n** [comment]
It's a pity that such a support is unplanned. However I don't use webroot to authenticate my domains, I use manual hook for it. So the only stumbling point for me is a non-ascii --cert-name, and then it's error out only when generating the renewal config:

```
2021-04-01 11:09:51,779:DEBUG:certbot.storage:Writing new config /etc/letsencrypt/renewal/курск.рф.conf.
2021-04-01 11:09:51,780:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1250, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 428, in obtain_and_enroll_certificate
    self.config)
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 1048, in new_lineage
    target, values)
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 150, in write_renewal_config
    config.write(outfile=f)
  File "/usr/lib/python3/dist-packages/configobj.py", line 2119, in write
    'ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 88-92: ordinal not in range(128)
2021-04-01 11:09:51,787:ERROR:certbot.log:An unexpected error occurred:
```

Everything else up to this point works just fine, i.e. the certificate is issued. Or should I file a separate issue for my issue as this was the closest match I found.
