### ISSUE TITLE
Incompatible with ConfigArgParse 0.12.0

### ISSUE THREAD

**Issue by mesouug** [certbot/certbot#4648]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip

## I ran this command and it produced this output:
An unexpected error occurred:
AttributeError: 'tuple' object has no attribute 'add'

## Certbot's behavior differed from what I expected because:
ConfigArgParse updated to version 0.12.0

## Here is a Certbot log showing the issue (if available):
```
# cat /tmp/tmpsCKLky 
2017-05-12 16:49:25,831:DEBUG:certbot.main:certbot version: 0.14.0
2017-05-12 16:49:25,832:DEBUG:certbot.main:Arguments: []
2017-05-12 16:49:25,832:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-05-12 16:49:25,835:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/share/letsencrypt/env/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/share/letsencrypt/env/local/lib/python2.7/site-packages/certbot/main.py", line 729, in main
    args = cli.prepare_and_parse_args(plugins, cli_args)
  File "/usr/local/share/letsencrypt/env/local/lib/python2.7/site-packages/certbot/cli.py", line 1089, in prepare_and_parse_args
    helpful.add_deprecated_argument("--agree-dev-preview", 0)
  File "/usr/local/share/letsencrypt/env/local/lib/python2.7/site-packages/certbot/cli.py", line 741, in add_deprecated_argument
    self.parser.add_argument, argument_name, num_args)
  File "/usr/local/share/letsencrypt/env/local/lib/python2.7/site-packages/certbot/util.py", line 479, in add_deprecated_argument
    configargparse.ACTION_TYPES_THAT_DONT_NEED_A_VALUE.add(ShowWarning)
AttributeError: 'tuple' object has no attribute 'add'
```

**Comment by LINKIWI** [comment]
+1, also seeing this problem.

The relevant command that is triggering this exception in my case is `sudo letsencrypt --apache -d <domain> -d <another domain>`. This same command has always worked in the past.

**Comment by ryanpineo** [comment]
This is caused by the recent release of configargparse version 0.12.0.  The variable ACTION_TYPES_THAT_DONT_NEED_A_VALUE was changed from a set to a tuple in that release.

**Comment by ahaw021** [comment]
I have written a work around until the bug is fixed https://community.letsencrypt.org/t/potential-issue-with-new-certbot-and-argparse-attributeerror-tuple-object-has-no-attribute-add/33978

**Comment by anthony-o** [comment]
I have the same issue on a Ubuntu 14.04 with latest updates.

**Comment by koobs** [comment]
FreeBSD port (certbot) is also affected by this after its dependency was updated to 0.12. Tracking in [FreeBSD Bugzilla #219306](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219306)
