### ISSUE TITLE
Cannot run the Certbot

### ISSUE THREAD

**Issue by Astrian** [certbot/certbot#4658]
## My operating system is (include version):
Ubuntu 16.04.1 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`apt-get pip`

## I ran this command and it produced this output:
```
➜  ~ certbot certonly
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'acme==0.12.0.dev0' distribution was not found and is required by certbot
```

## Certbot's behavior differed from what I expected because:
It can't run

**Comment by yan12125** [comment]
> I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get pip

Hmm, apt-get and pip are two different ways to install certbot, and they may conflict with each other. Could you try to uninstall all existing certbot applications (```apt-get remove```, ```pip uninstall```, etc.) and install with [the suggested approach for Ubuntu 16.04](https://certbot.eff.org/#ubuntuxenial-other)?
```
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa:certbot/certbot
$ sudo apt-get update
$ sudo apt-get install certbot
```

**Comment by pde** [comment]
@Astrian you may also need to do something like "sudo pip uninstall certbot acme" to get rid of the version from `pip`.
