### ISSUE TITLE
DNS label contains malformed punycode

### ISSUE THREAD

**Issue by skhello27** [certbot/certbot#4664]
## My operating system is (include version): 
Debian 7.11

## I installed Certbot with (certbot-auto, OS package manager, pip, etc): 
certbot-auto

## I ran this command and it produced this output: ./certbot-auto
<skip>
   16: xn--8080apmfex.xn--p1ai
    17: www.xn--8080apmfex.xn--p1ai
    18: xn--v1aaa.xn--8080apmfex.xn--p1ai
    -------------------------------------------------------------------------------
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel):16
Obtaining a new certificate
An unexpected error occurred:
The request message was malformed :: Error creating new authz :: DNS label contains malformed punycode
Please see the logfiles in /var/log/letsencrypt for more details.

xxx@vds3997:~# cat /etc/nginx/sites-available/psy-apache | grep server_
    server_name www.xn--80apmfex.xn--p1ai xn--80apmfex.xn--p1ai xn--v1aaa.xn--80apmfex.xn-
-p1ai;

## Certbot's behavior differed from what I expected because:

as we can see certbot doubles 80 in my domain name

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Content-Type: application/json
Content-Length: 352
Boulder-Request-Id: RwdAFEAB8LroQOHGExZUZ5zbshExtxV9FOVF2qS2KaA
Replay-Nonce: 8USr_fl-yP8IcvTvsl88nh2RiXi9hJ5GkDC-zEu5D00
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 15 May 2017 15:45:51 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 15 May 2017 15:45:51 GMT
Connection: keep-alive

{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
2017-05-15 15:45:58,929:INFO:certbot.main:Obtaining a new certificate
2017-05-15 15:45:58,930:DEBUG:acme.client:Requesting fresh nonce
2017-05-15 15:45:58,930:DEBUG:acme.client:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz.
2017-05-15 15:45:59,154:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "HEAD /acme/new-authz HTTP
.1" 405 0
2017-05-15 15:45:59,155:DEBUG:acme.client:Received response:
HTTP 405
Server: nginx
Content-Type: application/problem+json
Content-Length: 91
Allow: POST
Boulder-Request-Id: zPR_Thx4ww-OuETpqBjQnwU1_WunuAhqeWTXfE_Bh-A
Replay-Nonce: BlSpNulyQ9q0Y_KSaZKM4SG6hA2SDnt1nl_rM1F8Y1U
Expires: Mon, 15 May 2017 15:45:59 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 15 May 2017 15:45:59 GMT
Connection: keep-alive

2017-05-15 15:45:59,155:DEBUG:acme.client:Storing nonce: BlSpNulyQ9q0Y_KSaZKM4SG6hA2SDnt1nl_rM1F8Y1U
2017-05-15 15:45:59,155:DEBUG:acme.client:JWS payload:
{
  "identifier": {
    "type": "dns",
    "value": "xn--8080apmfex.xn--p1ai"
  },
  "resource": "new-authz"
}
2017-05-15 15:45:59,159:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz:
{
  "header": {
    "alg": "RS256",
    "jwk": {
      "e": "AQAB",
      "kty": "RSA",
      "n": "uuZqnIHVb4QCUmc1cbjsyGDTs6YPrLymEvA1FhnqBze3KiTUJHNKXaXkOMZJkerDvwfPScZtkBxO6HtZNmvAobabCdQVjmsomaT7v6fUGzy1WeZ1HJ_ZZWZgMBS6FX
hgV06zAOd3hkfOGgLE05tAX8WbNfNLudiJfRDlNNd_u4qcDoXM07v7gmwGvBIBIY6X7sjcJE982_vlVq9i_RwHN_SjzA-83QznqYRcnNlgU56MK5XUt-WFeExiYAZlXK1buj6zGVQQ
4BafhTqWuXx5cQynW1okF9xzZ78o63veBmyiMGyJJY0JL0PZexaPAPF9t2B-aPj3LRqvF4folQ"
    }
  },
  "protected": "eyJub25jZSI6ICJCbFNwTnVseVE5cTBZX0tTYVpLTTRTRzZoQTJTRG50MW5sX3JNMUY4WTFVIn0",
  "payload": "ewogICJpZGVudGlmaWVyIjogewogICAgInR5cGUiOiAiZG5zIiwgCiAgICAidmFsdWUiOiAieG4tLTgwODBhcG1mZXgueG4tLXAxYWkiCiAgfSwgCiAgInJlc291
NlIjogIm5ldy1hdXRoeiIKfQ",
  "signature": "EAtMULRoMxHMiZ6JEK_sVNWydeVBTJBTiia0k8NXMkUkgBFwwgdLHESmO-Lh8s4e9HXg5Z_2viYbHRv5QLJrkHADQPpUjXVvWiFUowPqenh52VYwGm2RYK5MlN
RNncywvVUYT4mf6CeuaokROjWVlLBGOQMowI7uoJbXSlCYSEgFHleRbUd4XvWCA6TWZDQYyv5Nk5-PTi6Y-ISSEPfVCSHbv56TnZHAXzai-10U9NyhjzT4AhiflpWMbrviiqrrr2uy
a-_lwFS8I294eYGaz42NNraw2L0LKE1LfyM6jOOUc998hkSf8VzlHWlWhq1o_VvQs2mDFoX5pycThQ"
}
2017-05-15 15:45:59,394:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-authz HTTP
.1" 400 138
2017-05-15 15:45:59,395:DEBUG:acme.client:Received response:
HTTP 400
Server: nginx
Content-Type: application/problem+json
Content-Length: 138
Boulder-Request-Id: n840QfU9iivzHUh0tpRCkKGASMw7OoS0mfyhaZaS92Q
Boulder-Requester: 14506710
Replay-Nonce: wSJ3YlhMffhVZwaItcJrDnR9IncYxgphdXMqltMsUXI
Expires: Mon, 15 May 2017 15:45:59 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 15 May 2017 15:45:59 GMT
Connection: close

{
  "type": "urn:acme:error:malformed",
  "detail": "Error creating new authz :: DNS label contains malformed punycode",
  "status": 400
}
2017-05-15 15:45:59,395:DEBUG:acme.client:Storing nonce: wSJ3YlhMffhVZwaItcJrDnR9IncYxgphdXMqltMsUXI
2017-05-15 15:45:59,396:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 742, in main
    return config.func(config, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 597, in run
    certname, lineage)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 82, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 344, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/client.py", line 313, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 66, in get_authorizations
    self.authzr[domain] = self.acme.request_domain_challenges(domain)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 212, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 191, in request_challenges
    response = self.net.post(self.directory.new_authz, new_authz)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 674, in post
    return self._post_once(*args, **kwargs)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 687, in _post_once
    return self._check_response(response, content_type=content_type)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/client.py", line 574, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:malformed :: The request message was malformed :: Error creating new authz :: DNS label contains malformed punycode

**Comment by SwartzCr** [comment]
That sure seems like a bug! It's probably a problem with python string handling? @bmw or @yan12125 want to investigate?

**Comment by yan12125** [comment]
Hmm I can't reproduce this on Arch Linux. I change ```server localhost;``` to ```server_name  www.xn--80apmfex.xn--p1ai;```, and ```certbot --nginx``` shows the correct domain name. (tested with master and 0.14.0, Python 2.7.13 and 3.6.1 - 4 scenarios in total)

**Comment by skhello27** [comment]
This bug disappeared. 
I do not know why. 
May be it was fluctuation.
