### ISSUE TITLE
An unexpected error occurred: VersionConflict

### ISSUE THREAD

**Issue by alduxvm** [certbot/certbot#4670]
## My operating system is (include version):
Ubuntu 14.04.5 LTS 

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
It was executed from source `git clone https://github.com/letsencrypt/letsencrypt`

## I ran this command and it produced this output:
```
./letsencrypt-auto renew --agree-tos
Error: couldn't get currently installed version for /root/.local/share/letsencrypt/bin/letsencrypt: 
An unexpected error occurred:
VersionConflict: (acme 0.14.0 (/root/.local/share/letsencrypt/lib/python2.7/site-packages), Requirement.parse('acme==0.12.0'))
Please see the logfile '/tmp/tmp4Z07EI' for more details.
```

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
File '/tmp/tmp4Z07EI':
```
2017-05-16 11:14:35,444:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 722, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 193, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 40, in __init__
    self.plugin_cls = entry_point.load()
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2301, in load
    self.require(*args, **kwargs)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (acme 0.14.0 (/root/.local/share/letsencrypt/lib/python2.7/site-packages), Requirement.parse('acme==0.12.0'))
```

**Comment by dvdvck** [comment]
Trying to invalidate the local cache made the trick
`
root@stooge:~# cd .local/share/
root@stooge:~/.local/share# mv letsencrypt/ letsencrypt.old
`
This would not fix the root cause but you can proceed as always do ;)

**Comment by SwartzCr** [comment]
Did that work?
I think the problem is that you have a very old version and are trying to install a new version on top of it. As @dvdvck suggested, removing the old version should fix your problem. Let me know if that works!

**Comment by alduxvm** [comment]
The above worked, thanks!
