### ISSUE TITLE
Timeout and error 504 when running "certbot certonly" and entering an email

### ISSUE THREAD

**Issue by seenickcode** [certbot/certbot#4695]
## My operating system is (include version):
Ubuntu 16.04.1 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get

## I ran this command and it produced this output:

1. try to gen a cert, enter your email
```
root@ip-172-31-31-206:/home/ubuntu# certbot certonly
Saving debug log to /var/log/letsencrypt/letsencrypt.log

How would you like to authenticate with the ACME CA?
-------------------------------------------------------------------------------
1: Spin up a temporary webserver (standalone)
2: Place files in webroot directory (webroot)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
Enter email address (used for urgent renewal and security notices) (Enter 'c' to
cancel):<MY EMAIL>
```

2.  the system pauses after this and times out:
```
An unexpected error occurred:
ClientError: <Response [504]>
Please see the logfiles in /var/log/letsencrypt for more details.
```

3.  Logs:
```
root@ip-172-31-31-206:/home/ubuntu# tail -n 500 /var/log/letsencrypt
tail: error reading '/var/log/letsencrypt': Is a directory
root@ip-172-31-31-206:/home/ubuntu# tail -n 500 /var/log/letsencrypt/letsencrypt.log
2017-05-19 15:11:26,847:DEBUG:certbot.main:certbot version: 0.14.1
2017-05-19 15:11:26,848:DEBUG:certbot.main:Arguments: []
2017-05-19 15:11:26,848:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-05-19 15:11:26,856:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7f6bf6c601d0> and installer <certbot.cli._Default object at 0x7f6bf6c601d0>
2017-05-19 15:11:26,856:DEBUG:certbot.cli:Default Detector is Namespace(account=<certbot.cli._Default object at 0x7f6bf6c59790>, agree_dev_preview=None, allow_subset_of_names=<certbot.cli._Default object at 0x7f6bf6c59b50>, apache=<certbot.cli._Default object at 0x7f6bf6c604d0>, authenticator=<certbot.cli._Default object at 0x7f6bf6c601d0>, break_my_certs=<certbot.cli._Default object at 0x7f6bf6c43d90>, cert_path=<certbot.cli._Default object at 0x7f6bf6c5d990>, certname=<certbot.cli._Default object at 0x7f6bf6c596d0>, chain_path=<certbot.cli._Default object at 0x7f6bf6c5dc90>, checkpoints=<certbot.cli._Default object at 0x7f6bf6c5d490>, config_dir=<certbot.cli._Default object at 0x7f6bf6c5dd90>, config_file=None, configurator=<certbot.cli._Default object at 0x7f6bf6c601d0>, csr=<certbot.cli._Default object at 0x7f6bf6c5d290>, debug=<certbot.cli._Default object at 0x7f6bf6c4a590>, debug_challenges=<certbot.cli._Default object at 0x7f6bf6c4a3d0>, dialog=None, domains=<certbot.cli._Default object at 0x7f6bf6c595d0>, dry_run=<certbot.cli._Default object at 0x7f6bf6c597d0>, duplicate=<certbot.cli._Default object at 0x7f6bf6c59590>, eff_email=<certbot.cli._Default object at 0x7f6bf6c59bd0>, email=<certbot.cli._Default object at 0x7f6bf6c59ad0>, expand=<certbot.cli._Default object at 0x7f6bf6c59ed0>, force_interactive=<certbot.cli._Default object at 0x7f6bf6c594d0>, fullchain_path=<certbot.cli._Default object at 0x7f6bf6c5db90>, func=<function certonly at 0x7f6bf0bee938>, hsts=<certbot.cli._Default object at 0x7f6bf6c43610>, http01_port=<certbot.cli._Default object at 0x7f6bf6c43f10>, ifaces=<certbot.cli._Default object at 0x7f6bf6c5d790>, init=<certbot.cli._Default object at 0x7f6bf6c5d590>, installer=<certbot.cli._Default object at 0x7f6bf6c601d0>, key_path=<certbot.cli._Default object at 0x7f6bf6c5da90>, logs_dir=<certbot.cli._Default object at 0x7f6bf6c5df90>, manual=<certbot.cli._Default object at 0x7f6bf6c607d0>, manual_auth_hook=<certbot.cli._Default object at 0x7f6bf6c60a10>, manual_cleanup_hook=<certbot.cli._Default object at 0x7f6bf6c60b50>, manual_public_ip_logging_ok=<certbot.cli._Default object at 0x7f6bf6c60c50>, must_staple=<certbot.cli._Default object at 0x7f6bf6c43a90>, nginx=<certbot.cli._Default object at 0x7f6bf6c605d0>, no_bootstrap=<certbot.cli._Default object at 0x7f6bf6c4abd0>, no_self_upgrade=<certbot.cli._Default object at 0x7f6bf6c59190>, no_verify_ssl=<certbot.cli._Default object at 0x7f6bf6c4a250>, noninteractive_mode=<certbot.cli._Default object at 0x7f6bf6c593d0>, num=<certbot.cli._Default object at 0x7f6bf6cb0f10>, os_packages_only=<certbot.cli._Default object at 0x7f6bf6c59390>, post_hook=<certbot.cli._Default object at 0x7f6bf6cbab50>, pre_hook=<certbot.cli._Default object at 0x7f6bf6cba910>, pref_challs=<certbot.cli._Default object at 0x7f6bf6cba690>, prepare=<certbot.cli._Default object at 0x7f6bf6c5d690>, quiet=<certbot.cli._Default object at 0x7f6bf6c4a910>, reason=<certbot.cli._Default object at 0x7f6bf6c5d390>, redirect=<certbot.cli._Default object at 0x7f6bf6c43910>, register_unsafely_without_email=<certbot.cli._Default object at 0x7f6bf6c598d0>, reinstall=<certbot.cli._Default object at 0x7f6bf6c59dd0>, renew_by_default=<certbot.cli._Default object at 0x7f6bf6c59f50>, renew_hook=<certbot.cli._Default object at 0x7f6bf6cbad90>, renew_with_new_domains=<certbot.cli._Default object at 0x7f6bf6c59d50>, rsa_key_size=<certbot.cli._Default object at 0x7f6bf6c43c10>, server=<certbot.cli._Default object at 0x7f6bf6c600d0>, staging=<certbot.cli._Default object at 0x7f6bf6c4a790>, standalone=<certbot.cli._Default object at 0x7f6bf6c606d0>, standalone_supported_challenges=<certbot.cli._Default object at 0x7f6bf6c60d90>, staple=<certbot.cli._Default object at 0x7f6bf6cbaf90>, strict_permissions=<certbot.cli._Default object at 0x7f6bf6cba450>, text_mode=<certbot.cli._Default object at 0x7f6bf6c592d0>, tls_sni_01_port=<certbot.cli._Default object at 0x7f6bf6c4a0d0>, tos=<certbot.cli._Default object at 0x7f6bf6c59990>, uir=<certbot.cli._Default object at 0x7f6bf6c43310>, update_registration=<certbot.cli._Default object at 0x7f6bf6c599d0>, user_agent=<certbot.cli._Default object at 0x7f6bf6c5d190>, validate_hooks=<certbot.cli._Default object at 0x7f6bf6cb0990>, verb='certonly', verbose_count=<certbot.cli._Default object at 0x7f6bf6c591d0>, webroot=<certbot.cli._Default object at 0x7f6bf6c608d0>, webroot_map=<certbot.cli._Default object at 0x7f6bf6c60f90>, webroot_path=<certbot.cli._Default object at 0x7f6bf6c609d0>, work_dir=<certbot.cli._Default object at 0x7f6bf6c5de90>)
2017-05-19 15:11:26,861:DEBUG:certbot.log:Root logging level set at 20
2017-05-19 15:11:26,862:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-05-19 15:11:26,862:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2017-05-19 15:11:26,928:DEBUG:certbot.plugins.selection:Multiple candidate plugins: * standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x7f6bf4e652d0>
Prep: True

* webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f6bf6c60d10>
Prep: True
2017-05-19 15:11:28,427:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x7f6bf4e652d0> and installer None
2017-05-19 15:11:31,697:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-05-19 15:11:31,712:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-05-19 15:11:51,878:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 504 175
2017-05-19 15:11:51,878:DEBUG:acme.client:Received response:
HTTP 504
Server: AkamaiGHost
Mime-Version: 1.0
Content-Type: text/html
Content-Length: 175
Expires: Fri, 19 May 2017 15:11:51 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 19 May 2017 15:11:51 GMT
Connection: keep-alive

<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An error occurred while processing your request.<p>
Reference&#32;&#35;97&#46;43111cb8&#46;1495206711&#46;f179cdc
</BODY></HTML>

2017-05-19 15:11:51,879:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.14.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 742, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 666, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 382, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 367, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 158, in register
    acme = acme_from_config_key(config, key)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 44, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 71, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 646, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 580, in _check_response
    raise errors.ClientError(response)
ClientError: <Response [504]>
```

## Certbot's behavior differed from what I expected because:
It should go to the next step.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Above.

**Comment by cpu** [comment]
This error is a result of an ongoing service disruption. Please follow status.letsencrypt.org for more information. We should have all of the remaining issues resolved shortly.

I don't believe there is anything for the Certbot developers to do in this case so I'm going to close this issue for now. Please re-open if I'm wrong!
