### ISSUE TITLE
ClientError: <Response [504]>

### ISSUE THREAD

**Issue by crankwan** [certbot/certbot#4696]
## My operating system is (include version):
```
Ubuntu 16.04
Linux version 4.4.0-63-generic (buildd@lcy01-31) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #84-Ubuntu SMP Wed Feb 1 17:20:32 UTC 2017
```
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

```
apt install letsencrypt
```
> I installed letsencrypt on the other ubuntu server and version is 4.4.0-78-generic,
> pip version both are 8.1.1, is it related to the linux kernal version? 
## I ran this command and it produced this output:
```
An unexpected error occurred:                                                                                                                                                                                          
ClientError: <Response [504]>
```
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2017-05-19 16:43:50,770:DEBUG:letsencrypt.cli:Root logging level set at 30
2017-05-19 16:43:50,772:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-05-19 16:43:50,772:DEBUG:letsencrypt.cli:letsencrypt version: 0.4.1
2017-05-19 16:43:50,772:DEBUG:letsencrypt.cli:Arguments: []
2017-05-19 16:43:50,773:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2017-05-19 16:43:50,777:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2017-05-19 16:43:51,032:DEBUG:letsencrypt.plugins.disco:Other error:(PluginEntryPoint#webroot): Missing parts of webroot configuration; please set either --webroot-path and --domains, or --webroot-map. Run with  --help webroot for examples.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/disco.py", line 103, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/plugins/webroot.py", line 56, in prepare
    "Missing parts of webroot configuration; please set either "
PluginError: Missing parts of webroot configuration; please set either --webroot-path and --domains, or --webroot-map. Run with  --help webroot for examples.
2017-05-19 16:43:51,033:DEBUG:letsencrypt.display.ops:Single candidate plugin: * standalone
Description: Automatically use a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = letsencrypt.plugins.standalone:Authenticator
Initialized: <letsencrypt.plugins.standalone.Authenticator object at 0x7f05030ed410>
Prep: True
2017-05-19 16:43:51,034:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt.plugins.standalone.Authenticator object at 0x7f05030ed410> and installer None
2017-05-19 16:43:55,757:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2017-05-19 16:43:55,760:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-05-19 16:44:56,643:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 504 176
2017-05-19 16:44:56,647:DEBUG:root:Received <Response [504]>. Headers: {'Content-Length': '176', 'Expires': 'Fri, 19 May 2017 16:44:56 GMT', 'Server': 'AkamaiGHost', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 19 May 2017 16:44:56 GMT', 'Content-Type': 'text/html', 'Mime-Version': '1.0'}. Content: '<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>\nAn error occurred while processing your request.<p>\nReference&#32;&#35;97&#46;5696f648&#46;1495212296&#46;102f6412\n</BODY></HTML>\n'
2017-05-19 16:44:56,647:DEBUG:acme.client:Received response <Response [504]> (headers: {'Content-Length': '176', 'Expires': 'Fri, 19 May 2017 16:44:56 GMT', 'Server': 'AkamaiGHost', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Fri, 19 May 2017 16:44:56 GMT', 'Content-Type': 'text/html', 'Mime-Version': '1.0'}): '<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>\nAn error occurred while processing your request.<p>\nReference&#32;&#35;97&#46;5696f648&#46;1495212296&#46;102f6412\n</BODY></HTML>\n'
2017-05-19 16:44:56,650:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 689, in obtain_cert
    le_client = _init_le_client(config, authenticator, installer)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 206, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 191, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 116, in register
    acme = acme_from_config_key(config, key)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 41, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 63, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 627, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 574, in _check_response
    raise errors.ClientError(response)
ClientError: <Response [504]>
```

**Comment by zjs** [comment]
This error is a result of an [ongoing service disruption](http://status.letsencrypt.org) with Let's Encrypt.

**Comment by crankwan** [comment]
@zjs It's OK now! 👍
