### ISSUE TITLE
Getting `An object does not implement interface` when calling `certbot renew`

### ISSUE THREAD

**Issue by aeisenberg** [certbot/certbot#4715]
I am unable to run renew on my domains and sub domains. My uninformed guess is that `certbot-auto` has updated and the renewal configuration is no longer valid. 

My domain is:

https://ganchrow.com/

I ran this command:

    certbot-auto renew --dry-run

It produced this output:

    -------------------------------------------------------------------------------
    Processing /etc/letsencrypt/renewal/ganchrow.com.conf
    -------------------------------------------------------------------------------
    Cert is due for renewal, auto-renewing...
    Attempting to renew cert from /etc/letsencrypt/renewal/ganchrow.com.conf produced an unexpected error: An object does not implement interface <InterfaceClass certbot.interfaces.IInstaller>

            . Skipping.

My operating system is (include version):

Ubuntu 16.04.2 LTS  3.13.0-108-generic

My web server is (include version):

nginx/1.10.0 (Ubuntu)

Cerbot version: 

certbot 0.14.1

I can login to a root shell on my machine (yes or no, or I don't know):

yep.

Here is the file contents `ganchrow.com.conf`:

    # renew_before_expiry = 30 days
    cert = /etc/letsencrypt/live/ganchrow.com/cert.pem
    privkey = /etc/letsencrypt/live/ganchrow.com/privkey.pem
    chain = /etc/letsencrypt/live/ganchrow.com/chain.pem
    fullchain = /etc/letsencrypt/live/ganchrow.com/fullchain.pem
    version = 0.12.0
    archive_dir = /etc/letsencrypt/archive/ganchrow.com

    # Options used in the renewal process
    [renewalparams]
    authenticator = webroot
    installer = webroot
    account = 75b3d80dce4eed74f9faa78cd4c62133
    rsa_key_size = 4096
    webroot_path = /usr/share/nginx/html,
    [[webroot_map]]
    ganchrow.com = /usr/share/nginx/html
    www.ganchrow.com = /usr/share/nginx/html

Here is a stack trace that is from the `letsencrypt.log`:

```
2017-05-23 13:44:13,938:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2017-06-15 13:04:00 UTC.
2017-05-23 13:44:13,942:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2017-05-23 13:44:13,963:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer webroot
2017-05-23 13:44:13,967:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/dev-2-baalmface.ganchrow.com.conf produced an unexpected error: An object does not implement interface <InterfaceClass certbot.interfaces.IInstaller>

        . Skipping.
2017-05-23 13:44:13,967:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/renewal.py", line 418, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 634, in renew_cert
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 187, in choose_configurator_plugins
    installer = pick_installer(config, req_inst, plugins)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 32, in pick_installer
    config, default, plugins, question, (interfaces.IInstaller,))
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 76, in pick_plugin
    verified = filtered.verify(ifaces)
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 234, in verify
    return self.filter(lambda p_ep: p_ep.verify(ifaces))
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 221, in filter
    in six.iteritems(self._plugins) if pred(plugin_ep)))
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 221, in <genexpr>
    in six.iteritems(self._plugins) if pred(plugin_ep)))
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 234, in <lambda>
    return self.filter(lambda p_ep: p_ep.verify(ifaces))
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 99, in verify
    zope.interface.verify.verifyObject(iface, self.init())
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/zope/interface/verify.py", line 105, in verifyObject
    return _verify(iface, candidate, tentative, vtype='o')
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/zope/interface/verify.py", line 50, in _verify
    raise DoesNotImplement(iface)
DoesNotImplement: An object does not implement interface <InterfaceClass certbot.interfaces.IInstaller>

```

Thanks for your help.

ps- I also posted this at [letsencrypt.org community support](https://community.letsencrypt.org/t/cannot-renew-cert-getting-an-object-does-not-implement-interface/34701), but I haven't had any response yet and so I am posting it here, too.

**Comment by bmw** [comment]
The problem is this line in `ganchrow.com.conf`:
```
installer = webroot
```
don't worry too much about the terminology (unless you're curious) but [webroot is not an installer](https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins). You should be able to work around this problem by simply deleting that line from your configuration file.

Did you manually edit that file to say `installer = webroot`? If not, if you have any information on the commands you ran to get Certbot into that state, I'd be very interested.

**Comment by aeisenberg** [comment]
Ahhh...thank you. that works. Apologies for the noise.

These files have been maintained by several people over the last few months. It is certainly possible that this was edited by hand.

**Comment by bmw** [comment]
No problem! Happy to help.
