### ISSUE TITLE
"couldn't get currently installed version" during renewal

### ISSUE THREAD

**Issue by dgdosen** [certbot/certbot#4766]
Hi all - I'm trying to renew some certs and have this error.  running `certbot-auto renw` - Is this enough to go on?

```
registrar@registry:~$ ./certbot-auto renew
Error: couldn't get currently installed version for /home/registrar/.local/share/letsencrypt/bin/letsencrypt:
Traceback (most recent call last):
  File "/home/registrar/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/home/registrar/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 13, in <module>
    from acme import jose
  File "/home/registrar/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/home/registrar/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/home/registrar/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/util.py", line 4, in <module>
    from cryptography.hazmat.primitives.asymmetric import rsa
  File "/home/registrar/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "/home/registrar/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/backends/__init__.py", line 7, in <module>
    import pkg_resources
  File "/home/registrar/.local/share/letsencrypt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 36, in <module>
    import plistlib
  File "/usr/lib/python2.7/plistlib.py", line 62, in <module>
    import datetime
ImportError: No module named datetime
```

**Comment by SwartzCr** [comment]
hm this is the same as #4776 so I'm going to close this as a duplicate - feel free to watch the other thread for more updates
