### ISSUE TITLE
Certbot tells me to choose a plugin when I already did

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#4858]
## My operating system is (include version):

Ubuntu 16.04 but this should be irrelevant.

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Dev instructions

## I ran this command and it produced this output:

```
certbot run --nginx
certbot rollback --configurator nginx --checkpoints 9001
Root logging level set at 10
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/home/bmw/src/certbot/certbot/main.py", line 743, in main
    return config.func(config, plugins)
  File "/home/bmw/src/certbot/certbot/main.py", line 516, in rollback
    client.rollback(config.installer, config.checkpoints, config, plugins)
  File "/home/bmw/src/certbot/certbot/client.py", line 614, in rollback
    config, default_installer, plugins, question="Which installer "
  File "/home/bmw/src/certbot/certbot/plugins/selection.py", line 32, in pick_installer
    config, default, plugins, question, (interfaces.IInstaller,))
  File "/home/bmw/src/certbot/certbot/plugins/selection.py", line 67, in pick_plugin
    "Missing command line flags. For non-interactive execution, "
MissingCommandlineFlag: Missing command line flags. For non-interactive execution, you will need to specify a plugin on the command line.  Run with '--help plugins' to see a list of options, and see https://eff.org/letsencrypt-plugins for more detail on what the plugins do and how to use them.
Please see the logfiles in /var/log/letsencrypt for more details.
```

## Certbot's behavior differed from what I expected because:
I told it the plugin I wanted with `--configurator`

cc @pde

**Comment by bmw** [comment]
`--nginx` doesn't work either.
