### ISSUE TITLE
Interrupted system call (SIGWINCH) stops renew with an error

### ISSUE THREAD

**Issue by JanWielemaker** [certbot/certbot#4871]
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Ubuntu 16.04

## I ran this command and it produced this output:

    certbot renew --dry-run

## Certbot's behavior differed from what I expected because:

Certbot stops with an error if I resize the terminal window while it is running.

## Here is a Certbot log showing the issue (if available):

```
Waiting for verification...
Attempting to renew cert from /etc/letsencrypt/renewal/swish.swi-prolog.org.conf produced an unexpected error: (4, 'Interrupted system call'). Skipping.
```

**Comment by SwartzCr** [comment]
Weird @JanWielemaker what version of certbot are you running?
Can you attach a full log of this? Logs are located in `/var/log/letsencrypt`

**Comment by JanWielemaker** [comment]
The official PPA for Ubuntu 16.04.  Attached is the relevant part of the log.  It is easy to reproduce: simply do `certbot renew --dry-run` and while this is working resize the terminal (gnome terminal).   Of course it is not really a big thing.  Certbot is doing what it is supposed to do for me as long as I'm not impatient :)

```
2017-06-25 14:17:27,951:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/swish.swi-prolog.org.conf
 produced an unexpected error: (4, 'Interrupted system call'). Skipping.
2017-06-25 14:17:28,031:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 418, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 640, in renew_cert
    _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 77, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 296, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 313, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 81, in get_authorizations
    self._respond(resp, best_effort)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 134, in _respond
    resp, chall_update)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 158, in _send_responses
    self.acme.answer_challenge(achall.challb, resp)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 229, in answer_challenge
    response = self.net.post(challb.uri, response)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 674, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 685, in _post_once
    response = self._send_request('POST', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 619, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 246, in recv
    [self.socket], [], [], self.socket.gettimeout())
error: (4, 'Interrupted system call')
```

**Comment by hlieberman** [comment]
This is Debian bug #867768 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867768).

**Comment by SwartzCr** [comment]
Ah I pinged @erikrose in the linked issue, but it seems like it's the same as this bug?https://stackoverflow.com/questions/19348236/ncurses-interrupts-system-call-when-resizing-terminal
I'd think we could catch and ignore the ncurses error, but I'd like it if someone who knew more about ncurses could weigh in on it.
I'm going to tag @bmw as well so that he can take a look at it if Erik doesn't get around to it - since these issues have been open for almost a month.

**Comment by hlieberman** [comment]
On Mon, Aug 7, 2017 at 14:46 Brad Warren <notifications@github.com> wrote:

> I think the bug for this upstream is shazow/urllib3#700
> <https://github.com/shazow/urllib3/issues/700> which was fixed in urllib3
> 1.20.
>

1.21 is in sid and making its way to testing. When it gets there, we can
talk to DPMT about putting it into backports.
-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by bmw** [comment]
This issue has been resolved.
