### ISSUE TITLE
certbot fails with " we only support configurations with one vhost per file" if there's no trailing line break in the virtualhost.conf

### ISSUE THREAD

**Issue by nohn** [certbot/certbot#4878]
## My operating system is (include version):

Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

OS package manager

## I ran this command and it produced this output:

`letsencrypt --debug`

```
Error: should only be one vhost in  /etc/apache2/sites-available/example.conf           

Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 666, in run
    lineage.chain, lineage.fullchain)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 355, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 214, in deploy_cert
    vhost = self.choose_vhost(domain)
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 308, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 723, in make_vhost_ssl
    raise errors.PluginError("Currently, we only support "
PluginError: Currently, we only support configurations with one vhost per file
```

## Certbot's behavior differed from what I expected because:

I have only one vhost in example.conf

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2017-06-27 12:06:41,032:DEBUG:letsencrypt.cli:Root logging level set at 30
2017-06-27 12:06:41,033:INFO:letsencrypt.cli:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-06-27 12:06:41,033:DEBUG:letsencrypt.cli:letsencrypt version: 0.4.1
2017-06-27 12:06:41,033:DEBUG:letsencrypt.cli:Arguments: ['--debug']
2017-06-27 12:06:41,036:DEBUG:letsencrypt.cli:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2017-06-27 12:06:41,041:DEBUG:letsencrypt.cli:Requested authenticator None and installer None
2017-06-27 12:06:41,394:DEBUG:letsencrypt.display.ops:Single candidate plugin: * apache
Description: Apache Web Server - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = letsencrypt_apache.configurator:ApacheConfigurator
Initialized: <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7f0907dfac90>
Prep: True
2017-06-27 12:06:41,396:DEBUG:letsencrypt.cli:Selected authenticator <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7f0907dfac90> and installer <letsencrypt_apache.configurator.ApacheConfigurator object at 0x7f0907dfac90>
2017-06-27 12:06:44,785:DEBUG:letsencrypt.cli:Picked account: <Account(5f0ddcf80dde34465daf347267daaa8c)>
2017-06-27 12:06:44,786:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2017-06-27 12:06:44,790:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-06-27 12:06:45,015:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 280
2017-06-27 12:06:45,018:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '280', 'Expires': 'Tue, 27 Jun 2017 12:06:45 GMT', 'Boulder-Request-Id': 'nbK-7iqiSDVIkNrtIdOHF1kSfQLYaHf9EfazyU9vS6U', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 27 Jun 2017 12:06:45 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'k2aLCrHRkEgBdjOuMDtoYSxQQRSufTqLMoRj0IlNdGI'}. Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2017-06-27 12:06:45,018:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '280', 'Expires': 'Tue, 27 Jun 2017 12:06:45 GMT', 'Boulder-Request-Id': 'nbK-7iqiSDVIkNrtIdOHF1kSfQLYaHf9EfazyU9vS6U', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Tue, 27 Jun 2017 12:06:45 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'k2aLCrHRkEgBdjOuMDtoYSxQQRSufTqLMoRj0IlNdGI'}): '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2017-06-27 12:06:45,023:DEBUG:parsedatetime:parse (top of loop): [30 days][]
2017-06-27 12:06:45,029:DEBUG:parsedatetime:CRE_UNITS matched
2017-06-27 12:06:45,030:DEBUG:parsedatetime:parse (bottom) [][30 days][][]
2017-06-27 12:06:45,030:DEBUG:parsedatetime:weekday False, dateStd False, dateStr False, time False, timeStr False, meridian False
2017-06-27 12:06:45,030:DEBUG:parsedatetime:dayStr False, modifier False, modifier2 False, units True, qunits False
2017-06-27 12:06:45,030:DEBUG:parsedatetime:_evalString(30 days, time.struct_time(tm_year=2017, tm_mon=6, tm_mday=27, tm_hour=12, tm_min=6, tm_sec=45, tm_wday=1, tm_yday=178, tm_isdst=0))
2017-06-27 12:06:45,030:DEBUG:parsedatetime:_buildTime: [30 ][][days]
2017-06-27 12:06:45,030:DEBUG:parsedatetime:units days --> realunit days
2017-06-27 12:06:45,030:DEBUG:parsedatetime:return
2017-06-27 12:06:45,030:INFO:letsencrypt.cli:Cert not yet due for renewal
2017-06-27 12:06:45,924:ERROR:letsencrypt_apache.configurator:Error: should only be one vhost in /etc/apache2/sites-available/www.example.com.conf
2017-06-27 12:06:45,935:DEBUG:letsencrypt.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 355, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 214, in deploy_cert
    vhost = self.choose_vhost(domain)
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 308, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 723, in make_vhost_ssl
    raise errors.PluginError("Currently, we only support "
PluginError: Currently, we only support configurations with one vhost per file

2017-06-27 12:06:45,936:DEBUG:letsencrypt.error_handler:Calling registered functions
2017-06-27 12:06:45,937:DEBUG:letsencrypt.cli:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 9, in <module>
    load_entry_point('letsencrypt==0.4.1', 'console_scripts', 'letsencrypt')()
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 1986, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/cli.py", line 666, in run
    lineage.chain, lineage.fullchain)
  File "/usr/lib/python2.7/dist-packages/letsencrypt/client.py", line 355, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 214, in deploy_cert
    vhost = self.choose_vhost(domain)
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 308, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/usr/lib/python2.7/dist-packages/letsencrypt_apache/configurator.py", line 723, in make_vhost_ssl
    raise errors.PluginError("Currently, we only support "
PluginError: Currently, we only support configurations with one vhost per file
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
cat  /etc/apache2/sites-available/example.com.conf 
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        ServerName www.example.com
        ServerAlias example.com

        ServerAdmin webmaster@example.com
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        Redirect 301 / https://www.example.com/en
    
        ErrorLog /error.log
        CustomLog /access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet  
```
<= no trailing linebreak

If I add the trailing line break, everything works as expected.

**Comment by SwartzCr** [comment]
Hi @nohn 
It looks like you have a very old version of let's encrypt. It should now be called certbot and you can get a newer version for your OS from a PPA. You can find instructions on how to do so here: https://certbot.eff.org/#ubuntuxenial-apache
Let me know if that fixes your problem!
