### ISSUE TITLE
Certbot fails with "TypeError: tuple indices must be integers, not str"

### ISSUE THREAD

**Issue by mxbi** [certbot/certbot#4884]
## My operating system is (include version):

Ubuntu Server Trusty 14.04 (DigitalOcean), Python 2.7.6 (Also tried with Python 3.5.3)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

apt - version is certbot 0.14.2

## I ran this command and it produced this output:

```
root@[SERVER]:~# certbot certonly
Saving debug log to /var/log/letsencrypt/letsencrypt.log

How would you like to authenticate with the ACME CA?
-------------------------------------------------------------------------------
1: Spin up a temporary webserver (standalone)
2: Place files in webroot directory (webroot)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
Please enter in your domain name(s) (comma and/or space separated)  (Enter 'c'
to cancel):[SERVER_DOMAIN]
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for [SERVER_DOMAIN]
Waiting for verification...
Cleaning up challenges
An unexpected error occurred:
TypeError: tuple indices must be integers, not str
Please see the logfiles in /var/log/letsencrypt for more details.

```

## Certbot's behavior differed from what I expected because:

The program terminated before SSL keys were saved. However, I think they were successfully generated, because after a few attempts I am told that I have maxed out the number of SSL certificates I can have (paraphrasing the error, this was a few weeks ago)

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

This is the end of the latest log:

```
2017-06-28 19:09:27,950:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-cert HTTP/1.1" 201 1277
2017-06-28 19:09:27,952:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Content-Type: application/pkix-cert
Content-Length: 1277
Boulder-Request-Id: b6WofTnJc8Fgo2MK5r7FUgvOcfqohVkdF9BTIoEUAmw
Boulder-Requester: 14438887
Link: <https://acme-v01.api.letsencrypt.org/acme/issuer-cert>;rel="up"
Location: https://acme-v01.api.letsencrypt.org/acme/cert/04a7dc1ff[REDACTED]
Replay-Nonce: EqkiVg[REDACTED_NONCE]
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Wed, 28 Jun 2017 19:09:27 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 28 Jun 2017 19:09:27 GMT
Connection: keep-alive

MIIE+TCCA+GgAwIBAgISBKfcH/[REDACTED, looks like a key]

2017-06-28 19:09:27,952:DEBUG:acme.client:Storing nonce: EqkiVg[REDACTED_NONCE]
2017-06-28 19:09:27,963:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.14.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 742, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 682, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 82, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 344, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 323, in obtain_certificate
    domains, csr, authzr=authzr)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 273, in obtain_certificate_from_csr
    authzr)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 313, in request_issuance
    headers={'Accept': content_type})
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 674, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 687, in _post_once
    return self._check_response(response, content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 563, in _check_response
    jobj = response.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 850, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 810, in text
    encoding = self.apparent_encoding
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 680, in apparent_encoding
    return chardet.detect(self.content)['encoding']
  File "/usr/local/lib/python2.7/dist-packages/chardet/__init__.py", line 24, in detect
    u.feed(aBuf)
  File "/usr/local/lib/python2.7/dist-packages/chardet/universaldetector.py", line 116, in feed
    if prober.feed(aBuf) == constants.eFoundIt:
  File "/usr/local/lib/python2.7/dist-packages/chardet/charsetgroupprober.py", line 60, in feed
    st = prober.feed(aBuf)
  File "/usr/local/lib/python2.7/dist-packages/chardet/utf8prober.py", line 53, in feed
    codingState = self._mCodingSM.next_state(c)
  File "/usr/local/lib/python2.7/dist-packages/chardet/codingstatemachine.py", line 44, in next_state
    byteCls = self._mModel['classTable'][c]
TypeError: tuple indices must be integers, not str
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

I am trying to use standalone certbot, so I'm not sure if there is anything relevant to put here.

Any help would be very much appreciated!

**Comment by mxbi** [comment]
I was able to make it work by pointing another the domain to another server and using that server (Ubuntu 16.04, Python 2.7.12) to generate the certificate. Obviously this was just a workaround so I am still looking for a solution to this issue.

**Comment by SwartzCr** [comment]
My guess is that certbot thinks it's getting a response from the let's encrypt server that is a json blob, but it's actually getting back an error with a website inside of it, which is then causing a parsing error.
In order to debug, you could try to run certbot with --debug and then navigate to the challenge page once it's loaded and see what you get. If you get the nginx challenge you're fine, but if you get some sort of 404 or default page that could be a problem.

**Comment by SwartzCr** [comment]
@mxbi have you had any luck getting it to work?

**Comment by mxbi** [comment]
@SwartzCr Unfortunately not - I just tried it again now that the old cert has expired, and I get the same error. Could you elaborate on running it with `--debug`? I tried it, however the behaviour is the same (it crashes with the error immediately after saying "Cleaning up challenges". How am I supposed to navigate to the challenge page?

I also tried updating all python packages and updating Python to 2.7.14, to no avail.

**Comment by bmw** [comment]
Just dug into this a bit. What's going on is [here](https://github.com/certbot/certbot/blob/95a7d4585619d612ff28ac24dac4faefaee59e72/acme/acme/client.py#L569) we try to parse every response from the ACME server like it contains JSON with a `try` and `except` block around it to catch any errors if that fails. It seems like you're encountering a different error type than the one being caught, causing Certbot to crash.

Presumably, landing a PR to change that line to `except Exception:  # pylint: disable=broad-except` should fix the problem.

**Comment by joohoi** [comment]
Closing this as I think it's outdated. If the problem still exists, please let me know and I'll reopen the issue.
