### ISSUE TITLE
OPENSSL_sk_num error when creating certificates

### ISSUE THREAD

**Issue by creepersbane** [certbot/certbot#4901]
## My operating system is (include version):
Raspbian 8 (Debian Jessie), Linux 4.4.27-v7+

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output (all dependencies are installed):
pi@raspberrypi:~/certbot $ ./certbot-auto --apache --no-bootstrap

Error: couldn't get currently installed version for /home/pi/.local/share/letsencrypt/bin/letsencrypt:
Traceback (most recent call last):
  File "/home/pi/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 9, in <module>
    from acme import jose
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 12, in <odule>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol OPENSSL_sk_num
pi@raspberrypi:~/certbot $

## Certbot's behavior differed from what I expected because:
It is not supposed to crash

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
Certbot did not run long enough for letsencrypt to be installed

**Comment by SwartzCr** [comment]
Hi @creepersbane, have you tried installing it via jessie backports? https://certbot.eff.org/#debianjessie-apache
Let me know if that fixes your problem!

**Comment by creepersbane** [comment]
Tried to update apt-get to use backports

pi@raspberrypi:~ $ sudo apt-get update
Hit http://apt.adafruit.com jessie InRelease
Hit http://mirrordirector.raspbian.org jessie InRelease
Get:1 http://archive.raspbian.org jessie InRelease [14.9 kB]
Get:2 http://archive.raspberrypi.org jessie InRelease [22.9 kB]
Get:3 http://ftp.debian.org jessie-backports InRelease [166 kB]
Hit http://apt.adafruit.com jessie/main armhf Packages
Ign http://apt.adafruit.com jessie/main Translation-en_GB
Ign http://apt.adafruit.com jessie/main Translation-en
Get:4 http://archive.raspberrypi.org jessie/main Sources [54.9 kB]
Get:5 http://archive.raspbian.org jessie/main Sources [7,754 kB]
Ign http://ftp.debian.org jessie-backports InRelease
Get:6 http://archive.raspberrypi.org jessie/main armhf Packages [168 kB]
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages
Get:7 http://ftp.debian.org jessie-backports/main Translation-en [630 kB]
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Get:8 http://ftp.debian.org jessie-backports/main armhf Packages [876 kB]
Get:9 http://archive.raspberrypi.org jessie/ui Sources [17.4 kB]
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Ign http://ftp.debian.org jessie-backports/main Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Get:10 http://archive.raspbian.org jessie/contrib Sources [64.5 kB]
Get:11 http://archive.raspbian.org jessie/non-free Sources [113 kB]
Get:12 http://archive.raspbian.org jessie/rpi Sources [1,132 B]
Fetched 9,883 kB in 28s (346 kB/s)
Reading package lists... Done
W: GPG error: http://ftp.debian.org jessie-backports InRelease: The following si                                                  gnatures couldn't be verified because the public key is not available: NO_PUBKEY                                                   8B48AD6246925553 NO_PUBKEY 7638D0442B90D010

**Comment by creepersbane** [comment]
I got it installed, but now it says:

pi@raspberrypi:~ $ sudo certbot --apache
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 7, in <module>
    from certbot.main import main
  File "/usr/local/lib/python2.7/dist-packages/certbot/main.py", line 9, in <module>
    from acme import jose
  File "/usr/local/lib/python2.7/dist-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/usr/local/lib/python2.7/dist-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/usr/local/lib/python2.7/dist-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /usr/local/lib/python2.7/dist-packages/cryptography/hazmat/bindings/_openssl.so: undefined symbol: d2i_DHxparams
pi@raspberrypi:~ $

**Comment by kraftbj** [comment]
I encountered a similar issue

<details><summary>My error output</summary>kraft@tex:~/letsencrypt$ ./letsencrypt-auto
Error: couldn't get currently installed version for /home/kraft/.local/share/letsencrypt/bin/letsencrypt:
Traceback (most recent call last):
  File "/home/kraft/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/home/kraft/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 9, in <module>
    from acme import jose
  File "/home/kraft/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/home/kraft/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/home/kraft/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/home/kraft/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/kraft/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/kraft/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/kraft/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: libssl.so.1.0.2: cannot open shared object file: No such file or directory</details>

On Ubuntu 16.04.2 LTS, which now ships OpenSSL 1.1.0. Downgrading to 1.0 resolved it.

**Comment by creepersbane** [comment]
@kraftbj It seems that the shared object was just out of place for you. For me, the object exists, but cannot be used for some reason.

**Comment by fyfe** [comment]
This maybe related to this issue (pyca/cryptography#3693) with [cryptography](https://github.com/pyca/cryptography) if you have multiple versions of SSL installed it could be using the headers from one version and the libraries from another.

Try installing cryptography using the following command adjusting the paths to the location where openssl/libressl is installed
`pip install --global-option=build_ext --global-option="-I/usr/local/include/" --global-option="-L/usr/local/lib" cryptography`

**Comment by SwartzCr** [comment]
@creepersbane you could try @fyfe's suggestion, but it's also true that certain versions of certbot require certain versions of OpenSSL.
Since python cryptography compiles itself against the system package of python cryptography it comes with specific calls into the cryptography API, based on the version it expects. If cryptography has changed those APIs then it's possible that it'll try calling ones that either don't exist or that have changed name/location. So while you may have OpenSSL - if it's the wrong version for your version of cryptography it could still fail due to the version mismatch.
Let me know once you've tried a few of debugging ideas and let me know how it goes!

**Comment by lsycxyj** [comment]
So any solutions?

**Comment by creepersbane** [comment]
@lsycxyj still haven't tried. My server is unavailable until Monday

**Comment by creepersbane** [comment]
Well, this was fixed with my other issue report, so I'll be closing this.
