### ISSUE TITLE
SSLError while communicating with acme-v01.api.letsencrypt.org

### ISSUE THREAD

**Issue by MrKich** [certbot/certbot#4933]
## My operating system is (include version):
Ubuntu 14.04.5 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt-get install certbot
(OS package manager from PPA certbot/certbot)

## I ran this command and it produced this output:
```
$ sudo certbot certonly --webroot -w /home/www/drupal/ -d www.example.com 
[sudo] password for user: 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Enter email address (used for urgent renewal and security notices) (Enter 'c' to
cancel):mail@yandex.ru
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
An unexpected error occurred:
SSLError: [Errno bad handshake] 
Please see the logfiles in /var/log/letsencrypt for more details.
```

## Certbot's behavior differed from what I expected because:
It cannot verify acme's own certificate.

## Here is a Certbot log showing the issue:
```
2017-07-15 06:08:11,327:DEBUG:certbot.main:certbot version: 0.14.2
2017-07-15 06:08:11,327:DEBUG:certbot.main:Arguments: ['--webroot', '-w', '/home/www/drupal/', '-d', 'www.example.com']
2017-07-15 06:08:11,327:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-07-15 06:08:11,338:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer <certbot.cli._Default object at 0x7f7da901c6d0>
2017-07-15 06:08:11,338:DEBUG:certbot.cli:Default Detector is Namespace(account=<certbot.cli._Default object at 0x7f7da9007d50>, agree_dev_preview=None, allow_subset_of_names=<certbot.cli._Default object at 0x7f7da900f690>, apache=<certbot.cli._Default object at 0x7f7da901c9d0>, authenticator='webroot', break_my_certs=<certbot.cli._Default object at 0x7f7da8ff9a50>, cert_path=<certbot.cli._Default object at 0x7f7da9019e90>, certname=<certbot.cli._Default object at 0x7f7da900fad0>, chain_path=<certbot.cli._Default object at 0x7f7da901c1d0>, checkpoints=<certbot.cli._Default object at 0x7f7da9019990>, config_dir=<certbot.cli._Default object at 0x7f7da901c2d0>, config_file=None, configurator=<certbot.cli._Default object at 0x7f7da901c6d0>, csr=<certbot.cli._Default object at 0x7f7da9019790>, debug=<certbot.cli._Default object at 0x7f7da9007210>, debug_challenges=<certbot.cli._Default object at 0x7f7da9007090>, dialog=None, domains='www.example.com', dry_run=<certbot.cli._Default object at 0x7f7da900fbd0>, duplicate=<certbot.cli._Default object at 0x7f7da9007bd0>, eff_email=<certbot.cli._Default object at 0x7f7da900ffd0>, email=<certbot.cli._Default object at 0x7f7da900fed0>, expand=<certbot.cli._Default object at 0x7f7da900fd50>, force_interactive=<certbot.cli._Default object at 0x7f7da900f8d0>, fullchain_path=<certbot.cli._Default object at 0x7f7da901c0d0>, func=<function certonly at 0x7f7da92946e0>, hsts=<certbot.cli._Default object at 0x7f7da8ff9050>, http01_port=<certbot.cli._Default object at 0x7f7da8ff9bd0>, ifaces=<certbot.cli._Default object at 0x7f7da9019c90>, init=<certbot.cli._Default object at 0x7f7da9019a90>, installer=<certbot.cli._Default object at 0x7f7da901c6d0>, key_path=<certbot.cli._Default object at 0x7f7da9019f90>, logs_dir=<certbot.cli._Default object at 0x7f7da901c4d0>, manual=<certbot.cli._Default object at 0x7f7da901ccd0>, manual_auth_hook=<certbot.cli._Default object at 0x7f7da901cf10>, manual_cleanup_hook=<certbot.cli._Default object at 0x7f7da8fa1090>, manual_public_ip_logging_ok=<certbot.cli._Default object at 0x7f7da8fa1190>, must_staple=<certbot.cli._Default object at 0x7f7da8ff9750>, nginx=<certbot.cli._Default object at 0x7f7da901cad0>, no_bootstrap=<certbot.cli._Default object at 0x7f7da9007690>, no_self_upgrade=<certbot.cli._Default object at 0x7f7da9007810>, no_verify_ssl=<certbot.cli._Default object at 0x7f7da8ff9ed0>, noninteractive_mode=<certbot.cli._Default object at 0x7f7da900f7d0>, num=<certbot.cli._Default object at 0x7f7da9019590>, os_packages_only=<certbot.cli._Default object at 0x7f7da90079d0>, post_hook=<certbot.cli._Default object at 0x7f7da8ff7e90>, pre_hook=<certbot.cli._Default object at 0x7f7da8ff7c50>, pref_challs=<certbot.cli._Default object at 0x7f7da8ff79d0>, prepare=<certbot.cli._Default object at 0x7f7da9019b90>, quiet=<certbot.cli._Default object at 0x7f7da9007510>, reason=<certbot.cli._Default object at 0x7f7da9019890>, redirect=<certbot.cli._Default object at 0x7f7da8ff9590>, register_unsafely_without_email=<certbot.cli._Default object at 0x7f7da900fcd0>, reinstall=<certbot.cli._Default object at 0x7f7da900ff50>, renew_by_default=<certbot.cli._Default object at 0x7f7da900fa90>, renew_hook=<certbot.cli._Default object at 0x7f7da9019210>, renew_with_new_domains=<certbot.cli._Default object at 0x7f7da900f890>, rsa_key_size=<certbot.cli._Default object at 0x7f7da8ff98d0>, server=<certbot.cli._Default object at 0x7f7da901c5d0>, staging=<certbot.cli._Default object at 0x7f7da9007390>, standalone=<certbot.cli._Default object at 0x7f7da901cbd0>, standalone_supported_challenges=<certbot.cli._Default object at 0x7f7da8fa12d0>, staple=<certbot.cli._Default object at 0x7f7da8ff7310>, strict_permissions=<certbot.cli._Default object at 0x7f7da8ff7790>, text_mode=<certbot.cli._Default object at 0x7f7da900f6d0>, tls_sni_01_port=<certbot.cli._Default object at 0x7f7da8ff9d50>, tos=<certbot.cli._Default object at 0x7f7da900f090>, uir=<certbot.cli._Default object at 0x7f7da8ffed90>, update_registration=<certbot.cli._Default object at 0x7f7da900fdd0>, user_agent=<certbot.cli._Default object at 0x7f7da9019690>, validate_hooks=<certbot.cli._Default object at 0x7f7da9019310>, verb='certonly', verbose_count=<certbot.cli._Default object at 0x7f7da900f290>, webroot=True, webroot_map=<certbot.cli._Default object at 0x7f7da8fa14d0>, webroot_path='/home/www/drupal/', work_dir=<certbot.cli._Default object at 0x7f7da901c3d0>)
2017-07-15 06:08:11,346:DEBUG:certbot.log:Root logging level set at 20
2017-07-15 06:08:11,346:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-07-15 06:08:11,347:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2017-07-15 06:08:11,347:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f7da901cf90>
Prep: True
2017-07-15 06:08:11,347:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7f7da901cf90> and installer None
2017-07-15 06:08:21,530:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-07-15 06:08:21,595:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-07-15 06:08:21,715:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.14.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 742, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 666, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 382, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 367, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 158, in register
    acme = acme_from_config_key(config, key)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 44, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 71, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 646, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 619, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 331, in send
    raise SSLError(e)
SSLError: [Errno bad handshake]
```
### Python 2.7.6
```
>>> import requests
>>> requests.get("https://acme-v01.api.letsencrypt.org")
<Response [200]>
```

### Openssl
`echo | openssl s_client -connect acme-v01.api.letsencrypt.org:443`

```
CONNECTED(00000003)
---
Certificate chain
 0 s:/CN=*.api.letsencrypt.org/O=INTERNET SECURITY RESEARCH GROUP/L=Mountain View/ST=California/C=US
   i:/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
 1 s:/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
   i:/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
 2 s:/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHDzCCBfegAwIBAgIQfwAAAQAAAU4w1QtkQskueDANBgkqhkiG9w0BAQsFADBa
MQswCQYDVQQGEwJVUzESMBAGA1UEChMJSWRlblRydXN0MRcwFQYDVQQLEw5UcnVz
dElEIFNlcnZlcjEeMBwGA1UEAxMVVHJ1c3RJRCBTZXJ2ZXIgQ0EgQTUyMB4XDTE1
MDYyNjE3MDU0NVoXDTE4MDYyNTE3MDU0NVowgYUxHjAcBgNVBAMTFSouYXBpLmxl
dHNlbmNyeXB0Lm9yZzEpMCcGA1UEChMgSU5URVJORVQgU0VDVVJJVFkgUkVTRUFS
Q0ggR1JPVVAxFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxEzARBgNVBAgTCkNhbGlm
b3JuaWExCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEAlkLBpvVuOTZrpaPkzmAx+5OcK6gffKPon8E6ktJmNsjfrh3ATdgKt121ccD+
7I3gBcZu5euG1ldynO/wx29oeGhBiiWx9Bkm1brFKDLvH56ztO29xEo5ZQnxV7w0
25NvjBca5J2tRiAIjcdjMITE1usp5rrNLNM2LIs1RutP7bexvuNv2dGyJ0uNIWI4
Ym2Tt5rnUTx7Vsz0M4nz2i6sSB9ajrSa1h4hFrZYqIU/zpl20f7So8oZDYCZN4WY
xYgbUuEneWxFigElkJbNk0UeVN26tdMGHdIWCabgoZSy80X+pFvxCgdbLQzS0LXQ
orqkGsMYO0+fjjmLj0742IHYswIDAQABo4IDozCCA58wDgYDVR0PAQH/BAQDAgWg
MIICJwYDVR0gBIICHjCCAhowggELBgpghkgBhvkvAAYDMIH8MEAGCCsGAQUFBwIB
FjRodHRwczovL3NlY3VyZS5pZGVudHJ1c3QuY29tL2NlcnRpZmljYXRlcy9wb2xp
Y3kvdHMvMIG3BggrBgEFBQcCAjCBqhqBp1RoaXMgVHJ1c3RJRCBTZXJ2ZXIgQ2Vy
dGlmaWNhdGUgaGFzIGJlZW4gaXNzdWVkIGluIGFjY29yZGFuY2Ugd2l0aCBJZGVu
VHJ1c3QncyBUcnVzdElEIENlcnRpZmljYXRlIFBvbGljeSBmb3VuZCBhdCBodHRw
czovL3NlY3VyZS5pZGVudHJ1c3QuY29tL2NlcnRpZmljYXRlcy9wb2xpY3kvdHMv
MIIBBwYGZ4EMAQICMIH8MEAGCCsGAQUFBwIBFjRodHRwczovL3NlY3VyZS5pZGVu
dHJ1c3QuY29tL2NlcnRpZmljYXRlcy9wb2xpY3kvdHMvMIG3BggrBgEFBQcCAjCB
qhqBp1RoaXMgVHJ1c3RJRCBTZXJ2ZXIgQ2VydGlmaWNhdGUgaGFzIGJlZW4gaXNz
dWVkIGluIGFjY29yZGFuY2Ugd2l0aCBJZGVuVHJ1c3QncyBUcnVzdElEIENlcnRp
ZmljYXRlIFBvbGljeSBmb3VuZCBhdCBodHRwczovL3NlY3VyZS5pZGVudHJ1c3Qu
Y29tL2NlcnRpZmljYXRlcy9wb2xpY3kvdHMvMB0GA1UdDgQWBBQvAQatcXq62MSt
v2WLHPKwErqzgDBFBgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vdmFsaWRhdGlvbi5p
ZGVudHJ1c3QuY29tL2NybC90cnVzdGlkY2FhNTIuY3JsMIGEBggrBgEFBQcBAQR4
MHYwMAYIKwYBBQUHMAGGJGh0dHA6Ly9jb21tZXJjaWFsLm9jc3AuaWRlbnRydXN0
LmNvbTBCBggrBgEFBQcwAoY2aHR0cDovL3ZhbGlkYXRpb24uaWRlbnRydXN0LmNv
bS9jZXJ0cy90cnVzdGlkY2FhNTIucDdjMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
BgEFBQcDAjAfBgNVHSMEGDAWgBSiViQ80NQVuei/eKMTEFhILhZU4TA1BgNVHREE
LjAsghUqLmFwaS5sZXRzZW5jcnlwdC5vcmeCE2FwaS5sZXRzZW5jcnlwdC5vcmcw
DQYJKoZIhvcNAQELBQADggEBAIgV29HRYYk2RfrkE6KOeAT6K3AJsKgNe+i9Pdo7
YLdiDGMv/kKyyTNsq4l8IEaY1kw3aqkyT44D8vp6yGbbNl1uAE4VnaPeChLOBK0G
xz3CjtoZPqLxmieft8jybIVWZKZlIIsZrSMaEvrmRTGYartBSuxqOzIjCNxvkkRt
MYDNYRhiy6NPMtA0kpDQCN6tOggXdCm19kmzKI8pUvQGCnGscXJvlQIeaZva0GWf
UOuPael/zohUUsm2lJowlIli939RdxUal0hwv8tD12qAyZAF2/+4y61ds4svGD9B
ukNnsAzS3EXNqq5qWFqRQyiTZfCcjaXEdtySyNAUiM6eFTY=
-----END CERTIFICATE-----
subject=/CN=*.api.letsencrypt.org/O=INTERNET SECURITY RESEARCH GROUP/L=Mountain View/ST=California/C=US
issuer=/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
---
No client certificate CA names sent
---
SSL handshake has read 5917 bytes and written 421 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 346DA87C365EECEEFB206FEAAA9FB22D261985208AD08FEE5D7CCB0811A54D37
    Session-ID-ctx: 
    Master-Key: 6473B9677741DF9219948BA74778BCC4B9150E642A5A892BF56B8D5577A8866E5BC475EBB720830E833332A74DE68AD1
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 00 00 03 d5 0b 1e 61 89-7e 71 d7 7a 22 81 94 3f   ......a.~q.z"..?
    0010 - 52 6a 8a 7f d1 bb 59 da-49 0b 66 32 fb 66 0d 3e   Rj....Y.I.f2.f.>
    0020 - 3e ff 31 43 40 f0 d3 4e-3f aa 06 ce 93 52 7d 89   >.1C@..N?....R}.
    0030 - 92 d0 69 29 da 90 66 64-d6 4b 6b de e8 c3 51 d3   ..i)..fd.Kk...Q.
    0040 - 12 f2 91 1d 9f 85 c5 db-8b d7 b0 5a 36 58 02 85   ...........Z6X..
    0050 - ae 0d 56 72 36 af 47 3c-87 71 8b ac df 53 cc 7f   ..Vr6.G<.q...S..
    0060 - b4 d9 f3 a9 e6 21 a9 1d-61 61 07 92 a1 2e a1 84   .....!..aa......
    0070 - 43 15 c1 2e be 7c 05 3a-c9 55 4c 9d 77 3b 30 a0   C....|.:.UL.w;0.
    0080 - 13 b9 e5 c5 e7 de 31 97-f8 98 33 70 e1 e2 37 e7   ......1...3p..7.
    0090 - 63 a6 7a 08 fc bb 5b b3-f6 c0 eb 6b c3 6c a4 54   c.z...[....k.l.T

    Start Time: 1500103122
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
```

`echo | openssl s_client -connect acme-v01.api.letsencrypt.org:443 -CAfile /etc/ssl/certs/ca-certificates.crt`

```
CONNECTED(00000003)
---
Certificate chain
 0 s:/CN=*.api.letsencrypt.org/O=INTERNET SECURITY RESEARCH GROUP/L=Mountain View/ST=California/C=US
   i:/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
 1 s:/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
   i:/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
 2 s:/C=US/O=IdenTrust/CN=IdenTrust Commercial Root CA 1
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIHDzCCBfegAwIBAgIQfwAAAQAAAU4w1QtkQskueDANBgkqhkiG9w0BAQsFADBa
MQswCQYDVQQGEwJVUzESMBAGA1UEChMJSWRlblRydXN0MRcwFQYDVQQLEw5UcnVz
dElEIFNlcnZlcjEeMBwGA1UEAxMVVHJ1c3RJRCBTZXJ2ZXIgQ0EgQTUyMB4XDTE1
MDYyNjE3MDU0NVoXDTE4MDYyNTE3MDU0NVowgYUxHjAcBgNVBAMTFSouYXBpLmxl
dHNlbmNyeXB0Lm9yZzEpMCcGA1UEChMgSU5URVJORVQgU0VDVVJJVFkgUkVTRUFS
Q0ggR1JPVVAxFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxEzARBgNVBAgTCkNhbGlm
b3JuaWExCzAJBgNVBAYTAlVTMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEAlkLBpvVuOTZrpaPkzmAx+5OcK6gffKPon8E6ktJmNsjfrh3ATdgKt121ccD+
7I3gBcZu5euG1ldynO/wx29oeGhBiiWx9Bkm1brFKDLvH56ztO29xEo5ZQnxV7w0
25NvjBca5J2tRiAIjcdjMITE1usp5rrNLNM2LIs1RutP7bexvuNv2dGyJ0uNIWI4
Ym2Tt5rnUTx7Vsz0M4nz2i6sSB9ajrSa1h4hFrZYqIU/zpl20f7So8oZDYCZN4WY
xYgbUuEneWxFigElkJbNk0UeVN26tdMGHdIWCabgoZSy80X+pFvxCgdbLQzS0LXQ
orqkGsMYO0+fjjmLj0742IHYswIDAQABo4IDozCCA58wDgYDVR0PAQH/BAQDAgWg
MIICJwYDVR0gBIICHjCCAhowggELBgpghkgBhvkvAAYDMIH8MEAGCCsGAQUFBwIB
FjRodHRwczovL3NlY3VyZS5pZGVudHJ1c3QuY29tL2NlcnRpZmljYXRlcy9wb2xp
Y3kvdHMvMIG3BggrBgEFBQcCAjCBqhqBp1RoaXMgVHJ1c3RJRCBTZXJ2ZXIgQ2Vy
dGlmaWNhdGUgaGFzIGJlZW4gaXNzdWVkIGluIGFjY29yZGFuY2Ugd2l0aCBJZGVu
VHJ1c3QncyBUcnVzdElEIENlcnRpZmljYXRlIFBvbGljeSBmb3VuZCBhdCBodHRw
czovL3NlY3VyZS5pZGVudHJ1c3QuY29tL2NlcnRpZmljYXRlcy9wb2xpY3kvdHMv
MIIBBwYGZ4EMAQICMIH8MEAGCCsGAQUFBwIBFjRodHRwczovL3NlY3VyZS5pZGVu
dHJ1c3QuY29tL2NlcnRpZmljYXRlcy9wb2xpY3kvdHMvMIG3BggrBgEFBQcCAjCB
qhqBp1RoaXMgVHJ1c3RJRCBTZXJ2ZXIgQ2VydGlmaWNhdGUgaGFzIGJlZW4gaXNz
dWVkIGluIGFjY29yZGFuY2Ugd2l0aCBJZGVuVHJ1c3QncyBUcnVzdElEIENlcnRp
ZmljYXRlIFBvbGljeSBmb3VuZCBhdCBodHRwczovL3NlY3VyZS5pZGVudHJ1c3Qu
Y29tL2NlcnRpZmljYXRlcy9wb2xpY3kvdHMvMB0GA1UdDgQWBBQvAQatcXq62MSt
v2WLHPKwErqzgDBFBgNVHR8EPjA8MDqgOKA2hjRodHRwOi8vdmFsaWRhdGlvbi5p
ZGVudHJ1c3QuY29tL2NybC90cnVzdGlkY2FhNTIuY3JsMIGEBggrBgEFBQcBAQR4
MHYwMAYIKwYBBQUHMAGGJGh0dHA6Ly9jb21tZXJjaWFsLm9jc3AuaWRlbnRydXN0
LmNvbTBCBggrBgEFBQcwAoY2aHR0cDovL3ZhbGlkYXRpb24uaWRlbnRydXN0LmNv
bS9jZXJ0cy90cnVzdGlkY2FhNTIucDdjMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
BgEFBQcDAjAfBgNVHSMEGDAWgBSiViQ80NQVuei/eKMTEFhILhZU4TA1BgNVHREE
LjAsghUqLmFwaS5sZXRzZW5jcnlwdC5vcmeCE2FwaS5sZXRzZW5jcnlwdC5vcmcw
DQYJKoZIhvcNAQELBQADggEBAIgV29HRYYk2RfrkE6KOeAT6K3AJsKgNe+i9Pdo7
YLdiDGMv/kKyyTNsq4l8IEaY1kw3aqkyT44D8vp6yGbbNl1uAE4VnaPeChLOBK0G
xz3CjtoZPqLxmieft8jybIVWZKZlIIsZrSMaEvrmRTGYartBSuxqOzIjCNxvkkRt
MYDNYRhiy6NPMtA0kpDQCN6tOggXdCm19kmzKI8pUvQGCnGscXJvlQIeaZva0GWf
UOuPael/zohUUsm2lJowlIli939RdxUal0hwv8tD12qAyZAF2/+4y61ds4svGD9B
ukNnsAzS3EXNqq5qWFqRQyiTZfCcjaXEdtySyNAUiM6eFTY=
-----END CERTIFICATE-----
subject=/CN=*.api.letsencrypt.org/O=INTERNET SECURITY RESEARCH GROUP/L=Mountain View/ST=California/C=US
issuer=/C=US/O=IdenTrust/OU=TrustID Server/CN=TrustID Server CA A52
---
No client certificate CA names sent
---
SSL handshake has read 5917 bytes and written 421 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 45EE9F83CEB035C4EC46A8772B95DDFC73DFBC286C8BC2A8AF453332C5A0FED1
    Session-ID-ctx: 
    Master-Key: 0A6978EA17B04D5E4E953746821C942CDAF99E68D6E133C12FF23182A14526CA80DC41E70A06556A251F6B4BB536592B
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 00 00 03 d5 0b 1e 61 89-7e 71 d7 7a 22 81 94 3f   ......a.~q.z"..?
    0010 - dd 12 32 70 4b 43 be 12-69 47 5a 01 e1 82 d1 3c   ..2pKC..iGZ....<
    0020 - f8 e6 97 a4 3f f6 52 2b-e9 f0 ef d2 88 0f 4a a4   ....?.R+......J.
    0030 - bc ed 05 4d 51 21 7c 3c-88 3d 81 7b 0c a4 e4 45   ...MQ!|<.=.{...E
    0040 - 23 1a de 99 28 20 83 9f-de 12 9a f2 f8 b1 6f c8   #...( ........o.
    0050 - cd 70 65 90 9e 26 28 c8-fe 5d 82 07 0f b2 13 73   .pe..&(..].....s
    0060 - c0 4c 8c c7 5e cc 0d 7f-bf d2 f8 f5 b8 28 71 b2   .L..^........(q.
    0070 - ce 4b 24 2d 11 72 fa 3b-2e 8b 69 23 6d 4c ac c5   .K$-.r.;..i#mL..
    0080 - c2 0d c3 4a 42 3b f9 70-42 b8 ec e8 7a ac bc 9a   ...JB;.pB...z...
    0090 - bf 86 3d 02 cb 5d 7e 97-e3 06 aa 0a 2b 78 12 cf   ..=..]~.....+x..

    Start Time: 1500103081
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
```

**Comment by SwartzCr** [comment]
@jsha any ideas?

**Comment by jsha** [comment]
That's weird indeed. I assume when you ran the example Python code above, it was on the same machine? Do you have PYTHONPATH set? I.e. could you be using a different version of `requests` in the Python REPL than through Certbot?

Could you share a tcpdump of a Certbot session failing its handshake?

**Comment by postmarkio** [comment]
On Debian Stretch with Nginx when I just attempted a cert renewal I'm getting similar errors in the logs. This has just started. Any ideas on this one anybody?

... SNIP...
2017-07-17 21:42:21,516:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x7fdd86330cd0> and installer None
2017-07-17 21:42:21,523:DEBUG:certbot.main:Picked account: <Account(02838c0356821fa10bef71d444d2ec7d)>
2017-07-17 21:42:21,524:DEBUG:root:Sending GET request to https://acme-staging.api.letsencrypt.org/directory.
2017-07-17 21:42:21,530:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
2017-07-17 21:42:43,569:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 849, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 621, in obtain_cert
    le_client = _init_le_client(config, auth, installer)
... /SNIP...

**Comment by MrKich** [comment]
```
$ head -n 1 /usr/bin/certbot
#!/usr/bin/python

$ which python
/usr/bin/python

$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.__file__
'/usr/local/lib/python2.7/dist-packages/requests/__init__.pyc'
>>> requests.__version__
'1.2.3'
>>> requests.get("https://acme-v01.api.letsencrypt.org")
<Response [200]>
```

## Found very "funny" moment:
```
>>> import requests
>>> s = requests.Session()
>>> s.request('GET', "https://acme-v01.api.letsencrypt.org")
<Response [200]>
>>> s.request('GET', "https://acme-v01.api.letsencrypt.org", timeout=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 331, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno bad handshake]
>>> s.request('GET', "https://acme-v01.api.letsencrypt.org", verify=True)
<Response [200]>
>>> s.request('GET', "https://acme-v01.api.letsencrypt.org", verify=False, timeout=10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 335, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 438, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 331, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno bad handshake]
```

Looks like it is a requests 1.2.3 bug O_O

**Comment by jsha** [comment]
Nice find! It looks like maybe it's specific to reused connections? @bmw, what version of requests ships with our PPA? Can we bump it?

**Comment by MrKich** [comment]
I have completely traced that bug
It is in pyopenssl wrapper which is from urllib3's contib (which is used by requests=1.2.3)

There is a special behavior with python OpenSSL and blocking socket during ssl handshakes (or bug, idk)
Urllib3 treats this as handshake error (which is actually not)
https://stackoverflow.com/questions/26540429/python-openssl-connection-failing-handshake-when-using-timeout

Error seems to be fixed in urllib3 >=1.8 (have not tested, but since that version they ugly catch that error)

#### Original piece of code on server

```
cnx = OpenSSL.SSL.Connection(ctx, sock)
    cnx.set_tlsext_host_name(server_hostname)
    cnx.set_connect_state()
    try:
        cnx.do_handshake()
    except OpenSSL.SSL.Error as e:
        raise ssl.SSLError('bad handshake', e)

    return WrappedSocket(cnx, sock)
```

#### Starting from version 1.8
```
while True:
        try:
            cnx.do_handshake()
        except OpenSSL.SSL.WantReadError:
            select.select([sock], [], [])
            continue
        except OpenSSL.SSL.Error as e:
            raise ssl.SSLError('bad handshake', e)
        break
```

**Comment by MrKich** [comment]
And something strange - is that urllib3 package (and its version in __init__.py file) shows that its version is 1.19.1, but after looking at github of urllib3 - it seems that it is not 1.19. (or maybe some another branch? Oo)
https://github.com/shazow/urllib3/

**Comment by bmw** [comment]
The version of requests we have packaged in [the PPA](https://launchpad.net/~certbot/+archive/ubuntu/certbot/) is 2.12.4 (not 1.2.3). The version of urllib3 is 1.19.1. Can you try updating your requests package using our PPA and see if you still have the problem?

**Comment by bmw** [comment]
This hasn't seen any updates in almost 2 years so I'm closing this issue. If you're still having problems, please comment or open a new issue.
