### ISSUE TITLE
Acme/Jose/JWK Module Import Error

### ISSUE THREAD

**Issue by geoconnections** [certbot/certbot#4980]
## My operating system is (include version):
Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-40-generic x86_64)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
sudo apt-get install python-certbot-apache 

## I ran this command and it produced this output:
certbot --help

Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.14.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 9, in <module>
    from acme import jose
  File "/usr/lib/python2.7/dist-packages/acme/jose/__init__.py", line 53, in <module>
    from acme.jose.jwa import (
  File "/usr/lib/python2.7/dist-packages/acme/jose/jwa.py", line 18, in <module>
    from acme.jose import jwk
  File "/usr/lib/python2.7/dist-packages/acme/jose/jwk.py", line 128, in <module>
    class JWKES(JWK):  # pragma: no cover
  File "/usr/lib/python2.7/dist-packages/acme/jose/jwk.py", line 137, in JWKES
    ec.EllipticCurvePublicKey, ec.EllipticCurvePrivateKey)
AttributeError: 'module' object has no attribute 'EllipticCurvePublicKey'

**Comment by SwartzCr** [comment]
@geoconnections  Can you figure out what version of acme you have?
@jsha any ideas?

**Comment by jsha** [comment]
The `ec` package comes from:

```
from cryptography.hazmat.primitives.asymmetric import ec
```

So what we'd really want to know is what version of python-cryptography you have: `dpkg -l python-cryptography`

**Comment by geoconnections** [comment]
acme 0.14.2
python-cryptography 1.7.1-2+cert

**Comment by geoconnections** [comment]
I was able to find a solution while debugging a different issue. I had to run:

pip install --upgrade requests[security]

**Comment by SwartzCr** [comment]
This seems closable, but this is the second time requests has seemed to cause problems. @bmw or @erikrose is there anything we can do?

**Comment by erikrose** [comment]
Impossible to say without more info. I'd be interested to know whether six was installed and what the old and new versions of requests were. But I think there are a lot of other things that ought to be higher priority.

**Comment by SwartzCr** [comment]
@geoconnections are you still encountering this issue?

**Comment by geoconnections** [comment]
No. The fix mentioned on Aug 4 took care of the problem. 

@erikrose sorry I didn't take notes as I went through so I am unable to shed any light on your questions. 

I will say that I had the same problem crop up on a second system and it was again fixed with the [security] option on requests
