### ISSUE TITLE
_openssl.so: cannot change memory protections: Permission denied

### ISSUE THREAD

**Issue by smarek** [certbot/certbot#4996]
Follow-up from #3295

## My operating system is (include version):
Debian 9 Stretch 

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Both certbot-auto from Debian aptitude (0.10.2-1) and Letsencrypt-auto from https://github.com/letsencrypt/letsencrypt

## I ran this command and it produced this output:
`certbot-auto renew` or `letsencrypt-auto renew`

```
./letsencrypt-auto renew
Upgrading certbot-auto 0.16.0 to 0.17.0...
Replacing certbot-auto...
Error: couldn't get currently installed version for /root/.local/share/letsencrypt/bin/letsencrypt: 
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 9, in <module>
    from acme import jose
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: cannot change memory protections: Permission denied
```

## Certbot's behavior differed from what I expected because:

Running **grsec** kernel (4.9.0-2-grsec-amd64)
First running with certbot-auto would upgrade the local sandbox and start failing due to _openssl.so library, then letsencrypt-auto did the same.

Problem was solved by completely removing the sandbox (/root/.local/share/letsencrypt)
and running current letsencrypt-auto again (re-initialized sandbox does not suffer from this issue)

**Comment by SwartzCr** [comment]
So currently letsencrypt-auto and certbot-auto are the same thing, they both pull the most recent version from pip. Certbot should be packaged for debian 9, is that what you mean when you reference the 0.10.2 version?
the -auto scripts are trying to build python cryptography against openSSL and failing due to grsec it seems like, but the packaged version shouldn't need to do this. Can you share the error you get with the packaged version?
Additionally python-cryptography is shipping a wheel, which should resolve this issue in future versions.

**Comment by smarek** [comment]
Maybe I wrote the issue in confusing way, 0.10.2 is packaged version in Debian see here: https://packages.debian.org/stretch/certbot

Actually the failing one is the Debian packaged version, if I remove local sandbox/prefix and run the letsencrypt-auto from its github version, it works as expected.

**Comment by SwartzCr** [comment]
Interesting - I wonder if @hlieberman has any ideas about whether or how this can be fixed since he is the debian package maintainer. My naive guess is that it's not fixable since it has to do with how python cryptography is built after debian pulls down the source files.

**Comment by hlieberman** [comment]
Hmm.  I'm suspicious that this is related to the way that
python-cryptography loads the openssl library itself.  Try disabling
MEMPROTECT on that .so file -- or maybe on the python interpreter itself.

Also, check your logfiles for grsecurity denies.

**Comment by hlieberman** [comment]
Yeah, that's definitely what's happening here.  Look at
https://cffi.readthedocs.io/en/latest/using.html#callbacks-old-style
in the warning.

On Tue, Aug 8, 2017 at 6:07 PM, Harlan Lieberman-Berg
<hlieberman@setec.io> wrote:
> Hmm.  I'm suspicious that this is related to the way that
> python-cryptography loads the openssl library itself.  Try disabling
> MEMPROTECT on that .so file -- or maybe on the python interpreter itself.
>
> Also, check your logfiles for grsecurity denies.



-- 
Harlan Lieberman-Berg
~hlieberman

**Comment by SwartzCr** [comment]
@smarek did that help? Have you tried to disable MEMPROTECT?

**Comment by conorsch** [comment]
Howdy @smarek! Recently encountered a similar problem cryptography-related nassl Python module in another project ([pshtt](https://github.com/dhs-ncats/pshtt), for those following along at home). Running 4.4.84-grsec on Debian Stretch.

@hlieberman Thanks for pointing out the specific problem with python-cryptography. 

> Try disabling MEMPROTECT on that .so file -- or maybe on the python interpreter itself.

For my case, disabling MEMPROTECT on the python interpreter itself resolved the issue. You shouldn't need any special flags on the shared object files. Here's the full traceback, in case it helps others:

```
root@9ab8fb83dd3d:/# pshtt --help
Traceback (most recent call last):
  File "/usr/local/bin/pshtt", line 11, in <module>
    load_entry_point('pshtt==0.1.4', 'console_scripts', 'pshtt')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pshtt/cli.py", line 26, in <module>
    import pshtt
  File "/usr/local/lib/python2.7/dist-packages/pshtt/pshtt.py", line 20, in <module>
    from sslyze.server_connectivity import ServerConnectivityInfo
  File "/usr/local/lib/python2.7/dist-packages/sslyze/server_connectivity.py", line 13, in <module>
    from nassl.ssl_client import ClientCertificateRequested, OpenSslVersionEnum
  File "/usr/local/lib/python2.7/dist-packages/nassl/ssl_client.py", line 8, in <module>
    from nassl._nassl import SSL_CTX, SSL, BIO, WantReadError, OpenSSLError, X509, WantX509LookupError
ImportError: /usr/local/lib/python2.7/dist-packages/nassl/_nassl.so: cannot change memory protections: Permission denied
```

Hope this helps, @smarek. Thanks for the helpful discussion, @SwartzCr! :wink:

**Comment by SwartzCr** [comment]
Thanks @conorsch! I will close this issue, as it seems that there's a resolution path. Feel free to open new issues if you think there's something we can do in certbot, or if there continue to be issues for this.
