### ISSUE TITLE
Fail to parse httpd 2.2 variable

### ISSUE THREAD

**Issue by tazou** [certbot/certbot#5022]
Hello,
When I try to install certbot for Apache 2, I have this error. (See below)

## My operating system is (include version):
Red Hat Enterprise Linux Server release 6.9 (Santiago)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
wget https://dl.eff.org/certbot-auto

## I ran this command and it produced this output:
./certbot-auto --apache
/root/.local/share/letsencrypt/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError(u'Error Parsing variable: ${ENVTSP}',)

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
cat /var/log/letsencrypt/letsencrypt.log
```
2017-08-11 09:25:13,988:DEBUG:certbot.main:certbot version: 0.17.0
2017-08-11 09:25:13,989:DEBUG:certbot.main:Arguments: ['--apache']
2017-08-11 09:25:13,989:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-08-11 09:25:14,011:DEBUG:certbot.log:Root logging level set at 20
2017-08-11 09:25:14,011:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-08-11 09:25:14,013:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-08-11 09:25:14,125:DEBUG:certbot_apache.configurator:Apache version is 2.2.15
2017-08-11 09:25:15,242:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): Error Parsing variable: ${ENVTSP}
Traceback (most recent call last):
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_apache/configurator.py", line 200, in prepare
    self.vhosts = self.get_virtual_hosts()
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_apache/configurator.py", line 617, in get_virtual_hosts
    new_vhost = self._create_vhost(path)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_apache/configurator.py", line 593, in _create_vhost
    self._add_servernames(vhost)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_apache/configurator.py", line 541, in _add_servernames
    servername, serveraliases = self._get_vhost_names(host.path)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_apache/configurator.py", line 523, in _get_vhost_names
    serveralias = self.parser.get_arg(alias)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/certbot_apache/parser.py", line 351, in get_arg
    raise errors.PluginError("Error Parsing variable: %s" % var)
PluginError: Error Parsing variable: ${ENVTSP}
2017-08-11 09:25:15,247:DEBUG:certbot.plugins.selection:No candidate plugin
2017-08-11 09:25:15,247:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
```

## There is the httpd details version : 
httpd -V
```
Server version: Apache/2.2.15 (Unix)
Server built:   Jul  7 2017 06:40:45
Server's Module Magic Number: 20051115:25
Server loaded:  APR 1.3.9, APR-Util 1.3.9
Compiled using: APR 1.3.9, APR-Util 1.3.9
Architecture:   64-bit
Server MPM:     Prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APACHE_MPM_DIR="server/mpm/prefork"
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=128
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_PIDLOG="run/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_LOCKFILE="logs/accept.lock"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"
```

Do you know how can I install certbot on my server please ?

Best regards.

**Comment by SwartzCr** [comment]
It seems that certbot is able to install itself fine, but then is choking on a variable specified in one of your apache configs.
Can you look through your apache virtual hosts and see if the string `${ENVTSP}` exists anywhere?
@joohoi do you know if any of those characters cause problems for our parser?

**Comment by joohoi** [comment]
We should strip them off at https://github.com/certbot/certbot/blob/master/certbot-apache/certbot_apache/parser.py#L347 so there must be something else going on. @tazou could you post your Apache vhost configuration by any chance? This problem could be caused by any file included from your main Apache configuration file.

**Comment by tazou** [comment]
Hello,
Yes this variable is present a lot of time in my configs : 
```
 grep -r ENVTSP /etc/httpd/conf*|grep -v '.svn'|wc -l
783
```

For example : 
`/etc/httpd/conf.d/VDM_www.marseille.fr.conf:  Redirect permanent "/Histoire-de-marseille"          	"http://musee-histoire.marseille.${ENVTSP}"`

And this variable comes from the file : 
```
 grep ENVTSP /etc/sysconfig/httpd 
export ENVTSP='va.tsp'
```

An idea please ?
Thank you.

**Comment by SwartzCr** [comment]
@tazou have you been able to resolve this issue or are you still unable to get certificates?
If you haven't managed to get a certificate, I'm sure @joohoi would be happy to continue helping you debug this problem

**Comment by tazou** [comment]
Hello,
It is not solved yet.
I'll appreciate help yes :)
Thank you.

**Comment by joohoi** [comment]
Certbot isn't currently able to resolve the variables used in configuration. For most of the directives that doesn't matter, but reading the stack trace of the error, it looks like the variable is used in a ServerAlias directive somewhere down the line. To resolve the problem temporarily, you could try removing the variables from the ServerName and ServerAlias directives in your configuration.

In bigger picture, resolving the variables in ServerName and ServerAlias directives looks like rather time consuming problem to solve, and we might be able to get to it at some point, but unfortunately I don't believe it's too high priority right now. In short term how we possibly could remedy the situation here would be just ignoring the ServerNames and ServerAliases with variables in order to not to bail out with error. I'll bring this up for the team.

**Comment by tazou** [comment]
Hi,
Thanks for your answer.
I did it by hand with something like that : 

> ./certbot-auto -n -d test.mysite.fr --preferred-challenges dns certonly --manual

Thanks for your help,
Regards.
