### ISSUE TITLE
centos 6.4 OSError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by ice-ice** [certbot/certbot#5038]
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/virtualenv.py", line 2308, in <module>
    main()
  File "/usr/lib/python2.6/site-packages/virtualenv.py", line 821, in main
    symlink=options.symlink)
  File "/usr/lib/python2.6/site-packages/virtualenv.py", line 956, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/lib/python2.6/site-packages/virtualenv.py", line 1130, in install_python
    fix_lib64(lib_dir, symlink)
  File "/usr/lib/python2.6/site-packages/virtualenv.py", line 1539, in fix_lib64
    cp_or_ln('lib', lib64_link)
OSError: [Errno 13] Permission denied

**Comment by 631768417** [comment]
/home/certbot-master/certbot-auto --nginx -d www.le6.top --nginx-server-root=/alidata/server/nginx-1.4.4/conf/vhosts

**Comment by SwartzCr** [comment]
I think the issue you're having is that you need to be running `certbot-auto` as root. This would mean running the command you pasted with `sudo` at the beginning.
This is because it needs to do things like make a virtual environment to install packages and fetch system dependencies.
Can you try that and let me know if it helps?
Also depending on what operating system you're using there might be a system package for certbot. You can find full instructions at certbot.eff.org

**Comment by SwartzCr** [comment]
@631768417 have you had any success getting past this issue? Are you still unable to get a certificate?
