### ISSUE TITLE
how to upgrade certbot from a package instead of source

### ISSUE THREAD

**Issue by yuwiggin** [certbot/certbot#5039]
## My operating system is (include version):
Ubuntu 16.04, 
nginx version: nginx/1.10.3 (Ubuntu)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
I installed Certbot from source last year (v0.9.3), i.e.    
`sudo git clone https://github.com/letsencrypt/letsencrypt /opt/letsencrypt`  
`cd /opt/letsencrypt`  
`./certbot-auto`  

## I ran this command and it produced this output:
I want to upgrade Certbot with 
`./certbot-auto`
but output the following:  

```
Upgrading certbot-auto 0.9.3 to 0.17.0...
Replacing certbot-auto...
[sudo] password for xxxx: 
Creating virtual environment...
rm: cannot remove '/home/viking/.local/share/letsencrypt/bin/activate': Permission denied
.....

```
Then I ran 
`sudo ./certbot-auto'   

## Certbot's behavior differed from what I expected because:
No response in a long time.  
Now I don't want this source build.  I'd like to install/upgrade it from a package.   
How to do?

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.  

```
2017-08-20 04:49:04,446:DEBUG:certbot.main:certbot version: 0.17.0
2017-08-20 04:49:04,446:DEBUG:certbot.main:Arguments: []
2017-08-20 04:49:04,446:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-08-20 04:49:04,461:DEBUG:certbot.log:Root logging level set at 20
2017-08-20 04:49:04,462:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-08-20 04:49:04,462:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2017-08-20 04:49:04,804:WARNING:certbot.plugins.util:Failed to find executable apache2ctl in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
2017-08-20 04:49:04,805:DEBUG:certbot.plugins.disco:No installation (PluginEntryPoint#apache): Cannot find Apache control command apache2ctl
Traceback (most recent call last):
  File "/home/viking/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/home/viking/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 173, in prepare
    'Cannot find Apache control command {0}'.format(restart_cmd))
NoInstallationError: Cannot find Apache control command apache2ctl
2017-08-20 04:49:04,833:DEBUG:certbot.plugins.selection:No candidate plugin
2017-08-20 04:49:04,833:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
```

**Comment by creepersbane** [comment]
Try installing certbot from Jessie Backports. You may enable the repository by following the instructions here: https://backports.debian.org/Instructions/

Afterward, install certbot with the following command: `sudo apt-get -t jessie-backports install certbot python-certbot-apache`

**Comment by SwartzCr** [comment]
Actually on Ubuntu you'll need to enable the certbot PPA, instructions can be found at https://certbot.eff.org
Additionally you can probably just remove that letsencrypt directory in .local if you're not planning to use to source built version. Is it possible that pip put it there? Could pip remove it?

**Comment by SwartzCr** [comment]
Also @creepersbane I've noticed that you've been helping answer questions on github! Awesome!
Want to join our IRC chatroom or give me an email at noah@eff.org to coordinate? That way we can maybe split responsibility or I can help you find issues to help people with?

**Comment by creepersbane** [comment]
@SwartzCr that would be great!

(Now back to the real problem before this becomes a full blown off-topic conversation :D)

@yuwiggin try @SwartzCr's suggestion. Hope it works!
