### ISSUE TITLE
certbot-nginx cannot find virtualhost with regex

### ISSUE THREAD

**Issue by akamustang** [certbot/certbot#5102]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
PPA

## I ran this command and it produced this output:
```
sudo certbot --nginx -d example.com -d www.example.com
```
```
Cannot find a VirtualHost matching domain example.com.
```

## Certbot's behavior differed from what I expected because:
It couldn't match a server_name that uses regex.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.17.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 753, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 606, in run
    certname, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 82, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 74, in get_authorizations
    resp = self._solve_challenges()
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 115, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/usr/lib/python2.7/dist-packages/certbot_nginx/configurator.py", line 803, in perform
    sni_response = chall_doer.perform()
  File "/usr/lib/python2.7/dist-packages/certbot_nginx/tls_sni_01.py", line 55, in perform
    vhost = self.configurator.choose_vhost(achall.domain)
  File "/usr/lib/python2.7/dist-packages/certbot_nginx/configurator.py", line 241, in choose_vhost
    "Cannot find a VirtualHost matching domain %s." % (target_name))
MisconfigurationError: Cannot find a VirtualHost matching domain example.com.
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
server {
  server_name ~^(www\.)(?<domain>example(\..+)?)$;
  ...
}

server {
  server_name ~^(?<domain>example(\..+)?)$;
  ...
}
```

**Comment by SwartzCr** [comment]
@ohemorange is this something we support? What do we recommend to people who have vhosts like this?

**Comment by ohemorange** [comment]
Yes, we support regex. Is your `nginx.conf` located in `/etc/nginx/`, or somewhere else? And does it properly include the files containing these server blocks?

**Comment by ohemorange** [comment]
Ah, looks like this is a https://github.com/certbot/certbot/issues/4930 problem. Full explanation and suggestion here: https://github.com/certbot/certbot/issues/4930#issuecomment-316224973

Closing as duplicate, thanks for reporting!

**Comment by akamustang** [comment]
My Google-fu was weak this day, thanks for responding.
