### ISSUE TITLE
RHEL 7 Install Problem

### ISSUE THREAD

**Issue by mcgredonps** [certbot/certbot#5109]
## My operating system is (include version):
Red Hat Enterprise Linux Server release 7.4 (Maipo)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Instructions to use yum, etc at https://certbot.eff.org/,  with apache and centosrhel7-apache

## I ran this command and it produced this output:

Claimed to install, no errors. Problem cropped up with trying to install certificate afterwards, with a python error. Aftermath, running through yum install again:

yum -y install yum-utils
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Package yum-utils-1.1.31-42.el7.noarch already installed and latest version
Nothing to do
yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional
Loaded plugins: product-id
yum install certbot-apache
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Package python2-certbot-apache-0.14.1-1.el7.noarch already installed and latest version
Nothing to do

# yum install certbot-apache
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Package python2-certbot-apache-0.14.1-1.el7.noarch already installed and latest version
Nothing to do

At this point attempt to run certbot. It fails due to a python config problem I don't at all follow because I don't directly do python. 

# certbot --apache
Traceback (most recent call last):
  File "/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.14.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2687, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2341, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2347, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 14, in <module>
    from certbot import account
  File "/usr/lib/python2.7/site-packages/certbot/account.py", line 17, in <module>
    from acme import messages
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/site-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'

## Certbot's behavior differed from what I expected because:

Certbot failed with some python problem. Didn't see any operational fixes elsewhere on the internet that I could make work, though several have noted the problem. I'm not much of a python guy.

**Comment by SwartzCr** [comment]
Seems directly related to #5104 and #4886
Can you try to update your versions of `requests` and `six` as mentioned in #4886

**Comment by mcgredonps** [comment]
Looks like the same error after "pip install --upgrade six" I this some sort of not-finding-the-library problem? Certbot claims to not being finding urllib3, despite pip claiming it's installed.
The pip stuff is per 4886.

# pip list | grep 'six\|req\|cert\|url'
certbot (0.18.1)
certbot-apache (0.18.1)
certifi (2017.7.27.1)
pycurl (7.19.0)
requests (2.18.4)
six (1.10.0)
urlgrabber (3.10)
urllib3 (1.22)

# certbot --apache
Traceback (most recent call last):
  File "/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.14.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2687, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2341, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2347, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 14, in <module>
    from certbot import account
  File "/usr/lib/python2.7/site-packages/certbot/account.py", line 17, in <module>
    from acme import messages
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/site-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'

**Comment by adityaduggal** [comment]
Even I am facing this issue with CentOS-7, I have tried `pip install --upgrade six`

```
[root@www /]# pip freeze
acme==0.18.1
ansible==2.4.0.0
asn1crypto==0.23.0
backports.ssl-match-hostname==3.4.0.2
bcrypt==3.1.3
-e git+https://github.com/frappe/bench@c97be6ab1f15d2027c52c73ba7a075fbe6a7d89e#egg=bench
certbot==0.18.1
certbot-nginx==0.18.1
certifi==2017.7.27.1
cffi==1.11.0
chardet==3.0.4
click==6.7
ConfigArgParse==0.11.0
configobj==4.7.2
cryptography==2.0.3
cssselect==1.0.1
decorator==3.4.0
enum34==1.1.6
fail2ban==0.9.7
future==0.16.0
gitdb==0.6.4
GitPython==0.3.2rc1
honcho==1.0.1
idna==2.6
iniparse==0.4
ipaddress==1.0.18
IPy==0.75
Jinja2==2.9.6
kitchen==1.1.1
langtable==0.0.31
lxml==4.0.0
Magic-file-extensions==0.2
MarkupSafe==1.0
meld3==0.6.10
mock==1.0.1
MySQL-python==1.2.5
ndg-httpsclient==0.3.2
paramiko==2.3.1
parsedatetime==1.5
perf==0.1
ply==3.4
policycoreutils-default-encoding==0.1
psutil==5.3.1
pyasn1==0.3.6
pycparser==2.18
pycurl==7.19.0
pygobject==3.22.0
pygpgme==0.3
pyliblzma==0.5.3
PyNaCl==1.1.2
pyOpenSSL==0.13.1
pyparsing==1.5.6
pyRFC3339==1.0
python-augeas==0.5.0
python-crontab==2.2.4
python-dateutil==2.6.1
python-dmidecode==3.12.2
python-linux-procfs==0.4.9
python2-pythondialog==3.3.0
pytz==2016.10
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.12
requests==2.18.4
s3cmd==1.6.1
schedutils==0.4
semantic-version==2.6.0
seobject==0.1
sepolicy==1.1
six==1.11.0
slip==0.4.0
slip.dbus==0.4.0
smmap==0.9.0
supervisor==3.1.4
urlgrabber==3.10
urllib3==1.22
virtualenv==15.1.0
yum-langpacks==0.4.2
yum-metadata-parser==1.1.4
zope.component==4.1.0
zope.event==4.0.3
zope.interface==4.0.5
```

```
[root@www /]# certbot

Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.18.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 14, in <module>
    from certbot import account
  File "/usr/lib/python2.7/site-packages/certbot/account.py", line 17, in <module>
    from acme import messages
  File "/usr/lib/python2.7/site-packages/acme/messages.py", line 5, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/site-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 32, in <module>
    from .exceptions import InvalidURL
  File "/usr/lib/python2.7/site-packages/requests/exceptions.py", line 10, in <module>
    from .packages.urllib3.exceptions import HTTPError as BaseHTTPError
  File "/usr/lib/python2.7/site-packages/requests/packages/__init__.py", line 95, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'requests.packages.urllib3'
```

On analysing the above trace of mine, I think there could be an issue with the site name in nginx config file, my website name is something like this `test_website.domain.com`

So I am thinking that underscore in the sub-domain is causing the issue. I am just guessing seeing the trace.

**Comment by SwartzCr** [comment]
Hi! Have either of you been able to resolve these problems in the last month? Or are you still experiencing

**Comment by mcgredonps** [comment]
Still a problem. It's on RHEL 7 hosts, and as a result I'm in the midst of just changing to acme and booting out certbot. That "Recommended: CertBot" at LetsEncrypt seems like false advertising.

________________________________

**Comment by adityaduggal** [comment]
Hi,
I was able to resolve this issue, I tried to explain my issue here at the below forum
https://community.letsencrypt.org/t/certbot-not-working-with-centos7-and-nginx/45646

Let me know if it resolved the issue or not.

**Comment by bbaassssiiee** [comment]
Dependency hell continues.

**Comment by antuspcm** [comment]
I have just solved this after entering dependency hell and having a couple of sessions with it.  This looks like its been quite a problem since 2017 and probably not going to get any better on EL7 with python2 going EOL, and more people installing newer everything python installed with pip. I probably have broken other python apps on my system relying on pip installed packages but having my cert valid for email and http is probably the most important function of my server. Its a pitty its so fragile. 

To get it to work I had to remove several pip python packages, restore old OS package manager versions and install a 3rd party PyOpenSSL rpm bring its API in to the sweet spot for certbot.

pip uninstall requests
pip uninstall urllib3
pip uninstall  pyOpenSSL

yum remove python-urllib3
yum remove python-requests

yum install python-urllib3
yum install python-requests
yum install certbot
yum install python2-certbot-apache.noarch

wget https://cbs.centos.org/kojifiles/packages/pyOpenSSL/16.2.0/3.el7/noarch/python2-pyOpenSSL-16.2.0-3.el7.noarch.rpm
yum localinstall python2-pyOpenSSL-16.2.0-3.el7.noarch.rpm

# certbot --version
certbot 0.39.0

**Comment by FelixSchwarz** [comment]
Please never install packages with pip to system-wide directories. If you use `pip` as root please make sure you always have an active virtualenv. Fedora's crash reporting regularly pings me with broken installs like the ones described in this issue and it is a bit annoying.

I try to provide the latest certbot releases in EPEL 7+8 so using `pip` should not give you any benefits (just downsides like fewer security protections when installing the packages etc). If you experience crashes when using Fedora/EPEL RPMs only (no pip-installed modules!) feel free to cc me.

**Comment by kalatchev** [comment]
@antuspcm - Your solution is still relevant in 2021, November. Thanks for sharing!
