### ISSUE TITLE
Connection failure to letsencrypt servers after doing a long challenge with Route53

### ISSUE THREAD

**Issue by hundt** [certbot/certbot#5110]
As the log below shows, when doing a Route53 verification with 18 different domains, a connection to https://acme-staging.api.letsencrypt.org fails with `ECONNRESET`. In the same environment, I can successfully get a certificate for two domains. I suspect this has something to do with the Keep-Alive connection to acme-staging.api.letsencrypt.org established at the beginning of the process but then not used for almost 17 minutes--the next time it tries to use that connection is when it fails.

## My operating system is (include version):
    $ uname -a
    Linux ip-10-9-0-232 3.10.0-327.10.1.el7.x86_64 #1 SMP Tue Feb 16 17:03:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    $ cat /etc/redhat-release
    CentOS Linux release 7.2.1511 (Core) 
    $ certbot --version
    certbot 0.18.1

Python packages installed (2.7):

    ConfigArgParse-0.12.0 PyOpenSSL-17.2.0 acme-0.18.1 asn1crypto-0.22.0 boto-2.48.0 boto3-1.4.7 botocore-1.7.9 certbot-0.18.1 certbot-dns-route53-0.18.1 certifi-2017.7.27.1 cffi-1.10.0 chardet-3.0.4 configobj-5.0.6 cryptography-2.0.3 docutils-0.14 enum34-1.1.6 funcsigs-1.0.2 future-0.16.0 futures-3.1.1 idna-2.6 ipaddress-1.0.18 jmespath-0.9.3 mock-2.0.0 parsedatetime-2.4 pbr-3.1.1 pycparser-2.18 pyrfc3339-1.0 python-dateutil-2.6.1 pytz-2017.2 pyyaml-3.12 requests-2.18.4 s3transfer-0.1.11 six-1.10.0 urllib3-1.22 zope.component-4.4.0 zope.event-4.3.0 zope.interface-4.4.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
    pip

## I ran this command and it produced this output:

    certbot certonly -n --agree-tos --email <redacted> --dns-route53 --logs-dir ./letsencrypt/logs --config-dir ./letsencrypt/conf --work-dir ./letsencrypt/work -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> -d <redacted> --staging

(The same issue happens without `--staging`)

## Certbot's behavior differed from what I expected because:

It fails at the "Waiting for verification" stage with: `ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))`

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Here are some relevant excerpts:

    2017-09-13 14:37:15,317:DEBUG:acme.client:Sending GET request to https://acme-staging.api.letsencrypt.org/directory.
    2017-09-13 14:37:15,318:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging.api.letsencrypt.org
    2017-09-13 14:37:15,454:DEBUG:urllib3.connectionpool:https://acme-staging.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 581
    2017-09-13 14:37:15,454:DEBUG:acme.client:Received response:
    HTTP 200
    Server: nginx
    Content-Type: application/json
    Content-Length: 581
    Boulder-Request-Id: l5aVTIxy55n8FeYqaRQGimZHHZh0eQUNqXHtq8QXF6U
    Replay-Nonce: yONB2npOshNHfciwrHZEhLde-sdX8hu7uUaglQ13v8U
    X-Frame-Options: DENY
    Strict-Transport-Security: max-age=604800
    Expires: Wed, 13 Sep 2017 14:37:15 GMT
    Cache-Control: max-age=0, no-cache, no-store
    Pragma: no-cache
    Date: Wed, 13 Sep 2017 14:37:15 GMT
    Connection: keep-alive

...

    2017-09-13 14:37:17,450:DEBUG:urllib3.connectionpool:https://acme-staging.api.letsencrypt.org:443 "POST /acme/new-authz HTTP/1.1" 201 1029
    2017-09-13 14:37:17,450:DEBUG:acme.client:Received response:
    HTTP 201

...

tons of Route53 stuff, no more activity on acme-staging.api.letsencrypt.org

...

    2017-09-13 14:54:02,256:INFO:certbot.plugins.dns_common:Waiting 10 seconds for DNS changes to propagate
    2017-09-13 14:54:12,266:INFO:certbot.auth_handler:Waiting for verification...
    2017-09-13 14:54:12,267:DEBUG:acme.client:JWS payload:
    <redacted>
    2017-09-13 14:54:12,269:DEBUG:acme.client:Sending POST request to https://acme-staging.api.letsencrypt.org/acme/challenge/uXZMh-DkSM80vD_Ua7IEAvEjDEcIJskk-jcn5GBFq3U/57718590:
    <redacted>
    2017-09-13 14:54:12,272:DEBUG:certbot.log:Exiting abnormally:
    Traceback (most recent call last):
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/bin/certbot", line 11, in <module>
        sys.exit(main())
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/certbot/main.py", line 755, in main
        return config.func(config, plugins)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/certbot/main.py", line 694, in certonly
        lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/certbot/main.py", line 82, in _get_and_save_cert
        lineage = le_client.obtain_and_enroll_certificate(domains, certname)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
        certr, chain, key, _ = self.obtain_certificate(domains)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/certbot/client.py", line 318, in obtain_certificate
        self.config.allow_subset_of_names)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 81, in get_authorizations
        self._respond(resp, best_effort)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 134, in _respond
        resp, chall_update)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/certbot/auth_handler.py", line 158, in _send_responses
        self.acme.answer_challenge(achall.challb, resp)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/acme/client.py", line 229, in answer_challenge
        response = self.net.post(challb.uri, response)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/acme/client.py", line 682, in post
        return self._post_once(*args, **kwargs)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/acme/client.py", line 693, in _post_once
        response = self._send_request('POST', url, data=data, **kwargs)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/acme/client.py", line 627, in _send_request
        response = self.session.request(method, url, *args, **kwargs)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
        r = adapter.send(request, **kwargs)
      File "/home/jenkins/jenkins_slave/workspace/renew-aws-certs/venv/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
        raise ConnectionError(err, request=request)
    ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

n/a

**Comment by SwartzCr** [comment]
@bmw thoughts?

**Comment by bmw** [comment]
Interesting. Can you reproduce this reliably? I tested once where challenge setup took 30+ minutes and didn't encounter this issue.

**Comment by hundt** [comment]
@bmw 

Yes, I can.

I wonder if this is related to this issue: https://github.com/requests/requests/issues/3808

The connection to letsencrypt from the machine that this fails on is going through an AWS NAT Gateway. When I ran the same command from my laptop (no NAT gateway but also quite different OS/library setup) it succeeded.

**Comment by bmw** [comment]
Thanks for digging into this @hundt. I think you're probably right that's the issue.

While I personally don't have time to work on this in the near future, I'd take a well written PR for this.

**Comment by toralf** [comment]
This might explain, why at my stable Gentoo linux server (ip 5.9.158.75) version 0.18.1 hangs at the step "clean up challenge" (IIRC) - whereas 0.17.0 works fine - command line is ::
`/usr/bin/certbot renew --max-log-backups 5 --standalone --non-interactive --text &>$log`

**Comment by jsha** [comment]
Interesting! I totally thought we had `requests` configured to do retries, but I guess not. It looks like the fix is very simple if someone wants to write it up:

(from https://github.com/requests/requests/issues/3808#issuecomment-271814088, posted earlier)
> changing the value of requests.adapters.DEFAULT_RETRIES to something other than zero before you create your session.

**Comment by jsha** [comment]
Posted a comment over at https://github.com/certbot/certbot/pull/5125#issuecomment-500539201 about my guess as to what's going on.

**Comment by bmw** [comment]
As suggested by jsha at https://community.letsencrypt.org/t/dns-challenge-almost-always-times-out/99191/10, one way to solve this that seems very clean to me is simply retrying the challenge response if the first one fails.

For RFC 8555, it's OK if the ACME server receives both requests from the client because a [second POST request should be interpreted as the client requesting to retry the challenge](https://tools.ietf.org/html/rfc8555#section-8.2).

For draft versions of ACME, I think the expected behavior on the server receiving a 2nd POST request is unclear, however, if the first request failed, Certbot is about to crash anyway so for simplicity of our implementation and to also try to solve this problem in ACMEv1 ([before we deprecate it](https://github.com/certbot/certbot/issues/6844)), I personally think it's fine for us to just always attempt a 2nd POST if the first fails.

A couple other notes if someone wants to try to implement this:

1. The relevant code is in `acme.client.ClientBase.answer_challenge`.
2. I am not sure if the `requests.Session` object is still usable or needs to be recreated. I hope it's the former but if it's not, I think it's OK to add a method to `acme.client.ClientNetwork` to create a new session.
3. The error from the first request should be logged.

**Comment by jsha** [comment]
I *think* the `requests.Session` object should still be usable. Once it gets a read timeout on a connection, it should remove that connection from the pool. Subsequent requests would create a new connection. I haven't tested this but it's typical of how connection pooling works.
