### ISSUE TITLE
resolution failure

### ISSUE THREAD

**Issue by Raptus1** [certbot/certbot#5241]
## My operating system is (include version): 
ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc): 
added repo

## I ran this command and it produced this output:  
sudo certbot --nginx
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
An unexpected error occurred:
ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))
Please see the logfiles in /var/log/letsencrypt for more details.

## Certbot's behavior differed from what I expected because:
I did not expect a resolution problem.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2017-11-12 10:09:31,236:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-11-12 10:09:31,239:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org

2017-11-12 12017-11-12 10:09:31,236:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-11-12 10:09:31,239:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org

2017-11-12 10:09:41,241:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 690, in run
    le_client = _init_le_client(config, authenticator, installer)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 486, in _init_le_client
    return client.Client(config, acc, authenticator, installer, acme=acme)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 235, in __init__
    acme = acme_from_config_key(config, self.account.key)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 45, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 71, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 654, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 627, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "~/.local/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "~/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "~/.local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))
2017-11-12 10:09:41,243:ERROR:certbot.log:An unexpected error occurred:

0:09:41,241:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 690, in run
    le_client = _init_le_client(config, authenticator, installer)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 486, in _init_le_client
    return client.Client(config, acc, authenticator, installer, acme=acme)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 235, in __init__
    acme = acme_from_config_key(config, self.account.key)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 45, in acme_from_config_key
    return acme_client.Client(config.server, key=key, net=net)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 71, in __init__
    self.net.get(directory).json())
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 654, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python2.7/dist-packages/acme/client.py", line 627, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "~/.local/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "~/.local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "~/.local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))
2017-11-12 10:09:41,243:ERROR:certbot.log:An unexpected error occurred:

**Comment by joohoi** [comment]
`ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))` suggests that it's a name resolution problem. Are you able to resolve the IP address of `acme-v01.api.letsencrypt.org` manually from the server you are trying to run Certbot from?

**Comment by Raptus1** [comment]
Now suddenly it has started to resolve properly, after months of not working. I tried nslookup and it was ok, after that the command was ok. 

Strange..
Anyway.. Closing this thread.
