### ISSUE TITLE
Error creating new authz :: Policy forbids issuing for name Please see the logfiles in /var/log/letsencrypt for more details.

### ISSUE THREAD

**Issue by Christian-Remboldt** [certbot/certbot#5246]
## My operating system is (include version):
Linux (raspbian ver.?)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
wget https://dl.eff.org/certbot-auto

## I ran this command and it produced this output:
_pi@raspberrypi:~ $_ sudo ./certbot-auto --apache certonly -d chriscri5jes2p4z.onion
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Obtaining a new certificate
An unexpected error occurred:
Error creating new authz :: Policy forbids issuing for name
Please see the logfiles in /var/log/letsencrypt for more details.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

2017-11-18 15:28:14,768:DEBUG:certbot.main:certbot version: 0.19.0
2017-11-18 15:28:14,775:DEBUG:certbot.main:Arguments: ['--apache', '-d', 'chriscri5jes2p4z.onion']
2017-11-18 15:28:14,775:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2017-11-18 15:28:14,960:DEBUG:certbot.log:Root logging level set at 20
2017-11-18 15:28:14,967:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2017-11-18 15:28:14,973:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2017-11-18 15:28:15,558:DEBUG:certbot_apache.configurator:Apache version is 2.4.25
2017-11-18 15:28:18,799:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x75d916b0>
Prep: True
2017-11-18 15:28:18,809:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x75d916b0>
Prep: True
2017-11-18 15:28:18,811:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x75d916b0> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x75d916b0>
2017-11-18 15:28:18,812:INFO:certbot.plugins.selection:Plugins selected: Authenticator apache, Installer apache
2017-11-18 15:28:18,859:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(status=None, contact=(u'mailto:admin@chris-cr.de',), agreement=u'https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf', key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x75b281f0>)>)), uri=u'https://acme-v01.api.letsencrypt.org/acme/reg/24423472', new_authzr_uri=u'https://acme-v01.api.letsencrypt.org/acme/new-authz', terms_of_service=u'https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'), 51b96a2c0a35bdc6ce2a17a570da7182, Meta(creation_host=u'raspberrypi', creation_dt=datetime.datetime(2017, 11, 17, 19, 13, 24, tzinfo=<UTC>)))>
2017-11-18 15:28:18,871:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2017-11-18 15:28:18,926:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2017-11-18 15:28:19,381:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 562
2017-11-18 15:28:19,388:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 562
Replay-Nonce: q910ZH5lwEOZ5nmXaO9A-8ee0mEvA1Qc-yvCmGffIuE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Sat, 18 Nov 2017 15:28:19 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 18 Nov 2017 15:28:19 GMT
Connection: keep-alive

{
  "-qzIOpI8Jiw": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
2017-11-18 15:28:19,393:INFO:certbot.main:Obtaining a new certificate
2017-11-18 15:28:19,394:DEBUG:acme.client:Requesting fresh nonce
2017-11-18 15:28:19,395:DEBUG:acme.client:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz.
2017-11-18 15:28:19,622:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "HEAD /acme/new-authz HTTP/1.1" 405 0
2017-11-18 15:28:19,628:DEBUG:acme.client:Received response:
HTTP 405
Server: nginx
Content-Type: application/problem+json
Content-Length: 91
Allow: POST
Replay-Nonce: fr7gY3mNsdhOQnzCufGVA-ImNp3-PGiMgl_Cl6H0G_Q
Expires: Sat, 18 Nov 2017 15:28:19 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 18 Nov 2017 15:28:19 GMT
Connection: keep-alive

2017-11-18 15:28:19,629:DEBUG:acme.client:Storing nonce: fr7gY3mNsdhOQnzCufGVA-ImNp3-PGiMgl_Cl6H0G_Q
2017-11-18 15:28:19,631:DEBUG:acme.client:JWS payload:
{
  "identifier": {
    "type": "dns", 
    "value": "chriscri5jes2p4z.onion"
  }, 
  "resource": "new-authz"
}
2017-11-18 15:28:19,707:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz:
{
  "protected": "eyJub25jZSI6ICJmcjdnWTNtTnNkaE9RbnpDdWZHVkEtSW1OcDMtUEdpTWdsX0NsNkgwR19RIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAia1lpYWtEOUtPaGZwM0VJNmJNQmRYWktiLUVIT0liV29VakdMQjg4QUdXZTJudnZxSk5FdHlwa0RrUnl3blU2UzJINHQtTDFJV1lZSXRieHRpV0V5THh2Q0MwYVJ3TU5zS1VJd2JsdHc3Qi1xS21MQ2g4T2pxNmVhb21oeV95Sjd6VC1YT2JpUEdMUi11LWkwVDM5V2hrWGpzNVk3cVpTdHk0eVVqQmVsMkFQd0p5cXhoNGNEVktNaFh4V01qSWdvSF9OQ2NTUTFTRnJWV0FSZHA2cTJNMVF5QXlSZEtVdlE3NDk0bTVISmNwSnczRUdQUHNFYzBNQ0xpRTBtelBCcUFnVGV6UzdZYmNOQkNRdGYzOGRQVjJiMmhVSnBvOTZ1YXp5VGVJbUpBQ0Z4VDJaS2UyQ2xwNUdZeVRUZHpLU1RJZDRSWW11M3RBR0lzZWNSWUNJYS1RIn19", 
  "payload": "ewogICJpZGVudGlmaWVyIjogewogICAgInR5cGUiOiAiZG5zIiwgCiAgICAidmFsdWUiOiAiY2hyaXNjcmk1amVzMnA0ei5vbmlvbiIKICB9LCAKICAicmVzb3VyY2UiOiAibmV3LWF1dGh6Igp9", 
  "signature": "Pa7q_nUpOEqSp6rCxxJLiv8sMdxZjgM5EgHUQgAPsZC-KLoHcHdUojWvq-77jyQvGzvtJvoAS0UZ01rVw_XErtNAjUWrBV0-stjbKypD8PMd1EzlO8rsAgCYnYRX7TwjRvDE7IvDiWnp3VeApmpJKwBG8Inw1tx8-KCuly78iC_2qkaFIzScmo7c8WmPgcd87Mi0sTsU5dd9DoNBhO8npo8kfn05HYsnm_POzH394WNlYsEAnutE9q40_beu9qfuE9Gk9IK3Y-URw72gE-4DhvwJrurLSW8SFu5sgXc5mSFxz0oNazKGPpcmMuZ-on_kpYMbD0-SCn4HtpMR7OS8Ig"
}
2017-11-18 15:28:19,911:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-authz HTTP/1.1" 400 141
2017-11-18 15:28:19,917:DEBUG:acme.client:Received response:
HTTP 400
Server: nginx
Content-Type: application/problem+json
Content-Length: 141
Boulder-Requester: 24423472
Replay-Nonce: l-9sRftNJIZpusJikGxF0HERjUTOH8bYn_H9KDXoZh8
Expires: Sat, 18 Nov 2017 15:28:19 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sat, 18 Nov 2017 15:28:19 GMT
Connection: close

{
  "type": "urn:acme:error:rejectedIdentifier",
  "detail": "Error creating new authz :: Policy forbids issuing for name",
  "status": 400
}
2017-11-18 15:28:19,918:DEBUG:acme.client:Storing nonce: l-9sRftNJIZpusJikGxF0HERjUTOH8bYn_H9KDXoZh8
2017-11-18 15:28:19,920:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 786, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 85, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 66, in get_authorizations
    self.authzr[domain] = self.acme.request_domain_challenges(domain)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/acme/client.py", line 212, in request_domain_challenges
    typ=messages.IDENTIFIER_FQDN, value=domain), new_authzr_uri)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/acme/client.py", line 191, in request_challenges
    response = self.net.post(self.directory.new_authz, new_authz)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/acme/client.py", line 682, in post
    return self._post_once(*args, **kwargs)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/acme/client.py", line 695, in _post_once
    return self._check_response(response, content_type=content_type)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/acme/client.py", line 582, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:rejectedIdentifier :: Error creating new authz :: Policy forbids issuing for name
2017-11-18 15:28:19,928:ERROR:certbot.log:An unexpected error occurred:
2017-11-18 15:28:19,929:ERROR:certbot.log:Error creating new authz :: Policy forbids issuing for name

**Comment by cpu** [comment]
Hi @Christian-Remboldt,

> pi@raspberrypi:~ $ sudo ./certbot-auto --apache certonly -d chriscri5jes2p4z.onion

Let's Encrypt only issues "Domain Validated" (DV) certificates because this is the only type that can be issued automatically at web scale. The [baseline requirements](https://cabforum.org/baseline-requirements-documents/) that all publicly trusted CAs have to obey specifically forbids issuing for any `.onion` domains unless the certificate is an "Extended Validation" (EV) certificate. Since Let's Encrypt can not issue EV certs automatically we can't issue for `.onion` domains.

This means for the time being it's impossible to use Let's Encrypt to issue a certificate for `chriscri5jes2p4z.onion`. I'm going to close this issue since it isn't something Certbot can fix.

If you're interested in more information I recommend reading @schoen's [recent email](https://cabforum.org/pipermail/public/2017-November/012451.html) to the CA/Browser Forum mailing list. It summarizes the current problems & what might be done in the future to help make this possible.

Hope that helps,
