### ISSUE TITLE
error in Logfile  and no new certificate

### ISSUE THREAD

**Issue by syswombat** [certbot/certbot#5320]
## My operating system is (include version):
Debian 4.9.30-2+deb9u2~bpo8+1

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
?

## Certbot's behavior differed from what I expected because:
no renew and error in log file
2017-12-11 02:03:26,111:INFO:certbot.renewal:Cert not yet due for renewal
2017-12-11 02:03:26,111:INFO:certbot.hooks:Running post-hook command: echo '1' > /usr/local/ispconfig/server/le.restart
2017-12-11 02:03:26,116:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 11, in <module>
    load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 849, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 655, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python2.7/dist-packages/certbot/renewal.py", line 430, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 1 parse failure(s)

**Comment by SwartzCr** [comment]
Can you share with me the output of `certbot certificates`?
It seems like you might have a post-hook that is causing an error, do you remember how you specified your post hooks? You may want to remove the one that appears in your error log.

**Comment by schoen** [comment]
@syswombat, if you're still having any type of troubles with Certbot, please open a new issue here and provide more information (or ask on the Community Forum at https://community.letsencrypt.org/). Thanks!
