### ISSUE TITLE
certbox --apache fails with "'module' object has no attribute '_init_cffi_1_0_external_module'"

### ISSUE THREAD

**Issue by md5i** [certbot/certbot#5345]
## My operating system is (include version):
Linux 4.14.0, Debian unstable

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
sudo apt-get install python-certbot-apache

## I ran this command and it produced this output:
$  sudo certbot --apache
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 11, in <module>
    from acme import jose
  File "/usr/lib/python2.7/dist-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/usr/lib/python2.7/dist-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/usr/lib/python2.7/dist-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python2.7/dist-packages/cryptography/x509/extensions.py", line 18, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
AttributeError: 'module' object has no attribute '_init_cffi_1_0_external_module'

## Certbot's behavior differed from what I expected because:
It raised an exception.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
    <VirtualHost _default_:8000>
      DocumentRoot "/var/web"
      <Directory "/var/web">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
      </Directory>
    
      <Directory "/var/web/git">
        Allow from all
        AllowOverride all
        Order allow,deny
        Options ExecCGI
        <Files gitweb.cgi>
          SetHandler cgi-script
        </Files>
      </Directory>
    
      DirectoryIndex gitweb.cgi
      SetEnv GITWEB_CONFIG /etc/gitweb.conf
    </VirtualHost>

**Comment by md5i** [comment]
Problem was on my end.   I had an old library sitting around in /usr/local.
