### ISSUE TITLE
certbot-auto  can't run on CentOS6.9 with python2.7

### ISSUE THREAD

**Issue by stonyz** [certbot/certbot#5357]
## My operating system is (include version):
CentOS 6.9

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto, pip

## I ran this command and it produced this output:

[root@app01 ~]# ./certbot-auto --apache --no-bootstrap
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 11, in <module>
    from acme import jose
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /opt/eff.org/certbot/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: cannot enable executable stack as shared object requires: Operation not permitted

## Certbot's behavior differed from what I expected because:
Didn't get a certification.

## Here is a Certbot log showing the issue (if available):

Didn't create log under /var/log/letsencrypt

**Comment by SwartzCr** [comment]
It seems like you might have a broken version of cryptography
This will happen if you have a version installed via pip and another version installed via certbot-auto.
Can you share the output of `pip freeze`?
My recommendation is to delete cryptography or pyOpenSSL from pip and run certbot-auto again

**Comment by stonyz** [comment]
Thanks @SwartzCr 
```
[root@app01 ~]# pip -V
pip 9.0.1 from /usr/local/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)
[root@xchangewithme---app ~]# pip freeze
virtualenv==15.1.0
[root@ app01 ~]# pip uninstall cryptography
Cannot uninstall requirement cryptography, not installed
[root@ app01 ~]# pip uninstall pyOpenSSL
Cannot uninstall requirement pyOpenSSL, not installed
```

it seems that pip doesn't have cryptography or pyOpenSSL installed.

**Comment by SwartzCr** [comment]
Is there a reason you're running it with `--no-bootstrap`?
Try running certbot-auto again without the `--no-bootstrap` option and see if that helps. My guess is that it will.

**Comment by stonyz** [comment]
I remove --no-bootstrap, the same thing.

```
[root@app01 ~]# ./certbot-auto --apache
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 11, in <module>
    from acme import jose
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/jose/__init__.py", line 37, in <module>
    from acme.jose.interfaces import JSONDeSerializable
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/jose/interfaces.py", line 9, in <module>
    from acme.jose import util
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/jose/util.py", line 5, in <module>
    import OpenSSL
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 13, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /opt/eff.org/certbot/venv/lib/python2.7/site-packages/cryptography/hazmat/bindings/_openssl.so: cannot enable executable stack as shared object requires: Operation not permitted
```

**Comment by SwartzCr** [comment]
It seems like your venv might be messed up, can you try deleting it and running certbot again?
This should cause it to re-install all of your python dependencies and hopefully fix things.

**Comment by stonyz** [comment]
After install the latest certbot-auto, the issue is gone. the issue can be closed
