### ISSUE TITLE
Cannot find a VirtualHost matching domain

### ISSUE THREAD

**Issue by fearrr** [certbot/certbot#5396]
## My operating system is (include version):
Ubuntu 16.04.3 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Automated (nginx plugin)

## I ran this command and it produced this output:
**command**
`certbot --nginx -d mysite.ru -d www.mysite.ru`

**output**
```
tls-sni-01 challenge for mysite.ru
tls-sni-01 challenge for www.mysite.ru
Cleaning up challenges
Cannot find a VirtualHost matching domain mysite.ru. In order for Certbot to correctly perform the challenge please add a corresponding server_name directive to your nginx configuration: https://nginx.org/en/docs/http/server_names.html
```

_p.s. mysite.ru is placeholder instead of real domain name_

## Certbot's behavior differed from what I expected because:
My config is ok

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

**logs tail**
```
2018-01-09 14:00:55,036:DEBUG:certbot.error_handler:Calling registered functions
2018-01-09 14:00:55,037:INFO:certbot.auth_handler:Cleaning up challenges
2018-01-09 14:00:55,109:DEBUG:certbot_nginx.parser:Could not parse file: /etc/nginx/nginx.conf due to Expected stringEnd (at char 116), (line:10, col:1)
2018-01-09 14:00:56,202:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 698, in run
    certname, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 85, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 74, in get_authorizations
    resp = self._solve_challenges()
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 115, in _solve_challenges
    resp = self.auth.perform(self.achalls)
  File "/usr/lib/python2.7/dist-packages/certbot_nginx/configurator.py", line 767, in perform
    sni_response = chall_doer.perform()
  File "/usr/lib/python2.7/dist-packages/certbot_nginx/tls_sni_01.py", line 55, in perform
    vhost = self.configurator.choose_vhost(achall.domain)
  File "/usr/lib/python2.7/dist-packages/certbot_nginx/configurator.py", line 242, in choose_vhost
    "https://nginx.org/en/docs/http/server_names.html") % (target_name))
MisconfigurationError: Cannot find a VirtualHost matching domain mysite.ru. In order for Certbot to correctly perform the challenge please add a corresponding server_name directive to your nginx configuration: https://nginx.org/en/docs/http/server_names.html
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
server {
    listen 80;
    server_name mysite.ru www.mysite.ru;
}
```

**Comment by fearrr** [comment]
I would like to add, that I tried completely re-install the certbot package

**Comment by SwartzCr** [comment]
It seems like your nginx config is causing an error preventing certbot from reading it 
`2018-01-09 14:00:55,109:DEBUG:certbot_nginx.parser:Could not parse file: /etc/nginx/nginx.conf due to Expected stringEnd (at char 116), (line:10, col:1)`
See if you can fix up that error, and then it should work hopefully

**Comment by joohoi** [comment]
This issue hasn't been updated for quite a long time, and things have changed quite a bit since. I'm closing this issue as deprecated, but feel free to comment if this is not the case, and we can reopen the issue.
