### ISSUE TITLE
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.

### ISSUE THREAD

**Issue by gamgine** [certbot/certbot#5415]
## My operating system is (include version):
new full reinstall (before is work)
Apache on Debian 9 (stretch) certbot 0.19.0
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
 apt-get install python-certbot-apache -t stretch-backports
## I ran this command and it produced this output:
certbot --apache
## Certbot's behavior differed from what I expected because:
¯\\_(ツ)_/¯
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP 
```
root@212-83-172-83:~# cat /var/log/letsencrypt/letsencrypt.log
2018-01-11 11:10:41,063:DEBUG:certbot.main:certbot version: 0.19.0
2018-01-11 11:10:41,068:DEBUG:certbot.main:Arguments: ['--apache']
2018-01-11 11:10:41,068:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-01-11 11:10:41,119:DEBUG:certbot.log:Root logging level set at 20
2018-01-11 11:10:41,121:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-01-11 11:10:41,122:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2018-01-11 11:10:41,322:DEBUG:certbot_apache.configurator:Apache version is 2.4.25
2018-01-11 11:10:41,838:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.configurator:ApacheConfigurator
Initialized: <certbot_apache.configurator.ApacheConfigurator object at 0x7ff9874b1190>
Prep: True
2018-01-11 11:10:41,840:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.configurator.ApacheConfigurator object at 0x7ff9874b1190> and installer <certbot_apache.configurator.ApacheConfigurator object at 0x7ff9874b1190>
2018-01-11 11:10:41,840:INFO:certbot.plugins.selection:Plugins selected: Authenticator apache, Installer apache
2018-01-11 11:10:41,851:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(status=u'valid', contact=(u'mailto:adm@gamgine.com',), agreement=u'https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf', key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x7ff985e76090>)>)), uri=u'https://acme-v01.api.letsencrypt.org/acme/reg/27392919', new_authzr_uri=u'https://acme-v01.api.letsencrypt.org/acme/new-authz', terms_of_service=u'https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'), 71a505d269e5de2bc990aa392e4efadf, Meta(creation_host=u'212-83-172-83.nitrogroup.fr', creation_dt=datetime.datetime(2018, 1, 11, 10, 50, 16, tzinfo=<UTC>)))>
2018-01-11 11:10:41,854:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2018-01-11 11:10:41,894:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2018-01-11 11:10:42,148:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 562
2018-01-11 11:10:42,150:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 562
Replay-Nonce: gcmXq2Mr1HJO4E0dXhRNZ-DoEUncVEc4us5zjVhZyV8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Thu, 11 Jan 2018 11:10:42 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Thu, 11 Jan 2018 11:10:42 GMT
Connection: keep-alive

{
  "c0XbJV2wVYc": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
2018-01-11 11:10:43,489:INFO:certbot.main:Obtaining a new certificate
2018-01-11 11:10:43,490:DEBUG:acme.client:Requesting fresh nonce
2018-01-11 11:10:43,490:DEBUG:acme.client:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz.
2018-01-11 11:10:43,698:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "HEAD /acme/new-authz HTTP/1.1" 405 0
2018-01-11 11:10:43,699:DEBUG:acme.client:Received response:
HTTP 405
Server: nginx
Content-Type: application/problem+json
Content-Length: 91
Allow: POST
Replay-Nonce: eiFc4dJDDoOPpOPd-CO0OnZsm2x5nwio4KhHCZ1cP5w
Expires: Thu, 11 Jan 2018 11:10:43 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Thu, 11 Jan 2018 11:10:43 GMT
Connection: keep-alive


2018-01-11 11:10:43,699:DEBUG:acme.client:Storing nonce: eiFc4dJDDoOPpOPd-CO0OnZsm2x5nwio4KhHCZ1cP5w
2018-01-11 11:10:43,700:DEBUG:acme.client:JWS payload:
{
  "identifier": {
    "type": "dns",
    "value": "cc.gamgine.com"
  },
  "resource": "new-authz"
}
2018-01-11 11:10:43,709:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz:
{
  "protected": "eyJub25jZSI6ICJlaUZjNGRKRERvT1BwT1BkLUNPME9uWnNtMng1bndpbzRLaEhDWjFjUDV3IiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAiNk5wTjlEYS10cWxBQkRmZjZTX3ZQQ2Jod21xU01YaDZhNzRVanhoZzNBZGZiMTZZb29sOHh5WWdidXBzV1dHeGV1YnZPNVJtNGpPQUY1RE82dE9wbjVuTnRRLURlRG8wZkNKOHdqbGJ5UzI3MG13bnZBV0QxZk5yWGlzMi0xSUs1bllVRmctLXZLQVlBallRbEVmUUhJb3hrSjdOX3NKeGhIVC0xYVpDTGc4UjV4UmlsNWtwelA0NkFmMkN1U2tTYmkwbUtMa0lQNnJaRGNTTFRWMkNGWkp5ZzZqRHUxUUhVWkpacnNTS2c4OWY4MF9odGVuWjdvLXRrSVItazZPcjM2ejZucDhfMzkxSkhqcTVFckJ5T1VwVm5zWGpHT3dKOENNb2xsUkFQZzFNdmh6ZVd5bk1JbFRETUlXdjA0ei1ZRlYxdTVad1o2OXBEeXZCdzlVaXd3In19",
  "payload": "ewogICJpZGVudGlmaWVyIjogewogICAgInR5cGUiOiAiZG5zIiwgCiAgICAidmFsdWUiOiAiY2MuZ2FtZ2luZS5jb20iCiAgfSwgCiAgInJlc291cmNlIjogIm5ldy1hdXRoeiIKfQ",
  "signature": "tPMHVjMxfKfZHVsw8qNUphM2ytf63qTWaq1JjtKCPbClXvgMPFPA1TIaS3n5k81Uj3OqeuxSmMzAqtUDBfrPm4RfkvkM-7aE1vCCAyV5PYG3OU5segDMmNUD2IDTeQyzI4Rpl9a3v6uD561y-ZGR1zm-r4znOW5kRbu0IcHZrXczIwm5hwn7IIOdhAKaoNIa0KdaK58Wj2ZFywI3_jozfDQTMIjFTy7K1yDIpOZ-sMXcKpjm2TnCk3HX4AaDQG-RFXZyounGJPDwA9-y0tgeFUcPr5RBSZN477yf8EejVIuw2sEAIkEmlonx2PBlzdrjFPnsdWKfW-BmigZcr-2UGA"
}
2018-01-11 11:10:43,976:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-authz HTTP/1.1" 201 729
2018-01-11 11:10:43,978:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Content-Type: application/json
Content-Length: 729
Boulder-Requester: 27392919
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Location: https://acme-v01.api.letsencrypt.org/acme/authz/DlLUHBjHJe6iDaSyhWNAxUwnHLlodNLtlfD7N-1iAbk
Replay-Nonce: r_-ZaoT1WMqTGbi9T9cEcLn0lBZ9sZK5Q45kmXXWNNU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Thu, 11 Jan 2018 11:10:43 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Thu, 11 Jan 2018 11:10:43 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "cc.gamgine.com"
  },
  "status": "pending",
  "expires": "2018-01-18T11:10:43.868488727Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/DlLUHBjHJe6iDaSyhWNAxUwnHLlodNLtlfD7N-1iAbk/3054247766",
      "token": "8Brp09kJyvkBwOdAkuTuWC-oUg8xj_hT1acT-CWABy0"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/DlLUHBjHJe6iDaSyhWNAxUwnHLlodNLtlfD7N-1iAbk/3054247767",
      "token": "qjGXb10iAjHkmkjWbh3Rx_tYPjL1j-xpkLGvTObSgaY"
    }
  ],
  "combinations": [
    [
      0
    ],
    [
      1
    ]
  ]
}
2018-01-11 11:10:43,978:DEBUG:acme.client:Storing nonce: r_-ZaoT1WMqTGbi9T9cEcLn0lBZ9sZK5Q45kmXXWNNU
2018-01-11 11:10:43,979:INFO:certbot.auth_handler:Performing the following challenges:
2018-01-11 11:10:43,980:CRITICAL:certbot.auth_handler:Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
2018-01-11 11:10:43,980:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 698, in run
    certname, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 85, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 68, in get_authorizations
    self._choose_challenges(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 103, in _choose_challenges
    self.authzr[dom].body.combinations)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 374, in gen_challenge_path
    return _find_smart_path(challbs, preferences, combinations)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 411, in _find_smart_path
    _report_no_chall_path()
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 442, in _report_no_chall_path
    raise errors.AuthorizationError(msg)
AuthorizationError: Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
```
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
<VirtualHost *:80>
        ServerName cc.gamgine.com
        ServerAdmin adm@gamgine.com
        DocumentRoot "/var/www/sites/gamgine/cc/"

        <Directory "/var/www/sites/gamgine/cc">
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/gamgine/cc-error.log
        CustomLog ${APACHE_LOG_DIR}/gamgine/cc-access.log combined
</VirtualHost>
```

**Comment by gamgine** [comment]
certbot --debug
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache

Which names would you like to activate HTTPS for?
-------------------------------------------------------------------------------
1: cc.gamgine.com
-------------------------------------------------------------------------------
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 1
Obtaining a new certificate
Performing the following challenges:
Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 698, in run
    certname, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 85, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 68, in get_authorizations
    self._choose_challenges(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 103, in _choose_challenges
    self.authzr[dom].body.combinations)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 374, in gen_challenge_path
    return _find_smart_path(challbs, preferences, combinations)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 411, in _find_smart_path
    _report_no_chall_path()
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 442, in _report_no_chall_path
    raise errors.AuthorizationError(msg)
AuthorizationError: Client with the currently selected authenticator does not support any combination of challenges that will satisfy the CA.
Please see the logfiles in /var/log/letsencrypt for more details.
```

**Comment by kc9jud** [comment]
Let's Encrypt is currently in the process of mitigating a security vulnerability. TLS-SNI-01 authentication is to be permanently disabled. See these links:

https://community.letsencrypt.org/t/2018-01-09-issue-with-tls-sni-01-and-shared-hosting-infrastructure/49996
https://community.letsencrypt.org/t/2018-01-11-update-regarding-acme-tls-sni-and-shared-hosting-infrastructure/50188

**Comment by kc9jud** [comment]
Duplicate of #5405.

**Comment by bmw** [comment]
Closing as a duplicate.
