### ISSUE TITLE
Certbot standalone http challenge fails with 404

### ISSUE THREAD

**Issue by opsydev** [certbot/certbot#5432]
## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
ppa:certbot/certbot
apt-get install certbot
certbot 0.19.0

## I ran this command and it produced this output:
`certbot certonly --standalone --cert-name some_name -d fqdn.of.the.server --agree-tos --email operations@company.com --keep-until-expiring --expand -n`

## Certbot's behavior differed from what I expected because:
Expected to get a cert as usual but I get 

```
 Invalid response from http://fqdn.of.the.server/.well-known/acme-challenge/t4-rYur_gOYHYEI3Vpszbs8wDBr3Epa6DK-lWHLoZhY: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p"
```

I have ensured the DNS is pointing correctly

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2018-01-16 02:11:13,015:DEBUG:certbot.main:certbot version: 0.19.0
2018-01-16 02:11:13,016:DEBUG:certbot.main:Arguments: ['--standalone', '--cert-name', 'server_name', '-d', 'fqdn.of.the.server', '--agree-tos', '--email', 'operations@company.com', '--keep-until-expiring', '--expand', '-n']
2018-01-16 02:11:13,016:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-01-16 02:11:13,052:DEBUG:certbot.log:Root logging level set at 20
2018-01-16 02:11:13,053:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-01-16 02:11:13,054:DEBUG:certbot.plugins.selection:Requested authenticator standalone and installer None
2018-01-16 02:11:13,416:DEBUG:certbot.plugins.selection:Single candidate plugin: * standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x7f2bfd3ce5d0>
Prep: True
2018-01-16 02:11:13,417:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x7f2bfd3ce5d0> and installer None
2018-01-16 02:11:13,417:INFO:certbot.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2018-01-16 02:11:13,424:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(status=None, contact=(u'mailto:operations@company.com',), agreement=u'https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf', key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x7f2bfd3ce610>)>)), uri=u'https://acme-v01.api.letsencrypt.org/acme/reg/18420175', new_authzr_uri=u'https://acme-v01.api.letsencrypt.org/acme/new-authz', terms_of_service=u'https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf'), c99975bb3259f3b317df8c0a7481232d, Meta(creation_host=u'fqdn.of.the.server', creation_dt=datetime.datetime(2017, 7, 6, 5, 12, 34, tzinfo=<UTC>)))>
2018-01-16 02:11:13,425:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2018-01-16 02:11:13,427:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2018-01-16 02:11:13,699:DEBUG:urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 562
2018-01-16 02:11:13,701:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 562
Replay-Nonce: wYNBHe44ogqm0NqVgu0v-1lD2V7uD6Asy-qLcfDHmpk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Tue, 16 Jan 2018 02:11:13 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 16 Jan 2018 02:11:13 GMT
Connection: keep-alive

{
  "bM9_7m_AjJA": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
2018-01-16 02:11:13,702:INFO:certbot.main:Obtaining a new certificate
2018-01-16 02:11:13,703:DEBUG:acme.client:Requesting fresh nonce
2018-01-16 02:11:13,703:DEBUG:acme.client:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz.
2018-01-16 02:11:13,890:DEBUG:urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "HEAD /acme/new-authz HTTP/1.1" 405 0
2018-01-16 02:11:13,892:DEBUG:acme.client:Received response:
HTTP 405
Server: nginx
Content-Type: application/problem+json
Content-Length: 91
Allow: POST
Replay-Nonce: titrAkmsxS8o-V2sO2vnVJV3MNeZIhY1wzxXy79F2SM
Expires: Tue, 16 Jan 2018 02:11:13 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 16 Jan 2018 02:11:13 GMT
Connection: keep-alive


2018-01-16 02:11:13,892:DEBUG:acme.client:Storing nonce: titrAkmsxS8o-V2sO2vnVJV3MNeZIhY1wzxXy79F2SM
2018-01-16 02:11:13,892:DEBUG:acme.client:JWS payload:
{
  "identifier": {
    "type": "dns",
    "value": "fqdn.of.the.server"
  },
  "resource": "new-authz"
}
2018-01-16 02:11:13,902:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz:
{
  "protected": "eyJub25jZSI6ICJ0aXRyQWttc3hTOG8tVjJzTzJ2blZKVjNNTmVaSWhZMXd6eFh5NzlGMlNNIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAieVNmVTZvRFFjUk5VQkplWDZiWG1UQS11QzF2YVFVMS1oTDRjRk92Ymh1WlFITFRVQWluSUN0dmk3c2oySUM3UGc3S2JFTWlJb1JfcTFnb0lLWXlGMlpIc1RHemhMVmxFVnFkd3FHa3dmcFk1eVR3bDJ6UDVsLTV2R1dWbjBWWmlKWEF1T2ZNMmdMQVRGb0NjV1RHdmhVcGhUTHlvN0ZueU5qZWo0YjZLX2lLZEpYNC1GekVRTnVCZG03X0xGMnJUYW4xUmZyQklvMUFpZUdlUzdmdWNMQjUwdWRUbkttYUpyUUlUNGNHcERKQ2otbjMzelp5WVU5YXRtZXBYMUpOazVuUDBCR0NCNzZpQjhFeW9Qb1B6cFp3ajYtVjdHT2NiZUZBcm5YcG1UZjlwNHlxeFE2a2ZSNGtaTjBiZHFxWHp2a2kzLWtVVjB4U3dBS2ZlZEtMNUJRIn19",
  "payload": "ewogICJpZGVudGlmaWVyIjogewogICAgInR5cGUiOiAiZG5zIiwgCiAgICAidmFsdWUiOiAiZG9ja2VyLnN2Yy5zaG9yZS5jYSIKICB9LCAKICAicmVzb3VyY2UiOiAibmV3LWF1dGh6Igp9",
  "signature": "fDFn1eXAo6JSMsVpXaofqTsZplEywqB_MJC1XI0uGkXNcGtp2ttV8CE6u3j7DKero0YSpxrpKcPQH0jYXZGBlIOpq_PtBkE-Pt-rPJwsIcNdKlJDdHNaxMopDmWaQLj0VggOaHg8nCd4M6uhjP4cnqj9Fv3PuFzxoA12lFTCEOKvYLNdCI8n81HLz-nDHmUoahvxnSbMjBJ2MppgrGYCjTonLhUR8-vNH8kr9Ivrk3ks_JC8O0fiQR1jl-TNTAobDmIjFyR_-CgBta4o2TGeABAH6NZW8p2iaxaeWMubHuvca2hxo0diHnmctiMAX08z9T7i6FituBbK9DBRqSE3_Q"
}
2018-01-16 02:11:14,322:DEBUG:urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/new-authz HTTP/1.1" 201 734
2018-01-16 02:11:14,324:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Content-Type: application/json
Content-Length: 734
Boulder-Requester: 18420175
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Location: https://acme-v01.api.letsencrypt.org/acme/authz/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0
Replay-Nonce: P33uZCjO16nbAOXbS9xwUU0dO8TabBCl-J0GltGjkqY
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Tue, 16 Jan 2018 02:11:14 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 16 Jan 2018 02:11:14 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "fqdn.of.the.server"
  },
  "status": "pending",
  "expires": "2018-01-23T02:11:14.219752291Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0/3110212763",
      "token": "vKmSzu9mS3l3BaAfpJCeJhMubhYGR1NPEogzT_hNxb8"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0/3110212767",
      "token": "JfCkT4w2kGr2i5DuHqaIGnkQTEtGTvJ5kWVhBladOEQ"
    }
  ],
  "combinations": [
    [
      1
    ],
    [
      0
    ]
  ]
}
2018-01-16 02:11:14,325:DEBUG:acme.client:Storing nonce: P33uZCjO16nbAOXbS9xwUU0dO8TabBCl-J0GltGjkqY
2018-01-16 02:11:14,326:INFO:certbot.auth_handler:Performing the following challenges:
2018-01-16 02:11:14,326:INFO:certbot.auth_handler:http-01 challenge for fqdn.of.the.server
2018-01-16 02:11:14,327:DEBUG:acme.standalone:Failed to bind to :80 using IPv4
2018-01-16 02:11:14,336:INFO:certbot.auth_handler:Waiting for verification...
2018-01-16 02:11:14,337:DEBUG:acme.client:JWS payload:
{
  "keyAuthorization": "vKmSzu9mS3l3BaAfpJCeJhMubhYGR1NPEogzT_hNxb8.hgLyg9AZW2WGzOyuo3itN1xowwkOnFe3K8Uak32atgU",
  "type": "http-01",
  "resource": "challenge"
}
2018-01-16 02:11:14,346:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/challenge/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0/3110212763:
{
  "protected": "eyJub25jZSI6ICJQMzN1WkNqTzE2bmJBT1hiUzl4d1VVMGRPOFRhYkJDbC1KMEdsdEdqa3FZIiwgImFsZyI6ICJSUzI1NiIsICJqd2siOiB7ImUiOiAiQVFBQiIsICJrdHkiOiAiUlNBIiwgIm4iOiAieVNmVTZvRFFjUk5VQkplWDZiWG1UQS11QzF2YVFVMS1oTDRjRk92Ymh1WlFITFRVQWluSUN0dmk3c2oySUM3UGc3S2JFTWlJb1JfcTFnb0lLWXlGMlpIc1RHemhMVmxFVnFkd3FHa3dmcFk1eVR3bDJ6UDVsLTV2R1dWbjBWWmlKWEF1T2ZNMmdMQVRGb0NjV1RHdmhVcGhUTHlvN0ZueU5qZWo0YjZLX2lLZEpYNC1GekVRTnVCZG03X0xGMnJUYW4xUmZyQklvMUFpZUdlUzdmdWNMQjUwdWRUbkttYUpyUUlUNGNHcERKQ2otbjMzelp5WVU5YXRtZXBYMUpOazVuUDBCR0NCNzZpQjhFeW9Qb1B6cFp3ajYtVjdHT2NiZUZBcm5YcG1UZjlwNHlxeFE2a2ZSNGtaTjBiZHFxWHp2a2kzLWtVVjB4U3dBS2ZlZEtMNUJRIn19",
  "payload": "ewogICJrZXlBdXRob3JpemF0aW9uIjogInZLbVN6dTltUzNsM0JhQWZwSkNlSmhNdWJoWUdSMU5QRW9nelRfaE54YjguaGdMeWc5QVpXMldHek95dW8zaXROMXhvd3drT25GZTNLOFVhazMyYXRnVSIsIAogICJ0eXBlIjogImh0dHAtMDEiLCAKICAicmVzb3VyY2UiOiAiY2hhbGxlbmdlIgp9",
  "signature": "mbbqkN7l36K_ECemh4GJQTekM3Tu-zEthfE79MrSz0ViqIVdbG5P3R_fcRNppt65fNNFqk6l2HVgZ7SdopM07UN99yQ7-p1TBpYliIH1JnXl-HdirGjIChZqvW3fK7E7e5KhBDZ8dVZ7hnfENbHDFaRXP6m5g2qg_fPsWM4qVv4psTtl-h4Q4ynWL4d_D1kCsE7iBCcS-irKlgsOsBko0nXF7UFlKwgEYX4uopuaRN0tNsaY3oCXVDKjKQEJfOanrWFnzmFo4XNH3mjEDYnqWgTOluaneFKp1T6-LFmwP0JKgMkpIdanI6FxwB7c6oOSIPbwm4K13YG_Bd89D_0n6Q"
}
2018-01-16 02:11:14,838:DEBUG:urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "POST /acme/challenge/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0/3110212763 HTTP/1.1" 202 336
2018-01-16 02:11:14,839:DEBUG:acme.client:Received response:
HTTP 202
Server: nginx
Content-Type: application/json
Content-Length: 336
Boulder-Requester: 18420175
Link: <https://acme-v01.api.letsencrypt.org/acme/authz/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0>;rel="up"
Location: https://acme-v01.api.letsencrypt.org/acme/challenge/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0/3110212763
Replay-Nonce: nMv2ft6po-1f3_QDjoFPcx-FOMOY180xa_P4nhKhIZk
Expires: Tue, 16 Jan 2018 02:11:14 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 16 Jan 2018 02:11:14 GMT
Connection: keep-alive

{
  "type": "http-01",
  "status": "pending",
  "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0/3110212763",
  "token": "vKmSzu9mS3l3BaAfpJCeJhMubhYGR1NPEogzT_hNxb8",
  "keyAuthorization": "vKmSzu9mS3l3BaAfpJCeJhMubhYGR1NPEogzT_hNxb8.hgLyg9AZW2WGzOyuo3itN1xowwkOnFe3K8Uak32atgU"
}
2018-01-16 02:11:14,840:DEBUG:acme.client:Storing nonce: nMv2ft6po-1f3_QDjoFPcx-FOMOY180xa_P4nhKhIZk
2018-01-16 02:11:17,844:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/acme/authz/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0.
2018-01-16 02:11:18,201:DEBUG:urllib3.connectionpool:https://acme-v01.api.letsencrypt.org:443 "GET /acme/authz/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0 HTTP/1.1" 200 1706
2018-01-16 02:11:18,203:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 1706
Link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
Replay-Nonce: ljZpuIFtGpjrNRTj9ChMHuUS1jeud7rdkaOSj54Ycdw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Tue, 16 Jan 2018 02:11:18 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 16 Jan 2018 02:11:18 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "fqdn.of.the.server"
  },
  "status": "invalid",
  "expires": "2018-01-23T02:11:14Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:acme:error:unauthorized",
        "detail": "Invalid response from http://fqdn.of.the.server/.well-known/acme-challenge/vKmSzu9mS3l3BaAfpJCeJhMubhYGR1NPEogzT_hNxb8: \"\u003c!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\"\u003e\n\u003chtml\u003e\u003chead\u003e\n\u003ctitle\u003e404 Not Found\u003c/title\u003e\n\u003c/head\u003e\u003cbody\u003e\n\u003ch1\u003eNot Found\u003c/h1\u003e\n\u003cp\"",
        "status": 403
      },
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0/3110212763",
      "token": "vKmSzu9mS3l3BaAfpJCeJhMubhYGR1NPEogzT_hNxb8",
      "keyAuthorization": "vKmSzu9mS3l3BaAfpJCeJhMubhYGR1NPEogzT_hNxb8.hgLyg9AZW2WGzOyuo3itN1xowwkOnFe3K8Uak32atgU",
      "validationRecord": [
        {
          "url": "http://fqdn.of.the.server/.well-known/acme-challenge/vKmSzu9mS3l3BaAfpJCeJhMubhYGR1NPEogzT_hNxb8",
          "hostname": "fqdn.of.the.server",
          "port": "80",
          "addressesResolved": [
            "159.203.50.222"
          ],
          "addressUsed": "159.203.50.222",
          "addressesTried": []
        }
      ]
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/DOmnsYz8sHm77KS1Uk6yBXCv8Ues0JRrpmqzaMygCi0/3110212767",
      "token": "JfCkT4w2kGr2i5DuHqaIGnkQTEtGTvJ5kWVhBladOEQ"
    }
  ],
  "combinations": [
    [
      1
    ],
    [
      0
    ]
  ]
}
2018-01-16 02:11:18,204:DEBUG:certbot.reporter:Reporting to user: The following errors were reported by the server:

Domain: fqdn.of.the.server
Type:   unauthorized
Detail: Invalid response from http://fqdn.of.the.server/.well-known/acme-challenge/vKmSzu9mS3l3BaAfpJCeJhMubhYGR1NPEogzT_hNxb8: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p"

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address.
2018-01-16 02:11:18,205:INFO:certbot.auth_handler:Cleaning up challenges
2018-01-16 02:11:18,206:DEBUG:certbot.plugins.standalone:Stopping server at :::80...
2018-01-16 02:11:18,340:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 861, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 786, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 85, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 357, in obtain_and_enroll_certificate
    certr, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/dist-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 81, in get_authorizations
    self._respond(resp, best_effort)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 138, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/usr/lib/python2.7/dist-packages/certbot/auth_handler.py", line 202, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
FailedChallenges: Failed authorization procedure. fqdn.of.the.server (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://fqdn.of.the.server/.well-known/acme-challenge/vKmSzu9mS3l3BaAfpJCeJhMubhYGR1NPEogzT_hNxb8: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p"
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A I am using --standalone

**Comment by SwartzCr** [comment]
I think you want to use the webroot plugin, since it seems that you're already running a webserver
standalone causes the certbot client to start a webserver to answer requests from the CA
The webroot authenticator will host a file on your existing webserver.
additionally if you're running apache or nginx you can use those authenticators instead

**Comment by opsydev** [comment]
This is run as part of a chef recipe that is used across multiple servers. So I want to stick to standalone. 
I did resolve this issue by re-installing cerbot `apt-get --purge certbot` `apt-get install certbot`. Not sure why that fixed it 🙁 
Since the version numbers did not change.
