### ISSUE TITLE
Certbot on Debian stretchy not running (stretchy-backports)

### ISSUE THREAD

**Issue by inglor** [certbot/certbot#5434]
## My operating system is (include version):
```
$ cat /etc/issue.net
Debian GNU/Linux 9
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`$ sudo apt-get install python-certbot-apache -t stretch-backports`

## I ran this command and it produced this output:
```
$ certbot
certbot
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 16, in <module>
    from certbot import account
  File "/usr/lib/python2.7/dist-packages/certbot/account.py", line 17, in <module>
    from acme import messages
  File "/usr/lib/python2.7/dist-packages/acme/messages.py", line 46, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```
## Certbot's behavior differed from what I expected because:
I was expecting it to work properly.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
No logs available.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not even reaching this point.

## Package versions
```
# apt-cache policy certbot
certbot:
  Installed: 0.19.0-1~bpo9+1
  Candidate: 0.19.0-1~bpo9+1
  Version table:
     0.19.0-1 550
        550 http://ftp.uk.debian.org/debian testing/main amd64 Packages
 *** 0.19.0-1~bpo9+1 660
        660 http://ftp.uk.debian.org/debian stretch-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     0.10.2-1 650
        650 http://ftp.uk.debian.org/debian stable/main amd64 Packages
# apt-cache policy python-acme
python-acme:
  Installed: 0.19.0-1~bpo9+1
  Candidate: 0.19.0-1~bpo9+1
  Version table:
     0.19.0-1 550
        550 http://ftp.uk.debian.org/debian testing/main amd64 Packages
 *** 0.19.0-1~bpo9+1 660
        660 http://ftp.uk.debian.org/debian stretch-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     0.10.2-1 650
        650 http://ftp.uk.debian.org/debian stable/main amd64 Packages
# apt-cache policy python-six
python-six:
  Installed: 1.10.0-3
  Candidate: 1.10.0-3
  Version table:
     1.11.0-1 550
        550 http://ftp.uk.debian.org/debian testing/main amd64 Packages
 *** 1.10.0-3 650
        650 http://ftp.uk.debian.org/debian stable/main amd64 Packages
        100 /var/lib/dpkg/status
```
## Repositories enabled
```
# cat /etc/apt/sources.list.d/stable.list
deb http://ftp.uk.debian.org/debian/ stable main contrib non-free
deb http://ftp.uk.debian.org/debian/ stable-updates main contrib non-free
deb http://ftp.uk.debian.org/debian/ stretch-backports main contrib non-free
```

**Comment by SwartzCr** [comment]
@hlieberman any thoughts?

**Comment by joohoi** [comment]
This issue hasn't been updated for quite a long time, and things have changed quite a bit since. I'm closing this issue as deprecated, but feel free to comment if this is not the case, and we can reopen the issue.
