### ISSUE TITLE
Could not install certs for apache default installation

### ISSUE THREAD

**Issue by Hipska** [certbot/certbot#5495]
## My operating system is (include version):
CentOS 7.4

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`yum install certbot-apache`

## I ran this command and it produced this output:
`certbot run -a webroot -i apache -w /var/www/html -d example.com` (replaced actual hostname by example.com)
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer apache
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Cert not yet due for renewal

You have an existing certificate that has exactly the same domains or certificate name you requested and isn't close to expiry.
(ref: /etc/letsencrypt/renewal/example.com.conf)

What would you like to do?
-------------------------------------------------------------------------------
1: Attempt to reinstall this existing certificate
2: Renew & replace the cert (limit ~5 per 7 days)
-------------------------------------------------------------------------------
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
Keeping the existing certificate

We were unable to find a vhost with a ServerName or Address of example.com.
Which virtual host would you like to choose?
(note: conf files with multiple vhosts are not yet supported)
-------------------------------------------------------------------------------
1: ssl.conf                       |                       | HTTPS | Enabled
-------------------------------------------------------------------------------
Press 1 [enter] to confirm the selection (press 'c' to cancel): 1
Deploying Certificate for example.com to VirtualHost /etc/httpd/conf.d/ssl.conf
Error while running apachectl graceful.

Job for httpd.service invalid.

Rolling back to previous server configuration...
Error while running apachectl graceful.

Job for httpd.service invalid.

Encountered exception during recovery
Error while running apachectl graceful.

Job for httpd.service invalid.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/error_handler.py", line 100, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 557, in _rollback_and_restart
    self.installer.restart()
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1793, in restart
    self._reload()
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1804, in _reload
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apachectl graceful.

Job for httpd.service invalid.

Error while running apachectl graceful.

Job for httpd.service invalid.


IMPORTANT NOTES:
 - An error occurred and we failed to restore your config and restart
   your server. Please submit a bug report to
   https://github.com/letsencrypt/letsencrypt
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/example.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/example.com/privkey.pem
   Your cert will expire on 2018-04-25. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
```

## Certbot's behavior differed from what I expected because:
It was unable to install SSL certificate for apache.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
It is on an apache without virtual host set. I did set `ServerName` in `/etc/httpd/conf/httpd.conf`

**Comment by Hipska** [comment]
Nevermind, it appears that apache was having problems. It's solved now.
