### ISSUE TITLE
certbot blindly adds port 443 to apache conf

### ISSUE THREAD

**Issue by poizan42** [certbot/certbot#5517]
## My operating system is (include version):
debian jessie 8.10

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
    dy:/home/poizan# ./certbot-auto
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator apache, Installer apache

    Which names would you like to activate HTTPS for?
    -------------------------------------------------------------------------------
    (redacted)
    8: poizan.dk
    (redacted)
    10: www.poizan.dk
    (redacted)
    -------------------------------------------------------------------------------
    Select the appropriate numbers separated by commas and/or spaces, or leave input
    blank to select all options shown (Enter 'c' to cancel): 8 10
    Cert is due for renewal, auto-renewing...
    Renewing an existing certificate
    Performing the following challenges:
    tls-sni-01 challenge for poizan.dk
    tls-sni-01 challenge for www.poizan.dk
    Waiting for verification...
    Cleaning up challenges
    Error while running apache2ctl graceful.
    httpd not running, trying to start
    Action 'graceful' failed.
    The Apache error log may have more information.

    (98)Address already in use: AH00072: make_sock: could not bind to address [::]:443
    (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:443
    no listening sockets available, shutting down
    AH00015: Unable to open logs

    Error while running apache2ctl graceful.
    httpd not running, trying to start
    Action 'graceful' failed.
    The Apache error log may have more information.

    (98)Address already in use: AH00072: make_sock: could not bind to address [::]:443
    (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:443
    no listening sockets available, shutting down
    AH00015: Unable to open logs

    IMPORTANT NOTES:
     - The following errors were reported by the server:

       Domain: www.poizan.dk
       Type:   connection
       Detail: Error getting validation data

       Domain: poizan.dk
       Type:   connection
       Detail: Error getting validation data

       To fix these errors, please make sure that your domain name was
       entered correctly and the DNS A/AAAA record(s) for that domain
       contain(s) the right IP address. Additionally, please check that
       your computer has a publicly routable IP address and that no
       firewalls are preventing the server from communicating with the
       client. If you're using the webroot plugin, you should also verify
       that you are serving files from the webroot path you provided.

## Certbot's behavior differed from what I expected because:
Content of /etc/apache2/ports.conf before running certbot:

    # If you just change the port or add more ports here, you will likely also
    # have to change the VirtualHost statement in
    # /etc/apache2/sites-enabled/000-default.conf

    Listen 80

    <IfModule ssl_module>
            Listen 10443
    </IfModule>

    <IfModule mod_gnutls.c>
            Listen 10443
    </IfModule>

Contents of /ec/apache2/ports.conf after running certbot:

    # If you just change the port or add more ports here, you will likely also
    # have to change the VirtualHost statement in
    # /etc/apache2/sites-enabled/000-default.conf

    Listen 80

    <IfModule ssl_module>
            Listen 10443
    </IfModule>

    <IfModule mod_gnutls.c>
            Listen 10443
    </IfModule>

    # vim: syntax=apache ts=4 sw=4 sts=4 sr noet
    <IfModule mod_ssl.c>
    Listen 443
    </IfModule>

certbot just blindly adds port 443. If apache is configured to not listen on port 443 then there is probably a very good reason for that, **under no circumstances should certbot ever automatically add port 443** as it breaks the current apache configuration if anything else is listening on port 443. Either should certbot query the user interactively for information about mapping of local port to external port or it should fail and ask the user to run certbot with manually given arguments.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Not relevant

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

Not relevant

**Comment by SwartzCr** [comment]
@joohoi thoughts?

**Comment by joohoi** [comment]
I'm sorry you are having problems with Certbot @poizan42 .

First and foremost, I really think we need to add `Listen` statements in order to migrate a HTTP only configurations to HTTPS. That said, this issue is still spot on, as in this case we're failing to actually deploy certificates in this kind of configuration. There are actually two different issues under this one. One for situations where user doesn't have an active HTTPS configuration, but would like to bind HTTPS to a non-standard port. The other one would be this exact issue you are facing.

As we need to define a port for Apache to use for the new HTTPS `VirtualHost`s, a possible fix for this particular issue would be:
 - Add a CLI parameter that allows user to define the port that HTTPS should be served on. We already have a functionality in place that checks if Apache listens to a specific port, and add a `Listen` statement if not. Currently this is fixed to `443` which is the reason behind this issue.

And perhaps for the configurations that already are serving HTTPS `VirtualHost`s:
 - If a HTTPS enabled `VirtualHost` is found anywhere in the active configuration, use port from that configuration for setting up the newly created `VirtualHost`s. If we're configuring certificates for pre-existing `VirtualHost`, skip the `Listen` statement addition completely.

**Comment by poizan42** [comment]
Let me be a clear that I'm not complaining that this functionally exists, but that it happens automatically. I believe that the default configuration in most distros has the <IfModule> guarded Listen 443, so if that is not there then it is most likely because the user has intentionally changed it. Everything would be fine if it just asked the user what to do (and to give a cli option in the future for automatic renewal).

> * Add a CLI parameter that allows user to define the port that HTTPS should be served on. We already have a functionality in place that checks if Apache listens to a specific port, and add a Listen statement if not. Currently this is fixed to 443 which is the reason behind this issue.

Actually --tls-sni-01-port does half of it. The following worked for me:

    ./certbot-auto --apache --tls-sni-01-port 10443 -d poizan.dk -d www.poizan.dk

This renewed the certificate successfully. However it still added the Listen 443 to ports.conf afterwards.

**Comment by nainno** [comment]
Hello,

Same issue here.
If you remove fro port.conf 
`Listen 443`

The next day it comes back and your website are not avaible.

**Comment by waldoj** [comment]
I'm having the same problem here, though to different effect.

Running Cerbot 0.23.0 and Apache 2.2.22, the twice-daily cron job inserts a stanza into `ports.conf` that includes a duplicative `Listen 443` and reloads Apache. The duplicate `Listen 443` causes Apache to choke, logging `(98)Address already in use: make_sock: could not bind to address 0.0.0.0:443`. My web server goes down until I can remove the Certbot-added duplicate `Listen 443`. This has happened twice a day for the past three days.

At this point, I'm just going to have `certbot-auto` run on a less-frequent cron job, until I can figure out how to tell Certbot to leave Apache's config files alone.

**Comment by joohoi** [comment]
This happens when Certbot is unable to detect all the loaded modules and when the `Listen 443` statement is wrapped inside of `<IfModule the_module_that_certbot_wasnt_able_to_detect>`. As a quick workaround, I would suggest moving the `Listen 443` statement to the top level of the configuration, making sure that Certbot sees it and hence does not try to re-add it.

**Comment by waldoj** [comment]
I regret your promising suggestion didn't fix the problem, @joohoi. I stripped `ports.conf` down to four lines:

```
NameVirtualHost *:80
Listen 80
NameVirtualHost *:443
Listen 443
```

Then I re-ran `/usr/local/bin/certbot-auto renew --quiet --no-self-upgrade`:

```
Requesting to rerun /usr/local/bin/certbot-auto with root privileges...
Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

Warning: DocumentRoot [/var/lib/letsencrypt/tls_sni_01_page/] does not exist
(98)Address already in use: make_sock: could not bind to address 0.0.0.0:443
no listening sockets available, shutting down
Unable to open logs

Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

(98)Address already in use: make_sock: could not bind to address 0.0.0.0:443
no listening sockets available, shutting down
Unable to open logs

Encountered exception during recovery
Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

(98)Address already in use: make_sock: could not bind to address 0.0.0.0:443
no listening sockets available, shutting down
Unable to open logs
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/error_handler.py", line 103, in _call_registered
    self.funcs[-1]()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 308, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 2132, in cleanup
    self.restart()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1995, in restart
    self._reload()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 2023, in _reload
    raise errors.MisconfigurationError(error)
MisconfigurationError: Error while running apache2ctl graceful.
httpd not running, trying to start
Action 'graceful' failed.
The Apache error log may have more information.

(98)Address already in use: make_sock: could not bind to address 0.0.0.0:443
no listening sockets available, shutting down
Unable to open logs
```

One of the four lines of `ports.conf` had been erased (`Listen 443`), with `ports.conf` now reading:

```
NameVirtualHost *:80
Listen 80

NameVirtualHost *:443

<IfModule mod_ssl.c>
    Listen 443
    # If you add NameVirtualHost *:443 here, you will also have to change
    # the VirtualHost statement in /etc/apache2/sites-available/default-ssl
    # to <VirtualHost *:443>
    # Server Name Indication for SSL named virtual hosts is currently not
    # supported by MSIE on Windows XP.
    #Listen *:443 http
    #NameVirtualHost *:443
Listen *:443 http
</IfModule>

<IfModule mod_gnutls.c>
    NameVirtualHost *:443
    Listen 443
</IfModule>
```

I'll continue to experiment, to try to identify what modifications might stop this behavior. So far, nothing has done the trick.

**Comment by joohoi** [comment]
This looks an unfortunate loop with Certbot's configuration reverter. When the previous run fails, in the beginning of the next one Certbot will try to revert the configuration to the initial state, and hence your changes get overridden with the initial configuration there. 

I would suggest running certbot: `/usr/local/bin/certbot-auto --apache`, and exiting it gracefully (by pressing 'c' when asked to cancel). After that redo your manual modifications and try to re-run the renewal process.

**Comment by waldoj** [comment]
👏 That fixed the problem very nicely. Thank you so much! I hope it helps folks who find this issue in the future.

**Comment by tdebatty** [comment]
+1 I'm running Apache on port 444 and OpenVPN on port 443.
At each renew, certbot adds the following lines to ports.conf:
```
<IfModule mod_ssl.c>
Listen 443
</IfModule>
```
As a result, Apache cannot restart (port already in use), and my web server is completely down...

**Comment by hans2520** [comment]
I just use my crontab to re-copy a permanent "good" backup config file back over what LE does and then restart apache... 

i.e.
#!/bin/bash

/etc/letsencrypt/certbot-auto renew
cp -fp /etc/httpd/conf/httpd.conf.bak /etc/httpd/conf/httpd.conf
service httpd restart

**Comment by sjlongland** [comment]
Just stumbled on this myself.

We use `sniproxy` to bounce connections to the appropriate back-end server, thus Apache *cannot* bind to port 443, as `sniproxy` is listening there.

For that reason, we have Apache listening on a different port.  This appears to be a sin in the church of `certbot`, as the moment I turn my back on it, it tries to rectify this "wrong" and breaks Apache.  I find my site is inaccessible due to Apache being unable to bind to port 443 like I specifically asked it *NOT* to in the first place.

To be clear, my cron job calls `certbot renew`, not `certbot renew_and_bugger_up_apache`.  Perhaps you might consider the `_and_bugger_up_apache` as a new optional feature rather than making it a core requirement as this is worse than having the site unsecured!

**Comment by sjlongland** [comment]
A work-around:
```
12 10   * * * root /usr/local/sbin/certbot-auto renew --post-hook "sed -i -e '/Listen 443/ d' /etc/apache2/ports.conf && /etc/init.d/apache2 restart"
```
That's the entry in my `/etc/crontab` that un-does this screw-up.

**Comment by mrsof** [comment]
> +1 I'm running Apache on port 444 and OpenVPN on port 443.
> At each renew, certbot adds the following lines to ports.conf:
> 
> ```
> <IfModule mod_ssl.c>
> Listen 443
> </IfModule>
> ```
> As a result, Apache cannot restart (port already in use), and my web server is completely down...

Same problem here

**Comment by mrsof** [comment]
thx @sjlongland but for me, I had to add 'Listen 443' again.

` 24 12 10 * * * /home/dinabazar/Documents/certbot-auto renew --post-hook "sed -i -e '0,/Listen 443/{/Listen 443/d;}' /etc/apache2/ports.conf && sed '/\<IfModule mod_ssl.c\>/a Listen 443' /etc/apache2/ports.conf && service apache2 restart`

**Comment by zege-at** [comment]
For complicated setups I  issue my certs with `certbot certonly --webroot -d DOMAIN --email EMAIL -w /var/www/_letsencrypt -n --agree-tos --force-renewal`
This way I can set up my webservers and services the way I want and certbot doesn't touch any configuration. The downside is if you have to add a new domain to an existing cert you have to manually re-run the command with the new domain added.

Official Docs also mention a different way of certbot not touching your apache configuration: `certbot certonly --apache`

**Comment by ashvin-bhuttoo** [comment]
I have openvpn running on port 443 and apache https running on port 4343, certbot fails to recognize that I customized my https port, it adds ports 443 to my ports.conf and apache fails to reload after certificate renew.

**Comment by maximeghislainetundi** [comment]
![ingenieur](https://user-images.githubusercontent.com/55503565/187099369-6798ef77-b5ac-4cc4-85bb-665691cc8093.jpeg)
