### ISSUE TITLE
Certbot PPA version no longer working on Ubuntu 14.04

### ISSUE THREAD

**Issue by sunitknandi** [certbot/certbot#5569]
After a software update via `apt-get upgrade` my certbot no longer works. My older version used to be 0.19 which worked perfectly, but the newer version 0.21.1 does not even start due to `ValueError: 'new_authzr_uri' in __slots__ conflicts with class variable`. Would you look into this and let me know how to fix it?

## My operating system is (include version):
```
root@mail:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
```
add-apt-repository ppa:certbot/certbot
apt-get update
apt-get install certbot
```

## I ran this command and it produced this output:
```
root@mail:~# certbot
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.21.1', 'console_scripts', 'certbot')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 17, in <module>
    from certbot import account
  File "/usr/lib/python3/dist-packages/certbot/account.py", line 122, in <module>
    class RegistrationResourceWithNewAuthzrURI(messages.RegistrationResource):
  File "/usr/local/lib/python3.4/dist-packages/acme/jose/json_util.py", line 181, in __new__
    return abc.ABCMeta.__new__(mcs, name, bases, dikt)
  File "/usr/lib/python3.4/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
ValueError: 'new_authzr_uri' in __slots__ conflicts with class variable
```

## Certbot's behavior differed from what I expected because:
Usually I get
```
root@mail:~# certbot
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Certbot doesn't know how to automatically configure the web server on this system. However, it can still get a certificate for you. Please run "certbot certonly" to do so. You'll need to manually configure your web server to use the resulting certificate.
```
but now it does not even start

**Comment by sunitknandi** [comment]
@ohemorange and @bmw , here is the output with Python 2.7
```
root@mail:~# alias python=python2
root@mail:~# python $(which certbot)
Traceback (most recent call last):
  File "/usr/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'certbot==0.21.1' distribution was not found and is required by the application
```

**Comment by bmw** [comment]
> @bmw did we test switching to josepy on python3.4?

Yes. Now that we've removed josepy from this repo, all of our normal tests use josepy rather than the previous JOSE code that was embedded in ACME including our Travis tests that run with Python 3.4 on the test-everything branch.

@sunitknandi, I think your problem is mixed packages from your `apt` and `pip`. If you look at your initial traceback, you'll see packages from `/usr/local/lib` being used. I suspect if you remove those packages, the problem will go away.

The problem in the 2nd traceback is the PPA now only provides a Python 3 package so when you try to run Certbot with Python 2, Python can't find the Certbot packages to import.

**Comment by sunitknandi** [comment]
@bmw I now get this after removing custom installed packages.
```
root@mail:~# certbot
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.21.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 17, in <module>
    from certbot import account
  File "/usr/lib/python3/dist-packages/certbot/account.py", line 122, in <module>
    class RegistrationResourceWithNewAuthzrURI(messages.RegistrationResource):
  File "/usr/local/lib/python3.4/dist-packages/acme/jose/json_util.py", line 181, in __new__
    return abc.ABCMeta.__new__(mcs, name, bases, dikt)
  File "/usr/lib/python3.4/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
ValueError: 'new_authzr_uri' in __slots__ conflicts with class variable
```

**Comment by bmw** [comment]
Unfortunately I still see custom installed packages in that traceback:
```
File "/usr/local/lib/python3.4/dist-packages/acme/jose/json_util.py", line 181, in __new__
```

**Comment by sunitknandi** [comment]
@bmw Thanks for pointing that out. Its working now. :)
