### ISSUE TITLE
main_test.py spits out tons of junk

### ISSUE THREAD

**Issue by ohemorange** [certbot/certbot#5570]
This, over and over:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 154, in shouldRollover
    self.stream = self._open()
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] No such file or directory: '/tmp/tmpPLCIf1/logs/letsencrypt.log'
Logged from file util.py, line 147
```

We should probably fix that.

**Comment by elyscape** [comment]
I'm seeing this as well. The weird thing is that it doesn't appear to be happening all the time. For example, the build log for the Fedora 27 package for certbot 0.21.1 [is 20MB, most of which is this error][0.21.1]. The same is true of the build log for certbot 0.22.2, [which clocks in at 23MB][0.22.2]. Meanwhile, the build log for certbot 0.22.0 [is a paltry 214KB][0.22.0], despite [not appearing to have any differences][diff] that would contribute to this.

[0.21.1]: https://kojipkgs.fedoraproject.org/packages/certbot/0.21.1/1.fc27/data/logs/noarch/build.log
[0.22.0]: https://kojipkgs.fedoraproject.org/packages/certbot/0.22.0/1.fc27/data/logs/noarch/build.log
[0.22.2]: https://kojipkgs.fedoraproject.org/packages/certbot/0.22.2/1.fc27/data/logs/noarch/build.log
[diff]: https://github.com/certbot/certbot/compare/v0.22.0...v0.22.2
