### ISSUE TITLE
--manual / dns update does not work (standalone is no longer supported)

### ISSUE THREAD

**Issue by Ttech** [certbot/certbot#5571]
## My operating system is (include version):
Arch Linux 4.14.14 x86_64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pacman -S certbot certbot-dns-rfc2136

## I ran this command and it produced this output:

certbot certonly --manual --preferred-challenges=dns --manual-auth-hook "/opt/toolkit/bin/certbot-dns-updater.sh pre" --manual-cleanup-hook "/opt/toolkit/bin/certbot-dns-updater.sh post" -d broken.tools
(script to update is here https://github.com/Ttech/letsencrypt-simple-dns-updater)

## Certbot's behavior differed from what I expected because:
I get an error about selecting preferred challenge even though it is selected.

The standalone specific supported challenges flag is deprecated. Please use the --preferred challenges flag instead.

Following the guide on hooks https://community.letsencrypt.org/t/article-certbot-auto-with-dns-based-renewal/52695/5 

## Here is a Certbot log showing the issue (if available):
$certbot certonly --manual --preferred-challenges=dns --manual-auth-hook "/opt/toolkit/bin/certbot-dns-updater.sh pre" --manual-cleanup-hook "/opt/toolkit/bin/certbot-dns-updater.sh post" -d broken.tools;cat /var/log/letsencrypt/letsencrypt.log
The standalone specific supported challenges flag is deprecated. Please use the --preferred-challenges flag instead.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Could not choose appropriate plugin: Too many flags setting configurators/installers/authenticators 'standalone' -> 'manual'
Too many flags setting configurators/installers/authenticators 'standalone' -> 'manual'
2018-02-14 04:48:39,940:DEBUG:certbot.main:certbot version: 0.21.1
2018-02-14 04:48:39,941:DEBUG:certbot.main:Arguments: ['--manual', '--preferred-challenges=dns', '--manual-auth-hook', '/opt/toolkit/bin/certbot-dns-updater.sh pre', '--manual-cleanup-hook', '/opt/toolkit/bin/certbot-dns-updater.sh post', '-d', 'broken.tools']
2018-02-14 04:48:39,942:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-nsone,PluginEntryPoint#dns-rfc2136,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-02-14 04:48:39,950:WARNING:certbot.plugins.standalone:The standalone specific supported challenges flag is deprecated. Please use the --preferred-challenges flag instead.
2018-02-14 04:48:39,959:DEBUG:certbot.log:Root logging level set at 20
2018-02-14 04:48:39,960:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-02-14 04:48:39,960:INFO:certbot.main:Could not choose appropriate plugin: Too many flags setting configurators/installers/authenticators 'standalone' -> 'manual'
2018-02-14 04:48:39,961:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.21.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1240, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1099, in certonly
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/usr/lib/python3.6/site-packages/certbot/plugins/selection.py", line 161, in choose_configurator_plugins
    req_auth, req_inst = cli_plugin_requests(config)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/selection.py", line 245, in cli_plugin_requests
    req_auth = set_configurator(req_auth, "manual")
  File "/usr/lib/python3.6/site-packages/certbot/plugins/selection.py", line 219, in set_configurator
    raise errors.PluginSelectionError(msg.format(repr(previously), repr(now)))
certbot.errors.PluginSelectionError: Too many flags setting configurators/installers/authenticators 'standalone' -> 'manual'

**Comment by bmw** [comment]
Do you have a configuration file in `/etc/letsencrypt/cli.ini` or `${XDG_CONFIG_HOME:-~/.config}/letsencrypt/cli.ini` specifying standalone and standalone supported challenges?

**Comment by schoen** [comment]
Hi, if you're still getting this error, please reopen this issue and provide the information that @bmw requested! Thanks.
