### ISSUE TITLE
ImportError: cannot import name jose

### ISSUE THREAD

**Issue by daramousk** [certbot/certbot#5599]
## My operating system is (include version):
#1 SMP Debian 4.9.65-3+deb9u2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS Package Manager

## I ran this command and it produced this output:
certbot --version, certbot revoke

## Certbot's behavior differed from what I expected because:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
  File "/home/george/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_ent
ry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/george/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_en
try_point
    return ep.load()
  File "/home/george/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/home/george/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 13, in <module>
    from acme import jose
ImportError: cannot import name jose

**Comment by sydneyli** [comment]
In your traceback, it looks like Python packages from `~/.local/lib` are being used. If you clean those up, does that fix the issue?

**Comment by daramousk** [comment]
@sydneyli Indeed, that was the issue, thanks for the quick response.

**Comment by Laurent001** [comment]
Hello

I am a newbie and I have the exact same pb.
How do you clean those?

Thx

**Comment by sydneyli** [comment]
Hi @Laurent001 ! Packages in `~/.local` were probably installed using `pip`, so I would try `pip uninstall <package_name>` (not as root-- so without sudo) for the packages that appear in your traceback as being run from `~/.local`.

**Comment by Laurent001** [comment]
Thx.
I will try something similar because I have not install pip but have the same error message.

**Comment by sydneyli** [comment]
@Laurent001  Can you share with us your traceback?

**Comment by Laurent001** [comment]
I will but I did nothing yet (holidays...)

**Comment by Tomvtzand** [comment]
Hey guys,

I've got the same issue.. 

Trackback
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 11, in <module>
    load_entry_point('certbot==0.17.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 9, in <module>
    from acme import jose
ImportError: cannot import name jose

Anybody know what to do?

Thanks,

Tom

**Comment by bam-tbf** [comment]
I am having the same issue, but there are no local libs in my case. I was getting this error, then even did a fresh certbot-auto install and am still getting the error on a Centos 7 machine. Here is the log:

`2018-05-18 13:46:26,269:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.23.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1240, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python2.7/site-packages/certbot/plugins/disco.py", line 200, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python2.7/site-packages/certbot/plugins/disco.py", line 46, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/certbot_external_auth/plugin.py", line 27, in <module>
    from acme.jose import b64
ImportError: No module named jose
2018-05-18 13:46:26,269:ERROR:certbot.log:An unexpected error occurred:`

**Comment by EmixMaxime** [comment]
Hi,

Same problem as @bam-tbf has on a debian9 machine.

```shell
maxime@mxteaches:~$ certbot renew --cert-name domain1.com --dry-run
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.19.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 11, in <module>
    from acme import jose
ImportError: cannot import name jose

```

**Comment by vmedek** [comment]
I have the same problem like  @EmixMaxime and @bam-tbf 
Debian 9 as well

Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.17.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 9, in <module>
    from acme import jose
ImportError: cannot import name jose

**Comment by Georgi-Todorov** [comment]
@vmedek Your proposed solution solved the issue on my Debian 9

> on Debian9 solved by installing from backports :
apt-get install certbot python3-certbot python3-acme python3-cryptography python3-josepy python3-setuptools -f -t stretch-backports

**Comment by benbyford** [comment]
i managed to fix this by updating mailinabox then restarting

**Comment by Laurent001** [comment]
I have managed this issue with:

1. - apt-get update
2. - apt-get upgrade
3. - add in sources.list the stretch-backports:
deb http://ftp.debian.org/debian stretch-backports main
4. - apt -t stretch-backports install python-certbot-nginx python-acme certbot

**Comment by superlab-io** [comment]
> I have managed this issue with:
> 
> 1. apt-get update
> 2. apt-get upgrade
> 3. add in sources.list the stretch-backports:
>    deb http://ftp.debian.org/debian stretch-backports main
> 4. apt -t stretch-backports install python-certbot-nginx python-acme certbot
>    It exists for apache. Replace "-nginx" by "-apache"
> 
> and I follow [this tuto](https://certbot.eff.org/lets-encrypt/debianstretch-nginx.html) for debian 9 because certbot needs to use the command line:
> 
> 1. certbot --authenticator webroot --installer nginx

It worked for me thank you!
