### ISSUE TITLE
Gettting ValueError on all certbot commands after update

### ISSUE THREAD

**Issue by sundeeprana** [certbot/certbot#5653]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version): 

Ubuntu 14.04.5 LTS

## I installed Certbot with (certbot-auto, OS package manager, pip, etc): 

apt-get package manager, following instructions on https://certbot.eff.org/#ubuntutrusty-nginx

## I ran this command and it produced this output:  

certbot renew --no-self-upgrade --post-hook="service nginx reload"

Output:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.21.1', 'console_scripts', 'certbot')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)

▽
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 17, in <module>
    from certbot import account
  File "/usr/lib/python3/dist-packages/certbot/account.py", line 122, in <module>
    class RegistrationResourceWithNewAuthzrURI(messages.RegistrationResource):

▽
  File "/usr/local/lib/python3.4/dist-packages/acme/jose/json_util.py", line 181, in __new__
    return abc.ABCMeta.__new__(mcs, name, bases, dikt)
  File "/usr/lib/python3.4/abc.py", line 133, in __new__
    cls = super().__new__(mcls, name, bases, namespace)
ValueError: 'new_authzr_uri' in __slots__ conflicts with class variable

## Certbot's behavior differed from what I expected because: 

Certbot is not working anymore at all. Any call to certbot is producing the error above. I recently upgraded my server by running:

apt-get update
apt-get upgrade
apt-get dist-upgrade
shutdown -r now

Following these upgrades, certbot is not longer running.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

No logs are created since it seems to error out before being able to create a log.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem; # managed by Certbot

**Comment by sundeeprana** [comment]
Found fix for issue. Related to previous locally compiled version of Python that was being referenced to. This may have been originally compiled for the old certbot-auto that was used before I upgraded to the new PPA install version.
