### ISSUE TITLE
virtualenv: No module named cryptography.hazmat.bindings.openssl.binding

### ISSUE THREAD

**Issue by shakaran** [certbot/certbot#5703]
Probably related to missing support for cryptography.hazmat in Amazon Linux which has origin in this issue https://github.com/certbot/certbot/issues/4065

The venv with certbot-auto doesn't have the library and even when it tries to update from 0.21 to 0.22 it fails

## My operating system is (include version):

```
# cat /etc/issue.net 
Amazon Linux AMI release 2017.09

```
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

With certbot-auto

## I ran this command and it produced this output:

```
./certbot-auto renew --dry-run --debug --no-bootstrap
Upgrading certbot-auto 0.21.1 to 0.22.0...
Replacing certbot-auto...
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt: 
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 10, in <module>
    import josepy as jose
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/__init__.py", line 41, in <module>
    from josepy.interfaces import JSONDeSerializable
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/interfaces.py", line 8, in <module>
    from josepy import errors, util
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/util.py", line 4, in <module>
    import OpenSSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
ImportError: No module named cryptography.hazmat.bindings.openssl.binding
```

## Certbot's behavior differed from what I expected because:

Cannot renew my certificate

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2018-03-07 11:43:07,356:INFO:certbot.auth_handler:Cleaning up challenges
2018-03-07 11:43:07,356:DEBUG:certbot.plugins.webroot:Removing /opt/tomcat/webapps/.well-known/acme-challenge/2btW9t_boSC9ahH8YX83rQpMQ87hpJAWjMk-v-tyA1g
2018-03-07 11:43:07,356:DEBUG:certbot.plugins.webroot:All challenges cleaned up, removing /opt/tomcat/webapps/.well-known/acme-challenge
2018-03-07 11:43:07,357:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 1240, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 1120, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 113, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/renewal.py", line 297, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/client.py", line 318, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/auth_handler.py", line 81, in get_authorizations
    self._respond(resp, best_effort)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/auth_handler.py", line 138, in _respond
    self._poll_challenges(chall_update, best_effort)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/auth_handler.py", line 202, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
FailedChallenges: Failed authorization procedure.
```

**Comment by ricotijsen** [comment]
Same here! Tried:
- Removed /opt/eff/* and reinstalled
- Reinstalled libffi-devel and openssl-devl

**Comment by shakaran** [comment]
I see the issue https://github.com/certbot/certbot/issues/1680 previously reported, in concrete [this comment](https://github.com/certbot/certbot/issues/1680#issuecomment-358726360
)

I could avoid this error removing previous cerbot generated files and installing via pip, that is:

```
rm -rf /opt/eff.org/*
pip install -U certbot

```
That's installs 0.22 version to me with the right dependencies generated and I could execute the command.

I will keep this issue open for the dev, so they could solve the problem for Amazon Linux instaling from the certbot-auto binary

Probably google bring a lot people here, since stackoverflock is filled with the same issues for other people

**Comment by dtatwood** [comment]
FYI found this solution for my issue on Amazon Linux. Needed to add the softlink as suggested: https://community.letsencrypt.org/t/renew-error-no-module-named-cryptography-hazmat-bindings-openssl-binding/52395/8

**Comment by xinxilas** [comment]
Hello friend

When i try to execute
 pip install -U certbot

I receive this error:
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
The folder you are executing pip from can no longer be found.
```

Can you help me?

Also, im trying the antoher workaround without success
https://community.letsencrypt.org/t/amazon-linux-importerror-no-module-named-cryptography-hazmat-bindings-openssl-binding/60299

Because i dont know which exactly folders i need to link
Any help please?

**Comment by jeffgreenca** [comment]
So, as others have pointed out, `cryptography` was installed here:
```
$ find /opt/eff.org/certbot/venv/ -name cryptography
./lib64/python2.7/dist-packages/cryptography
$
```

But that path is not in the virtualenv python's default search directories:
```
$ source /opt/eff.org/certbot/venv/bin/activate
(venv) $ python -c 'import sys; import pprint; pprint.pprint(sorted(sys.path))'
['',
 '/opt/eff.org/certbot/venv/lib/python2.7',
 '/opt/eff.org/certbot/venv/lib/python2.7/dist-packages',
 '/opt/eff.org/certbot/venv/lib/python2.7/site-packages',
 '/opt/eff.org/certbot/venv/lib64/python2.7',
 '/opt/eff.org/certbot/venv/lib64/python2.7/lib-dynload',
 '/opt/eff.org/certbot/venv/lib64/python2.7/site-packages',
 '/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages',
 '/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages',
 '/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages',
 '/opt/eff.org/certbot/venv/local/lib64/python2.7/site-packages',
 '/usr/lib/python2.7',
 '/usr/lib64/python2.7']
(venv) $
```

So, as a workaround, symlinking `/opt/eff.org/certbot/venv/lib64/site-packages` to `dist-packages` fixed it:
```
$ pwd
/opt/eff.org/certbot/venv/lib64/python2.7
$ ls -lh | grep dist-packages
drwxr-xr-x 9 root root 4.0K May  1 15:00 dist-packages
lrwxrwxrwx 1 root root   13 May  1 15:04 site-packages -> dist-packages
$
```

Worked on `Linux 4.9.76-3.78.amzn1.x86_64 #1 SMP Fri Jan 12 19:51:35 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`.

**Comment by sydneyli** [comment]
Closing in favor of tracking support & recommended installation paths at #6505 for Amazon Linux and #6506 for Amazon Linux 2.
