### ISSUE TITLE
Created an SSL vhost at /etc/httpd/conf/vhosts/www-root/<myhost>-le-ssl.conf Unable to save files: /etc/httpd/conf/vhosts/www-root. Attempted Save Notes: Created ssl vhost at /etc/httpd/conf/vhosts/www-root/<myhost>-le-ssl.conf  Error saving files, check logs for more info.

### ISSUE THREAD

**Issue by nibytes** [certbot/certbot#5705]
## My operating system is (include version):
CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yum install

## I ran this command and it produced this output:
certbot --apache -d domain -d www.domain

## Certbot's behavior differed from what I expected because:
 - Unable to install the certificate

## Here is a Certbot log showing the issue (if available):
Unable to save files: /etc/httpd/conf/vhosts/www-root. Attempted Save Notes: Created ssl vhost at /
tc/httpd/conf/vhosts/www-root/!domain!-le-ssl.conf
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2018-03-11 19:39:41,820:DEBUG:certbot.main:certbot version: 0.21.1
2018-03-11 19:39:41,820:DEBUG:certbot.main:Arguments: ['--apache', '-d', 'officeoffice2018.com', '-d', 'www.officeoffice2018.com']
2018-03-11 19:39:41,820:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-03-11 19:39:41,845:DEBUG:certbot.log:Root logging level set at 20
2018-03-11 19:39:41,845:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-03-11 19:39:41,846:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2018-03-11 19:39:41,956:DEBUG:certbot_apache.configurator:Apache version is 2.4.6
2018-03-11 19:39:42,386:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT
Initialized: <certbot_apache.override_centos.CentOSConfigurator object at 0x1c0d410>
Prep: True
2018-03-11 19:39:42,386:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.override_centos.CentOSConfigurator object at 0x1c0d410> and installer <certbot_apache.override_centos.CentOSConfigurator object at 0x1c0d410>
2018-03-11 19:39:42,386:INFO:certbot.plugins.selection:Plugins selected: Authenticator apache, Installer apache
2018-03-11 19:39:42,416:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(status=u'valid', contact=(u'mailto:own@gmail.com',), agreement=u'https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf', key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x1171550>)>)), uri=u'https://acme-v01.api.letsencrypt.org/acme/reg/30959024', new_authzr_uri=u'https://acme-v01.api.letsencrypt.org/acme/new-authz', terms_of_service=u'https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'), d6fab96944acc5a7a53ca522d5c7e52a, Meta(creation_host=u'vps1065703.ukrdomen.com', creation_dt=datetime.datetime(2018, 3, 11, 19, 1, 9, tzinfo=<UTC>)))>
2018-03-11 19:39:42,422:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2018-03-11 19:39:42,427:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2018-03-11 19:39:42,978:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 562
2018-03-11 19:39:42,979:DEBUG:acme.client:Received response:
HTTP 200
content-length: 562
expires: Sun, 11 Mar 2018 19:33:35 GMT
strict-transport-security: max-age=604800
server: nginx
connection: keep-alive
pragma: no-cache
cache-control: max-age=0, no-cache, no-store
date: Sun, 11 Mar 2018 19:33:35 GMT
x-frame-options: DENY
content-type: application/json
replay-nonce: 2liFXpXP8Vc2Wh6gwKV6FJzIh6wCJhIfPnDH_LBX5ag

{
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
  },
  "nVGCFm2pcfs": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
2018-03-11 19:39:42,990:INFO:certbot.renewal:Cert not yet due for renewal
2018-03-11 19:39:44,748:INFO:certbot.main:Keeping the existing certificate
2018-03-11 19:39:44,749:DEBUG:certbot.reporter:Reporting to user: Congratulations! Your certificate and chain have been saved at:
/etc/letsencrypt/live/!domain!/fullchain.pem
Your key file has been saved at:
/etc/letsencrypt/live/!domain!/privkey.pem
Your cert will expire on 2018-06-09. To obtain a new or tweaked version of this certificate in the future, simply run certbot again with the "certonly" option. To non-interactively renew *all* of your certificates, run "certbot renew"
2018-03-11 19:39:44,764:INFO:certbot_apache.configurator:Created an SSL vhost at /etc/httpd/conf/vhosts/www-root/!domain!.com-le-ssl.conf
2018-03-11 19:39:44,764:ERROR:certbot_apache.augeas_configurator:Unable to save files: /etc/httpd/conf/vhosts/www-root. Attempted Save Notes: Created ssl vhost at /etc/httpd/conf/vhosts/www-root/!domain!.com-le-ssl.conf

2018-03-11 19:39:44,765:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 452, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 285, in deploy_cert
    vhost = self.choose_vhost(domain)
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 379, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 984, in make_vhost_ssl
    self.save()
  File "/usr/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 144, in save
    save_files = self.unsaved_files()
  File "/usr/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 112, in unsaved_files
    "Error saving files, check logs for more info.")
PluginError: Error saving files, check logs for more info.

2018-03-11 19:39:44,766:DEBUG:certbot.error_handler:Calling registered functions
2018-03-11 19:39:44,766:DEBUG:certbot.reporter:Reporting to user: Unable to install the certificate
2018-03-11 19:39:44,767:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.21.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1240, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1001, in run
    _install_cert(config, le_client, domains, new_lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 757, in _install_cert
    path_provider.cert_path, path_provider.chain_path, path_provider.fullchain_path)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 452, in deploy_certificate
    fullchain_path=fullchain_path)
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 285, in deploy_cert
    vhost = self.choose_vhost(domain)
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 379, in choose_vhost
    vhost = self.make_vhost_ssl(vhost)
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 984, in make_vhost_ssl
    self.save()
  File "/usr/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 144, in save
    save_files = self.unsaved_files()
  File "/usr/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 112, in unsaved_files
    "Error saving files, check logs for more info.")
PluginError: Error saving files, check logs for more info.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
<VirtualHost !ip!:80>
	ServerName !domain!
	ServerAlias www.!domain!
	DocumentRoot /var/www/www-root/data/www/!domain!
	ServerAdmin webmaster@!domain!
	DirectoryIndex index.php index.html
	AddDefaultCharset off
	SuexecUserGroup www-root www-root
	CustomLog /var/www/httpd-logs/!domain!.access.log combined
	ErrorLog /var/www/httpd-logs/!domain!.error.log
	<FilesMatch "\.ph(p[3-5]?|tml)$">
		SetHandler application/x-httpd-php
	</FilesMatch>
	<FilesMatch "\.phps$">
		SetHandler application/x-httpd-php-source
	</FilesMatch>
	<IfModule php5_module>
		php_admin_value sendmail_path "/usr/sbin/sendmail -t -i -f webmaster@<domain>.com"
		php_admin_value upload_tmp_dir "/var/www/www-root/data/mod-tmp"
		php_admin_value session.save_path "/var/www/www-root/data/mod-tmp"
		php_admin_value open_basedir "/var/www/www-root/data:."
	</IfModule>
	<IfModule php7_module>
		php_admin_value sendmail_path "/usr/sbin/sendmail -t -i -f webmaster@<domain>.com"
		php_admin_value upload_tmp_dir "/var/www/www-root/data/mod-tmp"
		php_admin_value session.save_path "/var/www/www-root/data/mod-tmp"
		php_admin_value open_basedir "/var/www/www-root/data:."
	</IfModule>
</VirtualHost>
<Directory /var/www/www-root/data/www/!domain!.com>
	Options +Includes -ExecCGI
	<IfModule php5_module>
		php_admin_flag engine on
	</IfModule>
	<IfModule php7_module>
		php_admin_flag engine on
	</IfModule>
</Directory>

**UPD:**
Someone can say it's bug or maybe  I do it something wrong?

**Comment by schoen** [comment]
@joohoi , have you seen something like this recently?

**Comment by joohoi** [comment]
I haven't seen this around recently, no.

> Someone can say it's bug or maybe I do it something wrong?

Doesn't look like you're doing anything wrong here.

This error is reported by Augeas, a configuration management library Certbot uses, and we unfortunately don't have any more visibility to the underlying reason behind the write error than what can be seen in the log.

Few things I'd like you to check to make sure that the environment is correct:
 - Make sure that Certbot has privileges to write to `/etc/httpd/conf/vhosts/www-root/` directory.
 - There's disk space available.

**Comment by nibytes** [comment]
I also thought about it, but the user has the right to do anything with this directory, and the space on the disks is almost empty

**Comment by schoen** [comment]
@joohoi , do you think it could be practical to run the client under `strace -f` with some kind of limiting `-e` expression? (I don't know if you can limit it beyond `-e open,write`.)

**Comment by joohoi** [comment]
> @joohoi , do you think it could be practical to run the client under strace -f with some kind of limiting -e expression? (I don't know if you can limit it beyond -e open,write.)

Yeah, it could be useful to strace the process with `-ff -e trace=open,stat,read,write` to find out if it's a file operation that errors out.

**Comment by sydneyli** [comment]
@nibytes -- are you still seeing this issue? If so, could you try running the debugging commands suggested above?

**Comment by nibytes** [comment]
> 
> 
> @nibytes -- are you still seeing this issue? If so, could you try running the debugging commands suggested above?

Two years it's a long time, I no longer have access to that vds. Sorry!
