### ISSUE TITLE
Cannot run certbot on Ubuntu 16.04: ImportError: No module named 'idna'

### ISSUE THREAD

**Issue by vaindil** [certbot/certbot#5720]
## My operating system is (include version):
Ubuntu 16.04.4

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
```
$ sudo add-apt-repository ppa:certbot/certbot
$ sudo apt-get update
$ sudo apt-get install certbot 
```

## I ran this command and it produced this output:
I ran `certbot` on its own (both with and without `sudo`), got this:
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.21.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 10, in <module>
    import josepy as jose
  File "/usr/lib/python3/dist-packages/josepy/__init__.py", line 41, in <module>
    from josepy.interfaces import JSONDeSerializable
  File "/usr/lib/python3/dist-packages/josepy/interfaces.py", line 8, in <module>
    from josepy import errors, util
  File "/usr/lib/python3/dist-packages/josepy/util.py", line 4, in <module>
    import OpenSSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 9, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 21, in <module>
    from cryptography.x509.general_name import GeneralName, IPAddress, OtherName
  File "/usr/lib/python3/dist-packages/cryptography/x509/general_name.py", line 11, in <module>
    import idna
ImportError: No module named 'idna'
```

## Certbot's behavior differed from what I expected because:
It didn't run.

## Here is a Certbot log showing the issue (if available):
Log is empty.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not relevant.

**Comment by mnordhoff** [comment]
If you run "`dpkg -l python3-idna`", what does it output? Is the package installed?

**Comment by vaindil** [comment]
I apologize, guess a bunch of my python3 packages were somehow corrupted. I had to `sudo apt install --reinstall python3-packagenamehere` a ton of things to get it to work again. My apologies!
