### ISSUE TITLE
"The error was: NoInstallationError()" issue on Nginx/CentOS7 with --nginx

### ISSUE THREAD

**Issue by lguariento** [certbot/certbot#5736]
## My operating system is (include version):

CentOS7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

sudo yum install epel-release
sudo yum install certbot-nginx

## I ran

`sudo certbot --nginx`

and it produced this:

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The nginx plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError()
```

## Here is a Certbot log showing the issue (if available):

```
2018-03-15 18:22:14,627:DEBUG:certbot.main:certbot version: 0.22.0
2018-03-15 18:22:14,627:DEBUG:certbot.main:Arguments: ['--nginx']
2018-03-15 18:22:14,627:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-03-15 18:22:14,645:DEBUG:certbot.log:Root logging level set at 20
2018-03-15 18:22:14,645:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-03-15 18:22:14,646:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2018-03-15 18:22:14,647:DEBUG:certbot.plugins.disco:No installation (PluginEntryPoint#nginx):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/plugins/disco.py", line 126, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 131, in prepare
    raise errors.NoInstallationError
NoInstallationError
2018-03-15 18:22:14,647:DEBUG:certbot.plugins.selection:No candidate plugin
2018-03-15 18:22:14,647:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

I added 

```
    location "/.well-known/acme-challenge/" {
        default_type "text/plain";
        root /var/www/certbot;
    }
```

to the nginx virtual host configuration file. `var/www/certbot` exists and has 755 permissions. What am I doing wrong? Nginx is serving my website correctly (I have a jetty in reverse-proxing) and I can't understand why the certbot nginx plugin is not working.

**Comment by bmw** [comment]
Sorry you're having trouble, but as stated in our issue template that you filled out, if you're having trouble using Certbot, please first try asking for help at https://community.letsencrypt.org/. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.

**Comment by ScoreUnder** [comment]
Came here from google.

Some of the threads:
* https://community.letsencrypt.org/t/the-error-was-noinstallationerror-issue-on-nginx-centos7-with-nginx/56503/11
* https://community.letsencrypt.org/t/certbot-cron-job-nginx-plugin-noinstallationerror/67572/3

It's on "discourse", bane of NoScript users everywhere, so I'll summarise. The the long and short of it is that it can't find nginx on the PATH, so I recommend checking that. (`sudo` or `crontab` may use different values for PATH, so check within these utilities too)

I am using CentOS 7, and I just needed to put `PATH=/usr/bin:/usr/sbin:/bin:/sbin` at the top of my crontab to solve the cron-facing variant of this issue.
