### ISSUE TITLE
Certbot-auto not generating certificates for nginx.

### ISSUE THREAD

**Issue by sflang1** [certbot/certbot#5780]
Hello!

I'm trying to register a new SSL certificate in a VPS that has already multiple SSL certificates obtained with LetsEncrypt. I perform the command 
`sudo ./certbot-auto --nginx -d <domain name>-d <www.domain name>`
But it fails with the following log:
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for womamusic.com
http-01 challenge for www.womamusic.com
nginx: [emerg] a duplicate default server for 0.0.0.0:443 in /etc/nginx/sites-enabled/wikss.com:82
Cleaning up challenges
nginx restart failed:

I've double checked but there is no double default_server in the specified file. Even, this file doesn't have 82 lines:
```
# Virtual Host configuration for wikss.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.

server {
       listen 80 default_server;
       listen [::]:80;

       server_name wikss.com www.wikss.com;

       root /var/www/wikss.com/public;
       index index.php index.html;

       location ~ \.php$ {
               include snippets/fastcgi-php.conf;
               fastcgi_pass unix:/run/php/php7.0-fpm.sock;
       }

       location ~ /\.ht {
               deny all;
       }

       location ~ /.well-known {
               allow all;
       }

       location / {
               try_files $uri $uri/ /index.php?$query_string;
       }


    listen 443 default ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/wikss.com/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/wikss.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot

ssl_dhparam /etc/ssl/certs/dhparam.pem;

    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    # Redirect non-https traffic to https
    # if ($scheme != "https") {
    #     return 301 https://$host$request_uri;
    # } # managed by Certbot

}
```

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2018-03-22 01:35:27,302:DEBUG:certbot.reverter:Creating backup of /etc/nginx/nginx.conf
2018-03-22 01:35:27,304:DEBUG:certbot_nginx.parser:Writing nginx conf tree to /etc/nginx/sites-enabled/wikss.com:
# Virtual Host configuration for wikss.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.

server {
       listen 80 default_server;
       listen [::]:80;

       server_name wikss.com www.wikss.com;

       root /var/www/wikss.com/public;
       index index.php index.html;

       location ~ \.php$ {
               include snippets/fastcgi-php.conf;
               fastcgi_pass unix:/run/php/php7.0-fpm.sock;
       }

       location ~ /\.ht {
               deny all;
       }

       location ~ /.well-known {
               allow all;
       }

       location / {
               try_files $uri $uri/ /index.php?$query_string;
       }


    listen 443 default ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/wikss.com/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/wikss.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot

ssl_dhparam /etc/ssl/certs/dhparam.pem;

    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    # Redirect non-https traffic to https
    # if ($scheme != "https") {
    #     return 301 https://$host$request_uri;
    # } # managed by Certbot

}


server {rewrite ^(/.well-known/acme-challenge/.*) $1 break; # managed by Certbot

rewrite ^(/.well-known/acme-challenge/.*) $1 break; # managed by Certbot


       listen 80 ;
       listen [::]:80;
    server_name womamusic.com www.womamusic.com; # managed by Certbot

       root /var/www/wikss.com/public;
       index index.php index.html;

       location ~ \.php$ {
               include snippets/fastcgi-php.conf;
               fastcgi_pass unix:/run/php/php7.0-fpm.sock;
       }

       location ~ /\.ht {
               deny all;
       }

       location ~ /.well-known {
               allow all;
       }

       location / {
               try_files $uri $uri/ /index.php?$query_string;
       }


    listen 443 default ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/wikss.com/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/wikss.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot

ssl_dhparam /etc/ssl/certs/dhparam.pem;

    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    # Redirect non-https traffic to https
    # if ($scheme != "https") {
    #     return 301 https://$host$request_uri;
    # } # managed by Certbot


location = /.well-known/acme-challenge/FT_G2ESPTOz4cd3VB4EifWNQqKVunbeeqKFMHaKyh4g{default_type text/plain;return 200 FT_G2ESPTOz4cd3VB4EifWNQqKVunbeeqKFMHaKyh4g.rmJDXd2FpMP8EetheTQkSgL5ipQMf1OqEFUTt4mzfcw;} # managed by Certbot


location = /.well-known/acme-challenge/eHQZYUwN5UjKIYGKBe2upjotrAdi-3FMqmALUICYsYI{default_type text/plain;return 200 eHQZYUwN5UjKIYGKBe2upjotrAdi-3FMqmALUICYsYI.rmJDXd2FpMP8EetheTQkSgL5ipQMf1OqEFUTt4mzfcw;} # managed by Certbot

}
2018-03-22 01:35:27,306:DEBUG:certbot_nginx.parser:Writing nginx conf tree to /etc/nginx/nginx.conf:
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 768;
	# multi_accept on;
}

http {
include /etc/letsencrypt/le_http_01_cert_challenge.conf;
server_names_hash_bucket_size 128;

	##
	# Basic Settings
	##
	client_max_body_size 6M;

	sendfile off;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	##
	# SSL Settings
	##

	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}


#mail {
#	# See sample authentication script at:
#	# http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
# 
#	# auth_http localhost/auth.php;
#	# pop3_capabilities "TOP" "USER";
#	# imap_capabilities "IMAP4rev1" "UIDPLUS";
# 
#	server {
#		listen     localhost:110;
#		protocol   pop3;
#		proxy      on;
#	}
# 
#	server {
#		listen     localhost:143;
#		protocol   imap;
#		proxy      on;
#	}
#}

2018-03-22 01:35:27,332:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 124, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 972, in perform
    self.restart()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 787, in restart
    nginx_restart(self.conf('ctl'), self.nginx_conf)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 1042, in nginx_restart
    "nginx restart failed:\n%s\n%s" % (out.read(), err.read()))
MisconfigurationError: nginx restart failed:



2018-03-22 01:35:27,332:DEBUG:certbot.error_handler:Calling registered functions
2018-03-22 01:35:27,332:INFO:certbot.auth_handler:Cleaning up challenges
2018-03-22 01:35:28,623:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 1266, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 1031, in run
    certname, lineage)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 118, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/client.py", line 350, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/client.py", line 294, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/client.py", line 330, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 72, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 124, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 972, in perform
    self.restart()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 787, in restart
    nginx_restart(self.conf('ctl'), self.nginx_conf)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_nginx/configurator.py", line 1042, in nginx_restart
    "nginx restart failed:\n%s\n%s" % (out.read(), err.read()))
MisconfigurationError: nginx restart failed:



```

**Comment by bmw** [comment]
@sflang1, thanks for the bug report and sorry for the trouble. You should be able to work around the problem by changing the line:
```
listen 443 default ssl; # managed by Certbot
```
to
```
listen 443 default_server ssl; # managed by Certbot
```
If that doesn't work, please let us know and provide the log of the new error.

@ohemorange, I was also able to reproduce this if the `listen` for port 443 included `ipv6only=on`. Perhaps when creating a new server block for the challenge, we should do what we do when creating a permanent redirect server block and remove most other directives.

Please let me know what you think and how we should prioritize this.

**Comment by ohemorange** [comment]
The original reported issue is covered in https://github.com/certbot/certbot/issues/5438.

As for the separate issue, we do that, but we copy the listens because we allow listening on other ports. The correct thing to do is not copy ipv6only when duplicating the block. I'll rename this issue to that, and prioritize it with the other small Nginx fixes in the pipeline.

**Comment by bmw** [comment]
> As for the separate issue, we do that, but we copy the listens because we allow listening on other ports.

You're saying we do remove most other directives? That's not what I saw during my testing or in the log above.

That was just a suggestion, but just wanted to make sure we're on the same page about our current behavior.

**Comment by sflang1** [comment]
Hi, bmw, and ohemorange. 

I changed the line you told me and I can certify it works!

Thanks a lot for your attention!
