### ISSUE TITLE
Unable to create cert

### ISSUE THREAD

**Issue by UjoJano** [certbot/certbot#5784]
Hello. I tried to create a certificate with a mail-in-a-box script and with certboot. But it does not work to create certificates and I have invalid cert on the server. Can you help me with this?

Server: Ubuntu 14.04, Nginx

Mailinabox error:
https://github.com/mail-in-a-box/mailinabox/issues/1368

Certbot error (after run on other server for test):
2018-03-23 13:14:20,261:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2018-03-23 13:14:20,261:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f0e2550df60>
Prep: True
2018-03-23 13:14:20,262:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7f0e2550df60> and installer None
2018-03-23 13:14:20,262:INFO:certbot.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2018-03-23 13:14:34,429:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.22.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1266, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1141, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 635, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 514, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 164, in register
    acme = acme_from_config_key(config, key)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 45, in acme_from_config_key
    user_agent=determine_user_agent(config))
TypeError: __init__() got an unexpected keyword argument 'account'
2018-03-23 13:14:34,430:ERROR:certbot.log:An unexpected error occurred:

**Comment by sydneyli** [comment]
Can you tell us what command you ran, and how you installed certbot? MiaB doesn't use certbot by default to acquire/manage certs: mail-in-a-box/mailinabox#1314

**Comment by UjoJano** [comment]
Certboot I tried to install from desperation, and also did not work.
Install from to official instructions:
$ sudo apt-get update
$ sudo apt-get install software-properties-common
$ sudo add-apt-repository ppa: certbot / certbot
$ sudo apt-get update
$ sudo apt-get install python-certbot-nginx

If I had some other message, nginx would be configured later.  Certbot ended immediately after sending the order. On Ubu 16.04 + Apache with certboot has never had a problem.

Command: Temp is only for test if created acme
certbot certonly --webroot -w /temp/ -d www.example.com -d example.com

**Comment by UjoJano** [comment]
It can be closed. Solved.
