### ISSUE TITLE
certbot-dns-rfc2136 produces NOTIMP but no connections performed

### ISSUE THREAD

**Issue by xm74** [certbot/certbot#5796]
I'm trying to use certbot 0.22.2 with certbot-dns-rfc2136 plugin using TSIG on FreeBSD 11. with NSD 4.1 DNS-server.
Here is configurations.

```
root@beta:~ # uname -v
FreeBSD 11.1-RELEASE-p8 #0: Tue Mar 13 17:07:05 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
root@beta:~ # pkg info | egrep "certbot|acme"
py27-acme-0.22.2,1             ACME protocol implementation in Python
py27-certbot-0.22.2,1          Let's Encrypt client
py27-certbot-dns-rfc2136-0.22.2 RFC 2136 DNS Authenticator plugin for Certbot
root@beta:~ # host `hostname`
beta.peek.ru has address 78.40.219.163
beta.peek.ru has IPv6 address 2001:470:28:26f::1
root@beta:~ # cat /usr/local/etc/nsd/nsd.conf
...
key:
        name: "lekey"
        algorithm: hmac-sha512
        secret: "ox+Koh0/bk55s4l3892F3LRjtBztl+Y+k+bf3VN53VW0nfbhR72hs6ZuX0UeuUOSQwQOzAd9c1nX6uVnSN4Lvg=="
...
zone:
        name: "peek.ru"
        zonefile: "%s/%s.zone"
        allow-notify: 78.40.219.163 lekey
        request-xfr: 78.40.219.163 lekey
...
root@beta:~ # cat /usr/local/etc/letsencrypt/tsig.conf
dns_rfc2136_server = 78.40.219.163
dns_rfc2136_name = lekey
dns_rfc2136_secret = ox+Koh0/bk55s4l3892F3LRjtBztl+Y+k+bf3VN53VW0nfbhR72hs6ZuX0UeuUOSQwQOzAd9c1nX6uVnSN4Lvg==
dns_rfc2136_algorithm = HMAC-SHA512
root@beta:~ # sockstat -46 | grep :53
nsd      nsd        57787 4  udp4   78.40.219.163:53      *:*
nsd      nsd        57787 5  udp6   2001:470:28:26f::1:53 *:*
...
```

I trying to get wildcard ceritificate with DNS01 method but got this error.

```
root@beta:~ # certbot certonly --dns-rfc2136 --dns-rfc2136-credentials /usr/local/etc/letsencrypt/tsig.conf --agree-tos --email abuse@peek.ru --cert-name peek.ru -d "*.peek.ru" -d peek.ru --server https://acme-v02.api.letsencrypt.org/directory
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-rfc2136, Installer None

-------------------------------------------------------------------------------
You are updating certificate peek.ru to include new domain(s):
+ *.peek.ru

You are also removing previously included domain(s):
- beta.peek.ru
- list.peek.ru
- mail.peek.ru
- www.peek.ru

Did you intend to make this change?
-------------------------------------------------------------------------------
(U)pdate cert/(C)ancel: U
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for peek.ru
dns-01 challenge for peek.ru
Cleaning up challenges
Encountered exception during recovery
Received response from server: NOTIMP
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/certbot/error_handler.py", line 100, in _call_registered
    self.funcs[-1]()
  File "/usr/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 303, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/local/lib/python2.7/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 77, in _cleanup
    self._get_rfc2136_client().del_txt_record(domain, validation_name, validation)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 168, in del_txt_record
    .format(dns.rcode.to_text(rcode)))
PluginError: Received response from server: NOTIMP
Received response from server: NOTIMP
```

TCPdump show no connections to DNS server from binded IP. NSD log is empty too.

```
root@beta:~ # tcpdump -i bge0 -n -nn -ttt 'port 53'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on tun0, link-type NULL (BSD loopback), capture size 262144 bytes
^C
0 packets captured
4 packets received by filter
0 packets dropped by kernel
root@beta:~ # tail /usr/local/etc/nsd/var/log/nsd.log
[2018-03-27 18:00:25.906] nsd[52705]: warning: signal received, shutting down...
[2018-03-27 18:00:25.921] nsd[72952]: notice: nsd starting (NSD 4.1.17)
[2018-03-27 18:00:25.924] nsd[72952]: info: setup SSL certificates
[2018-03-27 18:00:25.968] nsd[75673]: info: zonefile peek.ru/peek.ru.zone is not modified
```

**Comment by ohemorange** [comment]
Hey @zjs! Any idea what might be going on here?

**Comment by bmw** [comment]
@joohoi said he'd also take a look at this.

**Comment by xm74** [comment]
@zjs @ohemorange @joohoi Tell me if any assistance from my side will required.

**Comment by joohoi** [comment]
This feels rather strange, as `NOTIMP`, RCODE 4 - an actual DNS server response code defined in RFC 1035 seems to be logged on the Certbot end. The error also seems to happen within the cleanup routine.

Could you double check the tcpdump interface, as you seem to be running Certbot on the same host as the DNS server that the traffic actually goes through that interface. And if possible, run Certbot with `--debug-challenges` paremeter, which will pause Certbot before asking Let's Encrypt to verify the challenges. This gives you an window to confirm that no TXT records actually get written. You should be able to verify this by querying TXT records for `_acme-challenge.peek.ru` based on your command line.

**Comment by xm74** [comment]
I tried to do same from other server (because I thought that this might be some kind loopback interface issue) and got exactly the same with `--debug-challenges` option.
New test host

```
root@mx:~ # host `hostname`
mx.topreader.org has address 167.99.61.179
mx.topreader.org has IPv6 address 2604:a880:800:a1::1619:6001
```

Same DNS server host

```
root@beta:~ # uname -v
FreeBSD 11.1-RELEASE-p8 #0: Tue Mar 13 17:07:05 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC
root@beta:~ # pkg info | egrep "certbot|acme"
py27-acme-0.22.2,1             ACME protocol implementation in Python
py27-certbot-0.22.2,1          Let's Encrypt client
py27-certbot-dns-rfc2136-0.22.2 RFC 2136 DNS Authenticator plugin for Certbot
root@beta:~ # host `hostname`
beta.peek.ru has address 78.40.219.163
beta.peek.ru has IPv6 address 2001:470:28:26f::1
root@beta:~ # cat /usr/local/etc/nsd/nsd.conf
...
key:
        name: "lekey"
        algorithm: hmac-sha512
        secret: "ox+Koh0/bk55s4l3892F3LRjtBztl+Y+k+bf3VN53VW0nfbhR72hs6ZuX0UeuUOSQwQOzAd9c1nX6uVnSN4Lvg=="
...
zone:
        name: "peek.ru"
        zonefile: "%s/%s.zone"
        allow-notify: 167.99.61.179 lekey
        request-xfr: 167.99.61.179 lekey
...
```

Performing test that DNS works.

```
root@mx:~ # host -t a peek.ru 78.40.219.163
Using domain server:
Name: 78.40.219.163
Address: 78.40.219.163#53
Aliases:

peek.ru has address 78.40.219.163
```

and see that packets reached DNS

```
root@beta:/home/xm # tcpdump -i bge0 -n 'port 53'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on tun0, link-type NULL (BSD loopback), capture size 262144 bytes
...
17:50:05.665869 IP 167.99.61.179.19043 > 78.40.219.163.53: 32208+ A? peek.ru. (25)
17:50:05.665940 IP 78.40.219.163.53 > 167.99.61.179.19043: 32208*- 1/2/2 A 78.40.219.163 (132)
```

Trying to obtain certificate from external host.

```
root@mx:~ # pkg info | egrep "certbot|acme"
py27-acme-0.22.2,1             ACME protocol implementation in Python
py27-certbot-0.22.2,1          Let's Encrypt client
py27-certbot-dns-rfc2136-0.22.2 RFC 2136 DNS Authenticator plugin for Certbot
root@mx:~ # cat tsig.conf
dns_rfc2136_server = 78.40.219.163
dns_rfc2136_name = lekey
dns_rfc2136_secret = ox+Koh0/bk55s4l3892F3LRjtBztl+Y+k+bf3VN53VW0nfbhR72hs6ZuX0UeuUOSQwQOzAd9c1nX6uVnSN4Lvg==
dns_rfc2136_algorithm = HMAC-SHA512
root@mx:~ # certbot certonly --dns-rfc2136 --dns-rfc2136-credentials tsig.conf --debug-challenges --agree-tos --email abuse@peek.ru -d "*.peek.ru" -d peek.ru --server https://acme-v02.api.letsencrypt.org/directory
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-rfc2136, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for peek.ru
dns-01 challenge for peek.ru
Unsafe permissions on credentials configuration file: tsig.conf
Cleaning up challenges
Encountered exception during recovery
Received response from server: NOTIMP
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/certbot/error_handler.py", line 100, in _call_registered
    self.funcs[-1]()
  File "/usr/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 303, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/local/lib/python2.7/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 77, in _cleanup
    self._get_rfc2136_client().del_txt_record(domain, validation_name, validation)
  File "/usr/local/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 168, in del_txt_record
    .format(dns.rcode.to_text(rcode)))
PluginError: Received response from server: NOTIMP
Received response from server: NOTIMP
```

Now packets seen (I added -X to see packets content). 

```
root@beta:/home/xm # tcpdump -i bge0 -n -X 'host 167.99.61.179 and port 53'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on bge0, link-type NULL (BSD loopback), capture size 262144 bytes
18:01:51.976900 IP 167.99.61.179.36990 > 78.40.219.163.53: 26087 SOA? peek.ru. (25)
        0x0000:  4500 0035 a189 0000 3611 d44c a763 3db3  E..5....6..L.c=.
        0x0010:  4e28 dba3 907e 0035 0021 abe0 65e7 0000  N(...~.5.!..e...
        0x0020:  0001 0000 0000 0000 0470 6565 6b02 7275  .........peek.ru
        0x0030:  0000 0600 01                             .....
18:01:51.976977 IP 78.40.219.163.53 > 167.99.61.179.36990: 26087*- 1/2/2 SOA (158)
        0x0000:  4500 00ba 2d5d 0000 4011 3df4 4e28 dba3  E...-]..@.=.N(..
        0x0010:  a763 3db3 0035 907e 00a6 8fd0 65e7 8400  .c=..5.~....e...
        0x0020:  0001 0001 0002 0002 0470 6565 6b02 7275  .........peek.ru
        0x0030:  0000 0600 01c0 0c00 0600 0100 0151 8000  .............Q..
        0x0040:  2304 6265 7461 c00c 0561 6275 7365 c00c  #.beta...abuse..
        0x0050:  7848 b980 0000 2a30 0000 0708 0009 3a80  xH....*0......:.
        0x0060:  0000 3840 c00c 0002 0001 0001 5180 0010  ..8@........Q...
        0x0070:  036e 7332 0661 6672 6169 6403 6f72 6700  .ns2.afraid.org.
        0x0080:  c00c 0002 0001 0001 5180 0002 c025 c025  ........Q....%.%
        0x0090:  0001 0001 0001 5180 0004 4e28 dba3 c025  ......Q...N(...%
        0x00a0:  001c 0001 0001 5180 0010 2001 0470 0028  ......Q......p.(
        0x00b0:  026f 0000 0000 0000 0001                 .o........
18:01:52.098773 IP 167.99.61.179.40428 > 78.40.219.163.53: Flags [S], seq 42377428, win 65535, options [mss 1408,nop,wscale 6,sackOK,TS val 80807408 ecr 0], length 0
        0x0000:  4500 003c 0000 4000 3606 35da a763 3db3  E..<..@.6.5..c=.
        0x0010:  4e28 dba3 9dec 0035 0286 a0d4 0000 0000  N(.....5........
        0x0020:  a002 ffff ed15 0000 0204 0580 0103 0306  ................
        0x0030:  0402 080a 04d1 05f0 0000 0000            ............
18:01:52.098788 IP 78.40.219.163.53 > 167.99.61.179.40428: Flags [S.], seq 2456597509, ack 42377429, win 65535, options [mss 1408,nop,wscale 6,sackOK,TS val 1878036726 ecr 80807408], length 0
        0x0000:  4500 003c 0000 4000 4006 2bda 4e28 dba3  E..<..@.@.+.N(..
        0x0010:  a763 3db3 0035 9dec 926c b405 0286 a0d5  .c=..5...l......
        0x0020:  a012 ffff a5ab 0000 0204 0580 0103 0306  ................
        0x0030:  0402 080a 6ff0 90f6 04d1 05f0            ....o.......
18:01:52.210565 IP 167.99.61.179.40428 > 78.40.219.163.53: Flags [.], ack 1, win 1034, options [nop,nop,TS val 80807520 ecr 1878036726], length 0
        0x0000:  4500 0034 0000 4000 3606 35e2 a763 3db3  E..4..@.6.5..c=.
        0x0010:  4e28 dba3 9dec 0035 0286 a0d5 926c b406  N(.....5.....l..
        0x0020:  8010 040a cfc8 0000 0101 080a 04d1 0660  ...............`
        0x0030:  6ff0 90f6                                o...
18:01:52.210614 IP 167.99.61.179.40428 > 78.40.219.163.53: Flags [P.], seq 1:210, ack 1, win 1034, options [nop,nop,TS val 80807521 ecr 1878036726], length 20924430 update [1n] [1au] SOA? peek.ru. (207)
        0x0000:  4500 0105 0000 4000 3606 3511 a763 3db3  E.....@.6.5..c=.
        0x0010:  4e28 dba3 9dec 0035 0286 a0d5 926c b406  N(.....5.....l..
        0x0020:  8018 040a ef51 0000 0101 080a 04d1 0661  .....Q.........a
        0x0030:  6ff0 90f6 00cf 5f6e 2800 0001 0000 0001  o....._n(.......
        0x0040:  0001 0470 6565 6b02 7275 0000 0600 010f  ...peek.ru......
        0x0050:  5f61 636d 652d 6368 616c 6c65 6e67 65c0  _acme-challenge.
        0x0060:  0c00 1000 0100 0000 7800 2c2b 3378 524d  ........x.,+3xRM
        0x0070:  3065 7854 474e 6554 426b 6976 3133 7849  0exTGNeTBkiv13xI
        0x0080:  4935 6144 6874 786b 694b 5971 6533 6a65  I5aDhtxkiKYqe3je
        0x0090:  6f43 3832 6172 6705 6c65 6b65 7900 00fa  oC82arg.lekey...
        0x00a0:  00ff 0000 0000 005d 0b68 6d61 632d 7368  .......].hmac-sh
        0x00b0:  6135 3132 0000 005a bd0d f001 2c00 40a1  a512...Z....,.@.
        0x00c0:  45de 1497 4944 7cf0 bcf2 cfba 940d 9a85  E...ID|.........
        0x00d0:  27a7 9688 03ed af9c 5528 c483 6a5b 3284  '.......U(..j[2.
        0x00e0:  65c4 f937 35a2 17c4 c480 25a2 d12c f2f0  e..75.....%..,..
        0x00f0:  f49d 298b dc82 b399 3f47 7415 ac90 325f  ..).....?Gt...2_
        0x0100:  6e00 0000 00                             n....
18:01:52.210697 IP 78.40.219.163.53 > 167.99.61.179.40428: Flags [P.], seq 1:15, ack 210, win 1034, options [nop,nop,TS val 1878036838 ecr 80807521], length 1424430 update NotImp- [0q] 0/0/0 (12)
        0x0000:  4500 0042 0000 4000 4006 2bd4 4e28 dba3  E..B..@.@.+.N(..
        0x0010:  a763 3db3 0035 9dec 926c b406 0286 a1a6  .c=..5...l......
        0x0020:  8018 040a c6f1 0000 0101 080a 6ff0 9166  ............o..f
        0x0030:  04d1 0661 000c 5f6e a804 0000 0000 0000  ...a.._n........
        0x0040:  0000                                     ..
18:01:52.321687 IP 167.99.61.179.40428 > 78.40.219.163.53: Flags [F.], seq 210, ack 15, win 1034, options [nop,nop,TS val 80807632 ecr 1878036838], length 0
        0x0000:  4500 0034 0000 4000 3606 35e2 a763 3db3  E..4..@.6.5..c=.
        0x0010:  4e28 dba3 9dec 0035 0286 a1a6 926c b414  N(.....5.....l..
        0x0020:  8011 040a ce08 0000 0101 080a 04d1 06d0  ................
        0x0030:  6ff0 9166                                o..f
18:01:52.321698 IP 78.40.219.163.53 > 167.99.61.179.40428: Flags [.], ack 211, win 1034, options [nop,nop,TS val 1878036949 ecr 80807632], length 0
        0x0000:  4500 0034 0000 4000 4006 2be2 4e28 dba3  E..4..@.@.+.N(..
        0x0010:  a763 3db3 0035 9dec 926c b414 0286 a1a7  .c=..5...l......
        0x0020:  8010 040a cd99 0000 0101 080a 6ff0 91d5  ............o...
        0x0030:  04d1 06d0                                ....
18:01:52.321766 IP 78.40.219.163.53 > 167.99.61.179.40428: Flags [F.], seq 15, ack 211, win 1034, options [nop,nop,TS val 1878036949 ecr 80807632], length 0
        0x0000:  4500 0034 0000 4000 4006 2be2 4e28 dba3  E..4..@.@.+.N(..
        0x0010:  a763 3db3 0035 9dec 926c b414 0286 a1a7  .c=..5...l......
        0x0020:  8011 040a cd98 0000 0101 080a 6ff0 91d5  ............o...
        0x0030:  04d1 06d0                                ....
18:01:52.327866 IP 167.99.61.179.42843 > 78.40.219.163.53: 28472 SOA? peek.ru. (25)
        0x0000:  4500 0035 a18a 0000 3611 d44b a763 3db3  E..5....6..K.c=.
        0x0010:  4e28 dba3 a75b 0035 0021 8bb2 6f38 0000  N(...[.5.!..o8..
        0x0020:  0001 0000 0000 0000 0470 6565 6b02 7275  .........peek.ru
        0x0030:  0000 0600 01                             .....
18:01:52.327908 IP 78.40.219.163.53 > 167.99.61.179.42843: 28472*- 1/2/2 SOA (158)
        0x0000:  4500 00ba 2d5e 0000 4011 3df3 4e28 dba3  E...-^..@.=.N(..
        0x0010:  a763 3db3 0035 a75b 00a6 6fa2 6f38 8400  .c=..5.[..o.o8..
        0x0020:  0001 0001 0002 0002 0470 6565 6b02 7275  .........peek.ru
        0x0030:  0000 0600 01c0 0c00 0600 0100 0151 8000  .............Q..
        0x0040:  2304 6265 7461 c00c 0561 6275 7365 c00c  #.beta...abuse..
        0x0050:  7848 b980 0000 2a30 0000 0708 0009 3a80  xH....*0......:.
        0x0060:  0000 3840 c00c 0002 0001 0001 5180 0010  ..8@........Q...
        0x0070:  036e 7332 0661 6672 6169 6403 6f72 6700  .ns2.afraid.org.
        0x0080:  c00c 0002 0001 0001 5180 0002 c025 c025  ........Q....%.%
        0x0090:  0001 0001 0001 5180 0004 4e28 dba3 c025  ......Q...N(...%
        0x00a0:  001c 0001 0001 5180 0010 2001 0470 0028  ......Q......p.(
        0x00b0:  026f 0000 0000 0000 0001                 .o........
18:01:52.432328 IP 167.99.61.179.40428 > 78.40.219.163.53: Flags [.], ack 16, win 1033, options [nop,nop,TS val 80807743 ecr 1878036949], length 0
        0x0000:  4500 0034 0000 4000 3606 35e2 a763 3db3  E..4..@.6.5..c=.
        0x0010:  4e28 dba3 9dec 0035 0286 a1a7 926c b415  N(.....5.....l..
        0x0020:  8010 0409 cd2a 0000 0101 080a 04d1 073f  .....*.........?
        0x0030:  6ff0 91d5                                o...
18:01:52.442782 IP 167.99.61.179.40429 > 78.40.219.163.53: Flags [S], seq 2136678362, win 65535, options [mss 1408,nop,wscale 6,sackOK,TS val 80807753 ecr 0], length 0
        0x0000:  4500 003c 0000 4000 3606 35da a763 3db3  E..<..@.6.5..c=.
        0x0010:  4e28 dba3 9ded 0035 7f5b 1fda 0000 0000  N(.....5.[......
        0x0020:  a002 ffff efe0 0000 0204 0580 0103 0306  ................
        0x0030:  0402 080a 04d1 0749 0000 0000            .......I....
18:01:52.442794 IP 78.40.219.163.53 > 167.99.61.179.40429: Flags [S.], seq 4146813792, ack 2136678363, win 65535, options [mss 1408,nop,wscale 6,sackOK,TS val 3275990647 ecr 80807753], length 0
        0x0000:  4500 003c 0000 4000 4006 2bda 4e28 dba3  E..<..@.@.+.N(..
        0x0010:  a763 3db3 0035 9ded f72b 5b60 7f5b 1fdb  .c=..5...+[`.[..
        0x0020:  a012 ffff 3388 0000 0204 0580 0103 0306  ....3...........
        0x0030:  0402 080a c343 a677 04d1 0749            .....C.w...I
18:01:52.554861 IP 167.99.61.179.40429 > 78.40.219.163.53: Flags [.], ack 1, win 1034, options [nop,nop,TS val 80807865 ecr 3275990647], length 0
        0x0000:  4500 0034 0000 4000 3606 35e2 a763 3db3  E..4..@.6.5..c=.
        0x0010:  4e28 dba3 9ded 0035 7f5b 1fdb f72b 5b61  N(.....5.[...+[a
        0x0020:  8010 040a 5da5 0000 0101 080a 04d1 07b9  ....]...........
        0x0030:  c343 a677                                .C.w
18:01:52.555031 IP 167.99.61.179.40429 > 78.40.219.163.53: Flags [P.], seq 1:210, ack 1, win 1034, options [nop,nop,TS val 80807865 ecr 3275990647], length 20962482 update [1n] [1au] SOA? peek.ru. (207)
        0x0000:  4500 0105 0000 4000 3606 3511 a763 3db3  E.....@.6.5..c=.
        0x0010:  4e28 dba3 9ded 0035 7f5b 1fdb f72b 5b61  N(.....5.[...+[a
        0x0020:  8018 040a 04f0 0000 0101 080a 04d1 07b9  ................
        0x0030:  c343 a677 00cf f412 2800 0001 0000 0001  .C.w....(.......
        0x0040:  0001 0470 6565 6b02 7275 0000 0600 010f  ...peek.ru......
        0x0050:  5f61 636d 652d 6368 616c 6c65 6e67 65c0  _acme-challenge.
        0x0060:  0c00 1000 fe00 0000 0000 2c2b 3378 524d  ..........,+3xRM
        0x0070:  3065 7854 474e 6554 426b 6976 3133 7849  0exTGNeTBkiv13xI
        0x0080:  4935 6144 6874 786b 694b 5971 6533 6a65  I5aDhtxkiKYqe3je
        0x0090:  6f43 3832 6172 6705 6c65 6b65 7900 00fa  oC82arg.lekey...
        0x00a0:  00ff 0000 0000 005d 0b68 6d61 632d 7368  .......].hmac-sh
        0x00b0:  6135 3132 0000 005a bd0d f001 2c00 40bc  a512...Z....,.@.
        0x00c0:  5c05 243d 6bb9 650e 6ea5 bc98 bcdf b235  \.$=k.e.n......5
        0x00d0:  ebf0 1ef8 97e3 b50a 5c58 a0ce 7f94 1311  ........\X......
        0x00e0:  c817 8221 4e34 12a5 cb84 dbf3 1e4a a0e4  ...!N4.......J..
        0x00f0:  a0ec 3741 b262 0888 2443 bed5 8f03 6ff4  ..7A.b..$C....o.
        0x0100:  1200 0000 00                             .....
18:01:52.555079 IP 78.40.219.163.53 > 167.99.61.179.40429: Flags [P.], seq 1:15, ack 210, win 1034, options [nop,nop,TS val 3275990759 ecr 80807865], length 1462482 update NotImp- [0q] 0/0/0 (12)
        0x0000:  4500 0042 0000 4000 4006 2bd4 4e28 dba3  E..B..@.@.+.N(..
        0x0010:  a763 3db3 0035 9ded f72b 5b61 7f5b 20ac  .c=..5...+[a.[..
        0x0020:  8018 040a c02a 0000 0101 080a c343 a6e7  .....*.......C..
        0x0030:  04d1 07b9 000c f412 a804 0000 0000 0000  ................
        0x0040:  0000                                     ..
18:01:52.666119 IP 167.99.61.179.40429 > 78.40.219.163.53: Flags [F.], seq 210, ack 15, win 1034, options [nop,nop,TS val 80807977 ecr 3275990759], length 0
        0x0000:  4500 0034 0000 4000 3606 35e2 a763 3db3  E..4..@.6.5..c=.
        0x0010:  4e28 dba3 9ded 0035 7f5b 20ac f72b 5b6f  N(.....5.[...+[o
        0x0020:  8011 040a 5be5 0000 0101 080a 04d1 0829  ....[..........)
        0x0030:  c343 a6e7                                .C..
18:01:52.666132 IP 78.40.219.163.53 > 167.99.61.179.40429: Flags [.], ack 211, win 1034, options [nop,nop,TS val 3275990870 ecr 80807977], length 0
        0x0000:  4500 0034 0000 4000 4006 2be2 4e28 dba3  E..4..@.@.+.N(..
        0x0010:  a763 3db3 0035 9ded f72b 5b6f 7f5b 20ad  .c=..5...+[o.[..
        0x0020:  8010 040a 5b76 0000 0101 080a c343 a756  ....[v.......C.V
        0x0030:  04d1 0829                                ...)
18:01:52.666222 IP 78.40.219.163.53 > 167.99.61.179.40429: Flags [F.], seq 15, ack 211, win 1034, options [nop,nop,TS val 3275990870 ecr 80807977], length 0
        0x0000:  4500 0034 0000 4000 4006 2be2 4e28 dba3  E..4..@.@.+.N(..
        0x0010:  a763 3db3 0035 9ded f72b 5b6f 7f5b 20ad  .c=..5...+[o.[..
        0x0020:  8011 040a 5b75 0000 0101 080a c343 a756  ....[u.......C.V
        0x0030:  04d1 0829                                ...)
18:01:52.776854 IP 167.99.61.179.40429 > 78.40.219.163.53: Flags [.], ack 16, win 1033, options [nop,nop,TS val 80808088 ecr 3275990870], length 0
        0x0000:  4500 0034 0000 4000 3606 35e2 a763 3db3  E..4..@.6.5..c=.
        0x0010:  4e28 dba3 9ded 0035 7f5b 20ad f72b 5b70  N(.....5.[...+[p
        0x0020:  8010 0409 5b07 0000 0101 080a 04d1 0898  ....[...........
        0x0030:  c343 a756                                .C.V
^C
22 packets captured
102 packets received by filter
0 packets dropped by kernel
```

Is this NSD issue?

**Comment by xm74** [comment]
I found that NSD doesn't support nsupdate functional so this is not certbot issue.
Anyway thank you for support.
