### ISSUE TITLE
use docker certbot produced an unexpected error Max retries exceeded with url: /directory

### ISSUE THREAD

**Issue by 1371030** [certbot/certbot#5843]
CentOS 6.9
docker run --rm -it \
    -v /etc/letsencrypt:/etc/letsencrypt \
    -v /var/log/letsencrypt:/var/log/letsencrypt \
    -v /home/host:/home/host \
    certbot/certbot:latest certonly \
    --webroot --webroot-path /home/host -m admin@host.net \
    -d host.net

Prep: True
2018-04-10 00:11:07,656:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7fafb4263990> and installer None
2018-04-10 00:11:07,656:INFO:certbot.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2018-04-10 00:11:07,662:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(status=None, terms_of_service_agreed=None, contact=(u'mailto:admin@host.net',), agreement=u'https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf', key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x7fafb41e23d0>)>)), uri=u'https://acme-v01.api.letsencrypt.org/acme/reg/19727708', new_authzr_uri=u'https://acme-v01.api.letsencrypt.org/acme/new-authz', terms_of_service=u'https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf'), bdfbe34a822413a8a57d42650321ff4c, Meta(creation_host=u'a9406a9ca91e', creation_dt=datetime.datetime(2017, 8, 9, 1, 36, 58, tzinfo=<UTC>)))>
2018-04-10 00:11:07,664:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2018-04-10 00:11:07,667:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2018-04-10 00:11:12,673:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/main.py", line 1266, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/main.py", line 1141, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/opt/certbot/src/certbot/main.py", line 642, in _init_le_client
    return client.Client(config, acc, authenticator, installer, acme=acme)
  File "/opt/certbot/src/certbot/client.py", line 230, in __init__
    acme = acme_from_config_key(config, self.account.key, self.account.regr)
  File "/opt/certbot/src/certbot/client.py", line 46, in acme_from_config_key
    return acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/opt/certbot/src/acme/acme/client.py", line 718, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/opt/certbot/src/acme/acme/client.py", line 1041, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/opt/certbot/src/acme/acme/client.py", line 990, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fafb41f82d0>: Failed to establish a new connection: [Errno -3] Try again',))
2018-04-10 00:11:12,676:ERROR:certbot.log:An unexpected error occurred:

**Comment by schoen** [comment]
Hi @1371030 ,

Could you try the forum at https://community.letsencrypt.org/? I think you'll find a larger and more relevant community to help you out over there. This GitHub issue queue is read by just a handful of Certbot developers and not by many other users.

Could you try running a command line inside that Docker image and running `curl -v https://acme-v01.api.letsencrypt.org/directory` to try to find out more about why the connection failed? (But instead of sharing your results here, maybe you could share them on the forum?)

Thanks!
