### ISSUE TITLE
dns-rfc2136: support port in dns_rfc2136_server config

### ISSUE THREAD

**Issue by MorphBonehunter** [certbot/certbot#5867]
## My operating system is (include version):
Arch Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager

## I ran this command and it produced this output:
edit the `certbot-rfc2136.ini`:
```
dns_rfc2136_server = 192.168.200.1:5353
```
because the Master is an hidden Primary and doesn't listen to default port
```
certbot certonly --dry-run --dns-rfc2136 --dns-rfc2136-credentials /root/nsupdate/certbot-rfc2136.ini -d 'example.com'
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-rfc2136, Installer None
Obtaining a new certificate
/usr/lib/python3.6/site-packages/josepy/jwa.py:107: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(self.padding, self.hash)
Performing the following challenges:
dns-01 challenge for example.com
Cleaning up challenges
Encountered exception during recovery
Encountered error when making query: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 205, in _query_soa
    response = dns.query.udp(request, self.server)
  File "/usr/lib/python3.6/site-packages/dns/query.py", line 238, in udp
    s.sendto(wire, destination)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 73, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 124, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 74, in _perform
    self._get_rfc2136_client().add_txt_record(validation_name, validation, self.ttl)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 108, in add_txt_record
    domain = self._find_domain(record_name)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 182, in _find_domain
    if self._query_soa(guess):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 218, in _query_soa
    .format(e))
certbot.errors.PluginError: Encountered error when making query: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 205, in _query_soa
    response = dns.query.udp(request, self.server)
  File "/usr/lib/python3.6/site-packages/dns/query.py", line 238, in udp
    s.sendto(wire, destination)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/error_handler.py", line 103, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 308, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 77, in _cleanup
    self._get_rfc2136_client().del_txt_record(validation_name, validation)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 143, in del_txt_record
    domain = self._find_domain(record_name)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 182, in _find_domain
    if self._query_soa(guess):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 218, in _query_soa
    .format(e))
certbot.errors.PluginError: Encountered error when making query: [Errno -2] Name or service not known
Encountered error when making query: [Errno -2] Name or service not known
```

## Certbot's behavior differed from what I expected because:
I would expect the given Port is used and the request succeed.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2018-04-13 10:42:15,044:DEBUG:certbot.main:certbot version: 0.23.0
2018-04-13 10:42:15,047:DEBUG:certbot.main:Arguments: ['--dry-run', '--dns-rfc2136', '--dns-rfc2136-credentials', '~/nsupdate/certbot-rfc2136.ini', '-d', 'example.com']
2018-04-13 10:42:15,048:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-rfc2136,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-04-13 10:42:15,212:DEBUG:certbot.log:Root logging level set at 20
2018-04-13 10:42:15,214:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-04-13 10:42:15,216:DEBUG:certbot.plugins.selection:Requested authenticator dns-rfc2136 and installer None
2018-04-13 10:42:15,231:DEBUG:certbot.plugins.selection:Single candidate plugin: * dns-rfc2136
Description: Obtain certificates using a DNS TXT record (if you are using BIND for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-rfc2136 = certbot_dns_rfc2136.dns_rfc2136:Authenticator
Initialized: <certbot_dns_rfc2136.dns_rfc2136.Authenticator object at 0x7f83470269e8>
Prep: True
2018-04-13 10:42:15,233:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_dns_rfc2136.dns_rfc2136.Authenticator object at 0x7f83470269e8> and installer None
2018-04-13 10:42:15,233:INFO:certbot.plugins.selection:Plugins selected: Authenticator dns-rfc2136, Installer None
2018-04-13 10:42:15,244:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x7f8343cdfbe0>)>), contact=(), agreement=None, status='valid', terms_of_service_agreed=None), uri='https://acme-staging-v02.api.letsencrypt.org/acme/acct/5912859', new_authzr_uri=None, terms_of_service='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'), 9a3aaece632e6dbd4fece6ae581b48d0, Meta(creation_dt=datetime.datetime(2018, 4, 13, 8, 20, 18, tzinfo=<UTC>), creation_host='pandora.example.com'))>
2018-04-13 10:42:15,247:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/directory.
2018-04-13 10:42:15,252:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org
2018-04-13 10:42:15,537:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 724
2018-04-13 10:42:15,539:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 724
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 13 Apr 2018 08:42:15 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 13 Apr 2018 08:42:15 GMT
Connection: keep-alive

b'{\n  "-v0ZLhz7MA0": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",\n  "keyChange": "https://acme-staging-v02.api.letsencrypt.org/acme/key-change",\n  "meta": {\n    "caaIdentities": [\n      "letsencrypt.org"\n    ],\n    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",\n    "website": "https://letsencrypt.org/docs/staging-environment/"\n  },\n  "newAccount": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct",\n  "newNonce": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce",\n  "newOrder": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order",\n  "revokeCert": "https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert"\n}'
2018-04-13 10:42:15,542:INFO:certbot.main:Obtaining a new certificate
2018-04-13 10:42:15,830:DEBUG:acme.client:Requesting fresh nonce
2018-04-13 10:42:15,830:DEBUG:acme.client:Sending HEAD request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order.
2018-04-13 10:42:16,016:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "HEAD /acme/new-order HTTP/1.1" 405 0
2018-04-13 10:42:16,017:DEBUG:acme.client:Received response:
HTTP 405
Server: nginx
Content-Type: application/problem+json
Content-Length: 103
Allow: POST
Replay-Nonce: az-HWHMmKAr4oyMHbebuF34S7adBmvH5UGvmRK0VFRk
Expires: Fri, 13 Apr 2018 08:42:16 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 13 Apr 2018 08:42:16 GMT
Connection: keep-alive

b''
2018-04-13 10:42:16,018:DEBUG:acme.client:Storing nonce: az-HWHMmKAr4oyMHbebuF34S7adBmvH5UGvmRK0VFRk
2018-04-13 10:42:16,019:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "example.com"\n    }\n  ],\n  "status": "pending",\n  "resource": "new-order"\n}'
2018-04-13 10:42:16,030:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC81OTEyODU5IiwgIm5vbmNlIjogImF6LUhXSE1tS0FyNG95TUhiZWJ1RjM0UzdhZEJtdkg1VUd2bVJLMFZGUmsiLCAidXJsIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvbmV3LW9yZGVyIn0",
  "signature": "c3craNWWTmIIst8oTagEzK4OLSf1kdUdJ4c7ObqyBMmCciT7fjJg2yL10j7I_TF2EnTZKkPsvMY6faYFfu_fzhNVtVyOZfUD_kMrPDtGPLcR5t8s2VrY6Pu941xHZngIqKlHDmO6CiJjGb6JC08cHfCsrIslx5ataZF4DtjTuA1iD3CfLWJzUgl9f9onIwQmw699L78YhOHu1UG-fv6XFgiU3jjCIlv9vk7lZJUEm-she5phFxjT9sXuoVX6r0la8dLNw4HFmgl6Vj9kvxUt1U90WkWsLJ-WeyIZiXkHSBYWZLosqJ1xoJjSzFH7vClzY8ALscEl2BS118DNEgtliA",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImV4YW1wbGUuY29tIgogICAgfQogIF0sCiAgInN0YXR1cyI6ICJwZW5kaW5nIiwKICAicmVzb3VyY2UiOiAibmV3LW9yZGVyIgp9"
}
2018-04-13 10:42:16,245:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 382
2018-04-13 10:42:16,247:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Content-Type: application/json
Content-Length: 382
Boulder-Requester: 5912859
Location: https://acme-staging-v02.api.letsencrypt.org/acme/order/5912859/376986
Replay-Nonce: vcKxYSPSE5xstswxL4ugdCWJB57aNe1MpyVfAcIu6yE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 13 Apr 2018 08:42:16 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 13 Apr 2018 08:42:16 GMT
Connection: keep-alive

b'{\n  "status": "pending",\n  "expires": "2018-04-20T08:42:16.126651651Z",\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "example.com"\n    }\n  ],\n  "authorizations": [\n    "https://acme-staging-v02.api.letsencrypt.org/acme/authz/sTTGqWX_LAQtjw1GYRDcmgOVKy0ctWiOQx-eg5YlIhw"\n  ],\n  "finalize": "https://acme-staging-v02.api.letsencrypt.org/acme/finalize/5912859/376986"\n}'
2018-04-13 10:42:16,247:DEBUG:acme.client:Storing nonce: vcKxYSPSE5xstswxL4ugdCWJB57aNe1MpyVfAcIu6yE
2018-04-13 10:42:16,248:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/acme/authz/sTTGqWX_LAQtjw1GYRDcmgOVKy0ctWiOQx-eg5YlIhw.
2018-04-13 10:42:16,479:DEBUG:urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "GET /acme/authz/sTTGqWX_LAQtjw1GYRDcmgOVKy0ctWiOQx-eg5YlIhw HTTP/1.1" 200 664
2018-04-13 10:42:16,480:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 664
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Fri, 13 Apr 2018 08:42:16 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Fri, 13 Apr 2018 08:42:16 GMT
Connection: keep-alive

b'{\n  "identifier": {\n    "type": "dns",\n    "value": "example.com"\n  },\n  "status": "pending",\n  "expires": "2018-04-20T08:42:16Z",\n  "challenges": [\n    {\n      "type": "http-01",\n      "status": "pending",\n      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/challenge/sTTGqWX_LAQtjw1GYRDcmgOVKy0ctWiOQx-eg5YlIhw/117425052",\n      "token": "iSJd78iEiIwGQAxxAoz2Bo-4xdDfsDNwAJ_mkJmqApA"\n    },\n    {\n      "type": "dns-01",\n      "status": "pending",\n      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/challenge/sTTGqWX_LAQtjw1GYRDcmgOVKy0ctWiOQx-eg5YlIhw/117425053",\n      "token": "vBa2uMU6ovWOA5ffAq7-AvZUWNBa2iwRsQ-kHroCf7w"\n    }\n  ]\n}'
2018-04-13 10:42:16,482:INFO:certbot.auth_handler:Performing the following challenges:
2018-04-13 10:42:16,483:INFO:certbot.auth_handler:dns-01 challenge for example.com
2018-04-13 10:42:16,495:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 205, in _query_soa
    response = dns.query.udp(request, self.server)
  File "/usr/lib/python3.6/site-packages/dns/query.py", line 238, in udp
    s.sendto(wire, destination)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 73, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 124, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 74, in _perform
    self._get_rfc2136_client().add_txt_record(validation_name, validation, self.ttl)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 108, in add_txt_record
    domain = self._find_domain(record_name)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 182, in _find_domain
    if self._query_soa(guess):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 218, in _query_soa
    .format(e))
certbot.errors.PluginError: Encountered error when making query: [Errno -2] Name or service not known

2018-04-13 10:42:16,496:DEBUG:certbot.error_handler:Calling registered functions
2018-04-13 10:42:16,496:INFO:certbot.auth_handler:Cleaning up challenges
2018-04-13 10:42:16,502:ERROR:certbot.error_handler:Encountered exception during recovery
2018-04-13 10:42:16,502:ERROR:certbot.error_handler:Encountered error when making query: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 205, in _query_soa
    response = dns.query.udp(request, self.server)
  File "/usr/lib/python3.6/site-packages/dns/query.py", line 238, in udp
    s.sendto(wire, destination)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 73, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 124, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 74, in _perform
    self._get_rfc2136_client().add_txt_record(validation_name, validation, self.ttl)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 108, in add_txt_record
    domain = self._find_domain(record_name)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 182, in _find_domain
    if self._query_soa(guess):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 218, in _query_soa
    .format(e))
certbot.errors.PluginError: Encountered error when making query: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 205, in _query_soa
    response = dns.query.udp(request, self.server)
  File "/usr/lib/python3.6/site-packages/dns/query.py", line 238, in udp
    s.sendto(wire, destination)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/error_handler.py", line 103, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 308, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 77, in _cleanup
    self._get_rfc2136_client().del_txt_record(validation_name, validation)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 143, in del_txt_record
    domain = self._find_domain(record_name)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 182, in _find_domain
    if self._query_soa(guess):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 218, in _query_soa
    .format(e))
certbot.errors.PluginError: Encountered error when making query: [Errno -2] Name or service not known
2018-04-13 10:42:16,505:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 205, in _query_soa
    response = dns.query.udp(request, self.server)
  File "/usr/lib/python3.6/site-packages/dns/query.py", line 238, in udp
    s.sendto(wire, destination)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.23.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1266, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1157, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 118, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 350, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 294, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3.6/site-packages/certbot/client.py", line 330, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 73, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3.6/site-packages/certbot/auth_handler.py", line 124, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 74, in _perform
    self._get_rfc2136_client().add_txt_record(validation_name, validation, self.ttl)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 108, in add_txt_record
    domain = self._find_domain(record_name)
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 182, in _find_domain
    if self._query_soa(guess):
  File "/usr/lib/python3.6/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 218, in _query_soa
    .format(e))
certbot.errors.PluginError: Encountered error when making query: [Errno -2] Name or service not known
```

**Comment by MorphBonehunter** [comment]
Ahh...sorry, i search for an issue, but not in the PR's.
So the issue could be closed if the PR got merged...

**Comment by joohoi** [comment]
The PR was just merged  to master!
