### ISSUE TITLE
certbot plugins fails to start

### ISSUE THREAD

**Issue by winteraz** [certbot/certbot#5948]
certbot plugins
Traceback (most recent call last):
  File "/usr/bin/certbot", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: mock

**Comment by schoen** [comment]
As with the other issue, please reopen this with the information from the template if you're still having this problem. Thanks.
