### ISSUE TITLE
Renewed certificate expires in the past

### ISSUE THREAD

**Issue by letsencrypt-user-g528jdgstajk8s7h** [certbot/certbot#6084]
## My operating system is (include version):
Debian GNU/Linux testing (buster) 

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt install certbot

## I ran this command and it produced this output:

```
$ date
Fri  8 Jun 14:50:06 UTC 2018

$ certbot --version
certbot 0.25.0.dev0

$ certbot certonly -d MYDOMAIN
Saving debug log to /var/log/letsencrypt/letsencrypt.log

How would you like to authenticate with the ACME CA?
-------------------------------------------------------------------------------                                                                     
1: Spin up a temporary webserver (standalone)
2: Place files in webroot directory (webroot)
-------------------------------------------------------------------------------                                                                     
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): 1
Plugins selected: Authenticator standalone, Installer None
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for MYDOMAIN
Waiting for verification...
Cleaning up challenges

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/MYDOMAIN/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/MYDOMAIN/privkey.pem
   Your cert will expire on 2017-10-21. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

$ openssl x509 -in /etc/letsencrypt/live/MYDOMAIN/fullchain.pem -noout -text          
                                                               
Certificate:                                                   
    Data:                                                      
        Version: 3 (0x2)                                       
        Serial Number:                                         
            03:e8:4d:16:XX:XX:XX:XX:XX:XX:30:0d:2a:6a:5a:48:02
    Signature Algorithm: sha256WithRSAEncryption                            
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity                                               
            Not Before: Jul 23 10:32:00 2017 GMT               
            Not After : Oct 21 10:32:00 2017 GMT                           
        Subject: CN = MYDOMAIN                                   
        Subject Public Key Info:                                                 
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)   
...
```

This has been the case for months and the last time I ran the renew command a few times and got barred from further renewals. Wih the git version I get the following errors:

```
$ git log 
commit afa7e3fb8266fb6af7c36d46eb8ee20e844d8107 (HEAD -> master, origin/master, origin/HEAD)
Author: Brad Warren <bmw@users.noreply.github.com>
Date:   Thu Jun 7 14:45:23 2018 -0700
...


$ ./certbot-auto
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt: 
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 4, in <module>
    import logging.handlers
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

**Comment by schoen** [comment]
Hi @letsencrypt-user-g528jdgstajk8s7h,

Thanks for reporting this problem. This does look like a bug, I'd like to get some more information about this—could you share the log from `/var/log/letsencrypt` associated with one of the renewals?

Also, did you ever modify the structure of the items inside `/etc/letsencrypt` in any way, like by renaming files or directories there?

**Comment by joohoi** [comment]
Looks like this never got answered, so I'm closing it.
