### ISSUE TITLE
Certbot dependencies conflict on Arch Linux (python-idna)

### ISSUE THREAD

**Issue by CannyFoxx** [certbot/certbot#6086]
## Operating system:
Arch Linux

## Installed as:
System package (pacman -S)

## I ran this command and it produced this output:
**$** certbot
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.7 (/usr/lib/python3.6/site-packages), Requirement.parse('idna<2.7,>=2.5'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.7 (/usr/lib/python3.6/site-packages), Requirement.parse('idna<2.7,>=2.5'), {'requests'})
```

## Current version of python-idna in ArchLinux repository:
2.7

**Comment by p53** [comment]
same problem here ubuntu 16.04, installing certbot with pip, problem is that today they released new version of idna 2.7 which doesn't work with requests python module..., idna is installed as dependency of cryptography module which only states it needs version of idna >=2.1

**Comment by CannyFoxx** [comment]
Problem is already resolved on Arch Linux.

**Comment by schoen** [comment]
@joohoi, do you know if the dependencies might be misstated somehow? Maybe not by us but by another packager?

**Comment by joohoi** [comment]
It looks like pyca/cryptography has [requirement](https://github.com/pyca/cryptography/blob/master/setup.py#L287) of  `"idna >= 2.1"` which naturally pulls in the most recent version. Requests itself [wants](https://github.com/requests/requests/blob/master/setup.py#L53) `"idna<2.7,>=2.5"`, and that causes the issue. I believe the issue here is the packaging of `python-requests`, and more specifically handling the conflicting depended version of `idna`.

**Comment by bmw** [comment]
This issue has been closed due to lack of activity, but if you think it should be reopened, please open a new issue with a link to this one and we'll take a look.
