### ISSUE TITLE
cerbot ReadTimeout but curl success.

### ISSUE THREAD

**Issue by kj863257** [certbot/certbot#6132]
```
CURL

curl https://acme-v01.api.letsencrypt.org/directory -v
* About to connect() to acme-v01.api.letsencrypt.org port 443 (#0)
*   Trying 118.214.71.162...
* Connected to acme-v01.api.letsencrypt.org (118.214.71.162) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=acme-v02.api.letsencrypt.org
* 	start date: 5月 25 00:25:19 2018 GMT
* 	expire date: 8月 23 00:25:19 2018 GMT
* 	common name: acme-v02.api.letsencrypt.org
* 	issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
> GET /directory HTTP/1.1
> User-Agent: curl/7.29.0
> Host: acme-v01.api.letsencrypt.org
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: application/json
< Content-Length: 658
< Replay-Nonce: cKSigvAIEBfCmGRsVGDI-wO627OPu1KofMd19UW-irI
< X-Frame-Options: DENY
< Strict-Transport-Security: max-age=604800
< Expires: Wed, 20 Jun 2018 07:26:46 GMT
< Cache-Control: max-age=0, no-cache, no-store
< Pragma: no-cache
< Date: Wed, 20 Jun 2018 07:26:46 GMT
< Connection: keep-alive
< 
{
  "5B7v2iqIjdM": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
* Connection #0 to host acme-v01.api.letsencrypt.org left intact
}# 


```

Curl is done and soon，but certbot timeout

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
An unexpected error occurred:
ReadTimeout: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Read timed out. (read timeout=45)
Please see the logfiles in /var/log/letsencrypt for more details.



cat /var/log/letsencrypt/letsencrypt.log
2018-06-20 15:29:35,192:DEBUG:certbot.main:certbot version: 0.24.0
2018-06-20 15:29:35,192:DEBUG:certbot.main:Arguments: ['--nginx', '-d', 'a3d.cc', '--email', 'kj863257@163.com', '--nginx-server-root', '/usr/local/nginx/conf/']
2018-06-20 15:29:35,192:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-06-20 15:29:35,215:DEBUG:certbot.log:Root logging level set at 20
2018-06-20 15:29:35,215:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-06-20 15:29:35,216:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2018-06-20 15:29:35,526:DEBUG:certbot.plugins.selection:Single candidate plugin: * nginx
Description: Nginx Web Server plugin - Alpha
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: nginx = certbot_nginx.configurator:NginxConfigurator
Initialized: <certbot_nginx.configurator.NginxConfigurator object at 0x7f4f6867be50>
Prep: True
2018-06-20 15:29:35,526:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_nginx.configurator.NginxConfigurator object at 0x7f4f6867be50> and installer <certbot_nginx.configurator.NginxConfigurator object at 0x7f4f6867be50>
2018-06-20 15:29:35,526:INFO:certbot.plugins.selection:Plugins selected: Authenticator nginx, Installer nginx
2018-06-20 15:29:35,823:DEBUG:acme.client:Sending GET request to https://acme-v01.api.letsencrypt.org/directory.
2018-06-20 15:29:35,828:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2018-06-20 15:30:21,204:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.24.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1315, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1072, in run
    le_client = _init_le_client(config, authenticator, installer)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 637, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 516, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 164, in register
    acme = acme_from_config_key(config, key)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 46, in acme_from_config_key
    return acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 718, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 1041, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 990, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='acme-v01.api.letsencrypt.org', port=443): Read timed out. (read timeout=45)
2018-06-20 15:30:21,206:ERROR:certbot.log:An unexpected error occurred:



```

and I try 'wget' but 'wget' read timeout too. 

Can anyone tell me why?

 thank you very much.

**Comment by sydneyli** [comment]
Is it taking longer than 45 seconds to fetch the file? We have 45s as the default timeout, but I believe curl's default timeout is much longer.

**Comment by kj863257** [comment]
But I test the actual request of the C URL for less than 3 seconds. It's a strange question. It's normal on another server.

**Comment by sydneyli** [comment]
Oh, I just read that `wget` is timing out for you too. What version is `wget`, and what distribution/OS are you on?

**Comment by kj863257** [comment]
Linux version 3.10.0-693.5.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Fri Oct 20 20:32:50 UTC 2017



`wget ` can set the timeout with the -T parameter, but no matter how long I wait, the process will stay connected.

**Comment by sydneyli** [comment]
@kj863257 I'm going to close this for now since this doesn't seem like a Certbot-specific issue. I would recommend posting in the [community forums](https://community.letsencrypt.org/) about this, where you may get your issue resolved quicker, since there's a larger audience of people who are also familiar with Certbot.
