### ISSUE TITLE
Use account reuse symlink logic when loading an account

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6154]
To reproduce, start with an empty Certbot config directory and use any released version of Certbot to obtain an ACMEv1 prod cert. You shouldn't set `--server` anywhere.

Then checkout the `acmev2-default` branch and run `certbot renew --force-renewal`. You should see an error like:
```
Traceback (most recent call last):
  File "/home/bmw/src/certbot/certbot/renewal.py", line 430, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/home/bmw/src/certbot/certbot/main.py", line 1190, in renew_cert
    le_client = _init_le_client(config, auth, installer)
  File "/home/bmw/src/certbot/certbot/main.py", line 641, in _init_le_client
    acc, acme = _determine_account(config)
  File "/home/bmw/src/certbot/certbot/main.py", line 508, in _determine_account
    acc = account_storage.load(config.account)
  File "/home/bmw/src/certbot/certbot/account.py", line 224, in load
    return self._load_for_server_path(account_id, self.config.server_path)
  File "/home/bmw/src/certbot/certbot/account.py", line 204, in _load_for_server_path
    "Account at %s does not exist" % account_dir_path)
AccountNotFound: Account at /etc/letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/8f7e408abe6ff5832f20529fb812abad does not exist
```
This happens because the default server value changed to ACMEv2 and Certbot is looking for the account specified in the renewal configuration file in the ACMEv2 account directory which doesn't exist and hasn't been symlinked yet.

**Comment by ohemorange** [comment]
planning to move the account reuse logic into `load`, then have `find_all` use that logic

**Comment by ohemorange** [comment]
or maybe also call into the logic

either way, planning to add things to `load`
