### ISSUE TITLE
Ubuntu16.04 nignx: coding problems

### ISSUE THREAD

**Issue by wushichatong** [certbot/certbot#6165]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

pip
## I ran this command and it produced this output:

certbot --nginx
## Certbot's behavior differed from what I expected because:
'utf-8' codec can't decode byte 0xcd in position 66: invalid continuation byte

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2018-07-01 09:59:27,003:ERROR:certbot.log:An unexpected error occurred:
2018-07-01 10:00:55,645:DEBUG:certbot.main:certbot version: 0.25.0
2018-07-01 10:00:55,646:DEBUG:certbot.main:Arguments: ['--nginx']
2018-07-01 10:00:55,647:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-07-01 10:00:55,671:DEBUG:certbot.log:Root logging level set at 20
2018-07-01 10:00:55,672:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-07-01 10:00:55,673:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2018-07-01 10:00:55,780:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 12, in <module>
    load_entry_point('certbot==0.25.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1323, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1192, in certonly
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 198, in choose_configurator_plugins
    installer = pick_installer(config, req_inst, plugins, installer_question)
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 32, in pick_installer
    config, default, plugins, question, (interfaces.IInstaller,))
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 77, in pick_plugin
    verified.prepare()
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 246, in prepare
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 246, in <listcomp>
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 127, in prepare
    self._initialized.prepare()
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 144, in prepare
    self.parser = parser.NginxParser(self.conf('server-root'))
  File "/usr/lib/python3/dist-packages/certbot_nginx/parser.py", line 38, in __init__
    self.load()
  File "/usr/lib/python3/dist-packages/certbot_nginx/parser.py", line 45, in load
    self._parse_recursively(self.config_root)
  File "/usr/lib/python3/dist-packages/certbot_nginx/parser.py", line 66, in _parse_recursively
    self._parse_recursively(subentry[1])
  File "/usr/lib/python3/dist-packages/certbot_nginx/parser.py", line 56, in _parse_recursively
    trees = self._parse_files(filepath)
  File "/usr/lib/python3/dist-packages/certbot_nginx/parser.py", line 207, in _parse_files
    parsed = nginxparser.load(_file)
  File "/usr/lib/python3/dist-packages/certbot_nginx/nginxparser.py", line 123, in load
    return loads(_file.read())
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 66: invalid continuation byte
2018-07-01 10:00:55,782:ERROR:certbot.log:An unexpected error occurred:

**Comment by schoen** [comment]
Hi @wushichatong ,

Unfortunately, I believe you've encountered a variant of a known bug, which is that the Certbot nginx and Apache parsers frequently fail to parse configuration files correctly when the configuration files contain non-ASCII characters (such as Unicode-encoded Chinese characters, for example). This problem is especially likely when the non-ASCII characters are found in a configuration directly that Certbot needs to understand, but they can even happen in many cases when the non-ASCII characters are merely found in a comment!

We recognize that this is a bug in Certbot, because both Apache and nginx permit non-ASCII text in configuration files and users are certainly entitled to use it. However, our current parsers do get confused in many such situations.

For more information about the status of this bug, I suggest following

https://github.com/certbot/certbot/issues/5337 (or similar related issues)

https://github.com/certbot/certbot/projects/2

In the meantime, you could work around this problem by

* switching to a different Let's Encrypt client (although I don't know for sure whether there's another client that can modify nginx configurations and that doesn't suffer from a similar bug)
* using `certbot certonly -a webroot` instead of `certbot --nginx` (this is less convenient, because you have to have the web server set up to serve static files from some location on disk, and you'll have to edit the nginx configuration file yourself to install the certificate at the end)
* temporarily removing the non-ASCII text from your nginx configuration files

I'm sorry for the inconvenience that this bug is causing you.

**Comment by sydneyli** [comment]
Closing as duplicate.
