### ISSUE TITLE
Reduce test output from certbot

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6241]
See https://kojipkgs.fedoraproject.org//work/tasks/136/28160136/build.log and the many
```
Logged from file util.py, line 144
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python2.7/logging/handlers.py", line 152, in shouldRollover
    self.stream = self._open()
  File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
    stream = open(self.baseFilename, self.mode)
```
lines.

**Comment by bmw** [comment]
@adferrand is going to take this as well

**Comment by adferrand** [comment]
Taken.

**Comment by adferrand** [comment]
@bmw 

The log seems to not be displayed anymore in any of the jobs executed by travis. I think the issue can be closed.

**Comment by bmw** [comment]
Nice catch. Thanks @adferrand.
