### ISSUE TITLE
Can not create virtualenv. The version is 15.0.1 instead of 16.0.0.

### ISSUE THREAD

**Issue by quangnd617** [certbot/certbot#6272]
I'm trying to install certbot with below command and I got this error:
sudo -H ./letsencrypt-auto certonly --standalone -d mysite -d www.mysite
```
Bootstrapping dependencies for Debian-based OSes... (you can skip this with --no-bootstrap)
Hit:1 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB] 
Get:3 http://us-east-2.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]                                                          
Ign:4 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 InRelease                                                                         
Hit:5 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 Release                               
Hit:6 http://security.ubuntu.com/ubuntu xenial-security InRelease
Get:8 http://openresty.org/package/ubuntu xenial InRelease [5,639 B]
Fetched 222 kB in 1s (118 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gcc is already the newest version (4:5.3.1-1ubuntu1).
libffi-dev is already the newest version (3.2.1-4).
augeas-lenses is already the newest version (1.4.0-0ubuntu1.1).
ca-certificates is already the newest version (20170717~16.04.1).
libaugeas0 is already the newest version (1.4.0-0ubuntu1.1).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.13).
openssl is already the newest version (1.0.2g-1ubuntu4.13).
python is already the newest version (2.7.12-1~16.04).
python-dev is already the newest version (2.7.12-1~16.04).
python-virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
The following packages were automatically installed and are no longer required:
  gyp javascript-common libjs-inherits libjs-jquery libjs-node-uuid libjs-underscore libuv1 libuv1-dev linux-aws-headers-4.4.0-1061 linux-headers-4.4.0-1061-aws linux-image-4.4.0-1061-aws
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'virtualenv==16.0.0' distribution was not found and is required by the application
```

But my virtualenv is on 16.0.0 already.
```
virtualenv --version
16.0.0
```

Where did I go wrong?
Do I have to change python to 3.5 ?
My operating system: Ubuntu 16.04

**Comment by sydneyli** [comment]
It sounds like you may have different versions of `virtualenv` installed between `sudo` and your current user.

This doesn't seem to be an immediate Certbot issue, so I'm closing this for now. I suggest posting on [the LetsEncrypt community forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people who are also familiar with the project. You'll probably get installation help faster there!
