### ISSUE TITLE
certbot-dns-rfc2136 should accept name for server

### ISSUE THREAD

**Issue by brianjmurrell** [certbot/certbot#6282]
## My operating system is (include version):
CentOS 7.5

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager

## I ran this command and it produced this output:
```
# certbot certonly --dns-rfc2136 --dns-rfc2136-credentials /etc/certbot-dns-rfc2136.ini -d certbottest.interlinx.bc.ca
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-rfc2136, Installer None
Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for certbottest.interlinx.bc.ca
in _query_soa(_acme-challenge.certbottest.interlinx.bc.ca)
domain: _acme-challenge.certbottest.interlinx.bc.ca.
Cleaning up challenges
in _query_soa(_acme-challenge.certbottest.interlinx.bc.ca)
domain: _acme-challenge.certbottest.interlinx.bc.ca.
Encountered exception during recovery: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/error_handler.py", line 108, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 310, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python2.7/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 79, in _cleanup
    self._get_rfc2136_client().del_txt_record(validation_name, validation)
  File "/usr/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 147, in del_txt_record
    domain = self._find_domain(record_name)
  File "/usr/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 186, in _find_domain
    if self._query_soa(guess):
  File "/usr/lib/python2.7/site-packages/certbot_dns_rfc2136/dns_rfc2136.py", line 224, in _query_soa
    .format(e))
PluginError: Encountered error when making query: Text input is malformed.
Encountered error when making query: Text input is malformed.
```

## Certbot's behavior differed from what I expected because:
I used a name instead of an IP address in the `/etc/certbot-dns-rfc2136.ini` file.

## Here is a Certbot log showing the issue (if available):
Not necessary I think.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A

**Comment by sydneyli** [comment]
Just clarifying: are you referring to using a name for the target DNS instead of an IP address? If you don't specify an IP, we run into a sort of chicken-and-egg problem: which DNS server should resolve the name of the DNS?

**Comment by brianjmurrell** [comment]
> Just clarifying: are you referring to using a name for the target DNS instead of an IP address?

Yes, I'm talking about using a name for the target server such as:

```
dns_rfc2136_server = server.example.com
```

> If you don't specify an IP, we run into a sort of chicken-and-egg problem: which DNS server should resolve the name of the DNS?

The server(s) configured in the resolver of the host.  I.e. if `dns_rfc2136_server` is a name, not an IP address, perform a `gethostbyname()` on it to get an IP address.

**Comment by sydneyli** [comment]
ah okay, thanks for clarifying @brianjmurrell! It might take us some time to get around to this, but would gladly accept contributions for this if you're interested in writing a PR?

**Comment by sydneyli** [comment]
There's actually already a PR open for this at #5664! I wasn't able to find an issue that's tracking it, so let's use this one :)

**Comment by kpfleming** [comment]
The code which is involved here has not changed; the 'server' configuration item is still passed directly to `dnspython`, and it only accepts addresses (it does not perform lookups to convert names into addresses). The PR will need to be updated to align with the current code in master, but the PR is still necessary.

**Comment by kaceo** [comment]
I searched for the error and landed here... sad to see that this is still not patched after one year.  In my usage case, the BIND server is inside one docker, and the CERTBOT is in another docker, and so hostname resolution is preferred to actual IP since the docker network assigns its own internal temporary IP addresses to each container.

**Comment by brianjmurrell** [comment]
The [PR](https://github.com/certbot/certbot/pull/5664) for this issue is still open so the issue should stay open.

**Comment by davispuh** [comment]
So in my `rfc2136.ini` I have `dns_rfc2136_server = example.org` and I'm pretty sure this used to work in past.
But now I'm getting error when trying to renew.

```
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator dns-rfc2136, Installer None
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for domain.example.org
Cleaning up challenges
Encountered exception during recovery: 
Traceback (most recent call last):                                                                                      
  File "/usr/lib/python3.8/site-packages/dns/inet.py", line 87, in af_for_address                                       
    dns.ipv4.inet_aton(text)                                                                                            
  File "/usr/lib/python3.8/site-packages/dns/ipv4.py", line 49, in inet_aton                                            
    raise dns.exception.SyntaxError                                                                                     
dns.exception.SyntaxError: Text input is malformed.                                                                     

During handling of the above exception, another exception occurred:                                                     

Traceback (most recent call last):                                                                                      
  File "/usr/lib/python3.8/site-packages/dns/inet.py", line 91, in af_for_address                                       
    dns.ipv6.inet_aton(text, True)                                                                                      
  File "/usr/lib/python3.8/site-packages/dns/ipv6.py", line 165, in inet_aton                                           
    raise dns.exception.SyntaxError                                                                                     
dns.exception.SyntaxError: Text input is malformed.                                                                     

During handling of the above exception, another exception occurred:                                                     

Traceback (most recent call last):                                                                                      
  File "/usr/lib/python3.8/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py", line 210, in _query_soa         
    response = dns.query.tcp(request, self.server, port=self.port)                                                      
  File "/usr/lib/python3.8/site-packages/dns/query.py", line 752, in tcp                                                
    (af, destination, source) = _destination_and_source(where, port,                                                    
  File "/usr/lib/python3.8/site-packages/dns/query.py", line 226, in _destination_and_source                            
    af = dns.inet.af_for_address(where)                                                                                 
  File "/usr/lib/python3.8/site-packages/dns/inet.py", line 94, in af_for_address                                       
    raise ValueError                                                                                                    
ValueError                                                                                                              

During handling of the above exception, another exception occurred:                                                     

Traceback (most recent call last):                                                                                      
  File "/usr/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations          
    resps = self.auth.perform(achalls)                                                                                  
  File "/usr/lib/python3.8/site-packages/certbot/plugins/dns_common.py", line 57, in perform                            
    self._perform(domain, validation_domain_name, validation)                                                           
  File "/usr/lib/python3.8/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py", line 76, in _perform            
    self._get_rfc2136_client().add_txt_record(validation_name, validation, self.ttl)                                    
  File "/usr/lib/python3.8/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py", line 112, in add_txt_record     
    domain = self._find_domain(record_name)                                                                             
  File "/usr/lib/python3.8/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py", line 186, in _find_domain       
    if self._query_soa(guess):                                                                                          
  File "/usr/lib/python3.8/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py", line 225, in _query_soa         
    raise errors.PluginError('Encountered error when making query: {0}'                                                 
certbot.errors.PluginError: Encountered error when making query:                                                        

During handling of the above exception, another exception occurred:                                                     

Traceback (most recent call last):                                                                                      
  File "/usr/lib/python3.8/site-packages/dns/inet.py", line 87, in af_for_address                                       
    dns.ipv4.inet_aton(text)                                                                                            
  File "/usr/lib/python3.8/site-packages/dns/ipv4.py", line 49, in inet_aton                                            
    raise dns.exception.SyntaxError                                                                                     
dns.exception.SyntaxError: Text input is malformed.                                                                     

During handling of the above exception, another exception occurred:                                                     

Traceback (most recent call last):                                                                                      
  File "/usr/lib/python3.8/site-packages/dns/inet.py", line 91, in af_for_address                                       
    dns.ipv6.inet_aton(text, True)                                                                                      
  File "/usr/lib/python3.8/site-packages/dns/ipv6.py", line 165, in inet_aton                                           
    raise dns.exception.SyntaxError                                                                                     
dns.exception.SyntaxError: Text input is malformed.                                                                     

During handling of the above exception, another exception occurred:                                                     

Traceback (most recent call last):                                                                                      
  File "/usr/lib/python3.8/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py", line 210, in _query_soa         
    response = dns.query.tcp(request, self.server, port=self.port)                                                      
  File "/usr/lib/python3.8/site-packages/dns/query.py", line 752, in tcp                                                
    (af, destination, source) = _destination_and_source(where, port,                                                    
  File "/usr/lib/python3.8/site-packages/dns/query.py", line 226, in _destination_and_source                            
    af = dns.inet.af_for_address(where)                                                                                 
  File "/usr/lib/python3.8/site-packages/dns/inet.py", line 94, in af_for_address                                       
    raise ValueError                                                                                                    
ValueError                                                                                                              

During handling of the above exception, another exception occurred:                                                     

Traceback (most recent call last):                                                                                      
  File "/usr/lib/python3.8/site-packages/certbot/_internal/error_handler.py", line 125, in _call_registered             
    self.funcs[-1]()                                                                                                    
  File "/usr/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 243, in _cleanup_challenges           
    self.auth.cleanup(achalls)                                                                                          
  File "/usr/lib/python3.8/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup                            
    self._cleanup(domain, validation_domain_name, validation)                                                           
  File "/usr/lib/python3.8/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py", line 79, in _cleanup            
    self._get_rfc2136_client().del_txt_record(validation_name, validation)                                              
  File "/usr/lib/python3.8/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py", line 147, in del_txt_record     
    domain = self._find_domain(record_name)                                                                             
  File "/usr/lib/python3.8/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py", line 186, in _find_domain       
    if self._query_soa(guess):                                                                                          
  File "/usr/lib/python3.8/site-packages/certbot_dns_rfc2136/_internal/dns_rfc2136.py", line 225, in _query_soa         
    raise errors.PluginError('Encountered error when making query: {0}'                                                 
certbot.errors.PluginError: Encountered error when making query:                                                        
Attempting to renew cert (domain.example.org) from /etc/letsencrypt/renewal/domain.example.org.conf produced an unexpected error: Encountered error when making query: . Skipping.       
```

**Comment by sabueso** [comment]
I've experienced the same error and I've solved this changing the canonical hostname to an IP address: I know that this would not fit for all situations, but maybe could be useful for someone as "fast-workaround".

**Comment by psuter80** [comment]
as long as this is not fixed, I suggest this should be documented. for example here: https://certbot-dns-rfc2136.readthedocs.io/en/stable/#credentials

the comment above the dns_rfc2136_server line could be expanded a bit like so: 
``` 
# Target DNS server IP address

**Comment by brianjmurrell** [comment]
The [PR](https://github.com/certbot/certbot/pull/5664) for this issue is still open so the issue should stay open.

**Comment by Hawk777** [comment]
No, hostnames still aren’t accepted.

**Comment by cxxcoder** [comment]
I've created a new PR #10072 for that.

**Comment by Blackclaws** [comment]
So I just ran into this, could any of the open PRs move forward?

**Comment by zoracon** [comment]
Right now we are prioritizing work around [rethinking our DNS plugins](https://github.com/certbot/certbot/issues/10333). I know this has been hanging, but depending on our near future conclusions we will come back to this queue.
