### ISSUE TITLE
Remove --update-symlinks flag

### ISSUE THREAD

**Issue by t1b00** [certbot/certbot#6284]
## My operating system is (include version):
Ubuntu 16.04 Xenial

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS Package Manager

## I ran this command and it produced this output:
I ran certbot update_symlinks and I'm getting "Excepted (path to my cert.pem) to be a symlink".

## Certbot's behavior differed from what I expected because:
I wanted to fix my symlinks which were erased after transferring all my LE data, so I ran certbot update_symlinks, figuring it would fix them, but I keep getting the error (on a far off certificate in the alphabetical order, like not on the first ones, yet they do not differ) that it excepted this certificate to have a symlink.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```

Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1000, in update_symlinks
    cert_manager.update_live_symlinks(config)
  File "/usr/lib/python3/dist-packages/certbot/cert_manager.py", line 39, in update_live_symlinks
    storage.RenewableCert(renewal_file, config, update_symlinks=True)
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 438, in __init__
    self._update_symlinks()
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 508, in _update_symlinks
    previous_link = get_link_target(link)
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 211, in get_link_target
    "Expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: Expected [Path_To_My_Certificate] to be a symlink
2018-08-05 03:13:44,586:DEBUG:certbot.main:certbot version: 0.26.1
2018-08-05 03:13:44,587:DEBUG:certbot.main:Arguments: ['-v']
2018-08-05 03:13:44,587:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#dns-cloudflare,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-08-05 03:13:44,596:DEBUG:certbot.log:Root logging level set at 10
2018-08-05 03:13:44,596:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-08-05 03:13:44,598:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 208, in get_link_target
    target = os.readlink(link)
OSError: [Errno 22] Invalid argument: '[Path_To_My_Certificate]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1000, in update_symlinks
    cert_manager.update_live_symlinks(config)
  File "/usr/lib/python3/dist-packages/certbot/cert_manager.py", line 39, in update_live_symlinks
    storage.RenewableCert(renewal_file, config, update_symlinks=True)
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 438, in __init__
    self._update_symlinks()
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 508, in _update_symlinks
    previous_link = get_link_target(link)
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 211, in get_link_target
    "Expected {0} to be a symlink".format(link))
certbot.errors.CertStorageError: Expected [Path_To_My_Certificate] to be a symlink
```

**Comment by sydneyli** [comment]
How exactly did you "transfer all your LE data"? If you haven't already, try following [our documentation here](https://certbot.eff.org/docs/using.html#modifying-the-renewal-configuration-file) w.r.t. fixing symlinks after moving things around? That section might be helpful!

**Comment by RektibouCaribou** [comment]
Well I copied my Let's Encrypt folder from /etc/. But using .tar.gz kept the symlinks contrary to zip so my problem is fixed right now. But still isn't certbot fix_symlinks supposed to re-create the symlinks?

**Comment by sydneyli** [comment]
This is related to #4750-- although the PR that fixed it properly handles the error that resulted, we still don't attempt to create symlinks. There's been a lot of confusion w.r.t. the `update_symlinks` flag, and we should either update the documentation around it or deprecate it entirely.

@ohemorange, do you have any more thoughts on this?

**Comment by ohemorange** [comment]
`update_symlinks` was a mistake and should be removed.

**Comment by bmw** [comment]
Erica said she's not planning on implementing this issue, but wanted to make herself responsible for tracking it to make sure it gets done. If someone else wants to work on this, please do so!

**Comment by bmw** [comment]
Work was done on implementing this feature in the [remove_updates_symlinks branch](https://github.com/certbot/certbot/tree/remove_update_symlinks).
