### ISSUE TITLE
broken after debian dist-upgrade

### ISSUE THREAD

**Issue by teo1978** [certbot/certbot#6285]
I had installed certbot strictly following the instructions on Debian 7 and I had succesfully created and installed certificates. `certbot-auto renew` was running periodically as a cron without errors (though I think none of the certificates has ever expired yet). I also had run certbot-auto a few more times to expand existing certificates to include new domains, always succesfully.

Now I ran `apt-get dist-upgrade` and succesfully upgraded Debian to 8.11.

Now certbot is broken.

```
# /root/certbot/certbot-auto renew
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt: 
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 10, in <module>
    import josepy as jose
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/josepy/__init__.py", line 44, in <module>
    from josepy.interfaces import JSONDeSerializable
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/josepy/interfaces.py", line 8, in <module>
    from josepy import errors, util
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/josepy/util.py", line 4, in <module>
    import OpenSSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 157, in <module>
    Binding.init_static_locks()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 141, in init_static_locks
    __import__("_ssl")
ImportError: No module named _ssl
```

I would have expected it to keep working out of the box; as a second-best scenario, I would have expected some warnings during the dist-upgrade process telling me exactly what I needed to do to keep certbot working.

**Comment by teo1978** [comment]
Ok I see, I forgot, the old version on debian 7 was installed without the package manager, so it couldn't possibly trigger any warning or upgrade.

**Comment by teo1978** [comment]
https://github.com/certbot/certbot/issues/6286#issuecomment-411557931

I seem to understand certbot-auto is supposed to keep itself up to date. So I think this actually _is_ an issue.

**Comment by sydneyli** [comment]
After upgrading, you'll probably need to re-build the `virtualenv` that `certbot-auto` uses. Remove `/opt/eff.org/certbot/venv/` and try running `certbot-auto` again?

**Comment by sydneyli** [comment]
Going to close as this is probably not directly a certbot issue, and I suspect rebuilding `venv` will fix it. @teo1978, if this issue persists, or if you have a similar issue in the future, you may find it fruitful to post on the [community forums](https://community.letsencrypt.org/c/help), where there's a large audience also familiar with the project and can answer your questions faster!
