### ISSUE TITLE
ContextualVersionConflict with idna 2.7

### ISSUE THREAD

**Issue by staktrace** [certbot/certbot#6300]
## My operating system is (include version):
FreeBSD 11.1-stable

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

OS package manager (`pkg install py36-certbot`)

## I ran this command and it produced this output:

```
certbot-3.6 --help
```
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.7 (/usr/local/lib/python3.6/site-packages), Requirement.parse('idna<2.7,>=2.5'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/certbot-3.6", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.7 (/usr/local/lib/python3.6/site-packages), Requirement.parse('idna<2.7,>=2.5'), {'requests'})
```

## Certbot's behavior differed from what I expected because:

It shouldn't produce an error about `idna` version requirement failure. Note that I previously had `py36-idna-2.6` installed and it worked fine. A few days ago there was a security vulnerability in `py36-cryptography` and upgrading that also bumped the `py36-idna` package to 2.7, and it seems that `certbot` is not happy with this.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Nothing in log from this invocation.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

Not relevant here

**Comment by staktrace** [comment]
To be clear, `py36-certbot` has a dependency on `py36-cryptography` and accepts any version >= 1.2 (see [port Makefile](https://svnweb.freebsd.org/ports/head/security/py-certbot/Makefile?view=markup#l20)). But `py36-cryptography-2.3` now depends on `py36-idna-2.7` and `certbot` doesn't like that.

**Comment by staktrace** [comment]
Never mind, this is not specific to certbot. The dependency restriction was coming from `py36-requests` and upgrading that fixed my issue. Sorry for the noise!
