### ISSUE TITLE
Run failing after upgrading to Ubuntu 18.04

### ISSUE THREAD

**Issue by marv3lls** [certbot/certbot#6333]
## My operating system is (include version):
Ubuntu 18.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
```
cd ~/bin
wget https://dl.eff.org/certbot-auto
chmod +x certbot-auto
```

## I ran this command and it produced this output:
```
22:22:50 root@marvell.cat bin certbot-auto renew
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 5, in <module>
    import logging.handlers
  File "/usr/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/usr/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

## Certbot's behavior differed from what I expected because:
It didn't renew the nine certs I have on here.

## Here is a Certbot log showing the issue (if available):
Nothing new on this run.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not relevant. I ran them all `certonly` initially.

**Comment by sydneyli** [comment]
Hi @marv3lls! Thanks for reporting. After a dist upgrade, existing `virtualenv` environments tend to break. Remove the `/opt/eff.org/certbot/venv` folder, and try running `certbot-auto` again? This should re-build the venv.
