### ISSUE TITLE
KeyError handle_modules with 0.27.0 on openSUSE

### ISSUE THREAD

**Issue by ArloL** [certbot/certbot#6344]
## My operating system is (include version):

openSUSE Leap 42.1

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

## I ran this command and it produced this output:

````
kevdev36:~ # certbot-auto --version
Upgrading certbot-auto 0.26.1 to 0.27.0...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
An unexpected error occurred:
KeyError: 'handle_modules'
Please see the logfile '/tmp/tmpMAZJox' for more details.
````

## Certbot's behavior differed from what I expected because:

It did not print the version.

## Here is a Certbot log showing the issue (if available):

/tmp/tmpMAZJox

````
2018-09-06 09:59:58,652:DEBUG:certbot.main:certbot version: 0.27.0
2018-09-06 09:59:58,652:DEBUG:certbot.main:Arguments: ['--version']
2018-09-06 09:59:58,653:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-09-06 09:59:58,660:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 1345, in main
    args = cli.prepare_and_parse_args(plugins, cli_args)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/cli.py", line 1243, in prepare_and_parse_args
    _plugins_parsing(helpful, plugins)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/cli.py", line 1458, in _plugins_parsing
    helpful.add_plugin_args(plugins)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/cli.py", line 840, in add_plugin_args
    plugin_ep.plugin_cls.inject_parser_options(parser_or_group, name)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/plugins/common.py", line 81, in inject_parser_options
    return cls.add_parser_arguments(add)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/configurator.py", line 159, in add_parser_arguments
    add("handle-modules", default=cls.OS_DEFAULTS["handle_modules"],
KeyError: 'handle_modules'
2018-09-06 09:59:58,660:ERROR:certbot.log:An unexpected error occurred:
````

## Workaround

Downgrade to 0.26.1 and use `certbot-auto` with `--no-self-upgrade`.

````
kevdev36:~ # wget https://raw.githubusercontent.com/certbot/certbot/v0.26.1/certbot-auto
kevdev36:~ # chmod +x certbot-auto
kevdev36:~ # /opt/eff.org/certbot/venv/bin/pip install certbot==0.26.1 certbot-apache==0.26.1 certbot-nginx==0.26.1
kevdev36:~ # ./certbot-auto --no-self-upgrade --version
certbot 0.26.1
````

**Comment by mnordhoff** [comment]
[DLoader on the forum seems to have found the issue](https://community.letsencrypt.org/t/error-during-renewal-keyerror-handle-modules/71500/4?u=mnordhoff):

> If you look at the “override_suse.py” file in the directory
>
> “/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot_apache/"
>
> you will see that someone recently modified it to create the “handle_mods” element instead of the “handle_modules” element in the OS_DEFAULTS array.
>
> If you look in the other “override_” files, you will see that they all use the “handle_modules” element name.
>
> I changed “handle_mods=False” to “handle_modules=False” and it now works fine.

#6238 renamed `handle_mods` to `handle_modules` but missed one reference in `override_suse`.

https://github.com/certbot/certbot/blob/d39a354a659cbc3ee7ff177ea6bd42724b16c71e/certbot-apache/certbot_apache/override_suse.py#L26

**Comment by sydneyli** [comment]
Thank you to everyone who reported and those of you on the forum for investigating! I've put out a simple PR for this at #6347.
