### ISSUE TITLE
[Feature request] nginx plugin doesn't auto detect wildcard domains

### ISSUE THREAD

**Issue by ciarancourtney** [certbot/certbot#6384]
## My operating system is (include version):
Ubuntu 18.04.1

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

apt initially, then pip installed all certbot packages to see if issue was resolved

## I ran this command and it produced this output:

    sudo certbot --authenticator=dns-route53 --installer=nginx

    No names were found in your configuration files. Please enter in your domain

## Certbot's behavior differed from what I expected because:

I have a single _index_ nginx conf containing a wildcard `server_name` which routes to all other 'location' confs based on path

Why can't the nginx plugin just detect that its a wildcard cert?

```
server {
    listen 80;
    server_name .example.com;

    root /var/www;
    index index.html;

    include conf.d/*.location;
}
```

**Comment by ciarancourtney** [comment]
Yes thats what appears in log.

FYI The log dir `/var/log/letsencrypt/` is not 'tab-able' by non-root users, which may trip up some people.

<details>
<summary>/var/log/letsencrypt/letsencrypt.log</summary>

2018-09-19 09:58:49,450:DEBUG:certbot.util:Not suggesting name "_"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 310, in get_filtered_names
    filtered_names.add(enforce_le_validity(name))
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 526, in enforce_le_validity
    "Valid characters are A-Z, a-z, 0-9, ., and -.".format(domain))
certbot.errors.ConfigurationError: _ contains an invalid character. Valid characters are A-Z, a-z, 0-9, ., and -.
2018-09-19 09:58:49,452:DEBUG:certbot.util:Not suggesting name ".example.com"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 310, in get_filtered_names
    filtered_names.add(enforce_le_validity(name))
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 522, in enforce_le_validity
    domain = enforce_domain_sanity(domain)
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 601, in enforce_domain_sanity
    raise errors.ConfigurationError("{0} it contains an empty label.".format(msg))
certbot.errors.ConfigurationError: Requested domain .example.com is not a FQDN because it contains an empty label.

</details>

**Comment by ohemorange** [comment]
For users:

Use `-d example.com -d *.example.com` to specify the domains.

For devs:

Ok so what's going on here is that we have a check that does `domain.split('.')`, and makes sure that none of the entries in the list are empty. Nginx special-cases `.example.com` as meaning both `example.com` and `*.example.com` in one. Previously, we didn't support wildcards at all, so it made sense not to show this.

This check happens in `certbot/util.py`, so it's consistent between Nginx and Apache.

The best fix on our end is probably to expand the domain into being read as both domains inside the Nginx plugin, before it goes through the check.

We may also need to do the same thing in Apache.

But then, we have the UX conundrum that this will also work when Nginx is set as authenticator, erroneously displaying wildcard domains when we can't actually get them.

**Comment by ohemorange** [comment]
> But then, we have the UX conundrum that this will also work when Nginx is set as authenticator, erroneously displaying wildcard domains when we can't actually get them.

On second thought, this is probably fine, because then the user can run again and select a different domain or use a different authenticator. We should make sure that the error message that happens when you do that is good.

**Comment by ohemorange** [comment]
@ciarancourtney, any chance you'd be up for submitting a PR to fix this?

**Comment by ciarancourtney** [comment]
> @ciarancourtney, any chance you'd be up for submitting a PR to fix this?

Sure, I'll take a look

**Comment by ohemorange** [comment]
Awesome, let me know if you have any questions or run into any snags.

**Comment by bmw** [comment]
Do we think this issue will be resolved for the release next week?

**Comment by ohemorange** [comment]
Hi @ciarancourtney! Going through older issues, and I see you wrote a commit to address this but never opened a PR -- are you still interested in doing so? Wouldn't want to erase your contributions but the commit is probably out of date at this point.

**Comment by ciarancourtney** [comment]
Hi sorry for late reply, honestly I haven't been (at least knowingly) using certbot since so I'm sure the code will have changed a lot or the use case may not be relevant anymore, you have my blessing to reuse/erase my changes how you wish.

**Comment by zoracon** [comment]
For now we decided to leave this unplanned and close. But if there's more interest or concerns from more users we can certainly reconsider reopening this issue. If there's renewed interest from more users we can reconsider & reopen.
