### ISSUE TITLE
Certbot broke after auto-updating to 0.27.1

### ISSUE THREAD

**Issue by andrew-koster-** [certbot/certbot#6446]
## My operating system is (include version):

Amazon Linux with all updates installed.

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Certbot-auto.

## I ran this command and it produced this output:

[x@ip-XXX-XX-XX-XXX ~]$ ./certbot-auto 
Requesting to rerun ./certbot-auto with root privileges...
Upgrading certbot-auto 0.26.1 to 0.27.1...
Replacing certbot-auto...
Creating virtual environment...
Installing Python packages...
Installation succeeded.
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 10, in <module>
    import josepy as jose
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/__init__.py", line 44, in <module>
    from josepy.interfaces import JSONDeSerializable
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/interfaces.py", line 8, in <module>
    from josepy import errors, util
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/util.py", line 4, in <module>
    import OpenSSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
ImportError: No module named cryptography.hazmat.bindings.openssl.binding

## Certbot's behavior differed from what I expected because:

It worked when I installed it, and it automatically broke itself.

## Here is a Certbot log showing the issue (if available):

There are no recent logs in /var/log/letsencrypt , the only files with any content contain error messages from over a month ago, when I was first setting it up.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

I don't know which configuration file we're talking about here.

**Comment by bmw** [comment]
Unfortunately, this is a known issue and certbot-auto's support for Amazon Linux is experimental as shown by the need to pass in `--debug` during the initial installation.

The issue for this is https://github.com/certbot/certbot/issues/2544 where some people have found workarounds though.
