### ISSUE TITLE
apache plugin fails to work

### ISSUE THREAD

**Issue by fezie** [certbot/certbot#6471]
## My operating system is (include version):

Debian GNU/Linux 9.5 (stretch)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

From github repository.
git revision 2c1964c639916bcedc4d10d073cbcca212e7b8f1

## I ran this command and it produced this output:

# ./certbot-auto --apache -d z-51.de
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError('Problem in Augeas installation',)

## Certbot's behavior differed from what I expected because:

A much earlier revision worked. But I can't remember which one.

## Here is a Certbot log showing the issue (if available):

2018-11-04 16:46:28,528:DEBUG:certbot.main:certbot version: 0.27.1
2018-11-04 16:46:28,528:DEBUG:certbot.main:Arguments: ['--apache', '-d', 'z-51.de']
2018-11-04 16:46:28,528:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-11-04 16:46:28,544:DEBUG:certbot.log:Root logging level set at 20
2018-11-04 16:46:28,545:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-11-04 16:46:28,546:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2018-11-04 16:46:28,566:DEBUG:certbot.plugins.disco:No installation (PluginEntryPoint#apache): Problem in Augeas installation
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 132, in prepare
    self._initialized.prepare()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 227, in prepare
    raise errors.NoInstallationError("Problem in Augeas installation")
NoInstallationError: Problem in Augeas installation
2018-11-04 16:46:28,567:DEBUG:certbot.plugins.selection:No candidate plugin
2018-11-04 16:46:28,567:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

<VirtualHost *:80>
        ServerName z-51.de
        DocumentRoot /var/www/html
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

**Comment by fezie** [comment]
Ok forget it. Now after installing python3-augeas it works again
