### ISSUE TITLE
Renew hangs with exit code 1 when CA servers not reachable.

### ISSUE THREAD

**Issue by vbrinza** [certbot/certbot#6478]
## My operating system is (include version):

Centos 7

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

pip

## I ran this command and it produced this output:

certbot renew --pre-hook "systemctl stop nginx" --post-hook "systemctl start nginx"

## Certbot's behavior differed from what I expected because:

I would expect the renew script to exit with 0 when it can't connect to your server.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2018-10-30 23:00:02,608:INFO:certbot.hooks:Running pre-hook command: systemctl stop nginx
2018-10-30 23:00:02,640:INFO:certbot.main:Renewing an existing certificate
2018-10-30 23:00:02,641:DEBUG:acme.client:Requesting fresh nonce
2018-10-30 23:00:02,641:DEBUG:acme.client:Sending HEAD request to https://acme-v01.api.letsencrypt.org/acme/new-authz.
2018-10-30 23:00:02,813:DEBUG:requests.packages.urllib3.connectionpool:"HEAD /acme/new-authz HTTP/1.1" 405 0
2018-10-30 23:00:02,814:DEBUG:acme.client:Received response:
HTTP 405
content-length: 91
pragma: no-cache
expires: Tue, 30 Oct 2018 23:00:02 GMT
server: nginx
connection: keep-alive
allow: POST
cache-control: max-age=0, no-cache, no-store
date: Tue, 30 Oct 2018 23:00:02 GMT
content-type: application/problem+json
replay-nonce: r47g33joLOb8WGzvrCnco35al2zsI9I8IAPBAMQOxVs

2018-10-30 23:00:02,815:DEBUG:acme.client:Storing nonce: r47g33joLOb8WGzvrCnco35al2zsI9I8IAPBAMQOxVs
2018-10-30 23:00:02,815:DEBUG:acme.client:JWS payload:
{
  "identifier": {
    "type": "dns",
    "value": "storage6.domain.org"
  },
  "resource": "new-authz"
}
2018-10-30 23:00:02,823:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/new-authz:
{
  "header": {
    "alg": "RS256",
    "jwk": {
      "e": "AQAB",
      "kty": "RSA",
      "n": "3XGIfmNF9yWscuA49BhHKFiY7f5S6t0qeMvrqUZLFBi-L0f5Xu4SPC9MHOGO47jO1EOuTypddRmiZET4iPSTD8oqNLZn8uk-hgX6wG8vDExNbk-IRN8W5qzPxsBPFSBlfEmdbGVhEM15y5YjCFimbbQakyeFSS_bJY9CUkFVDw30DNVsdBSQas9VYa3KLVEYdbRdGgpnn8jzKtx8viDl9UTjXcZ93gITAwC6cu7WRFIefcttUw_fbo2tRHQbvT_Vg-pC01nqm7ssNGSlybjBBGmdh7G5RV2Q_SfFw-xJbtpsk4Krn7_VKPKAXAEU0xs2sjgzl37mE7A94OGGQDSvTw"
    }
  },
  "protected": "eyJub25jZSI6ICJyNDdnMzNqb0xPYjhXR3p2ckNuY28zNWFsMnpzSTlJOElBUEJBTVFPeFZzIn0",
  "payload": "ewogICJpZGVudGlmaWVyIjogewogICAgInR5cGUiOiAiZG5zIiwgCiAgICAidmFsdWUiOiAic3RvcmFnZTYub3BlbnN0cmVldGNhbS5vcmciCiAgfSwgCiAgInJlc291cmNlIjogIm5ldy1hdXRoeiIKfQ",
  "signature": "rKH6ug_-hmID66qNuEs2BrVNW_e1Zx5mbCkQftY_dgGWPADrTjbMogO0UzqY9CGtj6ofazcCarcJZ6hQIrOSbVMyq_lRGyoe_357jYUlQSt74AP2F-3khoS313rAtUmPDEc3rP3cjCluklPnM4sgPCTwjt1FcUpTFoj2vqHxfvGbzDOWlG3ZPsgjMolOLIdoVv9pAuPQMoe_Tf0bJEhmWlicsG9G5RSuzx06pH9uI6hGkgCQHjwhT30QHrzUIWJgj1lroBZ38q-rv_cRDBeycEr4WMu_M6Hx4fzRDGi5hVlW6nujSvvvu01Egy02xJEGJMwPKuvyu2-n7m8i9r47gw"
}
2018-10-30 23:00:03,285:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/new-authz HTTP/1.1" 201 1278
2018-10-30 23:00:03,286:DEBUG:acme.client:Received response:
HTTP 201
content-length: 1278
expires: Tue, 30 Oct 2018 23:00:03 GMT
cache-control: max-age=0, no-cache, no-store
strict-transport-security: max-age=604800
server: nginx
connection: keep-alive
link: <https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"
location: https://acme-v01.api.letsencrypt.org/acme/authz/7bTXcgeXtIDezNEpAYA2d754-CBlgBZbN0kAwUh7yM8
pragma: no-cache
boulder-requester: 20832837
date: Tue, 30 Oct 2018 23:00:03 GMT
x-frame-options: DENY
content-type: application/json
replay-nonce: WIGMfhzOea2MyVGo4lviKPquF0fiIQUmUUlDG_G503k

{
  "identifier": {
    "type": "dns",
    "value": "storage6.domain.org"
  },
  "status": "pending",
  "expires": "2018-11-06T23:00:03Z",
  "challenges": [
    {
      "type": "tls-sni-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/7bTXcgeXtIDezNEpAYA2d754-CBlgBZbN0kAwUh7yM8/8794162107",
      "token": "iLi9Vfmnk7yQYuV-UXXW7amGPT7QPdIt183WMT9QVgI"
    },
    {
      "type": "http-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/7bTXcgeXtIDezNEpAYA2d754-CBlgBZbN0kAwUh7yM8/8794162113",
      "token": "Lr_MEGSn_V8ygylm5qvxSI-2HdGrtFRzohn5kK_T1Zk"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/7bTXcgeXtIDezNEpAYA2d754-CBlgBZbN0kAwUh7yM8/8794162130",
      "token": "9vQv7zjyNeOnxzIiiWPTkC5CYrDMT373PHBSQh_5IPY"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "uri": "https://acme-v01.api.letsencrypt.org/acme/challenge/7bTXcgeXtIDezNEpAYA2d754-CBlgBZbN0kAwUh7yM8/8794162132",
      "token": "1nMjEMWyzvmrnKG2lEqmzLdEoP3Af_Ue1oPXE1fTR4E"
    }
  ],
  "combinations": [
    [
      1
    ],
    [
      0
    ],
    [
      2
    ],
    [
      3
    ]
  ]
}
2018-10-30 23:00:03,286:DEBUG:acme.client:Storing nonce: WIGMfhzOea2MyVGo4lviKPquF0fiIQUmUUlDG_G503k
2018-10-30 23:00:03,287:DEBUG:acme.challenges:tls-alpn-01 was not recognized, full message: {u'status': u'pending', u'token': u'1nMjEMWyzvmrnKG2lEqmzLdEoP3Af_Ue1oPXE1fTR4E', u'type': u'tls-alpn-01', u'uri': u'https://acme-v01.api.letsencrypt.org/acme/challenge/7bTXcgeXtIDezNEpAYA2d754-CBlgBZbN0kAwUh7yM8/8794162132'}
2018-10-30 23:00:03,288:INFO:certbot.auth_handler:Performing the following challenges:
2018-10-30 23:00:03,288:INFO:certbot.auth_handler:tls-sni-01 challenge for storage6.domain.org
2018-10-30 23:00:03,303:INFO:certbot.auth_handler:Waiting for verification...
2018-10-30 23:00:03,303:DEBUG:acme.client:JWS payload:
{
  "keyAuthorization": "iLi9Vfmnk7yQYuV-UXXW7amGPT7QPdIt183WMT9QVgI.Pk8VcIsEGnvR4kRP6Q9Ok2WpH4pfN62LFl5MYYvWaBg",
  "type": "tls-sni-01",
  "resource": "challenge"
}
2018-10-30 23:00:03,309:DEBUG:acme.client:Sending POST request to https://acme-v01.api.letsencrypt.org/acme/challenge/7bTXcgeXtIDezNEpAYA2d754-CBlgBZbN0kAwUh7yM8/8794162107:
{
  "header": {
    "alg": "RS256",
    "jwk": {
      "e": "AQAB",
      "kty": "RSA",
      "n": "3XGIfmNF9yWscuA49BhHKFiY7f5S6t0qeMvrqUZLFBi-L0f5Xu4SPC9MHOGO47jO1EOuTypddRmiZET4iPSTD8oqNLZn8uk-hgX6wG8vDExNbk-IRN8W5qzPxsBPFSBlfEmdbGVhEM15y5YjCFimbbQakyeFSS_bJY9CUkFVDw30DNVsdBSQas9VYa3KLVEYdbRdGgpnn8jzKtx8viDl9UTjXcZ93gITAwC6cu7WRFIefcttUw_fbo2tRHQbvT_Vg-pC01nqm7ssNGSlybjBBGmdh7G5RV2Q_SfFw-xJbtpsk4Krn7_VKPKAXAEU0xs2sjgzl37mE7A94OGGQDSvTw"
    }
  },
  "protected": "eyJub25jZSI6ICJXSUdNZmh6T2VhMk15VkdvNGx2aUtQcXVGMGZpSVFVbVVVbERHX0c1MDNrIn0",
  "payload": "ewogICJrZXlBdXRob3JpemF0aW9uIjogImlMaTlWZm1uazd5UVl1Vi1VWFhXN2FtR1BUN1FQZEl0MTgzV01UOVFWZ0kuUGs4VmNJc0VHbnZSNGtSUDZROU9rMldwSDRwZk42MkxGbDVNWVl2V2FCZyIsIAogICJ0eXBlIjogInRscy1zbmktMDEiLCAKICAicmVzb3VyY2UiOiAiY2hhbGxlbmdlIgp9",
  "signature": "BXn0Io0KKIsREjd9N-0p9qWDQhO9_9dFz6-PslzuOwfAoLuKnEOS-BZDGmpSFd7eWdYqURvhfJLB-SQpFoBWg_WvVhuJfvwssNH1OUXYBkIXm46SRmms9O4pwxtqr-Dx5dk6LtOIM6346cz5VQlS276bmXFiG51IRYbBXbSgzkdHqhY2ttzoG5T0r5eatgWg7yLm5IpDUVAX0Shm0J2EQUeC-Rwm9XXkNZ7TEGp-3a-ZU3gS_jtTWqoimgy3w_otCxgR7I0xz55Rqa8g24ABK76BbACRO4S4LoP9kqKT_xS0T52ywHS59L3qpklHbKpnAIpVeTirBiCCn8-aE2XRtA"
}
2018-10-30 23:00:08,483:DEBUG:requests.packages.urllib3.connectionpool:"POST /acme/challenge/7bTXcgeXtIDezNEpAYA2d754-CBlgBZbN0kAwUh7yM8/8794162107 HTTP/1.1" 500 107
2018-10-30 23:00:08,487:DEBUG:acme.client:Received response:
HTTP 500
content-length: 107
expires: Tue, 30 Oct 2018 23:00:08 GMT
server: nginx
connection: close
pragma: no-cache
cache-control: max-age=0, no-cache, no-store
date: Tue, 30 Oct 2018 23:00:08 GMT
content-type: application/problem+json
replay-nonce: JxProPRj7wf9VrAwvEmVd2UTB36Ovdu0usSyQ3NzuQ8

{
  "type": "urn:acme:error:serverInternal",
  "detail": "Problem getting authorization",
  "status": 500
}
2018-10-30 23:00:08,488:DEBUG:acme.client:Storing nonce: JxProPRj7wf9VrAwvEmVd2UTB36Ovdu0usSyQ3NzuQ8
2018-10-30 23:00:08,488:WARNING:certbot.renewal:Attempting to renew cert from /etc/letsencrypt/renewal/storage6.domain.org.conf produced an unexpected error: urn:acme:error:serverInternal :: The server experienced an internal error :: Problem getting authorization. Skipping.
2018-10-30 23:00:08,508:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/renewal.py", line 418, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 640, in renew_cert
    _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 77, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/renewal.py", line 296, in renew_cert
    new_certr, new_chain, new_key, _ = le_client.obtain_certificate(domains)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 313, in obtain_certificate
    self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 81, in get_authorizations
    self._respond(resp, best_effort)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 134, in _respond
    resp, chall_update)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 158, in _send_responses
    self.acme.answer_challenge(achall.challb, resp)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 229, in answer_challenge
    response = self.net.post(challb.uri, response)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 674, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 687, in _post_once
    return self._check_response(response, content_type=content_type)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 574, in _check_response
    raise messages.Error.from_json(jobj)
Error: urn:acme:error:serverInternal :: The server experienced an internal error :: Problem getting authorization

2018-10-30 23:00:08,508:INFO:certbot.hooks:Running post-hook command: systemctl start nginx
2018-10-30 23:00:11,134:ERROR:certbot.hooks:Hook command "systemctl start nginx" returned error code 1
2018-10-30 23:00:11,134:ERROR:certbot.hooks:Error output from systemctl:
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

2018-10-30 23:00:11,134:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.14.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 742, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 692, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python2.7/site-packages/certbot/renewal.py", line 435, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)
2018-10-30 23:36:56,369:DEBUG:acme.crypto_util:Performing handshake with ('2.28.137.222', 49925)
2018-10-30 23:36:56,369:DEBUG:acme.crypto_util:Server name (storage6.domain.org) not recognized, dropping SSL
2018-10-30 23:36:56,428:DEBUG:acme.crypto_util:Performing handshake with ('2.28.137.222', 49926)
2018-10-30 23:36:56,428:DEBUG:acme.crypto_util:Server name (storage6.domain.org) not recognized, dropping SSL
2018-10-30 23:56:06,173:DEBUG:acme.crypto_util:Performing handshake with ('213.186.170.226', 52348)
2018-10-30 23:56:06,315:DEBUG:acme.crypto_util:Performing handshake with ('213.186.170.226', 60387)
2018-10-31 01:42:19,708:DEBUG:acme.crypto_util:Performing handshake with ('98.113.125.29', 51198)
2018-10-31 01:42:19,708:DEBUG:acme.crypto_util:Server name (storage6.domain.org) not recognized, dropping SSL
2018-10-31 01:42:19,914:DEBUG:acme.crypto_util:Performing handshake with ('98.113.125.29', 51200)
2018-10-31 01:42:20,027:DEBUG:acme.crypto_util:Server name (storage6.domain.org) not recognized, dropping SSL
2018-10-31 01:42:20,244:DEBUG:acme.crypto_util:Performing handshake with ('98.113.125.29', 51202)
2018-10-31 01:42:20,480:DEBUG:acme.crypto_util:Performing handshake with ('98.113.125.29', 51204)
2018-10-31 01:42:20,480:DEBUG:acme.crypto_util:Server name (storage6.domain.org) not recognized, dropping SSL
2018-10-31 01:42:21,705:DEBUG:acme.crypto_util:Performing handshake with ('98.113.125.29', 51206)
2018-10-31 01:42:21,705:DEBUG:acme.crypto_util:Server name (storage6.domain.org) not recognized, dropping SSL
2018-10-31 01:42:21,937:DEBUG:acme.crypto_util:Performing handshake with ('98.113.125.29', 51207)
2018-10-31 01:42:22,157:DEBUG:acme.crypto_util:Performing handshake with ('98.113.125.29', 51208)
2018-10-31 01:42:22,158:DEBUG:acme.crypto_util:Server name (storage6.domain.org) not recognized, dropping SSL
2018-10-31 01:42:22,367:DEBUG:acme.crypto_util:Performing handshake with ('98.113.125.29', 51209)
2018-10-31 01:42:22,367:DEBUG:acme.crypto_util:Server name (storage6.domain.org) not recognized, dropping SSL

**Comment by ohemorange** [comment]
Actually, it's not giving error code 0 from the server error, it's because certbot failed to restart nginx in the post-hook. Luckily, we have a better way of doing things these days! Check out https://certbot.eff.org/lets-encrypt/centosrhel7-nginx for more info.

**Comment by vbrinza** [comment]
@ohemorange thanks, it solves my issues. Also the cron suggestion is good considering issues with CA servers.
