### ISSUE TITLE
Renew fails since certbot 0.28.0 with apache and FastCgiExternalServer

### ISSUE THREAD

**Issue by keros** [certbot/certbot#6495]
## My operating system is (include version):
Ubuntu 16.04
Server version: Apache/2.4.18 (Ubuntu)
All certs use the certbot apache module

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto (because of an dependency issue)

## I ran this command and it produced this output:
letsencrypt --version
-> certbot 0.28.0
letsencrypt renew
```
...
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for www.mydomain.com
http-01 challenge for mydomain.com
Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 46 of /etc/apache2/sites-available/mydomain.com.conf:
FastCgiExternalServer: redefinition of previously defined class "/var/www/mydomain.com/cgi-bin/php-fpm-fcgi-mydomain.com"

Cleaning up challenges
Attempting to renew cert (mydomain.com) from /etc/letsencrypt/renewal/mydomain.com.conf produced an unexpected error: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 46 of /etc/apache2/sites-available/mydomain.com.conf:
FastCgiExternalServer: redefinition of previously defined class "/var/www/mydomain.com/cgi-bin/php-fpm-fcgi-mydomain.com"
. Skipping.
...
```

## Certbot's behavior differed from what I expected because:
There should not be an error like on the previous versions of certbot.

## Here is a Certbot log showing the issue (if available):
```
2018-11-12 09:34:42,791:DEBUG:certbot.main:certbot version: 0.28.0
2018-11-12 09:34:42,791:DEBUG:certbot.main:Arguments: ['--cert-name', 'mydomain.com']
2018-11-12 09:34:42,791:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-11-12 09:34:42,827:DEBUG:certbot.log:Root logging level set at 20
2018-11-12 09:34:42,828:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-11-12 09:34:42,861:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7fa2505f4510> and installer <certbot.cli._Default object at 0x7fa2505f4510>
2018-11-12 09:34:42,905:DEBUG:certbot.storage:Should renew, less than 30 days before certificate expiry 2018-12-11 03:38:05 UTC.
2018-11-12 09:34:42,905:INFO:certbot.renewal:Cert is due for renewal, auto-renewing...
2018-11-12 09:34:42,906:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2018-11-12 09:34:43,401:DEBUG:certbot_apache.configurator:Apache version is 2.4.18
2018-11-12 09:34:55,454:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT
Initialized: <certbot_apache.override_debian.DebianConfigurator object at 0x7fa25062d390>
Prep: True
2018-11-12 09:34:55,458:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT
Initialized: <certbot_apache.override_debian.DebianConfigurator object at 0x7fa25062d390>
Prep: True
2018-11-12 09:34:55,458:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.override_debian.DebianConfigurator object at 0x7fa25062d390> and installer <certbot_apache.override_debian.DebianConfigurator object at 0x7fa25062d390>
2018-11-12 09:34:55,458:INFO:certbot.plugins.selection:Plugins selected: Authenticator apache, Installer apache
2018-11-12 09:34:55,464:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(body=Registration(status=None, terms_of_service_agreed=None, agreement=u'https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf', only_return_existing=None, contact=(u'mailto:webmaster@x-net.at',), key=JWKRSA(key=<ComparableRSAKey(<cryptography.hazmat.backends.openssl.rsa._RSAPublicKey object at 0x7fa24d2c3610>)>)), uri=u'https://acme-v01.api.letsencrypt.org/acme/reg/1860575', new_authzr_uri=u'https://acme-v01.api.letsencrypt.org/acme/new-authz', terms_of_service=u'https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf'), b08a91702ce6faba002c0ea55e96f023, Meta(creation_host=u'myserver.internal.local', creation_dt=datetime.datetime(2016, 5, 24, 13, 15, 59, tzinfo=<UTC>)))>
2018-11-12 09:34:55,467:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2018-11-12 09:34:55,473:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
2018-11-12 09:34:55,732:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2018-11-12 09:34:55,735:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 658
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 12 Nov 2018 08:34:55 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 12 Nov 2018 08:34:55 GMT
Connection: keep-alive

{
  "2DfrFyrq7GA": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2018-11-12 09:34:55,736:INFO:certbot.main:Renewing an existing certificate
2018-11-12 09:34:55,943:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0443_key-certbot.pem
2018-11-12 09:34:55,949:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0443_csr-certbot.pem
2018-11-12 09:34:55,950:DEBUG:acme.client:Requesting fresh nonce
2018-11-12 09:34:55,950:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2018-11-12 09:34:56,159:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 204 0
2018-11-12 09:34:56,161:DEBUG:acme.client:Received response:
HTTP 204
Server: nginx
Replay-Nonce: iN-qTFMnukQ4l3Fl9A0QARnv8V5h4Hx6uXloO2kGucE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 12 Nov 2018 08:34:56 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 12 Nov 2018 08:34:56 GMT
Connection: keep-alive


2018-11-12 09:34:56,161:DEBUG:acme.client:Storing nonce: iN-qTFMnukQ4l3Fl9A0QARnv8V5h4Hx6uXloO2kGucE
2018-11-12 09:34:56,163:DEBUG:acme.client:JWS payload:
{
  "identifiers": [
    {
      "type": "dns", 
      "value": "mydomain.com"
    }, 
    {
      "type": "dns", 
      "value": "www.mydomain.com"
    }
  ]
}
2018-11-12 09:34:56,169:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJub25jZSI6ICJpTi1xVEZNbnVrUTRsM0ZsOUEwUUFSbnY4VjVoNEh4NnVYbG9PMmtHdWNFIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDEuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL3JlZy8xODYwNTc1IiwgImFsZyI6ICJSUzI1NiJ9", 
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwgCiAgICAgICJ2YWx1ZSI6ICJyZWNodHNhbndhbHQtc2Nob2VwcGwuYXQiCiAgICB9LCAKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwgCiAgICAgICJ2YWx1ZSI6ICJ3d3cucmVjaHRzYW53YWx0LXNjaG9lcHBsLmF0IgogICAgfQogIF0KfQ", 
  "signature": "RrUIVG9oBQgO7CZDixv5p0s15FQA4HB9ImigIMFNojV7tSUtcok15qRiV3OF0nhuyb0OGBYEO0yjWVHp3NRdxQhQnkIbCAVlBmf5TaYgDbXBWY05FLdeb2sb27kJuCqMozfY0SOpSGxwUNrcKt4pSBkPow4lhHwX4W-z6ZNuohFT0NZ6_iY_8oeixfqIbhDFavWvuGHuRmE9Yy2QFr5DxcIpmEy2YRn2fPvXZxL5u5A7UTEmaAtdaIoG22PYpls8HgxHjdtmjDCzoR4TMhdCA9i7gySvi-xSsTVH_D08xKPOGn-ScxhlnPvqgqXIzlgAhVCtmvX1qPujpp7m24kimQ"
}
2018-11-12 09:34:56,369:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 551
2018-11-12 09:34:56,370:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Content-Type: application/json
Content-Length: 551
Boulder-Requester: 1860575
Location: https://acme-v02.api.letsencrypt.org/acme/order/1860575/167778100
Replay-Nonce: zpedpb29h84M7hy1kiRLZM-SSJKE-_3x_4rYqDKXhBc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 12 Nov 2018 08:34:56 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 12 Nov 2018 08:34:56 GMT
Connection: keep-alive

{
  "status": "pending",
  "expires": "2018-11-18T05:41:59Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "mydomain.com"
    },
    {
      "type": "dns",
      "value": "www.mydomain.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/qUhjUoBCfvXIc4Z67nJtdjUiuRC8VORUA8Gx0mm68sw",
    "https://acme-v02.api.letsencrypt.org/acme/authz/XOfKMMMjMlD1Ki5L0BxiKAY3FTWPeamFI7kWS033Vls"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/1860575/167778100"
}
2018-11-12 09:34:56,371:DEBUG:acme.client:Storing nonce: zpedpb29h84M7hy1kiRLZM-SSJKE-_3x_4rYqDKXhBc
2018-11-12 09:34:56,372:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/acme/authz/qUhjUoBCfvXIc4Z67nJtdjUiuRC8VORUA8Gx0mm68sw.
2018-11-12 09:34:56,571:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /acme/authz/qUhjUoBCfvXIc4Z67nJtdjUiuRC8VORUA8Gx0mm68sw HTTP/1.1" 200 1172
2018-11-12 09:34:56,573:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 1172
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 12 Nov 2018 08:34:56 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 12 Nov 2018 08:34:56 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "www.mydomain.com"
  },
  "status": "pending",
  "expires": "2018-11-18T05:41:59Z",
  "challenges": [
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/qUhjUoBCfvXIc4Z67nJtdjUiuRC8VORUA8Gx0mm68sw/9174770220",
      "token": "w9TJinPXe7FvQ0ysL-vgsNTdWHFcqBdBXioVqiTyOo0"
    },
    {
      "type": "tls-sni-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/qUhjUoBCfvXIc4Z67nJtdjUiuRC8VORUA8Gx0mm68sw/9174770221",
      "token": "8Uq_muzxsXb6wYspBeBPb5jlvyzNbMlCDsid522Mowc"
    },
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/qUhjUoBCfvXIc4Z67nJtdjUiuRC8VORUA8Gx0mm68sw/9174770222",
      "token": "9JeIpbNhAy3SdE8xOuWe_mDVsR60f83OsiX6hcn-mBo"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/qUhjUoBCfvXIc4Z67nJtdjUiuRC8VORUA8Gx0mm68sw/9174770223",
      "token": "5ZZS1iZ3JQrpUdrkwEVL_kfQYY5KUBfLmIFbgjEIY_0"
    }
  ]
}
2018-11-12 09:34:56,575:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/acme/authz/XOfKMMMjMlD1Ki5L0BxiKAY3FTWPeamFI7kWS033Vls.
2018-11-12 09:34:56,762:DEBUG:requests.packages.urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /acme/authz/XOfKMMMjMlD1Ki5L0BxiKAY3FTWPeamFI7kWS033Vls HTTP/1.1" 200 1168
2018-11-12 09:34:56,764:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 1168
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Mon, 12 Nov 2018 08:34:56 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 12 Nov 2018 08:34:56 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "mydomain.com"
  },
  "status": "pending",
  "expires": "2018-11-18T05:41:59Z",
  "challenges": [
    {
      "type": "tls-sni-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/XOfKMMMjMlD1Ki5L0BxiKAY3FTWPeamFI7kWS033Vls/9174770216",
      "token": "3IlVKFr7SFgiMJVbEQQDD3szqMH1VcDHMCQey3qXBlw"
    },
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/XOfKMMMjMlD1Ki5L0BxiKAY3FTWPeamFI7kWS033Vls/9174770217",
      "token": "37WIP5volojDHY5FZi6g0FweDajnzZk5oZohp1mv6xM"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/XOfKMMMjMlD1Ki5L0BxiKAY3FTWPeamFI7kWS033Vls/9174770218",
      "token": "6EayipnY2bIKyVDLTu-9aP9jas2Z6tlgOLxES6I5whY"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/challenge/XOfKMMMjMlD1Ki5L0BxiKAY3FTWPeamFI7kWS033Vls/9174770219",
      "token": "FXJRgg5cC3ykO7xaZ6e-XPrvC7zB2IyZen7LrfGomwc"
    }
  ]
}
2018-11-12 09:34:56,765:INFO:certbot.auth_handler:Performing the following challenges:
2018-11-12 09:34:56,766:INFO:certbot.auth_handler:http-01 challenge for www.mydomain.com
2018-11-12 09:34:56,767:INFO:certbot.auth_handler:http-01 challenge for mydomain.com
2018-11-12 09:34:57,839:DEBUG:certbot_apache.http_01:Adding a temporary challenge validation Include for name: mydomain.com:80 in: /etc/apache2/sites-available/mydomain.com.conf
2018-11-12 09:34:57,866:DEBUG:certbot_apache.http_01:writing a pre config file with text:
         RewriteEngine on
        RewriteRule ^/\.well-known/acme-challenge/([A-Za-z0-9-_=]+)$ /var/lib/letsencrypt/http_challenges/$1 [END]
    
2018-11-12 09:34:57,866:DEBUG:certbot_apache.http_01:writing a post config file with text:
         <Directory /var/lib/letsencrypt/http_challenges>
            Require all granted
        </Directory>
        <Location /.well-known/acme-challenge>
            Require all granted
        </Location>
    
2018-11-12 09:34:57,905:DEBUG:certbot.reverter:Creating backup of /etc/apache2/sites-available/mydomain.com.conf
2018-11-12 09:34:57,906:DEBUG:certbot.reverter:Creating backup of /etc/apache2/apache2.conf
2018-11-12 09:34:58,738:ERROR:certbot.util:Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 46 of /etc/apache2/sites-available/mydomain.com.conf:
FastCgiExternalServer: redefinition of previously defined class "/var/www/mydomain.com/cgi-bin/php-fpm-fcgi-mydomain.com"

2018-11-12 09:34:58,746:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 132, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 2286, in perform
    self.restart()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 2173, in restart
    self.config_test()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 2213, in config_test
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 46 of /etc/apache2/sites-available/mydomain.com.conf:
FastCgiExternalServer: redefinition of previously defined class "/var/www/mydomain.com/cgi-bin/php-fpm-fcgi-mydomain.com"


2018-11-12 09:34:58,747:DEBUG:certbot.error_handler:Calling registered functions
2018-11-12 09:34:58,748:INFO:certbot.auth_handler:Cleaning up challenges
2018-11-12 09:35:01,111:WARNING:certbot.renewal:Attempting to renew cert (mydomain.com) from /etc/letsencrypt/renewal/mydomain.com.conf produced an unexpected error: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 46 of /etc/apache2/sites-available/mydomain.com.conf:
FastCgiExternalServer: redefinition of previously defined class "/var/www/mydomain.com/cgi-bin/php-fpm-fcgi-mydomain.com"
. Skipping.
2018-11-12 09:35:01,116:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/renewal.py", line 430, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 1168, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 116, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/renewal.py", line 305, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/client.py", line 335, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/client.py", line 371, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 132, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 2286, in perform
    self.restart()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 2173, in restart
    self.config_test()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_apache/configurator.py", line 2213, in config_test
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apache2ctl configtest.
Action 'configtest' failed.
The Apache error log may have more information.

AH00526: Syntax error on line 46 of /etc/apache2/sites-available/mydomain.com.conf:
FastCgiExternalServer: redefinition of previously defined class "/var/www/mydomain.com/cgi-bin/php-fpm-fcgi-mydomain.com"


2018-11-12 09:35:01,118:ERROR:certbot.renewal:All renewal attempts failed. The following certs could not be renewed:
2018-11-12 09:35:01,118:ERROR:certbot.renewal:  /etc/letsencrypt/live/mydomain.com/fullchain.pem (failure)
2018-11-12 09:35:01,144:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 1340, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 1247, in renew
    renewal.handle_renewal_request(config)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/renewal.py", line 455, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
<VirtualHost *:80>
	ServerName   mydomain.com:80

	UseCanonicalName Off
	ServerAdmin  "office@mydomain.com"
	DocumentRoot /var/www/mydomain.com/httpdocs
	CustomLog /var/log/apache2/mydomain.com_access.log combined
	ErrorLog /var/log/apache2/mydomain.com_error.log

	# use mod fastcgi -> proxy:fcgi makes some problems
	<IfModule mod_fastcgi.c>
		# Set virtual handler for fpm functions
		<LocationMatch "^/(fpm-ping|fpm-status)$">
			# Change the requre line to your needs if you need the functions
			Require all denied
			SetHandler php-fpm-fcgi-virt
			Action php-fpm-fcgi-virt /php-fpm-fcgi virtual
		</LocationMatch>
		# Set handler for *.php, *.php7, *.phtml, ... files
		<FilesMatch ".+\.ph(p[3457]?|t|tml)$">
			SetHandler php-fpm-fcgi
		</FilesMatch>
		<FilesMatch ".+\.phps$">
			# Deny access to raw php sources by default
			# To re-enable it's recommended to enable access to the files
			# only in specific virtual host or directory
			Require all denied
		</FilesMatch>
		# Deny access to files without filename (e.g. '.php')
		<FilesMatch "^\.ph(p[3457]?|t|tml|ps)$">
			Require all denied
		</FilesMatch>

		Action php-fpm-fcgi /php-fpm-fcgi
		Alias /php-fpm-fcgi /var/www/mydomain.com/cgi-bin/php-fpm-fcgi-mydomain.com
		FastCgiExternalServer /var/www/mydomain.com/cgi-bin/php-fpm-fcgi-mydomain.com -idle-timeout 300 -socket /run/php/php7-fpm.mydomain.com.sock -pass-header Authorization

		<Directory "/var/www/mydomain.com/cgi-bin">
			Require all granted
		</Directory>
	</IfModule>

	<Directory /var/www/mydomain.com/httpdocs>
		Options -Indexes
		Require all granted
		AllowOverride All
	</Directory>
</VirtualHost>
```

## Additional information
I'm not sure what certbot is doing here.
If I do an "apache2ctl configtest" I get "Syntax OK" back.
I asume certbot creates an duplicate configuration file or it uses "apache2ctl configtest" in a special way.
The error:
`Syntax error on line 46 of /etc/apache2/`**sites-available**`/mydomain.com.conf`
This seems wrong to me if I do the configtest it only checks the "**sites-enabled**" folder.

My current workaround is to disable the line -> renew -> enable the line.
For some configs I can disable the line entirely because there is always a redirect to https, but sadly this is not always possible.

**Comment by joohoi** [comment]
Yeah, Certbot copies over the `VirtualHost` in question, and `FastCgiExternalServer` looks to be one of the directives that we cannot reliably copy (breaks the configuration like in this case), comment out (could potentially expose webroot contents of the default document root), or modify (would require knowledge of the application in question). We have an umbrella issue tracking all of the issues that fall into this same category at #4797 . 

I'm closing this issue in order to not to fragment the discussion, but will link back to this from the umbrella issue description. I'm sorry for the inconvenience.
