### ISSUE TITLE
Connection reset by peer while handling challenge with --standalone

### ISSUE THREAD

**Issue by paolobenve** [certbot/certbot#6534]
Executing

`sudo certbot-auto certonly --expand --cert-name qumran2 --preferred-challenges http --standalone -d domain1,domain2,etc.`

I got an error:

```
Waiting for verification...
----------------------------------------
Exception happened during processing of request from ('::ffff:190.102.144.183', 23506, 0, 0)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/acme/standalone.py", line 206, in __init__
    BaseHTTPServer.BaseHTTPRequestHandler.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/acme/standalone.py", line 215, in handle
    BaseHTTPServer.BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
----------------------------------------
Cleaning up challenges
etc.
```
Notwithstanding, certbot-auto did what it should.

**Comment by sydneyli** [comment]
Hi @paolobenve, thanks for reporting. I recommend you ask this question on the [Let's Encrypt Community Forums](https://community.letsencrypt.org/c/help), where there's a larger audience of people familiar with the project. You'll get much faster help there!
