### ISSUE TITLE
Running tools/venv.py inside the local venv doesn't work

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#6545]
To hit this error I:

1. Ran `tools/venv.py` without a virtual environment active.
2. Ran `source venv/bin/activate`.
3. Ran `tools/venv.py` again.

The result was:
```
(venv) eff-bmw:certbot bmw$ tools/venv.py 
+ /Users/bmw/Development/certbot/certbot/venv/bin/python -m virtualenv --no-site-packages --setuptools venv --python /Users/bmw/Development/certbot/certbot/venv/bin/python
Traceback (most recent call last):
  File "tools/venv.py", line 41, in <module>
    main()
  File "tools/venv.py", line 37, in main
    _venv_common.main('venv', venv_args, REQUIREMENTS)
  File "/Users/bmw/Development/certbot/certbot/tools/_venv_common.py", line 150, in main
    subprocess_with_print(command)
  File "/Users/bmw/Development/certbot/certbot/tools/_venv_common.py", line 107, in subprocess_with_print
    subprocess.check_call(cmd, env=env, shell=shell)
  File "/Users/bmw/Homebrew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Users/bmw/Homebrew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/bmw/Homebrew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/Users/bmw/Homebrew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1046, in _execute_child
    child_exception = pickle.loads(data)
  File "/Users/bmw/Homebrew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/Users/bmw/Homebrew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/Users/bmw/Homebrew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 977, in load_string
    self.append(rep.decode("string-escape"))
LookupError: unknown encoding: string-escape
```
One of the first things `tools/venv.py` does is rename any existing `venv`. This is likely the cause of this error because we then continue to try and use the Python installation inside the `venv` after it has been moved.

While I think it's totally reasonable you can't use the `tools/venv*` scripts like this, I think we should improve the error message if possible as it's not immediately clear what went wrong.

**Comment by bmw** [comment]
This is still an issue albeit a low priority one. Someone who doesn't usually work with Python or Certbot hit this issue and I think it'd be nice if we helped people avoid problems like this.
