### ISSUE TITLE
Hooks to manage firewall rules aren't executed at the right moment.

### ISSUE THREAD

**Issue by Axelandre42** [certbot/certbot#6611]
## My operating system is (include version):

Debian 9 Stretch
`uname -a` result: `Linux scw-7c2934 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux`

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

Aptitude (from `stretch-backports`)
`apt install -t stretch-backports certbot`

Certbot version is 0.28.0

## I ran this command and it produced this output:

The command is: `certbot renew --dry-run --pre-hook '/opt/scripts/firewall.sh -a 80,443' --post-hook '/opt/scripts/firewall.sh -r 80,443'`
And gives:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/***DOMAIN***.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator standalone, Installer None
Attempting to renew cert (sip0.fwaeles.ovh) from /etc/letsencrypt/renewal/***DOMAIN***.conf produced an unexpected error: HTTPSConnectionPool(host='acme-staging-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4aa11f40f0>, 'Connection to acme-staging-v02.api.letsencrypt.org timed out. (connect timeout=45)')). Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/***DOMAIN***/fullchain.pem (failure)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/***DOMAIN***/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)
```

## Certbot's behavior differed from what I expected because:
It executes the pre-hook **after** (it should be before) trying to use HTTP(S)...

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2018-12-17 21:57:18,806:DEBUG:certbot.main:certbot version: 0.28.0
2018-12-17 21:57:18,808:DEBUG:certbot.main:Arguments: ['--dry-run', '--pre-hook', '/opt/scripts/firewall.sh -a 80,443', '--post-hook', '/opt/scripts/firewall.sh -r 80,443']
2018-12-17 21:57:18,810:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2018-12-17 21:57:18,830:DEBUG:certbot.log:Root logging level set at 20
2018-12-17 21:57:18,833:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2018-12-17 21:57:18,852:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7f4aa120dd30> and installer <certbot.cli._Default object at 0x7f4aa120dd30>
2018-12-17 21:57:18,853:DEBUG:certbot.cli:Var dry_run=True (set by user).
2018-12-17 21:57:18,853:DEBUG:certbot.cli:Var server={'staging', 'dry_run'} (set by user).
2018-12-17 21:57:18,853:DEBUG:certbot.cli:Var dry_run=True (set by user).
2018-12-17 21:57:18,853:DEBUG:certbot.cli:Var server={'staging', 'dry_run'} (set by user).
2018-12-17 21:57:18,854:DEBUG:certbot.cli:Var account={'server'} (set by user).
2018-12-17 21:57:18,867:INFO:certbot.renewal:Cert not due for renewal, but simulating renewal for dry run
2018-12-17 21:57:18,868:DEBUG:certbot.plugins.selection:Requested authenticator standalone and installer None
2018-12-17 21:57:18,914:DEBUG:certbot.plugins.selection:Single candidate plugin: * standalone
Description: Spin up a temporary webserver
Interfaces: IAuthenticator, IPlugin
Entry point: standalone = certbot.plugins.standalone:Authenticator
Initialized: <certbot.plugins.standalone.Authenticator object at 0x7f4aa120ff98>
Prep: True
2018-12-17 21:57:18,916:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.standalone.Authenticator object at 0x7f4aa120ff98> and installer None
2018-12-17 21:57:18,917:INFO:certbot.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2018-12-17 21:57:18,922:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(new_authzr_uri=None, terms_of_service=None, body=Registration(agreement=None, only_return_existing=None, terms_of_service_agreed=None, key=None, contact=(), status=None), uri='https://acme-staging-v02.api.letsencrypt.org/acme/acct/7607344'), 642b4810d14b2bf3db010d9b43419710, Meta(creation_dt=datetime.datetime(2018, 12, 17, 17, 37, 58, tzinfo=<UTC>), creation_host='localhost'))>
2018-12-17 21:57:18,925:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/directory.
2018-12-17 21:57:18,937:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org
2018-12-17 21:59:34,056:WARNING:certbot.renewal:Attempting to renew cert (***DOMAIN***) from /etc/letsencrypt/renewal/***DOMAIN***.conf produced an unexpected error: HTTPSConnectionPool(host='acme-staging-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4aa11f40f0>, 'Connection to acme-staging-v02.api.letsencrypt.org timed out. (connect timeout=45)')). Skipping.
2018-12-17 21:59:34,065:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 837, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 281, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 143, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4aa11f40f0>, 'Connection to acme-staging-v02.api.letsencrypt.org timed out. (connect timeout=45)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 363, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-staging-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4aa11f40f0>, 'Connection to acme-staging-v02.api.letsencrypt.org timed out. (connect timeout=45)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 430, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1166, in renew_cert
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 611, in _init_le_client
    return client.Client(config, acc, authenticator, installer, acme=acme)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 248, in __init__
    acme = acme_from_config_key(config, self.account.key, self.account.regr)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 51, in acme_from_config_key
    return acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 763, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1097, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1046, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 479, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='acme-staging-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4aa11f40f0>, 'Connection to acme-staging-v02.api.letsencrypt.org timed out. (connect timeout=45)'))

2018-12-17 21:59:34,066:ERROR:certbot.renewal:All renewal attempts failed. The following certs could not be renewed:
2018-12-17 21:59:34,066:ERROR:certbot.renewal:  /etc/letsencrypt/live/***DOMAIN***/fullchain.pem (failure)
2018-12-17 21:59:34,069:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.28.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1340, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1247, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 455, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
certbot.errors.Error: 1 renew failure(s), 0 parse failure(s)
```

#### About my firewall configuration:

I'm using a highly restrictive configuration that doesn't even allow outbound connections.
It is needed to open the ports before performing the very first HTTP(S) request to the Let's Encrypt API.

The following code is the content of `/opt/scripts/firewall.sh`:
```bash
#!/bin/sh

IPV4=/sbin/iptables
IPV6=/sbin/ip6tables

display_help() {
	echo 'Usage: firewall.sh [-46] [-a <ports>] [-r <ports>]'
}

add_ports() {
	for PORT in $( echo $1 | sed 's/,/ /g' )
	do
		$IPV4 -A INPUT  -p tcp --dport $PORT -j ACCEPT
		$IPV4 -A OUTPUT -p tcp --dport $PORT -j ACCEPT
		$IPV6 -A INPUT  -p tcp --dport $PORT -j ACCEPT
		$IPV6 -A OUTPUT -p tcp --dport $PORT -j ACCEPT
	done
}

remove_ports() {
	for PORT in $( echo $1 | sed 's/,/ /g' )
	do
		$IPV4 -D INPUT  -p tcp --dport $PORT -j ACCEPT
		$IPV4 -D OUTPUT -p tcp --dport $PORT -j ACCEPT
		$IPV6 -D INPUT  -p tcp --dport $PORT -j ACCEPT
		$IPV6 -D OUTPUT -p tcp --dport $PORT -j ACCEPT
	done
}

ipv4_rules() {
	# Clear 'filter' table.
	$IPV4 -F
	$IPV4 -X

	# Set 'filter' policies to DROP.
	$IPV4 -P INPUT   DROP
	$IPV4 -P FORWARD DROP
	$IPV4 -P OUTPUT  DROP

	# Accept all established connections.
	$IPV4 -A INPUT  -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
	$IPV4 -A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

	# Drop invalid packets.
	$IPV4 -A INPUT -m conntrack --ctstate INVALID -j DROP

	# Drop non-SYN new connetions packets.
	$IPV4 -A INPUT -p tcp ! --syn -m conntrack --ctstate NEW -j DROP
	
	# Drop spoofed IPv4 source addresses.
	$IPV4 -A INPUT -s 0.0.0.0/8       -j DROP
	$IPV4 -A INPUT -s 100.64.0.0/10   -j DROP
	$IPV4 -A INPUT -s 169.254.0.0/16  -j DROP
	$IPV4 -A INPUT -s 172.16.0.0/12   -j DROP
	$IPV4 -A INPUT -s 192.0.2.0/24    -j DROP
	$IPV4 -A INPUT -s 192.168.0.0/16  -j DROP
	$IPV4 -A INPUT -s 198.51.100.0/24 -j DROP
	$IPV4 -A INPUT -s 203.0.113.0/24  -j DROP
	$IPV4 -A INPUT -s 224.0.0.0/3     -j DROP
	$IPV4 -A INPUT -s 240.0.0.0/5     -j DROP
	
	# Drop non-loopback 127.0.0.0/8 packet source.
	$IPTABLES -A INPUT -s 127.0.0.0/8 ! -i lo -j DROP
	
	# Drop fragmented packets.
	$IPV4 -A INPUT -f -j DROP

	# Allow loopback.
	$IPV4 -A INPUT  -i lo -j ACCEPT
	$IPV4 -A OUTPUT -o lo -j ACCEPT

	# Allow ports.
	$IPV4 -A INPUT  -p tcp --dport 22    -j ACCEPT
	$IPV4 -A OUTPUT -p tcp --dport 22    -j ACCEPT
	$IPV4 -A INPUT  -p tcp --dport 53    -j ACCEPT
	$IPV4 -A OUTPUT -p tcp --dport 53    -j ACCEPT
	$IPV4 -A INPUT  -p udp --dport 53    -j ACCEPT
	$IPV4 -A OUTPUT -p udp --dport 53    -j ACCEPT
	$IPV4 -A INPUT  -p tcp --dport 5060  -j ACCEPT
	$IPV4 -A OUTPUT -p tcp --dport 5060  -j ACCEPT
	$IPV4 -A INPUT  -p udp --dport 5060  -j ACCEPT
	$IPV4 -A OUTPUT -p udp --dport 5060  -j ACCEPT

	$IPV4 -A INPUT  -p udp -m multiport --dports 30000:40000 -j ACCEPT
	$IPV4 -A OUTPUT -p udp -m multiport --dports 30000:40000 -j ACCEPT

	# ICMP tweaks.
	$IPV4 -A INPUT  -p icmp --icmp-type 0  -j ACCEPT
	$IPV4 -A INPUT  -p icmp --icmp-type 3  -j ACCEPT
	$IPV4 -A INPUT  -p icmp --icmp-type 8  -j ACCEPT
	$IPV4 -A INPUT  -p icmp --icmp-type 11 -j ACCEPT
	$IPV4 -A INPUT  -p icmp --icmp-type 12 -j ACCEPT
	$IPV4 -A OUTPUT -p icmp -j ACCEPT
}

ipv6_rules() {
	# Clear 'filter' table.
	$IPV6 -F
	$IPV6 -X

	# Set 'filter' policies to DROP.
	$IPV6 -P INPUT   DROP
	$IPV6 -P FORWARD DROP
	$IPV6 -P OUTPUT  DROP

	# Accept all established connections.
	$IPV6 -A INPUT  -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
	$IPV6 -A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

	# Drop invalid packets.
	$IPV6 -A INPUT -m conntrack --ctstate INVALID -j DROP

	# Drop non-SYN new connetions packets.
	$IPV6 -A INPUT -p tcp ! --syn -m conntrack --ctstate NEW -j DROP
	
	# Drop spoofed IPv6 source addresses.
	$IPV6 -A INPUT -s fe80::/10      -j DROP
	$IPV6 -A INPUT -s fc00::/7       -j DROP
	$IPV6 -A INPUT -s 2001:db8::/32  -j DROP
	$IPV6 -A INPUT -s 0100::/64      -j DROP
	$IPV6 -A INPUT -s ::/128 -j DROP
	
	# Drop non-loopback ::1/128 packet source.
	$IPV6 -A INPUT -s ::1/128 ! -i lo -j DROP
	
	# Drop fragmented packets.
	$IPV6 -A INPUT -f -j DROP

	# Allow loopback.
	$IPV6 -A INPUT  -i lo -j ACCEPT
	$IPV6 -A OUTPUT -o lo -j ACCEPT

	# Allow ports.
	$IPV6 -A INPUT  -p tcp --dport 22    -j ACCEPT
	$IPV6 -A OUTPUT -p tcp --dport 22    -j ACCEPT
	$IPV6 -A INPUT  -p tcp --dport 53    -j ACCEPT
	$IPV6 -A OUTPUT -p tcp --dport 53    -j ACCEPT
	$IPV6 -A INPUT  -p udp --dport 53    -j ACCEPT
	$IPV6 -A OUTPUT -p udp --dport 53    -j ACCEPT
	$IPV6 -A INPUT  -p tcp --dport 5060  -j ACCEPT
	$IPV6 -A OUTPUT -p tcp --dport 5060  -j ACCEPT
	$IPV6 -A INPUT  -p udp --dport 5060  -j ACCEPT
	$IPV6 -A OUTPUT -p udp --dport 5060  -j ACCEPT

	$IPV6 -A INPUT  -p udp -m multiport --dports 30000:40000 -j ACCEPT
	$IPV6 -A OUTPUT -p udp -m multiport --dports 30000:40000 -j ACCEPT

	# ICMP tweaks.
	$IPV6 -A INPUT  -p icmp --icmp-type 0  -j ACCEPT
	$IPV6 -A INPUT  -p icmp --icmp-type 3  -j ACCEPT
	$IPV6 -A INPUT  -p icmp --icmp-type 8  -j ACCEPT
	$IPV6 -A INPUT  -p icmp --icmp-type 11 -j ACCEPT
	$IPV6 -A INPUT  -p icmp --icmp-type 12 -j ACCEPT
	$IPV6 -A OUTPUT -p icmp -j ACCEPT
}

while getopts ":46a:r:h" OPTION
do
	case $OPTION in
		4)
			echo 'Setting up IPv4 rules...'
			ipv4_rules
			;;
		6)
			echo 'Setting up IPv6 rules...'
			ipv6_rules
			;;
		a)
			echo "Adding ports $( echo $OPTARG | sed 's/,/, /g' ) to allow list..."
			add_ports "${OPTARG}"
			;;
		r)
			echo "Removing ports $( echo $OPTARG | sed 's/,/, /g' ) to allow list..."
			remove_ports "${OPTARG}"
			;;
		h)
			display_help
			;;
		:)
			echo "firewall.sh:${OPTARG}: Missing arguments!"
			display_help
			exit 1
			;;
		\?)
			echo "firewall.sh:${OPTARG}: Invalid option!"
			display_help
			exit 1
			;;
	esac
done
exit 0
```
#### About why I'm not using ports 80 and 443:

This server is only intended for my IP PBX so no need for web access.

#### About what I expect with this issue:

The best solution would be to run the `--pre-hook` command just before the very first HTTP(S) request to make Certbot _compatible with those restrictive firewalls._

#### A last (stupid) question:

Who is providing the `stretch-backports` builds ?

#### And a conclusion:

Thank you to have read this _small_ report.
I hope it can be solved soon and pushed to the Debian repositories.

**Comment by schoen** [comment]
Hi @Axelandre42,

Thanks for reporting this; this seems like it could possibly be a bug in Certbot.

Have you tried renewing the certificate with these hooks but without `--dry-run`? If you do this, do you see the same behavior or different behavior?

**Comment by Axelandre42** [comment]
My current certificate is _brand new_ so it doesn't need to be renewed. If I run it without `--dry-run`, Certbot says it doesn't to be renewed...

Here's the result:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/***DOMAIN***.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/***DOMAIN***/fullchain.pem expires on 2019-03-17 (skipped)
No renewals were attempted.
No hooks were run.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

**Comment by jacen05** [comment]
Hello,

I have the same problem on Debian 10.

System
```
# cat /etc/debian_version
10.1
# uname -a
Linux vps737543 4.19.0-6-cloud-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
```

Certbot version:
```
# dpkg -l | grep  certbot
ii  certbot                          0.31.0-1                    all          automatically configure HTTPS using Let's Encrypt
ii  python-certbot-apache            0.31.0-1                    all          transitional dummy package
ii  python3-certbot                  0.31.0-1                    all          main library for certbot
ii  python3-certbot-apache           0.31.0-1                    all          Apache plugin for Certbot
```

I tried:
`# certbot renew --dry-run --pre-hook "iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT" --post-hook "iptables -t filter -D OUTPUT -p tcp --dport 443 -j ACCEPT"`
=> Error `Requesting acme-staging-v02.api.letsencrypt.org/directory: Network is unreachable.`

I also tried defining the commands as script files in /etc/letsencrypt/renewal-hooks/
```
# cat /etc/letsencrypt/renewal-hooks/pre/enable_http
#!/bin/sh

IPTABLES=/usr/sbin/iptables
$IPTABLES -A OUTPUT -o eth0 -p tcp -m conntrack --ctstate NEW -m tcp --dport 443 -j ACCEPT

# cat /etc/letsencrypt/renewal-hooks/post/disable_http
#!/bin/sh

IPTABLES=/usr/sbin/iptables
$IPTABLES -D OUTPUT -o eth0 -p tcp -m conntrack --ctstate NEW -m tcp --dport 443 -j ACCEPT
```
Same error.
However if I run manually the scripts it works
```
# bash /etc/letsencrypt/renewal-hooks/pre/enable_http
# certbot renew --dry-run
# bash /etc/letsencrypt/renewal-hooks/post/disable_http
```

Additionnal info: same behavior observed without `--dry-run` option.

So either my certbot is not up-to-date (but it is the latest version in Debian 10 repo) or the problem is not solved.

**Comment by jacen05** [comment]
Issue still persists in Debian 10, with both the certbot version from the Debian buster repository (0.31.0) and from the snap (1.12.0).
I've done the same tests than the one described in my previous post.
