### ISSUE TITLE
Forced use of virtual hosts stops Mac OS X Server support!

### ISSUE THREAD

**Issue by zerofino** [certbot/certbot#6615]
## My operating system is (include version):
Mac OS X Server, El Capitan, 10.11.6; Server.app, 5.2

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
MacPorts

## I ran this command and it produced this output:
sudo certbot --apache certonly
Result: Complaining about missing virtual host definition during authentication test.

## Certbot's behavior differed from what I expected because:
It is unclear, why a virtual host definition is required (and how it becomes tested). Instead the authentication key file seems to be not really placed to ".../.well-known/acme-challenge/ folder. Some test file is easily accessible via http://<domain>//.well-known/acme-challenge/test.html.
Probably a http to https switch appears, but this does not alter the data content.
In any way the Mac OS X Server philosophy (starting from version 5) does not use named virtual hosts and it seems to be impossible to force it to use them.
On the other hand Certbot certificates have been successfully installed before the last Certbot update. But the elder method seems to be obsolete, because it does not operates with the current acme server.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2018-12-20 21:46:32,527:DEBUG:certbot.error_handler:Calling registered functions
2018-12-20 21:46:32,528:INFO:certbot.auth_handler:Cleaning up challenges
2018-12-20 21:46:33,342:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.29.1', 'console_scripts', 'certbot')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot/main.py", line 1352, in main
    return config.func(config, plugins)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot/main.py", line 1227, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot/main.py", line 123, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot/client.py", line 353, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot/client.py", line 389, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot/auth_handler.py", line 132, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot_apache/configurator.py", line 2280, in perform
    http_response = http_doer.perform()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot_apache/http_01.py", line 72, in perform
    self._mod_config()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot_apache/http_01.py", line 99, in _mod_config
    for vh in self._relevant_vhosts():
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certbot_apache/http_01.py", line 136, in _relevant_vhosts
    " {0}.".format(http01_port))
PluginError: Unable to find a virtual host listening on port 80 which is currently needed for Certbot to prove to the CA that you control your domain. Please add a virtual host for port 80.

**Alternative output at terminal:**

Obtaining a new certificate
Performing the following challenges:
http-01 challenge for pro.protronis.com
Input the webroot for pro.protronis.com: (Enter 'c' to cancel): /Volumes/...
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. pro.protronis.com (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://<domain>/.well-known/acme-challenge/rkIC4aYTNPMwjH5MgCDpEG0WQqLS0_b2SaDO9IepSr8 [2003:2:2:15:80:150:6:143]: 404

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: pro.protronis.com
   Type:   unauthorized
   Detail: Invalid response from
   http://<domain>/.well-known/acme-challenge/rkIC4aYTNPMwjH5MgCDpEG0WQqLS0_b2SaDO9IepSr8
   [2003:2:2:15:80:150:6:143]: 404

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
<VirtualHost 127.0.0.1:34580>
	ServerName default
	ServerAdmin admin@example.com
	DocumentRoot "/Library/Server/Web/Data/Sites/Default"
	DirectoryIndex index.html index.php default.html
	CustomLog "/var/log/apache2/access_log" combinedvhost
	ErrorLog "/var/log/apache2/error_log"
	<IfModule mod_ssl.c>
		SSLEngine Off
		SSLCipherSuite "HIGH:MEDIUM:!MD5:!RC4:!3DES"
		SSLProtocol -all +TLSv1 +TLSv1.1 +TLSv1.2
		SSLProxyEngine Off
		SSLProxyProtocol -all +TLSv1 +TLSv1.1 +TLSv1.2
		SSLProxyCheckPeerCN off
		SSLProxyCheckPeerName off
	</IfModule>
	<IfModule mod_secure_transport.c>
		MSTEngine Off
		MSTCipherSuite HIGH, MEDIUM
		MSTProtocolRange TLSv1.2 TLSv1.2
		MSTProxyEngine On
		MSTProxyProtocolRange TLSv1.2 TLSv1.2
	</IfModule>
	<Directory "/Library/Server/Web/Data/Sites/Default">
		Options All -Indexes -ExecCGI -Includes +MultiViews
		AllowOverride None
		<IfModule mod_dav.c>
			DAV Off
		</IfModule>
		<IfDefine !WEBSERVICE_ON>
			Require all denied
			ErrorDocument 403 /customerror/websitesoff403.html
		</IfDefine>
	</Directory>
	Alias /.well-known "/Volumes/.../.well-known"
</VirtualHost>

This virtual host at a special service port becomes accessed from port 80 via proxy definitions.
As already told above there is no named virtual host for port 80 and it cannot get the reason, why it should be needed.
Sorry, but your last Certbot update has broken Mac OS X Server support without real need, I guess.
Could you please turn compatibility back?

**Comment by sydneyli** [comment]
@zerofino, thanks for reporting!

@schoen, any insights on this issue? I think you mentioned you were dealing with some similar issues on the community forums.

**Comment by zerofino** [comment]
Sorry, but my main problem was a wrong DNS configuration by the provider, which stopped Certbot from operating. After solving this certificate generation was successful again.
The virtual host problem of Mac OS X Server is still the case, but one simply has to use the webroot directory method.
