### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'python-digitalocean>=1.11' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by ufo911** [certbot/certbot#6617]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu Server 16.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Don't remember mixed up

## I ran this command and it produced this output:
I set cronjob for certbot renew --noninteractive

## Certbot's behavior differed from what I expected because:
2018-12-20 21:10:01,907:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1338, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 206, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 52, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2228, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2245, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-digitalocean>=1.11' distribution was not found and is required by the application
2018-12-20 21:10:01,907:ERROR:certbot.log:An unexpected error occurred:

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
pkg_resources.DistributionNotFound: The 'python-digitalocean>=1.11' distribution was not found and is required by the application
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
nginix is ok

**Comment by ufo911** [comment]
So, my pip was installed to home/user dir and that was problem, I installed python-digitalocean to /usr/lib/python3/dist-packages/ and problem solved.
