### ISSUE TITLE
now we are getting error for 2.7 going to deprecation please update this

### ISSUE THREAD

**Issue by pixelgaurav** [certbot/certbot#6686]
pip prints the following errors: 
=====================================================
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

Exception:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/pip/_internal/wheel.py", line 848, in build
    assert building_is_possible
AssertionError

**Comment by adferrand** [comment]
I am going to close this issue related to pip 19.0:
* in favor or #3726 to handle the deprecation warning
* in favor of #6682 for the AssertionError
