### ISSUE TITLE
--webroot doesn't work

### ISSUE THREAD

**Issue by Shifterovich** [certbot/certbot#6733]
## I ran this command and it produced this output:

```
samuel@testbox:~$ sudo certbot certonly -n --webroot -w /var/www/html --staging -d <redacteddomain> --preferred-challenges http --must-staple --agree-tos --email redacted@mail.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for <redacteddomain>
Using the webroot path /var/www/html for all unmatched domains.
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. <redacteddomain> (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching https:///.well-known/acme-challenge/redactedtoken: Error getting validation data

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: <redacteddomain>
   Type:   connection
   Detail: Fetching
   https:///.well-known/acme-challenge/redactedtoken:
   Error getting validation data

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
```

## Certbot's behavior differed from what I expected because:

The URL didn't contain the domain.

## Here is a Certbot log showing the issue (if available):

```
2019-02-02 22:35:44,584:DEBUG:certbot.reporter:Reporting to user: The following errors were reported by the server:

Domain: <redacteddomain>
Type:   connection
Detail: Fetching https:///.well-known/acme-challenge/redactedtoken: Error getting validation data

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address. Additionally, please check that your computer has a publicly routable IP address and that no firewalls are preventing the server from communicating with the client. If you're using the webroot plugin, you should also verify that you are serving files from the webroot path you provided.
2019-02-02 22:35:44,584:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 82, in handle_authorizations
    self._respond(aauthzrs, resp, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 161, in _respond
    self._poll_challenges(aauthzrs, chall_update, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 232, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
certbot.errors.FailedChallenges: Failed authorization procedure. <redacteddomain> (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching https:///.well-known/acme-challenge/redactedtoken: Error getting validation data

2019-02-02 22:35:44,585:DEBUG:certbot.error_handler:Calling registered functions
2019-02-02 22:35:44,585:INFO:certbot.auth_handler:Cleaning up challenges
2019-02-02 22:35:44,585:DEBUG:certbot.plugins.webroot:Removing /var/www/html/.well-known/acme-challenge/redactedtoken
2019-02-02 22:35:44,586:DEBUG:certbot.plugins.webroot:All challenges cleaned up
2019-02-02 22:35:44,586:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.28.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1340, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1225, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 392, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 335, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 371, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 82, in handle_authorizations
    self._respond(aauthzrs, resp, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 161, in _respond
    self._poll_challenges(aauthzrs, chall_update, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 232, in _poll_challenges
    raise errors.FailedChallenges(all_failed_achalls)
certbot.errors.FailedChallenges: Failed authorization procedure. <redacteddomain> (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching https:///.well-known/acme-challenge/redactedtoken: Error getting validation data
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

(none, I am using webroot)

**Comment by Shifterovich** [comment]
I see. I just remembered that I have a server block that redirects (301) all HTTP requests to HTTPS. I thought it would break certbot, but it didn't. But apparently that's because --nginx

> directly injects the challenge response into your port 80 virtualhost

After removing the catch-all-HTTP server block, everything works.

Thanks!
