### ISSUE TITLE
certbot --apache fails with commented lines

### ISSUE THREAD

**Issue by CoskunSunali** [certbot/certbot#6834]
## My operating system is (include version):

centos-release-7-6.1810.2.el7.centos.x86_64

## Certbot's behavior differed from what I expected because:

It used to work but after updating to latest version it started throwing:

```bash
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('There has been an error in parsing the file /etc/httpd/conf.d/_ssl.conf on line 139: Syntax error',)
```

## Here is a Certbot log showing the issue (if available):

```bash
2019-03-09 00:24:25,216:DEBUG:certbot.main:Arguments: ['--apache']
2019-03-09 00:24:25,216:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-03-09 00:24:25,234:DEBUG:certbot.log:Root logging level set at 20
2019-03-09 00:24:25,234:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2019-03-09 00:24:25,235:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2019-03-09 00:24:25,329:DEBUG:certbot_apache.configurator:Apache version is 2.4.6
2019-03-09 00:24:25,588:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): There has been an error in parsing the file /etc/httpd/conf.d/_ssl.conf on line 139: Syntax error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/plugins/disco.py", line 132, in prepare
    self._initialized.prepare()
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 255, in prepare
    self.check_parsing_errors("httpd.aug")
  File "/usr/lib/python2.7/site-packages/certbot_apache/augeas_configurator.py", line 77, in check_parsing_errors
    raise errors.PluginError(msg)
PluginError: There has been an error in parsing the file /etc/httpd/conf.d/_ssl.conf on line 139: Syntax error
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
#<Location />
#SSLRequire (    %{SSL_CIPHER} !~ m/^(EXP|NULL)/ \
#            and %{SSL_CLIENT_S_DN_O} eq "Snake Oil, Ltd." \
#            and %{SSL_CLIENT_S_DN_OU} in {"Staff", "CA", "Dev"} \
#            and %{TIME_WDAY} >= 1 and %{TIME_WDAY} <= 5 \
#            and %{TIME_HOUR} >= 8 and %{TIME_HOUR} <= 20       ) \
#           or %{REMOTE_ADDR} =~ m/^192\.76\.162\.[0-9]+$/
#</Location>
```

Mentioned line 139 is `#SSLRequire (    %{SSL_CIPHER} !~ m/^(EXP|NULL)/ \` and **certbot works** when I remove the `<Location>` tag.

However, as can be seen, the mentioned line actually starts with `#` which means it is a commented out line.

Any ideas?

**Comment by schoen** [comment]
Hi @CoskunSunali,

Thanks for letting us know about this. Which version of Certbot are you using here?

**Comment by CoskunSunali** [comment]
Hi @schoen 

`certbot --version` reports `certbot 0.31.0`

**Comment by schoen** [comment]
@joohoi, could this be related somehow to the Apache fixes that you've been making recently?
