### ISSUE TITLE
Pre and post-hooks failing

### ISSUE THREAD

**Issue by kbpersonal** [certbot/certbot#6885]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I ran this command and it produced this output: 
root@killinit:/var/log/letsencrypt# certbot renew --dry-run
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/domain.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not due for renewal, but simulating renewal for dry run
Plugins selected: Authenticator apache, Installer apache
Running pre-hook command: /etc/letsencrypt/renewal-hooks/pre/pre.sh
Output from pre.sh:
Enabling site 000-default.
To activate the new configuration, you need to run:
  service apache2 reload

Renewing an existing certificate
Performing the following challenges:
http-01 challenge for domain
Cleaning up challenges
Attempting to renew cert (domain) from /etc/letsencrypt/renewal/domain.conf produced an unexpected error: Unable to find a virtual host listening on port 80 which is currently needed for Certbot to prove to the CA that you control your domain. Please add a virtual host for port 80.. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/domain/fullchain.pem (failure)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/domain/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Running post-hook command: /etc/letsencrypt/renewal-hooks/post/post.sh
Output from post.sh:
Site 000-default disabled.
To activate the new configuration, you need to run:
  service apache2 reload

1 renew failure(s), 0 parse failure(s)

## Certbot's behavior differed from what I expected because:
I use pre and post-hooks to enable/disable virtualhost on port 80 during the renewal process. Manually it works but with pre and post hooks trying to automate renewal it fails with the message above. 

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
root@user322:/var/log/letsencrypt# cat letsencrypt.log
2019-03-25 17:14:13,273:DEBUG:certbot.main:certbot version: 0.26.1
2019-03-25 17:14:13,273:DEBUG:certbot.main:Arguments: ['--dry-run']
2019-03-25 17:14:13,274:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-03-25 17:14:13,283:DEBUG:certbot.log:Root logging level set at 20
2019-03-25 17:14:13,283:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2019-03-25 17:14:13,292:DEBUG:certbot.plugins.selection:Requested authenticator <certbot.cli._Default object at 0x7f018d2a6278> and installer <certbot.cli._Default object at 0x7f018d2a6278>
2019-03-25 17:14:13,292:DEBUG:certbot.cli:Var dry_run=True (set by user).
2019-03-25 17:14:13,292:DEBUG:certbot.cli:Var server={'staging', 'dry_run'} (set by user).
2019-03-25 17:14:13,292:DEBUG:certbot.cli:Var dry_run=True (set by user).
2019-03-25 17:14:13,292:DEBUG:certbot.cli:Var server={'staging', 'dry_run'} (set by user).
2019-03-25 17:14:13,292:DEBUG:certbot.cli:Var account={'server'} (set by user).
2019-03-25 17:14:13,301:INFO:certbot.renewal:Cert not due for renewal, but simulating renewal for dry run
2019-03-25 17:14:13,301:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2019-03-25 17:14:13,374:DEBUG:certbot_apache.configurator:Apache version is 2.4.18
2019-03-25 17:14:13,742:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT
Initialized: <certbot_apache.override_debian.DebianConfigurator object at 0x7f019c474080>
Prep: True
2019-03-25 17:14:13,744:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin - Beta
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT
Initialized: <certbot_apache.override_debian.DebianConfigurator object at 0x7f019c474080>
Prep: True
2019-03-25 17:14:13,744:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.override_debian.DebianConfigurator object at 0x7f019c474080> and installer <certbot_apache.override_debian.DebianConfigurator object at 0x7f019c474080>
2019-03-25 17:14:13,744:INFO:certbot.plugins.selection:Plugins selected: Authenticator apache, Installer apache
2019-03-25 17:14:13,746:DEBUG:certbot.main:Picked account: <Account(RegistrationResource(uri='https://acme-staging-v02.api.letsencrypt.org/acme/acct/8700497', body=Registration(only_return_existing=None, terms_of_service_agreed=None, agreement=None, contact=(), key=None, status=None), terms_of_service=None, new_authzr_uri=None), 257d0046e5d26128d90037aff070d7a6, Meta(creation_host='user322', creation_dt=datetime.datetime(2019, 3, 25, 22, 5, 58, tzinfo=<UTC>)))>
2019-03-25 17:14:13,748:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/directory.
2019-03-25 17:14:13,750:DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org
2019-03-25 17:14:13,884:DEBUG:requests.packages.urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 724
2019-03-25 17:14:13,884:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 724
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Tue, 26 Mar 2019 00:14:13 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 26 Mar 2019 00:14:13 GMT
Connection: keep-alive

{
  "BGPV24TAScs": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-staging-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org/docs/staging-environment/"
  },
  "newAccount": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert"
}
2019-03-25 17:14:13,885:INFO:certbot.hooks:Running pre-hook command: /etc/letsencrypt/renewal-hooks/pre/pre.sh
2019-03-25 17:14:13,921:INFO:certbot.hooks:Output from pre.sh:
Enabling site 000-default.
To activate the new configuration, you need to run:
  service apache2 reload

2019-03-25 17:14:13,921:INFO:certbot.main:Renewing an existing certificate
2019-03-25 17:14:14,057:DEBUG:acme.client:Requesting fresh nonce
2019-03-25 17:14:14,057:DEBUG:acme.client:Sending HEAD request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order.
2019-03-25 17:14:14,149:DEBUG:requests.packages.urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "HEAD /acme/new-order HTTP/1.1" 405 0
2019-03-25 17:14:14,150:DEBUG:acme.client:Received response:
HTTP 405
Server: nginx
Content-Type: application/problem+json
Content-Length: 103
Allow: POST
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: z7cFAhTpdt4PYK6I2vQfzCJ3qlx4CfRk1kJrEKTJsaA
Expires: Tue, 26 Mar 2019 00:14:14 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 26 Mar 2019 00:14:14 GMT
Connection: keep-alive

2019-03-25 17:14:14,150:DEBUG:acme.client:Storing nonce: z7cFAhTpdt4PYK6I2vQfzCJ3qlx4CfRk1kJrEKTJsaA
2019-03-25 17:14:14,150:DEBUG:acme.client:JWS payload:
b'{\n  "resource": "new-order",\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "domain"\n    }\n  ],\n  "status": "pending"\n}'
2019-03-25 17:14:14,153:DEBUG:acme.client:Sending POST request to https://acme-staging-v02.api.letsencrypt.org/acme/new-order:
{
  "payload": "ewogICJyZXNvdXJjZSI6ICJuZXctb3JkZXIiLAogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInJzYi1raWxsaW5pdC5kdWNrZG5zLm9yZyIKICAgIH0KICBdLAogICJzdGF0dXMiOiAicGVuZGluZyIKfQ",
  "protected": "eyJhbGciOiAiUlMyNTYiLCAibm9uY2UiOiAiejdjRkFoVHBkdDRQWUs2STJ2UWZ6Q0ozcWx4NENmUmsxa0pyRUtUSnNhQSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXN0YWdpbmctdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIiLCAia2lkIjogImh0dHBzOi8vYWNtZS1zdGFnaW5nLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC84NzAwNDk3In0",
  "signature": "MYj8sYdoCQUaDyH5ZJ9W4YqD6WFmYZQbbffl8t6o-Y_8KUzaGvJSiGmO6_BfzlhpC9RvsFtXg9944j1RLzaGaIRiv6ee_1ugnRlTV5YEb_tp636J4tiYJiJQRlaO5rlV4bdzWMPHfkUTaGz8PLEh55DFoWe8GH3l9FB1k9xXtV4LKbze9vt85eFojl2sC8mEwKNzKnBVaa5V2U2-wKcvSesDti8N0SWJoj4dtiyyzO3s2qU1wByCn__Jw1ShYSxmk-2ck1mpUq0KIIgbmLEfYFz04k_sGnx8tgYmCy-uQ6wErHLaUW6cU5IjdmJZIZw75oWaww-uBNE1HMDiO6Odcw"
}
2019-03-25 17:14:14,239:DEBUG:requests.packages.urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 387
2019-03-25 17:14:14,239:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Content-Type: application/json
Content-Length: 387
Boulder-Requester: 8700497
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-staging-v02.api.letsencrypt.org/acme/order/8700497/28360971
Replay-Nonce: fTVdQw6X4JRmElaDQYE9n9f-_QYtkA4NEC12A1r9LiU
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Tue, 26 Mar 2019 00:14:14 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 26 Mar 2019 00:14:14 GMT
Connection: keep-alive

{
  "status": "pending",
  "expires": "2019-04-01T23:30:09Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "domain"
    }
  ],
  "authorizations": [
    "https://acme-staging-v02.api.letsencrypt.org/acme/authz/2CQ6cVelvsmX64Sa5HuxJGohRAkrhpfTgi8e-0sTlUU"
  ],
  "finalize": "https://acme-staging-v02.api.letsencrypt.org/acme/finalize/8700497/28360971"
}
2019-03-25 17:14:14,240:DEBUG:acme.client:Storing nonce: fTVdQw6X4JRmElaDQYE9n9f-_QYtkA4NEC12A1r9LiU
2019-03-25 17:14:14,240:DEBUG:acme.client:Sending GET request to https://acme-staging-v02.api.letsencrypt.org/acme/authz/2CQ6cVelvsmX64Sa5HuxJGohRAkrhpfTgi8e-0sTlUU.
2019-03-25 17:14:14,324:DEBUG:requests.packages.urllib3.connectionpool:https://acme-staging-v02.api.letsencrypt.org:443 "GET /acme/authz/2CQ6cVelvsmX64Sa5HuxJGohRAkrhpfTgi8e-0sTlUU HTTP/1.1" 200 937
2019-03-25 17:14:14,324:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Content-Type: application/json
Content-Length: 937
Link: <https://acme-staging-v02.api.letsencrypt.org/directory>;rel="index"
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Tue, 26 Mar 2019 00:14:14 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 26 Mar 2019 00:14:14 GMT
Connection: keep-alive

{
  "identifier": {
    "type": "dns",
    "value": "domain"
  },
  "status": "pending",
  "expires": "2019-04-01T23:30:09Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/challenge/2CQ6cVelvsmX64Sa5HuxJGohRAkrhpfTgi8e-0sTlUU/281733535",
      "token": "zXnQfq-rWRigJ2XAhmDtZ8zxdSPDWzSYBo6jF__x2kU"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/challenge/2CQ6cVelvsmX64Sa5HuxJGohRAkrhpfTgi8e-0sTlUU/281733536",
      "token": "Uu7tK4a6AzH9JmTocChiVZv664hrcWnV2nhZb2j_u7A"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/challenge/2CQ6cVelvsmX64Sa5HuxJGohRAkrhpfTgi8e-0sTlUU/281733537",
      "token": "FOLK6G61-tO6vpIrUHSwGnxJHom9q2ob-K8g32izcz8"
    }
  ]
}
2019-03-25 17:14:14,325:INFO:certbot.auth_handler:Performing the following challenges:
2019-03-25 17:14:14,325:INFO:certbot.auth_handler:http-01 challenge for domain
2019-03-25 17:14:14,380:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 126, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 2119, in perform
    http_response = http_doer.perform()
  File "/usr/lib/python3/dist-packages/certbot_apache/http_01.py", line 71, in perform
    self._mod_config()
  File "/usr/lib/python3/dist-packages/certbot_apache/http_01.py", line 98, in _mod_config
    for vh in self._relevant_vhosts():
  File "/usr/lib/python3/dist-packages/certbot_apache/http_01.py", line 135, in _relevant_vhosts
    " {0}.".format(http01_port))
certbot.errors.PluginError: Unable to find a virtual host listening on port 80 which is currently needed for Certbot to prove to the CA that you control your domain. Please add a virtual host for port 80.

2019-03-25 17:14:14,380:DEBUG:certbot.error_handler:Calling registered functions
2019-03-25 17:14:14,380:INFO:certbot.auth_handler:Cleaning up challenges
2019-03-25 17:14:14,615:WARNING:certbot.renewal:Attempting to renew cert (domain) from /etc/letsencrypt/renewal/domain.conf produced an unexpected error: Unable to find a virtual host listening on port 80 which is currently needed for Certbot to prove to the CA that you control your domain. Please add a virtual host for port 80.. Skipping.
2019-03-25 17:14:14,617:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 430, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1197, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 115, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 305, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 334, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 370, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 126, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 2119, in perform
    http_response = http_doer.perform()
  File "/usr/lib/python3/dist-packages/certbot_apache/http_01.py", line 71, in perform
    self._mod_config()
  File "/usr/lib/python3/dist-packages/certbot_apache/http_01.py", line 98, in _mod_config
    for vh in self._relevant_vhosts():
  File "/usr/lib/python3/dist-packages/certbot_apache/http_01.py", line 135, in _relevant_vhosts
    " {0}.".format(http01_port))
certbot.errors.PluginError: Unable to find a virtual host listening on port 80 which is currently needed for Certbot to prove to the CA that you control your domain. Please add a virtual host for port 80.

2019-03-25 17:14:14,619:ERROR:certbot.renewal:All renewal attempts failed. The following certs could not be renewed:
2019-03-25 17:14:14,619:ERROR:certbot.renewal:  /etc/letsencrypt/live/domain/fullchain.pem (failure)
2019-03-25 17:14:14,619:INFO:certbot.hooks:Running post-hook command: /etc/letsencrypt/renewal-hooks/post/post.sh
2019-03-25 17:14:14,802:INFO:certbot.hooks:Output from post.sh:
Site 000-default disabled.
To activate the new configuration, you need to run:
  service apache2 reload

2019-03-25 17:14:14,803:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.26.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1276, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python3/dist-packages/certbot/renewal.py", line 455, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
certbot.errors.Error: 1 renew failure(s), 0 parse failure(s)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

Pre-hook script at /etc/letsencrypt/renewal-hooks/pre/pre.sh
#!/bin/sh
a2ensite 000-default
service apache2 reload
sleep 2

Post-hook script at /etc/letsencrypt/renewal-hooks/post/post.sh
#!/bin/sh
a2dissite 000-default
service apache2 reload

apache2 00-default block: 
<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html
        ServerName domain

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>

When I manually run pre.sh then run --dry-run it works prefectly as intended i.e I already manually enable the port 80 virtual host and run certbot renew --dry-run

**Comment by schoen** [comment]
Hi @kdizzay,

Thanks for reporting this problem. Do you think you could try increasing the `sleep 2` to something much larger like `sleep 20` just to make sure that the problem isn't somehow related to the Apache restart process here?

**Comment by kdizzay** [comment]
Thanks for responding @schoen 

Replaced pre.sh as 
#!/bin/sh
a2ensite 000-default
sleep 10
service apache2 reload
sleep 20

Still same result

**Comment by niallor** [comment]
I have a problem that seems to be related. I am using __certbot 0.31.0__ on __Ubuntu 16.04.6 LTS__. This is the latest version available in the PPA.

In my case, the host where a cert needs renewing is usually not connected to Internet. I use a pre-hook script to start a VPS tunnel so that the renewal transaction can take place. I have a corresponding post-hook script, of course, but I'm not triggering it automatically for the time being.

I am seeing __failure to renew__ in each of the following cases.

- The pre-hook script is installed in the pre-hook directory _/etc/letsencrypt/renewal-hooks/pre/_
- The pre-hook script is not installed in the pre-hook directory, but is triggered using the `--pre-hook` option on command line.

I am seeing __successful renewal__ in each of the following cases.

- The pre-hook script is invoked separately from the command line before invoking _certbot_ using the command `certbot --dry-run renew` with whatever intervening delay results from my typing the commands separately.
- The pre-hook script and _certbot_ are invoked in a single command list, using the `&&` control operator.
- Running _certbot_ twice as follows `certbot --dry-run --pre-hook /etc/letsencrypt/renewal-hooks/available/start-ovpn-client.sh renew ; certbot --dry-run renew`

In the last case, the first run of _certbot_ fails, but sets up the VPN tunnel, and  the second run then succeeds.

**Comment by kdizzay** [comment]
Hi @niallor , 

I have been able to replicate your 4 use cases with my pre and post hook scripts exactly and the results match yours. Last case is interesting, wonder what is happening with hook behaviors.

**Comment by niallor** [comment]
Without yet having examined the code (which I'll do when I have half a day or more free), my theory is that (perhaps only a certain class of) pre-hook scripts may change the environment in ways that _certbot_ is not prepared for. In my case, the pre-hook script adds an interface, adds an IPv6 address, and sets an IPv6 default route. When _certbot_ itself invokes the pre-hook script, it may already have created a model of the network environment, which these rather fundamental changes will invalidate. When the pre-hook script is run before _certbot_ starts, then the ground isn't moving underneath it, so the problem doesn't arise. I expect I'll be looking for whether code to sense the network environment is present and is run before the hook is triggered.
