### ISSUE TITLE
OS detection - integer expression expected

### ISSUE THREAD

**Issue by tszulborski** [certbot/certbot#6912]
## My operating system is (include version):
CloudLinux 7.6

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
 wget https://dl.eff.org/certbot-auto
 chmod a+x ./certbot-auto

## I ran this command and it produced this output:
 /bin/certbot-auto renew
/bin/certbot-auto: line 754: [: 7.6: integer expression expected
/bin/certbot-auto: line 754: [: 7.6: integer expression expected

## Certbot's behavior differed from what I expected because:
There is some problem with OS detection.

**Comment by larkov** [comment]
Having the same problem on fedora 7.6

**Comment by ctgraham** [comment]
Trace of the issue:

```
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="6.8"
ID="ol"
VERSION_ID="6.8"
PRETTY_NAME="Oracle Linux Server 6.8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:6:8:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 6"
ORACLE_BUGZILLA_PRODUCT_VERSION=6.8
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=6.8
```

```
# bash -x /usr/local/bin/certbot-auto
+ set -e
+ '[' -z /root ']'
+ '[' -z '' ']'
+ XDG_DATA_HOME=/root/.local/share
+ '[' -z '' ']'
+ export OLD_VENV_PATH=/root/.local/share/letsencrypt
+ OLD_VENV_PATH=/root/.local/share/letsencrypt
+ export VENV_PATH=/opt/eff.org/certbot/venv
+ VENV_PATH=/opt/eff.org/certbot/venv
+ VENV_BIN=/opt/eff.org/certbot/venv/bin
+ BOOTSTRAP_VERSION_PATH=/opt/eff.org/certbot/venv/certbot-auto-bootstrap-version.txt
+ LE_AUTO_VERSION=0.33.0
++ basename /usr/local/bin/certbot-auto
+ BASENAME=certbot-auto
+ USAGE='Usage: certbot-auto [OPTIONS]
A self-updating wrapper script for the Certbot ACME client. When run, updates
to both this script and certbot will be downloaded and installed. After
ensuring you have the latest versions installed, certbot will be invoked with
all arguments you have provided.

Help for certbot itself cannot be provided until it is installed.

  --debug                                   attempt experimental installation
  -h, --help                                print this help
  -n, --non-interactive, --noninteractive   run without asking for user input
  --no-bootstrap                            do not install OS dependencies
  --no-self-upgrade                         do not download updates
  --os-packages-only                        install OS dependencies and exit
  --install-only                            install certbot, upgrade if needed, and exit
  -v, --verbose                             provide more output
  -q, --quiet                               provide only update/error output;
                                            implies --non-interactive

All arguments are accepted and forwarded to the Certbot client when run.'
+ export CERTBOT_AUTO=/usr/local/bin/certbot-auto
+ CERTBOT_AUTO=/usr/local/bin/certbot-auto
+ '[' certbot-auto = letsencrypt-auto ']'
+ '[' '' = 1 -o '' = 1 ']'
+ command -v command
+ export 'EXISTS=command -v'
+ EXISTS='command -v'
+ '[' '' = --cb-auto-has-root ']'
+ SetRootAuthMechanism
+ SUDO=
+ '[' -n '' ']'
++ id -u
+ test 0 -ne 0
+ '[' -n '' ']'
+ MIN_PYTHON_VERSION=2.7
++ sed 's/\.//'
++ echo 2.7
+ MIN_PYVER=27
+ BOOTSTRAP_DEB_COMMON_VERSION=1
+ BOOTSTRAP_RPM_COMMON_VERSION=1
+ BOOTSTRAP_RPM_PYTHON3_VERSION=1
+ BOOTSTRAP_SUSE_COMMON_VERSION=1
+ BOOTSTRAP_ARCH_COMMON_VERSION=1
+ BOOTSTRAP_GENTOO_COMMON_VERSION=1
+ BOOTSTRAP_FREEBSD_VERSION=1
+ BOOTSTRAP_MAC_VERSION=1
+ BOOTSTRAP_SMARTOS_VERSION=1
+ BOOTSTRAP_MAGEIA_COMMON_VERSION=1
+ '[' -f /etc/debian_version ']'
+ '[' -f /etc/mageia-release ']'
+ '[' -f /etc/redhat-release ']'
+ prev_le_python=
+ unset LE_PYTHON
+ DeterminePythonVersion NOCRASH
+ '[' '' = 1 ']'
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v ''
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v python2.7
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v python27
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v python2
+ break
+ '[' 0 '!=' 0 ']'
++ sed 's/\.//'
++ cut -d. -f1,2
++ cut '-d ' -f 2
++ python2 -V
+ PYVER=26
+ '[' 26 -lt 27 ']'
+ '[' NOCRASH '!=' NOCRASH ']'
++ . /etc/os-release
++ echo ol
+ RPM_DIST_NAME=ol
++ . /etc/os-release
++ echo 6.8
+ RPM_DIST_VERSION=6.8
+ '[' ol = fedora -a 6.8 -ge 29 -o 26 -eq 26 ']'
/usr/local/bin/certbot-auto: line 754: [: 6.8: integer expression expected
+ BOOTSTRAP_VERSION='BootstrapRpmCommon 1'
+ LE_PYTHON=
+ '[' '' = 1 ']'
+ '[' '' = --le-auto-phase2 ']'
+ export PHASE_1_VERSION=0.33.0
+ PHASE_1_VERSION=0.33.0
+ '[' '!' -f /opt/eff.org/certbot/venv/bin/letsencrypt ']'
+ '[' '' = 1 ']'
+ '[' '' '!=' 1 ']'
++ TempDir
++ mktemp -d
+ TEMP_DIR=/tmp/tmp.Q73Vvd5ofE
+ trap 'rm -rf "$TEMP_DIR"' EXIT
+ cat
+ DeterminePythonVersion NOCRASH
+ '[' '' = 1 ']'
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v ''
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v python2.7
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v python27
+ for LE_PYTHON in '"$LE_PYTHON"' python2.7 python27 python2 python
+ command -v python2
+ break
+ '[' 0 '!=' 0 ']'
++ sed 's/\.//'
++ cut -d. -f1,2
++ cut '-d ' -f 2
++ python2 -V
+ PYVER=26
+ '[' 26 -lt 27 ']'
+ '[' NOCRASH '!=' NOCRASH ']'
+ '[' 26 -lt 27 ']'
+ error 'WARNING: couldn'\''t find Python 2.7+ to check for updates.'
+ echo 'WARNING: couldn'\''t find Python 2.7+ to check for updates.'
WARNING: couldn't find Python 2.7+ to check for updates.
++ CompareVersions python2 0.33.0 ''
++ python2 - 0.33.0 ''
Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "/usr/lib64/python2.6/distutils/version.py", line 140, in __cmp__
    compare = cmp(self.version, other.version)
AttributeError: StrictVersion instance has no attribute 'version'
+ LE_VERSION_STATE=
+ rm -rf /tmp/tmp.Q73Vvd5ofE
```
