### ISSUE TITLE
letsencrypt更新证书报错ReadTimeout: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Read timed out. (read timeout=45)

### ISSUE THREAD

**Issue by SirBlues** [certbot/certbot#6944]
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Please read the Terms of Service at
https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf. You must
agree in order to register with the ACME server at
https://acme-v02.api.letsencrypt.org/directory
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(A)gree/(C)ancel: A
An unexpected error occurred:
ReadTimeout: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Read timed out. (read timeout=45)
Please see the logfiles in /var/log/letsencrypt for more details.

总是报超时错误，求解答

**Comment by SirBlues** [comment]
2019-04-11 14:38:06,297:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 1233, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 604, in _init_le_client
    acc, acme = _determine_account(config)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 520, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/client.py", line 179, in register
    regr = perform_registration(acme, config, tos_cb)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/client.py", line 222, in perform_registration
    return acme.new_account_and_tos(newreg, tos_cb)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/client.py", line 860, in new_account_and_tos
    return self.client.new_account(regr)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/client.py", line 606, in new_account
    response = self._post(self.directory['newAccount'], new_account)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/client.py", line 96, in _post
    return self.net.post(*args, **kwargs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/client.py", line 1201, in post
    return self._post_once(*args, **kwargs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/client.py", line 1214, in _post_once
    response = self._send_request('POST', url, data=data, **kwargs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/acme/client.py", line 1117, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Read timed out. (read timeout=45)
"letsencrypt.log" 115L, 7840C                                                                
日志里的报错

**Comment by bmw** [comment]
Certbot failed to get a response from Let's Encrypt's server. If you've tried running Certbot again and you're still having trouble, I recommend you create a post at https://community.letsencrypt.org where there is a large community of people familiar with the project that can help you try to debug any network issues you're having.
