### ISSUE TITLE
Route53 plugin gets "Throttling", "Rate exceeded". Maybe related to GET /2013-04-01/hostedzone

### ISSUE THREAD

**Issue by christopher-ursich** [certbot/certbot#6982]
## My operating system is (include version):
Ubuntu 18.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
1. `sudo add-apt-repository ppa:certbot/certbot`
1. `sudo apt install certbot python3-certbot-dns-route53`

## I ran this command and it produced this output:
`certbot certonly --dns-route53 --domains " (43 domains, in numerous hosted zones) "`

## Certbot's behavior differed from what I expected because:
I posted [this question on the community forum](https://community.letsencrypt.org/t/aws-route-53-plugin-gets-rate-exceeded-how-to-slow-down-certbot/91463), but didn't get an answer.

I am attempting to generate a single certificate with SAN entries for numerous domains, spread across numerous Route 53 hosted zones.  Certbot is hitting the error shown below, indicating that it is exceeding [Route 53's rate limits](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests).

The output is like:
```
Plugins selected: Authenticator dns-route53, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for dom1.tld
dns-01 challenge for dom2.tld
 ...
dns-01 challenge for dom43.tld
Cleaning up challenges
Encountered exception during recovery: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot_dns_route53/dns_route53.py", line 49, in _perform
    self._wait_for_change(change_id)
  File "/usr/lib/python3/dist-packages/certbot_dns_route53/dns_route53.py", line 131, in _wait_for_change
    response = self.r53.get_change(Id=change_id)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 324, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python3/dist-packages/botocore/client.py", line 622, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Throttling) when calling the GetChange operation (reached max retries: 4): Rate exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
    resp = self._solve_challenges(aauthzrs)
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges
    resp = self.auth.perform(all_achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python3/dist-packages/certbot_dns_route53/dns_route53.py", line 52, in _perform
    raise errors.PluginError("\n".join([str(e), INSTRUCTIONS]))
certbot.errors.PluginError: An error occurred (Throttling) when calling the GetChange operation (reached max retries: 4): Rate exceeded
To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/error_handler.py", line 108, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 323, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/lib/python3/dist-packages/certbot_dns_route53/dns_route53.py", line 56, in _cleanup
    self._change_txt_record("DELETE", validation_domain_name, validation)
  File "/usr/lib/python3/dist-packages/certbot_dns_route53/dns_route53.py", line 97, in _change_txt_record
    rrecords.remove(challenge)
ValueError: list.remove(x): x not in list
An error occurred (Throttling) when calling the GetChange operation (reached max retries: 4): Rate exceeded
To use certbot-dns-route53, configure credentials as described at https://boto3.readthedocs.io/en/latest/guide/configuration.html#best-practices-for-configuring-credentials and add the necessary permissions for Route53 access.
```

As proposed in [a similar community posting](https://community.letsencrypt.org/t/issue-with-aws-api-when-using-certbot-dns-route53-with-many-domains/75259), I attempted to slow down Certbot by modifying `dns_route53.py`.  I quadrupled the sleep time from 5 to 20:
```
def _wait_for_change(self, change_id):
    """Wait for a change to be propagated to all Route53 DNS servers.
       https://docs.aws.amazon.com/Route53/latest/APIReference/API_GetChange.html
    """
    for unused_n in range(0, 120):    # I could increase this number of tries.
        response = self.r53.get_change(Id=change_id)
        if response["ChangeInfo"]["Status"] == "INSYNC":
            return
        time.sleep(20)   # I increased this from 5 to 20.
```

When I run Certbot with `-v` verbosity, I see that it seems to be successfully waiting until all the hosted zones are "INSYNC."  Furthermore, I interpret `Cleaning up challenges` to be an indication that the records got there and were used.  Increasing the sleep time or number of tries will therefore not help, and it may never have been the problem.  _After_ that, however, Certbot hits the error.  Verbose output looks like the following.   (I am showing the first 2 instances of the error, but there are many.)
```
dns-01 challenge for dom43.tld
Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/route53/2013-04-01/paginators-1.json
Event before-parameter-build.route53.ListHostedZones: calling handler <function fix_route53_ids at 0x7f804ee9ff28>
Event before-parameter-build.route53.ListHostedZones: calling handler <function generate_idempotent_uuid at 0x7f804ee9ae18>
Making request for OperationModel(name=ListHostedZones) (verify_ssl=True) with params: {'url_path': '/2013-04-01/hostedzone', 'query_string': {}, 'method': 'GET', 'headers': {'User-Agent': 'Boto3/1.4.2 Python/3.6.7 Linux/4.15.0-47-generic Botocore/1.8.48'}, 'body': b'', 'url': 'https://route53.amazonaws.com/2013-04-01/hostedzone', 'context': {'client_region': 'aws-global', 'client_config': <botocore.config.Config object at 0x7f804eba0160>, 'has_streaming_input': False, 'auth_type': None}}
Event request-created.route53.ListHostedZones: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f804eba00f0>>
Event choose-signer.route53.ListHostedZones: calling handler <function set_operation_specific_signer at 0x7f804ee9ad08>
Calculating signature using v4 auth.
CanonicalRequest:
GET
/2013-04-01/hostedzone

host:route53.amazonaws.com
x-amz-date:20190420T205610Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
StringToSign:
AWS4-HMAC-SHA256
20190420T205610Z
20190420/us-east-1/route53/aws4_request
a0d20aa16f42dc2c95f68f1ae6bae706d9d9e83838436086f502744a2f9aa7d3
Signature:
2f9b8634d9a54d33ad5f913634a428a5ccc62d40921b61814f9984f3fd8fb3e1
Sending http request: <PreparedRequest [GET]>
Starting new HTTPS connection (1): route53.amazonaws.com
https://route53.amazonaws.com:443 "GET /2013-04-01/hostedzone HTTP/1.1" 400 255
Response headers: {'x-amzn-RequestId': 'ba355fed-63ae-11e9-8c0b-abde8334fe9c', 'Content-Type': 'text/xml', 'Content-Length': '255', 'Date': 'Sat, 20 Apr 2019 20:56:10 GMT', 'Connection': 'close'}
Response body:
b'<?xml version="1.0"?>\n<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>ba355fed-63ae-11e9-8c0b-abde8334fe9c</RequestId></ErrorResponse>'
Event needs-retry.route53.ListHostedZones: calling handler <botocore.retryhandler.RetryHandler object at 0x7f804eba0588>
retry needed: matching HTTP status and error code seen: 400, Throttling
Retry needed, action of: 0.47712741813508075
Response received to retry, sleeping for 0.47712741813508075 seconds
Event request-created.route53.ListHostedZones: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f804eba00f0>>
Event choose-signer.route53.ListHostedZones: calling handler <function set_operation_specific_signer at 0x7f804ee9ad08>
Calculating signature using v4 auth.
CanonicalRequest:
GET
/2013-04-01/hostedzone

host:route53.amazonaws.com
x-amz-date:20190420T205611Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
StringToSign:
AWS4-HMAC-SHA256
20190420T205611Z
20190420/us-east-1/route53/aws4_request
7e490d6a0098fb5a8f3c0a0d80189ea3286d56ca9bd6e038ff490c96f97b88aa
Signature:
63c5d64ff86c537b2c50cbae6d641d5a3e98ce58a710c111e5721b22a7dbe5fa
Sending http request: <PreparedRequest [GET]>
Resetting dropped connection: route53.amazonaws.com
https://route53.amazonaws.com:443 "GET /2013-04-01/hostedzone HTTP/1.1" 400 255
Response headers: {'x-amzn-RequestId': 'ba8c3253-63ae-11e9-bb48-99e3c6fc8554', 'Content-Type': 'text/xml', 'Content-Length': '255', 'Date': 'Sat, 20 Apr 2019 20:56:11 GMT', 'Connection': 'close'}
Response body:
b'<?xml version="1.0"?>\n<ErrorResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><Error><Type>Sender</Type><Code>Throttling</Code><Message>Rate exceeded</Message></Error><RequestId>ba8c3253-63ae-11e9-bb48-99e3c6fc8554</RequestId></ErrorResponse>'
Event needs-retry.route53.ListHostedZones: calling handler <botocore.retryhandler.RetryHandler object at 0x7f804eba0588>
retry needed: matching HTTP status and error code seen: 400, Throttling
Retry needed, action of: 0.12256372658444015
Response received to retry, sleeping for 0.12256372658444015 seconds
Event request-created.route53.ListHostedZones: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f804eba00f0>>
Event choose-signer.route53.ListHostedZones: calling handler <function set_operation_specific_signer at 0x7f804ee9ad08>
```

The plugin seems to be repeatedly performing `GET /2013-04-01/hostedzone`, either with too many requests-per-time or bytes-per-time.  I am not a developer, so my ability to understand what Certbot is trying to do at this point in the code is limited.  I do think that this is a bug, however, in the Route 53 plugin or possibly even in Boto.

**Comment by christopher-ursich** [comment]
The request for `/2013-04-01/hostedzone` does not always fail.  When it does succeed, the response is large.  Here I am showing a sequence of 2 request/replies:
```
CanonicalRequest:
GET
/2013-04-01/hostedzone

host:route53.amazonaws.com
x-amz-date:20190420T205615Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
StringToSign:
AWS4-HMAC-SHA256
20190420T205615Z
20190420/us-east-1/route53/aws4_request
67bb6642f47a662b12943d0546da08d426cd7feab43537b39603ffecffbcc333
Signature:
829c362d971d716d47e512f8a543e8542f97016496e4b094b3a43d3833cc0576
Sending http request: <PreparedRequest [GET]>
Resetting dropped connection: route53.amazonaws.com
https://route53.amazonaws.com:443 "GET /2013-04-01/hostedzone HTTP/1.1" 200 30872
Response headers: {'x-amzn-RequestId': 'bce58b2d-63ae-11e9-9553-3357063d8536', 'Content-Type': 'text/xml', 'Content-Length': '30872', 'vary': 'accept-encoding', 'Date': 'Sat, 20 Apr 2019 20:56:15 GMT'}
Response body:
b'<?xml version="1.0"?>\n<ListHostedZonesResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><HostedZones><HostedZone><Id>/hostedzon
```
**... 30,500+ characters edited out from the middle of the first response ...**
```
ne></Config><ResourceRecordSetCount>4</ResourceRecordSetCount></HostedZone></HostedZones><IsTruncated>true</IsTruncated><NextMarker>Z3JYSAIBVRPGN2</NextMarker><MaxItems>100</MaxItems></ListHostedZonesResponse>'
Event needs-retry.route53.ListHostedZones: calling handler <botocore.retryhandler.RetryHandler object at 0x7f804eba0588>
No retry needed.
Event before-parameter-build.route53.ListHostedZones: calling handler <function fix_route53_ids at 0x7f804ee9ff28>
Event before-parameter-build.route53.ListHostedZones: calling handler <function generate_idempotent_uuid at 0x7f804ee9ae18>
Making request for OperationModel(name=ListHostedZones) (verify_ssl=True) with params: {'url_path': '/2013-04-01/hostedzone', 'query_string': {'marker': 'Z3JYSAIBVRPGN2'}, 'method': 'GET', 'headers': {'User-Agent': 'Boto3/1.4.2 Python/3.6.7 Linux/4.15.0-47-generic Botocore/1.8.48'}, 'body': b'', 'url': 'https://route53.amazonaws.com/2013-04-01/hostedzone?marker=Z3JYSAIBVRPGN2', 'context': {'client_region': 'aws-global', 'client_config': <botocore.config.Config object at 0x7f804eba0160>, 'has_streaming_input': False, 'auth_type': None}}
Event request-created.route53.ListHostedZones: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f804eba00f0>>
Event choose-signer.route53.ListHostedZones: calling handler <function set_operation_specific_signer at 0x7f804ee9ad08>
Calculating signature using v4 auth.
CanonicalRequest:
GET
/2013-04-01/hostedzone
marker=Z3JYSAIBVRPGN2
host:route53.amazonaws.com
x-amz-date:20190420T205615Z

host;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
StringToSign:
AWS4-HMAC-SHA256
20190420T205615Z
20190420/us-east-1/route53/aws4_request
14d8b2695c7ba76edd623db29c8ed83da68c696c39a3624c50d069fddb156536
Signature:
8f5c4f1dee19ec33fb3a92ce4d4894135d707dd5fca32804315ffa6c8a000b0e
Sending http request: <PreparedRequest [GET]>
https://route53.amazonaws.com:443 "GET /2013-04-01/hostedzone?marker=Z3JYSAIBVRPGN2 HTTP/1.1" 200 30869
Response headers: {'x-amzn-RequestId': 'bcfb362e-63ae-11e9-9553-3357063d8536', 'Content-Type': 'text/xml', 'Content-Length': '30869', 'vary': 'accept-encoding', 'Date': 'Sat, 20 Apr 2019 20:56:15 GMT'}
Response body:
```
etc.

I notice that there _is_ some "chunking" of the response.  Notice that the first response ends in `<IsTruncated>true</IsTruncated><NextMarker>Z3JYSAIBVRPGN2</NextMarker><MaxItems>100</MaxItems></ListHostedZonesResponse>` and that the next query is for `https://route53.amazonaws.com/2013-04-01/hostedzone?marker=Z3JYSAIBVRPGN2`.

For whatever reason, this flow control is apparently not enough to prevent the Throttling/ Rate Exceeded problem.

**Comment by schoen** [comment]
Hi @christopher-ursich,

The "Cleaning up challenges" step *also* makes DNS API calls, because it asks the DNS API to delete the TXT records that were used during the challenge. Is it possible that the advice that you received on the forum added an appropriate delay to the calls that are used in satisfying the challenges, but not to the subsequent calls that are used in undoing them afterward?

**Comment by christopher-ursich** [comment]
The other article wasn't directed to me; it just seemed related.  You are correct that it doesn't mention adding delays to the deletion step.

To accomplish that, I inserted a 30-second delay at the top of the record-changing function:
```
def _change_txt_record(self, action, validation_domain_name, validation):
        time.sleep(30)
```
(My modification to `_wait_for_change` is still in place.)  My overall Certbot run still hit a throttling error, seemingly related to listing the hosted zones.

Next I tried adding delay where that gets called:
```
def _find_zone_id_for_domain(self, domain):
        """Find the zone id responsible a given FQDN.

           That is, the id for the zone whose name is the longest parent of the
           domain.
        """
        paginator = self.r53.get_paginator("list_hosted_zones")
        zones = []
        target_labels = domain.rstrip(".").split(".")
        for page in paginator.paginate():
            time.sleep(26)
```
I still get the same error, even with all 3 delays in place.

**Comment by christopher-ursich** [comment]
I further modified `_find_zone_id_for_domain`, this time to configure the paginator to send less data at a time.  I also increased the sleep time.
`
    def _find_zone_id_for_domain(self, domain):
        """Find the zone id responsible a given FQDN.

           That is, the id for the zone whose name is the longest parent of the
           domain.
        """
        paginator = self.r53.get_paginator("list_hosted_zones")
        response_iterator = paginator.paginate(
                PaginationConfig={
                    'PageSize': 10
                })
        zones = []
        target_labels = domain.rstrip(".").split(".")
        for page in response_iterator:
            time.sleep(56)
            for zone in page["HostedZones"]:
`
The overall process still errored out.

**Comment by johnegrosjean** [comment]
Just had same issue here, would be great if certbot included some API request rate limiting to prevent or at least recover from this error.

**Comment by christopher-ursich** [comment]
This is no longer an issue for me, so I will close this GitHub issue.
