### ISSUE TITLE
AuthorizationError: Some challenges have failed

### ISSUE THREAD

**Issue by fmunteanu** [certbot/certbot#6992]
I noticed a strange behavior into latest 0.33.1 release. If I use `--force-renewal` for a certificate with `--nginx` switch, the renewal will partially fail. However, if I run the command without `--nginx` switch and select manually option 1, everything is OK:
```
# certbot certonly --nginx --cert-name rpm.axivo.com --force-renewal
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for rpm.axivo.com
Waiting for verification...
Challenge failed for domain rpm.axivo.com
http-01 challenge for rpm.axivo.com
Cleaning up challenges
Some challenges have failed.

Domain: rpm.axivo.com
Type:   unauthorized
Detail: Invalid response from http://rpm.axivo.com/.well-known/acme-challenge/jhtigdESTyOhyqjuBMkHOKTPGR6pGJ3ce62lQ5yxRi8 [2607:5300:60:21a0::10]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n"

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address.
2019-04-25 13:15:46,197:DEBUG:certbot.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 90, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 154, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
AuthorizationError: Some challenges have failed.

2019-04-25 13:15:46,197:DEBUG:certbot.error_handler:Calling registered functions
2019-04-25 13:15:46,197:INFO:certbot.auth_handler:Cleaning up challenges
2019-04-25 13:16:12,764:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.33.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1364, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1249, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 115, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/renewal.py", line 308, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 349, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 385, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 90, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/lib/python2.7/site-packages/certbot/auth_handler.py", line 154, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
AuthorizationError: Some challenges have failed.
```

Without `--nginx` switch:
```
# certbot certonly --cert-name rpm.axivo.com --force-renewal
Saving debug log to /var/log/letsencrypt/letsencrypt.log

How would you like to authenticate with the ACME CA?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: Nginx Web Server plugin (nginx)
2: Spin up a temporary webserver (standalone)
3: Place files in webroot directory (webroot)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-3] then [enter] (press 'c' to cancel): 1
Plugins selected: Authenticator nginx, Installer None
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for rpm.axivo.com
Waiting for verification...
Cleaning up challenges

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/rpm.axivo.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/rpm.axivo.com/privkey.pem
   Your cert will expire on 2019-07-24. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```

**Comment by bmw** [comment]
Thanks for opening an issue!

In order to properly debug this though, we need more information from our issue template. Can you please answer the questions at https://github.com/certbot/certbot/blob/master/ISSUE_TEMPLATE.md and in particular provide full logs of both runs as well as the relevant nginx server block for `rpm.axivo.com`.

**Comment by fmunteanu** [comment]
I've built the RPMs for CentOS 7.6:
```
# uname -a
Linux chronos.axivo.com 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
# yum -q list *certbot*
Installed Packages
certbot.noarch                   0.33.1-1.el7     @axivo
python2-certbot.noarch           0.33.1-1.el7     @axivo
python2-certbot-nginx.noarch     0.33.1-1.el7     @axivo
# cat /etc/nginx/conf.d/default.conf
server {
    listen                          80 default_server;
    listen                          [::]:80 default_server;
    server_name                     _;

    access_log                      off;
    error_log                       /var/log/nginx/default.error.log error;

    location /.well-known/acme-challenge {
        default_type                text/plain;
        root                        /usr/share/nginx/html;
    }

    location / {
        return                      301 https://$host$request_uri;
    }
}
```
As I said, the only issue is when I use specifically the switch `--nginx`, otherwise I can renew, create etc certificates without issues.

**Comment by bmw** [comment]
> The only issue is when I use specifically the switch --nginx, otherwise I can renew, create etc certificates without issues.

I understand, but I'm unable to reproduce this problem so seeing Certbot's logs should help us properly debug this. Logs are stored in `/var/log/letsencrypt` by default. You should free to redact domains, e-mail and IP addresses as you see fit.

**Comment by fmunteanu** [comment]
I have no idea, now it works, I have not changed anything into above configuration:
```
# certbot certonly --nginx --cert-name rpm.axivo.com --force-renewal
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Renewing an existing certificate

IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/rpm.axivo.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/rpm.axivo.com/privkey.pem
   Your cert will expire on 2019-07-26. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot
   again. To non-interactively renew *all* of your certificates, run
   "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le
```
