### ISSUE TITLE
letsencrypt-auto Creating virtualenv failed.

### ISSUE THREAD

**Issue by yaoya0111** [certbot/certbot#6997]
## My operating system is (include version):
`CentOS Linux release 7.6.1810 (Core) `

python : `2.7.5`

pip:`pip 19.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)`

virtualenv : `15.1.0`

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`git clone` this repository and  `certbot-auto`  same failed message

## I ran this command and it produced this output:
`./letsencrypt-auto certonly -d www.example.com`

## Certbot's behavior differed from what I expected because:
```
Bootstrapping dependencies for RedHat-based OSes... (you can skip this with --no-bootstrap)
yum is /usr/bin/yum
yum is hashed (/usr/bin/yum)
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * elrepo: mirrors.neusoft.edu.cn
Package gcc-4.8.5-36.el7_6.1.x86_64 already installed and latest version
Package augeas-libs-1.4.0-6.el7_6.1.x86_64 already installed and latest version
Package 1:openssl-1.0.2k-16.el7_6.1.x86_64 already installed and latest version
Package 1:openssl-devel-1.0.2k-16.el7_6.1.x86_64 already installed and latest version
Package libffi-devel-3.0.13-18.el7.x86_64 already installed and latest version
Package redhat-rpm-config-9.1.0-87.el7.centos.noarch already installed and latest version
Package ca-certificates-2018.2.22-70.0.el7_5.noarch already installed and latest version
Package python-devel-2.7.5-77.el7_6.x86_64 already installed and latest version
Package python-virtualenv-15.1.0-2.el7.noarch already installed and latest version
Package python-tools-2.7.5-77.el7_6.x86_64 already installed and latest version
Package python2-pip-8.1.2-8.el7.noarch already installed and latest version
Nothing to do
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 2327, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python2.7/site-packages/virtualenv.py", line 796, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /opt/eff.org/certbot/venv/bin/python2.7 - setuptools pip wheel failed with error code 1
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 19, in create_venv
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--no-site-packages', '--python', '/usr/bin/python2.7', '/opt/eff.org/certbot/venv']' returned non-zero exit status 
```
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
there is empty folder in `var/log/letsencrypt/`

**Comment by yaoya0111** [comment]
`/opt/eff.org/certbot/venv/lib/python2.7/site-packages` folder is empty.

**Comment by yaoya0111** [comment]
i had solved this problem use another tools.

**Comment by stevennt** [comment]
How did you solve this problem? @yaoya0111

**Comment by yaoya0111** [comment]
@stevennt  [here is a tutorial of acme sh used in let's encrypt](https://kb.virtubox.net/knowledgebase/install-lets-encrypt-ssl-certificates-acme-sh/)  and [here is acme sh's github repository ](https://github.com/Neilpang/acme.sh)
