### ISSUE TITLE
v0.27.1 exec fail,  The 'ndg-httpsclient; extra == "security"' distribution was not found and is required by requests

### ISSUE THREAD

**Issue by pgnd** [certbot/certbot#6998]
exec'ing an previously working & recently upgraded
```
	certbot --version
		certbot 0.27.1
```
on
```
	lsb_release -rd
		Description:    openSUSE Leap 15.0
		Release:        15.0
```
failed with
```
	2019-04-28 15:27:13,130:DEBUG:certbot.log:Exiting abnormally:
	Traceback (most recent call last):
	  File "/usr/bin/certbot", line 11, in <module>
	    sys.exit(main())
	  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 1338, in main
	    plugins = plugins_disco.PluginsRegistry.find_all()
	  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 206, in find_all
	    plugin_ep = PluginEntryPoint(entry_point)
	  File "/usr/lib/python3.6/site-packages/certbot/plugins/disco.py", line 52, in __init__
	    self.plugin_cls = entry_point.load()
	  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2407, in load
	    self.require(*args, **kwargs)
	  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2430, in require
	    items = working_set.resolve(reqs, env, installer, extras=self.extras)
	  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
	    raise DistributionNotFound(req, requirers)
	pkg_resources.DistributionNotFound: The 'ndg-httpsclient; extra == "security"' distribution was not found and is required by requests
	2019-04-28 15:27:13,131:ERROR:certbot.log:An unexpected error occurred:
```
installing
```
	zypper in python3-ndg-httpsclient
```
cures the problem

this seems a possible return of

	https://github.com/certbot/certbot/issues/4708

but for python3

**Comment by bmw** [comment]
I can't seem to reproduce this in the [opensuse leap 15.0 docker image](https://hub.docker.com/r/opensuse/leap). It also looks like Certbot 0.30.2 is the version currently available in opensuse's repos.

I suspect either a recent update fixed these problems or you have packages installed through other package managers than `zypper` such as `pip` which can corrupt the Python packages on your operating system causing these problems.

Because of this, I'm closing this issue, but if you think I missed something or you're able to provide instructions on how to reproduce this on a clean install of opensuse, please let me know!
