### ISSUE TITLE
Ubuntu18.04 No module named 'six'

### ISSUE THREAD

**Issue by fzxiao233** [certbot/certbot#7024]
I try to use 'pip install six' and 'apt install python3-six'
It's display 'Already installed'

## Certbot's behavior differed from what I expected because:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 9, in <module>
    import configobj
  File "/usr/lib/python3/dist-packages/configobj.py", line 22, in <module>
    import six

**Comment by joohoi** [comment]
Hi! This looks like a conflict of Python dependencies in your system. This commonly happens when some python packages are installed directly from pypi using pip, and other packages are shipped with distribution packaging (apt). 

May I suggest you to turn to [Let's Encrypt community forums](https://community.letsencrypt.org/), as people there are more likely to be able to help you to identify and fix the exact conflict you are facing.

**Comment by fzxiao233** [comment]
Thank you!
