### ISSUE TITLE
certbot-apache fails on a fresh install of httpd on RHEL 8

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7273]
## My operating system is (include version):

RHEL 8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2019-07-26 19:05:42,605:DEBUG:certbot.main:certbot version: 0.37.0.dev0
2019-07-26 19:05:42,607:DEBUG:certbot.main:Arguments: ['-v', '--debug', '--text', '--agree-dev-preview', '--agree-tos', '--renew-by-default', '--redirect', '--register-unsafely-without-email', '--domain', 'ec2-3-83-206-109.compute-1.amazonaws.com', '--server', 'http://10.0.0.232:4000/directory']
2019-07-26 19:05:42,608:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-07-26 19:05:42,617:WARNING:certbot.util:Use of --agree-dev-preview is deprecated.
2019-07-26 19:05:42,634:DEBUG:certbot.log:Root logging level set at 10
2019-07-26 19:05:42,634:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2019-07-26 19:05:42,636:DEBUG:certbot.plugins.selection:Requested authenticator None and installer None
2019-07-26 19:05:42,791:ERROR:certbot.util:Error while running apachectl configtest.

AH00526: Syntax error on line 85 of /etc/httpd/conf.d/ssl.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty

2019-07-26 19:05:42,792:DEBUG:certbot.plugins.disco:Misconfigured PluginEntryPoint#apache: Error while running apachectl configtest.

AH00526: Syntax error on line 85 of /etc/httpd/conf.d/ssl.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty
Traceback (most recent call last):
  File "/home/ec2-user/letsencrypt/certbot-apache/certbot_apache/configurator.py", line 2239, in config_test
    util.run_script(self.option("conftest_cmd"))
  File "/home/ec2-user/letsencrypt/certbot/util.py", line 84, in run_script
    raise errors.SubprocessError(msg)
certbot.errors.SubprocessError: Error while running apachectl configtest.

AH00526: Syntax error on line 85 of /etc/httpd/conf.d/ssl.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/letsencrypt/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/home/ec2-user/letsencrypt/certbot-apache/certbot_apache/configurator.py", line 239, in prepare
    self.config_test()
  File "/home/ec2-user/letsencrypt/certbot-apache/certbot_apache/override_centos.py", line 58, in config_test
    super(CentOSConfigurator, self).config_test()
  File "/home/ec2-user/letsencrypt/certbot-apache/certbot_apache/configurator.py", line 2241, in config_test
    raise errors.MisconfigurationError(str(err))
certbot.errors.MisconfigurationError: Error while running apachectl configtest.

AH00526: Syntax error on line 85 of /etc/httpd/conf.d/ssl.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty

2019-07-26 19:05:42,794:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT
Initialized: <certbot_apache.override_centos.CentOSConfigurator object at 0x7fcd57c9ab70>
Prep: Error while running apachectl configtest.

AH00526: Syntax error on line 85 of /etc/httpd/conf.d/ssl.conf:
SSLCertificateFile: file '/etc/pki/tls/certs/localhost.crt' does not exist or is empty

2019-07-26 19:05:42,797:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
```

I think we need to update the code at https://github.com/certbot/certbot/blob/e6bf3fe7f81ff7651b3e8be3d530be725090ed2c/certbot-apache/certbot_apache/override_centos.py#L60 to also run `systemctl restart httpd` on RHEL 8 based systems.

cc @adferrand, @joohoi

**Comment by bmw** [comment]
Proposal to fix the problem: Always call this `systemctl` command if `systemctl` is in our PATH.

**Comment by bmw** [comment]
This also affects CentOS 8 as seen at #7397.

**Comment by rizkyarlin** [comment]
Running `systemctl restart httpd` gave me `See "systemctl status httpd.service" and "journalctl -xe" for details.` on CentOS8

**Comment by rizkyarlin** [comment]
Oh this is th RHEL issue, I'll ask at the centos issue

**Comment by bmw** [comment]
When this issue is resolved, we should be able to add CentOS/RHEL 8 to https://github.com/certbot/certbot/blob/f743dbec3a04349533735a161b650f02844b2294/tests/letstest/apache2_targets.yaml.
