### ISSUE TITLE
sudo certbot renew --dry-run : ContextualVersionConflict: (cryptography 2.1.4 (/usr/lib/python2.7/dist-packages)

### ISSUE THREAD

**Issue by marcoippolito** [certbot/certbot#7293]
In Ubuntu 18·04.02 Server Edition

   marco@pc:~$ sudo certbot renew --dry-run
    An unexpected error occurred:
    ContextualVersionConflict: (cryptography 2.1.4 (/usr/lib/python2.7/dist-packages),     
    Requirement.parse('cryptography>=2.3'), set(['PyOpenSSL']))
    Please see the logfile '/tmp/tmp2KOWbQ' for more details.

sudo nano /tmp/tmp2KOWbQ    :   

    2019-08-03 18:20:41,154:DEBUG:certbot.log:Exiting abnormally:
    Traceback (most recent call last):
      File "/usr/local/bin/certbot", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python2.7/dist-packages/certbot/main.py", line 1351, in main
        plugins = plugins_disco.PluginsRegistry.find_all()
      File "/usr/local/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 208, in find_all
        plugin_ep = PluginEntryPoint(entry_point)
      File "/usr/local/lib/python2.7/dist-packages/certbot/plugins/disco.py", line 50, in __init__
        self.plugin_cls = entry_point.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2323, in load
        self.require(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2346, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 783, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    ContextualVersionConflict: (cryptography 2.1.4 (/usr/lib/python2.7/dist-packages),   
    Requirement.parse('cryptography>=2.3'), set(['PyOpenSSL']))
    2019-08-03 18:20:41,154:ERROR:certbot.log:An unexpected error occurred:

**Comment by ohemorange** [comment]
Hey @marcoippolito ! Please first try asking for help at https://community.letsencrypt.org/. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.

**Comment by michelem09** [comment]
I have the same issue on 18.04

**Comment by ohemorange** [comment]
We've recently updated our packages on 18.04. Sometimes packages can get fetched out of order; I would recommend trying again after waiting a bit, then if the probably persists, try bringing it to the community forum: https://community.letsencrypt.org/
