### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'cert_file'

### ISSUE THREAD

**Issue by jamiek23** [certbot/certbot#7340]
Error is from a server that was previously working fine, using the DNS challenge via the Route53 plugin. Renews started failing, probably after an `apt update` - but I don't know when/what changed.

Removed the Ubuntu repository version of certbot, installed the PPA, and got exactly the same error. Using a similar setup (DNS challenge with Route53) on other servers running Debian 9, and they are working fine.

Happy to run any commands to help debug this!

## My operating system is (include version):
Ubuntu 18.04.3

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
apt - certbot PPA

## I ran this command and it produced this output:
```
root@netbox:~# certbot certonly --dns-route53 -d test.ipcortex.com -v
Root logging level set at 10
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Requested authenticator dns-route53 and installer None
Loading variable profile from defaults.
Loading variable config_file from defaults.
Loading variable credentials_file from defaults.
Loading variable data_path from defaults.
Loading variable profile from defaults.
Loading variable region from defaults.
Loading variable profile from defaults.
Loading variable ca_bundle from defaults.
Loading variable profile from defaults.
Loading variable api_versions from defaults.
Loading variable profile from defaults.
Loading variable credentials_file from defaults.
Loading variable config_file from defaults.
Loading variable profile from defaults.
Loading variable metadata_service_timeout from defaults.
Loading variable profile from defaults.
Loading variable metadata_service_num_attempts from defaults.
Loading variable profile from defaults.
Looking for credentials via: env
Looking for credentials via: assume-role
Looking for credentials via: shared-credentials-file
Looking for credentials via: custom-process
Looking for credentials via: config-file
Credentials found in config file: ~/.aws/config
Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/endpoints.json
Loading variable profile from defaults.
Event choose-service-name: calling handler <function handle_service_name_alias at 0x7fb5ad3d70d0>
Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/route53/2013-04-01/service-2.json
Event creating-client-class.route53: calling handler <function add_generate_presigned_url at 0x7fb5ad3acd90>
The s3 config key is not a dictionary type, ignoring its value of: None
Setting route53 timeout as (60, 60)
Loading JSON file: /usr/lib/python3/dist-packages/botocore/data/_retry.json
Registering retry handlers for service: route53
Single candidate plugin: * dns-route53
Description: Obtain certificates using a DNS TXT record (if you are using AWS Route53 for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-route53 = certbot_dns_route53.dns_route53:Authenticator
Initialized: <certbot_dns_route53.dns_route53.Authenticator object at 0x7fb5adcef470>
Prep: True
Selected authenticator <certbot_dns_route53.dns_route53.Authenticator object at 0x7fb5adcef470> and installer None
Plugins selected: Authenticator dns-route53, Installer None
Enter email address (used for urgent renewal and security notices) (Enter 'c' to
cancel): <REDACTED>
Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1234, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 605, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 521, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 181, in register
    acme = acme_from_config_key(config, key)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 51, in acme_from_config_key
    return acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 814, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1152, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1101, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 591, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 249, in _get_conn
    return conn or self._new_conn()
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py", line 831, in _new_conn
    **self.conn_kw)
  File "/usr/lib/python3/dist-packages/botocore/awsrequest.py", line 70, in __init__
    HTTPConnection.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/urllib3/connection.py", line 115, in __init__
    _HTTPConnection.__init__(self, *args, **kw)
TypeError: __init__() got an unexpected keyword argument 'cert_file'
An unexpected error occurred:
TypeError: __init__() got an unexpected keyword argument 'cert_file'
Please see the logfiles in /var/log/letsencrypt for more details.
```

## Certbot's behavior differed from what I expected because:
It probably shouldn't give an unexpected error, unless something is very broken on this server. (Pretty sure nothing is broken configuration wise, but happy to be corrected.)

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
(Not applicable - running in certonly mode and it doesn't get that far!)

**Comment by jamiek23** [comment]
Versions according to certbot and dpkg:
```
root@netbox:~# dpkg -l | grep certbot
ii  certbot                               0.31.0-1+ubuntu18.04.1+certbot+1  all          automatically configure HTTPS using Let's Encrypt
ii  python3-acme                          0.31.0-1+ubuntu18.04.1+certbot+1  all          ACME protocol library for Python 3
ii  python3-certbot                       0.31.0-1+ubuntu18.04.1+certbot+1  all          main library for certbot
ii  python3-certbot-dns-route53           0.23.0-2+ubuntu18.04.1+certbot+1  all          Route53 DNS plugin for Certbot
ii  python3-configobj                     5.0.6-2+ubuntu18.04.1+certbot+1   all          simple but powerful config file reader and writer for Python 3
ii  python3-future                        0.15.2-4+ubuntu18.04.1+certbot+3  all          Clean single-source support for Python 3 and 2 - Python 3.x
ii  python3-josepy                        1.1.0-2+ubuntu18.04.1+certbot+1   all          JOSE implementation for Python 3.x
ii  python3-parsedatetime                 2.4-3+ubuntu18.04.1+certbot+3     all          Python 3 module to parse human-readable date/time expressions
ii  python3-requests-toolbelt             0.8.0-1+ubuntu18.04.1+certbot+1   all          Utility belt for advanced users of python3-requests
ii  python3-zope.component                4.3.0-1+ubuntu18.04.1+certbot+3   all          Zope Component Architecture
ii  python3-zope.hookable                 4.0.4-4+ubuntu18.04.1+certbot+1   amd64        Hookable object support
ii  python3-zope.interface                4.3.2-1+ubuntu18.04.1+certbot+1   amd64        Interfaces for Python3
root@netbox:~# certbot --version
certbot 0.31.0
```

**Comment by adferrand** [comment]
Hello @jamiek23, could you provide also the version of the `botocore` and `urllib3` installed on your machine ?

**Comment by jamiek23** [comment]
Hi @adferrand - `python3-botocore` is at 1.8.48+repack-1, `python3-urllib3` is at 1.22-1ubuntu0.18.04.1.

`dpkg -l` output for reference:
```
root@netbox:~# dpkg -l | grep botocore
ii  python3-botocore                      1.8.48+repack-1                   all          Low-level, data-driven core of boto 3 (Python 3)
root@netbox:~# dpkg -l | grep urllib3
ii  python3-urllib3                       1.22-1ubuntu0.18.04.1             all          HTTP library with thread-safe connection pooling for Python3
```

**Comment by adferrand** [comment]
Thanks for your information! I reproduced your environment using a docker of Ubuntu 18.04.3, and PPA repository to install Certbot.

Even if I do not have valid AWS credentials, I could go beyond your point, until error indicating my credentials are not valid. I think you have a problem with the `request` module, or one related to HTTP connections, that is on an invalid version.

I give you the relevant list of packages installed at this point, with a working Certbot using Route 53 plugin, so you can debug and fix the packages that are either missing or on incorrect version
```
ii  certbot                     0.31.0-1+ubuntu18.04.1+certbot+1  all          automatically configure HTTPS using Let's Encrypt
ii  libpython3-stdlib:amd64     3.6.7-1~18.04                     amd64        interactive high-level object-oriented language (default python3 version)
ii  libpython3.6-minimal:amd64  3.6.8-1~18.04.1                   amd64        Minimal subset of the Python language (version 3.6)
ii  libpython3.6-stdlib:amd64   3.6.8-1~18.04.1                   amd64        Interactive high-level object-oriented language (standard library, version 3.6)
ii  python3                     3.6.7-1~18.04                     amd64        interactive high-level object-oriented language (default python3 version)
ii  python3-acme                0.31.0-1+ubuntu18.04.1+certbot+1  all          ACME protocol library for Python 3
ii  python3-apt                 1.6.4                             amd64        Python 3 interface to libapt-pkg
ii  python3-asn1crypto          0.24.0-1                          all          Fast ASN.1 parser and serializer (Python 3)
ii  python3-boto3               1.4.2-1                           all          Python interface to Amazon's Web Services - Python 3.x
ii  python3-botocore            1.8.48+repack-1                   all          Low-level, data-driven core of boto 3 (Python 3)
ii  python3-certbot             0.31.0-1+ubuntu18.04.1+certbot+1  all          main library for certbot
ii  python3-certbot-dns-route53 0.23.0-2+ubuntu18.04.1+certbot+1  all          Route53 DNS plugin for Certbot
ii  python3-certifi             2018.1.18-2                       all          root certificates for validating SSL certs and verifying TLS hosts (python3)
ii  python3-cffi-backend        1.11.5-1                          amd64        Foreign Function Interface for Python 3 calling C code - runtime
ii  python3-chardet             3.0.4-1                           all          universal character encoding detector for Python3
ii  python3-configargparse      0.11.0-1                          all          replacement for argparse with config files and environment variables (Python 3)
ii  python3-configobj           5.0.6-2+ubuntu18.04.1+certbot+1   all          simple but powerful config file reader and writer for Python 3
ii  python3-cryptography        2.1.4-1ubuntu1.3                  amd64        Python library exposing cryptographic recipes and primitives (Python 3)
ii  python3-dateutil            2.6.1-1                           all          powerful extensions to the standard Python 3 datetime module
ii  python3-dbus                1.2.6-1                           amd64        simple interprocess messaging system (Python 3 interface)
ii  python3-docutils            0.14+dfsg-3                       all          text processing system for reStructuredText (implemented in Python 3)
ii  python3-future              0.15.2-4+ubuntu18.04.1+certbot+3  all          Clean single-source support for Python 3 and 2 - Python 3.x
ii  python3-gi                  3.26.1-2ubuntu1                   amd64        Python 3 bindings for gobject-introspection libraries
ii  python3-icu                 1.9.8-0ubuntu1                    amd64        Python 3 extension wrapping the ICU C++ API
ii  python3-idna                2.6-1                             all          Python IDNA2008 (RFC 5891) handling (Python 3)
ii  python3-jmespath            0.9.3-1ubuntu1                    all          JSON Matching Expressions (Python 3)
ii  python3-josepy              1.1.0-2+ubuntu18.04.1+certbot+1   all          JOSE implementation for Python 3.x
ii  python3-minimal             3.6.7-1~18.04                     amd64        minimal subset of the Python language (default python3 version)
ii  python3-mock                2.0.0-3                           all          Mocking and Testing Library (Python3 version)
ii  python3-ndg-httpsclient     0.4.4-1                           all          enhanced HTTPS support for httplib and urllib2 using PyOpenSSL for Python3
ii  python3-olefile             0.45.1-1                          all          Python module to read/write MS OLE2 files
ii  python3-openssl             17.5.0-1ubuntu1                   all          Python 3 wrapper around the OpenSSL library
ii  python3-parsedatetime       2.4-3+ubuntu18.04.1+certbot+3     all          Python 3 module to parse human-readable date/time expressions
ii  python3-pbr                 3.1.1-3ubuntu3                    all          inject useful and sensible default behaviors into setuptools - Python 3.x
ii  python3-pil:amd64           5.1.0-1                           amd64        Python Imaging Library (Python3)
ii  python3-pkg-resources       39.0.1-2                          all          Package Discovery and Resource Access using pkg_resources
ii  python3-pyasn1              0.4.2-3                           all          ASN.1 library for Python (Python 3 module)
ii  python3-pygments            2.2.0+dfsg-1                      all          syntax highlighting package written in Python 3
ii  python3-requests            2.18.4-2ubuntu0.1                 all          elegant and simple HTTP library for Python3, built for human beings
ii  python3-requests-toolbelt   0.8.0-1+ubuntu18.04.1+certbot+1   all          Utility belt for advanced users of python3-requests
ii  python3-rfc3339             1.0-4                             all          parser and generator of RFC 3339-compliant timestamps (Python 3)
ii  python3-roman               2.0.0-3                           all          module for generating/analyzing Roman numerals for Python 3
ii  python3-s3transfer          0.1.13-1                          all          Amazon S3 Transfer Manager for Python3
ii  python3-six                 1.11.0-2                          all          Python 2 and 3 compatibility library (Python 3 interface)
ii  python3-software-properties 0.96.24.32.11                     all          manage the repositories that you install software from
ii  python3-tz                  2018.3-2                          all          Python3 version of the Olson timezone database
ii  python3-urllib3             1.22-1ubuntu0.18.04.1             all          HTTP library with thread-safe connection pooling for Python3
ii  python3-zope.component      4.3.0-1+ubuntu18.04.1+certbot+3   all          Zope Component Architecture
ii  python3-zope.event          4.2.0-1                           all          Very basic event publishing system
ii  python3-zope.hookable       4.0.4-4+ubuntu18.04.1+certbot+1   amd64        Hookable object support
ii  python3-zope.interface      4.3.2-1+ubuntu18.04.1+certbot+1   amd64        Interfaces for Python3
ii  python3.6                   3.6.8-1~18.04.1                   amd64        Interactive high-level object-oriented language (version 3.6)
ii  python3.6-minimal           3.6.8-1~18.04.1                   amd64        Minimal subset of the Python language (version 3.6)
```

If despite this your issue is not solved, I invite you to submit a post on our support forum https://certbot.eff.org/support, as there is a lot of Ubuntu users that will quickly help you to find the real root cause.

**Comment by jamiek23** [comment]
Just to close the loop for anyone who happens to run into the same issue - issue was that another Python application installed via `pip3` (netbox) installed a conflicting version of `python-requests`! (My `dpkg` was pretty much identical to Adrian's, which what threw me for a little while.)

**Comment by allantinashemuzeya** [comment]
HI @jamiek23 so the solution is to remove python-request?
