### ISSUE TITLE
Path and Config Issues with Apache on RHEL6

### ISSUE THREAD

**Issue by ajcoll5** [certbot/certbot#7404]
Certbot 0.80.x is unable to detect the correct Apache settings on an up-to-date RedHat Enterprise Linux 6 server. If I manually specify the apachectl and server config paths, it will attempt to run but Apache errors out when attempting to parse "SSLCompression off" in the options-ssl-apache.conf file as this version of Apache doesn't have that feature. 

Certbot 0.37.2 when cloned from git and ran with --apache and --no-self-upgrade correctly detects the paths and is able to successfully update certs.

## My operating system is (include version):
Red Hat Enterprise Linux Server release 6.10 (Santiago)
2.6.32-754.23.1.el6.x86_64

Server version: Apache/2.2.15 (Unix)  <- with latest security patches by RedHat
Server built:   Feb 19 2018 06:33:11

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
wget https://dl.eff.org/certbot-auto

## I ran this command and it produced this output:
```
[root@sn un]# sudo ./certbot-auto --apache
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The apache plugin is not working; there may be problems with your existing configuration.
The error was: NoInstallationError('Cannot find Apache executable apache2ctl',)
```

## Certbot's behavior differed from what I expected because:
Certbot 0.80.x is unable to find the correct configuration settings on RHEL6 with Apache.

## Here is a Certbot log showing the issue (if available):
```
2019-09-26 14:37:45,101:DEBUG:certbot.main:certbot version: 0.38.0
2019-09-26 14:37:45,103:DEBUG:certbot.main:Arguments: ['--apache']
2019-09-26 14:37:45,103:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-09-26 14:37:45,173:DEBUG:certbot.log:Root logging level set at 20
2019-09-26 14:37:45,175:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2019-09-26 14:37:45,176:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2019-09-26 14:37:45,191:DEBUG:certbot.plugins.util:Can't find apache2ctl, attempting PATH mitigation by adding /usr/local/bin:/usr/local/sbin
2019-09-26 14:37:45,191:DEBUG:certbot.plugins.util:Failed to find executable apache2ctl in expanded PATH: /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/usr/local/sbin
2019-09-26 14:37:45,191:DEBUG:certbot.plugins.disco:No installation (PluginEntryPoint#apache): Cannot find Apache executable apache2ctl
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/lib64/python3.4/site-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/opt/eff.org/certbot/venv/lib64/python3.4/site-packages/certbot_apache/configurator.py", line 236, in prepare
    self._verify_exe_availability(self.option("ctl"))
  File "/opt/eff.org/certbot/venv/lib64/python3.4/site-packages/certbot_apache/configurator.py", line 342, in _verify_exe_availability
    'Cannot find Apache executable {0}'.format(exe))
certbot.errors.NoInstallationError: Cannot find Apache executable apache2ctl
2019-09-26 14:37:45,194:DEBUG:certbot.plugins.selection:No candidate plugin
2019-09-26 14:37:45,194:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
```

**Comment by bmw** [comment]
Thanks for the detailed bug report! I think this is an instance of https://github.com/certbot/certbot/issues/7402 which will be fixed in our 0.39.0 release on Tuesday next week. Because of that, I'm closing this issue, but if you think I missed something, please let me know!
