### ISSUE TITLE
luadns dns validation: Failure if "forward" entry in zone

### ISSUE THREAD

**Issue by kaifried** [certbot/certbot#7425]
## My operating system is (include version):
I tested it with fedora 29 and ubuntu 18:04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
I installed certbot and certbot-dns-luadns via pip.

## I ran this command and it produced this output:
Command:

```bash
certbot certonly  --dns-luadns --dns-luadns-credentials ./lua.ini -d ***.de
```
The output was:

```bash
Saving debug log to /home/kai/le-dns/logdir/letsencrypt.log
Plugins selected: Authenticator dns-luadns, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for ***.de
Cleaning up challenges
Encountered exception during recovery: 
Traceback (most recent call last):
  File "/home/kai/le-dns/env/lib64/python3.7/site-packages/certbot/auth_handler.py", line 69, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/home/kai/le-dns/env/lib64/python3.7/site-packages/certbot/plugins/dns_common.py", line 58, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/home/kai/le-dns/env/lib64/python3.7/site-packages/certbot_dns_luadns/dns_luadns.py", line 52, in _perform
    self._get_luadns_client().add_txt_record(domain, validation_name, validation)
  File "/home/kai/le-dns/env/lib64/python3.7/site-packages/certbot/plugins/dns_common_lexicon.py", line 43, in add_txt_record
    self.provider.create_record(type='TXT', name=record_name, content=record_content)
  File "/home/kai/le-dns/env/lib64/python3.7/site-packages/lexicon/providers/base.py", line 80, in create_record
    return self._create_record(rtype, name, content)
  File "/home/*/le-dns/env/lib64/python3.7/site-packages/lexicon/providers/luadns.py", line 45, in _create_record
    existing_records = self._list_records(rtype, name, content)
  File "/home/kai/le-dns/env/lib64/python3.7/site-packages/lexicon/providers/luadns.py", line 71, in _list_records
    'id': record['id']
KeyError: 'id'
```

## dirty fix:
remove all "forward" entries from the dns zone.  
After that, the validation work fine.

**Comment by bmw** [comment]
I'm closing this in favor of https://github.com/certbot/certbot/issues/7631.

This issue is resolved by using a new version of our dependency `dns-lexicon`. #7631 is tracking updating the version of the library we have pinned so it will be updated everywhere we have control over our dependency versions like in our Docker images.

If you're having this issue using packages provided by your OS, I'd ask your distro maintainers to update the packaged version of `dns-lexicon`.
