### ISSUE TITLE
Certbot+Apache+Define="Error Parsing variable"

### ISSUE THREAD

**Issue by Dragorn421** [certbot/certbot#7447]
Same issue as https://github.com/certbot/certbot/issues/2481

I'm using certbot and python-certbot-apache packages (apt) on Debian 10.1. Certbot version is 0.31.0. It's a fresh install

What happens :
```
# certbot --apache
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Error Parsing variable: ${VHOST_NAME}')
```

My virtual hosts indeed use Define, for example:
```
<VirtualHost *:80>
	Define VHOST_NAME www.example.com

	ServerName ${VHOST_NAME}

	ErrorLog ${APACHE_LOG_DIR}/${VHOST_NAME}/error.log
	CustomLog ${APACHE_LOG_DIR}/${VHOST_NAME}/access.log combined

	RedirectPermanent / http://some/other/place/

	UnDefine VHOST_NAME
</VirtualHost>
```

Here are the certbot logs :
```
2019-10-11 18:49:08,110:DEBUG:certbot_apache.configurator:Apache version is 2.4.38
2019-10-11 18:49:08,368:DEBUG:certbot.plugins.disco:Other error:(PluginEntryPoint#apache): Error Parsing variable: ${VHOST_NAME}
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot_apache/parser.py", line 484, in get_arg
    value = value.replace(var, self.variables[var[2:-1]])
KeyError: 'VHOST_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 132, in prepare
    self._initialized.prepare()
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 258, in prepare
    self.vhosts = self.get_virtual_hosts()
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 848, in get_virtual_hosts
    new_vhost = self._create_vhost(path)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 824, in _create_vhost
    self._add_servernames(vhost)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 774, in _add_servernames
    servername, serveraliases = self._get_vhost_names(host.path)
  File "/usr/lib/python3/dist-packages/certbot_apache/configurator.py", line 762, in _get_vhost_names
    servername = self.parser.get_arg(servername_match[-1])
  File "/usr/lib/python3/dist-packages/certbot_apache/parser.py", line 486, in get_arg
    raise errors.PluginError("Error Parsing variable: %s" % var)
certbot.errors.PluginError: Error Parsing variable: ${VHOST_NAME}
2019-10-11 18:49:08,370:DEBUG:certbot.plugins.selection:No candidate plugin
2019-10-11 18:49:08,370:DEBUG:certbot.plugins.selection:Selected authenticator None and installer None
```

**Comment by bmw** [comment]
Thanks for the detailed bug report @Dragorn421.

I think this issue may be slightly different from #2481. I was able to reproduce the problem with the latest version of Certbot and was able to workaround it by removing the line `UnDefine VHOST_NAME` (which I understand you may not be able to do).

@joohoi, please correct me if I'm wrong, but I think what's going on is our Apache parser only understands these variables by having Apache print the defined variables with a command like `apachectl -t -D DUMP_RUN_CFG`. In this case, `VHOST_NAME` is not defined outside of the vhost so it is not included in `apachectl`'s output and therefore our parser cannot expand the variable.

If this is correct, the full fix here would be properly understanding `define` statements in an Apache config.

**Comment by joohoi** [comment]
The issue here is not being aware of the state in different depths (as the not-completely-unlike-xml structure of Apache2 config goes) of the configuration, which is currently one of the larger issues we're facing, and are hoping to fix to some depth within the parser replacement process.

Currently, we're looking for `Define` statements using `apache2ctl -t -D DUMP_RUN_CFG`, which does peek into `VirtualHosts` etc, but only reports the state of active `Define` variables at the _end_ of the execution. As this `Define` gets unset in the `VirtualHost` block, it doesn't get reported back, and we're unable to see it.

The only reliable fix to the issue with the current parser would be to mimic the state by doing recursive searches, and trying to reproduce the state logic using directive and block indices. This would be an enormous amount of work, and likely won't happen as we're in the middle of replacing the underlying parser engine.

**Comment by mmolinac** [comment]
Having the same issue right now.

**Comment by bmw** [comment]
The only fix for now is to make sure your variables are included in the output of `sudo apachectl -t -D DUMP_RUN_CFG`.

If that's not possible, you may not be able to use our Apache plugin for now.

**Comment by Dragorn421** [comment]
<details>

<summary>
With Certbot 1.17.0
</summary>

```
# snap info certbot
name:      certbot
summary:   Automatically configure HTTPS using Let's Encrypt
publisher: Certbot Project (certbot-eff✓)
store-url: https://snapcraft.io/certbot
contact:   https://github.com/certbot/certbot/issues
license:   unset
description: |
  The objective of Certbot, Let's Encrypt, and the ACME (Automated
  Certificate Management Environment) protocol is to make it possible
  to set up an HTTPS server and have it automatically obtain a
  browser-trusted certificate, without any human intervention. This is
  accomplished by running a certificate management agent on the web
  server.

  This agent is used to:
    - Automatically prove to the Let's Encrypt CA that you control the website
    - Obtain a browser-trusted certificate and set it up on your web server
    - Keep track of when your certificate is going to expire, and renew it
    - Help you revoke the certificate if that ever becomes necessary.
commands:
  - certbot
services:
  certbot.renew: oneshot, enabled, inactive
snap-id:      wy7i66qPx4neXr6m9rTh7Y40h8EhtZFh
tracking:     latest/stable
refresh-date: today at 16:07 CEST
channels:
  latest/stable:    1.17.0      2021-07-06 (1280) 44MB classic
  latest/candidate: ↑
  latest/beta:      1.17.0      2021-07-06 (1280) 44MB classic
  latest/edge:      1.18.0.dev0 2021-07-30 (1338) 44MB classic
installed:          1.17.0                 (1280) 44MB classic
```

</details>

<details>

<summary>
The error looks almost identical
</summary>

```
# certbot --apache
Saving debug log to /var/log/letsencrypt/letsencrypt.log
The apache plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('Error Parsing variable: ${VHOST}')
```

`/var/log/letsencrypt/letsencrypt.log`:
```
2021-07-30 16:08:04,892:DEBUG:urllib3.connectionpool:http://localhost:None "GET /v2/connections?snap=certbot&interface=content HTTP/1.1" 200 97
2021-07-30 16:08:05,479:DEBUG:certbot._internal.main:certbot version: 1.17.0
2021-07-30 16:08:05,480:DEBUG:certbot._internal.main:Location of certbot entry point: /snap/certbot/1280/bin/certbot
2021-07-30 16:08:05,480:DEBUG:certbot._internal.main:Arguments: ['--apache', '--preconfigured-renewal']
2021-07-30 16:08:05,481:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-07-30 16:08:05,495:DEBUG:certbot._internal.log:Root logging level set at 30
2021-07-30 16:08:05,496:DEBUG:certbot._internal.plugins.selection:Requested authenticator apache and installer apache
2021-07-30 16:08:05,610:DEBUG:certbot_apache._internal.configurator:Apache version is 2.4.38
2021-07-30 16:08:05,932:DEBUG:certbot._internal.plugins.disco:Other error:(PluginEntryPoint#apache): Error Parsing variable: ${VHOST}
Traceback (most recent call last):
  File "/snap/certbot/1280/lib/python3.8/site-packages/certbot_apache/_internal/parser.py", line 594, in get_arg
    value = value.replace(var, self.variables[var[2:-1]])
KeyError: 'VHOST'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/snap/certbot/1280/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 158, in prepare
    self._initialized.prepare()  # type: ignore
  File "/snap/certbot/1280/lib/python3.8/site-packages/certbot_apache/_internal/configurator.py", line 381, in prepare
    self.vhosts = self.get_virtual_hosts()
  File "/snap/certbot/1280/lib/python3.8/site-packages/certbot_apache/_internal/configurator.py", line 1008, in get_virtual_hosts
    v1_vhosts = self.get_virtual_hosts_v1()
  File "/snap/certbot/1280/lib/python3.8/site-packages/certbot_apache/_internal/configurator.py", line 1045, in get_virtual_hosts_v1
    new_vhost = self._create_vhost(path)
  File "/snap/certbot/1280/lib/python3.8/site-packages/certbot_apache/_internal/configurator.py", line 998, in _create_vhost
    self._add_servernames(vhost)
  File "/snap/certbot/1280/lib/python3.8/site-packages/certbot_apache/_internal/configurator.py", line 948, in _add_servernames
    servername, serveraliases = self._get_vhost_names(host.path)
  File "/snap/certbot/1280/lib/python3.8/site-packages/certbot_apache/_internal/configurator.py", line 936, in _get_vhost_names
    servername = self.parser.get_arg(servername_match[-1])
  File "/snap/certbot/1280/lib/python3.8/site-packages/certbot_apache/_internal/parser.py", line 596, in get_arg
    raise errors.PluginError("Error Parsing variable: %s" % var)
certbot.errors.PluginError: Error Parsing variable: ${VHOST}
2021-07-30 16:08:05,938:DEBUG:certbot._internal.plugins.selection:No candidate plugin
2021-07-30 16:08:05,938:DEBUG:certbot._internal.plugins.selection:Selected authenticator None and installer None
```

</details>
