### ISSUE TITLE
The 'certbot==0.27.0' distribution was not found and is required

### ISSUE THREAD

**Issue by OrangeDog** [certbot/certbot#7474]
## My operating system is (include version):
Ubuntu 18.04.3

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
`apt install certbot`

## I ran this command and it produced this output:
```
Start-Date: 2019-10-30  06:39:04
Commandline: /usr/bin/unattended-upgrade -d
Upgrade: certbot:amd64 (0.23.0-1, 0.27.0-1~ubuntu18.04.1), python3-certbot:amd64 (0.23.0-1, 0.27.0-1~ubuntu18.04.1)
End-Date: 2019-10-30  06:39:07
```
```
Oct 30 06:39:04 csrf-prod1-vm systemd[1]: Starting Certbot...
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]: Traceback (most recent call last):
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:     ws.require(__requires__)
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 892, in require
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:     needed = self.resolve(parse_requirements(requirements))
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:     raise VersionConflict(dist, req).with_context(dependent_req)
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]: pkg_resources.VersionConflict: (certbot 0.23.0 (/usr/lib/python3/dist-packages), Requirement.parse('c
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]: During handling of the above exception, another exception occurred:
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]: Traceback (most recent call last):
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:   File "/usr/bin/certbot", line 6, in <module>
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:     from pkg_resources import load_entry_point
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:     @_call_aside
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:     f(*args, **kwargs)
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_w
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:     working_set = WorkingSet._build_master()
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 576, in _build_master
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:     return cls._build_from_requirements(__requires__)
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 589, in _build_from_requireme
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:     dists = ws.resolve(reqs, Environment())
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 778, in resolve
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]:     raise DistributionNotFound(req, requirers)
Oct 30 06:39:05 csrf-prod1-vm certbot[18993]: pkg_resources.DistributionNotFound: The 'certbot==0.27.0' distribution was not found and is required
Oct 30 06:39:05 csrf-prod1-vm systemd[1]: certbot.service: Main process exited, code=exited, status=1/FAILURE
Oct 30 06:39:05 csrf-prod1-vm systemd[1]: certbot.service: Failed with result 'exit-code'.
Oct 30 06:39:05 csrf-prod1-vm systemd[1]: Failed to start Certbot.
```

## Certbot's behavior differed from what I expected because:
It shouldn't fail.

## Related
#5454

**Comment by OrangeDog** [comment]
The service appears to start correctly now (several hours later).

**Comment by ohemorange** [comment]
0.23.0 is the version in bionic, and 0.27.0 is what's in bionic-updates. My best guess is some manner of server error on the Ubuntu side. But looks like it's working now, so I'm going to close.
