### ISSUE TITLE
Changing the ACME Server fails due to wrong URI handling

### ISSUE THREAD

**Issue by oregano87** [certbot/certbot#7481]
- Debian 10 (buster)
-  certbot version 0.31.0
- Please note, real domain replaced by domain.local for anonymisation

I am trying to use my own CA for issuing certificates. But if I am using the --server option the first connect works fine 
--> Sending GET request to **http://acme.domain.local/acme/directory**

but the, the next call tries to connect without FQDN. 
--> Sending HEAD request to **http://acme/new-nonce**

Complete log attached after executing this command

`sudo certbot certonly --apache --agree-tos --email ca-admin@example.com --domain www.domain.local --server http://acme.domain.local/acme/directory`

```
2019-10-31 15:25:34,731:DEBUG:certbot.main:certbot version: 0.31.0
2019-10-31 15:25:34,731:DEBUG:certbot.main:Arguments: ['--agree-tos', '--email', 'ca-admin@example.com', '--domain', 'www.domain.local', '--server', 'http://acme.domain.local/acme/directory', '--apache']
2019-10-31 15:25:34,732:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2019-10-31 15:25:34,737:DEBUG:certbot.log:Root logging level set at 20
2019-10-31 15:25:34,737:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2019-10-31 15:25:34,737:DEBUG:certbot.plugins.selection:Requested authenticator apache and installer apache
2019-10-31 15:25:34,819:DEBUG:certbot_apache.configurator:Apache version is 2.4.38
2019-10-31 15:25:35,027:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT
Initialized: <certbot_apache.override_debian.DebianConfigurator object at 0x7fd4e3450cf8>
Prep: True
2019-10-31 15:25:35,028:DEBUG:certbot.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache.entrypoint:ENTRYPOINT
Initialized: <certbot_apache.override_debian.DebianConfigurator object at 0x7fd4e3450cf8>
Prep: True
2019-10-31 15:25:35,028:DEBUG:certbot.plugins.selection:Selected authenticator <certbot_apache.override_debian.DebianConfigurator object at 0x7fd4e3450cf8> and installer <certbot_apache.override_debian.DebianConfigurator object at 0x7fd4e3450cf8>
2019-10-31 15:25:35,028:INFO:certbot.plugins.selection:Plugins selected: Authenticator apache, Installer apache
2019-10-31 15:25:35,113:DEBUG:acme.client:Sending GET request to http://acme.domain.local/acme/directory.
2019-10-31 15:25:35,115:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): acme.domain.local:80
2019-10-31 15:25:35,123:DEBUG:urllib3.connectionpool:http://acme.domain.local:80 "GET /acme/directory HTTP/1.1" 200 227
2019-10-31 15:25:35,123:DEBUG:acme.client:Received response:
HTTP 200
Server: Apache-Coyote/1.1
Link: <http://acme/directory>;rel="index"
Replay-Nonce: 4P8ltoXBxEEyCIML6tJ9Aw
Content-Type: application/json
Content-Length: 227
Date: Thu, 31 Oct 2019 14:25:35 GMT

{"newNonce":"http://acme/new-nonce","newAccount":"http://acme/new-account","newOrder":"http://acme/new-order","revokeCert":"http://acme/revoke-cert","keyChange":"http://acme/key-change","meta":{"externalAccountRequired":false}}
2019-10-31 15:25:35,123:DEBUG:acme.client:Requesting fresh nonce
2019-10-31 15:25:35,124:DEBUG:acme.client:Sending HEAD request to http://acme/new-nonce.
2019-10-31 15:25:35,124:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): acme:80
2019-10-31 15:25:35,126:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fd4e3457518>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='acme', port=80): Max retries exceeded with url: /new-nonce (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4e3457518>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1234, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 605, in _init_le_client
    acc, acme = _determine_account(config)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 521, in _determine_account
    config, account_storage, tos_cb=_tos_cb)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 183, in register
    regr = perform_registration(acme, config, tos_cb)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 226, in perform_registration
    return acme.new_account_and_tos(newreg, tos_cb)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 863, in new_account_and_tos
    return self.client.new_account(regr)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 606, in new_account
    response = self._post(self.directory['newAccount'], new_account)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 96, in _post
    return self.net.post(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1204, in post
    return self._post_once(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1215, in _post_once
    data = self._wrap_in_jws(obj, self._get_nonce(url, new_nonce_url), url, acme_version)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1192, in _get_nonce
    response = self._check_response(self.head(new_nonce_url), content_type=None)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1166, in head
    return self._send_request('HEAD', *args, **kwargs)
  File "/usr/lib/python3/dist-packages/acme/client.py", line 1120, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='acme', port=80): Max retries exceeded with url: /new-nonce (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4e3457518>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2019-10-31 15:25:35,128:ERROR:certbot.log:An unexpected error occurred:
```

**Comment by oregano87** [comment]
Also tried version 0.40.0 dev0 but with the same behavior.

**Comment by oregano87** [comment]
If hostname will changed to something else than acme it works.

**Comment by bmw** [comment]
Unless something went wrong redacting your domain from Certbot's logs, I think the problem with your ACME server. The relevant log output is:
```
2019-10-31 15:25:35,123:DEBUG:acme.client:Received response:
HTTP 200
Server: Apache-Coyote/1.1
Link: <http://acme/directory>;rel="index"
Replay-Nonce: 4P8ltoXBxEEyCIML6tJ9Aw
Content-Type: application/json
Content-Length: 227
Date: Thu, 31 Oct 2019 14:25:35 GMT

{"newNonce":"http://acme/new-nonce","newAccount":"http://acme/new-account","newOrder":"http://acme/new-order","revokeCert":"http://acme/revoke-cert","keyChange":"http://acme/key-change","meta":{"externalAccountRequired":false}}
```
Your ACME server is directing Certbot to `http://acme`.

**Comment by oregano87** [comment]
You are right. The problem was a missing configuration in the properties.
Thank you.
