### ISSUE TITLE
ImportError: No module named __future__

### ISSUE THREAD

**Issue by Linuxine** [certbot/certbot#7496]
Hi, I am using Certbot on my Centos7 for years without issue. I have python 2.7, and have installed certbot only by launching the certbot-auto script. 

But this morning, when trying to renew my certificate as usual, I got the following error :

```
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt: 
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 3, in <module>
    from __future__ import print_function
ImportError: No module named __future__
```

I don't get how, but it seems Certbot may be using the wrong version of python ? I can see the "future" package in `/opt/eff.org/certbot/venv/lib/python2.7/site-packages/future`. I can also make the  `from __future__ import print_function` when launching manually the python in `/opt/eff.org/certbot/venv/bin`,  so I am a bit lost :/

I tried to rename the eff.org folder from my /opt to force the redownload, but it is worse, I get the error
```
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/pip", line 5, in <module>
    from pip import main
ImportError: cannot import name main
```
Which seems also to indicate that there is an issue with the path to python ?
Thanks for your help !

**Comment by Linuxine** [comment]
Okay I resolved my issue by install directly certbot using yum on my centOs, and now it works ! I guess I can close this ticket.
