### ISSUE TITLE
Webroot Unicode Issue

### ISSUE THREAD

**Issue by xtermi** [certbot/certbot#7545]
**Certbot Version: 0.31.0-1+ubuntu16.04.1+certbot+1
Ubuntu 16.04.6 LTS
Installation from certbot PPA.**

**CLI Command (Real domain name changed):**
letsencrypt --agree-tos --noninteractive --webroot certonly --webroot-path /data/www/k000009/web/hüüüü.at --cert-name www.xn--h-ehaaaa.at --domains www.xn--h-ehaaaa.at,xn--h-ehaaaa.at --force-renew

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None
Obtaining a new certificate
An unexpected error occurred:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 659-662: ordinal not in range(128)
Please see the logfiles in /var/log/letsencrypt for more details.

**Log File Output:**
2019-11-12 14:33:00,609:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer <certbot.cli._Default object at 0x7fcbae54d080>
2019-11-12 14:33:00,614:DEBUG:certbot.cli:Var authenticator=webroot (set by user).
2019-11-12 14:33:00,617:DEBUG:certbot.cli:Var webroot_path=/data/www/k000009/web/hüüüü.at (set by user).
2019-11-12 14:33:00,622:DEBUG:certbot.cli:Var webroot_path=/data/www/k000009/web/hüüüü.at (set by user).
2019-11-12 14:33:00,623:DEBUG:certbot.cli:Var webroot_map={'webroot_path'} (set by user).
2019-11-12 14:33:00,633:DEBUG:certbot.storage:Writing new config /etc/letsencrypt/renewal/www.letest.xn--h-ehaaaa.at-0003.conf.
2019-11-12 14:33:00,634:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/letsencrypt", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1365, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1250, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3/dist-packages/certbot/client.py", line 428, in obtain_and_enroll_certificate
    self.config)
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 1048, in new_lineage
    target, values)
  File "/usr/lib/python3/dist-packages/certbot/storage.py", line 150, in write_renewal_config
    config.write(outfile=f)
  File "/usr/lib/python3/dist-packages/configobj.py", line 2119, in write
    'ascii')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 659-662: ordinal not in range(128)

**Expected behaviour:**
The current certbot client crashes, if you use a webroot with unicode characters e.g. "üäö". The client should allow unicode characters, which are widely supported by operating systems.

**Comment by adferrand** [comment]
Hello1

Thanks for your report. I confirm the bug. Steps to reproduce it:

```
python tools/venv.py
source venv/bin/activate
rm -rf .certbot_test_workspace
mkdir /tmp/üüü.h
run_acme_server &
cd /tmp/üüü.h
sudo python -m SimpleHTTPServer &
certbot_test certonly --webroot --webroot-path /tmp/üüü.h -d test.example.net
```
