### ISSUE TITLE
certbot-auto 1.0.0 crashes when resizing putty window at prompt

### ISSUE THREAD

**Issue by Philippe23** [certbot/certbot#7637]
This is a reopen of https://github.com/certbot/certbot/issues/4926, since I finally got a chance to attempt to reproduce it and it's still happening.

certbot-auto 1.0.0 crashes when resizing putty window at prompt. Not sure if putty is a requirement, but haven't had a chance to try from another machine.

Also not sure if #3030 is related or not. I don't have dialog installed so I can't test to see if it crashes as mentioned in issue #3030.

## My operating system is (include version):

Server: Amazon Linux (amzn-ami-hvm-2016.09.0.20160923-x86_64-gp2)
Client: Windows 10

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot-auto

## I ran this command and it produced this output:

```
sudo /root/certbot-auto certonly --debug --manual --preferred-challenges dns-01  -d yyyy.xxxxx.com
```

## Certbot's behavior differed from what I expected because:

Don't expect a window resize to cause a crash/exit.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator manual, Installer None
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for yyyy.xxxxx.com

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
NOTE: The IP of this machine will be publicly logged as having requested this
certificate. If you're running certbot in manual mode on a machine that is not
your server, please ensure you're okay with that.

Are you OK with your IP being logged?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o: Cleaning up challenges
Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/main.py", line 14, in main
    return internal_main.main(cli_args)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/_internal/main.py", line 1350, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/_internal/main.py", line 1237, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/_internal/main.py", line 116, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/_internal/renewal.py", line 307, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/_internal/client.py", line 347, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/_internal/client.py", line 395, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/_internal/plugins/manual.py", line 112, in perform
    self._verify_ip_logging_ok()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/_internal/plugins/manual.py", line 133, in _verify_ip_logging_ok
    if display.yesno(msg, cli_flag=cli_flag, force_interactive=True):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/display/util.py", line 215, in yesno
    no=_parens_around_char(no_label)))
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/display/util.py", line 82, in input_with_timeout
    line = misc.readline_with_timeout(timeout, prompt)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/compat/misc.py", line 52, in readline_with_timeout
    rlist, _, _ = select.select([sys.stdin], [], [], timeout)
error: (4, 'Interrupted system call')
Please see the logfiles in /var/log/letsencrypt for more details.
```

**Comment by alexzorin** [comment]
This issue (now) only affects Python 3.4 and Python 2.7. Newer versions no longer crash on terminal resize thanks to [PEP 475](https://www.python.org/dev/peps/pep-0475/).

Since Python 2.7 and 3.4 are not long for this world, fixing this might no longer be worthwhile.

**Comment by Philippe23** [comment]
For reference: Redhat will still be supporting 2.7 until at least June 2024.

(Not saying that's reason enough to spend resources on this bug, just pointing it out so it's in the algebra.)

[1] https://access.redhat.com/solutions/4455511

**Comment by bmw** [comment]
This looks like a duplicate of https://github.com/certbot/certbot/issues/4926 which was closed due to inactivity. I'm reopening that issue and closing this one, but I doubt we'll end up fixing this in any way other than just dropping support for Python 2.7 and 3.4.
