### ISSUE TITLE
certbot install broken on Ubuntu 18.04 LTS due to conflicting acme dependency

### ISSUE THREAD

**Issue by flip111** [certbot/certbot#7718]
These are the commands i run:
```bash
# other deps like software-properties-common previously installed
add-apt-repository -y ppa:certbot/certbot
apt update
apt install -y python-certbot-nginx
python3 -m pip install certbot-dns-ovh
certbot -m $LETSENCRYPT_EMAIL --dns-ovh-propagation-seconds 60 --dns-ovh-credentials $CREDENTIALS_PATH --redirect --agree-tos -a dns-ovh -i nginx -d "*.$HOSTNAME" -d $HOSTNAME --server https://acme-v02.api.letsencrypt.org/directory
```

This is the full output
[certbot_error.txt](https://github.com/certbot/certbot/files/4105258/certbot_error.txt)

Relevant error line
```
ERROR: certbot 1.1.0 has requirement acme>=0.40.0, but you'll have acme 0.31.0 which is incompatible.
```

This is addition log `/tmp/tmpi_8gf7_n/log`
```
2020-01-23 20:49:59,174:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.6/dist-packages/certbot/_internal/main.py", line 1317, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python3.6/dist-packages/certbot/_internal/plugins/disco.py", line 206, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python3.6/dist-packages/certbot/_internal/plugins/disco.py", line 48, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2323, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (acme 0.31.0 (/usr/lib/python3/dist-packages), Requirement.parse('acme>=0.40.0'))
2020-01-23 20:49:59,174:ERROR:certbot._internal.log:An unexpected error occurred:
```

**Comment by bmw** [comment]
Installing Python packages like this from both apt and pip can cause problems like this and is [not supported by the Certbot team](https://certbot.eff.org/docs/install.html#installing-from-source). I'd recommend removing any packages installed from `pip` and if you want to use our OVH plugin, [run it in Docker](https://certbot.eff.org/docs/install.html#running-with-docker).

If you need additional help with this, I recommend posting to https://community.letsencrypt.org where there is a large group of people familiar with the project and server administration who can help you.

**Comment by oviliz** [comment]
@bmw , there's no other way to install certbot-dns-dnsmadeeasy apparently though. :(

**Comment by chriscn** [comment]
The way I fixed this incase anyone is having the same issue is to uninstall certbot from apt `sudo apt-get remove certbot` and install both certbot and the plugin you'd want from pip `pip3 install certbot certbot-dns-route53`
