### ISSUE TITLE
DNS OVH challenge not delete TXT record after challenge

### ISSUE THREAD

**Issue by valentinocossar** [certbot/certbot#7773]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Ubuntu 18.04 with Docker 19.03.6.

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
I've not installed Certbot because I'm running it through Docker.

## I ran this command and it produced this output:
Command:
```sh
docker run -it --rm --name certbot -v "/etc/letsencrypt:/etc/letsencrypt" -v "/var/lib/letsencrypt:/var/lib/letsencrypt" -v "/root/.certbot-dns-ovh-secrets.ini:/root/.certbot-dns-ovh-secrets.ini" certbot/dns-ovh renew --dns-ovh --dns-ovh-credentials ~/.certbot-dns-ovh-secrets.ini --dns-ovh-propagation-seconds 60 --dry-run --verbose
```

Output:
```sh
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/keep-new.heply.run/fullchain.pem (success)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

## Certbot's behavior differed from what I expected because:
Without verbose the challenge doesn't output errors. I would like the plugin also delete the TXT record using OVH API. I've run the same DELETE API from [eu.api.ovh.com](https://eu.api.ovh.com/) and I've correctly deleted the TXT record. So I'm assuming that the issue is with the Certbot DNS OVH plugin.

## Here is a Certbot log showing the issue (if available):

Output error:
```sh
Cleaning up challenges
Starting new HTTPS connection (1): eu.api.ovh.com:443
https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 None
Starting new HTTPS connection (1): eu.api.ovh.com:443
https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 None
https://eu.api.ovh.com:443 "GET /1.0/domain/zone/heply.run/status HTTP/1.1" 200 None
https://eu.api.ovh.com:443 "GET /1.0/domain/zone/heply.run/record?fieldType=TXT&subDomain=_acme-challenge.keep-new HTTP/1.1" 200 12
https://eu.api.ovh.com:443 "GET /1.0/domain/zone/heply.run/record/5105835836 HTTP/1.1" 200 None
list_records: [{'type': 'TXT', 'name': '_acme-challenge.keep-new.heply.run', 'ttl': 60, 'content': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 'id': 5105835836}]
delete_records: [5105835836]
https://eu.api.ovh.com:443 "DELETE /1.0/domain/zone/heply.run/record/5105835836 HTTP/1.1" 403 None
Encountered error deleting TXT record: 403 Client Error: Forbidden for url: https://eu.api.ovh.com/1.0/domain/zone/heply.run/record/5105835836
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common_lexicon.py", line 68, in del_txt_record
    self.provider.delete_record(type='TXT', name=record_name, content=record_content)
  File "/usr/local/lib/python3.8/site-packages/lexicon/providers/base.py", line 118, in delete_record
    return self._delete_record(identifier=identifier, rtype=rtype, name=name, content=content)
  File "/usr/local/lib/python3.8/site-packages/lexicon/providers/ovh.py", line 188, in _delete_record
    self._delete(
  File "/usr/local/lib/python3.8/site-packages/lexicon/providers/base.py", line 154, in _delete
    return self._request('DELETE', url, query_params=query_params)
  File "/usr/local/lib/python3.8/site-packages/lexicon/providers/ovh.py", line 240, in _request
    result.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://eu.api.ovh.com/1.0/domain/zone/heply.run/record/5105835836
```

**Comment by valentinocossar** [comment]
Maybe there's an issue with the generated token, I would like to investigate first with OVH.
