### ISSUE TITLE
"TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead."

### ISSUE THREAD

**Issue by HowellBP** [certbot/certbot#7846]
Traceback:

```2020-03-12 11:12:46,296:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1335, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 206, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 52, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.5/dist-packages/certbot_s3front/authenticator.py", line 21, in <module>
    class Authenticator(common.Plugin):
  File "/usr/local/lib/python3.5/dist-packages/certbot_s3front/authenticator.py", line 22, in Authenticator
    zope.interface.implements(interfaces.IAuthenticator)
  File "/usr/local/lib/python3.5/dist-packages/zope/interface/declarations.py", line 485, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.
2020-03-12 11:12:46,296:ERROR:certbot.log:An unexpected error occurred:

**Comment by HowellBP** [comment]
Installed via instructions for Xenial from https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx. I was upgrading from a previous version of certbot/python, but there are no instructions on how to upgrade, so I attempted to purge all configuration first.

**Comment by alexzorin** [comment]
The error is coming from your s3front plugin. It looks like the version you have installed is not compatible with Python 3.

Looking at https://github.com/dlapiduz/certbot-s3front/issues/56 , it appears that the author of that plugin did fix the Python 3 compatibility issue, so if you upgrade to the latest version, you should be all set.
