### ISSUE TITLE
Improve error messages when we fail to connect to the ACME server

### ISSUE THREAD

**Issue by bmw** [certbot/certbot#7855]
As suggested to me by @schoen, currently when we fail to connect, we basically just propagate the connection error from `requests`. Here's one example of (particularly nasty) error output:
```
% certbot register --config-dir $(mktemp -d) --work-dir $(mktemp -d) --logs-dir $(mktemp -d) --server https://example.org --register-unsafely-without-email
Saving debug log to /var/folders/z5/bm971dpn47g1hss3g209t2b00000gp/T/tmp.bYHhBLzARs/letsencrypt.log
Registering without email!
An unexpected error occurred:
Traceback (most recent call last):
  File "/local/path/venv3/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/local/path/venv3/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err 
  File "/local/path/venv3/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/path/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/local/path/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/local/path/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/local/path/venv3/lib/python3.7/site-packages/urllib3/connection.py", line 300, in connect
    conn = self._new_conn()
  File "/local/path/venv3/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e 
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x108b00890>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/path/venv3/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/local/path/venv3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/local/path/venv3/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='example.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x108b00890>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/path/acme/acme/client.py", line 1094, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/local/path/venv3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/local/path/venv3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/local/path/venv3/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='example.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x108b00890>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

ValueError: Requesting example.org/: Connection refused
Please see the logfiles in /var/folders/z5/bm971dpn47g1hss3g209t2b00000gp/T/tmp.bYHhBLzARs for more details.
```
We should improve this output by making sure the output isn't (just) the generic network error, but also describes that we failed to connect to the ACME server (rather than the ACME server failing to connect to us for instance).

**Comment by alexzorin** [comment]
Looks like you have already fixed this via #8000. The traceback now only appears in the debug log.

https://github.com/certbot/certbot/blob/0e59c6ba1baf2c32f229a9b8c68fd457ba136617/certbot/certbot/_internal/log.py#L336

The new output is a big improvement:

    $ certbot register --server https://localhost --register-unsafely-without-email
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Registering without email!
    An unexpected error occurred:
    ValueError: Requesting localhost/: Connection refused
    Please see the logfiles in /var/log/letsencrypt for more details.

I think that's probably good enough to close this.

The recursive PEP3134 tracebacks still happen in other places, but I'm hoping to address that globally in #8288.
