### ISSUE TITLE
Как исправить ошибку?   AttributeError: module 'types' has no attribute 'resolve_bases'

### ISSUE THREAD

**Issue by Mishanya03** [certbot/certbot#7868]
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\commands\install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\req\req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\index\package_finder.py", line 899, in find_requirement
    req.name, specifier=req.specifier, hashes=hashes,
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\index\package_finder.py", line 881, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\index\package_finder.py", line 826, in find_all_candidates
    project_url, link_evaluator=link_evaluator,
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\index\package_finder.py", line 794, in process_project_url
    page_links = list(parse_links(html_page))
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\index\collector.py", line 255, in parse_links
    namespaceHTMLElements=False,
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\html5lib\html5parser.py", line 46, in parse
    p = HTMLParser(tb, namespaceHTMLElements=namespaceHTMLElements)
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\html5lib\html5parser.py", line 123, in __init__
    getPhases(debug).items()])
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\html5lib\_utils.py", line 121, in wrapped
    cache[key] = func(*args, **kwargs)
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\html5lib\html5parser.py", line 446, in getPhases
    class Phase(with_metaclass(getMetaclass(debug, log))):
  File "c:\users\михаил\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\six.py", line 851, in __new__
    resolved_bases = types.resolve_bases(bases)
AttributeError: module 'types' has no attribute 'resolve_bases'

**Comment by schoen** [comment]
@adferrand, this looks like a Python dependency issue on Windows—could you take a look and opine on this, please?

**Comment by schoen** [comment]
Thank you, @adferrand!
