### ISSUE TITLE
`certbot certificates` throw errors

### ISSUE THREAD

**Issue by iTonyYo** [certbot/certbot#7940]
System: CentOS 7
Python: v2.7.5
Pip: v20.0.2
Kernel: v5.6.4

**when I run `certbot certificates`**,
```shell
Saving debug log to /var/log/letsencrypt/letsencrypt.log
^CExiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==1.3.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 1019, in certificates
    cert_manager.certificates(config)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/cert_manager.py", line 88, in certificates
    _describe_certs(config, parsed_certs, parse_failures)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/cert_manager.py", line 353, in _describe_certs
    notify(_report_human_readable(config, parsed_certs))
  File "/usr/lib/python2.7/site-packages/certbot/_internal/cert_manager.py", line 338, in _report_human_readable
    certinfo.append(human_readable_cert_info(config, cert))
  File "/usr/lib/python2.7/site-packages/certbot/_internal/cert_manager.py", line 264, in human_readable_cert_info
    elif checker.ocsp_revoked(cert):
  File "/usr/lib/python2.7/site-packages/certbot/ocsp.py", line 71, in ocsp_revoked
    return self.ocsp_revoked_by_paths(cert.cert_path, cert.chain_path)
  File "/usr/lib/python2.7/site-packages/certbot/ocsp.py", line 99, in ocsp_revoked_by_paths
    return self._check_ocsp_openssl_bin(cert_path, chain_path, host, url)
  File "/usr/lib/python2.7/site-packages/certbot/ocsp.py", line 117, in _check_ocsp_openssl_bin
    output, err = util.run_script(cmd, log=logger.debug)
  File "/usr/lib/python2.7/site-packages/certbot/util.py", line 82, in run_script
    stdout, stderr = proc.communicate()
  File "/usr/lib64/python2.7/subprocess.py", line 800, in communicate
    return self._communicate(input)
  File "/usr/lib64/python2.7/subprocess.py", line 1401, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib64/python2.7/subprocess.py", line 1455, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt
Please see the logfiles in /var/log/letsencrypt for more details.
```
**/var/log/letsencrypt/letsencrypt.log**,
```
2020-04-24 14:37:53,851:DEBUG:certbot._internal.main:certbot version: 1.3.0
2020-04-24 14:37:53,851:DEBUG:certbot._internal.main:Arguments: []
2020-04-24 14:37:53,851:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-04-24 14:37:53,869:DEBUG:certbot._internal.log:Root logging level set at 20
2020-04-24 14:37:53,869:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-04-24 14:37:53,880:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): ocsp.int-x3.letsencrypt.org:80
2020-04-24 14:37:54,987:ERROR:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    sys.exit(main())
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/main.py", line 1019, in certificates
    cert_manager.certificates(config)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/cert_manager.py", line 88, in certificates
    _describe_certs(config, parsed_certs, parse_failures)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/cert_manager.py", line 353, in _describe_certs
    notify(_report_human_readable(config, parsed_certs))
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/cert_manager.py", line 338, in _report_human_readable
    certinfo.append(human_readable_cert_info(config, cert))
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/_internal/cert_manager.py", line 264, in human_readable_cert_info
    elif checker.ocsp_revoked(cert):
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/ocsp.py", line 71, in ocsp_revoked
    return self.ocsp_revoked_by_paths(cert.cert_path, cert.chain_path)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/ocsp.py", line 100, in ocsp_revoked_by_paths
    return _check_ocsp_cryptography(cert_path, chain_path, url)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/certbot/ocsp.py", line 168, in _check_ocsp_cryptography
    headers={'Content-Type': 'application/ocsp-request'})
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 1056, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1090, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1052, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 890, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 852, in send
    self.connect()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/opt/eff.org/certbot/venv/lib/python2.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
KeyboardInterrupt
```
Tried to ping `ocsp.int-x3.letsencrypt.org`, but got **100% packet loss**.
![image](https://user-images.githubusercontent.com/5499703/80183719-e5834800-863b-11ea-859f-b3519b9da298.png)

I just want to check all my certificates on server, why `certbot certificates` will start new http connection to `ocsp.int-x3.letsencrypt.org:80`?
```
2020-04-24 14:37:53,880:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): ocsp.int-x3.letsencrypt.org:80
```

**Comment by alexzorin** [comment]
>I just want to check all my certificates on server, why certbot certificates will start new http connection to ocsp.int-x3.letsencrypt.org:80?

It's checking whether any of the certificates have been revoked.

In Certbot 1.4.0, [one of the changes](https://github.com/certbot/certbot/blob/master/certbot/CHANGELOG.md#140---master) was to add a timeout in case the OCSP server was not reachable from the host where Certbot is running:

>Fix hanging OCSP queries during revocation checking - added a 10 second timeout.

Unfortunately 1.4.0 is not in EPEL yet, so all you can really do is look into why your machine can't reach the Let's Encrypt OCSP servers. It's needed for other purposes too - like OCSP stapling in your webserver.

**Comment by alexzorin** [comment]
Since 1.4.0 is out and this is hopefully fixed in that release, I'm going to close this issue.
