### ISSUE TITLE
Support Google DNS _acme-challenge Zone

### ISSUE THREAD

**Issue by Soham3-1415** [certbot/certbot#7977]
## My operating system is (include version):
Arch Linux

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pacman -S certbot-dns-google

## I ran this command and it produced this output:
```
certbot certonly --staging --dns-google --dns-google-credentials $PATH_TO_ACCOUNT_CREDENTIALS -d projects.sohamroy.me

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-google, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for projects.sohamroy.me
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/acme-challenge-projects/managedZones?dnsName=projects.sohamroy.me.&alt=json
Attempting refresh to obtain initial access_token
Refreshing access_token
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/acme-challenge-projects/managedZones?dnsName=sohamroy.me.&alt=json
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/acme-challenge-projects/managedZones?dnsName=me.&alt=json
Cleaning up challenges
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/acme-challenge-projects/managedZones?dnsName=projects.sohamroy.me.&alt=json
Attempting refresh to obtain initial access_token
Refreshing access_token
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/acme-challenge-projects/managedZones?dnsName=sohamroy.me.&alt=json
URL being requested: GET https://dns.googleapis.com/dns/v1/projects/acme-challenge-projects/managedZones?dnsName=me.&alt=json
Error finding zone. Skipping cleanup.
Unable to determine managed zone for projects.sohamroy.me using zone names: ['projects.sohamroy.me', 'sohamroy.me', 'me'].
```

## Certbot's behavior differed from what I expected because:
I am using Let's Encrypt, and Let's Encrypt uses the `_acme-challenge` subdomain for domain validation. For security reasons, I only wish to provide DNS API access to certbot for that particular subdomain. In this case, I am trying to obtain a certificate for `projects.sohamroy.me`. Certbot only needs access to a zone controlling `_acme-challenge.projects.sohamroy.me`. However, Certbot does not look for this zone.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2020-05-06 14:50:37,692:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-05-06 14:50:37,692:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-05-06 14:50:37,696:INFO:googleapiclient.discovery:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
2020-05-06 14:50:37,932:INFO:googleapiclient.discovery:URL being requested: GET https://dns.googleapis.com/dns/v1/projects/acme-challenge-projects/managedZones?dnsName=projects.sohamroy.me.&alt=json
2020-05-06 14:50:37,933:INFO:oauth2client.transport:Attempting refresh to obtain initial access_token
2020-05-06 14:50:37,935:DEBUG:oauth2client.crypt:[b'REDACTED', b'REDACTED', b'REDACTED']
2020-05-06 14:50:37,936:INFO:oauth2client.client:Refreshing access_token
2020-05-06 14:50:38,183:INFO:googleapiclient.discovery:URL being requested: GET https://dns.googleapis.com/dns/v1/projects/acme-challenge-projects/managedZones?dnsName=sohamroy.me.&alt=json
2020-05-06 14:50:38,364:INFO:googleapiclient.discovery:URL being requested: GET https://dns.googleapis.com/dns/v1/projects/acme-challenge-projects/managedZones?dnsName=me.&alt=json
2020-05-06 14:50:38,505:WARNING:certbot_dns_google._internal.dns_google:Error finding zone. Skipping cleanup.
2020-05-06 14:50:38,505:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==1.3.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.8/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1233, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/client.py", line 410, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/client.py", line 344, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/client.py", line 391, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python3.8/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python3.8/site-packages/certbot_dns_google/_internal/dns_google.py", line 70, in _perform
    self._get_google_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/usr/lib/python3.8/site-packages/certbot_dns_google/_internal/dns_google.py", line 113, in add_txt_record
    zone_id = self._find_managed_zone_id(domain)
  File "/usr/lib/python3.8/site-packages/certbot_dns_google/_internal/dns_google.py", line 283, in _find_managed_zone_id
    raise errors.PluginError('Unable to determine managed zone for {0} using zone names: {1}.'
certbot.errors.PluginError: Unable to determine managed zone for projects.sohamroy.me using zone names: ['projects.sohamroy.me', 'sohamroy.me', 'me'].
```

**Comment by Soham3-1415** [comment]
Use of the `_acme-challenge` subdomain seems to be in the spec, but I'm not sure how best to implement this.

This seems to be the easiest approach, but it kind of feels sloppy. There might also be other functions that run into the same issue.
```patch
diff --git a/certbot-dns-google/certbot_dns_google/_internal/dns_google.py b/certbot-dns-google/certbot_dns_google/_internal/dns_google.py
index 4eaed1783..b1e629f8a 100644
--- a/certbot-dns-google/certbot_dns_google/_internal/dns_google.py
+++ b/certbot-dns-google/certbot_dns_google/_internal/dns_google.py
@@ -263,6 +263,7 @@ class _GoogleClient(object):
         """
 
         zone_dns_name_guesses = dns_common.base_domain_name_guesses(domain)
+        zone_dns_name_guesses = zone_dns_name_guesses.append('_acme-challenge.' + domain)
 
         mz = self.dns.managedZones()
         for zone_name in zone_dns_name_guesses:
```

**Comment by bmw** [comment]
I think this is a specific instance of https://github.com/certbot/certbot/issues/7701 so I'm closing this issue but if you think I'm mistaken, please let me know!
