### ISSUE TITLE
Unable ot renew issued wildcard certificate via Cloudflare plugin

### ISSUE THREAD

**Issue by PVasileff** [certbot/certbot#7982]
## My operating system is (include version):
OS Debian 10 x64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Cerbot Installed via Git:
```
git clone https://github.com/certbot/certbot.git /opt/certbot
cd /opt/certbot/acme/
python setup.py install
cd /opt/certbot/certbot
python setup.py install
cd /opt/certbot/certbot-dns-cloudflare/
python setup.py install
```
version: certbot 1.5.0.dev0

## I ran this command and it produced this output:
`certbot renew`

## Certbot's behavior differed from what I expected because:
Issued wildcard certificate for my domain unable to be renewed
Certificate issued via:

`certbot certonly --dns-cloudflare --dns-cloudflare-credentials /root/.secrets/cloudflare.ini -d mydomain.cf,*.mydomain.cf --preferred-challenges dns-01`

## Here is a Certbot log showing the issue (if available):
from command line when run cerbot renew:

```
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator dns-cloudflare, Installer None
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for mydomain.cf
dns-01 challenge for mydomain.cf
Cleaning up challenges
Attempting to renew cert (mydomain.cf) from /etc/letsencrypt/renewal/mydomain.cf.conf produced an unexpected error: 'code'. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/mydomain.cf/fullchain.pem (failure)
```

from letsencrypt.log:
```
2020-05-10 13:01:58,487:DEBUG:certbot._internal.main:certbot version: 1.5.0.dev0
2020-05-10 13:01:58,488:DEBUG:certbot._internal.main:Arguments: []
2020-05-10 13:01:58,488:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-cloudflare,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-05-10 13:01:58,521:DEBUG:certbot._internal.log:Root logging level set at 20
2020-05-10 13:01:58,522:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-05-10 13:01:58,572:DEBUG:certbot._internal.plugins.selection:Requested authenticator <certbot._internal.cli.cli_utils._Default object at 0x7fd2b1210cd0> and installer <certbot._internal.cli.cli_utils._Default object at 0x7fd2b1210cd0>
2020-05-10 13:01:58,621:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): ocsp.int-x3.letsencrypt.org:80
2020-05-10 13:01:58,699:DEBUG:urllib3.connectionpool:http://ocsp.int-x3.letsencrypt.org:80 "POST / HTTP/1.1" 200 527
2020-05-10 13:01:58,700:DEBUG:certbot.ocsp:OCSP response for certificate /etc/letsencrypt/archive/anotherdomain.cf/cert4.pem is signed by the certificate's issuer.
2020-05-10 13:01:58,703:DEBUG:certbot.ocsp:OCSP certificate status for /etc/letsencrypt/archive/anotherdomain.cf/cert4.pem is: OCSPCertStatus.GOOD
2020-05-10 13:01:58,708:INFO:certbot._internal.renewal:Cert not yet due for renewal
2020-05-10 13:01:58,709:DEBUG:certbot._internal.plugins.selection:Requested authenticator dns-cloudflare and installer None
2020-05-10 13:01:58,750:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): ocsp.int-x3.letsencrypt.org:80
2020-05-10 13:01:58,825:DEBUG:urllib3.connectionpool:http://ocsp.int-x3.letsencrypt.org:80 "POST / HTTP/1.1" 200 527
2020-05-10 13:01:58,826:DEBUG:certbot.ocsp:OCSP response for certificate /etc/letsencrypt/archive/mydomain.cf/cert3.pem is signed by the certificate's issuer.
2020-05-10 13:01:58,826:DEBUG:certbot.ocsp:OCSP certificate status for /etc/letsencrypt/archive/mydomain.cf/cert3.pem is: OCSPCertStatus.GOOD
2020-05-10 13:01:58,827:DEBUG:certbot._internal.storage:Should renew, less than 30 days before certificate expiry 2020-05-31 06:04:33 UTC.
2020-05-10 13:01:58,828:INFO:certbot._internal.renewal:Cert is due for renewal, auto-renewing...
2020-05-10 13:01:58,828:DEBUG:certbot._internal.plugins.selection:Requested authenticator dns-cloudflare and installer None
2020-05-10 13:01:58,836:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * dns-cloudflare
Description: Obtain certificates using a DNS TXT record (if you are using Cloudflare for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-cloudflare = certbot_dns_cloudflare._internal.dns_cloudflare:Authenticator
Initialized: <certbot_dns_cloudflare._internal.dns_cloudflare.Authenticator object at 0x7fd2b1210e90>
Prep: True
2020-05-10 13:01:58,837:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_cloudflare._internal.dns_cloudflare.Authenticator object at 0x7fd2b1210e90> and installer None
2020-05-10 13:01:58,837:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator dns-cloudflare, Installer None
2020-05-10 13:01:58,841:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(status=None, terms_of_service_agreed=None, agreement=None, only_return_existing=None, contact=(), key=None, external_account_binding=None), uri=u'https://acme-v02.api.letsencrypt.org/acme/acct/70153737', new_authzr_uri=None, terms_of_service=None), bb46601daf8edc90eeb35b1ced2e7371, Meta(creation_host=u'lb.anotherdomain.cf', creation_dt=datetime.datetime(2019, 10, 24, 8, 51, 37, tzinfo=<UTC>)))>
2020-05-10 13:01:58,842:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-05-10 13:01:58,843:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2020-05-10 13:01:59,504:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-05-10 13:01:59,505:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 10 May 2020 10:01:59 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "6_qGHLO5Q08": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-05-10 13:01:59,505:INFO:certbot._internal.main:Renewing an existing certificate
2020-05-10 13:02:00,006:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0024_key-certbot.pem
2020-05-10 13:02:00,010:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0024_csr-certbot.pem
2020-05-10 13:02:00,011:DEBUG:acme.client:Requesting fresh nonce
2020-05-10 13:02:00,011:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-05-10 13:02:00,177:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-05-10 13:02:00,177:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 10 May 2020 10:02:00 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0102WdK5NQrZ7wlE1egPhHQlaOBGQxJL-D7zpOLCShRSh_Y
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-05-10 13:02:00,178:DEBUG:acme.client:Storing nonce: 0102WdK5NQrZ7wlE1egPhHQlaOBGQxJL-D7zpOLCShRSh_Y
2020-05-10 13:02:00,178:DEBUG:acme.client:JWS payload:
{
  "identifiers": [
    {
      "type": "dns", 
      "value": "mydomain.cf"
    }, 
    {
      "type": "dns", 
      "value": "*.mydomain.cf"
    }
  ]
}
2020-05-10 13:02:00,181:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJub25jZSI6ICIwMTAyV2RLNU5Rclo3d2xFMWVnUGhIUWxhT0JHUXhKTC1EN3pwT0xDU2hSU2hfWSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvbmV3LW9yZGVyIiwgImtpZCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hY2N0LzcwMTUzNzM3IiwgImFsZyI6ICJSUzI1NiJ9", 
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwgCiAgICAgICJ2YWx1ZSI6ICJzcGFtYXNzYXNzaW4uY2YiCiAgICB9LCAKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwgCiAgICAgICJ2YWx1ZSI6ICIqLnNwYW1hc3Nhc3Npbi5jZiIKICAgIH0KICBdCn0", 
  "signature": "yLJ6dK1bxx-Pi0N7ArA3-Q2ZcBxMbWdudOyJDpHJ-uXlzPCt_i8rkAOKM62srngoC1uL7tHVDw11uhY1FyCA4FaSCgphD12uO0TkbVBrzu6fJv_9H1SjRhguHtx2DmzTn-i3HLCHrXNw6NnOgsMpx9Rr6ezd-CgOcc9nDq7rno7m0UdN8it6O7woLhzl3ukfhZAbts9IxYkMsZTn3470l-tHZwRlc5-Fp9QikIV-4155A9FHDQI5Gg5dE_ZSSkYJjzI4PNRWZopngX7Mn-ApTz7DQ3xQNh6L10B3e3m6t4iefHyNS-v1wYpQLyZavONKRICIQrnyS2q_C3jM3joWmg"
}
2020-05-10 13:02:00,381:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 473
2020-05-10 13:02:00,382:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sun, 10 May 2020 10:02:00 GMT
Content-Type: application/json
Content-Length: 473
Connection: keep-alive
Boulder-Requester: 70153737
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/70153737/3295657064
Replay-Nonce: 01019D2vDgH470UwGIqpHt_DkU7c0eqV4NJmQMcgnXejPXI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-05-16T06:01:43Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "*.mydomain.cf"
    },
    {
      "type": "dns",
      "value": "mydomain.cf"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/4464358989",
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/4464358991"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/70153737/3295657064"
}
2020-05-10 13:02:00,382:DEBUG:acme.client:Storing nonce: 01019D2vDgH470UwGIqpHt_DkU7c0eqV4NJmQMcgnXejPXI
2020-05-10 13:02:00,382:DEBUG:acme.client:JWS payload:

2020-05-10 13:02:00,386:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/4464358989:
{
  "protected": "eyJub25jZSI6ICIwMTAxOUQydkRnSDQ3MFV3R0lxcEh0X0RrVTdjMGVxVjROSm1RTWNnblhlalBYSSIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYXV0aHotdjMvNDQ2NDM1ODk4OSIsICJraWQiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC83MDE1MzczNyIsICJhbGciOiAiUlMyNTYifQ", 
  "payload": "", 
  "signature": "hCZOV8I6RjQRYVFnW_glTK5yTfwAdvCgL_AoC1ia2fNMZ25xOcfIA5P39RvzYyuJWWod3iv7gsZRLMcZgPL6_NzJx_kiY0--cl00jquE738gSiIBoeif7GbY82R0O6oCuuJ7MCZvlY_xfek4J0_zSaS1CePF6tFDZs6yvl7isymVzShJhcPO5oCqkIAa2wg-GCwgEBkKl-ZafIfUSIzWkqQMNrq0PB2noiAv8iYbUOFC9q7cPcYbKuqawU2WYNingDOdyLquRXMbz89O7vaZeSe2qqpxaop5LQlguwfF9C_kpvKSuyTF_33hJnClrugi212-8s_xMtWRy4idx-EGmA"
}
2020-05-10 13:02:00,589:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/4464358989 HTTP/1.1" 200 387
2020-05-10 13:02:00,590:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 10 May 2020 10:02:00 GMT
Content-Type: application/json
Content-Length: 387
Connection: keep-alive
Boulder-Requester: 70153737
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 01017aCSN2XmuhcYmglMhVzufrFYKLw1H1PD-fXVf-QoJjw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "mydomain.cf"
  },
  "status": "pending",
  "expires": "2020-05-16T06:01:43Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/4464358989/_fxFbw",
      "token": "29Ffj2zb1daxWkqOrYH-CNvs0mHdkzzka9ZcdbAeenw"
    }
  ],
  "wildcard": true
}
2020-05-10 13:02:00,591:DEBUG:acme.client:Storing nonce: 01017aCSN2XmuhcYmglMhVzufrFYKLw1H1PD-fXVf-QoJjw
2020-05-10 13:02:00,591:DEBUG:acme.client:JWS payload:

2020-05-10 13:02:00,594:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/4464358991:
{
  "protected": "eyJub25jZSI6ICIwMTAxN2FDU04yWG11aGNZbWdsTWhWenVmckZZS0x3MUgxUEQtZlhWZi1Rb0pqdyIsICJ1cmwiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYXV0aHotdjMvNDQ2NDM1ODk5MSIsICJraWQiOiAiaHR0cHM6Ly9hY21lLXYwMi5hcGkubGV0c2VuY3J5cHQub3JnL2FjbWUvYWNjdC83MDE1MzczNyIsICJhbGciOiAiUlMyNTYifQ", 
  "payload": "", 
  "signature": "rkhjPlwdnBajb-QuNoSwjqM_XrGsqmTD2CBIiqGstv1HyvN-LSe0gM5FLAh5tyJzUkEpaqfoiyANo8hWyb75a4RsSa-vAd7HmMoQVjfjtIB16rGhbo5JslypY5JkYnoPZvKoeXFMgcDZMn40_1qoZhhZiB16B4s0oCInM2qf3Szov10cjgwIjGEwC8bCSS1qxDRQhKcf9weSGxozIkOWfiXPZ-0xDTKPBH26cm5ZydZkdpkZQhSXTYngd6B-KUmiR2cdh7FyD4bBF3GkimjD5YpIeHwwzS07jaoa6jgHEHbKu-F-XcIzBtI-lPjaPZ5t7afTJMEmabh5bLyh0dZeQQ"
}
2020-05-10 13:02:00,788:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/4464358991 HTTP/1.1" 200 793
2020-05-10 13:02:00,789:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 10 May 2020 10:02:00 GMT
Content-Type: application/json
Content-Length: 793
Connection: keep-alive
Boulder-Requester: 70153737
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 01020q0_qDZTSZZ5XFNmD3nLxvcLVMfKOU2KEk4HgRuQlQo
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "mydomain.cf"
  },
  "status": "pending",
  "expires": "2020-05-16T06:01:43Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/4464358991/89-P4Q",
      "token": "QnvCrfIfoNupi34cR1WxpGaGn_4aK4vrkid6J8F7jls"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/4464358991/b1PRLw",
      "token": "QnvCrfIfoNupi34cR1WxpGaGn_4aK4vrkid6J8F7jls"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/4464358991/pIZDxA",
      "token": "QnvCrfIfoNupi34cR1WxpGaGn_4aK4vrkid6J8F7jls"
    }
  ]
}
2020-05-10 13:02:00,789:DEBUG:acme.client:Storing nonce: 01020q0_qDZTSZZ5XFNmD3nLxvcLVMfKOU2KEk4HgRuQlQo
2020-05-10 13:02:00,790:INFO:certbot._internal.auth_handler:Performing the following challenges:
2020-05-10 13:02:00,790:INFO:certbot._internal.auth_handler:dns-01 challenge for mydomain.cf
2020-05-10 13:02:00,790:INFO:certbot._internal.auth_handler:dns-01 challenge for mydomain.cf
2020-05-10 13:02:00,804:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.cloudflare.com:443
2020-05-10 13:02:01,123:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?per_page=1&name=mydomain.cf HTTP/1.1" 200 None
2020-05-10 13:02:01,126:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Found zone_id of 0dcfca0f4a3ef0ee73b936aa94adfc26 for mydomain.cf using name mydomain.cf
2020-05-10 13:02:01,126:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Attempting to add record to zone 0dcfca0f4a3ef0ee73b936aa94adfc26: {'content': u'ONLDlQB-gsL7i5fjE1U8Dz3Wd1qwm0fPf-EoAGFvLY8', 'type': 'TXT', 'name': '_acme-challenge.mydomain.cf', 'ttl': 120}
2020-05-10 13:02:01,368:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "POST /client/v4/zones/0dcfca0f4a3ef0ee73b936aa94adfc26/dns_records HTTP/1.1" 401 None
2020-05-10 13:02:01,373:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "build/bdist.linux-x86_64/egg/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 77, in _perform
    self._get_cloudflare_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "build/bdist.linux-x86_64/egg/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 116, in add_txt_record
    self.cf.zones.dns_records.post(zone_id, data=data)  # zones | pylint: disable=no-member
  File "build/bdist.linux-x86_64/egg/CloudFlare/cloudflare.py", line 632, in post
    params, data, files)
  File "build/bdist.linux-x86_64/egg/CloudFlare/cloudflare.py", line 75, in call_with_auth
    params, data, files)
  File "build/bdist.linux-x86_64/egg/CloudFlare/cloudflare.py", line 449, in _call
    code = errors['code']
KeyError: 'code'

2020-05-10 13:02:01,373:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-05-10 13:02:01,373:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-05-10 13:02:01,381:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.cloudflare.com:443
2020-05-10 13:02:01,653:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?per_page=1&name=mydomain.cf HTTP/1.1" 200 None
2020-05-10 13:02:01,654:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Found zone_id of 0dcfca0f4a3ef0ee73b936aa94adfc26 for mydomain.cf using name mydomain.cf
2020-05-10 13:02:01,909:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones/0dcfca0f4a3ef0ee73b936aa94adfc26/dns_records?content=ONLDlQB-gsL7i5fjE1U8Dz3Wd1qwm0fPf-EoAGFvLY8&per_page=1&type=TXT&name=_acme-challenge.mydomain.cf HTTP/1.1" 200 None
2020-05-10 13:02:01,910:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Unable to find TXT record.
2020-05-10 13:02:01,910:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:TXT record not found; no cleanup needed.
2020-05-10 13:02:01,916:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.cloudflare.com:443
2020-05-10 13:02:03,421:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?per_page=1&name=mydomain.cf HTTP/1.1" 200 None
2020-05-10 13:02:03,433:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Found zone_id of 0dcfca0f4a3ef0ee73b936aa94adfc26 for mydomain.cf using name mydomain.cf
2020-05-10 13:02:03,691:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones/0dcfca0f4a3ef0ee73b936aa94adfc26/dns_records?content=GjNQx1efH6I4WcXAzZC_ITvMcT_OM5v7RTK2TP6hyJI&per_page=1&type=TXT&name=_acme-challenge.mydomain.cf HTTP/1.1" 200 None
2020-05-10 13:02:03,693:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Unable to find TXT record.
2020-05-10 13:02:03,693:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:TXT record not found; no cleanup needed.
2020-05-10 13:02:03,694:WARNING:certbot._internal.renewal:Attempting to renew cert (mydomain.cf) from /etc/letsencrypt/renewal/mydomain.cf.conf produced an unexpected error: 'code'. Skipping.
2020-05-10 13:02:03,696:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/_internal/renewal.py", line 448, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/_internal/main.py", line 1176, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/_internal/main.py", line 116, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/_internal/renewal.py", line 306, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/_internal/client.py", line 343, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/_internal/client.py", line 390, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "build/bdist.linux-x86_64/egg/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 77, in _perform
    self._get_cloudflare_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "build/bdist.linux-x86_64/egg/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 116, in add_txt_record
    self.cf.zones.dns_records.post(zone_id, data=data)  # zones | pylint: disable=no-member
  File "build/bdist.linux-x86_64/egg/CloudFlare/cloudflare.py", line 632, in post
    params, data, files)
  File "build/bdist.linux-x86_64/egg/CloudFlare/cloudflare.py", line 75, in call_with_auth
    params, data, files)
  File "build/bdist.linux-x86_64/egg/CloudFlare/cloudflare.py", line 449, in _call
    code = errors['code']
KeyError: 'code'

2020-05-10 13:02:03,696:ERROR:certbot._internal.renewal:All renewal attempts failed. The following certs could not be renewed:
2020-05-10 13:02:03,696:ERROR:certbot._internal.renewal:  /etc/letsencrypt/live/mydomain.cf/fullchain.pem (failure)
2020-05-10 13:02:03,698:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot==1.5.0.dev0', 'console_scripts', 'certbot')()
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/_internal/main.py", line 1255, in renew
    renewal.handle_renewal_request(config)
  File "/usr/local/lib/python2.7/dist-packages/certbot-1.5.0.dev0-py2.7.egg/certbot/_internal/renewal.py", line 473, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)

```

**Comment by alexzorin** [comment]
Same issue https://github.com/certbot/certbot/issues/7970#issuecomment-625514238. Unfortunately Cloudflare is blocking Freenom domains from using the required APIs:

>You cannot use this API for domains with a .cf, .ga, .gq, .ml, or .tk TLD
