### ISSUE TITLE
Generate a certificate with CNAME

### ISSUE THREAD

**Issue by daliyo** [certbot/certbot#7999]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
CentOS8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto 1.4.0

## I ran this command and it produced this output:
sudo /usr/local/bin/certbot-auto --nginx -d 51cy.club
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for 51cy.club
Waiting for verification...
Challenge failed for domain 51cy.club
http-01 challenge for 51cy.club
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: 51cy.club
   Type:   dns
   Detail: No valid IP addresses found for 51cy.club

## Certbot's behavior differed from what I expected because:
My domain DNS is resolved like this:
host1.example.com A to 127.0.0.1
51cy.club CNAME to host1.example.com

I hope its result is successful, but it prompts me that there is an error.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

2020-05-19 01:24:23,192:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/4663441986 HTTP/1.1" 200 523
2020-05-19 01:24:23,193:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 18 May 2020 17:24:23 GMT
Content-Type: application/json
Content-Length: 523
Connection: keep-alive
Boulder-Requester: 85609968
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 00015SSJPNHPH4Sn-iVlI5hwag_x2hDngNllhDYMiv2fCMg
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "51cy.club"
  },
  "status": "invalid",
  "expires": "2020-05-25T17:24:14Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:dns",
        "detail": "No valid IP addresses found for 51cy.club",
        "status": 400
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/4663441986/FlsnQQ",
      "token": "fBatsL6VOVSZ7C-ZYxlca1-LmHU1h-jwiL-FuSKgnII"
    }
  ]
}
2020-05-19 01:24:23,194:DEBUG:acme.client:Storing nonce: 00015SSJPNHPH4Sn-iVlI5hwag_x2hDngNllhDYMiv2fCMg
2020-05-19 01:24:23,194:WARNING:certbot._internal.auth_handler:Challenge failed for domain 51cy.club
2020-05-19 01:24:23,195:INFO:certbot._internal.auth_handler:http-01 challenge for 51cy.club
2020-05-19 01:24:23,195:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: 51cy.club
Type:   dns
Detail: No valid IP addresses found for 51cy.club
2020-05-19 01:24:23,196:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2020-05-19 01:24:23,196:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-05-19 01:24:23,196:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-05-19 01:24:24,707:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 11, in <module>
    load_entry_point('letsencrypt==0.7.0', 'console_scripts', 'letsencrypt')()
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/main.py", line 1101, in run
    certname, lineage)
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/client.py", line 409, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/client.py", line 343, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/client.py", line 390, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/opt/eff.org/certbot/venv/lib64/python3.6/site-packages/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
nginx .conf file
server {
    listen 80;
    server_name 51cy.club;

    location / {
        proxy_pass  http://localhost:9800/;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

**Comment by alexzorin** [comment]
Hi @daliyo,

Please post your question to https://community.letsencrypt.org, where you will be able to get in-depth answers and in-depth help with your DNS setup.
