### ISSUE TITLE
Permission errors when preserving owner/group on key renewal should not be fatal

### ISSUE THREAD

**Issue by jlu5** [certbot/certbot#8070]
## My operating system is (include version):

Debian 10

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

certbot 1.5.0 installed via virtualenv / pip

## Context

On one of my machines, I set up certbot with a dedicated non-root user. I set the owner/group of `/etc/letsencrypt/archive` to `certbot:ssl-apps`, the group being shared across all service users that need to read TLS certificates. Then, I set the directory as setgid so the created keyfiles would assume the right group ID.

Today, I noticed that renewals were actually failing due to a permission error. I did some digging and I found that certbot tries to copy over user/group settings from the old key file. In my case, this process failed because 1) certbot was not running as root 2) I didn't add the `certbot` user to the `ssl-apps` group, thinking it wouldn't be necessary since I had setgid and certbot already owned the files. I didn't notice this problem earlier because creating new certificates worked smoothly - there's no file to copy permissions from.

I narrowed down the issue to this bit of code:

https://github.com/certbot/certbot/blob/master/certbot/certbot/_internal/storage.py#L1109-L1116

I think the operation to set the file ownership should be allowed to fail, and leave a warning instead. In the worst case, the file would be created with more restrictive permissions (because of BASE_PRIVKEY_MODE) instead of causing the cert renewal to fail. With the current setup, the renewal fails despite actually succeeding on the remote end, burning through precious rate limits. (Not to mention, the one-line "Operation not permitted" error shown by default made me think it was an permissions issue writing to `/etc/letsencrypt/`, so I burnt through the rate limits even more trying to fix that.)

Here's the relevant log snippet:

```
2020-06-11 19:18:49,829:DEBUG:certbot._internal.storage:Writing new private key to /etc/letsencrypt/archive/<redacted>/privkey10.pem.
2020-06-11 19:18:49,829:ERROR:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/certbot/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/opt/certbot/lib/python3.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 1233, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/main.py", line 116, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/renewal.py", line 313, in renew_cert
    lineage.save_successor(prior_version, new_cert, new_key.pem, new_chain, config)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/_internal/storage.py", line 1116, in save_successor
    old_privkey, target["privkey"], mode, copy_user=False, copy_group=True)
  File "/opt/certbot/lib/python3.7/site-packages/certbot/compat/filesystem.py", line 73, in copy_ownership_and_apply_mode
    os.chown(dst, user_id, group_id)
PermissionError: [Errno 1] Operation not permitted: '/etc/letsencrypt/archive/<redacted>/privkey10.pem'
```

**Comment by bmw** [comment]
Making this change complicates our code and the possible cases for the user after Certbot runs, but we should pretty much avoid failing writing the obtained certificate to disk at all costs.

I think we'd accept a well written PR making this change allowing `copy_ownership_and_apply_mode` to fail here.

**Comment by xiruizhao** [comment]
@jlu5's use case is granting read access to TLS certificates to certain non-root system users, since currently only the root user has access to TLS certificates. This is achieved by
1. create a system group for TLS certificates access and add the target user to it (`addgroup --system certbot`, `adduser <target_user> certbot`).
2. change `/etc/letsencrypt`'s group to `certbot`, add group read permission for files, and add group executable permission and set setgid bit for directories (`chgrp -R certbot /etc/letsencrypt`,  `find /etc
/letsencrypt -type f -exec chmod g+r '{}' \; -o -type d -exec chmod g+rxs '{}' \;`).

With this setup, `certbot renew --force-renewal` succeeds on my machine (Ubuntu 20.04 LTS), so I don't think certbot's code should be changed . However, I think certbot should consider adopting the setup I just described or add it to documentation.

@jlu5 I don't think you should create a non-root system user for certbot, since certbot may need to be root to write nginx confs to obtain certificates. However, this does not apply if you use other plugins.

**Comment by Soberia** [comment]
Same situation here on the Docker container with a non-privileged user, the certificate was issued successfully but it has failed to be stored on the disk:

```
2023-12-12 05:11:16,332:DEBUG:acme.client:Storing nonce: 5L5O4-*
2023-12-12 05:11:16,335:INFO:certbot._internal.client:Non-standard path(s), might not work with crontab installed by your operating system package manager
2023-12-12 05:11:16,336:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1869, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1600, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 143, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 528, in obtain_and_enroll_certificate
    return storage.RenewableCert.new_lineage(
  File "/opt/certbot/src/certbot/certbot/_internal/storage.py", line 1074, in new_lineage
    _write_live_readme_to(base_readme_path, is_base_dir=True)
  File "/opt/certbot/src/certbot/certbot/_internal/storage.py", line 252, in _write_live_readme_to
    with open(readme_path, "w") as f:
PermissionError: [Errno 13] Permission denied: '/etc/letsencrypt/live/README'
2023-12-12 05:11:16,341:ERROR:certbot._internal.log:An unexpected error occurred:
2023-12-12 05:11:16,342:ERROR:certbot._internal.log:PermissionError: [Errno 13] Permission denied: '/etc/letsencrypt/live/README'
```

Surprisingly enough DNS challenge will finish successfully without any file premission error but no luck with the HTTP challenge.
