### ISSUE TITLE
Missing modules when installing certbot on Amazon Linux AMI

### ISSUE THREAD

**Issue by nickweavers** [certbot/certbot#8074]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
```
$ cat /etc/system-release
Amazon Linux AMI release 2018.03
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:
```
$ certbot-auto --version
Requesting to rerun /usr/local/bin/certbot-auto with root privileges...
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 2, in <module>
    from certbot._internal import main as internal_main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/_internal/main.py", line 10, in <module>
    import josepy as jose
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/__init__.py", line 41, in <module>
    from josepy.interfaces import JSONDeSerializable
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/interfaces.py", line 7, in <module>
    from josepy import errors, util
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/josepy/util.py", line 7, in <module>
    import OpenSSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
ImportError: No module named cryptography
```

## Certbot's behavior differed from what I expected because:
The certbot command won't even run

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
$ ls -la /var/log/letsencrypt
ls: cannot access /var/log/letsencrypt: No such file or directory
```

## Additional notes:

I came across this post https://community.letsencrypt.org/t/amazon-linux-importerror-no-module-named-cryptography-hazmat-bindings-openssl-binding/60299/3 and found that the suggested command worked for me if I added sudo
```
$ sudo /opt/eff.org/certbot/venv/local/bin/pip install cryptography interface
Collecting cryptography
  Using cached https://files.pythonhosted.org/packages/5f/fc/a92bad2460d349ee9eb868f9f9dcddb7c8f42a45677d53a5c663fa251e75/cryptography-2.9.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting interface
  Downloading https://files.pythonhosted.org/packages/f9/80/7283dfe76ceb7eb1868cf97b8c8cb3a988f80757921341f95d5420de2a6e/Interface-2.11.1.tar.gz
Collecting cffi!=1.11.3,>=1.8 (from cryptography)
  Using cached https://files.pythonhosted.org/packages/08/29/8001b940ef40e7a25ffe8f3188bc9b118934b513d64f769dbf461e46f4ed/cffi-1.14.0-cp27-cp27mu-manylinux1_x86_64.whl
Requirement already satisfied: six>=1.4.1 in /opt/eff.org/certbot/venv/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied: ipaddress; python_version < "3" in /opt/eff.org/certbot/venv/lib/python2.7/dist-packages (from cryptography)
Requirement already satisfied: enum34; python_version < "3" in /opt/eff.org/certbot/venv/lib/python2.7/dist-packages (from cryptography)
Collecting zope.interface (from interface)
  Using cached https://files.pythonhosted.org/packages/e7/b6/426a95296d767b6703b485bb2b53806270729c81a0204c131b9ae73d282b/zope.interface-5.1.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting zope.schema (from interface)
  Downloading https://files.pythonhosted.org/packages/94/58/f224f1237d6cf27109e2b00806001636322766f49a2b2a64ba49ed11f1e5/zope.schema-6.0.0-py2.py3-none-any.whl (85kB)
    100% |################################| 92kB 6.9MB/s
Requirement already satisfied: pycparser in /opt/eff.org/certbot/venv/lib/python2.7/dist-packages (from cffi!=1.11.3,>=1.8->cryptography)
Requirement already satisfied: setuptools in /opt/eff.org/certbot/venv/lib/python2.7/dist-packages (from zope.interface->interface)
Requirement already satisfied: zope.event in /opt/eff.org/certbot/venv/lib/python2.7/dist-packages (from zope.schema->interface)
Building wheels for collected packages: interface
  Running setup.py bdist_wheel for interface ... done
  Stored in directory: /root/.cache/pip/wheels/67/ff/9c/32ef7f63060382c02ba8b1f8f33fed59987378e119da38835f
Successfully built interface
Installing collected packages: cffi, cryptography, zope.interface, zope.schema, interface
Successfully installed cffi-1.14.0 cryptography-2.9.2 interface-2.11.1 zope.interface-5.1.0 zope.schema-6.0.0
You are using pip version 9.0.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

but when I tried to issue the cetbot-auto --help command again I got:

```
$ certbot-auto --help
Requesting to rerun /usr/local/bin/certbot-auto with root privileges...
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 2, in <module>
    from certbot._internal import main as internal_main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/_internal/main.py", line 11, in <module>
    import zope.component
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 23, in <module>
    from zope.component.interfaces import IComponentArchitecture
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/zope/component/interfaces.py", line 21, in <module>
    import zope.deferredimport
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/zope/deferredimport/__init__.py", line 1, in <module>
    from zope.deferredimport.deferredmodule import initialize
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/zope/deferredimport/deferredmodule.py", line 18, in <module>
    import zope.proxy
ImportError: No module named proxy
```

So I tried:

```
$ sudo /opt/eff.org/certbot/venv/local/bin/pip install proxy
Collecting proxy
  Downloading https://files.pythonhosted.org/packages/56/a0/fd0b0b4bb6dfc6c1feae51201ba403624e40af554a21168591af305a6cbc/proxy-0.0.1-py2.py3-none-any.whl
Installing collected packages: proxy
Successfully installed proxy-0.0.1
You are using pip version 9.0.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

But this time it didn't solve the problem as rerunning certbot-auto again still gave 

```
$ certbot-auto --help
Requesting to rerun /usr/local/bin/certbot-auto with root privileges...
Error: couldn't get currently installed version for /opt/eff.org/certbot/venv/bin/letsencrypt:
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/bin/letsencrypt", line 7, in <module>
    from certbot.main import main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/main.py", line 2, in <module>
    from certbot._internal import main as internal_main
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/certbot/_internal/main.py", line 11, in <module>
    import zope.component
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/zope/component/__init__.py", line 23, in <module>
    from zope.component.interfaces import IComponentArchitecture
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/zope/component/interfaces.py", line 21, in <module>
    import zope.deferredimport
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/zope/deferredimport/__init__.py", line 1, in <module>
    from zope.deferredimport.deferredmodule import initialize
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/dist-packages/zope/deferredimport/deferredmodule.py", line 18, in <module>
    import zope.proxy
ImportError: No module named proxy
```

**Comment by schoen** [comment]
Hi @nickweavers,

I'm sorry you're having trouble with `certbot-auto`.

Could you try asking about your situation on https://community.letsencrypt.org/? There will be more people there who may be able to help you than here on our issue tracker.

However, I also think @bmw may also wish to say that `certbot-auto` is unsupported on your distribution, so I'll give him the opportunity to weigh in on that.

**Comment by bmw** [comment]
In the 4.5 years its been around, certbot-auto has never worked reliably on Amazon Linux. https://github.com/certbot/certbot/issues/6505 is the general issue tracking support for that, but until that's resolved the few of us working on Certbot won't be able to help you debug the various issues you may hit on the system.

You can try the community forum or you can try running [Certbot in Docker](https://certbot.eff.org/docs/install.html#running-with-docker).

I'm closing this issue in favor of #6505.
