### ISSUE TITLE
DistributionNotFound: soupsieve<2.0

### ISSUE THREAD

**Issue by erolj** [certbot/certbot#8099]
## My operating system is (include version):
CentOS Linux release 7.8.2003 (Core)
Linux 3.10.0-1127.el7.x86_64

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
https://certbot.eff.org/lets-encrypt/centosrhel7-apache
https://certbot-dns-cloudflare.readthedocs.io/en/stable/
```
yum install -y certbot python2-certbot-apache
yum install -y python2-certbot-dns-cloudflare
git clone https://github.com/cloudflare/python-cloudflare 
cd python-cloudflare
./setup.py build
./setup.py install

```
## I ran this command and it produced this output:
```
Cloning into 'python-cloudflare'...
remote: Enumerating objects: 163, done.
remote: Counting objects: 100% (163/163), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 1775 (delta 97), reused 120 (delta 63), pack-reused 1612
Receiving objects: 100% (1775/1775), 577.94 KiB | 486.00 KiB/s, done.
Resolving deltas: 100% (1152/1152), done.
running build
running build_py
creating build
creating build/lib
creating build/lib/cli4
copying cli4/__init__.py -> build/lib/cli4
copying cli4/__main__.py -> build/lib/cli4
copying cli4/cli4.py -> build/lib/cli4
copying cli4/converters.py -> build/lib/cli4
creating build/lib/examples
copying examples/__init__.py -> build/lib/examples
copying examples/example_always_use_https.py -> build/lib/examples
copying examples/example_are_zones_ipv6.py -> build/lib/examples
copying examples/example_are_zones_ipv6_simple.py -> build/lib/examples
copying examples/example_certificates.py -> build/lib/examples
copying examples/example_create_zone_and_populate.py -> build/lib/examples
copying examples/example_delete_zone_entry.py -> build/lib/examples
copying examples/example_dns_export.py -> build/lib/examples
copying examples/example_dnssec_settings.py -> build/lib/examples
copying examples/example_ips.py -> build/lib/examples
copying examples/example_list_api_from_web.py -> build/lib/examples
copying examples/example_paging_thru_zones.py -> build/lib/examples
copying examples/example_proxied.py -> build/lib/examples
copying examples/example_settings.py -> build/lib/examples
copying examples/example_update_dynamic_dns.py -> build/lib/examples
copying examples/example_user.py -> build/lib/examples
copying examples/example_with_usage.py -> build/lib/examples
copying examples/example_zones.py -> build/lib/examples
creating build/lib/CloudFlare
copying CloudFlare/__init__.py -> build/lib/CloudFlare
copying CloudFlare/api_decode_from_web.py -> build/lib/CloudFlare
copying CloudFlare/api_extras.py -> build/lib/CloudFlare
copying CloudFlare/api_v4.py -> build/lib/CloudFlare
copying CloudFlare/cloudflare.py -> build/lib/CloudFlare
copying CloudFlare/exceptions.py -> build/lib/CloudFlare
copying CloudFlare/logging_helper.py -> build/lib/CloudFlare
copying CloudFlare/read_configs.py -> build/lib/CloudFlare
copying CloudFlare/utils.py -> build/lib/CloudFlare
running egg_info
creating cloudflare.egg-info
writing requirements to cloudflare.egg-info/requires.txt
writing cloudflare.egg-info/PKG-INFO
writing top-level names to cloudflare.egg-info/top_level.txt
writing dependency_links to cloudflare.egg-info/dependency_links.txt
writing entry points to cloudflare.egg-info/entry_points.txt
writing manifest file 'cloudflare.egg-info/SOURCES.txt'
reading manifest file 'cloudflare.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cloudflare.egg-info/SOURCES.txt'
copying examples/example_page_rules.sh -> build/lib/examples
copying examples/example_paging_thru_zones.sh -> build/lib/examples
copying examples/example_zone_search.sh -> build/lib/examples
running install
running bdist_egg
running egg_info
writing requirements to cloudflare.egg-info/requires.txt
writing cloudflare.egg-info/PKG-INFO
writing top-level names to cloudflare.egg-info/top_level.txt
writing dependency_links to cloudflare.egg-info/dependency_links.txt
writing entry points to cloudflare.egg-info/entry_points.txt
reading manifest file 'cloudflare.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cloudflare.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/cli4
copying build/lib/cli4/__init__.py -> build/bdist.linux-x86_64/egg/cli4
copying build/lib/cli4/__main__.py -> build/bdist.linux-x86_64/egg/cli4
copying build/lib/cli4/cli4.py -> build/bdist.linux-x86_64/egg/cli4
copying build/lib/cli4/converters.py -> build/bdist.linux-x86_64/egg/cli4
creating build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/__init__.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_always_use_https.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_are_zones_ipv6.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_are_zones_ipv6_simple.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_certificates.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_create_zone_and_populate.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_delete_zone_entry.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_dns_export.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_dnssec_settings.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_ips.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_list_api_from_web.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_paging_thru_zones.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_proxied.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_settings.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_update_dynamic_dns.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_user.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_with_usage.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_zones.py -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_page_rules.sh -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_paging_thru_zones.sh -> build/bdist.linux-x86_64/egg/examples
copying build/lib/examples/example_zone_search.sh -> build/bdist.linux-x86_64/egg/examples
creating build/bdist.linux-x86_64/egg/CloudFlare
copying build/lib/CloudFlare/__init__.py -> build/bdist.linux-x86_64/egg/CloudFlare
copying build/lib/CloudFlare/api_decode_from_web.py -> build/bdist.linux-x86_64/egg/CloudFlare
copying build/lib/CloudFlare/api_extras.py -> build/bdist.linux-x86_64/egg/CloudFlare
copying build/lib/CloudFlare/api_v4.py -> build/bdist.linux-x86_64/egg/CloudFlare
copying build/lib/CloudFlare/cloudflare.py -> build/bdist.linux-x86_64/egg/CloudFlare
copying build/lib/CloudFlare/exceptions.py -> build/bdist.linux-x86_64/egg/CloudFlare
copying build/lib/CloudFlare/logging_helper.py -> build/bdist.linux-x86_64/egg/CloudFlare
copying build/lib/CloudFlare/read_configs.py -> build/bdist.linux-x86_64/egg/CloudFlare
copying build/lib/CloudFlare/utils.py -> build/bdist.linux-x86_64/egg/CloudFlare
byte-compiling build/bdist.linux-x86_64/egg/cli4/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/cli4/__main__.py to __main__.pyc
byte-compiling build/bdist.linux-x86_64/egg/cli4/cli4.py to cli4.pyc
byte-compiling build/bdist.linux-x86_64/egg/cli4/converters.py to converters.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_always_use_https.py to example_always_use_https.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_are_zones_ipv6.py to example_are_zones_ipv6.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_are_zones_ipv6_simple.py to example_are_zones_ipv6_simple.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_certificates.py to example_certificates.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_create_zone_and_populate.py to example_create_zone_and_populate.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_delete_zone_entry.py to example_delete_zone_entry.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_dns_export.py to example_dns_export.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_dnssec_settings.py to example_dnssec_settings.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_ips.py to example_ips.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_list_api_from_web.py to example_list_api_from_web.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_paging_thru_zones.py to example_paging_thru_zones.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_proxied.py to example_proxied.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_settings.py to example_settings.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_update_dynamic_dns.py to example_update_dynamic_dns.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_user.py to example_user.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_with_usage.py to example_with_usage.pyc
byte-compiling build/bdist.linux-x86_64/egg/examples/example_zones.py to example_zones.pyc
byte-compiling build/bdist.linux-x86_64/egg/CloudFlare/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/CloudFlare/api_decode_from_web.py to api_decode_from_web.pyc
byte-compiling build/bdist.linux-x86_64/egg/CloudFlare/api_extras.py to api_extras.pyc
byte-compiling build/bdist.linux-x86_64/egg/CloudFlare/api_v4.py to api_v4.pyc
byte-compiling build/bdist.linux-x86_64/egg/CloudFlare/cloudflare.py to cloudflare.pyc
byte-compiling build/bdist.linux-x86_64/egg/CloudFlare/exceptions.py to exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/CloudFlare/logging_helper.py to logging_helper.pyc
byte-compiling build/bdist.linux-x86_64/egg/CloudFlare/read_configs.py to read_configs.pyc
byte-compiling build/bdist.linux-x86_64/egg/CloudFlare/utils.py to utils.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/man
creating build/bdist.linux-x86_64/egg/man/man1
copying cli4/cli4.man -> build/bdist.linux-x86_64/egg/man/man1
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cloudflare.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/cloudflare-2.8.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing cloudflare-2.8.1-py2.7.egg
Copying cloudflare-2.8.1-py2.7.egg to /usr/lib/python2.7/site-packages
Adding cloudflare 2.8.1 to easy-install.pth file
Installing cli4 script to /usr/bin

Installed /usr/lib/python2.7/site-packages/cloudflare-2.8.1-py2.7.egg
Processing dependencies for cloudflare==2.8.1
Searching for beautifulsoup4
Reading https://pypi.python.org/simple/beautifulsoup4/
Best match: beautifulsoup4 4.9.1
Downloading https://files.pythonhosted.org/packages/c6/62/8a2bef01214eeaa5a4489eca7104e152968729512ee33cb5fbbc37a896b7/beautifulsoup4-4.9.1.tar.gz#sha256=73cc4d115b96f79c7d77c1c7f7a0a8d4c57860d1041df407dd1aae7f07a77fd7
Processing beautifulsoup4-4.9.1.tar.gz
Writing /tmp/easy_install-SPSFxp/beautifulsoup4-4.9.1/setup.cfg
Running beautifulsoup4-4.9.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SPSFxp/beautifulsoup4-4.9.1/egg-dist-tmp-KMpmKy
/usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'long_description_content_type'
  warnings.warn(msg)
zip_safe flag not set; analyzing archive contents...
bs4.__init__: module references __file__
Adding beautifulsoup4 4.9.1 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/beautifulsoup4-4.9.1-py2.7.egg
Searching for jsonlines
Reading https://pypi.python.org/simple/jsonlines/
Best match: jsonlines 1.2.0
Downloading https://files.pythonhosted.org/packages/90/cd/0beacbcfdf9b3af9e7c615cb3dba7ec4be1030d4b283e3c9717e3fd9af3c/jsonlines-1.2.0.tar.gz#sha256=43b8d5588a9d4862c8a4a49580e38e20ec595aee7ad6fe469b10fb83fbefde88
Processing jsonlines-1.2.0.tar.gz
Writing /tmp/easy_install-4gQXV2/jsonlines-1.2.0/setup.cfg
Running jsonlines-1.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-4gQXV2/jsonlines-1.2.0/egg-dist-tmp-2mf3ZI
zip_safe flag not set; analyzing archive contents...
Adding jsonlines 1.2.0 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/jsonlines-1.2.0-py2.7.egg
Searching for soupsieve<2.0
Reading https://pypi.python.org/simple/soupsieve/
Best match: soupsieve 1.9.6
Downloading https://files.pythonhosted.org/packages/71/a0/b40ed5dcd4f64c521cdc29cfa7c4847f521c590f7835099307089eaef3ad/soupsieve-1.9.6.tar.gz#sha256=7985bacc98c34923a439967c1a602dc4f1e15f923b6fcf02344184f86cc7efaa
Processing soupsieve-1.9.6.tar.gz
Writing /tmp/easy_install-SPCmMk/soupsieve-1.9.6/setup.cfg
Running soupsieve-1.9.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SPCmMk/soupsieve-1.9.6/egg-dist-tmp-xke8ns
error: Setup script exited with error in soupsieve setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers

[root@me ~]# certbot certonly --dns-cloudflare --dns-cloudflare-credentials /PATH/TO/cloudflare.ini -d mydomain.com -d *.mydomain.com -i apache
An unexpected error occurred:
DistributionNotFound: soupsieve<2.0
Please see the logfile '/tmp/tmpfeVUUA/log' for more details.
```

## Certbot's behavior differed from what I expected because:
Running with manual config resulting in the same error.
```
[root@me ~]# certbot certonly --manual
An unexpected error occurred:
DistributionNotFound: soupsieve<2.0
Please see the logfile '/tmp/tmpOOfAdz/log' for more details.
```

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
[root@me ~]# cat /tmp/tmpfeVUUA/log
2020-06-20 10:45:57,430:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/bin/certbot", line 9, in <module>
    load_entry_point('certbot==1.4.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 1317, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python2.7/site-packages/certbot/_internal/plugins/disco.py", line 207, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/plugins/disco.py", line 54, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2259, in load
    if require: self.require(env, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2272, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
DistributionNotFound: soupsieve<2.0
2020-06-20 10:45:57,430:ERROR:certbot._internal.log:An unexpected error occurred:
```

## Here is the relevant Apache virtualhost for the domain I am configuring:
```
<VirtualHost xxx.xxx.xxx.xxx:80>
	SuexecUserGroup "#1002" "#1002"
	ServerName mydomain.com
	ServerAlias www.mydomain.com
	ServerAlias mail.mydomain.com
	ServerAlias webmail.mydomain.com
	ServerAlias admin.mydomain.com
	DocumentRoot /home/mydomain/public_html
	ErrorLog /var/log/virtualmin/mydomain.com_error_log
	CustomLog /var/log/virtualmin/mydomain.com_access_log combined
	ScriptAlias /cgi-bin/ /home/mydomain/cgi-bin/
	ScriptAlias /awstats/ /home/mydomain/cgi-bin/
	DirectoryIndex index.html index.htm index.php index.php4 index.php5
	<Directory /home/mydomain/public_html>
		Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch +ExecCGI
		allow from all
		AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
		Require all granted
		AddType application/x-httpd-php .php
		AddHandler fcgid-script .php
		AddHandler fcgid-script .php5
		AddHandler fcgid-script .php7.2
		FCGIWrapper /home/mydomain/fcgi-bin/php7.2.fcgi .php
		FCGIWrapper /home/mydomain/fcgi-bin/php5.fcgi .php5
		FCGIWrapper /home/mydomain/fcgi-bin/php7.2.fcgi .php7.2
	</Directory>
	<Directory /home/mydomain/cgi-bin>
		allow from all
		AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
		Require all granted
	</Directory>
	RewriteEngine on
	RewriteCond %{HTTP_HOST} =webmail.mydomain.com
	RewriteRule ^(.*) https://mydomain.com:20000/ [R]
	RewriteCond %{HTTP_HOST} =admin.mydomain.com
	RewriteRule ^(.*) https://mydomain.com:10000/ [R]
	RemoveHandler .php
	RemoveHandler .php5
	RemoveHandler .php7.2
	php_admin_value engine Off
	FcgidMaxRequestLen 1073741824
	<Files awstats.pl>
		AuthName "mydomain.com statistics"
		AuthType Basic
		AuthUserFile /home/mydomain/.awstats-htpasswd
	require valid-user
	</Files>
	Alias /dav /home/mydomain/public_html
	<Location /dav>
		DAV on
		AuthType Basic
		AuthName "mydomain.com"
		AuthUserFile /home/mydomain/etc/dav.digest.passwd
		Require valid-user
		ForceType text/plain
		Satisfy All
		RemoveHandler .php
		RemoveHandler .php5
		RemoveHandler .php7.2
		RewriteEngine off
	</Location>
</VirtualHost>
<VirtualHost xxx.xxx.xxx.xxx:443>
	SuexecUserGroup "#1002" "#1002"
	ServerName mydomain.com
	ServerAlias www.mydomain.com
	ServerAlias mail.mydomain.com
	ServerAlias webmail.mydomain.com
	ServerAlias admin.mydomain.com
	DocumentRoot /home/mydomain/public_html
	ErrorLog /var/log/virtualmin/mydomain.com_error_log
	CustomLog /var/log/virtualmin/mydomain.com_access_log combined
	ScriptAlias /cgi-bin/ /home/mydomain/cgi-bin/
	ScriptAlias /awstats/ /home/mydomain/cgi-bin/
	DirectoryIndex index.html index.htm index.php index.php4 index.php5
	<Directory /home/mydomain/public_html>
		Options -Indexes +IncludesNOEXEC +SymLinksIfOwnerMatch +ExecCGI
		allow from all
		AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
		Require all granted
		AddType application/x-httpd-php .php
		AddHandler fcgid-script .php
		AddHandler fcgid-script .php5
		AddHandler fcgid-script .php7.2
		FCGIWrapper /home/mydomain/fcgi-bin/php7.2.fcgi .php
		FCGIWrapper /home/mydomain/fcgi-bin/php5.fcgi .php5
		FCGIWrapper /home/mydomain/fcgi-bin/php7.2.fcgi .php7.2
	</Directory>
		<Directory /home/mydomain/cgi-bin>
		allow from all
		AllowOverride All Options=ExecCGI,Includes,IncludesNOEXEC,Indexes,MultiViews,SymLinksIfOwnerMatch
		Require all granted
	</Directory>
	RewriteEngine on
	RewriteCond %{HTTP_HOST} =webmail.mydomain.com
	RewriteRule ^(.*) https://mydomain.com:20000/ [R]
	RewriteCond %{HTTP_HOST} =admin.mydomain.com
	RewriteRule ^(.*) https://mydomain.com:10000/ [R]
	RemoveHandler .php
	RemoveHandler .php5
	RemoveHandler .php7.2
	php_admin_value engine Off
	FcgidMaxRequestLen 1073741824
	SSLEngine on
	SSLCertificateFile /home/mydomain/ssl.cert
	SSLCertificateKeyFile /home/mydomain/ssl.key
	SSLProtocol all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
	<Files awstats.pl>
		AuthName "mydomain.com statistics"
		AuthType Basic
		AuthUserFile /home/mydomain/.awstats-htpasswd
		require valid-user
	</Files>
	Alias /dav /home/mydomain/public_html
	<Location /dav>
		DAV on
		AuthType Basic
		AuthName "mydomain.com"
		AuthUserFile /home/mydomain/etc/dav.digest.passwd
		Require valid-user
		ForceType text/plain
		Satisfy All
		RemoveHandler .php
		RemoveHandler .php5
		RemoveHandler .php7.2
		RewriteEngine off
	</Location>
	SSLCACertificateFile /home/mydomain/ssl.ca
</VirtualHost>
```

**Comment by alexzorin** [comment]
For what reason are you installing `python-cloudflare` from source?

**Comment by JialuZhang** [comment]
@erolj @alexzorin 

In your configuration,
```
	<Location /dav>
		DAV on
		AuthType Basic
		AuthName "mydomain.com"
		AuthUserFile /home/mydomain/etc/dav.digest.passwd
		Require valid-user
		ForceType text/plain
		Satisfy All
		RemoveHandler .php
		RemoveHandler .php5
		RemoveHandler .php7.2
		RewriteEngine off
	</Location>
```
the line "RewriteEngine Off“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine Off" is introduced by Apache to explicitly disable all "RewriteRule" and "RewriteCond".
That is to say, if you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then instead of commenting them all, you can explicitly set “RewriteEngine Off” to disable all "RewriteRule".
More importantly, the default value of “RewriteEngine" is already an "off", so adding “RewriteEngine off" is quite unnecessary and it may cause confusion to users.
Since herein there is no "RewriteRule" in this directory, deleting “RewriteEngine Off” would be ideal.
Related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
