### ISSUE TITLE
cant generate cert

### ISSUE THREAD

**Issue by DevDorrejo** [certbot/certbot#8124]
i cant generate cert for any of the domain, help pls

If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## I ran this command and it produced this output: certbot --apache
`certbot --apache
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Could not find ssl_module; not disabling session tickets.
Plugins selected: Authenticator apache, Installer apache

Which names would you like to activate HTTPS for?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: astian.org
2: abc.astian.org
3: www.abc.astian.org
4: example.astian.org
5: www.example
[letsencrypt.log](https://github.com/certbot/certbot/files/4866018/letsencrypt.log)
.astian.org
6: example.astian.org
7: www.example.astian.org
8: example.astian.org
9: www.example.astian.org
10: example.astian.org
11: www.example.astian.org
12: www.astian.org
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate numbers separated by commas and/or spaces, or leave input
blank to select all options shown (Enter 'c' to cancel): 1
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for astian.org
Waiting for verification...
Challenge failed for domain astian.org
http-01 challenge for astian.org
Cleaning up challenges
Some challenges have failed.

IMPORTANT NOTES:
- The following errors were reported by the server:

Domain: astian.org
Type:   unauthorized
Detail: Invalid response from
http://astian.org/.well-known/acme-challenge/v_XPmYvxdCFz5PeDESmtEcnuh6bZJKTaed_hl6JIHSc
[5.9.70.7]: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE
html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n
\"http://www.w3.org/TR/xhtml1/D"

To fix these errors, please make sure that your domain name was
entered correctly and the DNS A/AAAA record(s) for that domain
contain(s) the right IP address.`

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2020-07-02 14:22:54,364:DEBUG:certbot._internal.main:certbot version: 1.4.0
2020-07-02 14:22:54,365:DEBUG:certbot._internal.main:Arguments: ['--apache']
2020-07-02 14:22:54,365:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-07-02 14:22:54,377:DEBUG:certbot._internal.log:Root logging level set at 20
2020-07-02 14:22:54,378:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-07-02 14:22:54,378:DEBUG:certbot._internal.plugins.selection:Requested authenticator apache and installer apache
2020-07-02 14:22:54,446:DEBUG:certbot_apache._internal.configurator:Apache version is 2.4.43
2020-07-02 14:22:54,770:WARNING:certbot_apache._internal.configurator:Could not find ssl_module; not disabling session tickets.
2020-07-02 14:22:54,771:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT
Initialized: <certbot_apache._internal.override_suse.OpenSUSEConfigurator object at 0x7f44d8cdc320>
Prep: True
2020-07-02 14:22:54,772:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_apache._internal.override_suse.OpenSUSEConfigurator object at 0x7f44d8cdc320> and installer <certbot_apache._internal.override_suse.OpenSUSEConfigurator object at 0x7f44d8cdc320>
2020-07-02 14:22:54,772:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator apache, Installer apache
2020-07-02 14:22:54,776:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/90342359', new_authzr_uri=None, terms_of_service=None), e548ecb21e7fe034383606c1aa947a22, Meta(creation_dt=datetime.datetime(2020, 7, 2, 18, 6, 3, tzinfo=<UTC>), creation_host='server00.astian.org'))>
2020-07-02 14:22:54,777:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2020-07-02 14:22:54,778:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2020-07-02 14:22:55,369:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2020-07-02 14:22:55,370:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 02 Jul 2020 18:22:55 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "TIKXg6-S5vE": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2020-07-02 14:22:56,528:INFO:certbot._internal.main:Obtaining a new certificate
2020-07-02 14:22:56,765:DEBUG:certbot.crypto_util:Generating key (2048 bits): /etc/letsencrypt/keys/0002_key-certbot.pem
2020-07-02 14:22:56,767:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0002_csr-certbot.pem
2020-07-02 14:22:56,767:DEBUG:acme.client:Requesting fresh nonce
2020-07-02 14:22:56,767:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2020-07-02 14:22:56,914:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2020-07-02 14:22:56,915:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 02 Jul 2020 18:22:56 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002A5Wkyry59GJ4TmXkHFkAznMJA8Tgz-KNO7RPbQriQcI
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2020-07-02 14:22:56,915:DEBUG:acme.client:Storing nonce: 0002A5Wkyry59GJ4TmXkHFkAznMJA8Tgz-KNO7RPbQriQcI
2020-07-02 14:22:56,915:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "astian.org"\n    }\n  ]\n}'
2020-07-02 14:22:56,918:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTAzNDIzNTkiLCAibm9uY2UiOiAiMDAwMkE1V2t5cnk1OUdKNFRtWGtIRmtBem5NSkE4VGd6LUtOTzdSUGJRcmlRY0kiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "Fqnfm3h-__LfKHYJ9uSO0nKtfAJ6btiycRkL0JqEc93sJnIu8HpiCV2V3rVqeOlNRFuxwaqCLIgUb5f-Q8YIzPaQubhfng1jSTbqV9tylGo22MhC8wDY6r4D3gQZ2jbOdU2B14ECV2Xv72M22e9fY8S3NfK6jgD_G7hHRaopCxs2JmL15ZdG8NLlDLoTVuRnsXIFnubyU6EHSNohWf2qa6j8zfYRmJS21p4g8LzhhSl672j1dSnouZh3J-i8MfWA8U58h-eieX7AUKqTntbp_qve2x2_JS6HedWgU4fNCrVQJgPU9X1FLhnwhDpVamVKWo7DwnXEpxcr30BUJnnogw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImFzdGlhbi5vcmciCiAgICB9CiAgXQp9"
}
2020-07-02 14:22:57,091:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 340
2020-07-02 14:22:57,092:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Thu, 02 Jul 2020 18:22:56 GMT
Content-Type: application/json
Content-Length: 340
Connection: keep-alive
Boulder-Requester: 90342359
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/90342359/4024868774
Replay-Nonce: 0002VN11kkymhY1zoISk2jEBM4OCdPX6syfjlVjxWxGpH3M
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2020-07-09T18:22:56.970471359Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "astian.org"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/5624377239"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/90342359/4024868774"
}
2020-07-02 14:22:57,092:DEBUG:acme.client:Storing nonce: 0002VN11kkymhY1zoISk2jEBM4OCdPX6syfjlVjxWxGpH3M
2020-07-02 14:22:57,093:DEBUG:acme.client:JWS payload:
b''
2020-07-02 14:22:57,096:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/5624377239:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTAzNDIzNTkiLCAibm9uY2UiOiAiMDAwMlZOMTFra3ltaFkxem9JU2syakVCTTRPQ2RQWDZzeWZqbFZqeFd4R3BIM00iLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzU2MjQzNzcyMzkifQ",
  "signature": "C6qNLsR_H53KkgRbV8s08X17TupjdQQqgQb_XWLHl4KXuVnSOCZr7EVUv0kMvdxjwo68vdkDRRWHBfLGhwYYo_-Y6Rl6pphzNAMjQwfMwiyCoWQ1gvklpiJzipbUm5vbpl4o2bY2SdDhEl7WKzxHKADcBf3nXnqNhTH799ohgFUfXc1_m3g5lbxEBRx9OEvESGRBmE-jOruJ3eJ-1Un0-wQ840aDcRZCiA8xwpZC38VzzO2nNe3qMBw-W4Jz2gOv8lfq3Bg4wCiQKLmasOpwdEk7x1itSc1fW_SC1SKjygkwY4bXFpomK5t7b9Sqn68sk35rgJ3UeknZGzXeP9zoTQ",
  "payload": ""
}
2020-07-02 14:22:57,247:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/5624377239 HTTP/1.1" 200 788
2020-07-02 14:22:57,248:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 02 Jul 2020 18:22:57 GMT
Content-Type: application/json
Content-Length: 788
Connection: keep-alive
Boulder-Requester: 90342359
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0002dOrSZPlXwlog61DhpGe04V7b212Xz4Wps3yBVlnauO8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "astian.org"
  },
  "status": "pending",
  "expires": "2020-07-09T18:22:56Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5624377239/Hw856w",
      "token": "H_XesKzQuknLboCs342tJHxFqcS7nVoAODZovNS6y3g"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5624377239/OoHKmg",
      "token": "H_XesKzQuknLboCs342tJHxFqcS7nVoAODZovNS6y3g"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5624377239/xcqWJA",
      "token": "H_XesKzQuknLboCs342tJHxFqcS7nVoAODZovNS6y3g"
    }
  ]
}
2020-07-02 14:22:57,249:DEBUG:acme.client:Storing nonce: 0002dOrSZPlXwlog61DhpGe04V7b212Xz4Wps3yBVlnauO8
2020-07-02 14:22:57,249:INFO:certbot._internal.auth_handler:Performing the following challenges:
2020-07-02 14:22:57,250:INFO:certbot._internal.auth_handler:http-01 challenge for astian.org
2020-07-02 14:22:57,291:DEBUG:certbot_apache._internal.http_01:Adding a temporary challenge validation Include for name: www.astian.org in: /etc/apache2/vhosts.d/astian.org.conf
2020-07-02 14:22:57,291:DEBUG:certbot_apache._internal.http_01:writing a pre config file with text:
         RewriteEngine on
        RewriteRule ^/\.well-known/acme-challenge/([A-Za-z0-9-_=]+)$ /var/lib/letsencrypt/http_challenges/$1 [END]
    
2020-07-02 14:22:57,292:DEBUG:certbot_apache._internal.http_01:writing a post config file with text:
         <Directory /var/lib/letsencrypt/http_challenges>
            Require all granted
        </Directory>
        <Location /.well-known/acme-challenge>
            Require all granted
        </Location>
    
2020-07-02 14:22:57,341:DEBUG:certbot.reverter:Creating backup of /etc/apache2/vhosts.d/astian.org.conf
2020-07-02 14:23:00,466:INFO:certbot._internal.auth_handler:Waiting for verification...
2020-07-02 14:23:00,466:DEBUG:acme.client:JWS payload:
b'{}'
2020-07-02 14:23:00,468:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall-v3/5624377239/Hw856w:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTAzNDIzNTkiLCAibm9uY2UiOiAiMDAwMmRPclNaUGxYd2xvZzYxRGhwR2UwNFY3YjIxMlh6NFdwczN5QlZsbmF1TzgiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLXYzLzU2MjQzNzcyMzkvSHc4NTZ3In0",
  "signature": "CGwoTTOO6rCjp_y38EBe1iNsveLQhHkbi3JBTUEU6PQWWF5CANH-R-sy8O3hcvEMOUuO9a_QEUUCQ7M28ev5ar1scYliHssROrTr7BFVpBgaaaHAvvCZanMhFjMFaGILrz82o084BFat4fSuLdDjRzMqEM77udmdq7Wq3YVpbLBu2V97UrSS_EHWqj1E7eacmRoFWevA2wil2IHhqPEa_M6aSEccA8okItNTbgscx-1q1q1Zlik_r2oY1KA-xRaeAqW5-tvO7WZaDxRq8XI0xPAHFsDcDZs1CN2Y8JpUIAwKqjuDf91EXvmcYjVHIERnpCpLQUYmQZ6oVotPZ0gThQ",
  "payload": "e30"
}
2020-07-02 14:23:00,629:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall-v3/5624377239/Hw856w HTTP/1.1" 200 185
2020-07-02 14:23:00,630:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 02 Jul 2020 18:23:00 GMT
Content-Type: application/json
Content-Length: 185
Connection: keep-alive
Boulder-Requester: 90342359
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz-v3/5624377239>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/5624377239/Hw856w
Replay-Nonce: 0001YMGLgIcbLXwM_46bFTRMT5AAOpmtkiFgzc0e9docEM8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5624377239/Hw856w",
  "token": "H_XesKzQuknLboCs342tJHxFqcS7nVoAODZovNS6y3g"
}
2020-07-02 14:23:00,630:DEBUG:acme.client:Storing nonce: 0001YMGLgIcbLXwM_46bFTRMT5AAOpmtkiFgzc0e9docEM8
2020-07-02 14:23:01,632:DEBUG:acme.client:JWS payload:
b''
2020-07-02 14:23:01,635:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/5624377239:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvOTAzNDIzNTkiLCAibm9uY2UiOiAiMDAwMVlNR0xnSWNiTFh3TV80NmJGVFJNVDVBQU9wbXRraUZnemMwZTlkb2NFTTgiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LXYzLzU2MjQzNzcyMzkifQ",
  "signature": "M5dVzctk6GYaYBC2U52Ic4fM1HIct_dOayvAaIE2lmXDDTJ6K1lU2y1hO6g6nS09xYPtksYyaxiXZFceBuIfz3xn2DbIIdSVRu_Y_ENh2_uXisWH3_4vQ-XczR6ylMSJk6hKlDLXWOmhVdexIDpNGe5kxrN-4kMAJEDP6_cUE16eQ1E4VtkP1d5xJbr16YxXO0JCfC_HtowQuRgBaxXpKuo3q1C0WUEHEbjH3F1uL5az8jVPGOQ2O1JCks6yfusufUtIglQ2SJcDJgh44vfdCHqWr1rFbtdOq7fVZ1uiXUBjhY3T4olRP8NaYtKMxOSeKATrqJ5-GSocEVf8KRM4nQ",
  "payload": ""
}
2020-07-02 14:23:01,798:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/5624377239 HTTP/1.1" 200 1118
2020-07-02 14:23:01,798:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 02 Jul 2020 18:23:01 GMT
Content-Type: application/json
Content-Length: 1118
Connection: keep-alive
Boulder-Requester: 90342359
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0001gI0c8VhuGnibAVNZxoa0s-k2INqeAwDvkn7YHT_tcv0
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "astian.org"
  },
  "status": "invalid",
  "expires": "2020-07-09T18:22:56Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "Invalid response from http://astian.org/.well-known/acme-challenge/H_XesKzQuknLboCs342tJHxFqcS7nVoAODZovNS6y3g [5.9.70.7]: \"\u003c?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?\u003e\\n\u003c!DOCTYPE html PUBLIC \\\"-//W3C//DTD XHTML 1.0 Strict//EN\\\"\\n  \\\"http://www.w3.org/TR/xhtml1/D\"",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/5624377239/Hw856w",
      "token": "H_XesKzQuknLboCs342tJHxFqcS7nVoAODZovNS6y3g",
      "validationRecord": [
        {
          "url": "http://astian.org/.well-known/acme-challenge/H_XesKzQuknLboCs342tJHxFqcS7nVoAODZovNS6y3g",
          "hostname": "astian.org",
          "port": "80",
          "addressesResolved": [
            "5.9.70.7"
          ],
          "addressUsed": "5.9.70.7"
        }
      ]
    }
  ]
}
2020-07-02 14:23:01,798:DEBUG:acme.client:Storing nonce: 0001gI0c8VhuGnibAVNZxoa0s-k2INqeAwDvkn7YHT_tcv0
2020-07-02 14:23:01,799:WARNING:certbot._internal.auth_handler:Challenge failed for domain astian.org
2020-07-02 14:23:01,799:INFO:certbot._internal.auth_handler:http-01 challenge for astian.org
2020-07-02 14:23:01,799:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: astian.org
Type:   unauthorized
Detail: Invalid response from http://astian.org/.well-known/acme-challenge/H_XesKzQuknLboCs342tJHxFqcS7nVoAODZovNS6y3g [5.9.70.7]: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n  \"http://www.w3.org/TR/xhtml1/D"

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address.
2020-07-02 14:23:01,799:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2020-07-02 14:23:01,800:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-07-02 14:23:01,800:INFO:certbot._internal.auth_handler:Cleaning up challenges
2020-07-02 14:23:01,956:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==1.4.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/main.py", line 1101, in run
    certname, lineage)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/main.py", line 121, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/client.py", line 409, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/client.py", line 343, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/client.py", line 390, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
<VirtualHost *:80>

#ServerAdmin webmaster@dummy-host.example.com
ServerName www.astian.org
ServerAlias astian.org

DocumentRoot /location/

# if not specified, the global error log is used
ErrorLog /location/error_log
CustomLog /location/access_log combined

# don't loose time with IP address lookups
HostnameLookups Off
# needed for named virtual hosts
UseCanonicalName Off
# configures the footer on server-generated documents
ServerSignature On

# Include /etc/apache2/conf.d/php5.conf
# Include /etc/apache2/conf.d/*.conf

<Directory "/location/">

Options Indexes FollowSymLinks MultiViews
AllowOverride All

<IfModule !mod_access_compat.c>
Require all granted
</IfModule>
<IfModule mod_access_compat.c>
Order allow,deny
Allow from all
</IfModule>

</Directory>

</VirtualHost>
```

**Comment by DevDorrejo** [comment]
did:
- zypper remove --clean-deps certbot (certbot 1.4.0)
- pip install certbot certbot-apache. (certbot 1.5.0)

now is working.

but this error still appear 
Could not find ssl_module; not disabling session tickets.

**Comment by bmw** [comment]
Thanks for the update.

Since that issue is tracked by https://github.com/certbot/certbot/issues/8072, I'm closing this one in favor of that one.

**Comment by DevDorrejo** [comment]
ok, but look that the one on the repo is not working, and look the log pls.

**Comment by bmw** [comment]
Ah I see. Thanks for flagging that.

I have two questions for you:

1. If you run `certbot certonly --apache -d astian.org --dry-run` with your current installation, does it succeed?
2. If you remove your Certbot installation from pip, reinstall the same package from `zypper`, and run the some command, does that succeed?

**Comment by DevDorrejo** [comment]
sorry for the late response, dont know why, but is working normally cerbot --apache but with the error of the #8072, maybe because i didnt delete the files that the pip version created that was v1.5 of certbot.

maybe some files from the pip install fix the problem of the one on the repos.

**Comment by bmw** [comment]
No worries and thanks for trying that.

If `certbot certonly --apache -d astian.org --dry-run` is working with the `certbot-apache` package from `pip` removed though, I'm probably going to close this issue unless you can find a way to reliably produce the problem.

I set up an OpenSUSE Leap 15.2 system using the configuration file you provided and was unable to reproduce the problem.

**Comment by DevDorrejo** [comment]
ok, thank you for your help, maybe my dns provider was having some problem or the ISP from them.

i will close the issue.
