### ISSUE TITLE
certbot snap searches for x86_64 libaugeus on Raspberry Pi

### ISSUE THREAD

**Issue by Thynix** [certbot/certbot#8216]
## My operating system is (include version):

Ubuntu 20.04 on a Raspberry Pi 3B

```
ubuntu@yeoman:~$ uname -a
Linux yeoman 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):

snap

## I ran this command and it produced this output:

```
ubuntu@yeoman:~$ sudo snap install --classic --edge certbot
certbot (edge) 1.7.0-59-gf7eb5b79f from Certbot Project (certbot-eff✓) installed
ubuntu@yeoman:~$ sudo certbot --apache
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
OSError: cannot load library '/snap/certbot/536/usr/lib/x86_64-linux-gnu/libaugeas.so.0': /snap/certbot/536/usr/lib/x86_64-linux-gnu/libaugeas.so.0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/snap/certbot/536/usr/lib/x86_64-linux-gnu/libaugeas.so.0'
Please see the logfiles in /var/log/letsencrypt for more details.
```

This happens both with the edge version above and the current stable `latest/stable:    1.7.0               2020-08-04 (501) 46MB classic` (which I tried first)

## Certbot's behavior differed from what I expected because:

Crash

## Here is a Certbot log showing the issue (if available):

From this portion of the log it looks like the `x86_64` portion is hardcoded:

```
  File "/snap/certbot/536/lib/python3.8/site-packages/augeas/ffi.py", line 48, in <module>
    lib = ffi.dlopen(os.path.join(os.getenv('SNAP'), "usr/lib/x86_64-linux-gnu/libaugeas.so.0"))
```

Complete log follows:

```
2020-08-15 01:53:31,813:DEBUG:certbot._internal.main:certbot version: 1.8.0.dev0
2020-08-15 01:53:31,815:DEBUG:certbot._internal.main:Arguments: ['--apache']
2020-08-15 01:53:31,816:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2020-08-15 01:53:31,932:DEBUG:certbot._internal.log:Root logging level set at 20
2020-08-15 01:53:31,933:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2020-08-15 01:53:31,940:DEBUG:certbot._internal.plugins.selection:Requested authenticator apache and installer apache
2020-08-15 01:53:33,133:DEBUG:certbot_apache._internal.configurator:Apache version is 2.4.41
2020-08-15 01:53:33,697:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/certbot/536/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot/_internal/main.py", line 1357, in main
    return config.func(config, plugins)
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot/_internal/main.py", line 1084, in run
    installer, authenticator = plug_sel.choose_configurator_plugins(config, plugins, "run")
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot/_internal/plugins/selection.py", line 223, in choose_configurator_plugins
    authenticator = installer = pick_configurator(config, req_inst, plugins)
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot/_internal/plugins/selection.py", line 22, in pick_configurator
    return pick_plugin(
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot/_internal/plugins/selection.py", line 106, in pick_plugin
    verified.prepare()
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 297, in prepare
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 297, in <listcomp>
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 157, in prepare
    self._initialized.prepare()
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot_apache/_internal/configurator.py", line 336, in prepare
    self.parser = self.get_parser()
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot_apache/_internal/configurator.py", line 441, in get_parser
    return parser.ApacheParser(
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot_apache/_internal/parser.py", line 46, in __init__
    self.init_augeas()
  File "/snap/certbot/536/lib/python3.8/site-packages/certbot_apache/_internal/parser.py", line 93, in init_augeas
    import augeas
  File "/snap/certbot/536/lib/python3.8/site-packages/augeas/__init__.py", line 42, in <module>
    from augeas.ffi import ffi, lib
  File "/snap/certbot/536/lib/python3.8/site-packages/augeas/ffi.py", line 48, in <module>
    lib = ffi.dlopen(os.path.join(os.getenv('SNAP'), "usr/lib/x86_64-linux-gnu/libaugeas.so.0"))
  File "/snap/certbot/536/lib/python3.8/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/snap/certbot/536/lib/python3.8/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/snap/certbot/536/lib/python3.8/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/snap/certbot/536/usr/lib/x86_64-linux-gnu/libaugeas.so.0': /snap/certbot/536/usr/lib/x86_64-linux-gnu/libaugeas.so.0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/snap/certbot/536/usr/lib/x86_64-linux-gnu/libaugeas.so.0'
2020-08-15 01:53:33,737:ERROR:certbot._internal.log:An unexpected error occurred:
2020-08-15 01:53:33,738:ERROR:certbot._internal.log:OSError: cannot load library '/snap/certbot/536/usr/lib/x86_64-linux-gnu/libaugeas.so.0': /snap/certbot/536/usr/lib/x86_64-linux-gnu/libaugeas.so.0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called '/snap/certbot/536/usr/lib/x86_64-linux-gnu/libaugeas.so.0'
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

I haven't gotten that far. :(

**Comment by alexzorin** [comment]
Looks to be related to #7943. The [python-augeas fork](https://github.com/hercules-team/python-augeas/compare/master...basak:snap) being used isn't accounting for the host architecture.

**Comment by bmw** [comment]
Thanks a lot for the detailed write up. You both are correct on the cause here and we'll get this fixed soon.

While it's possible to fix this without fixing https://github.com/certbot/certbot/issues/7943, I personally think we should start by trying to resolve that issue and only do something different if we hit trouble/blockers.

**Comment by JamesB192** [comment]
huh, voiding the warranty by cracking open seems to reveal that as of certbot-501.snap (1.7.0?) the string "usr/lib/x86_64-linux-gnu/" is specified in the python module augeas.ffi as well as three YAML files that appear to be trying to prepend to the LDPATH environment variable. on my rpi4 the correct path fragment would appear to be "usr/lib/aarch64-linux-gnu/". This would appear to indicate an issue with the source YAML file fed to snapcraft as weel as an augeas issue. I hope I am misinterpreting that.

**Comment by bmw** [comment]
Nope you're correct! `LD_LIBRARY_PATH` needs to be updated too. I have a branch where I've fixed both that I plan to include in our next release.

**Comment by Dnllns** [comment]
I have the same problems in rpi 2b
![Captura de pantalla de 2020-09-07 17-00-00](https://user-images.githubusercontent.com/42231443/92400467-46637680-f12c-11ea-95bb-30a2168eb881.png)

**Comment by alexzorin** [comment]
Hi @Dnllns, the fix for that is not yet released, but will be this week. Alternatively you can try the `--edge` version rather than the `--stable` version, it's available there.

**Comment by coreGreenberet** [comment]
I've just installed certbot on debian 10.7 and I'm getting the same error
![grafik](https://user-images.githubusercontent.com/3853374/103639470-b2c17b80-4f4e-11eb-9de8-6e387d4945ee.png)

I've installed certbot via --edge, but I'm getting the same error. I even tried to do a snap refresh --edge core.

**Comment by alexzorin** [comment]
@coreGreenberet unfortunately the Certbot snap doesn't support 32-bit x86 (i386). The version you have installed won't be updated and is intended for removal (#8459).

For now, installing from [apt](https://packages.debian.org/buster/python3-certbot-apache) is an alternative way to install (an older release of) Certbot on Debian 10 i386.

**Comment by ROBERT-MCDOWELL** [comment]
this issue is also present on Fedora 34 64bits
An unexpected error occurred:
OSError: cannot load library 'libaugeas.so.0': /snap/core20/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/lib64/libaugeas.so.0)

**Comment by ROBERT-MCDOWELL** [comment]
forgot the command
/var/lib/snapd/snap/certbot/1434/bin/python3 -s /snap/certbot/1434/bin/certbot -q renew
