### ISSUE TITLE
Failures when using an internal ACME CA + dns-google plugin

### ISSUE THREAD

**Issue by tashian** [certbot/certbot#8339]
## My operating system is (include version):
Ubuntu 20.04

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
snap (certbot version 1.8.0)

## Scenario
I have an internal CA and I've installed the CA root certificate into the system's trust store, and I've run `update-ca-certificates`. I'm using the `dns-google` plugin.

When I try to get a certificate from my internal CA with certbot, I get a TLS handshake error:
```bash
$ sudo certbot certonly \
  --server https://localhost:4430/acme/acme/directory \
  -n --agree-tos --email carl@smallstep.com \
  --dns-google \
  --dns-google-credentials ~/certbot-gcp-credentials.json \
  -d example.smallstep.internal
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-google, Installer None
An unexpected error occurred:
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=4430): Max retries exceeded with url: /acme/acme/directory (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```

And when I add `REQUESTS_CA_BUNDLE` and include the path to my CA root certificate, `certbot` is now able to connect to my CA, but it fails on the TLS handshake with Google.

```bash
$ sudo REQUESTS_CA_BUNDLE=~/certs/root_ca.crt certbot certonly \
  --server https://localhost:4430/acme/acme/directory \
  -n --agree-tos --email carl@smallstep.com \
  --dns-google \
  --dns-google-credentials ~/certbot-gcp-credentials.json \
  -d example.smallstep.internal
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-google, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for example.smallstep.internal
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
Cleaning up challenges
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/dns/v1/rest
Encountered exception during recovery:
Traceback (most recent call last):
  File "/snap/certbot/579/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/snap/certbot/579/lib/python3.8/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/certbot_dns_google/_internal/dns_google.py", line 70, in _perform
    self._get_google_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/certbot_dns_google/_internal/dns_google.py", line 76, in _get_google_client
    return _GoogleClient(self.conf('credentials'))
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/certbot_dns_google/_internal/dns_google.py", line 96, in __init__
    self.dns = discovery.build('dns', 'v1',
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/googleapiclient/discovery.py", line 221, in build
    content = _retrieve_discovery_doc(requested_url, http, cache_discovery,
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/googleapiclient/discovery.py", line 269, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/httplib2/__init__.py", line 1322, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/httplib2/__init__.py", line 1072, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/httplib2/__init__.py", line 995, in _conn_request
    conn.connect()
  File "/snap/certbot/579/usr/lib/python3.8/http/client.py", line 1409, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/snap/certbot/579/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/snap/certbot/579/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/snap/certbot/579/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] internal error (_ssl.c:1108)

During handling of the above exception, another exception occurred:

(repeat of same traceback as above)
```

**Comment by alexzorin** [comment]
I believe this is the same problem as https://github.com/certbot/certbot/issues/8204#issuecomment-693685615, which is being worked on.
