### ISSUE TITLE
Duplicated listen directive in Nginx+Cerbot config

### ISSUE THREAD

**Issue by Metabaron1** [certbot/certbot#8446]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version): 
Alpine Linux v3.12 (docker)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc): 
apk add --update --no-cache certbot certbot-nginx (certbot 1.4.0)

## I ran this command and it produced this output:
certbot run --non-interactive --nginx --agree-tos --no-redirect -m mymail@mydomain.com -d mydomain.com 1 --http-01-port 8000 --https-port 8443

## Certbot's behavior differed from what I expected because:
Certbot tries to add a new "Listen 8443 ssl;" directive,  instead of just adding "ssl" to the already existing "Listen 8443;" directive

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2020-11-11 04:43:34,175:DEBUG:certbot_nginx._internal.parser:Writing nginx conf tree to
 /etc/nginx/conf.d/default.conf:
server {
    server_name mydomain.com;
    location / {
      ... proxy_pass config ...
    }
    listen 8443 ;
    
    listen 8443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    server_name mydomain.com;
    listen 8000;

    location / {
       ...
    }
}
2020-11-11 04:43:34,203:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/certbot/_internal/client.py", line 521, in deploy_certificate
    self.installer.restart()
  File "/usr/lib/python3.8/site-packages/certbot_nginx/_internal/configurator.py", line 914, in restart
    nginx_restart(self.conf('ctl'), self.nginx_conf)
  File "/usr/lib/python3.8/site-packages/certbot_nginx/_internal/configurator.py", line 1185, in nginx_restart
    raise errors.MisconfigurationError(
certbot.errors.MisconfigurationError: nginx restart failed:
b''
b'default.conf:13\n'

2020-11-11 04:43:34,203:DEBUG:certbot._internal.error_handler:Calling registered functions
2020-11-11 04:43:34,204:CRITICAL:certbot._internal.client:Rolling back to previous server configuration...
2020-11-11 04:43:35,535:DEBUG:certbot._internal.reporter:Reporting to user: 
We were unable to install your certificate, however, we successfully restored yo
2020-11-11 04:43:35,536:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==1.4.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.8/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1347, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1108, in run
    _install_cert(config, le_client, domains, new_lineage)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 751, in _install_cert
    le_client.deploy_certificate(domains, path_provider.key_path,
  File "/usr/lib/python3.8/site-packages/certbot/_internal/client.py", line 521, in deploy_certificate
    self.installer.restart()
  File "/usr/lib/python3.8/site-packages/certbot_nginx/_internal/configurator.py", line 914, in restart
    nginx_restart(self.conf('ctl'), self.nginx_conf)
  File "/usr/lib/python3.8/site-packages/certbot_nginx/_internal/configurator.py", line 1185, in nginx_restart
    raise errors.MisconfigurationError(
certbot.errors.MisconfigurationError: nginx restart failed:

```
## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

```
server {
    server_name mydomain.com;
    location / {
      ... proxy_pass config ...
    }
    listen 8443 ;
}
server {
    server_name mydomain.com;
    listen 8000;

    location / {
       ...
    }
}
```

Hi all
As explained [in forum](https://community.letsencrypt.org/t/chicken-or-the-egg-initial-config-for-nginx-certbot-docker-as-non-root/138061) , I'm running Cerbot + Nginx in docker container as non root user, using ports http:8000/https:8443.
I'm looking for an elegant way to initialise Nginx config, so Cerbot can add Let's encrypt  AND protocol-related options (ssl_dhparam, ...) configs.

But : 
- if I setup an initial dummy certificate to start Nginx with ssl enabled on port 8443, Certbot replaces the Let's encrypt config but NOT protocol-related options.

- if I just start Nginx with "Listen 8443;" without ssl enabled, Certbot adds the Let's encrypt config  AND  protocol-related options. But it also tries to add a secong "Listen 8443 ssl;", but fail of course as there is already one listen directive, instead of it   just adding "ssl" to the existing directive. Or removing previous directive before adding a new one...

Because of this bug, or future ;), actually I have to start Nginx with a dummy "Listen 8444" without no ssl , so Certbot add  the requested and expected correct full ssl configuration without conflict:

```
    Listen 8444;
    listen 8443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
```
but after I have to remove the initial dummy  "Listen 8444"

I have checked certbot-nginx/certbot_nginx/_internal/configurator.py : seems that previous configs are removed before setting  new ones. But I I'm not python developper and I dont undertand why the previous "Listen 8443" is not removed before setting the "Listen 8443 ssl;". 
If I resquest a port reconfiguration from Certbot parameter (--https-port 8443), Certbot can safely assume that I'm ok if previous Listen directive is removed first, and as you can't have 2 listen directives on the same port anyway, with ssl or not.

Is it a normal behaviour and a bad use, or a bug?

Thans for help.

**Comment by Metabaron1** [comment]
Stated in forum : not a bug
