### ISSUE TITLE
Auto-renew on specific port doesn't work

### ISSUE THREAD

**Issue by uvu9Ba** [certbot/certbot#8485]
## My operating system is (include version):
CentOS 7.8

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
OS package manager -> yum -> version 1.7.0

## I ran this command and it produced this output:
`systemctl start certbot-renew.service`

```
Dec 01 00:26:15 example-lb-staging-01 systemd[1]: Starting This service automatically renews any certbot certificates found...
Dec 01 00:26:16 example-lb-staging-01 certbot[47655]: Saving debug log to /var/log/letsencrypt/letsencrypt.log
Dec 01 00:26:16 example-lb-staging-01 certbot[47655]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Dec 01 00:26:16 example-lb-staging-01 certbot[47655]: Processing
Dec 01 00:26:16 example-lb-staging-01 certbot[47655]: /etc/letsencrypt/renewal/staging.example.org.conf
Dec 01 00:26:16 example-lb-staging-01 certbot[47655]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Dec 01 00:26:16 example-lb-staging-01 certbot[47655]: Cert is due for renewal, auto-renewing...
Dec 01 00:26:16 example-lb-staging-01 certbot[47655]: Plugins selected: Authenticator standalone, Installer None
Dec 01 00:26:16 example-lb-staging-01 certbot[47655]: Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
Dec 01 00:26:16 example-lb-staging-01 certbot[47655]: Running pre-hook command: sleep 10
Dec 01 00:26:26 example-lb-staging-01 certbot[47655]: Renewing an existing certificate
Dec 01 00:26:29 example-lb-staging-01 certbot[47655]: Performing the following challenges:
Dec 01 00:26:29 example-lb-staging-01 certbot[47655]: http-01 challenge for api.staging.example.org
[...]
Dec 01 00:26:29 example-lb-staging-01 certbot[47655]: Cleaning up challenges
Dec 01 00:26:29 example-lb-staging-01 certbot[47655]: Attempting to renew cert (staging.example.org) from /etc/letsencrypt/renewal/staging.example.org.conf produced an unexpected error: Problem binding to port 80: Could not bind to IPv4 or IPv6.. Skipping.
Dec 01 00:26:29 example-lb-staging-01 certbot[47655]: All renewal attempts failed. The following certs could not be renewed:
Dec 01 00:26:29 example-lb-staging-01 certbot[47655]: /etc/letsencrypt/live/staging.example.org/fullchain.pem (failure)
Dec 01 00:26:29 example-lb-staging-01 certbot[47655]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Dec 01 00:26:29 example-lb-staging-01 certbot[47655]: All renewal attempts failed. The following certs could not be renewed:
Dec 01 00:26:29 example-lb-staging-01 certbot[47655]: /etc/letsencrypt/live/staging.example.org/fullchain.pem (failure)
Dec 01 00:26:29 example-lb-staging-01 certbot[47655]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Dec 01 00:26:29 example-lb-staging-01 certbot[47655]: 1 renew failure(s), 0 parse failure(s)
Dec 01 00:26:29 example-lb-staging-01 systemd[1]: certbot-renew.service: main process exited, code=exited, status=1/FAILURE
Dec 01 00:26:29 example-lb-staging-01 systemd[1]: Failed to start This service automatically renews any certbot certificates found.
Dec 01 00:26:29 example-lb-staging-01 systemd[1]: Unit certbot-renew.service entered failed state.
Dec 01 00:26:29 example-lb-staging-01 systemd[1]: certbot-renew.service failed.
```

## Certbot's behavior differed from what I expected because:
The auto renew of certbot binds to port 80 instead of port 12364.  
On port 80 runs a HAProxy which redirects ACME traffic to port 12364. (This is working for manual cert generation)

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
2020-12-01 00:26:29,299:WARNING:certbot._internal.renewal:Attempting to renew cert (staging.example.org) from /etc/letsencrypt/renewal/staging.example.org.conf produced an unexpected error: Problem binding to port 80: Could not bind to IPv4 or IPv6.. Skipping.
2020-12-01 00:26:29,300:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/_internal/renewal.py", line 462, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 1178, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 116, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/renewal.py", line 320, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/client.py", line 351, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/client.py", line 398, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/plugins/standalone.py", line 156, in perform
    return [self._try_perform_single(achall) for achall in achalls]
  File "/usr/lib/python2.7/site-packages/certbot/_internal/plugins/standalone.py", line 163, in _try_perform_single
    _handle_perform_error(error)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/plugins/standalone.py", line 210, in _handle_perform_error
    raise error
StandaloneBindError: Problem binding to port 80: Could not bind to IPv4 or IPv6.

2020-12-01 00:26:29,300:ERROR:certbot._internal.renewal:All renewal attempts failed. The following certs could not be renewed:
2020-12-01 00:26:29,300:ERROR:certbot._internal.renewal:  /etc/letsencrypt/live/staging.example.org/fullchain.pem (failure)
2020-12-01 00:26:29,303:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==1.7.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 1357, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 1261, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/renewal.py", line 487, in handle_renewal_request
    len(renew_failures), len(parse_failures)))
Error: 1 renew failure(s), 0 parse failure(s)
2020-12-01 00:26:29,303:ERROR:certbot._internal.log:1 renew failure(s), 0 parse failure(s)
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
# cat /etc/letsencrypt/renewal/staging.example.org.conf 

# renew_before_expiry = 30 days
version = 1.7.0
archive_dir = /etc/letsencrypt/archive/staging.example.org
cert = /etc/letsencrypt/live/staging.example.org/cert.pem
privkey = /etc/letsencrypt/live/staging.example.org/privkey.pem
chain = /etc/letsencrypt/live/staging.example.org/chain.pem
fullchain = /etc/letsencrypt/live/staging.example.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = xxxxxxxxxxxxxxxxxxxxxxxxxxxx  # removed
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = standalone
pref_challs = http-01,
http01_port = 12364
```

**Comment by alexzorin** [comment]
Hi @uvu9Ba,

It's tricky to figure out what happened here. I wasn't able to reproduce it on CentOS 7 with Certbot from EPEL.

Certbot would not disregard `http01_port` in the renewal parameters unless it was told another port via the CLI (or `cli.ini`). 

It could also happen if the renewal parameters did not contain `http01_port` at the time of renewal, for some reason. If, for example, the existing certificate was updated using `certbot certonly`, and `--http-01-port` was not included at that time, that could have caused the renewal parameter to disappear.

What would really help are the steps, from scratch, that result in this problem. For now I'm not sure how else this could be investigated.

**Comment by uvu9Ba** [comment]
Hi @alexzorin,
thanks for looking into this. Did you used the same version (1.7.0)?

I updated to version 1.9.0 and re-tested it with `--force-renewal` option. Now it seems to work.
