### ISSUE TITLE
Certbot + Nginx in Docker, error when creating certificate in script

### ISSUE THREAD

**Issue by Mithrandir2k18** [certbot/certbot#8619]
## My operating system is (include version):
`Linux raspberry 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux`

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
Docker image: certbot/certbot:arm32v6-latest 

### Command:
```
docker-compose run --rm --entrypoint "\
          certbot certonly --webroot -w /var/www/certbot \
          --email $email \
          -d $domain
          --rsa-key-size 4096 \
          --agree-tos \
          --force-renewal" certbot
```

### Relevant Compose service:
```
certbot:
                #if you are not on amd64, check out https://hub.docker.com/r/certbot/certbot/tags?page=1&ordering=last_updated for images, e.g. for arm: certbot/certbot:arm32v6-latest                
                image: certbot/certbot:arm32v6-latest                
                volumes:
                        - ./data/certbot/conf:/etc/letsencrypt
                        - ./data/certbot/www:/var/www/certbot
                entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
                restart: unless-stopped
```
### Output interactive script:
```
Creating ipfs-gateway-docker_certbot_run ... done
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator webroot, Installer None


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Would you be willing, once your first certificate is successfully issued, to
share your email address with the Electronic Frontier Foundation, a founding
partner of the Let's Encrypt project and the non-profit organization that
develops Certbot? We'd like to send you email about our work encrypting the web,
EFF news, campaigns, and ways to support digital freedom.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o: (Y)es/(N)o: No
Account registered.
Requesting a certificate for mydomain.com
Performing the following challenges:
http-01 challenge for mydomain.com
Using the webroot path /var/www/certbot for all unmatched domains.
Waiting for verification...
Cleaning up challenges
live directory exists for mydomain.com
ERROR: 1
```
### Output of docker-compose up -d:
```
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating network "ipfs-gateway-docker_default" with the default driver
Creating ipfs-gateway-docker_ipfs_host_1 ... done
Creating ipfs-gateway-docker_nginx_1     ... done
Creating ipfs-gateway-docker_certbot_1   ... done
Attaching to ipfs-gateway-docker_certbot_1, ipfs-gateway-docker_nginx_1, ipfs-gateway-docker_ipfs_host_1
ipfs_host_1  | Daemon is ready
certbot_1    | Saving debug log to /var/log/letsencrypt/letsencrypt.log
certbot_1    | 
certbot_1    | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1    | Processing /etc/letsencrypt/renewal/mydomain.com.conf
certbot_1    | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1    | 
certbot_1    | Traceback (most recent call last):
certbot_1    |   File "/opt/certbot/src/certbot/certbot/_internal/renewal.py", line 71, in _reconstitute
certbot_1    |     renewal_candidate = storage.RenewableCert(full_path, config)
certbot_1    |   File "/opt/certbot/src/certbot/certbot/_internal/storage.py", line 449, in __init__
certbot_1    |     raise errors.CertStorageError(
certbot_1    | certbot.errors.CertStorageError: renewal config file {} is missing a required file reference
certbot_1    | Renewal configuration file /etc/letsencrypt/renewal/mydomain.com.conf is broken. Skipping.
certbot_1    | 
certbot_1    | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1    | No renewals were attempted.
certbot_1    | 
certbot_1    | Additionally, the following renewal configurations were invalid: 
certbot_1    |   /etc/letsencrypt/renewal/mydomain.com.conf (parsefail)
certbot_1    | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
certbot_1    | 0 renew failure(s), 1 parse failure(s)
```

The config file that's said to be broken is totally empty but exists.

## Certbot's behavior differed from what I expected because:
I thought it'd create a cert renewal config.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
/opt/certbot # cd /var/log/letsencrypt
/var/log/letsencrypt # ls
letsencrypt.log    letsencrypt.log.1  letsencrypt.log.2
/var/log/letsencrypt # cat *
2021-01-27 05:14:58,040:DEBUG:certbot._internal.main:certbot version: 1.11.0
2021-01-27 05:14:58,041:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2021-01-27 05:14:58,041:DEBUG:certbot._internal.main:Arguments: []
2021-01-27 05:14:58,042:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-01-27 05:14:58,152:DEBUG:certbot._internal.log:Root logging level set at 20
2021-01-27 05:14:58,153:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-01-27 05:14:58,159:DEBUG:certbot.display.util:Notifying user: Processing /etc/letsencrypt/renewal/mydomain.com.conf
2021-01-27 05:14:58,163:WARNING:certbot._internal.renewal:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/renewal.py", line 71, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/opt/certbot/src/certbot/certbot/_internal/storage.py", line 449, in __init__
    raise errors.CertStorageError(
certbot.errors.CertStorageError: renewal config file {} is missing a required file reference
2021-01-27 05:14:58,167:WARNING:certbot._internal.renewal:Renewal configuration file /etc/letsencrypt/renewal/mydomain.com.conf is broken. Skipping.
2021-01-27 05:14:58,169:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/renewal.py", line 71, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/opt/certbot/src/certbot/certbot/_internal/storage.py", line 449, in __init__
    raise errors.CertStorageError(
certbot.errors.CertStorageError: renewal config file {} is missing a required file reference

2021-01-27 05:14:58,169:DEBUG:certbot.display.util:Notifying user: 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-01-27 05:14:58,170:DEBUG:certbot.display.util:Notifying user: No renewals were attempted.
2021-01-27 05:14:58,171:DEBUG:certbot.display.util:Notifying user: 
Additionally, the following renewal configurations were invalid: 
2021-01-27 05:14:58,172:DEBUG:certbot.display.util:Notifying user:   /etc/letsencrypt/renewal/mydomain.com.conf (parsefail)
2021-01-27 05:14:58,173:DEBUG:certbot.display.util:Notifying user: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-01-27 05:14:58,175:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1421, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1318, in renew
    renewal.handle_renewal_request(config)
  File "/opt/certbot/src/certbot/certbot/_internal/renewal.py", line 496, in handle_renewal_request
    raise errors.Error("{0} renew failure(s), {1} parse failure(s)".format(
certbot.errors.Error: 0 renew failure(s), 1 parse failure(s)
2021-01-27 05:14:58,180:ERROR:certbot._internal.log:0 renew failure(s), 1 parse failure(s)
2021-01-27 05:07:15,316:DEBUG:certbot._internal.main:certbot version: 1.11.0
2021-01-27 05:07:15,317:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2021-01-27 05:07:15,318:DEBUG:certbot._internal.main:Arguments: []
2021-01-27 05:07:15,319:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-01-27 05:07:15,430:DEBUG:certbot._internal.log:Root logging level set at 20
2021-01-27 05:07:15,431:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-01-27 05:07:15,438:DEBUG:certbot.display.util:Notifying user: Processing /etc/letsencrypt/renewal/mydomain.com.conf
2021-01-27 05:07:15,443:WARNING:certbot._internal.renewal:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/renewal.py", line 71, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/opt/certbot/src/certbot/certbot/_internal/storage.py", line 449, in __init__
    raise errors.CertStorageError(
certbot.errors.CertStorageError: renewal config file {} is missing a required file reference
2021-01-27 05:07:15,448:WARNING:certbot._internal.renewal:Renewal configuration file /etc/letsencrypt/renewal/mydomain.com.conf is broken. Skipping.
2021-01-27 05:07:15,450:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/renewal.py", line 71, in _reconstitute
    renewal_candidate = storage.RenewableCert(full_path, config)
  File "/opt/certbot/src/certbot/certbot/_internal/storage.py", line 449, in __init__
    raise errors.CertStorageError(
certbot.errors.CertStorageError: renewal config file {} is missing a required file reference

2021-01-27 05:07:15,451:DEBUG:certbot.display.util:Notifying user: 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-01-27 05:07:15,453:DEBUG:certbot.display.util:Notifying user: No renewals were attempted.
2021-01-27 05:07:15,455:DEBUG:certbot.display.util:Notifying user: 
Additionally, the following renewal configurations were invalid: 
2021-01-27 05:07:15,456:DEBUG:certbot.display.util:Notifying user:   /etc/letsencrypt/renewal/mydomain.com.conf (parsefail)
2021-01-27 05:07:15,458:DEBUG:certbot.display.util:Notifying user: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-01-27 05:07:15,459:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    load_entry_point('certbot', 'console_scripts', 'certbot')()
  File "/opt/certbot/src/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1421, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1318, in renew
    renewal.handle_renewal_request(config)
  File "/opt/certbot/src/certbot/certbot/_internal/renewal.py", line 496, in handle_renewal_request
    raise errors.Error("{0} renew failure(s), {1} parse failure(s)".format(
certbot.errors.Error: 0 renew failure(s), 1 parse failure(s)
2021-01-27 05:07:15,464:ERROR:certbot._internal.log:0 renew failure(s), 1 parse failure(s)
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
```
server {
        listen 80;
        server_name mydomain.com;
        location / {
                return 301 https://$host$request_uri;
        }

        location /.well-known/acme-challenge/ {
                root /var/www/certbot;
        }
}
server {
        listen 443 ssl;
        server_name mydomain.com;

        ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
         
        location / {
                proxy_pass http://ipfs_host:8080;
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }
}

server {
        listen 4003 ssl;
        server_name mydomain.com;

        ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
         
        location / {
                proxy_pass http://ipfs_host:8081;
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
}
```

**Comment by alexzorin** [comment]
Hello @Mithrandir2k18,

The error:

    certbot_1    | certbot.errors.CertStorageError: renewal config file {} is missing a required file reference
    certbot_1    | Renewal configuration file /etc/letsencrypt/renewal/mydomain.com.conf is broken. Skipping.

suggests that the file `./data/certbot/conf/renewal/mydomain.com.conf` is empty - it got truncated or corrupted somehow.

I don't know of any behavior in Certbot that would cause this to happen.

From this state I think your next best choice would be to restore a backup of that volume if you have it, or remove the volume and start again from a clean state.

**Comment by Mithrandir2k18** [comment]
Yes it is, as I state in the post the renewal conf is totally empty. I think it must be caused by the preceeding error messages, namely whatever this means:
```
Waiting for verification...
Cleaning up challenges
live directory exists for mydomain.com
ERROR: 1
```

I can repeat that, as I said I am writing a script to automate this entire setup process, but I doubt the results will be different, as I already ran that script from a clean state.

**Comment by alexzorin** [comment]
>Yes it is, as I state in the post the renewal conf is totally empty

Ah yes, sorry I missed that.

>     live directory exists for mydomain.com

Are you certain that this happens from a blank state?

For context, this error would happen if Certbot was trying to create a renewal config for `mydomain.com`, but `./data/certbot/conf/live/mydomain.com` already existed.

You might, for example, end up in this situation if you deleted the renewal config file (instead of using `certbot delete`). That would leave Certbot in a broken state.

If you have a `docker-compose.yml` which reproduces this issue from a blank state, I'd really appreciate if you could share it.

**Comment by Mithrandir2k18** [comment]
> Ah yes, sorry I missed that.

No problem, it was quite a big dump of data.

> Are you certain that this happens from a blank state?

Relatively yes, I mount all the volumes in a single folder and made sure to delete it each time I ran the script.



> If you have a `docker-compose.yml` which reproduces this issue from a blank state, I'd really appreciate if you could share it.

Sure, I planned to make it public anyway(albeit in a fully working state). I uploaded the repo [here](https://github.com/Mithrandir2k18/dockerized-https-ipfs-gateway).

**Comment by alexzorin** [comment]
>I uploaded the repo here.

Thank you!

I haven't run it yet, but I think I see the problem already:

https://github.com/Mithrandir2k18/dockerized-https-ipfs-gateway/blob/b6d9c9aaab4537bbc34e1777aacdc05b546cbaa0/setup_configs.sh#L15

I alluded to this earlier ("Or if you pre-created that directory before the renewal config existed.").

If the `live/mydomain.com` already exists before the renewal config is created, then Certbot will error out when it tries to create the `mydomain.com` certificate. 

Your `setup_configs.sh` appears to do exactly that.

It's a bit unfortunate that Certbot is sensitive to this directory already existing, but I recommend not manually manipulating those files and directories and letting Certbot create and delete them as necessary, using only `certbot certonly/delete` to manage them.

**Comment by alexzorin** [comment]
I suppose you are doing it because you want to bootstrap a self-signed certificate to solve the chicken-and-egg problem with nginx starting.

If I can make a suggestion: configure nginx to read your certificate from `/etc/nginx/ssl.{crt,privkey}`. It can start out self-signed, and once you have acquired a real certificate using Certbot, you can overwrite those files with symlinks to `/etc/letsencrypt/live/mydomain.com/{fullchain,privkey}.pem`.

That way, your nginx configuration doesn't need to change, and you don't need to do any unexpected manipulations of the contents of `/etc/letsencrypt/`.

**Comment by Mithrandir2k18** [comment]
> I suppose you are doing it because you want to bootstrap a self-signed certificate to solve the chicken-and-egg problem with nginx starting.

Yes that's exactly that. As I state in the readme stub, I basically just adapted the steps from an old out-of-date guide into the script. This is my first time working with nginx and certbot; I understand the fundamentals, though.

> If I can make a suggestion

Sure! I'd also accept pull requests ;)

The suggestion with the symlink sounds great! Just one more question, how does certbot behave if I run it multiple times for the same domain? Will I run into troubles with letsEncrypt for registering the same domain+name combo multiple times? Or can I just test this how often I want? Because for each test, I'd just delete the data folder and the docker containers and let it all run.

**Comment by alexzorin** [comment]
If you're going to run it over and over and over for testing reasons, run Certbot with `--staging` to use the staging environment (https://letsencrypt.org/docs/staging-environment/) with certificates from the test CA. The certificates will be untrusted by your browser.

Otherwise you will rapidly run into rate limits (https://letsencrypt.org/docs/rate-limits/).

**Comment by Mithrandir2k18** [comment]
I guess that's all I need to try and fix it. I am going to close this issue and open another one if something else comes up. Thank you very much for your help! :)
