### ISSUE TITLE
Certification generation/renewal fails on my CentOS 7 install

### ISSUE THREAD

**Issue by Zephyrrus** [certbot/certbot#8621]
## My operating system is (include version):
CentOS Linux release 7.9.2009 (Core)

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
yum install certbot

## I ran this command and it produced this output:
certbot certonly --nginx -d domain.com 
(replaced my domain with domain.com for privacy reasons)

## Certbot's behavior differed from what I expected because:
Certbot crashes with the following error:
[root@ema-03 ~]# sudo certbot certonly --nginx -d domain.com 
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
From cffi callback <function _verify_callback at 0x7f565fd2fc80>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 313, in wrapper
    _lib.X509_up_ref(x509)
AttributeError: 'module' object has no attribute 'X509_up_ref'
An unexpected error occurred:
TypeError: __str__ returned non-string (type Error)
Please see the logfiles in /var/log/letsencrypt for more details.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2021-01-28 10:45:03,057:DEBUG:certbot._internal.main:certbot version: 1.11.0
2021-01-28 10:45:03,057:DEBUG:certbot._internal.main:Location of certbot entry point: /bin/certbot
2021-01-28 10:45:03,058:DEBUG:certbot._internal.main:Arguments: ['--nginx', '-d', 'domain.com']
2021-01-28 10:45:03,058:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-01-28 10:45:03,126:DEBUG:certbot._internal.log:Root logging level set at 20
2021-01-28 10:45:03,126:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-01-28 10:45:03,128:DEBUG:certbot._internal.plugins.selection:Requested authenticator nginx and installer nginx
2021-01-28 10:45:03,941:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * nginx
Description: Nginx Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: nginx = certbot_nginx._internal.configurator:NginxConfigurator
Initialized: <certbot_nginx._internal.configurator.NginxConfigurator object at 0x7f565febdfd0>
Prep: True
2021-01-28 10:45:03,942:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * nginx
Description: Nginx Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: nginx = certbot_nginx._internal.configurator:NginxConfigurator
Initialized: <certbot_nginx._internal.configurator.NginxConfigurator object at 0x7f565febdfd0>
Prep: True
2021-01-28 10:45:03,943:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_nginx._internal.configurator.NginxConfigurator object at 0x7f565febdfd0> and installer <certbot_nginx._internal.configurator.NginxConfigurator object at 0x7f565febdfd0>
2021-01-28 10:45:03,943:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator nginx, Installer nginx
2021-01-28 10:45:03,973:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(status=None, terms_of_service_agreed=None, agreement=None, only_return_existing=None, contact=(), key=None, external_account_binding=None), uri=u'https://acme-v02.api.letsencrypt.org/acme/acct/50678373', new_authzr_uri=None, terms_of_service=None), 600c7e82c49a139458c705ab7be5a366, Meta(creation_host=u'ema-03', register_to_eff=None, creation_dt=datetime.datetime(2019, 2, 1, 15, 41, 37, tzinfo=<UTC>)))>
2021-01-28 10:45:03,975:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-01-28 10:45:03,986:INFO:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org
2021-01-28 10:45:06,420:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/bin/certbot", line 9, in <module>
    load_entry_point('certbot==1.11.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 1421, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 1277, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 659, in _init_le_client
    return client.Client(config, acc, authenticator, installer, acme=acme)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/client.py", line 255, in __init__
    acme = acme_from_config_key(config, self.account.key, self.account.regr)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/client.py", line 43, in acme_from_config_key
    return acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 831, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 1168, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python2.7/site-packages/acme/client.py", line 1118, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 486, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 598, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
2021-01-28 10:45:06,424:ERROR:certbot._internal.log:An unexpected error occurred:
2021-01-28 10:45:06,424:ERROR:certbot._internal.log:TypeError: __str__ returned non-string (type Error)

**Comment by alexzorin** [comment]
While urllib3 is not being very helpful with its error message in this case, it looks like your server can't connect to the ACME server.

Try check:

    curl -i -m10 https://acme-v02.api.letsencrypt.org/directory

**Comment by Zephyrrus** [comment]
That seems to be the issue.
```
[root@ema-03 letsencrypt]# curl -i -m10 https://acme-v02.api.letsencrypt.org/directory
curl: (28) Operation timed out after 10001 milliseconds with 0 out of -1 bytes received
```

Executing
```
curl -i -m10 https://acme-v02.api.letsencrypt.org/
```
seems to work so I'm not sure why it can't access `/directory` but it can access the root.

**Comment by alexzorin** [comment]
Well, there seems to be an active incident right now that could be related: https://letsencrypt.status.io/.

Otherwise, you could maybe try dropping your MTU to 1300 temporarily to see whether it helps.

I'm going to close this issue because this tracker is really for reporting defects with Certbot, but if the issue persists, opening a thread on https://community.letsencrypt.org/ might help, where the community (including Let's Encrypt staff) will be able to see it and help out.
