### ISSUE TITLE
certbot._internal.log:Exiting abnormally

### ISSUE THREAD

**Issue by Bagunda** [certbot/certbot#8714]
```
2021-03-15 14:29:30,379:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Mon, 15 Mar 2021 11:29:30 GMT
Content-Type: application/json
Content-Length: 746
Connection: keep-alive
Boulder-Requester: 115683996
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104sLuDyWKG6PK_bKXAkw0T8tjfnysXMWXFckE-mWkBd9I
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "bagunda.ru"
  },
  "status": "valid",
  "expires": "2021-04-14T11:29:29Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "valid",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/11579541424/R_rbdA",
      "token": "jwxMXJBiPM7jpSZn0v7CO0H-mg_UFohygJ5-ZHXQCow",
      "validationRecord": [
        {
          "url": "http://bagunda.ru/.well-known/acme-challenge/jwxMXJBiPM7jpSZn0v7CO0H-mg_UFohygJ5-ZHXQCow",
          "hostname": "bagunda.ru",
          "port": "80",
          "addressesResolved": [
            "95.217.220.63",
            "2a01:4f9:c010:9bab::1"
          ],
          "addressUsed": "2a01:4f9:c010:9bab::1"
        }
      ]
    }
  ]
}

2021-03-15 14:29:30,379:DEBUG:acme.client:Storing nonce: 0104sLuDyWKG6PK_bKXAkw0T8tjfnysXMWXFckE-mWkBd9I
2021-03-15 14:29:30,380:INFO:certbot._internal.auth_handler:http-01 challenge for www.bagunda.ru
2021-03-15 14:29:30,380:DEBUG:certbot._internal.reporter:Reporting to user: The following errors were reported by the server:

Domain: www.bagunda.ru
Type:   unauthorized
Detail: Invalid response from http://www.bagunda.ru/.well-known/acme-challenge/f_45NpOil7Ynx_JMeFa13oSK5luZRstBuPaBqiwGpuk [2a01:4f9:c010:9bab::1]: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><$

To fix these errors, please make sure that your domain name was entered correctly and the DNS A/AAAA record(s) for that domain contain(s) the right IP address.
2021-03-15 14:29:30,381:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2021-03-15 14:29:30,600:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/certbot/1042/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/main.py", line 1421, in main
    return config.func(config, plugins)
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/main.py", line 1162, in run
    new_lineage = _get_and_save_cert(le_client, config, domains,
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/main.py", line 134, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/client.py", line 441, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/client.py", line 421, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 91, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, best_effort)
  File "/snap/certbot/1042/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 180, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2021-03-15 14:29:30,601:ERROR:certbot._internal.log:Some challenges have failed.
```

**Comment by ohemorange** [comment]
Hello! Looks like this is a configuration error, rather than an issue with the code. Please first try asking for help at https://community.letsencrypt.org/. There is a much larger community there of people familiar with the project who will be able to more quickly answer your questions.
