### ISSUE TITLE
Certbot stuck at saving devug to log /var/log/letsencrypt/letsencrypt.log

### ISSUE THREAD

**Issue by sagarparker** [certbot/certbot#8718]
Log file :

2021-03-17 19:30:23,843:DEBUG:certbot.main:certbot version: 0.40.0
2021-03-17 19:30:23,843:DEBUG:certbot.main:Arguments: ['-q']
2021-03-17 19:30:23,844:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryP>
2021-03-17 19:30:23,854:DEBUG:certbot.log:Root logging level set at 30
2021-03-17 19:30:23,854:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-03-17 19:30:23,855:DEBUG:certbot.renewal:no renewal failures
2021-03-18 08:23:18,282:DEBUG:certbot.main:certbot version: 0.40.0
2021-03-18 08:23:18,282:DEBUG:certbot.main:Arguments: ['-q']
2021-03-18 08:23:18,283:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryP>
2021-03-18 08:23:18,291:DEBUG:certbot.log:Root logging level set at 30
2021-03-18 08:23:18,292:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-03-18 08:23:18,292:DEBUG:certbot.renewal:no renewal failures
2021-03-18 10:22:29,559:DEBUG:certbot.main:certbot version: 0.40.0
2021-03-18 10:22:29,559:DEBUG:certbot.main:Arguments: ['--nginx', '-d', 'joynsocial.com', '-d', 'www.joynsocial.com']
2021-03-18 10:22:29,559:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryP>
2021-03-18 10:22:29,568:DEBUG:certbot.log:Root logging level set at 20
2021-03-18 10:22:29,568:INFO:certbot.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-03-18 10:22:29,568:DEBUG:certbot.plugins.selection:Requested authenticator nginx and installer nginx
2021-03-18 10:24:58,876:ERROR:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.40.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1382, in main
    return config.func(config, plugins)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1115, in run
    installer, authenticator = plug_sel.choose_configurator_plugins(config, plugins, "run")
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 223, in choose_configurator_plugins
    authenticator = installer = pick_configurator(config, req_inst, plugins)
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 22, in pick_configurator
    return pick_plugin(
  File "/usr/lib/python3/dist-packages/certbot/plugins/selection.py", line 105, in pick_plugin
    verified.prepare()
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 252, in prepare
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 252, in <listcomp>
    return [plugin_ep.prepare() for plugin_ep in six.itervalues(self._plugins)]
  File "/usr/lib/python3/dist-packages/certbot/plugins/disco.py", line 130, in prepare
    self._initialized.prepare()
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 193, in prepare
    self.config_test()
  File "/usr/lib/python3/dist-packages/certbot_nginx/configurator.py", line 928, in config_test
    util.run_script([self.conf('ctl'), "-c", self.nginx_conf, "-t"])
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 85, in run_script
    stdout, stderr = proc.communicate()
  File "/usr/lib/python3.8/subprocess.py", line 1024, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)

**Comment by alexzorin** [comment]
Hello,

It sounds like your system is hanging on this command:

    sudo nginx -c /etc/nginx/nginx.conf -t

If you run it manually, does it hang as well?

**Comment by sagarparker** [comment]
Sure I will try and let you know.

**Comment by sagarparker** [comment]
Used AWS certificate instead :)
