### ISSUE TITLE
Can't create certs on certbot with the certbot-dns-cloudflare plugin: "Cannot create a non-glue record that is beneath a delegated child zone."

### ISSUE THREAD

**Issue by vboufleur** [certbot/certbot#8726]
Hi!

I'm having a issue on certbot with the certbot-dns-cloudflare plugin. I'm not able to create certificates with it because of the way that my DNS zone is configured (with a delegated child zone). What should I do to fix this issue? Is there any workaround available?

## My operating system is (include version):

I'm using a light customized docker image based on the official one: `certbot/certbot`.

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
It comes bundled with the official image.

## I ran this command and it produced this output:
`certbot certonly -n -m owner@ipburger.com --agree-tos --no-eff-email --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare.ini -d *.ip.ipb.cloud,*.ip.fresh.ipb.cloud,*.ip.shared.ipb.cloud,*.ip.heroku.ipb.cloud`
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-cloudflare, Installer None
Account registered.
Requesting a certificate for *.ip.ipb.cloud and 3 more domains
2021-03-22 19:03:45,048 INFO success: certbot-run entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-22 19:03:45,048 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-03-22 19:03:45,049 INFO success: lighttpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Performing the following challenges:
dns-01 challenge for ip.fresh.ipb.cloud
dns-01 challenge for ip.heroku.ipb.cloud
dns-01 challenge for ip.ipb.cloud
dns-01 challenge for ip.shared.ipb.cloud
Encountered CloudFlareAPIError adding TXT record: 89018 Cannot create a non-glue record that is beneath a delegated child zone.
Cleaning up challenges
```

## Certbot's behavior differed from what I expected because:
I expected the certs to be created successfully.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
From inside the container: `/var/log/letsencrypt/letsencrypt.log`
```
2021-03-22 19:03:45,612:INFO:certbot._internal.auth_handler:Performing the following challenges:
2021-03-22 19:03:45,612:INFO:certbot._internal.auth_handler:dns-01 challenge for ip.fresh.ipb.cloud
2021-03-22 19:03:45,612:INFO:certbot._internal.auth_handler:dns-01 challenge for ip.heroku.ipb.cloud
2021-03-22 19:03:45,613:INFO:certbot._internal.auth_handler:dns-01 challenge for ip.ipb.cloud
2021-03-22 19:03:45,613:INFO:certbot._internal.auth_handler:dns-01 challenge for ip.shared.ipb.cloud
2021-03-22 19:03:45,618:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.cloudflare.com:443
2021-03-22 19:03:45,821:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?name=ip.fresh.ipb.cloud&per_page=1 HTTP/1.1" 200 None
2021-03-22 19:03:45,968:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?name=fresh.ipb.cloud&per_page=1 HTTP/1.1" 200 None
2021-03-22 19:03:46,151:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?name=ipb.cloud&per_page=1 HTTP/1.1" 200 None
2021-03-22 19:03:46,152:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Found zone_id of b03fe59b58a09bc9a7e1cfaf273a2338 for ip.fresh.ipb.cloud using name ipb.cloud
2021-03-22 19:03:46,152:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Attempting to add record to zone b03fe59b58a09bc9a7e1cfaf273a2338: {'type': 'TXT', 'name': '_acme-challenge.ip.fresh.ipb.cloud', 'content': 'TvvaNOhNjGuZrwWPRE6VPuQntxp4K_rIr3wfNwhSjJg', 'ttl': 120}
2021-03-22 19:03:46,333:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "POST /client/v4/zones/b03fe59b58a09bc9a7e1cfaf273a2338/dns_records HTTP/1.1" 400 None
2021-03-22 19:03:46,334:ERROR:certbot_dns_cloudflare._internal.dns_cloudflare:Encountered CloudFlareAPIError adding TXT record: 89018 Cannot create a non-glue record that is beneath a delegated child zone.
2021-03-22 19:03:46,335:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 116, in add_txt_record
    self.cf.zones.dns_records.post(zone_id, data=data)  # zones | pylint: disable=no-member
  File "/usr/local/lib/python3.8/site-packages/CloudFlare/cloudflare.py", line 686, in post
    return self._base.call_with_auth('POST', self._parts,
  File "/usr/local/lib/python3.8/site-packages/CloudFlare/cloudflare.py", line 126, in call_with_auth
    return self._call(method, headers, parts,
  File "/usr/local/lib/python3.8/site-packages/CloudFlare/cloudflare.py", line 502, in _call
    raise CloudFlareAPIError(code, message)
CloudFlare.exceptions.CloudFlareAPIError: Cannot create a non-glue record that is beneath a delegated child zone.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 77, in _perform
    self._get_cloudflare_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/usr/local/lib/python3.8/site-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 125, in add_txt_record
    raise errors.PluginError('Error communicating with the Cloudflare API: {0}{1}'
certbot.errors.PluginError: Error communicating with the Cloudflare API: Cannot create a non-glue record that is beneath a delegated child zone.
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not relevant.

**Comment by alexzorin** [comment]
It makes sense to me, that trying to do this results in that error. 

All those domains you are requesting certificates for, are subdelegated to `nono.io` nameservers.

As such, the `nono.io` nameservers are authoritative for e.g. `_acme-challenge.ip.ipb.cloud.`. Cloudflare is not.

You would need to get Certbot to perform the DNS updates against the `nono.io` DNS API (if it exists), rather than Cloudflare's.

I am going to close this as I don't think it's a bug or feature request with Certbot, but more broadly, discussions about how to approach DNS setups are very welcome on https://community.letsencrypt.org/.
