### ISSUE TITLE
pip installation dependency problem. (ERROR: zope-component 5.0.0 has requirement zope.interface>=5.3.0a1)

### ISSUE THREAD

**Issue by atoonk** [certbot/certbot#8734]
## My operating system is (include version): 
Fresh new Ubuntu 20.04.2 LTS install

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
```pip3 install certbot-dns-nsone certbot```

During the install I see this error:
```
ERROR: zope-component 5.0.0 has requirement zope.interface>=5.3.0a1, but you'll have zope-interface 4.7.1 which is incompatible.
```
## I ran this command and it produced this output:
```
root@ip-10-0-1-102:/home/ubuntu#  certbot
An unexpected error occurred:
pkg_resources.ContextualVersionConflict: (zope.interface 4.7.1 (/usr/lib/python3/dist-packages), Requirement.parse('zope.interface>=5.3.0a1'), {'zope.component'})
Please see the logfile '/tmp/tmph289w85g/log' for more details.
```

The log file:
```
root@ip-10-0-1-102:/home/ubuntu# cat /tmp/tmph289w85g/log
2021-03-24 03:14:16,070:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.8/dist-packages/certbot/_internal/main.py", line 1390, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python3.8/dist-packages/certbot/_internal/plugins/disco.py", line 229, in find_all
    plugin_ep = cls._load_entry_point(entry_point, plugins, with_prefix=False)
  File "/usr/local/lib/python3.8/dist-packages/certbot/_internal/plugins/disco.py", line 247, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point, with_prefix)
  File "/usr/local/lib/python3.8/dist-packages/certbot/_internal/plugins/disco.py", line 49, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (zope.interface 4.7.1 (/usr/lib/python3/dist-packages), Requirement.parse('zope.interface>=5.3.0a1'), {'zope.component'})
2021-03-24 03:14:16,070:ERROR:certbot._internal.log:An unexpected error occurred:
2021-03-24 03:14:16,071:ERROR:certbot._internal.log:pkg_resources.ContextualVersionConflict: (zope.interface 4.7.1 (/usr/lib/python3/dist-packages), Requirement.parse('zope.interface>=5.3.0a1'), {'zope.component'})
```

## Certbot's behavior differed from what I expected because:
certbot can't be used on a fresh ubuntu install where certbot is installed using pip due to dependency conflict.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
This is the complete pip install output

```
root@ip-10-0-1-102:/home/ubuntu# pip3 install certbot-dns-nsone
Collecting certbot-dns-nsone
  Downloading certbot_dns_nsone-1.13.0-py2.py3-none-any.whl (8.9 kB)
Requirement already satisfied: zope.interface in /usr/lib/python3/dist-packages (from certbot-dns-nsone) (4.7.1)
Collecting certbot>=1.1.0
  Downloading certbot-1.13.0-py2.py3-none-any.whl (251 kB)
     |████████████████████████████████| 251 kB 4.7 MB/s
Requirement already satisfied: setuptools>=39.0.1 in /usr/lib/python3/dist-packages (from certbot-dns-nsone) (45.2.0)
Collecting dns-lexicon>=2.2.1
  Downloading dns_lexicon-3.5.5-py3-none-any.whl (259 kB)
     |████████████████████████████████| 259 kB 8.3 MB/s
Collecting acme>=0.31.0
  Downloading acme-1.13.0-py2.py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 1.9 MB/s
Collecting pyrfc3339
  Downloading pyRFC3339-1.1-py2.py3-none-any.whl (5.7 kB)
Requirement already satisfied: configobj>=5.0.6 in /usr/lib/python3/dist-packages (from certbot>=1.1.0->certbot-dns-nsone) (5.0.6)
Collecting zope.component
  Downloading zope.component-5.0.0-py2.py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 7.5 MB/s
Requirement already satisfied: cryptography>=2.1.4 in /usr/lib/python3/dist-packages (from certbot>=1.1.0->certbot-dns-nsone) (2.8)
Requirement already satisfied: distro>=1.0.1 in /usr/lib/python3/dist-packages (from certbot>=1.1.0->certbot-dns-nsone) (1.4.0)
Collecting josepy>=1.1.0
  Downloading josepy-1.8.0-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 858 kB/s
Collecting parsedatetime>=2.4
  Downloading parsedatetime-2.6-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 128 kB/s
Collecting ConfigArgParse>=0.9.3
  Downloading ConfigArgParse-1.4.tar.gz (45 kB)
     |████████████████████████████████| 45 kB 4.5 MB/s
Collecting pytz
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 9.9 MB/s
Collecting tldextract<4,>=2
  Downloading tldextract-3.1.0-py2.py3-none-any.whl (87 kB)
     |████████████████████████████████| 87 kB 8.0 MB/s
Collecting beautifulsoup4<5,>=4
  Downloading beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
     |████████████████████████████████| 115 kB 13.1 MB/s
Requirement already satisfied: requests<3,>=2 in /usr/lib/python3/dist-packages (from dns-lexicon>=2.2.1->certbot-dns-nsone) (2.22.0)
Collecting future<1,>=0
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 12.6 MB/s
Requirement already satisfied: pyyaml<6,>=5 in /usr/lib/python3/dist-packages (from dns-lexicon>=2.2.1->certbot-dns-nsone) (5.3.1)
Requirement already satisfied: PyOpenSSL>=17.3.0 in /usr/lib/python3/dist-packages (from acme>=0.31.0->certbot-dns-nsone) (19.0.0)
Collecting requests-toolbelt>=0.3.0
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 690 kB/s
Collecting zope.event
  Downloading zope.event-4.5.0-py2.py3-none-any.whl (6.8 kB)
Collecting zope.hookable>=4.2.0
  Downloading zope.hookable-5.0.1-cp38-cp38-manylinux2010_x86_64.whl (26 kB)
Collecting filelock>=3.0.8
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from tldextract<4,>=2->dns-lexicon>=2.2.1->certbot-dns-nsone) (2.8)
Collecting requests-file>=1.4
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Collecting soupsieve>1.2; python_version >= "3.0"
  Downloading soupsieve-2.2.1-py3-none-any.whl (33 kB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from requests-file>=1.4->tldextract<4,>=2->dns-lexicon>=2.2.1->certbot-dns-nsone) (1.14.0)
Building wheels for collected packages: ConfigArgParse, future
  Building wheel for ConfigArgParse (setup.py) ... done
  Created wheel for ConfigArgParse: filename=ConfigArgParse-1.4-py3-none-any.whl size=19638 sha256=85040f42ad0a2017fe397f10f526e053bff753794edf7744b605e2bf9f5b79a4
  Stored in directory: /root/.cache/pip/wheels/6c/c3/07/c907f695d63f74c7f3515a46e1a63bcc4600de3748239ce754
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=9c357faed0f4718b54b0c3ad7e5d6d8ae0bc335c6f1ee8ac6b5d8e01d5b08274
  Stored in directory: /root/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
Successfully built ConfigArgParse future
ERROR: zope-component 5.0.0 has requirement zope.interface>=5.3.0a1, but you'll have zope-interface 4.7.1 which is incompatible.
Installing collected packages: pytz, pyrfc3339, zope.event, zope.hookable, zope.component, josepy, requests-toolbelt, acme, parsedatetime, ConfigArgParse, certbot, filelock, requests-file, tldextract, soupsieve, beautifulsoup4, future, dns-lexicon, certbot-dns-nsone
Successfully installed ConfigArgParse-1.4 acme-1.13.0 beautifulsoup4-4.9.3 certbot-1.13.0 certbot-dns-nsone-1.13.0 dns-lexicon-3.5.5 filelock-3.0.12 future-0.18.2 josepy-1.8.0 parsedatetime-2.6 pyrfc3339-1.1 pytz-2021.1 requests-file-1.5.1 requests-toolbelt-0.9.1 soupsieve-2.2.1 tldextract-3.1.0 zope.component-5.0.0 zope.event-4.5.0 zope.hookable-5.0.1
```

**Comment by alexzorin** [comment]
Hello @atoonk,

Our instructions for installing Certbot and DNS plugins from `pip` can be found here: https://certbot.eff.org/lets-encrypt/pip-other#wildcard

Mioxing installation methods (e.g. Certbot from `apt`/`snap` and DNS plugin from `pip`) is not supported and will result in errors like you the one you encountered.

On Ubuntu 20.04, we recommend using the [`snap`](https://certbot.eff.org/lets-encrypt/ubuntufocal-other#wildcard). Otherwise, you can try the `pip` instructions I linked earlier.

**Comment by atoonk** [comment]
thanks that worked.
