### ISSUE TITLE
Problem with running command: $ python3 tools/venv3.py

### ISSUE THREAD

**Issue by Megidd** [certbot/certbot#8795]
## My operating system is (include version):

Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-209-generic i686)

32 bit!

## I installed Certbot with git clone:

Dependencies:

```
$ sudo apt update 
$ sudo apt install python3-dev python3-venv gcc libaugeas0 libssl-dev \
>                  libffi-dev ca-certificates openssl
```

Cloning:

```
$ git clone https://github.com/certbot/certbot
$ cd certbot/
```

### Chronological order of what I tried:

On branch master:

```
$ python tools/venv.py 
  File "tools/venv.py", line 59
    def find_python_executable() -> str:
                                 ^
SyntaxError: invalid syntax
```

Tried the latest version tag:

```
$ git checkout v1.14.0
$ python3.5 tools/venv.py 
Incompatible python version for Certbot found: 3.5.2
Incompatible python version for Certbot found: 3.5.2
Incompatible python version for Certbot found: 2.7.12
Traceback (most recent call last):
  File "tools/venv.py", line 265, in <module>
    main(sys.argv[1:])
  File "tools/venv.py", line 256, in main
    create_venv(venv_path)
  File "tools/venv.py", line 249, in create_venv
    python = find_python_executable()
  File "tools/venv.py", line 108, in find_python_executable
    raise RuntimeError('Error, no compatible Python executable for Certbot could be found.')
RuntimeError: Error, no compatible Python executable for Certbot could be found.
```

Tried another version tag:

```
$ git checkout v1.13.0 
$ python3.5 tools/venv.py 
Incompatible python version for Certbot found: 3.5.2
Incompatible python version for Certbot found: 3.5.2
Incompatible python version for Certbot found: 2.7.12
Traceback (most recent call last):
  File "tools/venv.py", line 262, in <module>
    main(sys.argv[1:])
  File "tools/venv.py", line 253, in main
    create_venv(venv_path)
  File "tools/venv.py", line 246, in create_venv
    python = find_python_executable()
  File "tools/venv.py", line 105, in find_python_executable
    raise RuntimeError('Error, no compatible Python executable for Certbot could be found.')
RuntimeError: Error, no compatible Python executable for Certbot could be found.
```

Tried another version tag:

```
$ git checkout v1.12.0 
$ python3.5 tools/venv.py 
+ /usr/bin/python3.5 -m virtualenv --python /usr/bin/python3.5 venv
/usr/bin/python3.5: No module named virtualenv
Traceback (most recent call last):
  File "tools/venv.py", line 37, in <module>
    main(sys.argv[1:])
  File "tools/venv.py", line 28, in main
    create_venv(venv_path)
  File "tools/venv.py", line 20, in create_venv
    _venv_common.subprocess_with_print(command, environ)
  File "/home/uconn/repos/certbot/tools/_venv_common.py", line 134, in subprocess_with_print
    subprocess.check_call(cmd, env=env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.5', '-m', 'virtualenv', '--python', '/usr/bin/python3.5', 'venv']' returned non-zero exit status 1
```

Installed virtualenv module:

```
$ sudo apt install python3-pip
$ pip3 install virtualenv
```

Run script again:

```
 python3.5 tools/venv.py 
+ /usr/bin/python3.5 -m virtualenv --python /usr/bin/python3.5 venv
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 133, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/uconn/.local/lib/python3.5/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/home/uconn/.local/lib/python3.5/site-packages/virtualenv/run/__init__.py", line 13, in <module>
    from .plugin.activators import ActivationSelector
  File "/home/uconn/.local/lib/python3.5/site-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/home/uconn/.local/lib/python3.5/site-packages/virtualenv/run/plugin/base.py", line 9, in <module>
    from importlib_metadata import entry_points
  File "/home/uconn/.local/lib/python3.5/site-packages/importlib_metadata/__init__.py", line 158
    dist: Optional['Distribution'] = None
        ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "tools/venv.py", line 37, in <module>
    main(sys.argv[1:])
  File "tools/venv.py", line 28, in main
    create_venv(venv_path)
  File "tools/venv.py", line 20, in create_venv
    _venv_common.subprocess_with_print(command, environ)
  File "/home/uconn/repos/certbot/tools/_venv_common.py", line 134, in subprocess_with_print
    subprocess.check_call(cmd, env=env, shell=shell)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.5', '-m', 'virtualenv', '--python', '/usr/bin/python3.5', 'venv']' returned non-zero exit status 1
```

Run the other script:

```
$ python3.5 tools/venv3.py 
Incompatible python version for Certbot found: 3.5.2
Incompatible python version for Certbot found: 3.5.2
Incompatible python version for Certbot found: 2.7.12
Traceback (most recent call last):
  File "tools/venv3.py", line 30, in <module>
    main(sys.argv[1:])
  File "tools/venv3.py", line 21, in main
    create_venv(venv_path)
  File "tools/venv3.py", line 14, in create_venv
    python3 = _venv_common.find_python_executable(3)
  File "/home/uconn/repos/certbot/tools/_venv_common.py", line 108, in find_python_executable
    .format(python_major))
RuntimeError: Error, no compatible Python 3 executable for Certbot could be found.
```

Install Python 3.9:

```
$ sudo add-apt-repository ppa:deadsnakes/ppa
$ sudo apt-get update
$ sudo apt-get install python3.9
```

Run script with Python 3.9:

```
$ python3.9 tools/venv3.py 
+ /usr/bin/python3.9 -m venv venv3
Error: Command '['/home/uconn/repos/certbot/venv3/bin/python3.9', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/uconn/repos/certbot/tools/venv3.py", line 30, in <module>
    main(sys.argv[1:])
  File "/home/uconn/repos/certbot/tools/venv3.py", line 21, in main
    create_venv(venv_path)
  File "/home/uconn/repos/certbot/tools/venv3.py", line 16, in create_venv
    _venv_common.subprocess_with_print(command)
  File "/home/uconn/repos/certbot/tools/_venv_common.py", line 134, in subprocess_with_print
    subprocess.check_call(cmd, env=env, shell=shell)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.9', '-m', 'venv', 'venv3']' returned non-zero exit status 1.
```

Run the other script with Python 3.9:

```
$ python3.9 tools/venv.py 
+ /usr/bin/python3.9 -m virtualenv --python /usr/bin/python3.9 venv
/usr/bin/python3.9: No module named virtualenv
Traceback (most recent call last):
  File "/home/uconn/repos/certbot/tools/venv.py", line 37, in <module>
    main(sys.argv[1:])
  File "/home/uconn/repos/certbot/tools/venv.py", line 28, in main
    create_venv(venv_path)
  File "/home/uconn/repos/certbot/tools/venv.py", line 20, in create_venv
    _venv_common.subprocess_with_print(command, environ)
  File "/home/uconn/repos/certbot/tools/_venv_common.py", line 134, in subprocess_with_print
    subprocess.check_call(cmd, env=env, shell=shell)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.9', '-m', 'virtualenv', '--python', '/usr/bin/python3.9', 'venv']' returned non-zero exit status 1.
```

Install Python 3.6:

```
$ sudo apt-get install python3.6
```

Run script with Python 3.6:

```
$ python3.6 tools/venv3.py 
+ /usr/bin/python3.6 -m venv venv3
Error: Command '['/home/uconn/repos/certbot/venv3/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "tools/venv3.py", line 30, in <module>
    main(sys.argv[1:])
  File "tools/venv3.py", line 21, in main
    create_venv(venv_path)
  File "tools/venv3.py", line 16, in create_venv
    _venv_common.subprocess_with_print(command)
  File "/home/uconn/repos/certbot/tools/_venv_common.py", line 134, in subprocess_with_print
    subprocess.check_call(cmd, env=env, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.6', '-m', 'venv', 'venv3']' returned non-zero exit status 1.
```

Tried these version tags, all throwing errors while running the script:

v1.11.0, v1.10.0, v1.9.0, v1.8.0, v1.7.0, v1.6.0, v1.5.0, v1.4.0, v1.3.0, v1.2.0, v1.1.0, v1.0.0, 

v0.40.1, v0.39.0, 

## Certbot's behavior differed from what I expected because:

Scripts `tools/venv.py` (newer versions) and `tools/venv3.py` (older versions) couldn't be run with Python 3.5, 3.6, and 3.9, throwing the above errors.

**Comment by ohemorange** [comment]
Have you tried using the recommended installation method for your system? https://certbot.eff.org/lets-encrypt/ubuntuxenial-other

**Comment by Megidd** [comment]
@ohemorange My sever machine is 32 bit, however:

> The Certbot snap supports the x86_64, ARMv7, and ARMv8 architectures.

![Screen Shot 2021-04-21 at 06 39 42](https://user-images.githubusercontent.com/17475482/115486807-a4cd0780-a26c-11eb-8c69-5cab9167ac8f.png)

**Comment by ohemorange** [comment]
Gotcha -- you'll want [these instructions](https://certbot.eff.org/lets-encrypt/pip-other) then.

**Comment by Megidd** [comment]
Finally, this approach worked for me:

1. Install openSUSE Tumbleweed 32-bit (remove Ubuntu 32-bit)
2. Install Nginx
3. Install Certbox by [this](https://software.opensuse.org/download/package?package=certbot&project=home%3Aecsos%3Aserver)
4. Install Nginx plugin for Certbot i.e. `python36-certbot-nginx`
5. Run `sudo certbot --nginx`
6. Follow the instructions displayed
