### ISSUE TITLE
certbot 1.4.0 renew --manual failed due to mod_ssl

### ISSUE THREAD

**Issue by MeggyCal** [certbot/certbot#8825]
`certbot --dry-run --manual` fails. Without `--manual` it succeeds.

## My operating system is (include version):
openSUSE Tumbleweed, up-to-date

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
zypper (from openSUSE repos)

## I ran this command and it produced this output:
certbot --dry-run --manual -n renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/allo-coach.ch.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Cert not due for renewal, but simulating renewal for dry run
ssl_module is statically linked but --apache-bin is missing; not disabling session tickets.
Could not choose appropriate plugin: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.')
Failed to renew certificate allo-coach.ch with error: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.')

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
All simulated renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/allo-coach.ch/fullchain.pem (failure)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)

## apache config:
cat /etc/apache2/sysconfig.d/loadmodule.conf
# File generated from /etc/sysconfig/apache2, do not edit. Edit the sysconfig file instead.
LoadModule actions_module /usr/lib64/apache2-event/mod_actions.so
LoadModule alias_module /usr/lib64/apache2-event/mod_alias.so
LoadModule auth_basic_module /usr/lib64/apache2-event/mod_auth_basic.so
LoadModule authn_core_module /usr/lib64/apache2-event/mod_authn_core.so
LoadModule authn_file_module /usr/lib64/apache2-event/mod_authn_file.so
LoadModule authz_core_module /usr/lib64/apache2-event/mod_authz_core.so
LoadModule authz_host_module /usr/lib64/apache2-event/mod_authz_host.so
LoadModule authz_groupfile_module /usr/lib64/apache2-event/mod_authz_groupfile.so
LoadModule authz_user_module /usr/lib64/apache2-event/mod_authz_user.so
LoadModule authn_dbm_module /usr/lib64/apache2-event/mod_authn_dbm.so
LoadModule autoindex_module /usr/lib64/apache2-event/mod_autoindex.so
LoadModule cgid_module /usr/lib64/apache2-event/mod_cgid.so
LoadModule dir_module /usr/lib64/apache2-event/mod_dir.so
LoadModule env_module /usr/lib64/apache2-event/mod_env.so
LoadModule expires_module /usr/lib64/apache2-event/mod_expires.so
LoadModule include_module /usr/lib64/apache2-event/mod_include.so
LoadModule mime_module /usr/lib64/apache2-event/mod_mime.so
LoadModule negotiation_module /usr/lib64/apache2-event/mod_negotiation.so
LoadModule setenvif_module /usr/lib64/apache2-event/mod_setenvif.so
LoadModule status_module /usr/lib64/apache2-event/mod_status.so
LoadModule suexec_module /usr/lib64/apache2-event/mod_suexec.so
LoadModule userdir_module /usr/lib64/apache2-event/mod_userdir.so
LoadModule asis_module /usr/lib64/apache2-event/mod_asis.so
LoadModule dav_module /usr/lib64/apache2-event/mod_dav.so
LoadModule dav_fs_module /usr/lib64/apache2-event/mod_dav_fs.so
LoadModule dav_lock_module /usr/lib64/apache2-event/mod_dav_lock.so
LoadModule dav_svn_module /usr/lib64/apache2/mod_dav_svn.so
LoadModule deflate_module /usr/lib64/apache2-event/mod_deflate.so
LoadModule filter_module /usr/lib64/apache2-event/mod_filter.so
LoadModule cache_module /usr/lib64/apache2-event/mod_cache.so
LoadModule cache_disk_module /usr/lib64/apache2-event/mod_cache_disk.so
LoadModule file_cache_module /usr/lib64/apache2-event/mod_file_cache.so
LoadModule headers_module /usr/lib64/apache2-event/mod_headers.so
LoadModule ldap_module /usr/lib64/apache2-event/mod_ldap.so
LoadModule authnz_ldap_module /usr/lib64/apache2-event/mod_authnz_ldap.so
LoadModule proxy_module /usr/lib64/apache2-event/mod_proxy.so
LoadModule proxy_connect_module /usr/lib64/apache2-event/mod_proxy_connect.so
LoadModule proxy_express_module /usr/lib64/apache2-event/mod_proxy_express.so
LoadModule proxy_ftp_module /usr/lib64/apache2-event/mod_proxy_ftp.so
LoadModule proxy_http_module /usr/lib64/apache2-event/mod_proxy_http.so
LoadModule proxy_fcgi_module /usr/lib64/apache2-event/mod_proxy_fcgi.so
LoadModule rewrite_module /usr/lib64/apache2-event/mod_rewrite.so
LoadModule dbd_module /usr/lib64/apache2-event/mod_dbd.so
LoadModule authn_dbd_module /usr/lib64/apache2-event/mod_authn_dbd.so
LoadModule ssl_module /usr/lib64/apache2-event/mod_ssl.so
LoadModule socache_shmcb_module /usr/lib64/apache2-event/mod_socache_shmcb.so
LoadModule log_config_module /usr/lib64/apache2-event/mod_log_config.so
LoadModule http2_module /usr/lib64/apache2-event/mod_http2.so
LoadModule fcgid_module /usr/lib64/apache2/mod_fcgid.so
LoadModule wsgi_module /usr/lib64/apache2/mod_wsgi.so

## letsencrypt log with --manual
2021-03-09 10:09:22,207:DEBUG:certbot._internal.main:certbot version: 1.11.0
2021-03-09 10:09:22,208:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/bin/certbot
2021-03-09 10:09:22,208:DEBUG:certbot._internal.main:Arguments: ['--dry-run', '--manual', '-n']
2021-03-09 10:09:22,208:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-03-09 10:09:22,223:DEBUG:certbot._internal.log:Root logging level set at 20
2021-03-09 10:09:22,224:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-03-09 10:09:22,225:DEBUG:certbot.display.util:Notifying user: Processing /etc/letsencrypt/renewal/allo-coach.ch.conf
2021-03-09 10:09:22,246:DEBUG:certbot._internal.plugins.selection:Requested authenticator manual and installer <certbot._internal.cli.cli_utils._Default object at 0x7f6a520e0c10>
2021-03-09 10:09:22,246:DEBUG:certbot._internal.cli:Var dry_run=True (set by user).
2021-03-09 10:09:22,246:DEBUG:certbot._internal.cli:Var server={'staging', 'dry_run'} (set by user).
2021-03-09 10:09:22,246:DEBUG:certbot._internal.cli:Var dry_run=True (set by user).
2021-03-09 10:09:22,246:DEBUG:certbot._internal.cli:Var server={'staging', 'dry_run'} (set by user).
2021-03-09 10:09:22,246:DEBUG:certbot._internal.cli:Var account={'server'} (set by user).
2021-03-09 10:09:22,246:DEBUG:certbot._internal.cli:Var authenticator=manual (set by user).
2021-03-09 10:09:22,271:DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): r3.o.lencr.org:80
2021-03-09 10:09:22,602:DEBUG:urllib3.connectionpool:http://r3.o.lencr.org:80 "POST / HTTP/1.1" 200 503
2021-03-09 10:09:22,603:DEBUG:certbot.ocsp:OCSP response for certificate /etc/letsencrypt/archive/allo-coach.ch/cert6.pem is signed by the certificate's issuer.
2021-03-09 10:09:22,607:DEBUG:certbot.ocsp:OCSP certificate status for /etc/letsencrypt/archive/allo-coach.ch/cert6.pem is: OCSPCertStatus.GOOD
2021-03-09 10:09:22,609:INFO:certbot._internal.renewal:Cert not due for renewal, but simulating renewal for dry run
2021-03-09 10:09:22,609:DEBUG:certbot._internal.plugins.selection:Requested authenticator manual and installer apache
2021-03-09 10:09:22,852:DEBUG:certbot_apache._internal.configurator:Apache version is 2.4.46
2021-03-09 10:09:23,275:WARNING:certbot_apache._internal.configurator:ssl_module is statically linked but --apache-bin is missing; not disabling session tickets.
2021-03-09 10:09:23,276:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * apache
Description: Apache Web Server plugin
Interfaces: IAuthenticator, IInstaller, IPlugin
Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT
Initialized: <certbot_apache._internal.override_suse.OpenSUSEConfigurator object at 0x7f6a521210a0>
Prep: True
2021-03-09 10:09:23,280:DEBUG:certbot._internal.plugins.disco:Other error:(PluginEntryPoint#manual): An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 157, in prepare
    self._initialized.prepare()
  File "/usr/lib/python3.8/site-packages/certbot/_internal/plugins/manual.py", line 91, in prepare
    raise errors.PluginError(
certbot.errors.PluginError: An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.
2021-03-09 10:09:23,280:DEBUG:certbot._internal.plugins.selection:No candidate plugin
2021-03-09 10:09:23,280:DEBUG:certbot._internal.plugins.selection:Selected authenticator None and installer <certbot_apache._internal.override_suse.OpenSUSEConfigurator object at 0x7f6a521210a0>
2021-03-09 10:09:23,280:INFO:certbot._internal.main:Could not choose appropriate plugin: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.')
2021-03-09 10:09:23,281:ERROR:certbot._internal.renewal:Failed to renew certificate allo-coach.ch with error: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.')
2021-03-09 10:09:23,282:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/certbot/_internal/renewal.py", line 471, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1229, in renew_cert
    installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
  File "/usr/lib/python3.8/site-packages/certbot/_internal/plugins/selection.py", line 235, in choose_configurator_plugins
    diagnose_configurator_problem("authenticator", req_auth, plugins)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/plugins/selection.py", line 339, in diagnose_configurator_problem
    raise errors.PluginSelectionError(msg)
certbot.errors.PluginSelectionError: The manual plugin is not working; there may be problems with your existing configuration.
The error was: PluginError('An authentication script must be provided with --manual-auth-hook when using the manual plugin non-interactively.')

2021-03-09 10:09:23,282:DEBUG:certbot.display.util:Notifying user: 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-03-09 10:09:23,282:ERROR:certbot._internal.renewal:All simulated renewals failed. The following certificates could not be renewed:
2021-03-09 10:09:23,282:ERROR:certbot._internal.renewal:  /etc/letsencrypt/live/allo-coach.ch/fullchain.pem (failure)
2021-03-09 10:09:23,282:DEBUG:certbot.display.util:Notifying user: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2021-03-09 10:09:23,282:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==1.11.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3.8/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1421, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/main.py", line 1318, in renew
    renewal.handle_renewal_request(config)
  File "/usr/lib/python3.8/site-packages/certbot/_internal/renewal.py", line 496, in handle_renewal_request
    raise errors.Error("{0} renew failure(s), {1} parse failure(s)".format(
certbot.errors.Error: 1 renew failure(s), 0 parse failure(s)
2021-03-09 10:09:23,283:ERROR:certbot._internal.log:1 renew failure(s), 0 parse failure(s)

**Comment by tigerfoot** [comment]
Initial downstream report is https://bugzilla.suse.com/show_bug.cgi?id=1172313

**Comment by alexzorin** [comment]
Hello @tigerfoot,

> 2021-03-09 10:09:23,275:WARNING:certbot_apache._internal.configurator:ssl_module is statically linked but --apache-bin is missing; not disabling session tickets.

This is a soft failure, relating to some optional functionality that disables SSL tickets depending on the version of OpenSSL that mod_ssl is linked to. ([We have an issue open for that problem](https://github.com/certbot/certbot/issues/8711)).

It doesn't have any adverse effects on certificate renewal or installation.

> 2021-03-09 10:09:22,609:DEBUG:certbot._internal.plugins.selection:Requested authenticator manual and installer apache

Your certificate was set up using the "manual" plugin for authentication. You can check the `authenticator =` line in `/etc/letsencrypt/renewal/allo-coach.ch.conf` to verify this.

Typically, this means you performed domain validation by hand (an interactive process which is fundamentally incompatible with automatic renewal).

If you change your authenticator to "apache" or "webroot", I suspect everything will work fine:

    certbot renew --cert-name allo-coach.ch --apache

I'm going to close this as I don't think it's a defect or feature request, but you can get help on https://community.letsencrypt.org with any questions about using Certbot itself. Thanks.

**Comment by drbeco** [comment]
https://github.com/certbot/certbot/issues/8711#issuecomment-1509903171
