### ISSUE TITLE
when create_record, unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by lachhebo** [certbot/certbot#8830]
## I ran this command and it produced this output:

**command:** 

`sudo /dictial-certbot/venv/bin/certbot certonly --dns-ovh --dns-ovh-credentials /home/admin/.ovhapi -d dictial.com -d *.dictial.com  --email ismael.lachheb@protonmail.com --agree-tos --noninteractive`

**output:**

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-ovh, Installer None
Requesting a certificate for dictial.com and *.dictial.com
Performing the following challenges:
dns-01 challenge for dictial.com
dns-01 challenge for dictial.com
Cleaning up challenges
Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
An unexpected error occurred:
TypeError: create_record() got an unexpected keyword argument 'type'
Please see the logfiles in /var/log/letsencrypt for more details.
```

## Certbot's behavior differed from what I expected because:

I expected it to work, it was fonctionnal a few months ago

**Comment by lachhebo** [comment]
##  logs:
```
2021-05-06 18:53:05,241:DEBUG:certbot._internal.main:certbot version: 1.15.0
2021-05-06 18:53:05,241:DEBUG:certbot._internal.main:Location of certbot entry point: /dictial-certbot/venv/bin/certbot
2021-05-06 18:53:05,241:DEBUG:certbot._internal.main:Arguments: ['--dns-ovh', '--dns-ovh-credentials', '/home/admin/.ovhapi', '-d', 'dictial.com', '-d', '*.dictial.com', '--email', 'ismael.lachheb@protonmail.com', '--agree-tos', '--noninteractive']
2021-05-06 18:53:05,242:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-ovh,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-05-06 18:53:05,252:DEBUG:certbot._internal.log:Root logging level set at 20
2021-05-06 18:53:05,252:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-05-06 18:53:05,253:DEBUG:certbot._internal.plugins.selection:Requested authenticator dns-ovh and installer None
2021-05-06 18:53:05,256:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * dns-ovh
Description: Obtain certificates using a DNS TXT record (if you are using OVH for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-ovh = certbot_dns_ovh._internal.dns_ovh:Authenticator
Initialized: <certbot_dns_ovh._internal.dns_ovh.Authenticator object at 0x7fc8baa63588>
Prep: True
2021-05-06 18:53:05,257:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_ovh._internal.dns_ovh.Authenticator object at 0x7fc8baa63588> and installer None
2021-05-06 18:53:05,257:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator dns-ovh, Installer None
2021-05-06 18:53:05,263:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/122553492', new_authzr_uri=None, terms_of_service=None), 9dcd0b4e53724c952fc117c7d773c182, Meta(creation_dt=datetime.datetime(2021, 5, 6, 17, 58, 45, tzinfo=<UTC>), creation_host='ip-172-31-14-136.eu-west-3.compute.internal', register_to_eff=None))>
2021-05-06 18:53:05,264:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-05-06 18:53:05,265:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-05-06 18:53:05,757:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-05-06 18:53:05,757:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 06 May 2021 18:53:05 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert",
  "xKKPjr3GT74": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417"
}
2021-05-06 18:53:05,758:DEBUG:certbot.display.util:Notifying user: Requesting a certificate for dictial.com and *.dictial.com
2021-05-06 18:53:05,884:DEBUG:certbot.crypto_util:Generating RSA key (2048 bits): /etc/letsencrypt/keys/0005_key-certbot.pem
2021-05-06 18:53:05,886:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0005_csr-certbot.pem
2021-05-06 18:53:05,887:DEBUG:acme.client:Requesting fresh nonce
2021-05-06 18:53:05,887:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2021-05-06 18:53:06,010:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2021-05-06 18:53:06,010:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 06 May 2021 18:53:05 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0103a9ROxpPMVZlU1kHznpab9LTTldTsKql1FFTt1bKBihM
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2021-05-06 18:53:06,011:DEBUG:acme.client:Storing nonce: 0103a9ROxpPMVZlU1kHznpab9LTTldTsKql1FFTt1bKBihM
2021-05-06 18:53:06,011:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "dictial.com"\n    },\n    {\n      "type": "dns",\n      "value": "*.dictial.com"\n    }\n  ]\n}'
2021-05-06 18:53:06,013:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTIyNTUzNDkyIiwgIm5vbmNlIjogIjAxMDNhOVJPeHBQTVZabFUxa0h6bnBhYjlMVFRsZFRzS3FsMUZGVHQxYktCaWhNIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9uZXctb3JkZXIifQ",
  "signature": "X46UbRiELd1GFYfEy6cgR4vWOuemuBl5pjh0HyW39lvewshIvxMM6AN1Dw1dNnVSLNjR4oavHAhT8bDFFZiPWWFELMuefG-Bp6AgbWWJ7DSHh07zfoQ_S59ByrLAwSnj_5CgY6pmM27Okte8Ul2qnfAq8Gn_2NJOdQNKlxAzoodxFJANC3PBwMSv8DWW5zLY94W--ouoUY_G401sIn0zYZNwUxW_SZurivvcUoYEU3-Co2_sM1U4myx1_VN6xigVrGShibDu2OBl-7yW3fjeh5bYYL5HaNYsmjguIEB721HdQ3Otl01E2Bxc_jqFd9u352ouAKf0Tn1-94F04YQong",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImRpY3RpYWwuY29tIgogICAgfSwKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogIiouZGljdGlhbC5jb20iCiAgICB9CiAgXQp9"
}
2021-05-06 18:53:06,194:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 468
2021-05-06 18:53:06,195:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Thu, 06 May 2021 18:53:06 GMT
Content-Type: application/json
Content-Length: 468
Connection: keep-alive
Boulder-Requester: 122553492
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/122553492/9524740393
Replay-Nonce: 01036ehegVrcVQu-1rC7pN29Wja-2R9_5DHKmJLO0YtABfw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2021-05-13T17:58:46Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "*.dictial.com"
    },
    {
      "type": "dns",
      "value": "dictial.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12904289595",
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12904289596"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/122553492/9524740393"
}
2021-05-06 18:53:06,195:DEBUG:acme.client:Storing nonce: 01036ehegVrcVQu-1rC7pN29Wja-2R9_5DHKmJLO0YtABfw
2021-05-06 18:53:06,195:DEBUG:acme.client:JWS payload:
b''
2021-05-06 18:53:06,197:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/12904289595:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTIyNTUzNDkyIiwgIm5vbmNlIjogIjAxMDM2ZWhlZ1ZyY1ZRdS0xckM3cE4yOVdqYS0yUjlfNURIS21KTE8wWXRBQmZ3IiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xMjkwNDI4OTU5NSJ9",
  "signature": "eIASnVk0skgOmMordj2m40pv0MTpW31jANCoiS1VcGl42VfdTpWsqszsSpbDLX4no9F_hmg4yjFPH1OAopybwyAulAH8VZO8EKfRMIeKt8g0EunjcjEaaHPy1LM6zfgkO33mzMDDLKiz7AH_jjW56xD_oKrbtHvQNvS5HgYmK89aJLQb3kBlbdO3FeW5wlayZXCQcIBcFXrLPFm6fYCTXv10F2eH9mLxTaA3rcmXSemMY1gMPvhPz8HSnQmdBNwCULLUgyGGXrlkSrhWn5IcufD0GX1S41WHWGCSBxQflDcOx4GawuEiTUPHVGGlIyjgqMg1TNK4sNTEGI6LL3Ef-g",
  "payload": ""
}
2021-05-06 18:53:06,348:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/12904289595 HTTP/1.1" 200 384
2021-05-06 18:53:06,349:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 06 May 2021 18:53:06 GMT
Content-Type: application/json
Content-Length: 384
Connection: keep-alive
Boulder-Requester: 122553492
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0103CfNstLcwJ4GKclSuGz8miYSLi3sj2_OyO1CnTiiyiKs
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "dictial.com"
  },
  "status": "pending",
  "expires": "2021-05-13T17:58:46Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12904289595/Mwwj5w",
      "token": "T6Ag7H6512fe7NTKUzlUxfmcdng09EXI3HQdGRtVmns"
    }
  ],
  "wildcard": true
}
2021-05-06 18:53:06,349:DEBUG:acme.client:Storing nonce: 0103CfNstLcwJ4GKclSuGz8miYSLi3sj2_OyO1CnTiiyiKs
2021-05-06 18:53:06,349:DEBUG:acme.client:JWS payload:
b''
2021-05-06 18:53:06,351:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/12904289596:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMTIyNTUzNDkyIiwgIm5vbmNlIjogIjAxMDNDZk5zdExjd0o0R0tjbFN1R3o4bWlZU0xpM3NqMl9PeU8xQ25UaWl5aUtzIiwgInVybCI6ICJodHRwczovL2FjbWUtdjAyLmFwaS5sZXRzZW5jcnlwdC5vcmcvYWNtZS9hdXRoei12My8xMjkwNDI4OTU5NiJ9",
  "signature": "cVasUXhoEPqLAPKgDcbmBCkAhdv8oxehYZ3egKAm5_k3Z8DyBsJ10rgXs1qzpyL0cqa-FqoKC13ON9r1x6Q5vTWVTpFghORHj9SJbGsrnWBsYrHHkU7whmw7yX2w9A5ni7Q98Dvoh95VD9Spcpgdv-Pvy_d4rL6ThKMxqLUPJRMIz_NbkractL3sHoy0POvsb0-L8T0eadmUQNaEO5RQRLfRTPWmqlwMj8TFy8vW4HB0xfMS_qsRJO-3cUo5qCbzNNu4AmsOXOPL9ceud0THxI_qmPcGd5Xx7FsJf5trIjC_Wtpa960W4tPqGctI6-IB6p2SaRSeMOSayFxboTY7HQ",
  "payload": ""
}
2021-05-06 18:53:06,506:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/12904289596 HTTP/1.1" 200 792
2021-05-06 18:53:06,506:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Thu, 06 May 2021 18:53:06 GMT
Content-Type: application/json
Content-Length: 792
Connection: keep-alive
Boulder-Requester: 122553492
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 0104-ci2goNMjVfnYXmMEwwEeyobBWJ9Zh6PB0OubTRT0R4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "dictial.com"
  },
  "status": "pending",
  "expires": "2021-05-13T17:58:46Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12904289596/4SIRYQ",
      "token": "pp1UFj9ozjSOkuyKeWRCct2ZgH3Up5S5tu7Q924uvaw"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12904289596/rXe5eQ",
      "token": "pp1UFj9ozjSOkuyKeWRCct2ZgH3Up5S5tu7Q924uvaw"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12904289596/arzfTw",
      "token": "pp1UFj9ozjSOkuyKeWRCct2ZgH3Up5S5tu7Q924uvaw"
    }
  ]
}
2021-05-06 18:53:06,506:DEBUG:acme.client:Storing nonce: 0104-ci2goNMjVfnYXmMEwwEeyobBWJ9Zh6PB0OubTRT0R4
2021-05-06 18:53:06,506:INFO:certbot._internal.auth_handler:Performing the following challenges:
2021-05-06 18:53:06,507:INFO:certbot._internal.auth_handler:dns-01 challenge for dictial.com
2021-05-06 18:53:06,507:INFO:certbot._internal.auth_handler:dns-01 challenge for dictial.com
2021-05-06 18:53:06,509:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eu.api.ovh.com:443
2021-05-06 18:53:06,546:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
2021-05-06 18:53:06,621:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 None
2021-05-06 18:53:06,723:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/dictial.com/status HTTP/1.1" 200 None
2021-05-06 18:53:06,724:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/plugins/dns_common.py", line 60, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot_dns_ovh/_internal/dns_ovh.py", line 57, in _perform
    self._get_ovh_client().add_txt_record(domain, validation_name, validation)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/plugins/dns_common_lexicon.py", line 48, in add_txt_record
    self.provider.create_record(type='TXT', name=record_name, content=record_content)
TypeError: create_record() got an unexpected keyword argument 'type'

2021-05-06 18:53:06,724:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-05-06 18:53:06,724:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-05-06 18:53:06,726:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eu.api.ovh.com:443
2021-05-06 18:53:06,757:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
2021-05-06 18:53:06,803:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 None
2021-05-06 18:53:06,862:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/dictial.com/status HTTP/1.1" 200 None
2021-05-06 18:53:06,862:ERROR:certbot._internal.error_handler:Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
2021-05-06 18:53:06,863:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/dictial-certbot/venv/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/_internal/main.py", line 1435, in main
    return config.func(config, plugins)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/_internal/main.py", line 1304, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/_internal/main.py", line 140, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/_internal/client.py", line 444, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/_internal/client.py", line 424, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/plugins/dns_common.py", line 60, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot_dns_ovh/_internal/dns_ovh.py", line 57, in _perform
    self._get_ovh_client().add_txt_record(domain, validation_name, validation)
  File "/dictial-certbot/venv/lib/python3.7/site-packages/certbot/plugins/dns_common_lexicon.py", line 48, in add_txt_record
    self.provider.create_record(type='TXT', name=record_name, content=record_content)
TypeError: create_record() got an unexpected keyword argument 'type'
2021-05-06 18:53:06,864:ERROR:certbot._internal.log:An unexpected error occurred:
2021-05-06 18:53:06,864:ERROR:certbot._internal.log:TypeError: create_record() got an unexpected keyword argument 'type'
```

**Comment by JonHerr** [comment]
lexicon.providers.dnspod line: 112    def _delete_record(self, identifier=None, rtype=None, name=None, content=None):

**Comment by JonHerr** [comment]
looking through it seems to be a duplicate of https://github.com/certbot/certbot/issues/8826

seems for now you can downgrade the lexicon provider version to <3.1
pip install dns-lexicon==3.0.8

**Comment by lachhebo** [comment]
Thanks, it worked

**Comment by bmw** [comment]
Closing as a duplicate of https://github.com/certbot/certbot/issues/8826. This should be fixed in our next release.
