### ISSUE TITLE
TypeError: delete_record() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by flapili** [certbot/certbot#8846]
## My operating system is (include version):
debian 10 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
pip and git clone + python3 tools/venv.py

## I ran this command and it produced this output:

`certbot certonly --dns-ovh --dns-ovh-credentials ovh_credentials.ini -d flapili.fr -d *.flapili.fr`

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-ovh, Installer None
Requesting a certificate for flapili.fr and *.flapili.fr
Performing the following challenges:
dns-01 challenge for flapili.fr
dns-01 challenge for flapili.fr
Cleaning up challenges
Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
An unexpected error occurred:
TypeError: create_record() got an unexpected keyword argument 'type'
Please see the logfiles in /var/log/letsencrypt for more details.

```
2021-05-13 00:00:31,267:DEBUG:certbot._internal.main:certbot version: 1.16.0.dev0
2021-05-13 00:00:31,267:DEBUG:certbot._internal.main:Location of certbot entry point: venv/bin/certbot
2021-05-13 00:00:31,267:DEBUG:certbot._internal.main:Arguments: ['--dns-ovh', '--dns-ovh-credentials', '../ovh_credentials.ini', '-d', 'flapili.fr', '-d', '*.flapili.fr']
2021-05-13 00:00:31,267:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#certbot-route53:auth,PluginEntryPoint#dns-cloudflare,PluginEntryPoint#dns-cloudxns,PluginEntryPoint#dns-digitalocean,PluginEntryPoint#dns-dnsimple,PluginEntryPoint#dns-dnsmadeeasy,PluginEntryPoint#dns-gehirn,PluginEntryPoint#dns-google,PluginEntryPoint#dns-linode,PluginEntryPoint#dns-luadns,PluginEntryPoint#dns-nsone,PluginEntryPoint#dns-ovh,PluginEntryPoint#dns-rfc2136,PluginEntryPoint#dns-route53,PluginEntryPoint#dns-sakuracloud,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-05-13 00:00:31,278:DEBUG:certbot._internal.log:Root logging level set at 20
2021-05-13 00:00:31,278:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2021-05-13 00:00:31,279:DEBUG:certbot._internal.plugins.selection:Requested authenticator dns-ovh and installer None
2021-05-13 00:00:31,283:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * dns-ovh
Description: Obtain certificates using a DNS TXT record (if you are using OVH for DNS).
Interfaces: IAuthenticator, IPlugin
Entry point: dns-ovh = certbot_dns_ovh._internal.dns_ovh:Authenticator
Initialized: <certbot_dns_ovh._internal.dns_ovh.Authenticator object at 0x7f46fa1d0518>
Prep: True
2021-05-13 00:00:31,283:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_ovh._internal.dns_ovh.Authenticator object at 0x7f46fa1d0518> and installer None
2021-05-13 00:00:31,283:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator dns-ovh, Installer None
2021-05-13 00:00:31,291:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/123312054', new_authzr_uri=None, terms_of_service=None), fdf01224cb9aee3c78d31ef6e74671cb, Meta(creation_dt=datetime.datetime(2021, 5, 12, 21, 55, 11, tzinfo=<UTC>), creation_host='vmi588548.contaboserver.net', register_to_eff=None))>
2021-05-13 00:00:31,292:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2021-05-13 00:00:31,294:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2021-05-13 00:00:31,879:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 658
2021-05-13 00:00:31,880:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 12 May 2021 22:00:31 GMT
Content-Type: application/json
Content-Length: 658
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "Pv2ZMIJlMDE": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2021-05-13 00:00:31,881:DEBUG:certbot.display.util:Notifying user: Requesting a certificate for flapili.fr and *.flapili.fr
2021-05-13 00:00:31,962:DEBUG:certbot.crypto_util:Generating RSA key (2048 bits): /etc/letsencrypt/keys/0003_key-certbot.pem
2021-05-13 00:00:31,964:DEBUG:certbot.crypto_util:Creating CSR: /etc/letsencrypt/csr/0003_csr-certbot.pem
2021-05-13 00:00:31,965:DEBUG:acme.client:Requesting fresh nonce
2021-05-13 00:00:31,965:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2021-05-13 00:00:32,111:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2021-05-13 00:00:32,112:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 12 May 2021 22:00:32 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2021-05-13 00:00:32,112:DEBUG:acme.client:Storing nonce: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2021-05-13 00:00:32,112:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "flapili.fr"\n    },\n    {\n      "type": "dns",\n      "value": "*.flapili.fr"\n    }\n  ]\n}'
2021-05-13 00:00:32,114:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "signature": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "payload": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
2021-05-13 00:00:32,359:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 466
2021-05-13 00:00:32,359:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Wed, 12 May 2021 22:00:32 GMT
Content-Type: application/json
Content-Length: 466
Connection: keep-alive
Boulder-Requester: 123312054
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/123312054/9656643566
Replay-Nonce: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2021-05-19T21:55:13Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "*.flapili.fr"
    },
    {
      "type": "dns",
      "value": "flapili.fr"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/13066811153",
    "https://acme-v02.api.letsencrypt.org/acme/authz-v3/13066811155"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/123312054/9656643566"
}
2021-05-13 00:00:32,360:DEBUG:acme.client:Storing nonce: 0004g68PCTY7F1clrzwQaQcdJimSJdIUpV_CqGzJzn06Keo
2021-05-13 00:00:32,360:DEBUG:acme.client:JWS payload:
b''
2021-05-13 00:00:32,362:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/13066811153:
{
  "protected": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "signature": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "payload": ""
}
2021-05-13 00:00:32,538:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/13066811153 HTTP/1.1" 200 383
2021-05-13 00:00:32,538:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 12 May 2021 22:00:32 GMT
Content-Type: application/json
Content-Length: 383
Connection: keep-alive
Boulder-Requester: 123312054
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "flapili.fr"
  },
  "status": "pending",
  "expires": "2021-05-19T21:55:13Z",
  "challenges": [
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13066811153/6oGbIw",
      "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ],
  "wildcard": true
}
2021-05-13 00:00:32,539:DEBUG:acme.client:Storing nonce: 0003sHl8QCVV2qVs8EFbkGVuBQRsDXR51vKJAYjVG9uO4Jo
2021-05-13 00:00:32,539:DEBUG:acme.client:JWS payload:
b''
2021-05-13 00:00:32,540:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz-v3/13066811155:
{
  "protected": "xxxxxxxxxxxxxxx",
  "signature": "xxxxxxxxxxxxxxx",
  "payload": ""
}
2021-05-13 00:00:32,713:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz-v3/13066811155 HTTP/1.1" 200 791
2021-05-13 00:00:32,713:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Wed, 12 May 2021 22:00:32 GMT
Content-Type: application/json
Content-Length: 791
Connection: keep-alive
Boulder-Requester: 123312054
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: xxxxxxxxxxxxxxxxxxxxxxxxxxx
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "flapili.fr"
  },
  "status": "pending",
  "expires": "2021-05-19T21:55:13Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13066811155/ca6sQg",
      "token": "Kx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13066811155/KQeuVg",
      "token": "Kx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/13066811155/LgvusA",
      "token": "Kx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ]
}
2021-05-13 00:00:32,713:DEBUG:acme.client:Storing nonce: 0003teO5LQ1JcC9ksguCzoK3Qj7AsLBs1YR_gLtFSpKvcVE
2021-05-13 00:00:32,714:INFO:certbot._internal.auth_handler:Performing the following challenges:
2021-05-13 00:00:32,714:INFO:certbot._internal.auth_handler:dns-01 challenge for flapili.fr
2021-05-13 00:00:32,714:INFO:certbot._internal.auth_handler:dns-01 challenge for flapili.fr
2021-05-13 00:00:32,717:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eu.api.ovh.com:443
2021-05-13 00:00:32,942:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
2021-05-13 00:00:33,032:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 14
2021-05-13 00:00:33,131:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/flapili.fr/status HTTP/1.1" 200 None
2021-05-13 00:00:33,132:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/root/certbot/certbot/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/root/certbot/certbot/certbot/plugins/dns_common.py", line 60, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/root/certbot/certbot-dns-ovh/certbot_dns_ovh/_internal/dns_ovh.py", line 59, in _perform
    self._get_ovh_client().add_txt_record(domain, validation_name, validation)
  File "/root/certbot/certbot/certbot/plugins/dns_common_lexicon.py", line 48, in add_txt_record
    self.provider.create_record(type='TXT', name=record_name, content=record_content)
TypeError: create_record() got an unexpected keyword argument 'type'

2021-05-13 00:00:33,132:DEBUG:certbot._internal.error_handler:Calling registered functions
2021-05-13 00:00:33,132:INFO:certbot._internal.auth_handler:Cleaning up challenges
2021-05-13 00:00:33,134:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): eu.api.ovh.com:443
2021-05-13 00:00:33,218:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/auth/time HTTP/1.1" 200 10
2021-05-13 00:00:33,273:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/ HTTP/1.1" 200 14
2021-05-13 00:00:33,351:DEBUG:urllib3.connectionpool:https://eu.api.ovh.com:443 "GET /1.0/domain/zone/flapili.fr/status HTTP/1.1" 200 None
2021-05-13 00:00:33,352:ERROR:certbot._internal.error_handler:Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
2021-05-13 00:00:33,354:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "venv/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/root/certbot/certbot/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/root/certbot/certbot/certbot/_internal/main.py", line 1435, in main
    return config.func(config, plugins)
  File "/root/certbot/certbot/certbot/_internal/main.py", line 1304, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/root/certbot/certbot/certbot/_internal/main.py", line 140, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/root/certbot/certbot/certbot/_internal/client.py", line 444, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/root/certbot/certbot/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/root/certbot/certbot/certbot/_internal/client.py", line 424, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/root/certbot/certbot/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/root/certbot/certbot/certbot/plugins/dns_common.py", line 60, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/root/certbot/certbot-dns-ovh/certbot_dns_ovh/_internal/dns_ovh.py", line 59, in _perform
    self._get_ovh_client().add_txt_record(domain, validation_name, validation)
  File "/root/certbot/certbot/certbot/plugins/dns_common_lexicon.py", line 48, in add_txt_record
    self.provider.create_record(type='TXT', name=record_name, content=record_content)
TypeError: create_record() got an unexpected keyword argument 'type'
2021-05-13 00:00:33,355:ERROR:certbot._internal.log:An unexpected error occurred:
2021-05-13 00:00:33,355:ERROR:certbot._internal.log:TypeError: create_record() got an unexpected keyword argument 'type'

```

**Comment by alexzorin** [comment]
Hello @flapili,

This is the same as https://github.com/certbot/certbot/issues/8826, which should be fixed in the next release.

You may be able to work around it in the meantime by downgrading lexicon in your Python virtual environment.

I am going to close this as a duplicate, but feel free to comment in the existing issue.
