### ISSUE TITLE
snapped certbot might symlink /etc/letsencrypt/options-ssl-nginx.conf directly into /snap, breaking the reverter

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8897]
We have a report [that Certbot ended up in a state where this file was symlinked into the read-only `/snap` squashfs mount](https://community.letsencrypt.org/t/cant-renew-my-certificates/153284/17?u=_az).

     lrwxrwxrwx 1 root root 108 May 9 10:29 /etc/letsencrypt/options-ssl-nginx.conf -> /snap/certbot/current/lib/python3.8/site-packages/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf

This messes up the reverter because the function we call in the reverter, `shutil.copy2`, can sometimes try to modify the existing file node, rather than unlinking `/etc/letsencrypt/options-ssl-nginx.conf` and creating a new one:

    2021-06-06 00:01:41,831:ERROR:certbot._internal.renewal:Failed to renew certificate minirobota.sk with error: Unable to revert temporary config
    2021-06-06 00:01:41,854:DEBUG:certbot._internal.renewal:Traceback was:
    Traceback (most recent call last):
      File "/snap/certbot/1200/lib/python3.8/site-packages/certbot/reverter.py", line 232, in _recover_checkpoint
        shutil.copy2(os.path.join(
      File "/snap/certbot/1200/usr/lib/python3.8/shutil.py", line 432, in copy2
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/snap/certbot/1200/usr/lib/python3.8/shutil.py", line 261, in copyfile
        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    OSError: [Errno 30] Read-only file system: '/etc/letsencrypt/options-ssl-nginx.conf'

If it's the case that Certbot can naturally end up in this situation (i.e. it wasn't a human which created the symlink originally), it should be prevented. 

However, I wasn't able to figure out how this could happen. So for now, I am creating this issue to track the possibility of this issue existing, in case anybody else runs into it.

**Comment by ziedHamdi** [comment]
Hi,

I have this message:
```
Unable to recover files from /home/weally/.certbot/work/temp_checkpoint
Incomplete or failed recovery for /home/weally/.certbot/work/temp_checkpoint
Encountered exception during recovery: certbot.errors.PluginError: Unable to revert temporary config
Some challenges have failed.

```

It happened after I changed my domain from preprod.weally.org to app.weally.org
But executing the solution you mentioned in https://community.letsencrypt.org/t/cant-renew-my-certificates/153284/16 also fails
```
sudo cp --remove-destination `readlink /etc/letsencrypt/options-ssl-nginx.conf` /etc/letsencrypt/options-ssl-nginx.conf
cp: missing destination file operand after '/etc/letsencrypt/options-ssl-nginx.conf'

```
