### ISSUE TITLE
Can we make the Apache installer handle the same file encodings that Augeas can?

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8915]
The Apache installer can be crashed by creating this vhost which is both non-ASCII and non-UTF-8:

    python -c 'print("<VirtualHost *:80>\nServerName example.com\n</VirtualHost>\n#" + chr(0xe9))'  > /etc/apache2/sites-enabled/crash.conf

and then trying to install a certificate to it:

    certbot --apache -d example.com

In the nginx plugin, we just skip files which raise `UnicodeError`. 

The Apache plugin is a little bit different because we use Augeas, which as it turns out, just works.

The problem only comes up during certificate installation, where the configurator copy pastes the source vhost into an SSL vhost (`_copy_create_ssl_vhost_skeleton`). When it does this, it goes through `open`, which tries the `utf-8` encoding by default and instantly raises an error, causing the installation to fail.

One could argue that the configurator should be able to handle the same files that Augeas can. 

I'd like to find out why Augeas doesn't run into trouble here and whether we can do the same in this 1 place in the plugin, to make this succeed.

    Traceback (most recent call last):
      File "/home/alex/devel/certbot/venv/bin/certbot", line 33, in <module>
        sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
      File "/home/alex/devel/certbot/certbot/certbot/main.py", line 15, in main
        return internal_main.main(cli_args)
      File "/home/alex/devel/certbot/certbot/certbot/_internal/main.py", line 1574, in main
        return config.func(config, plugins)
      File "/home/alex/devel/certbot/certbot/certbot/_internal/main.py", line 1303, in run
        _install_cert(config, le_client, domains, new_lineage)
      File "/home/alex/devel/certbot/certbot/certbot/_internal/main.py", line 930, in _install_cert
        le_client.deploy_certificate(domains, path_provider.key_path, path_provider.cert_path,
      File "/home/alex/devel/certbot/certbot/certbot/_internal/client.py", line 542, in deploy_certificate
        self.installer.deploy_cert(
      File "/home/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 516, in deploy_cert
        vhosts = self.choose_vhosts(domain)
      File "/home/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 542, in choose_vhosts
        return [self.choose_vhost(domain, create_if_no_ssl)]
      File "/home/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 719, in choose_vhost
        vhost = self.make_vhost_ssl(vhost)
      File "/home/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 1381, in make_vhost_ssl
        self._copy_create_ssl_vhost_skeleton(nonssl_vhost, ssl_fp)
      File "/home/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 1523, in _copy_create_ssl_vhost_skeleton
        orig_contents = self._get_vhost_block(vhost)
      File "/home/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 1629, in _get_vhost_block
        vh_contents = fh.read(span_end-span_start).split("\n")
      File "/usr/lib/python3.8/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 58: invalid continuation byte

**Comment by osirisinferi** [comment]
I made certbot just handle the Apache virtualhost configuration files as bytes in stead of strings. Works like a charm, although I didn't test it thoroughly, it just runs :stuck_out_tongue: 

Changed two `open()` calls to open the file as bytes and added 8 "b"s to string literals to change them into byte literals.

So to answer the issue title: yes we might :laughing: Not sure if Augeas also handles files as bytes tho, so not sure if it's the exact answer :slightly_smiling_face:

**Comment by alexzorin** [comment]
There is also this advice from Python about handling files with unknown encodings: https://docs.python.org/3/howto/unicode.html#files-in-an-unknown-encoding.

One relevant benefit of the surrogate escaping is that we would keep [universal newlines](https://docs.python.org/3/glossary.html#term-universal-newlines) for Windows, so the newly created SSL vhost files will be readable if opened in Notepad. 

I'm not sure whether there are any other differences between binary mode and surrogate escaping.
