### ISSUE TITLE
Unable to find pre-hook command net in the PATH. [Windows]

### ISSUE THREAD

**Issue by am2222** [certbot/certbot#8921]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):
Windows 7

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
Windows installer

## I ran this command and it produced this output:
``
certbot renew --dry-run --pre-hook "net stop Apache2.4" --post-hook "net start Apache2.4"
``

## Certbot's behavior differed from what I expected because:
I returns the following error

```
Unable to find pre-hook command net in the PATH.
(PATH is C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Certbot\bin;;C:\Program Files (x86)\Certbot\Python)
```

## Here is a Certbot log showing the issue (if available):

```
2021-06-20 22:06:06,251:DEBUG:certbot._internal.main:certbot version: 1.16.0
2021-06-20 22:06:06,251:DEBUG:certbot._internal.main:Location of certbot entry point: C:\Program Files (x86)\Certbot\bin\certbot.exe
2021-06-20 22:06:06,251:DEBUG:certbot._internal.main:Arguments: ['--dry-run', '--pre-hook', 'net stop Apache2.4', '--post-hook', 'net start Apache2.4', '-v', '--preconfigured-renewal']
2021-06-20 22:06:06,252:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-06-20 22:06:06,252:DEBUG:certbot.compat.misc:Failed to set console mode
Traceback (most recent call last):
  File "C:\Program Files (x86)\Certbot\pkgs\certbot\compat\misc.py", line 59, in prepare_virtual_console
    h.SetConsoleMode(h.GetConsoleMode() | ENABLE_VIRTUAL_TERMINAL_PROCESSING)
pywintypes.error: (87, 'SetConsoleMode', 'The parameter is incorrect.')
2021-06-20 22:06:06,266:DEBUG:certbot.plugins.util:Failed to find executable net in PATH: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Certbot\bin;;C:\Program Files (x86)\Certbot\Python
2021-06-20 22:06:06,266:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files (x86)\Certbot\bin\certbot.exe\__main__.py", line 29, in <module>
    sys.exit(main())
  File "C:\Program Files (x86)\Certbot\pkgs\certbot\main.py", line 15, in main
    return internal_main.main(cli_args)
  File "C:\Program Files (x86)\Certbot\pkgs\certbot\_internal\main.py", line 1525, in main
    args = cli.prepare_and_parse_args(plugins, cli_args)
  File "C:\Program Files (x86)\Certbot\pkgs\certbot\_internal\cli\__init__.py", line 431, in prepare_and_parse_args
    return helpful.parse_args()
  File "C:\Program Files (x86)\Certbot\pkgs\certbot\_internal\cli\helpful.py", line 220, in parse_args
    hooks.validate_hooks(parsed_args)
  File "C:\Program Files (x86)\Certbot\pkgs\certbot\_internal\hooks.py", line 20, in validate_hooks
    validate_hook(config.pre_hook, "pre")
  File "C:\Program Files (x86)\Certbot\pkgs\certbot\_internal\hooks.py", line 57, in validate_hook
    raise errors.HookCommandNotFound(msg)
certbot.errors.HookCommandNotFound: Unable to find pre-hook command net in the PATH.
(PATH is C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Certbot\bin;;C:\Program Files (x86)\Certbot\Python)
2021-06-20 22:06:06,267:ERROR:certbot._internal.log:Unable to find pre-hook command net in the PATH.
(PATH is C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Certbot\bin;;C:\Program Files (x86)\Certbot\Python)
```

## WorkAround
Use the following command
```
certbot renew --dry-run --pre-hook "net stop Apache2.4" --post-hook "net start Apache2.4" --disable-hook-validation
```

I think this method does not work on windows since `PATH` parameter only stores pathnames not the command names. so for the native commands such as `net` the following part will always return `False`
https://github.com/certbot/certbot/blob/bc7c953bcc53fe231b720e2591dcc9278fe3f09e/certbot/certbot/_internal/hooks.py#L51

````python
            path = os.environ["PATH"]
            if os.path.exists(cmd):
                msg = "{1}-hook command {0} exists, but is not executable.".format(cmd, hook_name)
            else:
                msg = "Unable to find {2}-hook command {0} in the PATH.\n(PATH is {1})".format(
                    cmd, path, hook_name)

            raise errors.HookCommandNotFound(msg)
````

**Comment by alexzorin** [comment]
Hi @am2222,

Thank you very much for the report.

I think this is the same bug as https://github.com/certbot/certbot/issues/8215. 

I'm going to get the website changed to specify `net.exe` rather than just `net`, which should work, without disabling hook validation.
