### ISSUE TITLE
CentOS 8: ModuleNotFoundError for urllib3.packages.six

### ISSUE THREAD

**Issue by mikeperalta1** [certbot/certbot#8946]
## My operating system is (include version):
CentOS 8
```Linux [hostname] 4.18.0-305.7.1.el8_4.x86_64 #1 SMP Tue Jun 29 21:55:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux```

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
EPEL with yum/dnf 
```
certbot.noarch                              1.14.0-1.el8                                      @epel      
python3-certbot.noarch                      1.14.0-1.el8                                      @epel 
```

## I ran this command and it produced this output:

A nightly script ran the following command:
```
certbot certonly --standalone --agree-tos --email [redacted] --cert-name [redacted] --cert-path /etc/letsencrypt/live/[redacted]/cert.pem --key-path /etc/letsencrypt/live/[redacted]/privkey.pem --chain-path /etc/letsencrypt/live/[redacted]/chain.pem --fullchain-path /etc/letsencrypt/live/[redacted]/fullchain.pem --non-interactive --no-redirect --expand -d [redacted] -d ns1.[redacted] -d git.[redacted] -d [redacted] -d [redacted]
```

I received the following output:
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==1.14.0', 'console_scripts', 'certbot')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2846, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/certbot/main.py", line 2, in <module>
    from certbot._internal import main as internal_main
  File "/usr/lib/python3.6/site-packages/certbot/_internal/main.py", line 22, in <module>
    from certbot import crypto_util
  File "/usr/lib/python3.6/site-packages/certbot/crypto_util.py", line 33, in <module>
    from certbot import util
  File "/usr/lib/python3.6/site-packages/certbot/util.py", line 23, in <module>
    from certbot._internal import constants
  File "/usr/lib/python3.6/site-packages/certbot/_internal/constants.py", line 6, in <module>
    from acme import challenges
  File "/usr/lib/python3.6/site-packages/acme/challenges.py", line 14, in <module>
    import requests
  File "/usr/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3.6/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six'
```

**Please Note**: This script, and certbot on my system has worked perfectly for years. This error only started today. yum/dnf show the system is up to date.

I think I could probably use pyenv to install a more recent python if you'd like me to test.

## Certbot's behavior differed from what I expected because:
It usually works.

## Here is a Certbot log showing the issue (if available):
N/A

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A

**Comment by bmw** [comment]
Problems like this are usually caused by installing Python packages from multiple sources such as your OS package manager and `pip`. I think this is especially likely given the traceback shows some packages being used from `/usr/local/lib` which isn't where yum/dnf installs Python packages. On a clean CentOS 8 Docker images, I cannot reproduce this error just installing the packages from EPEL 8.

Hopefully that helps you resolve the problem, but if you need additional help, I'd recommend either checking out https://certbot.eff.org/lets-encrypt/centosrhel8-other where we have suggested multiple alternatives to the EPEL packages which avoid issues like this or making a post at https://community.letsencrypt.org where there is a much larger group of people familiar with Certbot and system administration and should be able to help you with this.

**Comment by mikeperalta1** [comment]
@bmw Crud, you're right. Thank you for the explanation and sorry for not noticing /usr/local. I've recently installed pyenv for my pipenv, and that probably messed something up. I'll screw around with this on my own. Have a great day.
