### ISSUE TITLE
dns-cloudflare should guard against creating duplicate TXT records

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#8994]
https://community.letsencrypt.org/t/error-when-creating-new-certificates-using-cloudflare-dns/157924

Reading over [the Cloudflare DNS plugin](https://github.com/certbot/certbot/blob/525c427c60f14f8f4b8604044db4f9d9ff4230e4/certbot-dns-cloudflare/certbot_dns_cloudflare/_internal/dns_cloudflare.py#L106-L115), it seems that the code blindly believes that it will be able to add its TXT record without any conflict.

I can think of a couple of reasons this might not be the case (it was already manually added, or a previous attempt was uncleanly terminated + the ACME server decided to reuse the pending authorization from the previous attempt).

If we could make this more robust, that would avoid the issue:

- Catch the specific error code which is relating to exact duplicate TXT records and swallow it, or
- Check the existing RRs and avoid trying to create duplicates at all

**Comment by robhagopian** [comment]
Related - dns-cloudflare should have an --force to overwrite an existing _acme_challenge TXT record (that somehow wasn't cleaned up properly) instead of throwing vague errors

**Comment by AshleighAdams** [comment]
I'm also experiencing this issue, latest certbot docker image as of today:

```log
2023-03-16 10:18:02,615:DEBUG:acme.client:Storing nonce: 32...I
2023-03-16 10:18:02,615:INFO:certbot._internal.auth_handler:Performing the following challenges:
2023-03-16 10:18:02,615:INFO:certbot._internal.auth_handler:dns-01 challenge for sub.redacted.com
2023-03-16 10:18:02,615:INFO:certbot._internal.auth_handler:dns-01 challenge for sub.redacted.com
2023-03-16 10:18:02,627:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.cloudflare.com:443
2023-03-16 10:18:03,518:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?name=sub.redacted.com&per_page=1 HTTP/1.1" 200 None
2023-03-16 10:18:04,392:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?name=redacted.com&per_page=1 HTTP/1.1" 200 None
2023-03-16 10:18:04,393:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Found zone_id of 7b...7 for sub.redacted.com using name redacted.com
2023-03-16 10:18:04,393:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Attempting to add record to zone 7b...7: {'type': 'TXT', 'name': '_acme-challenge.sub.redacted.com', 'content': '...', 'ttl': 120}
2023-03-16 10:18:05,519:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "POST /client/v4/zones/7b...7/dns_records HTTP/1.1" 400 None
2023-03-16 10:18:05,520:ERROR:certbot_dns_cloudflare._internal.dns_cloudflare:Encountered CloudFlareAPIError adding TXT record: 81057 Record already exists.
2023-03-16 10:18:05,523:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/plugin/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 130, in add_txt_record
    self.cf.zones.dns_records.post(zone_id, data=data)  # zones | pylint: disable=no-member
  File "/usr/local/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 684, in post
    return self._base.do_auth('POST', self._parts, [identifier1, identifier2, identifier3, identifier4], params, data, files)
  File "/usr/local/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 129, in do_auth
    return self._call(method, headers, parts, identifiers, params, data, files)
  File "/usr/local/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 502, in _call
    raise CloudFlareAPIError(code, message)
CloudFlare.exceptions.CloudFlareAPIError: Record already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/opt/certbot/src/plugin/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 76, in _perform
    self._get_cloudflare_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/opt/certbot/src/plugin/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 139, in add_txt_record
    raise errors.PluginError('Error communicating with the Cloudflare API: {0}{1}'
certbot.errors.PluginError: Error communicating with the Cloudflare API: Record already exists.

2023-03-16 10:18:05,523:DEBUG:certbot._internal.error_handler:Calling registered functions
2023-03-16 10:18:05,523:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-03-16 10:18:05,540:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.cloudflare.com:443
2023-03-16 10:18:06,381:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?name=sub.redacted.com&per_page=1 HTTP/1.1" 200 None
2023-03-16 10:18:07,301:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?name=redacted.com&per_page=1 HTTP/1.1" 200 None
2023-03-16 10:18:07,302:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Found zone_id of 7b...7 for sub.redacted.com using name redacted.com
2023-03-16 10:18:08,161:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones/7b...7/dns_records?type=TXT&name=_acme-challenge.sub.redacted.com&content=...&per_page=1 HTTP/1.1" 200 None
2023-03-16 10:18:08,963:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "DELETE /client/v4/zones/7b...7/dns_records/6b..8 HTTP/1.1" 200 None
2023-03-16 10:18:08,964:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Successfully deleted TXT record.
2023-03-16 10:18:08,969:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.cloudflare.com:443
2023-03-16 10:18:09,795:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?name=sub.redacted.com&per_page=1 HTTP/1.1" 200 None
2023-03-16 10:18:10,625:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones?name=redacted.com&per_page=1 HTTP/1.1" 200 None
2023-03-16 10:18:10,625:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Found zone_id of 7b...7 for sub.redacted.com using name redacted.com
2023-03-16 10:18:11,485:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "GET /client/v4/zones/7b...7/dns_records?type=TXT&name=_acme-challenge.sub.redacted.com&content=...&per_page=1 HTTP/1.1" 200 None
2023-03-16 10:18:12,270:DEBUG:urllib3.connectionpool:https://api.cloudflare.com:443 "DELETE /client/v4/zones/7b...7/dns_records/60...5 HTTP/1.1" 200 None
2023-03-16 10:18:12,271:DEBUG:certbot_dns_cloudflare._internal.dns_cloudflare:Successfully deleted TXT record.
2023-03-16 10:18:12,272:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/certbot/src/plugin/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 130, in add_txt_record
    self.cf.zones.dns_records.post(zone_id, data=data)  # zones | pylint: disable=no-member
  File "/usr/local/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 684, in post
    return self._base.do_auth('POST', self._parts, [identifier1, identifier2, identifier3, identifier4], params, data, files)
  File "/usr/local/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 129, in do_auth
    return self._call(method, headers, parts, identifiers, params, data, files)
  File "/usr/local/lib/python3.10/site-packages/CloudFlare/cloudflare.py", line 502, in _call
    raise CloudFlareAPIError(code, message)
CloudFlare.exceptions.CloudFlareAPIError: Record already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1864, in main
    return config.func(config, plugins)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1597, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 129, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/opt/certbot/src/certbot/certbot/_internal/renewal.py", line 387, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/opt/certbot/src/certbot/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/opt/certbot/src/plugin/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 76, in _perform
    self._get_cloudflare_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/opt/certbot/src/plugin/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 139, in add_txt_record
    raise errors.PluginError('Error communicating with the Cloudflare API: {0}{1}'
certbot.errors.PluginError: Error communicating with the Cloudflare API: Record already exists.
2023-03-16 10:18:12,276:ERROR:certbot._internal.log:Error communicating with the Cloudflare API: Record already exists.
```

**Comment by luckylinux** [comment]
I can confirm that I just got hit by this today on the newest Docker Image ...

**Comment by ohemorange** [comment]
At least five people have reported being hit by this, so I'm upgrading the priority. If you hit this in the meantime, you can manually delete any `_acme-challenge.<domainname>` records you see, and try again.

**Comment by luckylinux** [comment]
Well AGAIN it keeps failing. This Time I already tried 3 Times and it still keeps failing ...

Usually on attempt Number 2 it goes through. Not today though :(

There must be some Caching/Propagation Delay/Race Condition Issue or something that it detects a TXT Record already existing, because neither BEFORE the Certbot Docker Container is run, neither AFTER the Certbot Docker Container is run, I cannot see ANY DNS Record in the Cloudflare Dashboard.

Actually I see this in my Podman Logs:
```
Jan 22 06:19:12 certbot certbot-whoami-thehomelab-cc[59510]: Performing the following challenges:
Jan 22 06:19:12 certbot certbot-whoami-thehomelab-cc[59510]: dns-01 challenge for whoami.MYDOMAIN.TLD
Jan 22 06:19:12 certbot certbot-whoami-thehomelab-cc[59510]: dns-01 challenge for whoami.MYDOMAIN.TLD
```

Could it be that is why it's complaining that the Record already exists ?

This is my Compose File:
```
version: '3'

services:
  certbot-whoami-MYDOMAIN-TLD:
    # Name of the Container
    # Must be unique in order to prevent Issues
    container_name: certbot-whoami-MYDOMAIN-TLD
    #
    # Use Official Docker Images Mirror
    # This should be Disabled as it can cause Docker.io Rate Limit to be triggered
    #image: certbot/dns-cloudflare:latest
    #
    # Use local Docker Images Mirror
    #image: docker.MYDOMAIN.TLD/docker.io/certbot/dns-cloudflare:latest
    image: docker.MYDOMAIN.TLD/certbot/dns-cloudflare:latest
    #
    # Must NOT be set when using docker.io Repository, otherwise will result in Docker.io Rate Limit being triggered
    pull_policy: "missing"
    #
    # Do not keep restarting the Container
    # One Run should be enough
    restart: "no"
    #
    # Allow 2-3 based on restart_policy
    # This keeps on restarting however ...
    #restart: "unless-stopped"
    #
    # When using Restart, limit the amount of attemps
    # This keeps on restarting however ...
    #restart_policy:
    #  condition: on-failure
    #  max-attempts: 2
    #
    # Just in case include .env File
    env_file:
      - .env
    #
    # Certificate generation/renewal Command
    command: >
     "certonly" "--dns-cloudflare"
     "--dns-cloudflare-credentials" "/secrets/certbot/cloudflare.ini"
     "--dns-cloudflare-propagation-seconds" "120"
     "--email" "MYEMAIL@gmail.com"
     "--agree-tos" "--no-eff-email"
     "--non-interactive"
     "--verbose"
     "-d" "whoami.MYDOMAIN.TLD"
     "-d" "*.whoami.MYDOMAIN.TLD"

    #
    # Use the default  Network
    networks:
      - podman
    #
    # Volumes to mount inside container
    volumes:
      - ~/containers/certificates/certbot/whoami.MYDOMAIN.TLD:/etc/letsencrypt:rw,z
      - ~/containers/data/certbot/whoami.MYDOMAIN.TLD:/var/lib/letsencrypt:rw,z
      - ~/containers/secrets/certbot/MYDOMAIN.TLD:/secrets/certbot:rw,z
      - ~/containers/log/certbot/whoami.MYDOMAIN.TLD:/var/log/letsencrypt:rw,z

# Networks to be used
networks:
  podman:
    external: true

# Force Renewal of Certificates even if they are NOT close to their expiry date
# Only to be used in abnormal and special Circumstances !
# command: >
# ...
#     "--force-renewal"

```

Increasing Propagation Delay to 120 Seconds finally worked .... The SECOND Time I did it.

I wonder if requesting both the "Main [Sub]domain" as well as its Wildcard causes these Issues ...

**Comment by jmg421** [comment]
## Proposed Fix

I fixed the same class of bug in the Route53 plugin (PR #10718), so I'm familiar with the pattern. Happy to port the fix to Cloudflare.

### Root Cause

`_CloudflareClient.add_txt_record()` calls `self.cf.dns.records.create()` without checking if the record already exists. This fails when:
1. A previous attempt was uncleanly terminated (TXT record left behind)
2. The ACME server reuses a pending authorization from a prior attempt (same token = same validation value)
3. Manual record already exists from debugging

### Fix

Check for existing matching record before creating. If it already exists with the correct content, treat it as success:

```python
def add_txt_record(self, domain, record_name, record_content, record_ttl):
    zone_id = self._find_zone_id(domain)

    # Check if record already exists with this exact content
    existing = self._find_txt_record_id(zone_id, record_name, record_content)
    if existing:
        logger.debug('TXT record already exists with correct content; no action needed.')
        return

    data = {
        'type': 'TXT',
        'name': record_name,
        'content': record_content,
        'ttl': record_ttl,
    }

    try:
        self.cf.dns.records.create(zone_id=zone_id, **data)
    except cloudflare.APIStatusError as e:
        code = _cf_error_code(e)
        # 81057 = "Record already exists" — race condition, treat as success
        if code == 81057:
            logger.debug('TXT record was created concurrently; treating as success.')
            return
        # ... existing error handling ...
```

This is a two-layer defense:
1. Pre-check with `_find_txt_record_id()` (which already exists in the class for cleanup)
2. Catch-and-ignore the duplicate error code as a fallback for race conditions

### Scope

- Same pattern as Route53 fix in #10718 — idempotent record creation
- `_find_txt_record_id()` is already implemented and tested (used in `del_txt_record`)
- No new API calls needed beyond the existing helper

I can have a PR ready quickly since the infrastructure (the lookup method) already exists. Want me to go ahead?
