### ISSUE TITLE
certbot depends on cryptography<4,>=2 even though there is now 35.0.0

### ISSUE THREAD

**Issue by Joshix-1** [certbot/certbot#9099]
## My operating system is (include version):
- Arch Linux

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
- pacman
Version of cerbot: 1.21.0-1

## I ran this command and it produced this output:
```sh
sudo certbot
```
```
An unexpected error occurred:
pkg_resources.ContextualVersionConflict: (cryptography 35.0.0 (/usr/lib/python3.9/site-packages), Requirement.parse('cryptography<4,>=2'), {'dns-lexicon'})
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/tmp7nfkmqoj/log or re-run Certbot with -v for more details.
```

## Here is a Certbot log showing the issue (if available):
Contents of `/tmp/tmp7nfkmqoj/log`
```
2021-11-15 17:27:18,801:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==1.21.0', 'console_scripts', 'certbot')())
  File "/usr/lib/python3.9/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/main.py", line 1535, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python3.9/site-packages/certbot/_internal/plugins/disco.py", line 231, in find_all
    plugin_ep = cls._load_entry_point(entry_point, plugins, with_prefix=False)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/plugins/disco.py", line 249, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point, with_prefix)
  File "/usr/lib/python3.9/site-packages/certbot/_internal/plugins/disco.py", line 54, in __init__
    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 35.0.0 (/usr/lib/python3.9/site-packages), Requirement.parse('cryptography<4,>=2'), {'dns-lexicon'})
2021-11-15 17:27:18,801:ERROR:certbot._internal.log:An unexpected error occurred:
2021-11-15 17:27:18,802:ERROR:certbot._internal.log:pkg_resources.ContextualVersionConflict: (cryptography 35.0.0 (/usr/lib/python3.9/site-packages), Requirement.parse('cryptography<4,>=2'), {'dns-lexicon'})
```

**Comment by alexzorin** [comment]
This was fixed in https://github.com/AnalogJ/lexicon/issues/969.

Upgrading your installation of `dns-lexicon` to v3.7.1 or newer should fix this. v3.8.2-1 appears to be available in Arch's community repository.
