### ISSUE TITLE
Certbot not correctly cleaning up temp files when multiple instances are running

### ISSUE THREAD

**Issue by WesleyAC** [certbot/certbot#9173]
## My operating system is (include version):

`4.19.0-16-cloud-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux`

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

`apt`

---

I have several thousand files in /tmp that appear to be created by certbot. My expectation is that certbot should correctly clean up its temp files on error.

## Here is a Certbot log showing the issue (if available):

Here is one of the files:

```
2021-11-16 00:40:02,966:DEBUG:certbot.main:certbot version: 0.31.0
2021-11-16 00:40:02,966:DEBUG:certbot.main:Arguments: ['--noninteractive', '--keep-until-expiring', '--webroot', '--webroot-path', '/var/cert-webroot/', '--domain', 'REDACTED']
2021-11-16 00:40:02,966:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-digitalocean,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2021-11-16 00:40:02,977:DEBUG:certbot.lock:A lock on /var/log/letsencrypt/.certbot.lock is held by another process.
2021-11-16 00:40:02,977:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/lock.py", line 77, in _try_lock
    compat.lock_file(fd)
  File "/usr/lib/python3/dist-packages/certbot/compat.py", line 130, in lock_file
    fcntl.lockf(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.31.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 1351, in main
    log.post_arg_parse_setup(config)
  File "/usr/lib/python3/dist-packages/certbot/log.py", line 90, in post_arg_parse_setup
    config, 'letsencrypt.log', FILE_FMT)
  File "/usr/lib/python3/dist-packages/certbot/log.py", line 137, in setup_log_file_handler
    config.logs_dir, 0o700, compat.os_geteuid(), config.strict_permissions)
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 161, in set_up_core_dir
    lock_dir_until_exit(directory)
  File "/usr/lib/python3/dist-packages/certbot/util.py", line 135, in lock_dir_until_exit
    _LOCKS[dir_path] = lock.lock_dir(dir_path)
  File "/usr/lib/python3/dist-packages/certbot/lock.py", line 26, in lock_dir
    return LockFile(os.path.join(dir_path, '.certbot.lock'))
  File "/usr/lib/python3/dist-packages/certbot/lock.py", line 49, in __init__
    self.acquire()
  File "/usr/lib/python3/dist-packages/certbot/lock.py", line 62, in acquire
    self._try_lock(fd)
  File "/usr/lib/python3/dist-packages/certbot/lock.py", line 83, in _try_lock
    "Another instance of Certbot is already running.")
certbot.errors.LockError: Another instance of Certbot is already running.
```

**Comment by bmw** [comment]
This is currently expected behavior. If Certbot crashes before acquiring a lock on the logs directory, we put the log in `/tmp`. You can delete these files if you wish.
