### ISSUE TITLE
dns-lexicon not found

### ISSUE THREAD

**Issue by GreggGreen** [certbot/certbot#9243]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

Mac OS 12.3

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

Macports

## I ran this command and it produced this output:

certbot
An unexpected error occurred:
pkg_resources.DistributionNotFound: The 'dns-lexicon>=3.2.1' distribution was not found and is required by the application

## Certbot's behavior differed from what I expected because:

It's broken

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```

2022-03-18 12:18:27,975:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==1.25.0', 'console_scripts', 'certbot')())
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/certbot/_internal/main.py", line 1676, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/certbot/_internal/plugins/disco.py", line 241, in find_all
    plugin_ep = cls._load_entry_point(entry_point, plugins, with_prefix=False)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/certbot/_internal/plugins/disco.py", line 261, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point, with_prefix)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/certbot/_internal/plugins/disco.py", line 60, in __init__
    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2457, in load
    self.require(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2480, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'dns-lexicon>=3.2.1' distribution was not found and is required by the application
2022-03-18 12:18:27,975:ERROR:certbot._internal.log:An unexpected error occurred:
2022-03-18 12:18:27,975:ERROR:certbot._internal.log:pkg_resources.DistributionNotFound: The 'dns-lexicon>=3.2.1' distribution was not found and is required by the application

```

**Comment by osirisinferi** [comment]
Certbot itself does not depend on `dns-lexicon`, but some of its DNS plugins do. Do you have one of the DNS plugins installed?

Also, the dependency of dns-lexicon v3.2.1 hasn't been updated in at least 8 months. I.e., no recent change from Certbots side.

**Comment by alexzorin** [comment]
Our official macOS instructions are to install `certbot` from Homebrew: https://certbot.eff.org/instructions?ws=other&os=osx.

I noticed is that Lexicon is missing as a dependency from e.g. https://ports.macports.org/port/certbot-dns-ovh/details/.  When I try to install it locally, I get the same error message as @GreggGreen. I can fix this by manually installing the `py310-dns-lexicon` port.

@Schamschula is the maintainer of the Certbot packages in MacPorts, I think they may be able to render assistance here. Thank you.

**Comment by Schamschula** [comment]
Under MacPorts `py-dns-lexicon` is at version 3.9.4.

It is only needed for as a dependency of `certbot-dns-namecheap`, and not of `certbot` itself as mentioned above.

**Comment by Schamschula** [comment]
I didn't add the `certbot-dns-ovh` sub-port, so I hadn't personally tested it.

The original commit didn't declare a dependency on `certbot-dns-ovh`.

However, I hadn't gotten any tickets regarding it until now.

I will push an update shortly.

**Comment by osirisinferi** [comment]
See https://github.com/certbot/certbot/search?q=dns-lexicon&type= for the other 8 DNS plugins depending on Lexicon, if not already on your radar and/or not already depending on Lexicon 🙂

**Comment by alexzorin** [comment]
It looks like this should be fixed, once @GreggGreen updates their Certbot and DNS plugin ports. 

Thank you so much @Schamschula for your help and fixing this so quickly.

I'm going to close this issue, but please let us know if any issues persist.
