### ISSUE TITLE
JSONDecodeError in certbot_dns_google

### ISSUE THREAD

**Issue by philharmonie** [certbot/certbot#9256]
## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
certbot 0.31.0 in Docker container

## I ran this command and it produced this output:
I build my image with this Dockerfile:
```
FROM staticfloat/nginx-certbot
RUN apt update && apt install python3-certbot-nginx python3-certbot-dns-google -y
```
and from the container, I execute 
```
/usr/bin/certbot certonly --dns-google --dns-google-credentials /root/certbot-creds.ini -d '*.my-domain.com'
```

## Here is a Certbot log showing the issue (if available):
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-google, Installer None
Attempting to parse the version 0.40.0 renewal configuration file found at /etc/letsencrypt/renewal/my-example.com.conf with version 0.31.0 of Certbot. This might not work.
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
dns-01 challenge for my-example.com
Cleaning up challenges
Encountered exception during recovery: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/certbot/error_handler.py", line 108, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 323, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/lib/python3/dist-packages/certbot_dns_google/dns_google.py", line 73, in _cleanup
    self._get_google_client().del_txt_record(domain, validation_name, validation, self.ttl)
  File "/usr/lib/python3/dist-packages/certbot_dns_google/dns_google.py", line 76, in _get_google_client
    return _GoogleClient(self.conf('credentials'))
  File "/usr/lib/python3/dist-packages/certbot_dns_google/dns_google.py", line 88, in __init__
    credentials = ServiceAccountCredentials.from_json_keyfile_name(account_json, scopes)
  File "/usr/lib/python3/dist-packages/oauth2client/service_account.py", line 220, in from_json_keyfile_name
    client_credentials = json.load(file_obj)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
An unexpected error occurred:
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Please see the logfiles in /var/log/letsencrypt for more details.
```

**Comment by alexzorin** [comment]
The error suggests that the `/root/certbot-creds.ini` file inside the container is empty.

If you need support using Certbot, please post you question on https://community.letsencrypt.org/ where there are a lot of contributors available to help you.

**Comment by philharmonie** [comment]
> The error suggests that the `/root/certbot-creds.ini` file inside the container is empty.

But it is not:
```
cat /root/certbot-creds.ini
dns_google_token = mytoken
```

**Comment by osirisinferi** [comment]
That's not a valid certbot-dns-google credentials file. Please see the [plugins documentation](https://certbot-dns-google.readthedocs.io/en/stable/). If you don't manage to find a solution there, please open a thread in the Help section on the Community as mentioned earlier.

**Comment by philharmonie** [comment]
I get the exact same error with this file:
```
{
  "type": "service_account",
  "project_id": "my-domain",
  "private_key_id": "myid",
  "private_key": "mykeyfile",
  "client_email": "mail@my-domain.com",
  "client_id": "myid",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/my-domain%40my-domain.iam.gserviceaccount.com"
}
```

**Comment by alexzorin** [comment]
I wasn't able to reproduce this, using the Docker container you mentioned. For me, Certbot crashes upon encountering the redacted private key, which is the expected result.

    root@57e761bcbafa:/# cat /root/certbot-creds.ini
    {
    "type": "service_account",
    "project_id": "my-domain",
    "private_key_id": "myid",
    "private_key": "mykeyfile",
    "client_email": "mail@my-domain.com",
    "client_id": "myid",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/my-domain%40my-domain.iam.gserviceaccount.com"
    }
    root@57e761bcbafa:/# /usr/bin/certbot certonly --dns-google --dns-google-credentials /root/certbot-creds.ini -d '*.my-domain.com' --dry-run
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Plugins selected: Authenticator dns-google, Installer None
    Obtaining a new certificate
    Performing the following challenges:
    dns-01 challenge for my-domain.com
    Unsafe permissions on credentials configuration file: /root/certbot-creds.ini
    Cleaning up challenges
    Encountered exception during recovery:
    Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 75, in handle_authorizations
        resp = self._solve_challenges(aauthzrs)
    File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 139, in _solve_challenges
        resp = self.auth.perform(all_achalls)
    File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 57, in perform
        self._perform(domain, validation_domain_name, validation)
    File "/usr/lib/python3/dist-packages/certbot_dns_google/dns_google.py", line 70, in _perform
        self._get_google_client().add_txt_record(domain, validation_name, validation, self.ttl)
    File "/usr/lib/python3/dist-packages/certbot_dns_google/dns_google.py", line 76, in _get_google_client
        return _GoogleClient(self.conf('credentials'))
    File "/usr/lib/python3/dist-packages/certbot_dns_google/dns_google.py", line 88, in __init__
        credentials = ServiceAccountCredentials.from_json_keyfile_name(account_json, scopes)
    File "/usr/lib/python3/dist-packages/oauth2client/service_account.py", line 223, in from_json_keyfile_name
        revoke_uri=revoke_uri)
    File "/usr/lib/python3/dist-packages/oauth2client/service_account.py", line 185, in _from_parsed_json_keyfile
        signer = crypt.Signer.from_string(private_key_pkcs8_pem)
    File "/usr/lib/python3/dist-packages/oauth2client/_openssl_crypt.py", line 119, in from_string
        pkey = crypto.load_pkcs12(key, password).get_privatekey()
    File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3058, in load_pkcs12
        _raise_current_error()
    File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
        raise exception_type(errors)
    OpenSSL.crypto.Error: [('asn1 encoding routines', 'asn1_d2i_read_bio', 'not enough data')]

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/certbot/error_handler.py", line 108, in _call_registered
        self.funcs[-1]()
    File "/usr/lib/python3/dist-packages/certbot/auth_handler.py", line 323, in _cleanup_challenges
        self.auth.cleanup(achalls)
    File "/usr/lib/python3/dist-packages/certbot/plugins/dns_common.py", line 76, in cleanup
        self._cleanup(domain, validation_domain_name, validation)
    File "/usr/lib/python3/dist-packages/certbot_dns_google/dns_google.py", line 73, in _cleanup
        self._get_google_client().del_txt_record(domain, validation_name, validation, self.ttl)
    File "/usr/lib/python3/dist-packages/certbot_dns_google/dns_google.py", line 76, in _get_google_client
        return _GoogleClient(self.conf('credentials'))
    File "/usr/lib/python3/dist-packages/certbot_dns_google/dns_google.py", line 88, in __init__
        credentials = ServiceAccountCredentials.from_json_keyfile_name(account_json, scopes)
    File "/usr/lib/python3/dist-packages/oauth2client/service_account.py", line 223, in from_json_keyfile_name
        revoke_uri=revoke_uri)
    File "/usr/lib/python3/dist-packages/oauth2client/service_account.py", line 185, in _from_parsed_json_keyfile
        signer = crypt.Signer.from_string(private_key_pkcs8_pem)
    File "/usr/lib/python3/dist-packages/oauth2client/_openssl_crypt.py", line 119, in from_string
        pkey = crypto.load_pkcs12(key, password).get_privatekey()
    File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 3058, in load_pkcs12
        _raise_current_error()
    File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
        raise exception_type(errors)
    OpenSSL.crypto.Error: [('asn1 encoding routines', 'asn1_d2i_read_bio', 'not enough data')]
    An unexpected error occurred:
    OpenSSL.crypto.Error: [('asn1 encoding routines', 'asn1_d2i_read_bio', 'not enough data')]
    Please see the logfiles in /var/log/letsencrypt for more details.

    IMPORTANT NOTES:
    - Your account credentials have been saved in your Certbot
    configuration directory at /etc/letsencrypt. You should make a
    secure backup of this folder now. This configuration directory will
    also contain certificates and private keys obtained by Certbot so
    making regular backups of this folder is ideal.
