### ISSUE TITLE
Certbot incompatibility with cryptography >=35

### ISSUE THREAD

**Issue by Ultraboss77** [certbot/certbot#9299]
Certbot seems incompatible with cryptography >=35

## My operating system is (include version):
Linux myhost 4.19.0-20-arm64 #1 SMP Debian 4.19.235-1 (2022-03-17) aarch64 GNU/Linux

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
pip 22.1.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)

## I ran this command and it produced this output:
certbot certificates -d "xxxxxxxxxxxxxxxxxxxx"

## Here is a Certbot log showing the issue (if available):
```cat /var/log/letsencrypt/letsencrypt.log
2022-05-22 00:13:41,409:DEBUG:certbot._internal.main:certbot version: 1.27.0
2022-05-22 00:13:41,410:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2022-05-22 00:13:41,410:DEBUG:certbot._internal.main:Arguments: ['-d', 'xxxxxxxxxxxxxxxxxxxxxx']
2022-05-22 00:13:41,411:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2022-05-22 00:13:41,434:DEBUG:certbot._internal.log:Root logging level set at 30
2022-05-22 00:13:41,457:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1744, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/main.py", line 1335, in certificates
    cert_manager.certificates(config)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/cert_manager.py", line 95, in certificates
    _describe_certs(config, parsed_certs, parse_failures)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/cert_manager.py", line 406, in _describe_certs
    notify(_report_human_readable(config, parsed_certs))
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/cert_manager.py", line 386, in _report_human_readable
    cert_info = human_readable_cert_info(config, cert)
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/cert_manager.py", line 309, in human_readable_cert_info
    if cert.target_expiry <= now:
  File "/usr/local/lib/python3.7/dist-packages/certbot/_internal/storage.py", line 545, in target_expiry
    return crypto_util.notAfter(cert_path)
  File "/usr/local/lib/python3.7/dist-packages/certbot/crypto_util.py", line 579, in notAfter
    return _notAfterBefore(cert_path, crypto.X509.get_notAfter)
  File "/usr/local/lib/python3.7/dist-packages/certbot/crypto_util.py", line 598, in _notAfterBefore
    timestamp = method(x509)
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1407, in get_notAfter
    return self._get_boundary_time(_lib.X509_get_notAfter)
AttributeError: module 'lib' has no attribute 'X509_get_notAfter'
2022-05-22 00:13:41,463:ERROR:certbot._internal.log:An unexpected error occurred:
2022-05-22 00:13:41,463:ERROR:certbot._internal.log:AttributeError: module 'lib' has no attribute 'X509_get_notAfter'
```

I have to manually downgrade cryptography package with version cryptography==3.4.8 to make certbot works again !

According to cryptography changelog, there are some backwards incompatibility since v35 :
https://cryptography.io/en/latest/changelog/#v35-0-0

Do you think you can add a dependency in you setup.py like 'cryptography>=2.5.0,<35' ??

**Comment by alexzorin** [comment]
Certbot is compatible with `cryptography` at least as recent as `36.0.2`, which is what the current version of the Certbot snap uses.

What distro are you following the `pip` instructions on? Your issue looks to possibly be environmental relating to OpenSSL.

**Comment by alexzorin** [comment]
>2022-05-22 00:13:41,410:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot

Ah. You have installed Certbot into the global Python environment. This is a surefire way to run into problems, unfortunately.

Please try following the [`pip` instructions](https://certbot.eff.org/instructions?ws=other&os=pip) which make use of a Python virtual environment.

**Comment by osirisinferi** [comment]
I can't reproduce your issue with a fresh install of Certbot installed using pip as specified according to the instructions, i.e.: using a virtual environment. This fresh install comes with cryptography 37.0.2, so I'm pretty sure the issue isn't with cryptography >= 35.

Looking at the error message (especially `_lib.X509_get_notAfter`), it seems you're using a pyOpenSSL library older than version 20.0.0, which was released in November 2020. In version 20.0.0 the [`X509_get_notAfter()` function was changed to the current `X509_getm_notAfter()` method](https://github.com/pyca/pyopenssl/commit/43a23a313ae475310ee0e9734e083de145893c7a) which was [introduced in cryptography version 2.8.0](https://github.com/pyca/cryptography/commit/f5735cf25acd08222368a1db615bbf61d36b8007).

These older functions have been removed since [cryptography 36.0.0](https://github.com/pyca/cryptography/commit/81b374784441777993cde3f648815971b315ce6c), but shouldn't have been an issue when having an up to date pyOpenSSL.

**Comment by Ultraboss77** [comment]
Upgrade the pyOpenssl package solved the issue !
Thanks for the help and sorry for the bad warning :)

**Comment by Ultraboss77** [comment]
Not a certbot issue, need pyOpenssl >=20 if cryptography >= 35.
