### ISSUE TITLE
certbot snap package crash on RHEL 7.9

### ISSUE THREAD

**Issue by daniejstriata** [certbot/certbot#9332]
## My operating system is (include version):
RHEL 7.9

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
snap 2.56.2

## I ran this command and it produced this output:
Installing the certbot snap or attempting to run it creates the error below

## Certbot's behavior differed from what I expected because:
It cannot run or after removing it not it cannot be installed as it crashes. I tried the beta channel too with the same crash. Before I removed it I got the same error as below.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
```
→ snap install --channel=beta certbot  --classic
error: cannot perform the following tasks:
- Run hook prepare-plug-plugin of snap "certbot" (run hook "prepare-plug-plugin": 
-----
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw({0x722101, 0x0})
	/usr/lib/golang/src/runtime/panic.go:1198 +0x71 fp=0x7ffeebb00c10 sp=0x7ffeebb00be0 pc=0x435211
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:719 +0x396 fp=0x7ffeebb00c60 sp=0x7ffeebb00c10 pc=0x44a996

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5e6bb0, 0xc0000db7f8)
	/usr/lib/golang/src/runtime/cgocall.go:156 +0x5c fp=0xc0000db7d0 sp=0xc0000db798 pc=0x40551c
crypto/internal/boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL()
	_cgo_gotypes.go:603 +0x49 fp=0xc0000db7f8 sp=0xc0000db7d0 pc=0x533989
crypto/internal/boring.init.0()
	/usr/lib/golang/src/crypto/internal/boring/boring.go:46 +0x45 fp=0xc0000db830 sp=0xc0000db7f8 pc=0x534705
runtime.doInit(0xad3440)
	/usr/lib/golang/src/runtime/proc.go:6498 +0x123 fp=0xc0000db968 sp=0xc0000db830 pc=0x444923
runtime.doInit(0xad1160)
	/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000dbaa0 sp=0xc0000db968 pc=0x444871
runtime.doInit(0xad4220)
	/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000dbbd8 sp=0xc0000dbaa0 pc=0x444871
runtime.doInit(0xad3200)
	/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000dbd10 sp=0xc0000dbbd8 pc=0x444871
runtime.doInit(0xad4b60)
	/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000dbe48 sp=0xc0000dbd10 pc=0x444871
runtime.doInit(0xad2d80)
	/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000dbf80 sp=0xc0000dbe48 pc=0x444871
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:238 +0x1e6 fp=0xc0000dbfe0 sp=0xc0000dbf80 pc=0x4378a6
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000dbfe8 sp=0xc0000dbfe0 pc=0x464221

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000032fb0 sp=0xc000032f90 pc=0x437cb6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:372
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:306 +0xad fp=0xc000032fe0 sp=0xc000032fb0 pc=0x437b4d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000032fe8 sp=0xc000032fe0 pc=0x464221
created by runtime.init.8
	/usr/lib/golang/src/runtime/proc.go:294 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc0000337b0 sp=0xc000033790 pc=0x437cb6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:372
runtime.bgsweep()
	/usr/lib/golang/src/runtime/mgcsweep.go:163 +0x88 fp=0xc0000337e0 sp=0xc0000337b0 pc=0x4243e8
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000337e8 sp=0xc0000337e0 pc=0x464221
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:181 +0x55

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000033f80 sp=0xc000033f60 pc=0x437cb6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:372
runtime.bgscavenge()
	/usr/lib/golang/src/runtime/mgcscavenge.go:265 +0xcd fp=0xc000033fe0 sp=0xc000033f80 pc=0x4224ed
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000033fe8 sp=0xc000033fe0 pc=0x464221
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:182 +0x65

goroutine 18 [runnable]:
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:162 fp=0xc0000327e0 sp=0xc0000327d8 pc=0x419ea0
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000327e8 sp=0xc0000327e0 pc=0x464221
created by runtime.createfing
	/usr/lib/golang/src/runtime/mfinal.go:157 +0x45
-----)

```
installed package
```
→ rpm -qa | grep snap
snappy-1.1.0-3.el7.x86_64
snap-confine-2.56.2-1.el7.x86_64
snapd-2.56.2-1.el7.x86_64
snapd-selinux-2.56.2-1.el7.noarch
```
```
→ snap list
Name                    Version   Rev    Tracking       Publisher     Notes
btop                    1.2.7     433    latest/stable  kz6fittycent  -
certbot-dns-cloudflare  1.28.0    1748   latest/beta    certbot-eff✓  -
core                    16-2.56   13308  latest/stable  canonical✓    core
core20                  20220527  1518   latest/stable  canonical✓    base
core22                  20220607  188    latest/stable  canonical✓    base
htop                    3.2.1     3414   latest/stable  maxiberta     -
snapd                   2.56      16010  latest/stable  canonical✓    snapd
tmux                    2.3       11     latest/stable  shawn111      classic
```
```
→ snap version
snap    2.56.2-1.el7
snapd   2.56.2-1.el7
series  16
rhel    7.9
kernel  3.10.0-1160.66.1.el7.x86_64
```
Before I removed it:

```
→ certbot renew
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw({0x722101, 0x0})
	/usr/lib/golang/src/runtime/panic.go:1198 +0x71 fp=0x7ffcd357ac10 sp=0x7ffcd357abe0 pc=0x435211
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:719 +0x396 fp=0x7ffcd357ac60 sp=0x7ffcd357ac10 pc=0x44a996

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5e6bb0, 0xc0000d97f8)
	/usr/lib/golang/src/runtime/cgocall.go:156 +0x5c fp=0xc0000d97d0 sp=0xc0000d9798 pc=0x40551c
crypto/internal/boring._Cfunc__goboringcrypto_DLOPEN_OPENSSL()
	_cgo_gotypes.go:603 +0x49 fp=0xc0000d97f8 sp=0xc0000d97d0 pc=0x533989
crypto/internal/boring.init.0()
	/usr/lib/golang/src/crypto/internal/boring/boring.go:46 +0x45 fp=0xc0000d9830 sp=0xc0000d97f8 pc=0x534705
runtime.doInit(0xad3440)
	/usr/lib/golang/src/runtime/proc.go:6498 +0x123 fp=0xc0000d9968 sp=0xc0000d9830 pc=0x444923
runtime.doInit(0xad1160)
	/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000d9aa0 sp=0xc0000d9968 pc=0x444871
runtime.doInit(0xad4220)
	/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000d9bd8 sp=0xc0000d9aa0 pc=0x444871
runtime.doInit(0xad3200)
	/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000d9d10 sp=0xc0000d9bd8 pc=0x444871
runtime.doInit(0xad4b60)
	/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000d9e48 sp=0xc0000d9d10 pc=0x444871
runtime.doInit(0xad2d80)
	/usr/lib/golang/src/runtime/proc.go:6475 +0x71 fp=0xc0000d9f80 sp=0xc0000d9e48 pc=0x444871
runtime.main()
	/usr/lib/golang/src/runtime/proc.go:238 +0x1e6 fp=0xc0000d9fe0 sp=0xc0000d9f80 pc=0x4378a6
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000d9fe8 sp=0xc0000d9fe0 pc=0x464221

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000038fb0 sp=0xc000038f90 pc=0x437cb6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:372
runtime.forcegchelper()
	/usr/lib/golang/src/runtime/proc.go:306 +0xad fp=0xc000038fe0 sp=0xc000038fb0 pc=0x437b4d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000038fe8 sp=0xc000038fe0 pc=0x464221
created by runtime.init.8
	/usr/lib/golang/src/runtime/proc.go:294 +0x25

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc0000397b0 sp=0xc000039790 pc=0x437cb6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:372
runtime.bgsweep()
	/usr/lib/golang/src/runtime/mgcsweep.go:163 +0x88 fp=0xc0000397e0 sp=0xc0000397b0 pc=0x4243e8
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000397e8 sp=0xc0000397e0 pc=0x464221
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:181 +0x55

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000039f80 sp=0xc000039f60 pc=0x437cb6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:372
runtime.bgscavenge()
	/usr/lib/golang/src/runtime/mgcscavenge.go:265 +0xcd fp=0xc000039fe0 sp=0xc000039f80 pc=0x4224ed
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000039fe8 sp=0xc000039fe0 pc=0x464221
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:182 +0x65

goroutine 18 [finalizer wait]:
runtime.gopark(0xae7580, 0xc000038770, 0x71, 0x48, 0xad25a0)
	/usr/lib/golang/src/runtime/proc.go:366 +0xd6 fp=0xc000038630 sp=0xc000038610 pc=0x437cb6
runtime.goparkunlock(...)
	/usr/lib/golang/src/runtime/proc.go:372
runtime.runfinq()
	/usr/lib/golang/src/runtime/mfinal.go:177 +0xb3 fp=0xc0000387e0 sp=0xc000038630 pc=0x419f53
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000387e8 sp=0xc0000387e0 pc=0x464221
created by runtime.createfing
	/usr/lib/golang/src/runtime/mfinal.go:157 +0x45
Aborted (core dumped)

```

**Comment by daniejstriata** [comment]
I rolled back to snapd 2.55.3. Reinstalled certbot and it is functioning again. I tested the same version of snapd, 2.56.2, on Rocky Linux 8 and had no issues.

**Comment by alexzorin** [comment]
Uh, hmmm. 

What this looks like to me is that one of the snap binaries on your system is built using the FIPS version of Go, which uses BoringSSL rather than native Go cryptography. 

There is a crash happening somewhere in that BoringCrypto cgo code.

If this is still happening with the latest version of snapd, I think this is worth reporting to the maintainers of the EPEL snapd packagers, or perhaps posting to https://forum.snapcraft.io/.

**Comment by daniejstriata** [comment]
Installing snapd 2.57.6 is still breaking certbot. I logged a ticket on EPEL7 Bugzilla.

**Comment by figureone** [comment]
We're seeing this behavior also after an update to snapd 2.57.6 from EPEL7. Please let us know if you see any progress on bugzilla!

**Comment by alexzorin** [comment]
snapd-2.57.6-2.el7 should have fixed this, which was released just before Christmas. What's your exact version?

    rpm -q snapd

**Comment by figureone** [comment]
`snapd-2.57.6-1.el7` but you are correct `snapd-2.57.6-2.el7` resolves the issue.
Our local EPEL repo was a little outdated, thanks @alexzorin for letting us know about the new version!
