### ISSUE TITLE
Certbot Fails to Execute With OpenSSL 3.0 on FreeBSD

### ISSUE THREAD

**Issue by denradford** [certbot/certbot#9376]
Ran into this incompatibility after upgrading OpenSSL from 1.1.1 to 3.0

## My operating system is (include version):
FreeBSD 13.1
Python 3.10
OpenSSL 3.0

## I ran this command and it produced this output:
 certbot certonly --standalone --dry-run --csr rsa-csr.pem -n
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==1.29.0', 'console_scripts', 'certbot')())
  File "/usr/local/bin/certbot", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/usr/local/lib/python3.10/site-packages/certbot/_internal/main.py", line 19, in <module>
    import josepy as jose
  File "/usr/local/lib/python3.10/site-packages/josepy/__init__.py", line 40, in <module>
    from josepy.json_util import (
  File "/usr/local/lib/python3.10/site-packages/josepy/json_util.py", line 14, in <module>
    from OpenSSL import crypto
  File "/usr/local/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.10/site-packages/OpenSSL/crypto.py", line 17, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python3.10/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /usr/local/lib/python3.10/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: Undefined symbol "ERR_GET_FUNC"

ERR_GET_FUNC has been deprecated and removed from OpenSSL 3.0
[https://github.com/openssl/openssl/issues/15946](url)

**Comment by osirisinferi** [comment]
Which version of cryptography is installed at `/usr/local/lib/python3.10/site-packages/cryptography`? I suspect this is due to cryptography not being updated to a recent enough version.

**Comment by denradford** [comment]
> Which version of cryptography is installed at `/usr/local/lib/python3.10/site-packages/cryptography`? I suspect this is due to cryptography not being updated to a recent enough version.

You are spot on it appears. My version is 3.4.8.
 
> If I check `_openssl.abi3.so` of version 3.4.8 for the text `ERR_GET_FUNC`, it's present. The [cryptography changelog](https://cryptography.io/en/latest/changelog/) mentions addition of support for OpenSSL 3.0 as of version 35.0.0. If I install version 35.0.0, there is _no_ presence of `ERR_GET_FUNC` in `_openssl.abi3.so` any longer.

The FreeBSD port of py-cryptography  is stalled at version 3.4.8 which is the latest. [https://www.freshports.org/security/py-cryptography](url)

> Please update your `cryptography` library to the most recent version, at least 35.0.0 for OpenSSL 3.0 support. Also I do not recommend using `pip` to install Python libraries globally due to version differences/incompatibilities, but always use a virtual environment.

I compile everything from source., if a dependency i.e. openssl changes or is upgraded then all ports that depend on it are also recompiled  I will reach out the port maintainer to share our findings and see if he has time to port a more recent version of py-cryptography to FreeBSD. When I have time I will also try to build the latest version myself.

**Comment by osirisinferi** [comment]
> The FreeBSD port of py-cryptography is stalled at version 3.4.8 which is the latest. [https://www.freshports.org/security/py-cryptography](url)
> (&hellip;)
> I compile everything from source

Ah, sorry, I assumed `pip` was used, as I could only find `py39-cryptography` when [searching on FreeBSD Ports](https://www.freebsd.org/cgi/ports.cgi?query=cryptography&stype=all) and you were using Python 3.10.



> I will reach out the port maintainer to share our findings and see if he has time to port a more recent version of py-cryptography to FreeBSD.

That sounds like the best solution indeed. In any case, not much the Certbot team can do, I'm afraid, and therefore I'm closing your thread as completed :slightly_smiling_face:
