### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by alvinwangs** [certbot/certbot#9411]
## My operating system is (include version):
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.2
PRETTY_NAME="Alpine Linux v3.8"

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
apk update && apk add --no-cache certbot && apk add --no-cache python2 py2-pip python-dev 
apk --no-cache -U upgrade && \
    apk --no-cache -U add --virtual .build-deps \
      gcc \
      linux-headers \
      openssl-dev \
      musl-dev \
      libffi-dev && \
    pip install --upgrade pip \
    pip --no-cache-dir install -U pip setuptools && \
    pip --no-cache-dir install -U certbot-dns-cloudflare && \
    apk --no-cache del .build-deps

## I ran this command and it produced this output:
certbot certonly --register-unsafely-without-email --eff-email --agree-tos --must-staple --staple-ocsp --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cloudflare/edge.cjhh.mom.ini  --dns-cloudflare-propagation-seconds 30 -d edge.cjhh.mom

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2022-09-20 09:39:16,749:DEBUG:acme.client:Storing nonce: 0101eF05pl6I-qbDbsWpvShkFPGbNXcXpHaKkD6mHdeC078
2022-09-20 09:39:16,750:INFO:certbot._internal.auth_handler:Performing the following challenges:
2022-09-20 09:39:16,750:INFO:certbot._internal.auth_handler:dns-01 challenge for edge.cjhh.mom
2022-09-20 09:39:16,770:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python2.7/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python2.7/site-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 77, in _perform
    self._get_cloudflare_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/usr/lib/python2.7/site-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 84, in _get_cloudflare_client
    return _CloudflareClient(None, self.credentials.conf('api-token'))
  File "/usr/lib/python2.7/site-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 94, in __init__
    self.cf = CloudFlare.CloudFlare(email, api_key)
  File "/usr/lib/python2.7/site-packages/CloudFlare/cloudflare.py", line 941, in __init__
    raise e
RuntimeError: maximum recursion depth exceeded

2022-09-20 09:39:16,770:DEBUG:certbot._internal.error_handler:Calling registered functions
2022-09-20 09:39:16,771:INFO:certbot._internal.auth_handler:Cleaning up challenges
2022-09-20 09:39:16,773:ERROR:certbot._internal.error_handler:Encountered exception during recovery: RuntimeError: maximum recursion depth exceeded
2022-09-20 09:39:16,773:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 1421, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 1294, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 135, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/client.py", line 441, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/client.py", line 421, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python2.7/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/lib/python2.7/site-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 77, in _perform
    self._get_cloudflare_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/usr/lib/python2.7/site-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 84, in _get_cloudflare_client
    return _CloudflareClient(None, self.credentials.conf('api-token'))
  File "/usr/lib/python2.7/site-packages/certbot_dns_cloudflare/_internal/dns_cloudflare.py", line 94, in __init__
    self.cf = CloudFlare.CloudFlare(email, api_key)
  File "/usr/lib/python2.7/site-packages/CloudFlare/cloudflare.py", line 941, in __init__
    raise e
RuntimeError: maximum recursion depth exceeded
2022-09-20 09:39:16,774:ERROR:certbot._internal.log:An unexpected error occurred:
2022-09-20 09:39:16,774:ERROR:certbot._internal.log:RuntimeError: maximum recursion depth exceeded

**Comment by alexzorin** [comment]
Alpine 3.8 is over 2 years EOL and Certbot dropped support for Python 2 a long time ago. I don't think we are able to help you in this case, sorry.
