### ISSUE TITLE
ContextualVersionConflict in certbot snap

### ISSUE THREAD

**Issue by cerebrate** [certbot/certbot#9428]
If you're having trouble using Certbot and aren't sure you've found a bug or
request for a new feature, please first try asking for help at
https://community.letsencrypt.org/. There is a much larger community there of
people familiar with the project who will be able to more quickly answer your
questions.

## My operating system is (include version):

Debian 11 (bullseye)

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

snap (v. 1.31.0, rev 2414)

## I ran this command and it produced this output:

`/snap/bin/certbot renew`

produced

```
An unexpected error occurred:
pkg_resources.ContextualVersionConflict: (cryptography 38.0.1 (/snap/certbot/2414/lib/python3.8/site-packages), Requirement.parse('cryptography<38,>=0.6'), {'msal'})
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-usz020sh/log or re-run Certbot with -v for more details.
```

(This error also occurs in the _snap.certbot.renew.service_ .)

## Certbot's behavior differed from what I expected because:

An unexpected error occurred, instead of a renewed certificate.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

```
2022-10-07 18:19:06,696:DEBUG:urllib3.connectionpool:http://localhost:None "GET /v2/connections?snap=certbot&interface=content HTTP/1.1" 200 784
2022-10-07 18:19:07,059:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/certbot/2414/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/_internal/main.py", line 1705, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 241, in find_all
    plugin_ep = cls._load_entry_point(entry_point, plugins, with_prefix=False)
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 261, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point, with_prefix)
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/_internal/plugins/disco.py", line 60, in __init__
    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
  File "/snap/certbot/2414/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2470, in load
    self.require(*args, **kwargs)
  File "/snap/certbot/2414/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2493, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/snap/certbot/2414/lib/python3.8/site-packages/pkg_resources/__init__.py", line 800, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 38.0.1 (/snap/certbot/2414/lib/python3.8/site-packages), Requirement.parse('cryptography<38,>=0.6'), {'msal'})
2022-10-07 18:19:07,059:ERROR:certbot._internal.log:An unexpected error occurred:
2022-10-07 18:19:07,059:ERROR:certbot._internal.log:pkg_resources.ContextualVersionConflict: (cryptography 38.0.1 (/snap/certbot/2414/lib/python3.8/site-packages), Requirement.parse('cryptography<38,>=0.6'), {'msal'})
```

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:

(I am using certbot-dns-azure.)

```
  server {
    listen 9443 ssl;
    server_name automation.arkane-systems.net;

    proxy_buffering off;

    location / {
      proxy_pass https://jeeves.harmony.arkane-systems.lan/;
      proxy_set_header Host $host;
      proxy_http_version 1.1;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Authorization $http_authorization;
      proxy_pass_header Authorization;
    }

    location /api/notify.html5/callback {
      if ($http_authorization = "") { return 403; }
      proxy_pass https://jeeves.harmony.arkane-systems.lan/;
      proxy_set_header Host $host;
    }

    ssl_certificate /etc/letsencrypt/live/automation.arkane-systems.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/automation.arkane-systems.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

  }
```

**Comment by alexzorin** [comment]
I think you will have to report this to https://github.com/terrycain/certbot-dns-azure.

From what I can tell, the `msal` library that the plugin uses depends on `cryptography<38`, except Certbot recently upgraded to `cryptography==38.0.1`.

I think the author of `certbot-dns-azure` should be able to bump the version of `azure-identity` to one of the newer releases, which in turn will use a [newer release of `msal`](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/14cbf591948ffb23eb64a675d81e4fa35112d1d9/setup.py#L79) which now depends on `cryptography<41` rather than `cryptography<38`.

cc @terrycain.

I'm going to close this issue because it's not something we can do about in the Certbot project.

**Comment by cerebrate** [comment]
Thanks for your help!
