### ISSUE TITLE
certbot-dns-google partly ignores https_proxy

### ISSUE THREAD

**Issue by Catscrash** [certbot/certbot#9434]
Hi, the certbot-dns-google Plugin seems to ignore the https_proxy variable for at least parts of the web-calls. Traffic to letsencrypt seems to properly be routed through the proxy, but then there are some calls to google, which go directly to the firewall.

## My operating system is (include version):
Debian 11

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
snap

## I ran this command and it produced this output:
http_proxy=...:3128
https_proxy=...:3128
export http_proxy
export https_proxy
certbot certonly -v --test-cert -c /etc/letsencrypt/cli-google.ini -d ... -d ...

(I also tried 
snap set system proxy.https="http://webproxy-internal.aspera.usu.grp:3128
without additional luck)
```

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-google, Installer None
Requesting a certificate for xxx and xxxx
Performing the following challenges:
dns-01 challenge for xxx
dns-01 challenge for xxx
Attempting refresh to obtain initial access_token
Refreshing access_token
Cleaning up challenges
Attempting refresh to obtain initial access_token
Refreshing access_token
Encountered exception during recovery: OSError: [Errno 99] Cannot assign requested address
An unexpected error occurred:
OSError: [Errno 99] Cannot assign requested address
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
```

## Certbot's behavior differed from what I expected because:
I can see the access to acme-staging-v02.api.letsencrypt.org:443 going via the proxy, but afterwards there's plenty of traffic in the firewall to Google IPs on Port TCP/443 and UDP/53. This should all be behind proxy.

## Here is a Certbot log showing the issue (if available):
```
2022-10-17 16:13:37,347:INFO:oauth2client.client:Refreshing access_token
2022-10-17 16:13:37,384:ERROR:certbot._internal.error_handler:Encountered exception during recovery: OSError: [Errno 99] Cannot assign requested address
2022-10-17 16:13:37,385:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/snap/certbot/2414/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/_internal/main.py", line 1744, in main
    return config.func(config, plugins)
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/_internal/main.py", line 1591, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/_internal/main.py", line 141, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/_internal/client.py", line 530, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/_internal/client.py", line 442, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/_internal/client.py", line 510, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/_internal/auth_handler.py", line 86, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/snap/certbot/2414/lib/python3.8/site-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/certbot_dns_google/_internal/dns_google.py", line 67, in _perform
    self._get_google_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/certbot_dns_google/_internal/dns_google.py", line 116, in add_txt_record
    zone_id = self._find_managed_zone_id(domain)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/certbot_dns_google/_internal/dns_google.py", line 281, in _find_managed_zone_id
    response = request.execute()
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/googleapiclient/http.py", line 923, in execute
    resp, content = _retry_request(
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/googleapiclient/http.py", line 191, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/oauth2client/transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/oauth2client/client.py", line 778, in _do_refresh_request
    resp, content = transport.request(
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/oauth2client/transport.py", line 280, in request
    return http_callable(uri, method=method, body=body, headers=headers,
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/httplib2/__init__.py", line 1701, in request
    (response, content) = self._request(
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/httplib2/__init__.py", line 1421, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/httplib2/__init__.py", line 1343, in _conn_request
    conn.connect()
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/httplib2/__init__.py", line 1179, in connect
    raise socket_err
  File "/snap/certbot-dns-google/current/lib/python3.8/site-packages/httplib2/__init__.py", line 1133, in connect
    sock.connect((self.host, self.port))
OSError: [Errno 99] Cannot assign requested address
2022-10-17 16:13:37,386:ERROR:certbot._internal.log:An unexpected error occurred:
2022-10-17 16:13:37,387:ERROR:certbot._internal.log:OSError: [Errno 99] Cannot assign requested address

```

**Comment by alexzorin** [comment]
I haven't been able to reproduce this.

Looking into the code, the underlying `httplib2` library that Google uses, does support `HTTP_PROXY` and `HTTPS_PROXY`.

Trying the `certbot-dns-google` snap out for myself, everything seems properly proxied:

    # tcpconnect.bt
    Attaching 2 probes...
    Tracing tcp connections. Hit Ctrl-C to end.
    
    # After setting HTTPS_PROXY
    TIME     PID      COMM             SADDR                                   SPORT  DADDR                                   DPORT
    18:53:46 3857     python3          127.0.0.1                               55506  127.0.0.1                               8888
    18:53:46 2035     tinyproxy        192.168.64.5                            44240  172.65.46.172                           443
    18:53:48 3857     python3          127.0.0.1                               55520  127.0.0.1                               8888
    18:53:48 2035     tinyproxy        192.168.64.5                            38876  142.250.70.202                          443
    18:53:48 3857     python3          127.0.0.1                               55534  127.0.0.1                               8888
    18:53:48 2035     tinyproxy        192.168.64.5                            38890  142.250.70.202                          443
    18:53:49 3857     python3          127.0.0.1                               55540  127.0.0.1                               8888
    18:53:49 2035     tinyproxy        192.168.64.5                            60370  142.250.70.170                          443
    18:53:49 3857     python3          127.0.0.1                               56446  127.0.0.1                               8888
    18:53:49 2035     tinyproxy        192.168.64.5                            39042  142.250.70.202                          443

    # After unsetting HTTPS_PROXY
    18:54:18 3902     python3          192.168.64.5                            47164  172.65.46.172                           443
    18:54:19 3902     python3          192.168.64.5                            51736  142.250.70.202                          443
    18:54:19 3902     python3          192.168.64.5                            51740  142.250.70.202                          443
    18:54:20 3902     python3          192.168.64.5                            49468  142.250.70.138                          443
    18:54:20 3902     python3          192.168.64.5                            51750  142.250.70.202                          443

I don't think this is an issue with the DNS plugin ignoring `HTTPS`.

For the actual error occurring here:

    2022-10-17 16:13:37,387:ERROR:certbot._internal.log:OSError: [Errno 99] Cannot assign requested address

I don't know what would be causing this. You might have some success capturing an `strace` of Certbot, to see what is triggering the error in more detail.

**Comment by alexzorin** [comment]
Thanks!
