### ISSUE TITLE
Upgrade to Bullseye, Certbot doesn't run

### ISSUE THREAD

**Issue by TheSmashy** [certbot/certbot#9480]
## My operating system is (include version):
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
apt

## I ran this command and it produced this output:
sudo certbot

## Certbot's behavior differed from what I expected because:
I got this:
sudo certbot
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/usr/local/lib/python3.9/dist-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/main.py", line 28, in <module>
    from certbot import crypto_util
  File "/usr/local/lib/python3.9/dist-packages/certbot/crypto_util.py", line 42, in <module>
    from certbot import interfaces
  File "/usr/local/lib/python3.9/dist-packages/certbot/interfaces.py", line 21, in <module>
    from acme.client import ClientBase
ImportError: cannot import name 'ClientBase' from 'acme.client' (/usr/local/lib/python3.9/dist-packages/acme/client.py)
###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
2022-11-23 17:18:27,896:DEBUG:certbot._internal.main:certbot version: 1.12.0
2022-11-23 17:18:27,899:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/bin/certbot
2022-11-23 17:18:27,899:DEBUG:certbot._internal.main:Arguments: []
2022-11-23 17:18:27,900:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2022-11-23 17:18:27,999:DEBUG:certbot._internal.log:Root logging level set at 20
2022-11-23 17:18:28,002:INFO:certbot._internal.log:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2022-11-23 17:18:28,006:DEBUG:certbot._internal.plugins.selection:Requested authenticator None and installer None
2022-11-23 17:18:28,008:DEBUG:certbot._internal.plugins.selection:No candidate plugin
2022-11-23 17:18:28,008:DEBUG:certbot._internal.plugins.selection:Selected authenticator None and installer None

**Comment by alexzorin** [comment]
> File "/usr/local/bin/certbot", line 5, in 

It looks like you have installed Certbot using system-wide `pip`.

This isn't a supported installation method and will frequently result in issues like this.

Please use one of the supported installation methods:

- Snap: https://certbot.eff.org/instructions?ws=other&os=snap
- Pip: https://certbot.eff.org/instructions?ws=other&os=pip
- or the `certbot` package that comes with Debian.

If you have difficulty with the installation, please ask on https://community.letsencrypt.org/.

**Comment by TheSmashy** [comment]
I uninstalled certbot with apt (sudo apt remove certbot && sudo apt autoremove) and installed snap and installed it with snap, still getting errors:
`sudo certbot
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/usr/local/lib/python3.9/dist-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/main.py", line 18, in <module>
    import configobj
ModuleNotFoundError: No module named 'configobj'`

**Comment by alexzorin** [comment]
You'll have to get rid of `/usr/local/bin/certbot` (the globally `pip`-installed installation) because it's taking priority on your `$PATH` over your other installations.

**Comment by TheSmashy** [comment]
yeah, I'm a genius and did a sudo rm /usr/local/bin/certbot and now it works.  I cam back to post this and saw your comment.  Thanks a ton.

**Comment by andyneff** [comment]
I had the same problem. I forgot to update the `acme` package version to match `certbot`

**Comment by bluce-clj** [comment]
> I had the same problem. I forgot to update the `acme` package version to match `certbot`

which acme version ? 
certbot verion is 1.32.0 how chiose acme version?
