### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

### ISSUE THREAD

**Issue by Neo005** [certbot/certbot#9528]
With python 3.10 on ubuntu 18 - its causing:

Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 5, in <module>
    from certbot.main import main
  File "/usr/local/lib/python3.10/dist-packages/certbot/main.py", line 6, in <module>
    from certbot._internal import main as internal_main
  File "/usr/local/lib/python3.10/dist-packages/certbot/_internal/main.py", line 21, in <module>
    from acme import client as acme_client
  File "/usr/local/lib/python3.10/dist-packages/acme/client.py", line 21, in <module>
    import requests
  File "/usr/local/lib/python3.10/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 40, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python3/dist-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/usr/lib/python3/dist-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/usr/lib/python3/dist-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by alexzorin** [comment]
If you're going to use `pip`, do so in a Python virtual environment by using [these instructions](https://certbot.eff.org/instructions?ws=other&os=pip).

Trying to install Certbot with `pip` globally can lead to these types of problems.

Please ask on https://community.letsencrypt.org/ if you need further help with installation.
