### ISSUE TITLE
Apache plugin crashes with module errors on default config Apache, macOS Ventura 13.1

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9538]
Unfortunately, I can no longer reproduce this issue, but it was reported [on the forums](https://community.letsencrypt.org/t/site-ssl-good-renewal-fails/191549) and I was able to reproduce it on my machine for a while. 

After applying a workaround (which was to move the `LoadModule` for `mod_ssl` and `mod_rewrite` to the top of the configuration file), I've not been able to reproduce this again, even after moving the directives back to their original location. How fun. 

IMO this is worth investigating still because more than 1 person has encountered it.

## My operating system is (include version):
macOS Ventura 13.1

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
`git` @  be3bf316c0e9f29cfe9c90e5dd7b903f88f54504

## I ran this command and it produced this output:

    $ sudo certbot certonly --apache -d example.com
    Saving debug log to /var/log/letsencrypt/letsencrypt.log
    Unable to read ssl_module file; not disabling session tickets.
    Requesting a certificate for example.com
    Error while running apachectl configtest.

    AH00526: Syntax error on line 1 of /private/etc/apache2/other/le_http_01_challenge_pre.conf:
    Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

    Error while running apachectl configtest.

    AH00526: Syntax error on line 1 of /private/etc/apache2/other/le_http_01_challenge_pre.conf:
    Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

    Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

## Certbot's behavior differed from what I expected because:

`apachectl configtest` did not report this same error.

The error appears when Certbot adds its directives into into Apache's configuration.

## Here is a Certbot log showing the issue (if available):

    2023-01-22 16:23:15,326:DEBUG:certbot._internal.main:certbot version: 2.3.0.dev0
    2023-01-22 16:23:15,326:DEBUG:certbot._internal.main:Location of certbot entry point: /Users/alex/devel/certbot/venv/bin/certbot
    2023-01-22 16:23:15,326:DEBUG:certbot._internal.main:Arguments: ['--apache', '-d', 'example.com']
    2023-01-22 16:23:15,326:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#apache,PluginEntryPoint#certbot-route53:auth,PluginEntryPoint#dns-cloudflare,PluginEntryPoint#dns-digitalocean,PluginEntryPoint#dns-dnsimple,PluginEntryPoint#dns-dnsmadeeasy,PluginEntryPoint#dns-gehirn,PluginEntryPoint#dns-google,PluginEntryPoint#dns-linode,PluginEntryPoint#dns-luadns,PluginEntryPoint#dns-nsone,PluginEntryPoint#dns-ovh,PluginEntryPoint#dns-rfc2136,PluginEntryPoint#dns-route53,PluginEntryPoint#dns-sakuracloud,PluginEntryPoint#manual,PluginEntryPoint#nginx,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
    2023-01-22 16:23:15,354:DEBUG:certbot._internal.log:Root logging level set at 30
    2023-01-22 16:23:15,355:DEBUG:certbot._internal.plugins.selection:Requested authenticator apache and installer apache
    2023-01-22 16:23:15,461:DEBUG:certbot_apache._internal.configurator:Apache version is 2.4.54
    2023-01-22 16:23:15,655:DEBUG:certbot_apache._internal.configurator:[Errno 2] No such file or directory: '/etc/apache2/libexec/apache2/mod_ssl.so'
    Traceback (most recent call last):
    File "/Users/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 297, in _open_module_file
        with open(ssl_module_location, mode="rb") as f:
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/etc/apache2/libexec/apache2/mod_ssl.so'
    2023-01-22 16:23:15,655:WARNING:certbot_apache._internal.configurator:Unable to read ssl_module file; not disabling session tickets.
    2023-01-22 16:23:15,656:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * apache
    Description: Apache Web Server plugin
    Interfaces: Authenticator, Installer, Plugin
    Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT
    Initialized: <certbot_apache._internal.override_darwin.DarwinConfigurator object at 0x104d22890>
    Prep: True
    2023-01-22 16:23:15,656:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * apache
    Description: Apache Web Server plugin
    Interfaces: Authenticator, Installer, Plugin
    Entry point: apache = certbot_apache._internal.entrypoint:ENTRYPOINT
    Initialized: <certbot_apache._internal.override_darwin.DarwinConfigurator object at 0x104d22890>
    Prep: True
    2023-01-22 16:23:15,656:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_apache._internal.override_darwin.DarwinConfigurator object at 0x104d22890> and installer <certbot_apache._internal.override_darwin.DarwinConfigurator object at 0x104d22890>
    2023-01-22 16:23:15,656:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator apache, Installer apache
    2023-01-22 16:23:15,722:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://localhost:14000/my-account/158fbbf0f270a354', new_authzr_uri=None, terms_of_service=None), 323b7912532aa5fbb9fc4b6478a2e940, Meta(creation_dt=datetime.datetime(2023, 1, 22, 5, 16, 54, tzinfo=<UTC>), creation_host='1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa', register_to_eff=None))>
    2023-01-22 16:23:15,729:DEBUG:acme.client:Sending GET request to https://localhost:14000/dir.
    2023-01-22 16:23:15,734:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): localhost:14000
    2023-01-22 16:23:15,740:DEBUG:urllib3.connectionpool:https://localhost:14000 "GET /dir HTTP/1.1" 200 406
    2023-01-22 16:23:15,741:DEBUG:acme.client:Received response:
    HTTP 200
    Cache-Control: public, max-age=0, no-cache
    Content-Type: application/json; charset=utf-8
    Date: Sun, 22 Jan 2023 05:23:15 GMT
    Content-Length: 406

    {
    "keyChange": "https://localhost:14000/rollover-account-key",
    "meta": {
        "externalAccountRequired": false,
        "termsOfService": "data:text/plain,Do%20what%20thou%20wilt"
    },
    "newAccount": "https://localhost:14000/sign-me-up",
    "newNonce": "https://localhost:14000/nonce-plz",
    "newOrder": "https://localhost:14000/order-plz",
    "revokeCert": "https://localhost:14000/revoke-cert"
    }
    2023-01-22 16:23:15,741:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for example.com
    2023-01-22 16:23:15,745:DEBUG:acme.client:Requesting fresh nonce
    2023-01-22 16:23:15,745:DEBUG:acme.client:Sending HEAD request to https://localhost:14000/nonce-plz.
    2023-01-22 16:23:15,746:DEBUG:urllib3.connectionpool:https://localhost:14000 "HEAD /nonce-plz HTTP/1.1" 200 0
    2023-01-22 16:23:15,746:DEBUG:acme.client:Received response:
    HTTP 200
    Cache-Control: public, max-age=0, no-cache
    Link: <https://localhost:14000/dir>;rel="index"
    Replay-Nonce: uGJdVFCCUfY9GPde5dj1JQ
    Date: Sun, 22 Jan 2023 05:23:15 GMT

    2023-01-22 16:23:15,746:DEBUG:acme.client:Storing nonce: uGJdVFCCUfY9GPde5dj1JQ
    2023-01-22 16:23:15,746:DEBUG:acme.client:JWS payload:
    b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "example.com"\n    }\n  ]\n}'
    2023-01-22 16:23:15,750:DEBUG:acme.client:Sending POST request to https://localhost:14000/order-plz:
    {
    "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vbG9jYWxob3N0OjE0MDAwL215LWFjY291bnQvMTU4ZmJiZjBmMjcwYTM1NCIsICJub25jZSI6ICJ1R0pkVkZDQ1VmWTlHUGRlNWRqMUpRIiwgInVybCI6ICJodHRwczovL2xvY2FsaG9zdDoxNDAwMC9vcmRlci1wbHoifQ",
    "signature": "QlnWcufTXsPK4_XEU6n9U6MJE4Fo6-yzoPWIoxcPTryRln96AGURJ_EZcrDqxdoQquAXo9taSrPQi-1mK0znlZj282JlrCoylT15Ma0MyogneYp0sUzRX1SGoTrmkREHqJQT1FXyriNsm9yvvis7cQJr-CFXtdt5IopWPnsP-yAgfRJGo4YUgji9CDC-gyYX517ljjgwl-7F8oeYZ1BY71l277fRhcF_MWlhrzU5wPMNLQsXeyofaA_Jft-hrDDQkwq2At5zakmr7QCR5Bu5Uc2a2e10cvRLvrAllPrkAp0cLBZIBldjF74LN_3zDNrH_6vD1OR310326qkUNwx7zw",
    "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogImV4YW1wbGUuY29tIgogICAgfQogIF0KfQ"
    }
    2023-01-22 16:23:15,752:DEBUG:urllib3.connectionpool:https://localhost:14000 "POST /order-plz HTTP/1.1" 201 374
    2023-01-22 16:23:15,752:DEBUG:acme.client:Received response:
    HTTP 201
    Cache-Control: public, max-age=0, no-cache
    Content-Type: application/json; charset=utf-8
    Link: <https://localhost:14000/dir>;rel="index"
    Location: https://localhost:14000/my-order/W5vQgp2Nubp_vREAEYiotZcW63G-JyfpX_d1GjSWMLE
    Replay-Nonce: wuA0NBHnX48lUxli-ofT2Q
    Date: Sun, 22 Jan 2023 05:23:15 GMT
    Content-Length: 374

    {
    "status": "pending",
    "expires": "2023-01-23T05:23:15Z",
    "identifiers": [
        {
            "type": "dns",
            "value": "example.com"
        }
    ],
    "finalize": "https://localhost:14000/finalize-order/W5vQgp2Nubp_vREAEYiotZcW63G-JyfpX_d1GjSWMLE",
    "authorizations": [
        "https://localhost:14000/authZ/TFPuvlzOZYCCVUtrubt8aKnKaU-KNpZaJ8TCP-ERkCM"
    ]
    }
    2023-01-22 16:23:15,752:DEBUG:acme.client:Storing nonce: wuA0NBHnX48lUxli-ofT2Q
    2023-01-22 16:23:15,752:DEBUG:acme.client:JWS payload:
    b''
    2023-01-22 16:23:15,753:DEBUG:acme.client:Sending POST request to https://localhost:14000/authZ/TFPuvlzOZYCCVUtrubt8aKnKaU-KNpZaJ8TCP-ERkCM:
    {
    "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vbG9jYWxob3N0OjE0MDAwL215LWFjY291bnQvMTU4ZmJiZjBmMjcwYTM1NCIsICJub25jZSI6ICJ3dUEwTkJIblg0OGxVeGxpLW9mVDJRIiwgInVybCI6ICJodHRwczovL2xvY2FsaG9zdDoxNDAwMC9hdXRoWi9URlB1dmx6T1pZQ0NWVXRydWJ0OGFLbkthVS1LTnBaYUo4VENQLUVSa0NNIn0",
    "signature": "tjDyf2vNmg5JkENAbm04Ll06Z8kJeQDN4t81OeHpe_qqIebP-ik3R8b6pRRjwfL3kSyow9vpQyDUEgW-u73bOGt2bLB49SOn7B_PXHLxMo9Dw8QpgTMmxRuvUnOKE0AZq0Sy5HawDF0mqwZ3q1Y5sar4jz7_fjmshVGRCAIEhfb8nquRYLvLNe2PRSVHwgTCN4JNqm724fDKfOWC-mdmcOmh6vVRDJxHX8JaK0P5_2OQhtfjfUB0FefSVya9O8t7RyHh4Rgu1X3NmmzWBGmWBohVFfHiv3OpfYZ6UFNdI5yE_rR8LbhOZo9DR6X8gR0QvQknH9j_Q8KfKRRhJCUIKA",
    "payload": ""
    }
    2023-01-22 16:23:15,754:DEBUG:urllib3.connectionpool:https://localhost:14000 "POST /authZ/TFPuvlzOZYCCVUtrubt8aKnKaU-KNpZaJ8TCP-ERkCM HTTP/1.1" 200 862
    2023-01-22 16:23:15,754:DEBUG:acme.client:Received response:
    HTTP 200
    Cache-Control: public, max-age=0, no-cache
    Content-Type: application/json; charset=utf-8
    Link: <https://localhost:14000/dir>;rel="index"
    Replay-Nonce: P0ddbOu8Ls73qCZvoweYxQ
    Date: Sun, 22 Jan 2023 05:23:15 GMT
    Content-Length: 862

    {
    "status": "pending",
    "identifier": {
        "type": "dns",
        "value": "example.com"
    },
    "challenges": [
        {
            "type": "dns-01",
            "url": "https://localhost:14000/chalZ/rKauC1o-0NHSLLbo3k38wjRxJu1Max1ARFkfL_lYKI4",
            "token": "Im5XWJNVQcSPqDgTS5IkC_s2E8xv40g8JXIbeqmSWO0",
            "status": "pending"
        },
        {
            "type": "tls-alpn-01",
            "url": "https://localhost:14000/chalZ/nnYjvF9brsUQj5dPLbqr2_TtAGgYHF9MaOglkJx_ngo",
            "token": "SHgVe_5HDv2udM8Gd7PD8IqBaCwC8bHBPknd9Jenl-0",
            "status": "pending"
        },
        {
            "type": "http-01",
            "url": "https://localhost:14000/chalZ/OZtWHICO1rrEtGHhtGydSRd-NAaTWZVcFB5aXd6zLgo",
            "token": "M2XN9Kak0wtLO8mC4rgI_ZSDl5S8NgmLsvkE_NhJ-q4",
            "status": "pending"
        }
    ],
    "expires": "2023-01-22T06:23:15Z"
    }
    2023-01-22 16:23:15,755:DEBUG:acme.client:Storing nonce: P0ddbOu8Ls73qCZvoweYxQ
    2023-01-22 16:23:15,755:INFO:certbot._internal.auth_handler:Performing the following challenges:
    2023-01-22 16:23:15,755:INFO:certbot._internal.auth_handler:http-01 challenge for example.com
    2023-01-22 16:23:15,756:DEBUG:certbot_apache._internal.http_01:Adding a temporary challenge validation Include for name: example.com in: /private/etc/apache2/other/vhost.conf
    2023-01-22 16:23:15,757:DEBUG:certbot_apache._internal.http_01:writing a pre config file with text:
            RewriteEngine on
            RewriteRule ^/\.well-known/acme-challenge/([A-Za-z0-9-_=]+)$ /var/lib/letsencrypt/http_challenges/$1 [END]
        
    2023-01-22 16:23:15,757:DEBUG:certbot_apache._internal.http_01:writing a post config file with text:
            <Directory /var/lib/letsencrypt/http_challenges>
                Require all granted
            </Directory>
            <Location /.well-known/acme-challenge>
                Require all granted
            </Location>
        
    2023-01-22 16:23:15,761:DEBUG:certbot.reverter:Creating backup of /private/etc/apache2/other/vhost.conf
    2023-01-22 16:23:15,819:ERROR:certbot.util:Error while running apachectl configtest.

    AH00526: Syntax error on line 1 of /private/etc/apache2/other/le_http_01_challenge_pre.conf:
    Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

    2023-01-22 16:23:15,820:DEBUG:certbot._internal.error_handler:Encountered exception:
    Traceback (most recent call last):
    File "/Users/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 2399, in config_test
        util.run_script(self.options.conftest_cmd)
    File "/Users/alex/devel/certbot/certbot/certbot/util.py", line 126, in run_script
        raise errors.SubprocessError(msg)
    certbot.errors.SubprocessError: Error while running apachectl configtest.

    AH00526: Syntax error on line 1 of /private/etc/apache2/other/le_http_01_challenge_pre.conf:
    Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/Users/alex/devel/certbot/certbot/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
        resps = self.auth.perform(achalls)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 2480, in perform
        self.restart()
    File "/Users/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 2364, in restart
        self.config_test()
    File "/Users/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 2401, in config_test
        raise errors.MisconfigurationError(str(err))
    certbot.errors.MisconfigurationError: Error while running apachectl configtest.

    AH00526: Syntax error on line 1 of /private/etc/apache2/other/le_http_01_challenge_pre.conf:
    Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

    2023-01-22 16:23:15,820:DEBUG:certbot._internal.error_handler:Calling registered functions
    2023-01-22 16:23:15,820:INFO:certbot._internal.auth_handler:Cleaning up challenges
    2023-01-22 16:23:15,976:DEBUG:certbot._internal.log:Exiting abnormally:
    Traceback (most recent call last):
    File "/Users/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 2399, in config_test
        util.run_script(self.options.conftest_cmd)
    File "/Users/alex/devel/certbot/certbot/certbot/util.py", line 126, in run_script
        raise errors.SubprocessError(msg)
    certbot.errors.SubprocessError: Error while running apachectl configtest.

    AH00526: Syntax error on line 1 of /private/etc/apache2/other/le_http_01_challenge_pre.conf:
    Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/Users/alex/devel/certbot/venv/bin/certbot", line 33, in <module>
        sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/alex/devel/certbot/certbot/certbot/main.py", line 19, in main
        return internal_main.main(cli_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/alex/devel/certbot/certbot/certbot/_internal/main.py", line 1736, in main
        return config.func(config, plugins)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/alex/devel/certbot/certbot/certbot/_internal/main.py", line 1590, in certonly
        lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/alex/devel/certbot/certbot/certbot/_internal/main.py", line 138, in _get_and_save_cert
        lineage = le_client.obtain_and_enroll_certificate(domains, certname)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/alex/devel/certbot/certbot/certbot/_internal/client.py", line 516, in obtain_and_enroll_certificate
        cert, chain, key, _ = self.obtain_certificate(domains)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/alex/devel/certbot/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
        orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/alex/devel/certbot/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
        authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/alex/devel/certbot/certbot/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
        resps = self.auth.perform(achalls)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 2480, in perform
        self.restart()
    File "/Users/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 2364, in restart
        self.config_test()
    File "/Users/alex/devel/certbot/certbot-apache/certbot_apache/_internal/configurator.py", line 2401, in config_test
        raise errors.MisconfigurationError(str(err))
    certbot.errors.MisconfigurationError: Error while running apachectl configtest.

    AH00526: Syntax error on line 1 of /private/etc/apache2/other/le_http_01_challenge_pre.conf:
    Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

    2023-01-22 16:23:15,978:ERROR:certbot._internal.log:Error while running apachectl configtest.

    AH00526: Syntax error on line 1 of /private/etc/apache2/other/le_http_01_challenge_pre.conf:
    Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration

**Comment by rodrymbo** [comment]
I'm having the same error except for vhosts.d location ("AH00526: Syntax error on line 1 of /etc/apache2/vhosts.d/le_http_01_challenge_pre.conf: Invalid command 'RewriteEngine', perhaps misspelled or defined by a module not included in the server configuration") on Tumbleweed/Apache2.  

I was hoping I could find the text of le_http_01_challenge_pre.conf here in the source and see what it is trying to do, but that's not turning out to be simple. 

I've confirmed that the mod_rewrite module is not loaded via conf file. I've been looking to find if there is a rationale for that, since other times I've loaded Apache, mod_rewrite is loaded or at worst commented out in the configuration. On this install, it's nowhere in the conf files that grep can find ... though there are copies of the .so file at various locations in the filesystem. 

Anyway, it might be easier to debug something like this if the offending conf file had its extension renamed (e.g. from .conf to .error or something) instead of the file and its directory being deleted? It might also be good to include in the installation docs that this functionality of certbot requires apache's mod_rewrite (or whatever it is called this week) and what to do if it is not included. Or if it is part of the Apache plugin, maybe its installer could complain if the module isn't configured?

Anyway, the point is that I have been able to reproduce this several times this week on the latest tumbleweed with a new install from the default repos. It could be something with the distro, but I thought I'd point out here that I did encounter it. And of course, since Tumbleweed changes a lot, no telling whether it will have the same problem in a few weeks with a fresh install from the repos.
