### ISSUE TITLE
Plugin dns-google does not work if certbot is running in GCP CloudShell environment

### ISSUE THREAD

**Issue by TheRealSpaceShip** [certbot/certbot#9583]
I'm trying to get certificates for my tests with the help of certbot running it in the GCP CloudShell environment. 
I don't want to create ServiceAccount for this purpose and assume that the dns-google plugin will obtain info from the metadata server. But it seems like there is a bug where dns-google plugin could not get the `project id` from the metadata server if it's running in CloudShell.

## My operating system is (include version):
uname -a
Linux cs-325246420689-default 5.15.65+ #1 SMP Sat Jan 21 10:12:05 UTC 2023 x86_64 GNU/Linux

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
pip

## I ran this command and it produced this output:

Command (email is redacted):

```shell
pip install certbot certbot-dns-google
mkdir "$HOME/certbot"
export $USER_EMAIL="igor_lysak@example.com"
certbot certonly \
  --config-dir "$HOME/certbot" \
  --work-dir "$HOME/certbot" \
  --logs-dir "$HOME/certbot" \
  --preferred-challenges dns \
  --noninteractive \
  --email "$USER_EMAIL" \
  --agree-tos \
  --staging \
  --dns-google \
  --domain "example.com" \
  --domain "*.example.com"
```

Output:

```text
Saving debug log to /home/igor_lysak/certbot/letsencrypt.log
Requesting a certificate for example.com and *.example.com
Error finding zone. Skipping cleanup.
Error finding zone. Skipping cleanup.
Encountered error finding managed zone: <HttpError 400 when requesting https://dns.googleapis.com/dns/v1/projects//managedZones?dnsName=example.com.&alt=json returned "Invalid resource field value in the request.". Details: "[{'message': 'Invalid resource field value in the request.', 'domain': 'global', 'reason': 'invalidParameter'}]">
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /home/igor_lysak/certbot/letsencrypt.log or re-run Certbot with -v for more details.
```

## Certbot's behavior differed from what I expected because:

After some investigation, I have found that in [dns_google.py#L95 _GoogleClient constructor](https://github.com/certbot/certbot/blob/master/certbot-dns-google/certbot_dns_google/_internal/dns_google.py#L95) method `get_project_id()` returns empty string in CloudShell environment and this leads to failure of requesting resources via GCP API. In my opinion, it should fall back to the `gcloud` default configuration.

## Here is a Certbot log showing the issue (if available):

Domain name and communication with `api.letsencrypt.org` redacted.

```logs
2023-02-15 12:17:00,052:DEBUG:certbot._internal.main:certbot version: 2.2.0
2023-02-15 12:17:00,053:DEBUG:certbot._internal.main:Location of certbot entry point: /home/igor_lysak/.local/bin/certbot
2023-02-15 12:17:00,053:DEBUG:certbot._internal.main:Arguments: ['--config-dir', '/home/igor_lysak/certbot', '--work-dir', '/home/igor_lysak/certbot', '--logs-dir', '/home/igor_lysak/certbot', '--preferred-challenges', 'dns', '--noninteractive', '--email', 'igor_lysak@example.com', '--agree-tos', '--staging', '--dns-google', '--domain', 'example.com', '--domain', '*.example.com']
2023-02-15 12:17:00,053:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-google,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-02-15 12:17:00,066:DEBUG:certbot._internal.log:Root logging level set at 30
2023-02-15 12:17:00,068:DEBUG:certbot._internal.plugins.selection:Requested authenticator dns-google and installer None
2023-02-15 12:17:00,075:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * dns-google
Description: Obtain certificates using a DNS TXT record (if you are using Google Cloud DNS for DNS).
Interfaces: Authenticator, Plugin
Entry point: dns-google = certbot_dns_google._internal.dns_google:Authenticator
Initialized: <certbot_dns_google._internal.dns_google.Authenticator object at 0x7f69f0c3a790>
Prep: True
2023-02-15 12:17:00,076:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_google._internal.dns_google.Authenticator object at 0x7f69f0c3a790> and installer None
2023-02-15 12:17:00,076:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator dns-google, Installer None
...[redacted]
2023-02-15 12:17:01,371:INFO:certbot._internal.auth_handler:Performing the following challenges:
2023-02-15 12:17:01,371:INFO:certbot._internal.auth_handler:dns-01 challenge for example.com
2023-02-15 12:17:01,371:INFO:certbot._internal.auth_handler:dns-01 challenge for example.com
2023-02-15 12:17:01,381:DEBUG:google.auth._default:Checking None for explicit credentials as part of auth process...
2023-02-15 12:17:01,381:DEBUG:google.auth._default:Checking Cloud SDK credentials as part of auth process...
2023-02-15 12:17:01,382:DEBUG:google.auth._default:Cloud SDK credentials not found on disk; not using them
2023-02-15 12:17:01,383:DEBUG:google.auth.transport._http_client:Making request: GET http://169.254.169.254
2023-02-15 12:17:01,388:DEBUG:google.auth.transport._http_client:Making request: GET http://169.254.169.254/computeMetadata/v1/project/project-id
2023-02-15 12:17:01,394:DEBUG:googleapiclient.discovery:URL being requested: GET https://dns.googleapis.com/dns/v1/projects//managedZones?dnsName=example.com.&alt=json
2023-02-15 12:17:01,394:DEBUG:google_auth_httplib2:Making request: GET http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/?recursive=true
2023-02-15 12:17:01,396:DEBUG:google_auth_httplib2:Making request: GET http://169.254.169.254/computeMetadata/v1/instance/service-accounts/igor_lysak@example.com/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform.read-only%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readonly%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readwrite
2023-02-15 12:17:01,520:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot_dns_google/_internal/dns_google.py", line 281, in _find_managed_zone_id
    response = request.execute()
  File "/usr/local/lib/python3.9/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://dns.googleapis.com/dns/v1/projects//managedZones?dnsName=example.com.&alt=json returned "Invalid resource field value in the request.". Details: "[{'message': 'Invalid resource field value in the request.', 'domain': 'global', 'reason': 'invalidParameter'}]">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot_dns_google/_internal/dns_google.py", line 67, in _perform
    self._get_google_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot_dns_google/_internal/dns_google.py", line 116, in add_txt_record
    zone_id = self._find_managed_zone_id(domain)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot_dns_google/_internal/dns_google.py", line 284, in _find_managed_zone_id
    raise errors.PluginError('Encountered error finding managed zone: {0}'
certbot.errors.PluginError: Encountered error finding managed zone: <HttpError 400 when requesting https://dns.googleapis.com/dns/v1/projects//managedZones?dnsName=example.com.&alt=json returned "Invalid resource field value in the request.". Details: "[{'message': 'Invalid resource field value in the request.', 'domain': 'global', 'reason': 'invalidParameter'}]">

2023-02-15 12:17:01,520:DEBUG:certbot._internal.error_handler:Calling registered functions
2023-02-15 12:17:01,520:INFO:certbot._internal.auth_handler:Cleaning up challenges
2023-02-15 12:17:01,527:DEBUG:google.auth._default:Checking None for explicit credentials as part of auth process...
2023-02-15 12:17:01,527:DEBUG:google.auth._default:Checking Cloud SDK credentials as part of auth process...
2023-02-15 12:17:01,527:DEBUG:google.auth._default:Cloud SDK credentials not found on disk; not using them
2023-02-15 12:17:01,528:DEBUG:google.auth.transport._http_client:Making request: GET http://169.254.169.254
2023-02-15 12:17:01,534:DEBUG:google.auth.transport._http_client:Making request: GET http://169.254.169.254/computeMetadata/v1/project/project-id
2023-02-15 12:17:01,542:DEBUG:googleapiclient.discovery:URL being requested: GET https://dns.googleapis.com/dns/v1/projects//managedZones?dnsName=example.com.&alt=json
2023-02-15 12:17:01,542:DEBUG:google_auth_httplib2:Making request: GET http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/?recursive=true
2023-02-15 12:17:01,545:DEBUG:google_auth_httplib2:Making request: GET http://169.254.169.254/computeMetadata/v1/instance/service-accounts/igor_lysak@example.com/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform.read-only%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readonly%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readwrite
2023-02-15 12:17:01,661:WARNING:certbot_dns_google._internal.dns_google:Error finding zone. Skipping cleanup.
2023-02-15 12:17:01,666:DEBUG:google.auth._default:Checking None for explicit credentials as part of auth process...
2023-02-15 12:17:01,666:DEBUG:google.auth._default:Checking Cloud SDK credentials as part of auth process...
2023-02-15 12:17:01,666:DEBUG:google.auth._default:Cloud SDK credentials not found on disk; not using them
2023-02-15 12:17:01,666:DEBUG:google.auth.transport._http_client:Making request: GET http://169.254.169.254
2023-02-15 12:17:01,671:DEBUG:google.auth.transport._http_client:Making request: GET http://169.254.169.254/computeMetadata/v1/project/project-id
2023-02-15 12:17:01,675:DEBUG:googleapiclient.discovery:URL being requested: GET https://dns.googleapis.com/dns/v1/projects//managedZones?dnsName=example.com.&alt=json
2023-02-15 12:17:01,676:DEBUG:google_auth_httplib2:Making request: GET http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/?recursive=true
2023-02-15 12:17:01,678:DEBUG:google_auth_httplib2:Making request: GET http://169.254.169.254/computeMetadata/v1/instance/service-accounts/igor_lysak@example.com/token?scopes=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform.read-only%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readonly%2Chttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fndev.clouddns.readwrite
2023-02-15 12:17:01,793:WARNING:certbot_dns_google._internal.dns_google:Error finding zone. Skipping cleanup.
2023-02-15 12:17:01,793:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot_dns_google/_internal/dns_google.py", line 281, in _find_managed_zone_id
    response = request.execute()
  File "/usr/local/lib/python3.9/dist-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://dns.googleapis.com/dns/v1/projects//managedZones?dnsName=example.com.&alt=json returned "Invalid resource field value in the request.". Details: "[{'message': 'Invalid resource field value in the request.', 'domain': 'global', 'reason': 'invalidParameter'}]">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igor_lysak/.local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot/_internal/main.py", line 1736, in main
    return config.func(config, plugins)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot/_internal/main.py", line 1590, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot/_internal/main.py", line 138, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot/_internal/client.py", line 516, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot/plugins/dns_common.py", line 76, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot_dns_google/_internal/dns_google.py", line 67, in _perform
    self._get_google_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot_dns_google/_internal/dns_google.py", line 116, in add_txt_record
    zone_id = self._find_managed_zone_id(domain)
  File "/home/igor_lysak/.local/lib/python3.9/site-packages/certbot_dns_google/_internal/dns_google.py", line 284, in _find_managed_zone_id
    raise errors.PluginError('Encountered error finding managed zone: {0}'
certbot.errors.PluginError: Encountered error finding managed zone: <HttpError 400 when requesting https://dns.googleapis.com/dns/v1/projects//managedZones?dnsName=example.com.&alt=json returned "Invalid resource field value in the request.". Details: "[{'message': 'Invalid resource field value in the request.', 'domain': 'global', 'reason': 'invalidParameter'}]">
2023-02-15 12:17:01,794:ERROR:certbot._internal.log:Encountered error finding managed zone: <HttpError 400 when requesting https://dns.googleapis.com/dns/v1/projects//managedZones?dnsName=example.com.&alt=json returned "Invalid resource field value in the request.". Details: "[{'message': 'Invalid resource field value in the request.', 'domain': 'global', 'reason': 'invalidParameter'}]">
```

**Comment by alexzorin** [comment]
So the metadata server returns an empty-bodied HTTP 200 for the project-id, but then apparently you're meant to look to see if `GOOGLE_CLOUD_PROJECT` is set. 🤔

Is running Certbot in Cloud Shell useful and something future users are likely to do? Owing to its lack of permanency and persistence, it seems suitable to a throwaway invocation of Certbot, which is not a use case that we're likely to claim support for or test against.

**Comment by TheRealSpaceShip** [comment]
I see your point. In case, when the primary usage of Certbot is to be run as part of some automation there is nothing to do. This is undoubtedly a throwaway invocation of Certbot in the Cloud Shell environment. Thanks for the clarification.
