### ISSUE TITLE
EPEL RPM / RHEL7 / ImportError: cannot import name PROTOCOL_TLS

### ISSUE THREAD

**Issue by driskell** [certbot/certbot#9727]
## My operating system is (include version):
RedHat Enterprise Linux 7.9

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):
EPEL repository / RPM

## I ran this command and it produced this output:
```
# certbot
An unexpected error occurred:
ImportError: cannot import name PROTOCOL_TLS
Please see the logfile '/tmp/tmpxyrTML/log' for more details.
# cat /tmp/tmpxyrTML/log
2022-04-07 12:10:52,605:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/bin/certbot", line 9, in <module>
    load_entry_point('certbot==1.11.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 15, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/main.py", line 1383, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib/python2.7/site-packages/certbot/_internal/plugins/disco.py", line 236, in find_all
    plugin_ep = cls._load_entry_point(entry_point, plugins, with_prefix=False)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/plugins/disco.py", line 254, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point, with_prefix)
  File "/usr/lib/python2.7/site-packages/certbot/_internal/plugins/disco.py", line 56, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/certbot_dns_route53/authenticator.py", line 7, in <module>
    from certbot_dns_route53._internal import dns_route53
  File "/usr/lib/python2.7/site-packages/certbot_dns_route53/_internal/dns_route53.py", line 6, in <module>
    import boto3
  File "/usr/lib/python2.7/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/usr/lib/python2.7/site-packages/boto3/session.py", line 19, in <module>
    import botocore.session
  File "/usr/lib/fence-agents/bundled/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/usr/lib/fence-agents/bundled/botocore/credentials.py", line 34, in <module>
    from botocore.config import Config
  File "/usr/lib/fence-agents/bundled/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/usr/lib/fence-agents/bundled/botocore/endpoint.py", line 22, in <module>
    from botocore.awsrequest import create_request_object
  File "/usr/lib/fence-agents/bundled/botocore/awsrequest.py", line 24, in <module>
    import botocore.utils
  File "/usr/lib/fence-agents/bundled/botocore/utils.py", line 32, in <module>
    import botocore.httpsession
  File "/usr/lib/fence-agents/bundled/botocore/httpsession.py", line 10, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name PROTOCOL_TLS
2022-04-07 12:10:52,605:ERROR:certbot._internal.log:An unexpected error occurred:
2022-04-07 12:10:52,605:ERROR:certbot._internal.log:ImportError: cannot import name PROTOCOL_TLS
```

This is reported as a bug due to interactions between python-s3transfer library used elsewhere and urllib3. Details are at RedHat here: https://bugzilla.redhat.com/show_bug.cgi?id=2072990
It was hoped there would be a fix but it seems marked as CANTFIX so dropping the issue here.

Essentially certbot needs to import boto3 first, before urllib3, to ensure that on RedHat 7.9 the urllib3 is correct version to work with newer boto3 packaging with the latest python-s3transfer.

## Certbot's behavior differed from what I expected because:
It crashed

## Here is a Certbot log showing the issue (if available):
N/A

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
N/A

**Comment by alexzorin** [comment]
>Essentially certbot needs to import boto3 first, before urllib3, to ensure that on RedHat 7.9 the urllib3 is correct version to work with newer boto3 packaging with the latest python-s3transfer.

Hi @driskell,

The EPEL7 package for Certbot stopped receiving updates in 2021, because EPEL7 is stuck on Python 2, which we dropped support for a long time ago. There are no upstream changes we could make that would make any difference. Unfortunately it's a CANTFIX for us too.

What you could do is ask the EPEL maintainer for Certbot to create a patch that has the effect you're looking for. Perhaps something in the main entrypoint like:

```python
try:
  import boto3
except:
  pass
```

The other alternative that we recommend for all users is the Certbot snap, which is unaffected by these kinds of issues and would also give you an up-to-date copy of Certbot and its plugins.

**Comment by Catman155** [comment]
Hi. just wanted to let everyone who comes here the fix I did to make it work again on CentOS 7 python2. Remove/move/rename folder `/usr/lib/fence-agents`. This makes sure that certbot can't import this folder anymore which contains bundled dependencies. Then get and install the latest packages manually that are missing. This is the only thing that worked for me. Upgrading from 7 soon :P
