### ISSUE TITLE
Route53 plugin failed to find private zone

### ISSUE THREAD

**Issue by igor-nikiforov** [certbot/certbot#9831]
Since Hashicorp Vault started from 1.14 have ACME support I tried to configure it with dns-01 validation and found that if I'm using private hosted zone in Route53 for some reason plugin cannot find it.

## My operating system is (include version):
Ubuntu 20.04

## I installed Certbot with (snap, OS package manager, pip, certbot-auto, etc):

Installed with pip3:
```
certbot --version
certbot 2.7.3
```

## I ran this command and it produced this output:

I'm trying to get certificate for private zone `corp.internal`:
```
certbot certonly -n -v \
    --dns-route53 \
    --server https://vault.corp.internal/v1/corp-intermediate-ca/acme/directory \
    --eab-kid e6f40030-66d6-1db5-9e3a-853a07258dfc \
    --eab-hmac-key vault-eab-0-CLOvLzqgNdxTobaiFtwc86YbleFWEosR6qZTKuyYOxM \
    --agree-tos \
    --email ops@corp.com \
    --domains "test.corp.internal"
```

And it producing this:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Found credentials in environment variables.
Plugins selected: Authenticator dns-route53, Installer None
Requesting a certificate for test.corp.internal
Performing the following challenges:
dns-01 challenge for test.corp.internal
Cleaning up challenges
Encountered exception during recovery: certbot.errors.PluginError: Unable to find a Route53 hosted zone for _acme-challenge.test.corp.internal
Unable to find a Route53 hosted zone for _acme-challenge.test.corp.internal
```

But if I just change domain to public zone (`corp.cloud`) in the same account it's working:
```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Found credentials in environment variables.
Plugins selected: Authenticator dns-route53, Installer None
Requesting a certificate for corp.cloud
Performing the following challenges:
dns-01 challenge for corp.cloud
Waiting for verification...
Cleaning up challenges
```

Just to confirm that for tests I'm using IAM user with standard full access policy to Route53 - `AmazonRoute53FullAccess`.

## Certbot's behavior differed from what I expected because:
I expect that Route53 private zone will work same as public.

###### Logs are stored in `/var/log/letsencrypt` by default. Feel free to redact domains, e-mail and IP addresses as you see fit.

Looking in logs I see that I received response body with all zones but for some reason private zone filtered from output. Attention to Response body in XML:
```
2023-10-31 23:06:05,222:DEBUG:botocore.parsers:Response headers: {'x-amzn-RequestId': '7a8f731f-2b85-4b8e-b942-ec19c44886c6', 'Content-Type': 'text/xml', 'Content-Length': '832', 'Date': 'Wed, 01 Nov 2023 03:06:09 GMT'}
2023-10-31 23:06:05,223:DEBUG:botocore.parsers:Response body:
b'<?xml version="1.0"?>\n<ListHostedZonesResponse xmlns="https://route53.amazonaws.com/doc/2013-04-01/"><HostedZones><HostedZone><Id>/hostedzone/Z07709401GQPDCHL7XXXX</Id><Name>corp.cloud.</Name><CallerReference>d0331d0f-9900-42d7-b8e0-d8cfc756d861</CallerReference><Config><Comment>Corp Public Zone</Comment><PrivateZone>false</PrivateZone></Config><ResourceRecordSetCount>46</ResourceRecordSetCount></HostedZone><HostedZone><Id>/hostedzone/Z037552112VOZN270XXXX</Id><Name>corp.internal.</Name><CallerReference>terraform-20201225093221494200000001</CallerReference><Config><Comment>Corp Private Zone</Comment><PrivateZone>true</PrivateZone></Config><ResourceRecordSetCount>758</ResourceRecordSetCount></HostedZone></HostedZones><IsTruncated>false</IsTruncated><MaxItems>100</MaxItems></ListHostedZonesResponse>'
2023-10-31 23:06:05,225:DEBUG:botocore.hooks:Event needs-retry.route-53.ListHostedZones: calling handler <botocore.retryhandler.RetryHandler object at 0x7f191c221b20>
2023-10-31 23:06:05,226:DEBUG:botocore.retryhandler:No retry needed.
2023-10-31 23:06:05,228:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/local/lib/python3.8/dist-packages/certbot_dns_route53/_internal/dns_route53.py", line 71, in perform
    change_ids = [
  File "/usr/local/lib/python3.8/dist-packages/certbot_dns_route53/_internal/dns_route53.py", line 72, in <listcomp>
    self._change_txt_record("UPSERT",
  File "/usr/local/lib/python3.8/dist-packages/certbot_dns_route53/_internal/dns_route53.py", line 122, in _change_txt_record
    zone_id = self._find_zone_id_for_domain(validation_domain_name)
  File "/usr/local/lib/python3.8/dist-packages/certbot_dns_route53/_internal/dns_route53.py", line 110, in _find_zone_id_for_domain
    raise errors.PluginError(
certbot.errors.PluginError: Unable to find a Route53 hosted zone for _acme-challenge.test.corp.internal
```

**Comment by igor-nikiforov** [comment]
Looking in source code of `_find_zone_id_for_domain` function I think problem in these lines - https://github.com/certbot/certbot/blob/master/certbot-dns-route53/certbot_dns_route53/_internal/dns_route53.py#L102-L103
